- third_party/js.bzl
I'd like to stop pushing the compiled JS to github and instead maintain it on npm. This PR changes the BUILD rule to point to unpkg (a CDN for npm packages) rather than github static content to pull down the same minified JS.
> Download umap-js from unpkg rather than github

- tensorboard/plugins/mesh_visualizer/tf_mesh_dashboard/mesh-loader.js
- tensorboard/plugins/mesh_visualizer/tf_mesh_dashboard/tf-mesh-dashboard.html
There were two problems:
1. dataProvider is not available until component is attached
2. missing dependency to tf-mesh-loader in mesh-dashboard
One minor feature improvements:
- Runs selector now appears below the Point of view section and it now
spans the entire view height.
+cc @podlipensky
> Fix mesh visualizer

- docs/r2/hyperparameter_tuning_with_hparams.ipynb
Summary:
Resolves a docs bug noted here:
<https://github.com/tensorflow/tensorboard/pull/2110#issuecomment-485533043>
Test Plan:
Run this notebook in Colab, and observe that the resulting TensorBoard
instance shows both the static configuration (note human-readable
display names) and per-trial values:
Then, note that `git grep 'import_event' '*.ipynb'` has no matches as of
this commit, and other uses of `git grep import_event` are fallbacks
only.
wchargin-branch: import-event
> docs: update `import_event` in hparams tutorial

- tensorboard/plugins/hparams/api.py
- tensorboard/plugins/hparams/keras.py
- tensorboard/plugins/hparams/keras_test.py
- tensorboard/plugins/hparams/summary_v2.py
- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
This commit adds `hparams` and `hparams_pb`, to write `SessionStartInfo`
summaries for users who do not use the Keras callback.
As with `hparams_config{,_pb}`, this “conceptually” supports notf, but
there is still a transitive dependency through `metadata`.
In the tests, we opt to duplicate some infrastructure code rather than
abstracting over it. Compared to (e.g.) `scalar/summary_test`, our test
matrix has an extra dimension: in addition to “V1 vs. V2” and “op vs.
pb”, we have “`hparams` vs. `hparams_config`”. I couldn’t find an
abstraction whose code reuse outweighed its extra complexity.
These tests caught a bug present in the existing `summary.py` code,
wherein `bool` hparam values are always serialized as `int`s, because in
Python `bool` is a subtype of `int` and so one of …
> hparams: add hparam writing for non-Keras users

- tensorboard/plugins/histogram/BUILD
The test was timing out around in 0.1% runs with the small size.
> Update test size of histograms_plugin_test to medium

- tensorboard/pip_package/BUILD
- tensorboard/plugins/mesh/BUILD
Summary:
Amends #2205 to be consistent with other plugins.
Test Plan:
Pip package smoke test still passes.
wchargin-branch: mesh-library-target
> mesh: explictly define public API, for consistency

- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
tpu_profiler_analysis.proto has been moved from tensorflow/contrib to tensorflow/core/profiler and renamed to profiler_analysis.proto. Therefore, need to update the module import here.
The error message when capturing a profile is lost when responding with error code 400. Change to return a json error message with error code 200, so that it can be shown in the UI.
Also add a spinner when capturing profile. 
> Fix streaming trace viewer and improve error message

- tensorboard/util/test_util.py
Summary:
When the `TF2_BEHAVIOR` environment variable is set, TensorFlow behaves
as if `tf.compat.v1.enable_v2_behavior()` were invoked. In such a case,
we should not run V1-only tests.
We elect to test this by importing a private TensorFlow module rather
than reading the environment variable directly. Both are undocumented,
but the module import will give us a hard failure if it is changed,
while the environment variable will silently change behavior.
This fixes some Google-internal issues (see <http://cl/247294725>). It
should be a no-op externally; we do not set this environment variable.
Resolves #1996.
Test Plan:
Count the number of skipped tests before and after this change:
```
tests="$(bazel query "
tests(rdeps(
//tensorboard/...,
set($(git grep -l run_v._only)) - …
```
> test: skip V1-only tests under TF2 behavior

- tensorboard/pip_package/build_pip_package.sh
- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/metadata.py
- tensorboard/plugins/hparams/summary.py
- tensorboard/plugins/hparams/summary_v2.py
- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
This changes the private `metadata` module to emit TensorBoard protos
instead of TensorFlow protos, removing its dependency on TensorFlow. Its
two clients are updated: we add a reinterpret-cast to one and remove the
cast from the other.
Test Plan:
A new test target runs with `//tensorboard/compat:no_tensorflow`.
Verified that this passes in a virtualenv that actually does not have
TensorFlow installed, skipping only the expected six tests. Smoke test
updated for notf builds; the new smoke test fails before this change.
wchargin-branch: hparams-notf
> hparams: avoid TensorFlow dependency in summary_v2

- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
The test as written may be flaky, according to @nfelt’s comment here:
<https://github.com/tensorflow/tensorboard/pull/2188#discussion_r281431612>
Test Plan:
I couldn’t actually get the previous version of the test to fail (even
with `--runs_per_test=1000`), but it still passes, so that’s nice.
wchargin-branch: hparams-tests-explicit-flush
> hparams: manually flush writer in graph mode tests

- docs/_book.yaml
- docs/r2/tensorboard_profiling_keras.ipynb
Summary:
Per @lamberta via [the Google dev docs style guide][guide], we should
use sentence case for titles and headers, and “prefer italics instead
bold for emphasis” because “bold style tends to conflict with the
h3/h4/h5 styles that devsite uses when skimming the page”.
This commit replaces strong emphasis with emphasis, quotations, or code
spans, as appropriate. Strong emphasis is retained for description list
items and a `**NOTE**:` specifier (changed to `**Note:**` for
consistency with [the same guide][guide]).
This commit is easier to review with `--word-diff`.
[guide]: https://developers.google.com/style/capitalization
Test Plan:
Check that all remaining `**`-sequences are intended:
```
$ grep -F '**' docs/r2/tensorboard_profiling_keras.ipynb | cut -c -40
"*   **CPU**: CPU events …
```
> profile: standardize tutorial style

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
In order for WitWidget to live in a Jupyter notebook without interfering with other widgets that also use Polymer, we need to load it inside an iframe. Otherwise for examples the TFMA visualizations and WitWidget cannot live in the same notebook without failing, due to their vulcanized HTML files for their widgets both containing polymer dependencies (since the browser will fail on the loading of those deps a second time).
Moved WIT HTML element and its vulcanized dependency to inside an iframe.
Updated wit.js code to ensure WIT is fully loaded inside iframe before trying to use it.
Update WIT element to use correct font, as without this, inside iframe it reverts to default browser fonts.
Update WIT element to …
> Move What-If Tool into an iframe in Jupyter widget

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-inference-panel.html
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
Simplify "inference address" mentions in tool/code to not be misleading.
Documentation on how to set inference address can be found in many places (WIT README, WIT website walkthrough, TB website WIT page, ...).
> What-If Tool: simplify inference address documentation

- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
Continuing work on CMLE mode for WitWidget, which has been rebranded to AI Platform by Cloud. Added support for xgboost models in AI Platform as well.
Rename CMLE to AI Platform serving
Allow examples to be provided as JSON lists (which is true for xgboost models), not just JSON dicts.
Allow separate provided of feature names for display when examples are provided as flat lists.
Add better prediction result parsing logic for AI Platform use-case, handling more models out of the box.
Add ability for user to specify custom prediction adjustment function for when the AI Platform model returns results in a format that is unknown to WIT.
N/A
* Detailed steps to verify changes work correctly (as …
> Enable WitWidget for AI Platform including xgboost models

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
To support upcoming WIT integrations, made it possible to change the examples being shown by WitWidget through a method call.
- Changed WitWidget private _set_examples method to public set_examples method.
- Changed colab implementation of set_examples to use BroadcastChannel to allow it to be called in a different colab cell than the one that displays WIT. This is necessary because colab sandboxes each output cell in iframes.
N/A
Installed WitWidget with these changes in colab and jupyter and ran test notebook that displayed initial examples, then in another cell, calls set_examples to change which examples are shown. …
> Allow WitWidget example changing

- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
Repro steps:
1. Select a run that has more than one tags
2. Select a tag with RunMetadata
3. Select a node
4. Select the default tag
5. Click nodes around and see JSEs
We have nested dom-ifs to prevent `getTotalMicros` from being called.
However, this is only effective when the DOM is not mounted but this
assumption does not hold after first render (if=true).
> graph: Fix JSE when switching node selection

- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
This test seems to be fine in open-source land, but failed 18/32 times
within Google, because the wire format order for maps is undefined:
<https://developers.google.com/protocol-buffers/docs/proto3#maps>
Test Plan:
Within google3, cherry-pick this patch onto <http://cl/247655537>, then
run `:summary_v2_notf_test` with `--runs_per_test=128` to check for
flakiness.
wchargin-branch: hparams-test-deflake
> hparams: account for proto nondeterminism in tests

- tensorboard/pip_package/build_pip_package.sh
Summary:
The smoke test doesn’t actually catch those things that it’s supposed to
catch, because it installs `tf-nightly` (or `tf-nightly-2.0-preview`),
which in turn installs `tb-nightly`. We then install the just-built
version of `tensorboard`, so the resulting virtualenv has both
`tensorboard` and `tb-nightly`: #1907 strikes again.
When `--tf-version ""` is passed, this is not an issue, but some smoke
checks only run when that is not passed.
It just so happens that this is currently benign: each of the direct
dependencies of `:build_pip_package` either has no smoke test, contains
an `__init__.py` file that is required to overwrite the Bazel-generated
empty one, because the smoke test references symbols directly in that
file, or is not yet in `tb-nightly`. But (a) starting with …
> pip: fix smoke test double-TensorBoard dependency

- tensorboard/tools/diagnose_me.py
- tensorboard/tools/diagnose_tensorboard.py
Summary:
Users often report problems that depend on environment-specific
configuration. Rather than asking them to find all this information and
enter it into an issue template manually, we can ask them to run a
script and paste its output verbatim into the issue. Furthermore, we can
detect and suggest fixes to common problems, such as #1907 and #2010.
The script can grow as we see fit to add new diagnoses and suggestions.
Test Plan:
The script is designed to be robust to errors in each individual
diagnosis: in the worst case, it prints a stack trace and continues to
the next one. I’ve manually tested that the main framework works in
Python 2 and 3 on Linux and in Python 3 on Windows.
Automated testing of this script is possible, but would take a fair
number of CPU cycles to run tests …
> tools: create `diagnose_tensorboard`

- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/plugins/BUILD
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/video_writing.py
- tensorboard/program.py
Summary:
Fixes #2121.
Test Plan:
$ git grep '__metaclass__' | wc -l
0
wchargin-branch: six-add-metaclass
> Use `six.add_metaclass` for Python 3 compatibility

- WORKSPACE
- tensorboard/plugins/mesh/BUILD
Summary:
Fixes #2181. Thankfully, the `rules_webtesting` scene has gotten a bit
saner, requiring fewer explicitly defined transitive dependencies,
though it looks like the ones that we do have need to be manually kept
in sync (e.g., `bazel_skylib`).
Test Plan:
Running `bazel build //...` and `bazel test //...` works in Bazel 0.25.2
in both Python 2 and Python 3.
wchargin-branch: bazel-0.25
> Fix build for Bazel 0.25

- .travis.yml
- WORKSPACE
- tensorboard/tools/import_google_fonts.py
- third_party/fonts.bzl
- third_party/js.bzl
- third_party/polymer.bzl
- third_party/python.bzl
- third_party/typings.bzl
- third_party/workspace.bzl
Summary:
It’s easier for TensorBoard team members to upload files to the
TensorFlow.org mirror than the Bazel mirror. Many of our files were not
mirrored, and fetches from GitHub can be noticeably slow. (For instance,
the Bazel 0.22.0 binary is 1.8–2.0 seconds from the TF mirror and 8.5–12
seconds from GitHub.) As of this commit, all `mirror.bazel.build` URLs
are replaced with `mirror.tensorflow.org` URLs, and all such URLs
contain valid content.
Along the way, I swapped out the defunct numericjs source to a host that
actually still resolves.
On Travis, getting Bazel and running `bazel fetch //tensorboard/...`
typically takes about 44 seconds. Let’s see if this speeds that up.
Test Plan:
Check that Bazel URLs resolve:
```
$ git grep -Pho '(?<=")https?://mirror\.tensorflow\.org/[^"]*' |
> …
```
> build: use `mirror.tensorflow.org`, now populated

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Minor bug fix: Datapoint id title did not populate correctly when id is 0, because 0 == ''" is true.
I locally ran the web demos and verified that they work correctly.
> Fix datapoint id not displaying correctly for id=0

- tensorboard/plugins/projector/vz_projector/data.ts
> Fix issue where precomputed knn aren't being reused

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/umap.d.ts
While debugging the standalone projector app, we discovered a bug caused by the divergence between the umap-js and the `umap.d.ts` typings that we maintain in this repo. This bug caused an error when initializing very small datasets. This PR fixes the incorrect usage of `umap.initializeFit` and updates the types to match the library.
> Fix issue where we werent initializing knn properly

- tensorboard/plugins/hparams/hparams_demo.py
Summary:
In #2188, I removed the `group_name` parameter from the Keras callback,
but forgot to remove it from the call site in the demo code.
Test Plan:
Running `bazel run //tensorboard/plugins/hparams:hparams_demo` now
works. Previously, it failed with the error, “unexpected keyword
argument 'group_name'”.
wchargin-branch: hparams-demo-no-group-name
> hparams: fix demo (remove `group_name` argument)

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
In certain cases the confusion matrix was missing entries.
Correctly add both the inferred label and the true label to the set of all labels to show in the multiclass confusion matrix, including coercing all labels to strings. 
Verified continued correct working in multiclass demo, and verified correct behavior in multiclass colab notebook that displayed this issue.
> Fix WIT multiclass confusion matrix

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Cloud AI Platform models can have custom prediction code that takes in examples in any format the modeler wants. But WIT requires examples as lists, dicts, or example protos by design. So add the ability to transform examples to the custom format for cloud users that need this capability.
- Add adjust_example function argument to set_ai_platform_model methods, similar to existing adjust_prediction argument.
- Call adjust_example before sending to the model if that argument is passed.
No UI changes.
Ran colab with custom cloud model that needs this capability and verified it works.
> Add ability to customize examples for custom AI platform models

- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
long type does not exist in python 3, changed type testing to six.integer types from long to prevent errors when wit is used with json inputs.
None
Tested cloud xgboost model with python 3 kernel in colab.
None
> Fix long type not found for json input in python3

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Per user requests, adding PR curves and F1 score to performance tab of WIT for binary classification models.
- Adjust chart generation code to handle both PR curves and existing ROC curves
- Change visuals to handle both charts side by side
- Add calculation of precision (positive predictive value) in order to support PR curve.
- Add calculation of F1 score
- Add row in performance table for F1 score
Ran binary classification demos (single and multimodel) to visualize change and ensure correctness.
> Add PR curves and F1 score to WIT

- tensorboard/defs/hacks.bzl
- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
- third_party/polymer.bzl
- third_party/typings.bzl
- third_party/workspace.bzl
Summary:
Changes in #2267 displeased the Google linter: `list(my_depset)` is
banned because it’s not obvious that this forces iteration, so we switch
to the far clearer `.to_list()` everywhere.
The venerable linter further demands that docstrings be added, even for
drive-by fixes.
Test Plan:
A test import succeeds; all Google-internal tests pass.
wchargin-branch: import-lint
> build: fix lint errors

- tensorboard/plugins/profile/pod_viewer/details_card/details-card.html
- tensorboard/plugins/profile/pod_viewer/details_card/details-card.ts
- tensorboard/plugins/profile/pod_viewer/pod_viewer_common/proto.ts
- tensorboard/plugins/profile/pod_viewer/pod_viewer_dashboard/pod-viewer-dashboard.html
- tensorboard/plugins/profile/pod_viewer/pod_viewer_dashboard/pod-viewer-dashboard.ts
- tensorboard/plugins/profile/pod_viewer/stack_bar_chart/stack-bar-chart.ts
- tensorboard/plugins/profile/pod_viewer/topology_graph/BUILD
- tensorboard/plugins/profile/pod_viewer/topology_graph/topology-graph.html
- tensorboard/plugins/profile/pod_viewer/topology_graph/topology-graph.ts
When loading a large trace (~50MB), pod viewer takes a long time to render (>30s) and crashes the browser when changing the step or metric id. This change improves the logic and reduces the rendering and scripting time to ~1s. 
1) Previously send recv links are saved for each replica, which doesn't scale for a 4-way spatial partitioning model on a tpu v3-2048 pod which have 512 replicas. In data processing (c++), we instead only save aggregated stats across all replicas to reduce the result json size. Instead of srcCoreId and dstCoreId for each replica, we save a list of srcCoreIds  and dstCoreIds of all replicas for each channel.
proto.ts reflects this changes.
2) There's another proto change that deprecates …
> Improve the performance and scalability of pod viewer

- tensorboard/components/vz_chart_helpers/BUILD
- tensorboard/components/vz_chart_helpers/plottable-interactions.d.ts
- tensorboard/components/vz_chart_helpers/plottable-interactions.js
- tensorboard/components/vz_line_chart2/line-chart.ts
Plottable interactions are broken with the WebComponents due to its
event delegation and relative position computation -- their DOM
traversal was not compatible with the WebComponents. More information at
https://github.com/palantir/plottable/issues/3350.
Because of visibility (private and protected), it was not viable to
subclass the interactions to fix the issue, so we have decided to monkey
patch the broken functions in JavaScript. In farther future, we may want
to use raw DOM events to handle the interactions instead of using the
Plottable abstraction as it will be very expensive to maintain the monkey
patch.
> Polymer 2: fixed the Plottable interaction

- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
StartTracing API has more options to config how to profile a model. Add that to the capture profile pop up.
1) Add work_list, num_tracing_attempts and include_dataset_ops to the pop up.
2) Trim the string of the ProfilerServiceAddress to remove leading and trailing spaces.
3) Add auto-validate to the input field.
4) Fix a bug that the "_profilerServiceAddress" should be passed into the shouldDisableCaptureProfileButton instead of the "profilerServiceAddress".
bazel run tensorboard/plugins/profile:profile_demo
bazel run tensorboard:tensorboard -- --logdir=/tmp/profile_demo
> Add more options for TPU profiling

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Fixes #2263.
The trace viewer logic was hardcoded to use absolute paths (relative to the hostname), which doesn't work when `--path_prefix` is set.  As far as I can tell there is no particular reason why the trace viewer shouldn't use relative path names like the rest of TensorBoard, and the code that forced the absolute path has been around since the profile plugin was introduced, so I suspect it's just outdated.
Tested by running `tensorboard --path_prefix /mypath/` and then putting nginx in front of it as follows:
```sh
echo 'events {} http { access_log stdout; error_log stderr; server { listen 8080; server_name localhost; proxy_buffering off; location /mypath/ { proxy_pass http://localhost:6006; }}}' > /tmp/nginx.conf && sudo nginx -g 'daemon off;' -/tmp/nginx.conf
```
Confirmed that …
> [profile] make trace viewer respect --path_prefix

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/default.py
- tensorboard/default_test.py
- tensorboard/http_api.md
- tensorboard/main.py
- tensorboard/pip_package/setup.py
- tensorboard/plugins/base_plugin.py
This is the change based on https://github.com/tensorflow/community/pull/90.
The change makes two improvements:
1.  allow dynamic plugins (as spec in the RFC; uses entry_points to discover) to be loaded
2. change `plugins_listing` contract to include metadata about plugins including their respective FE entry point.
Notes on default_test: tried to get this tested end-to-end but setuptools was a bit cumbersome to test. For specifically, `setuptools.setup` cannot be invoked programmatically and it can lead to bad side-effects when not cleaned up properly.
> Extensible plugin infrastructural changes

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
We’d like to serve dashboard registration metadata from the backend, as
will be the case for dynamically loaded plugins. This is straightforward
except for the scalar plugin’s `useDataSelector` bit, which depends on
the query parameter. This patch changes moves the query parameter gating
from the scalar plugin to the core frontend.
Test Plan:
Verify that the following behavior is the same before and after this
change: (a) when the URL has no query parameters, neither the scalars
dashboard nor the images dashboard shows a data selector; and (b) when
the URL has `?EnableDataSelector`, the scalars dashboard has a data
selector and no run selector, while the images dashboard has a run
selector and no data selector.
wchargin-branch: top-level-data-selector-flag
> core: always gate data selector behind query param

- .travis.yml
- ci/bazelrc
- ci/download_bazel.sh
This streamlines and improves our .travis.yml configuration and caching behavior in hopes of reducing our painfully slow Travis builds.  In my testing so far this drops the total time to execute by ~30% (so from 50m total across 3 machines to more like 35m), by shaving a little over 2 minutes off of each of the 6 jobs in our test matrix.
Here's the list of changes I implemented that I felt overall improved speed (or were mixed, but seemed like better practice):
- changed caching approach to use Bazel's properly designed caching APIs
- repository caching for `bazel fetch` results
- remote caching API for build results/artifacts, using local disk backend
- **con:** fetch is slower (60ish seconds instead of 15) - not entirely sure why, but perhaps it doesn't cache all the downloaded results …
> Improve travis.yml config for faster CI

- tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
Default mouse wheel to zoom is rather obnoxious since large area of the
TensorBoard is zoomable area.
Note that preferably we'd want to provide some tooltip or help to make
this feature discoverable but simple hack using `HTMLElement.title` felt very 
disturbing and poor. We, in later time, might want to consider doing what
Google Map does on mobile (when scroll event happens inside the zoomable
area, it shows shows a transparent splash describing how to zoom). Note that
none of these solutions are friendly to the screen reader softwares.
Fixes #2214.
> Zoom with mouse wheel only when alt key is pressed

- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
- tensorboard/plugins/profile/pod_viewer/topology_graph/topology-graph.ts
The tooltip displayed when hovering on image of a pod is positioned suboptimally, this PR position the tooltip better. #2284 
bazel run tensorboard:tensorboard -- --logdir=gs://cloud-tpu-tools
> fix tooltip position

- .travis.yml
- tensorboard/tools/mirror_urls_test.sh
Summary:
This tests that URLs point to the TensorFlow mirror (as opposed to the
Bazel mirror) and that they resolve to valid archives.
Test Plan:
Run `./tensorboard/tools/mirror_urls_test.sh`, and note that it passes
with no output. Then apply the following patch to add some bad URLs:
```diff
diff --git a/WORKSPACE b/WORKSPACE
index 3943b0cf..d3975dfe 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -9,6 +9,9 @@ http_archive(
urls = [
"http://mirror.tensorflow.org/github.com/bazelbuild/bazel-skylib/archive/0.7.0.tar.gz",
+        "http://mirror.tensorflow.org/example.com/nonexistent.txt",
+        "http://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/0.7.0.tar.gz",
+        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/0.7.0.tar.gz", …
```
> test: ensure that build URLs are valid

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
Now that we have only enabled scroll zooming when pressing ALT, we
should provide message indicating that the affordance has changed.
Also changed the panning to also work with the ALT key.
This change augments #2221.
> Add user friendly message when scroll on chart

- tensorboard/plugins/projector/vz_projector/scatterPlotRectangleSelector.ts
For some reason the selector bounding box has disappeared in the embedding projector. This PR fixes it, making it visible again.
Fixes #2195.
> Fix invisible selector box

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
This PR adds the ability to choose which model to use for for counterfactual example computation (Previously, it was computed with respect to first model).
Added a drop-down menu to choose model name in counterfactual settings row. This panel is hidden when there is only one loaded model.
I ran all demos locally and verified that counterfactuals are computed correctly for the chosen model.
> Add option to select which model to use for counterfactual computation

- tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-loader.html
Summary:
The steps slider was supposed to be capped at the number of steps, but
in fact was always capped at 100 due to a typo in the Polymer binding.
Fixes #2270.
Test Plan:
Check out #2265 and run the mesh demo to generate test data. Then,
launch TensorBoard with the mesh data and observe that the slider now
goes from 0 to 9 instead of 0 to 100, and that moving along the entire
range of the slider is now useful.
wchargin-branch: mesh-fix-steps
> mesh: fix steps slider

- WORKSPACE
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Summary:
This pulls in bazelbuild/rules_closure#383 to fix #2297, and integrates
the same fix into our own `Vulcanize.java` for consistency.
This diff includes a jscompiler upgrade from `v20190325` to `v20190528`.
Test Plan:
The `//tensorboard` target still builds and appears to run fine, with
cursory inspection.
Changing the `href` attribute of the help button in `tf-tensorboard` to
`mailto:xxx@yyy.com` now builds and works properly; prior to this
commit, that failed to build, as described in #2297.
wchargin-branch: rules-closure-mailto-fix
> build: upgrade `rules_closure` to HEAD

- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
Update of TB to new closure rules broke the functioning of the witwidget pip package in colab.
Javascript published to colab when using witwidget (in colab/wit.py) was doing work in the global scope, unnecessarily creating global vars that now collide with other vars, leading to JS failures when loading WIT. This javascript should never have used the global scope. This fix moves the work into an anonymous function so as to avoid polluting the global scope.
N/A
Pip install local version with this change and verify that witwidget works again in colab.
Also test locally in Jupyter to ensure it still works there.
> Fix pip package in colab with latest closure libraries

- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/README.md
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/index.js
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/webpack.config.js
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/pip_package/build_pip_package.sh
Update WitWidget packaging/logic to enable it to work in JupyterLab notebooks, which handle extensions like WitWidget differently than standard Jupyter notebooks. This also enables use in Cloud AI Platform notebooks.
Update packaging code to create correct, public NPM package, as the HTML/JS side of lab extensions are NPM packages.
Update witwidget jupyter js code to handle loading wit_jupyter.html from correct packaged location when running in JupyterLab, while keeping the same initial logic for loading that file when in standard Jupyter, as they are different paths.
Update package building script and webpack config to correctly bundle wit_jupyter.html with the NPM package for the JupyterLab extension.
Update …
> Enable WIT usage in JupyterLab/Cloud AI Platform notebooks

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/base_plugin.py
Summary:
The two loading mechanisms are now specified in the same data object, so
switching from one to the other requires only a single change.
The HTTP API and the frontend are unchanged.
Test Plan:
Modify the scalar plugin’s `frontend_metadata` to use an ES module path:
```diff
diff --git a/tensorboard/plugins/scalar/scalars_plugin.py b/tensorboard/plugins/scalar/scalars_plugin.py
index 1b864a74..2e06c86a 100644
--- a/tensorboard/plugins/scalar/scalars_plugin.py
+++ b/tensorboard/plugins/scalar/scalars_plugin.py
@@ -85,7 +85,8 @@ class ScalarsPlugin(base_plugin.TBPlugin):
def frontend_metadata(self):
return super(ScalarsPlugin, self).frontend_metadata()._replace(
-        element_name='tf-scalar-dashboard',
+        #element_name='tf-scalar-dashboard',
+ …
```
> core: move ES module path into `FrontendMetadata`

- tensorboard/plugins/mesh/BUILD
- tensorboard/plugins/mesh/demo_utils_test.py
Summary:
This test case already contains actual TensorFlow code, via the `GFile`
use in the code under test. Within Google, such tests must be run via
`tf.test.main()` or `absltest.main()`, and the TensorFlow-specific code
should be in a `tf.test.TestCase` as well (though this is not strictly
required).
Test Plan:
Verified that this patch fixes a test that’s broken when syncing into
Google3.
wchargin-branch: tf-test-mesh-test
> build: use `tf.test.main` for `mesh:demo_utils_test`

- tensorboard/BUILD
- tensorboard/test.py
Summary:
Within Google, tests that call certain functions must be run via either
`tf.test` or `absltest`. When possible, we’d like to use `absltest` so
that the tests can be run in notf settings. Thus, we change the backing
implementation of `tensorboard.test` from `unittest` to `absltest`.
We retain the `tensorboard.test` layer to add the `get_temp_dir` method,
which is provided by `tf.test` but not `absltest`, and which our tests
often expect to use.
This has the side benefit that we get lots of assertions for free,
including `assertStartsWith`, `assertEndsWith`, and `assertLen`, as well
as fancy ones like `assertSequenceAlmostEqual` and `assertUrlEqual`.
(Unfortunately, we still lack `tf.test`’s `assertProtoEquals`.)
Test Plan:
Existing tests pass. Googlers, see <http://cl/251757823>. …
> test: use `absltest` for `tensorboard.test`

- tensorboard/plugins/interactive_inference/witwidget/BUILD
- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
In WIT, models that accept JSON as input were failing in python 3 notebooks due to how bytes_list protos are handled.
Added wrapper method for handling of objects that in py3 are bytes but in py2 are string (such as bytes_list handling from tf Example proto) to ensure they encoded as strings for use in WIT.
N/A
Ran py3 colab notebook with the offending model with local pip package built with this change and verified that it now works correctly in WIT.
Ran other colab notebooks to verify it didn't cause regressions.
> Fix py3 issue with AI Platform models

- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
Addresses performance issues within Google: <http://b/134690650>. This
speeds up the test by 20–25%.
Test Plan:
That the test still passes suffices.
wchargin-branch: scalars-test-speed
> scalars: speed up test and mark as “medium”

- tensorboard/components/tf_backend/test/requestManagerTests.ts
- tensorboard/components/tf_imports/BUILD
- third_party/typings.bzl
sinon-chai comes preinstalled with web-component-tester.
We can make use of it except it misses the typing information.
> cleanup: add typing for sinon-chai

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Plugins are developed with a relative to its package in mind. Without
setting the baseURI, the iframe has base path of
http[s]://[TBPATH]/[pathPrefix] which forces all relative paths the
plugin uses require 'data/plugin/[name]/' prefix, which is unnatural.
This change sets the base URI of the plugin iframe to
http[s]://[TBPATH]/[pathPrefix]/data/plugin/[name]/.
> Set base URI for plugin iframe

- tensorboard/plugins/projector/vz_projector/scatterPlot.ts
- tensorboard/plugins/projector/vz_projector/scatterPlotVisualizer3DLabels.ts
- tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerPolylines.ts
- tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
- third_party/js.bzl
- Vertex shader require related glsl code block
- other API changes in between
- WebGLRenderer.render no longer takes 4 inputs. Instead, you must set
renderTarget manually.
- BufferAttribute.prototype.count is important and attribute.array is
discourage in favor of setArray
- Types are not updated. 
- DefinitelyType no longer provide the latest
typing of three in favor TypeScript in three.js repo. For the time
being, we have decided not to pursue this as downloading the archive
would fetch unnecessarily large file (examples dir is 300+MB).
- Types in newer DefinitelyTyped and three.js seem to be incompatible
with current build system. https://github.com/stephanwlee/tensorboard/commit/daa35e457ed64cbe1cfe871beceb901377e5ec80
Poked around projector, what-if, and mesh plugins thoroughly.
> infra: upgrade three.js to r104 from r77

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Closure security conformance test guard against almost all instances of
setting .href. Since we will not be using the goog.safe APIs for now, we
will be using setAttribute instead.
Confirm the change with an example plugin.
> infra: use base.setAttribute instead .href

- tensorboard/components/tf_dashboard_common/dashboard-style.html
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
Nature of the bug:
Sidebar tf-runs-selector is a bit trickier in term of layout: its height
depends both on number/size of the content (# of runs) and size of the
viewport (show scrollbar if it does not fit in the sidebar).
To confine the size of the tf-runs-selector w.r.t the height of its
container (whose height is not defined by content but its sibling sizes
which are computed by respective descendents), we need to make each flex
container `overflow: hidden`. `overflow: hidden` makes child and
child-flex-container compute height w.r.t, the flex-container with
`overflow: hidden`.
When run numbers are low, we make tf-runs-selector's height computed
w.r.t. descendent heights by not putting `height: 100%`.
Confirmed the change both on Chrome 75 and Firefox 66.
> Fixed incorrect runs-selector rendering

- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/interactive_debugger_plugin.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.html
- tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
Plugins whose backends are provided via “loaders” rather than the
plugins themselves may fail to load. We still want to allow those
plugins to display a message in the frontend indicating what must be
done to enable them (e.g., update TensorFlow, start a `tfdbg` debugger),
which requires registering their frontends unconditionally.
This is a short-term hack to retain functionality prior to #2304 (with
the minor change that these plugins will now always appear at the end of
the list). We’ll want to replace this with a better mechanism when time
permits.
Fixes #2338.
Test Plan:
Launch TensorBoard without TensorFlow installed and with no flags other
than `--logdir`. Note that the beholder, debugger, hparams, what-if
tool, and profile dashboards all have valid entries in the …
> frontend: reinstate registration for conditional plugins

- .travis.yml
Summary:
This reverts commit 31c00fb586e80cd713492835ebf169915a322a56.
Test Plan:
CI suffices.
wchargin-branch: unpin-20190606-nightly
> ci: unpin 2019-06-06 nightlies

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 1.14.0 release process:
- Bump tb-nightly version to 1.15.0a0
- Cherrypick of 1.14.0 relnotes added to RELEASE.md
> Post-release 1.14.0

- tensorboard/tools/diagnose_tensorboard.py
Summary:
If a TensorBoard installation omits compiled proto bindings, the
`tensorboard.summary._tf.summary` module cannot be imported, which
triggers a TensorFlow warning about a “missing TensorBoard
installation”. We can check for this condition in our self-diagnosis
script.
Test Plan:
From the TensorBoard repository:
```
$ dtb="$(readlink -e ./tensorboard/tools/diagnose_tensorboard.py)"
$ filter() { awk 'ok && /^#/ { exit; }; /###.*Avoid/ { ok = 1; }; ok'; }
$ python "${dtb}" | filter
Your current directory contains a `tensorboard` Python package that
does not include generated files. This can happen if your current
directory includes the TensorBoard source tree (e.g., you are in the
TensorBoard Git repository). Consider changing to a different
directory.
$ …
```
> diagnose: detect missing genfiles

- tensorboard/plugins/base_plugin.py
Summary:
Prior to this change, defining a (possibly dynamically loaded) plugin
without this initializer would yield the rather inscrutable error
```
File "/VIRTUAL_ENV/tensorboard/plugins/base_plugin.py", line 253, in load
return self._plugin_class(context)
TypeError: object() takes no parameters
```
whose stack trace does not contain the offending plugin code at all.
(The error is because initializers are effectively inherited in Python.)
Test Plan:
Cherry-pick #2354, delete its example plugin’s `__init__`, and note that
the example still works. (You’ll have to build TensorBoard’s Pip package
and install it into a virtualenv.)
wchargin-branch: plugin-empty-initializer
> plugins: add initializer on base plugin class

- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/axes.ts
- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/interaction_manager.ts
- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/lines.ts
Common typo catcher caught few things in our recent PR #2223.
Closure type system annotates return type with "@return" instead of
"@returns".
Other extraneous whitespace changes are VIM removing all trailing whitespaces
throughout the file.
> cleanup: fixed few typos.

- .travis.yml
- tensorboard/tools/whitespace_hygiene_test.py
Summary:
Prevents regressions of nice fixes like #2364.
Test Plan:
Run the script, and note that it passes with no output. Then remove
`README.md` from the exceptions list and add `nonexistent.txt`, and
observe that the script fails with:
```
Superfluous trailing whitespace:
README.md:10:For in-depth information on the Graph Visualizer, see this tutorial: $
README.md:18:through setting up and using TensorBoard. There's an associated $
README.md:36:For more details, see $
README.md:69:For this, you need $
Stale exceptions (no whitespace problems; prune exceptions list):
nonexistent.txt
```
wchargin-branch: whitespace-hygiene-test
> ci: add trailing whitespace test

- README.md
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/components/vz_line_chart/dragZoomInteraction.ts
- tensorboard/plugins/projector/projector_plugin.py
Summary:
Their primary account is now @decentralion. The repository link is
forwarded by GitHub, but it’s better for to link to the canonical
address.
Test Plan:
One link is modified; clicking the link works.
Running `git grep -i 'dan\(delion\)\?mane'` returns no results.
wchargin-branch: decentralionize
> Update references to Dandelion’s GitHub account

- tensorboard/tools/diagnose_tensorboard.py
Summary:
The output of `pip freeze` in particular can be multiple pages long. We
do want this output, but we don’t want to scroll through it.
Test Plan:
Run the diagnosis script and copy the output into a GitHub comment box
to preview the rendered Markdown. Note that it’s now compact—
—and that you can click the “Diagnostics output” to expand the full
contents.
[1]: https://user-images.githubusercontent.com/4317806/59795069-465d2980-928f-11e9-893c-d8c62d99d592.png
wchargin-branch: diagnostics-details
> diagnose: wrap diagnostics in `<details>` element

- tensorboard/components/tf_dashboard_common/dashboard-style.html
Especially when name of the run is short and size of the window is large,
tf-runs-selector was not taking up the size of the parent width. This bug
was quite subtle for our demo/test data because data location string was
long enough to make the tf-runs-selector take up wider width. By manually
removing the data location string (length of run names do not matter), we
were able to reproduce the bug. 
This change makes tf-runs-selector take up the width of the parent.
Because we use position relative-absolute trick, we have to consider the
size of the parent's (or relative container) padding.
Fixes #2358.
> tf-runs-selector: make it take up parent's width.

- tensorboard/BUILD
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/default.py
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/setup.py
- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/tf_projector_plugin/BUILD
- tensorboard/plugins/projector/tf_projector_plugin/index.js
- tensorboard/plugins/projector/tf_projector_plugin/tf-projector-plugin.html
- tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.html
Build projector frontend code as a separate binary and loaded that as a
soruce (not from webfiles) in projector_plugin.
Made changes to our pip packaging to include the projector FE binaries.
Made changes to tensorboard dependencies to make local development easy.
Tested:
- local dev by running `pip setup.py develop` in source tree A then
running TensorBoard in source tree B
- tested pip package building and running TensorBoard
> Load projector plugin dynamically

- WORKSPACE
- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
- third_party/clutz.bzl
Summary:
This fixes the new analysis-phase `--incompatible_*` flags:
```
--incompatible_depset_is_not_iterable=false \
--incompatible_disable_deprecated_attr_params=false \
--incompatible_new_actions_api=false \
--incompatible_no_support_tools_in_action_inputs=false \
```
The flag `--incompatible_use_python_toolchains=false` is still required
for imports of Python modules defined only in the virtualenv to resolve.
I’m not sure what the right course of action is. The [official
“Migration” discussion][migration] seems to only consider cases where
the problem is caused by Python 2 vs. 3 runtimes, not where a virtualenv
is desired.
[migration]: https://github.com/bazelbuild/bazel/issues/7899
As noted inline in the fourth commit, I do not understand why a
particular hack is required in …
> build: partially fix for Bazel 0.27

- tensorboard/compat/tensorflow_stub/io/gfile.py
- tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
- tensorboard/summary/writer/record_writer_test.py
This fixes https://github.com/pytorch/pytorch/issues/20477
It looks like our original compat implementation of `PyRecordReader_New` didn't continue to try and read content from a file after it had done the original read. This updates the class to continue to request data from the file and read in new events. Note that this would only be seen in the non-TensorFlow case. Here's a test case:
```
conda create --name notf36 python=3.6
conda activate notf36
pip install --upgrade pip
pip install scipy
conda install -y protobuf
conda install -y absl-py
conda install -y numpy
conda install pytorch-nightly -c pytorch  # For the train.py below
pip install tb-nightly  # For the train.py below
bazel build tensorboard --verbose_failures
./bazel-bin/tensorboard/tensorboard --logdir …
```
> Make sure compat PyRecordReader_New reads new data

- docs/r2/tensorboard_in_notebooks.ipynb
Hi!
As described in #1952, it was necessary to add the information to expose the TensorBoard port when running the notebook using TensorFlow docker image. So, I added a paragraph in tensorboard-in-notebooks file, explaining the usage with docker, in **Setup** section:
[1]: https://user-images.githubusercontent.com/4317806/59947291-b4d1f100-9421-11e9-852e-0bc322fb69c0.png
> Add Docker instructions in tensorboard-in-notebooks

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/deterministic_tar_gz.py
- tensorboard/pip_package/deterministic_tar_gz_test.py
Summary:
We plan to promote TensorBoard’s Pip packages to Bazel targets, but the
filenames of these targets can’t actually be statically determined: they
must include the TensorBoard version number, which is defined in a
Python module. Instead, we’ll build a tarball containing the two wheels.
Building tarballs deterministically with system tools is famously
troublesome (you can do it with GNU `tar` and a lot of flags, but not
portably), and it seems that the standard approach is to use Python’s
built-in `tarfile` library.
Implementation based off of <https://github.com/servo/servo/pull/12244>,
but with changes to make it Python 3-compatible, to use our code style,
and to remove some unneeded machinery. Original is Apache-2 licensed.
Test Plan:
End-to-end tests included. Replacing the body …
> build: add tool to create deterministic tarballs

- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
There are many variants of the tf-graph-dashboard. We recently, to
support other type of compatibility check, added a required field of
"compat-node-title" and in the process broke other apps. This change
makes other app behave exactly the same while keeping the
customizability.
> graph: Add default compat-node-title

- tensorboard/plugins/interactive_inference/utils/BUILD
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/BUILD
- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/pip_package/setup.py
The utility was using TF v1 only API.
Where necessary, we now use `tf.compat.v1` instead of `tf`.
Also ran the migration script to add keywords to the arguments to some methods.
Report from the migration script:
```
INFO line 673:23: Added keywords to args of function 'tf.shape'
INFO line 713:17: Added keywords to args of function 'tf.cond'
INFO line 718:17: Added keywords to args of function 'tf.while_loop'
INFO line 749:8: Added keywords to args of function 'tf.parse_example'                              
INFO line 749:8: Renamed 'tf.parse_example' to 'tf.io.parse_example'                                                                                                                                    
TensorFlow 2.0 Upgrade Script       
-----------------------------
Converted 1 files …
```
> what-if: upgrade what-if source to be tf 2.0 compatible

- tensorboard/plugins/projector/vz_projector/vz-projector-metadata-card.html
Long strings in metadata were incorrectly overflowing the metadata card. Since the element is styled as a table, we need to use word-break rather than overflow-wrap.
**before**
**after**
> Fix word-break issue on metadata card

- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/zipper.bzl
- tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-loader.html
As per https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring
we need to add a docstring at the top of the bzl.
This change is not comprehensive as I have not audited all bzl files.
> cleanup: added doc string to bzl

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-steps-selector.html
Problem 1: the DOM structure
Problem 2: tf-pr-curve-steps-selector broke because its usage of
querySelector. It uses an internal state, `runsToStepIndex`, to record
run to stepIndex (note the distinction from just step) map. It was
manually setting the value to the paper-sliders and listened to the
changed event via listeners. Something in Polymer 2 broke. Instead,
now, we use data-binding to update the value of the paper-slider
Polymer way.
stepIndex vs. step: when there are tons of data, due to our reservoir
sampling, there can be only a subset of the steps. Say we have steps
[0, 4, 10, 1000] for a run foo. When the steps are rendered, it has to
translated to indices since the paper-slider does not supporting an enum.
`runToStepIndex` stores slider index which gets translated to real …
> Polymer 2: pr-curve: fix the basic functionalities

- tensorboard/components/tf_imports/tf_graphics_lib.html
- tensorboard/plugins/mesh/tf_mesh_dashboard/BUILD
- tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-loader.html
tf_mesh_dashboard did not explicitly define dependency on threejs and
implicitly relying on other plugins loading the threejs before its
resource is loaded on the Vulcanized HTML binary. Now that projector,
another user of the threejs, is now dynamically loaded, this pattern
becomes a lot more brittle.
WANT_LGTM=any
This unblocks internal sync.
> cleanup: express explicit dependency on threejs

- tensorboard/program.py
- third_party/python.bzl
Fixes #2028 
This adds a workaround to WerkzeugServer to ensure that werkzeug log messages continue to be subject to TensorBoard's overall log level setting (`--verbosity`).  This basically papers over a change introduced in 0.15.0 (specifically https://github.com/pallets/werkzeug/commit/4cf77d25858ff46ac7e9d64ade054bf05b41ce12) that causes Werkzeug to no longer take root logger configuration into account when setting its own logger level to INFO, and resulted in #2028 where werkzeug HTTP request logs were emitted without respecting the TB log level setting.
I also updated our workspace dep on Werkzeug to the latest version, 0.15.4.
Tested by running tensorboard built both with and without the workspace dep update (aka with both 0.11.15 and 0.15.4 werkzeug versions), and confirmed that no …
> Fix werkzeug logging at INFO by forcibly unsetting werkzeug log level

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Summary:
This is required to use the new `google.colab.kernel.proxyPort` Colab
feature (see Google-internal <http://b/130310433>).
Test Plan:
The included tests verify that the mechanism is implemented as intended.
To verify that the mechanism actually works in Colab, create a Colab
notebook with the following cells:
```python
import werkzeug
@werkzeug.Request.application
def app(request):
frame_ancestors = request.args.get("frame_ancestors")
response = werkzeug.Response("Hello, %s!\n" % (frame_ancestors,))
response.headers["Content-Type"] = "text/html"
if frame_ancestors is not None:
response.headers["Content-Security-Policy"] = (
"frame-ancestors %s" % frame_ancestors
)
return response
```
```python
import threading
import werkzeug.serving
if "server" in locals():
server.shutdown() …
```
> core: add CSP header for Colab output frames

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Models with many classes (like 100) have display issues in WIT
Only show top N classes in PD plots, just like we already do in inference panel
Correctly scroll large confusion matrices instead of overflowing into area where it can't be viewed
Ran all demos to see no regressions
Ran a demo with 100 classes to verify better visuals
> Handle large mutliclass better in WIT

- tensorboard/manager.py
- tensorboard/manager_e2e_test.py
Summary:
This enables specifying the TensorBoard binary with an environment
variable. Callers previously needed to set up a `PATH` with a custom
binary; this is simpler and less intrusive.
(Googlers, see comments on <http://cl/236333099> for context.)
Test Plan:
The newly added test fails before this change and passes after it.
wchargin-branch: tensorboard-binary
> manager: launch `TENSORBOARD_BINARY` if available

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Colab is iterating on mechanism to use iframe within an output frame but
it is not yet ready for consumption. As a result, all usage of iframes
do not work properly in Colab and we would like to communicate that to
users.
After merging this PR, we will update the issue #1913 accordingly.
> core: error msg for dynamic plugin in Colab

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/extract_pip_package.sh
Summary:
For ad hoc testing, one frequently wants to install a Pip package after
buliding it. A new script extracts the wheels and prints the path to the
enclosing directory (for `xdg-open` to drag-and-drop into Colab) and to
the wheels themselves (to copy-and-paste as a `pip install` argument).
Test Plan:
Run the new binary:
```
$ bazel run //tensorboard/pip_package:extract_pip_package 2>/dev/null
/tmp/tmp.caSTM9Sa7J
/tmp/tmp.caSTM9Sa7J/tensorboard-1.15.0a0-py2-none-any.whl
/tmp/tmp.caSTM9Sa7J/tensorboard-1.15.0a0-py3-none-any.whl
```
wchargin-branch: extract-pip-package
> build: add `:extract_pip_package` for convenience

- tensorboard/manager.py
- tensorboard/manager_e2e_test.py
- tensorboard/notebook.py
Summary:
This gives users a more explicit error message for common configuration
errors, like virtualenvs with `--system-site-packages` that mix and
match packages and binaries across environments.
Test Plan:
Automated tests cover changes to `manager.py`. For notebook changes,
build the Pip package, and install it and `IPython` to a new virtualenv.
From an IPython shell, run through all the cases:
```
In [1]: %load_ext tensorboard
In [2]: import os
In [3]: os.environ["PATH"] = ""
In [4]: %tensorboard --logdir logs
Launching TensorBoard...
ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.
In [5]: …
```
> manager: improve error messages for exec failures

- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- third_party/clutz.bzl
Commit 4ba5f51b6d3beb0746ce21d355cef29d918d021d changed ctx.new_file to
ctx.actions.declare_file which is the new way of declaring a file except
the new API behaves a bit differently than the old one.
new_file, as the first argument, took the root directory [1] and
previous to the commit, we passed the bazel genfile path. However,
declare_file no longer take the root path [2] (it generates a new root
path based on whether the rule is genrule or not [3]) and appended the
first argument to the root it generates.
This made TensorBoard have paths like below:
- bazel-out/k8-fastbuild/bin/t/c/tf_backend/bazel-out/k8-fastbuild/bin/backend.js
- bazel-out/k8-fastbuild/bin/t/c/bazel-out/k8-fastbuild/bin/index.pbtxt
- bazel-out/k8-fastbuild/bin/t/c/tf_backend/bazel-out/k8-fastbuild/bin/tf_backend-tsc …
> build: removed bin/genfile prefix in declare_file

- tensorboard/plugins/example/README.md
This change updates our "how to write a plugin" doc. Most contents are ported from https://github.com/tensorflow/tensorboard-plugin-example.
> doc: update how to write plugin doc

- tensorboard/pip_package/extract_pip_package.sh
Test Plan:
Old invocation (still works):
```
$ bazel run //tensorboard/pip_package:extract_pip_package
/tmp/tmp.EqS11sTivI
/tmp/tmp.EqS11sTivI/tensorboard-1.15.0a0-py2-none-any.whl
/tmp/tmp.EqS11sTivI/tensorboard-1.15.0a0-py3-none-any.whl
```
New invocation:
```
$ d="$(mktemp -d)"
$ bazel run //tensorboard/pip_package:extract_pip_package -- "${d}"
$ find "${d}"
/tmp/tmp.2Nr0JszquY
/tmp/tmp.2Nr0JszquY/tensorboard-1.15.0a0-py2-none-any.whl
/tmp/tmp.2Nr0JszquY/tensorboard-1.15.0a0-py3-none-any.whl
```
Failure case:
```
$ bazel run //tensorboard/pip_package:extract_pip_package -- w a t
usage: extract_pip_package [OUTPUT_DIR]
Extract TensorBoard wheel files into a given directory.
If OUTPUT_DIR is omitted, a temporary directory will be created, and its
path and contents printed to stdout.
$ …
```
> extract_pip_package: allow specifying output dir

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/BUILD
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
If a model fails to run inference in WitWidget, no error is currently displayed so the user has no idea why WIT isn't working correctly. This change adds in proper error handling.
Updated jupyter and colab witwidget code so that if inference throws any python error, it is properly caught and sent to the frontend.
The frontend now displays that inference error in a toast and in the status message.
Also fixed a small bug where when comparing 2 regression models, the initial Facets Dive view doesn't compare the two models.
Ran colab and jupyter notebooks with and without inference errors to see that the error message in both …
> Add inference error messages in WIT notebook mode

- tensorboard/components/tf_imports/BUILD
- tensorboard/components/tf_imports/polymer-externs.html
- tensorboard/components/tf_imports/polymer.html
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- third_party/js.bzl
- third_party/polymer.bzl
With the Polymer upgrade, the extern files for JSCompiler is supplied by the Polymer project. We would like to upgrade the type information for better Polymer2 compatibility.
For other externs, in vulcanize/BUILD, we were passing them as files to Vulcanize.java. However, due to the internal restrictions, we can only pass them as a tf_web_library which Vulcanize.java takes as a webfile.pbtxt. Now that externs exist in the webfile.pbtxt, we need to account for that when loading all externs.
Merge plan: squash into polymer2 branch.
> core: update polymer2 externs

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Test Plan:
Built `//tensorboard/components:index.html` before and after this
change, and verified that the two copies are bit-for-bit equivalent.
wchargin-branch: remove-node
> vulcanize: factor out `removeNode` helper

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Summary:
The [`TextNode(String, String)` constructor][ctor] is deprecated in
favor of the 1-argument version. The second parameter is unused.
Test Plan:
Built `//tensorboard/components:index.html` before and after this
change, and verified that the two copies are bit-for-bit equivalent.
[ctor]: https://jsoup.org/apidocs/org/jsoup/nodes/TextNode.html#TextNode-java.lang.String-java.lang.String-
wchargin-branch: update-textnode-usage
> vulcanize: drop deprecated argument to `TextNode`

- docs/_project.yaml
Summary:
Google-internal change; see <http://b/137553519>.
Test Plan:
None.
wchargin-branch: docs-cc-apache
> docs: update CC/Apache license name

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Users asked for median error stats in addition to current mean error stats
Added calculation of, and display of, median error, median absolute error, and median squared error to the regression performance table.
Ran regression demo and viewed performance stats in total and broken down into slices. Verified correct median numbers and that sorting by those new columns worked.
> Add median stats to What-If Tool regression performance stats table

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
This reverts commit 22ec90da870ac4b98cb3dd1198358dd54f18a925.
Internal version of jsoup is old and is compatible with the change.
> Revert "vulcanize: drop deprecated argument to `TextNode` (#2430)"

- tensorboard/plugins/hparams/keras.py
- tensorboard/plugins/hparams/keras_test.py
- tensorboard/plugins/hparams/summary_v2.py
- tensorboard/plugins/hparams/summary_v2_test.py
- tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.html
Summary:
Resolves #2440. See #1998 for discussion.
Test Plan:
The hparams demo still does not specify trial IDs (intentionally, as
this is the usual path). But apply the following patch—
```diff
diff --git a/tensorboard/plugins/hparams/hparams_demo.py b/tensorboard/plugins/hparams/hparams_demo.py
index ac4e762b..38b2b122 100644
--- a/tensorboard/plugins/hparams/hparams_demo.py
+++ b/tensorboard/plugins/hparams/hparams_demo.py
@@ -160,7 +160,7 @@ def model_fn(hparams, seed):
return model
-def run(data, base_logdir, session_id, hparams):
+def run(data, base_logdir, session_id, trial_id, hparams):
"""Run a training/validation session.
Flags must have been parsed for this function to behave.
@@ -179,7 +179,7 @@ def run(data, base_logdir, session_id, hparams): …
```
> hparams: allow setting trial ID

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
There were cases when JSComp removed Polymer bound methods (invisible to
JSComp) away from compiled binary (e.g., inlined into another method).
This change prevents such optimization.
Fixes #2451. Fixes #2447.
> build: fix JSComp removing methods issue

- tensorboard/pip_package/build_pip_package.sh
Summary:
We don’t use `set -x` indiscriminately because build tool output appears
in Bazel logs, and that would be a lot of spam. But we should print
output on failures, to clarify the cause of issues like #2458.
The original version of #2363 had this functionality in the BUILD rule
itself, but @nfelt found that the multiple layers of escaping made this
a bit hard to read (fair enough), so we now include the relevant
functionality in `build_pip_package.sh`.
Recommend ignoring whitespace for reading this patch.
Test Plan:
Building `//tensorboard/pip_package` on a machine with no `virtualenv`
binary now prints:
```
ERROR: /home/wchargin/tensorboard/tensorboard/pip_package/BUILD:8:1: Executing genrule //tensorboard/pip_package:pip_package failed (Exit 127) bash failed: error executing …
```
> build_pip_package: print build log on failure

- tensorboard/plugins/graph/tf_graph_common/scene.ts
* Fixes https://github.com/tensorflow/tensorboard/issues/2455
* Fixes an issue in graph scene.ts panToNode() method. It fails to find the correct node element. 
* Fix the logic by which svg node elements are found in panToNode().
* Now panToNode() works:
* Manual verification by using the Debugger Plugin with a Keras Model.fit() call with tfdbg TensorBoardDebugWrapperSession().
> [debugger plugin] Fix panToNode

- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
The `manager` and `notebook` modules no longer choke when there are
older or newer versions of TensorBoard running.
We also now silently ignore invalid files. There isn’t really any useful
information to report out to the user.
Fixes #2453. Fixes #2467.
Test Plan:
Launch TensorBoard version 1.14.0 (stable), and keep it running in the
background. Then, create a new virtualenv with Jupyter and latest
nightly TensorBoard. Launch Jupyter, and execute the following cell:
```
%load_ext tensorboard
%tensorboard --logdir /tmp/whatever
```
Before this patch, this would successfully launch TensorBoard, but also
spam a bunch of “incompatible version” log warnings. Those warnings are
now gone.
Then run
```python
from tensorboard import notebook
notebook.list()
```
and note that the list …
> notebook: improve cross-version compatibility

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Long WIT error messages caused text overflow, hiding some controls.
Added correct CSS rules to avoid overflow issue and to ellipsis the status string. The full error string is already shown in a toast as well.
Fixed:
Ran demo app, added fake very long error message, verified correct visual behavior (and incorrect behavior before fix).
> What-If Tool: Fix error message overflow issue

- README.md
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/directory_loader.py
- tensorboard/backend/event_processing/directory_loader_test.py
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/util/test_util.py
This adds an experimental option `--reload_multifile=true` that addresses #1063 by polling for new data from multiple active event files within a given run directory, rather than only polling the most recent event file.  (See #1063 for why that behavior has been problematic.)
To avoid runaway resource usage, we don't unconditionally poll *all* event files, since in most cases many of them are no longer receiving new data.  This PR instead introduces a notion of an "inactive age" (settable via `--reload_multifile_inactive_secs`) beyond which an eventfile with not event wall time more recent than that will be considered "inactive" and no longer polled.  This means, for example, that users who accumulate many runs over a period of weeks in the same logdir will only poll new data from runs …
> Add option to read multiple active event files per directory

- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
* This is a temporary solution to #2437 . It prevents double stamping of tf-debugger-dashboard in DOM, when the plugin is enabled through the command line flag `--debugger_port`.
* Remove the tf_tensorboard.registerDashboard() call in tf-debugger-dashboard. 
* In `debugger_plugin_loader.py`, make sure that there is always one plugin returned. This avoids the problem in which the debugger plugin is missing from the dropdown menu when the `--debugger_port` flag is not provided (Thanks to @nfelt and @stephanwlee for the idea).
* Remove check of grpc import now that grpc is a pip dependency of tensorboard.
* Simplify the logic of opening the initial dialog and disabled dialog in tf-debugger-dashboard
* Screenshots of UI …
> [debugger plugin] Temporary solution to avoid double stamping

- tensorboard/backend/event_processing/plugin_event_accumulator.py
Summary:
This was a relic of a piecewise migration from the `event_accumulator`’s
old form to its current `plugin_event_accumulator` form. (See #345 for
an example of one of the intermediate states.) Now totally superfluous,
it incurs needless cognitive and CPU overhead, as the `getattr` blocks
standard optimizations.
Test Plan:
All tests pass, and TensorBoard can still load the standard demo data.
wchargin-branch: eliminate-metaprogramming
> backend: eliminate unnecessary metaprogramming

- .travis.yml
Summary:
CI builds against `tf-nightly` are currently broken, because Travis
elects to install version `1.15.0.dev20190730` even though there are
four more recent releases. Moreover, that version of `tf-nightly`
happens to have a broken `tensorflow_estimator` package.
Upgrading Pip from Travis’s 9.0.1 to current (19.2.1) suffices to
resolve the most recent version.
wchargin-branch: ci-pip-latest
> ci: use latest Pip

- .travis.yml
Summary:
This was removed in #2278, but is actually pretty helpful.
wchargin-branch: ci-pip-freeze
> ci: print `pip freeze` output, for debugging

- third_party/js.bzl
Summary:
This fixes a “Cannot read property 'forEach' of undefined” error, as
reported in #2324.
Test Plan:
Run the following script to generate test data:
```python
import tensorflow as tf
from tensorboard.plugins.mesh import summary as mesh_summary
points = tf.random.normal([1, 20, 3], 0, 1)
meshes_summary = mesh_summary.op("new_points", vertices=points)
writer = tf.summary.FileWriter("logs")
with tf.Session() as sess:
summaries = sess.run(meshes_summary)
writer.add_summary(summaries)
```
Then, launch TensorBoard pointing at `./logs`, and observe that the mesh
plugin successfully loads and renders without console errors, though the
point clouds are still hard to see:
[screenshot]: https://user-images.githubusercontent.com/4317806/62171802-0f921e80-b2e5-11e9-9609-5a212aad9db9.png …
> mesh: update tf-graphics dep to 2019-07-30

- DEVELOPMENT.md
Summary:
Since #2472, this is needed to alter frontend dependencies; since #2493,
it is needed to lint frontend code.
Test Plan:
Ask a guinea pig to follow these instructions.
wchargin-branch: docs-yarn
> docs: point to Yarn install instructions

- tensorboard/examples/plugins/example_basic/BUILD
Summary:
This has timed out a few times on CI, and I’ve never seen it actually
hang, so bumping the timeout seems appropriate. See:
<https://github.com/tensorflow/tensorboard/pull/2500#discussion_r311094558>
Test Plan:
The test still passes, so the `BUILD` file is valid.
wchargin-branch: example-smoke-moderate
> example_basic: bump smoke test to moderate timeout

- WORKSPACE
- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/README.md
- tensorboard/components/tensor_widget/demo/demo.css
- tensorboard/components/tensor_widget/demo/demo.html
- tensorboard/components/tensor_widget/tensor-widget.ts
- tensorboard/components/tensor_widget/version.ts
- third_party/workspace.bzl
* Continue developing tensor-widget
* Add a ts_devserver BUILD target to tensor-widget.
* Server a demo.html and a demo.css file from the ts_devserver
* demo.html uses AMD `require()` to load the compiled tensor-widget library
* Add version.ts both for future versioning and so that we have something to show in the demo page.
* Update README.md to include instructions on how to run the dev server.
* 
* `ibazel run tensorboard/components/tensor_widget:dev_server`
* Ran all bazel tests
* `yarn fix-lint`
> [tensor-widget] Add TensorWidget demo scaffold

- tensorboard/components/BUILD
- tensorboard/components/trace_viewer.html
TensorBoard depends on Chromium Catapult projector by downloading its
Vulcanized source (it comes from [1] which is quite dated but there is
no good replacement). The bundle comes with a Polymer version v1.8.1 (
search for `Polymer.version="` in [1]) and it is incompatible with
tf-imports/polymer.html.
[1]:
https://raw.githubusercontent.com/catapult-project/catapult/vulcanized_traceviewer/trace_viewer_full.html
Fixes #2491.
> profile: fix trace viewer

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/projector/vz_projector/vz-projector-app.html
- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
Summary:
Links with `target="_blank"` open in a new tab, but by default that new
tab can control the page that opened it via the `window.opener` object.
Using `rel="noopener"` closes this security hole.
Test Plan:
No automated test for now; we tend to catch these in code review, so
this is a backfill. Manual verification:
```
$ git grep -o noopener '*.html' | wc -l
20
$ git grep -o _blank '*.html' | wc -l
20
```
wchargin-branch: rel-noopener
> Use `rel="noopener"` for `target="_blank"` links

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Now that we have real ShadowDom, the input within the paper-input has to
be styled through mulitple layers of webcomponents, correctly. Normally,
we would be using ShadyCSS (CSS mixin did not make it to the spec) and a
mixin API exposed by appropriate WebComponents to achieve that but it is
not viable in this case. Specifically, paper-dropdown-menu allows
styling of paper-input using a mixin but in order to style input within
the paper-input, we need to use another mixin. ShadyCSS explicitly says
the nested mixin is not supported.
Instead of transforming with CSS, we decided to fix the issue by
preprocessing the tabName in JavaScript.
See:
https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#known-issues
Fixes #2446.
> polymer2: fixed plugin dropdown UI issue

- tensorboard/plugins/scalar/http_api.md
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
This is not a user-facing change, because the runs selector is populated
by the separate `/data/runs` endpoint. As we begin to consider generic
data providers (cf. #2490), it seems superfluous that a “list scalars”
call to a storage layer might be required to include _all_ run names in
the response even if only a few have relevant data and the rest will be
ignored, anyway.
Test Plan:
Tests updated. Manually confirmed that runs like `text_demo` continue to
appear in the scalar dashboard’s run selector even though they have no
scalar data.
wchargin-branch: scalars-omit-empty
> scalars: omit empty runs from `/tags` route

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/defs/defs.bzl
In order to sync the latest change that includes rollup_bundle into
Google, we need to make a wrapper that change some behavior internally.
Extraenous changes are auto formatter (buildifier plugin) acting up.
> Wrap rollup_bundle around tf_js_binary for interop

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
repro case: https://next.plnkr.co/edit/4MCqtk5HAo3oTOKa
Unclear exactly why it behaves as it does. We can posit that it is a bug
with how shadyCSS handles the mixin and applies one.
While fixing the bug, vetted the CSS rules and removed unnecessary ones
(e.g., ---paper-font-subhead).
Fixes #2403.
> ui: fixed graph causing dropdown-menu bug

- tensorboard/components/tf_ng_tensorboard/BUILD
This change removes the tf_web_library target from the
tf_ng_tensorboard to unblock google sync process.
Generally speaking, tf_web_library is an impediment in general to our
building/development cycle so we should reconsider using the
tf_web_library for angular source at all. We are currently thinking that
Angular source can depend on Polymer but Polymer cannot depend on
Angular.
> ng: remove tf_web_library target

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_info/tf-graph-info.html
* Towards fixing https://github.com/tensorflow/tensorboard/issues/2518
* Fixes https://github.com/tensorflow/tensorboard/issues/2527
* Check not only the `nodeNamesToHealthPills` variable is truthy, but also that the number of its keys is greater than 0.
* Correct layout of the "show health pill" toggle.
The health pills no longer show up by default. The layout is fixed.
* Verified that the health pills don't show up by default with a logdir with graphs in it.
> [graph plugin] Prevent health pills from showing up by default; Fix layout and default

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/README.md
- tensorboard/components/tensor_widget/demo/demo.css
- tensorboard/components/tensor_widget/demo/demo.html
- tensorboard/components/tensor_widget/shape-utils-test.ts
- tensorboard/components/tensor_widget/shape-utils.ts
- tensorboard/components/tensor_widget/string-utils-test.ts
- tensorboard/components/tensor_widget/string-utils.ts
- tensorboard/components/tensor_widget/tensor-widget-impl.ts
- tensorboard/components/tensor_widget/tensor-widget.css
- tensorboard/components/tensor_widget/tensor-widget.ts
* Continue developing tensor widget
* Add tensor-widget-impl.ts that will hold the core logic that renders the tensor widget.
* Add the style sheet for TensorWidget: tensor-widget.css
* Add code that renders the header section and the basic info subsection of it.
* The basic info subsection includes the following fields:
* Name (optional)
* Tensor DType
* Tensor Shape
* Add string-utilts.ts to handle the formatting of long tensor names.
* Add shape-utils.ts. Right now it only has a trivial helper function to format shape strings.
* Add unit tests for string-utils.ts and shape-utils.ts.
* Add four tensor widget panels in demo.html.
* Detailed steps to verify changes work correctly (as …
> [tensor-widget] Render basic tensor info

- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
These tests were disabled for two reasons: they used `tf.placeholder`,
and they used `tf.contrib.summary` for DB mode tests. This patch revises
the implementation of the non–DB mode tests to avoid using placeholders,
and enables those tests in all versions of TensorFlow. The DB mode tests
still cannot be run in TF 2.x because `create_db_writer` is not exported
under any public APIs.
Test Plan:
Tests pass in current `tf-nightly` and `tf-nightly-2.0-preview`.
wchargin-branch: scalars-plugin-tests-tf2x
> Make scalars plugin tests mostly TF 2.x–compatible

- .bazelrc
Summary:
This expands our forward-compatibility window to at least 0.29.0rc4 by
opting out of the `--incompatible_use_python_toolchains` flag whose
default was flipped in 0.27.0 (see #2355).
Fixes #2534.
Test Plan:
On Bazel 0.29.0rc4, verify that `//tensorboard` fetches, builds, and
runs correctly and that all tests pass, without the need to manually
specify any flags to Bazel.
wchargin-branch: bazelrc-toolchains
> build: add `.bazelrc` to disable Python toolchains

- tensorboard/plugins/profile/memory_viewer/memory_usage/memory-usage.ts
- tensorboard/plugins/profile/memory_viewer/xla/logical-buffer.ts
- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
Add bug fixes and feature requests that have been made internally but are not in Github repository.
Memory viewer:
1)  Identify hbm heapSimulatorTrace from logical buffer color.
2)  Fix a bug that XLA made changes to heap simulator proto to have must alias support. 'SHARE_WITH' type allocation now needs to be taken into account in heap simulator.
Op Profile:
1) Add wasted time and sort by wasted time in the table.
2) Add memory bandwidth utilization to the header and make its color higher is red (bad) and lower is green (good).
3) Move unavailable info upper to where performance info is in the op details card.
(No change to memory viewer UI, only bug fixes.)
* Detailed steps to verify …
> Improve memory viewer and tf-op-profile tool. 

- WORKSPACE
With the symlink_node_modules (default is True), the macro created a
symlink from $PWD/node_modules into bazel internal directory
(e.g., wherever bazel-tensorboard/external/npm/node_modules leads to).
Because we rm -rf the source directory, the node_modules folder gets removed,
creating a broken symlink. This change makes sure npm install does not create
such symlink but instead creates every folder under the bazel internal
directory.
> infra: fix tomservo and nightly build

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
We initialize dynamic plugins by creating a new iframe and injecting
into it a `script` element with `import("path/to/index.js")`. This does
not work in Firefox, throwing what appears to be an internal error:
<https://bugzilla.mozilla.org/show_bug.cgi?id=1573262>
@stephanwlee had the idea to try wrapping the contents of the inner
frame’s script with `setTimeout(…, 0)`, which worked! It turns out that
we have to move the `baseURI` initialization into that deferred context,
too.
Fixes #2536.
Test Plan:
Launch TensorBoard and navigate to `/#projector`. Confirm that the
projector plugin loads properly in both Chrome 76 and Firefox 68. The
vanilla JS `example_basic` plugin also works in both now, too.
Co-authored-by: Stephan Lee <stephanwlee@gmail.com> …
> Fix dynamic plugin bootstrap sequence in Firefox

- tensorboard/plugins/graph/tf_graph_app/BUILD
Internal build requires the built binary.
> graph: provide built-binary for legacy target

- SECURITY.md
Summary:
We don’t have much to say on top of TensorFlow’s existing `SECURITY.md`,
so we link to that and explicitly provide a disclosure email for
passersby. Links are intentionally to `master` rather than permalinks.
Test Plan:
Preview the Markdown on GitHub and click both links; verify that they
work.
wchargin-branch: security-md
> Add `SECURITY.md` with disclosure instructions

- tensorboard/plugins/graph/tf_graph_common/test/hierarchy-test.ts
Summary:
This fixes the following `tsc` error:
```
../../../../../../../../../../../../../../tmp/tmpMOk7do/tf-graph-common/test/hierarchy-test.ts(15,8): error TS2451: Cannot redeclare block-scoped variable 'expect'.
Target //tensorboard/plugins/graph/tf_graph_common/test:test_web_library failed to build
```
The error does not always appear. I can reproduce it on `bf227471` on
Linux after running `bazel clean --expunge` with Bazel 0.26.1, Python
3.6, and `tf-nightly-2.0-preview==2.0.0.dev20190814`, but @stephanwlee
can’t reproduce it with those same configurations.  We don’t know why
this happens, and we don’t know why I’m just seeing it now.
Test Plan:
Check that all `const {expect} = chai;` bindings are now within a scope
brace of some kind:
```
$ git grep -h -B 1 'const {expect}' …
```
> build: fix nondeterministic `tsc` error

- tensorboard/plugins/hparams/api.py
Summary:
Active development of these APIs has completed, and they were published
in the 1.14 release notes. Closes #1998.
wchargin-branch: hparams-public-api
> hparams: mark public APIs as stable

- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.ts
This is in reference to something in #2492. I'm working with image data (audio spectrograms, tbe) and I'm trying to visualize them with the embedding projector, but due to the transparency in the sprite textures and them just being small, it makes it difficult to actually make sense of and visualize neighboring points. So I wanted to add some view that allows us to see the images larger, more organized, without the shaders.
I added the sprite images over each item in the nearest neighbor list (that pops up when you select a point).
I also added a checkbox to toggle this feature which will only be shown if a sprite image file is available.
It uses css background-image/position to load the image, and uses the …
> added images to nearest neighbors list

- tensorboard/backend/application_test.py
Summary:
This doesn’t actually end up mattering, but the default value for each
flag should be a valid member of that flag’s domain. This is a hold-over
from a previous formulation of `--generic_data`.
Test Plan:
That tests pass suffices.
wchargin-branch: fix-test-default-flag
> application: fix default flag value in test stub

- tensorboard/plugins/mesh/mesh_plugin_test.py
- tensorboard/plugins/mesh/metadata_test.py
- tensorboard/plugins/mesh/summary.py
- tensorboard/plugins/mesh/summary_test.py
Summary:
These just needed to drop down to graph mode in a few places. The
metadata test actually already worked in TF 2.x! :-)
Makes progress toward #1705.
Test Plan:
Tests pass in both TF 1.x and TF 2.x, and the mesh plugin no longer uses
`run_v1_only`:
```
$ git grep run_v1_only '*mesh*' | wc -l
0
```
wchargin-branch: mesh-tests-tf2x
> Make mesh plugin tests TF 2.x–compatible

- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/audio/summary.py
- tensorboard/plugins/audio/summary_test.py
- tensorboard/util/BUILD
- tensorboard/util/encoder.py
- tensorboard/util/encoder_test.py
Summary:
These tests used `tf.contrib.ffmpeg.encode_audio`, but they can actually
just use `tf.audio.encode_wav`, which has existed since TensorFlow 1.14.
This also makes the encoder itself TF 2.x–compatible.
Makes progress toward #1705.
Test Plan:
Tests pass in both TF 1.x and TF 2.x, and the `run_v1_only` decorators
have been removed:
```
$ git grep run_v1_only '*encoder*_test.py' '*audio*_test.py' | wc -l
0
```
wchargin-branch: audio-tf2x
> Make audio-related functionality and tests TF 2.x–compatible

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/data_provider.py
- tensorboard/backend/event_processing/data_provider_test.py
- tensorboard/data/provider.py
- tensorboard/plugins/core/core_plugin.py
Summary:
The `list_scalars` and `read_scalars` API calls aren’t sufficient for a
fully end-to-end demo with a custom data provider implementation,
because the frontend gets the list of runs to display from `/data/runs`.
This commit adds a corresponding API call and wires it up to the client.
Test Plan:
Unit tests included. To manually verify that the new APIs are being
called, patch the `MultiplexerDataProvider` to include some bogus value:
```diff
diff --git a/tensorboard/backend/event_processing/data_provider.py b/tensorboard/backend/event_processing/data_provider.py
index ef602320..20e43800 100644
--- a/tensorboard/backend/event_processing/data_provider.py
+++ b/tensorboard/backend/event_processing/data_provider.py
@@ -55,7 +55,7 @@ class MultiplexerDataProvider(provider.DataProvider): …
```
> data: add `list_runs` API call and implementation

- tensorboard/BUILD
- tensorboard/plugins/audio/BUILD
- tensorboard/util/BUILD
Summary:
As of #2557, we’ve migrated all users off of `tf.contrib.ffmpeg`, so
this BUILD target can be removed.
Test Plan:
Running `git grep contrib.ffmpeg` yields no results, and the only
mentions of `ffmpeg` are in `beholder/video_writing.py` (which shells
out to `ffmpeg(1)` as a subprocess).
wchargin-branch: remove-ffmpeg
> build: remove `//tensorboard:tf_contrib_ffmpeg`

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/backend/event_processing/db_import_multiplexer_test.py
- tensorboard/plugins/core/core_plugin.py
This was basically dead code already, since we opted to use a pure-python implementation of the DB writer instead, to avoid the need to launch a subprocess to avoid locking issues in having two SQLite libraries linked into the same process.  Now that the `tf.contrib.summary.create_db_writer()` symbol isn't being ported forward to TF 2.0, it's time to clean this up.
Addresses an item from #1718.
> Remove --db_import_use_op flag and implementation

- .travis.yml
Summary:
Recent releases of tf-nightly indicate\* that this package will soon
be updated to the TensorFlow 2.0 APIs, and suggest pinning a version.
This commit does that.
\* Via a message printed at `import tensorflow` time.
Test Plan:
Verify that the Travis build specifically instructs Pip to install
version `1.15.0.dev20190816` of the TF 1.x nightlies, while still
floating the TF 2.x nightlies.
wchargin-branch: pin-tf1x
> ci: pin TF 1.x nightlies to 2019-08-16

- tensorboard/plugins/graph/tf_graph_common/tf-node-icon.html
Source of bug:
1: typo: getSvgDefineableElement -> getSvgDefinableElement
2: wrong switch statement
fixed view:
> graph: fixed the node inspector view

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
This field is unused today and has no planned future use, since we only support `sqlite3` and aren't planning on extended support via this mechanism.  Removing it simplifies later refactoring.
> Remove unused TBContext.db_module field

- tensorboard/backend/event_processing/plugin_event_multiplexer.py
I'm not sure why the plugin EventMultiplexer still has `Scalars()` and `Audio()` methods, but they are unused, and they would never have worked because they invoke the corresponding methods on the plugin EventAccumulator, which doesn't even have those methods.
> Remove unused vestigial plugin EventMultiplexer APIs

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
- tensorboard/plugins/mesh/mesh_plugin_test.py
- tensorboard/plugins/projector/projector_plugin_test.py
This removes TensorBoardWSGIApp, a thin wrapper over TensorBoardWSGI that launches the reloading thread.  Instead, we move that logic up into `standard_tensorboard_wsgi()` which is the only non-test caller of TensorBoardWSGIApp.
For tests, we update these to use TensorBoardWSGI directly, and add an explicit `multiplexer.Reload()` call where necessary to maintain the previous behavior.
The only usage I know of outside the TB repo is in the TF Lite plugin which I have a PR out to fix in https://github.com/lintian06/tensorflow-lite-plugin/pull/1, but I'm not blocking on that to land.
This addresses core task 1 in https://github.com/tensorflow/tensorboard/issues/2573, and frees up the name TensorBoardWSGIApp to reuse for a new API to come.
> Refactor away TensorBoardWSGIApp in its current form

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/demo/demo.html
- tensorboard/components/tensor_widget/demo/demo.ts
- tensorboard/components/tensor_widget/shape-utils-test.ts
- tensorboard/components/tensor_widget/shape-utils.ts
- tensorboard/components/tensor_widget/slicing-control.ts
- tensorboard/components/tensor_widget/tensor-widget-impl.ts
- tensorboard/components/tensor_widget/tensor-widget.css
* Continue developing TensorWidget
* Add a slicing control UI, included in the newly created file silcing-control.ts
* This UI allows the user to  move between slices and to flexibly change which dimensions of a 3D+ tensor are sliced and which are viewed in the value table.
* The dimension selection is supported by an ad hoc dropdown menu.
The dropdown menu for swapping a viewing dimension with a slicing one:
The div for a slicing dimension becomes a number input box when clicked.
- Co-author: @bileschi
> [tensor-widget] Add slicing control to support 3D+ tensors

- package.json
- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/app.component.html
- tensorboard/components/tf_ng_tensorboard/app.component.ts
- tensorboard/components/tf_ng_tensorboard/app.module.ts
- tensorboard/components/tf_ng_tensorboard/core/BUILD
- tensorboard/components/tf_ng_tensorboard/core/core.actions.ts
- tensorboard/components/tf_ng_tensorboard/core/core.module.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
- tensorboard/components/tf_ng_tensorboard/header/BUILD
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.css
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.html
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
- tensorboard/components/tf_ng_tensorboard/header/header.module.ts
- tensorboard/components/tf_ng_tensorboard/reducers.ts
- tensorboard/components/tf_ng_tensorboard/types/BUILD
- tensorboard/components/tf_ng_tensorboard/types/api.ts
- yarn.lock
This change introduces ngrx, a state management, to our angular shell.
The usage of ngrx is very limited. Soon, it will be expanded to make XHR
to fetch list of plugins and properly render the header.
It looks like this:
Note that the folder structure was largely inspired by https://github.com/ngrx/platform/tree/master/projects/example-app but is prone to change based on team consensus.
> ng: introduce ngrx and create basic usage

- tensorboard/plugins/debugger/debug_graphs_helper_test.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/session_debug_test.py
* Re. https://github.com/tensorflow/tensorboard/issues/1705
* Make sure all debugger plugin's python tests pass with TF2
* In session_debug_test.py and interactive_debugger_plugin_test.py: use tf.compat.v1 and disable_v2_behavior(), as tfdbg (V1) is indeed wedded to the Session::Run() paradigm. 
* In debug_graphs_helper_test.py: make conditional assertions to fit v2-specific behaviors
> [Debugger Plugin] Fix Python unit tests for TF2

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/default.py
- tensorboard/plugins/base_plugin.py
- tensorboard/program.py
- tensorboard/program_test.py
This is a follow up to #2576 that makes the new `TensorBoardWSGIApp()` entry point accept types besides TBLoader instances for its `plugins` argument, namely it also accepts a `TBPlugin` subclass (which it will wrap in a `BasicLoader`) or a `TBLoader` subclass (which it will instantiate with no arguments to get an instance).
I moved the existing helper in `program.TensorBoard()` into `application.py` for this, which means that API also has gained the ability to take a `TBLoader` class (and a better error if passing in invalid types).
Lastly, I've streamlined the plugin list in `default.py` to just use bare `TBLoader` subclasses, which liberates 10 parentheses to be used for nobler purposes.
> Allow passing TBPlugin/TBLoader subclasses to TensorBoardWSGIApp

- tensorboard/plugins/projector/tf_projector_plugin/BUILD
Turning this on makes it easier to reliably serve the resulting HTML blob in different contexts.
> projector: compile the projector HTML binary

- tensorboard/components/tf_runs_selector/BUILD
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_runs_selector/tf-wbr-string.html
Summary:
Prior to this commit, `tf-runs-selector` used `innerHTML` to inset word
breaks into text, without explicit attention to sanitization. It
happened to “accidentally” to a pretty good job of preventing XSS
because it inserts `<wbr>` after each any equals sign, making it
impossible(?) to set any attribute value without closing the tag. But
some lesser injection vectors, like remote CSS fetching, are still
possible with a bit of thought.
This commit introduces a new component, `tf-wbr-string`, that performs
the word-breaking safely with Polymer APIs.
Test Plan:
Run TensorBoard, and verify that the data location at the bottom of the
runs selector is still rendered properly. Inspect the `tf-wbr-string` in
the dev tools, and note that `wbr`s appear in the appropriate places.
Then, select …
> Create `tf-wbr-string` for safe word-breaking

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/runsStore.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
This implements a rudimentary experiment selection mechanism for the
runs selector and scalars dashboard only, for the purposes of testing
data provider implementations. The experiment ID is stored as a query
parameter, which isn’t perfect because it precludes caching the big
TensorBoard HTML blob across experiments. In the long term, we can
consider refactoring to serve the big HTML blob from a static path
that’s fetched by the page.
The TensorBoard codebase still has some fragments of a previous
experimental data selector, which was partially removed in #2290, and so
parts of this diff look like changes but are functionally additions.
Test Plan:
Instrument the multiplexer data provider to log experiment IDs:
```diff
diff --git …
```
> data: plumb experiment ID through runs and scalars

- tensorboard/summary/_tf/summary/__init__.py
Summary:
The internal API for the base `tf.summary` module has changed from
`tensorflow._api.*` to `tensorflow_core._api.*` as of 2019-08-23
nightlies. This is a quick fix to update our component package
accordingly, though it does not prevent future similar regressions.
Test Plan:
Running
```python
import importlib
print(hasattr(importlib.import_module("tensorflow._api.v2"), "summary"))
print(hasattr(importlib.import_module("tensorflow_core._api.v2"), "summary"))
```
prints `True` `False` on yesterday’s nightly and `False` `True` on
today’s. The `//tensorboard/examples/plugins/example_basic:smoke_test`
target fails before this commit and passes after it.
wchargin-branch: tf-core-summary
> Look for `tensorflow_core._api` in summary component package

- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
Temporary hack to facilitate testing sans multiplexer.
Test Plan:
Remove the multiplexer from the scalars plugin:
```diff
diff --git a/tensorboard/plugins/scalar/scalars_plugin.py b/tensorboard/plugins/scalar/scalars_plugin.py
index 74e6eebc..b3b7a27f 100644
--- a/tensorboard/plugins/scalar/scalars_plugin.py
+++ b/tensorboard/plugins/scalar/scalars_plugin.py
@@ -60,6 +60,7 @@ class ScalarsPlugin(base_plugin.TBPlugin):
self._db_connection_provider = context.db_connection_provider
if context.flags and context.flags.generic_data == 'true':
self._data_provider = context.data_provider
+      self._multiplexer = None
else:
self._data_provider = None
```
Note that prior to this commit the scalars plugin would be marked
inactive (but work fine once explicitly selected), whereas it’s now …
> scalars: appear active when data provider present

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
The “inactive” dropdown is supposed to be hidden when no plugins are
inactive, but a silent type error caused this logic to be incorrect.
(The `activeDashboards` list has plugin names, not plugins.)
Test Plan:
Apply the following patch to “uninstall” all plugins except for scalars:
```diff
diff --git a/tensorboard/components/tf_tensorboard/default-plugins.html b/tensorboard/components/tf_tensorboard/default-plugins.html
index 307b65ac..e0497827 100644
--- a/tensorboard/components/tf_tensorboard/default-plugins.html
+++ b/tensorboard/components/tf_tensorboard/default-plugins.html
@@ -22,6 +22,7 @@ limitations under the License.
and is later instantiated dynamically with `document.createElement`.
-->
<link rel="import" href="../tf-scalar-dashboard/tf-scalar-dashboard.html" />
+ …
```
> tf-tensorboard: fix inactive menu hiding

- tensorboard/components/vz_line_chart2/panZoomDragLayer.html
- tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
With the Polymer change, d3 transition started to misbehave. Because we
were not happy with the frame-rate of the d3.transition, we decided to
refactor the code to use pure CSS for the animation instead.
Empirically, the animation looks a lot smoother.
> ui: fix help animation for line chart

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
- tensorboard/http_api.md
- tensorboard/plugins/BUILD
- tensorboard/plugins/audio/audio_plugin.py
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/base_plugin_test.py
- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/debugger/interactive_debugger_plugin.py
- tensorboard/plugins/distribution/distributions_plugin.py
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
- tensorboard/plugins/mesh/mesh_plugin.py
- tensorboard/plugins/pr_curve/pr_curves_plugin.py
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/text/text_plugin.py
Summary:
We used `namedtuple` for `FrontendMetadata` for convenience, but it’s
not actually semantically appropriate. Metadata objects shouldn’t be
iterable, for instance. Using a normal struct also enables us to define
default values, so plugins can drop the `super(…).…._replace` dance.
These APIs are still marked as experimental until 1.15, so this
backward-incompatible change is okay.
Prior discussions:
- <https://github.com/tensorflow/tensorboard/pull/2529#discussion_r312666985>
- <https://news.ycombinator.com/item?id=15132670>
Test Plan:
Unit tests for the new struct included; existing tests pass, including
the smoke test, and a manual spot check passes muster.
wchargin-branch: frontend-metadata-struct
> Promote `FrontendMetadata` from `namedtuple` to struct

- tensorboard/components/tf_ng_tensorboard/core/BUILD
- tensorboard/components/tf_ng_tensorboard/header/BUILD
- tensorboard/components/tf_ng_tensorboard/plugins/BUILD
- tensorboard/components/tf_ng_tensorboard/testing/BUILD
- tensorboard/components/tf_ng_tensorboard/types/BUILD
For Google sync, we decided to create a wrapper around ts_library in #2596.
This change applies the fix to all existing `ts_library`s.
WANT_LGTM=any
> build: make use of tf_ts_library

- WORKSPACE
Summary:
We upgrade TensorFlow, which defines our protobuf dependency, past
508f76b1d99 (actual dep upgrade), f4e64ca17ce (build fix), and
dad4197fcf0 (workspace fix).
Test Plan:
Run `bazel build @com_google_protobuf//:protoc_lib` using Bazel 0.29.0,
which now completes silently, but previously would print a bunch of
compiler warnings in `descriptor.cc`.
wchargin-branch: protobuf-fix-warnings
> Upgrade protobuf to fix compilation warnings

- tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
- tensorboard/plugins/audio/audio_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/mesh/mesh_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
Summary:
Most\* plugin endpoints for serving actual data have historically tried
to access data from the multiplexer with no validation or error
handling, and as a result would crash and burn (with 500s) given a run
or tag that doesn’t exist. This actually happens fairly commonly: if you
start TensorBoard and interact with the web UI, kill the server while
leaving the browser tab open, and start a new TensorBoard on the same
port but a different log directory, then the old TensorBoard’s refresh
loop will request data from the runs and tags that were previously
available.
These are now properly handled as 400s, not 500s, and they don’t spam
the command line anymore, either. We resolve some TODOs from 2015!
\* Weighted by frequency of use. :-) By raw counts, more plugins behaved
well than …
> Properly handle bad requests to plugin data endpoints

- tensorboard/components/tf_paginated_view/test/categoryPaginatedViewTests.ts
- tensorboard/components/tf_paginated_view/test/tests.html
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
- tensorboard/components/tf_paginated_view/tf-dom-repeat.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
This change updates `active` prop to a template of a
tf-category-paginated-view when the category pane is collapsed/expanded.
It also updates the `active` when a component is no longer mounted onto
the DOM.
The change does not contain any redraw logic but it magically works
because the DataLoaderBehavior, when active changes to active, fetches
data point for ones that are not in cache and then triggers rerender.
This flow of logic is indirect and thus can be made to be more direct
but that can cause too many "redraw" call which can be quite expensive
(scales poorly with # of runs).
Related to #2595.
> scalar: fix tiny chart

- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/angular/BUILD
- tensorboard/components/tf_ng_tensorboard/app.component.ts
- tensorboard/components/tf_ng_tensorboard/app.module.ts
- tensorboard/components/tf_ng_tensorboard/core/BUILD
- tensorboard/components/tf_ng_tensorboard/core/core.actions.ts
- tensorboard/components/tf_ng_tensorboard/core/core.effects.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.effects.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
- tensorboard/components/tf_ng_tensorboard/core/core.service.ts
- tensorboard/components/tf_ng_tensorboard/header/BUILD
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.test.ts
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
- tensorboard/components/tf_ng_tensorboard/plugins/BUILD
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.test.ts
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
- tensorboard/components/tf_ng_tensorboard/testing/BUILD
- tensorboard/components/tf_ng_tensorboard/types/api.ts
- tensorboard/defs/defs.bzl
- tsconfig.json
In this change:
- made tsconfig more strict to roughly reflect internal one
- TypeScript code change to conform to the stricer rule
- created "expected_*" target to denote internal compat dependency graph
- defined missing bazel deps
- the type hacks are annotated for easier migration
- `export` annotation for JSCompiler compatibility.
Corresponding change is cl/266471999.
I have tried `bazel test tensorboard/components/tf_ng_tensorboard/...` both internally and externally after the change.
> build: make ng source sync-able

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Test Plan:
Visit <http://localhost:6006/?experiment=foo#scalars>, check the “Show
data download links” box, select a run from the dropdown, and verify
that the “CSV” and “JSON” links have `&experiment=foo` query parameters.
wchargin-branch: scalars-xid-download
> scalars: include experiment ID in download links

- tensorboard/plugins/mesh/BUILD
This is a temporary disable until #2624 can be resolved.
> build: disable mesh summary v2 test

- WORKSPACE
- third_party/workspace.bzl
This updates our protobuf deps to consistently use protobuf 3.8.0, to fix a version skew issue arising after https://github.com/tensorflow/tensorboard/pull/2609 where the protobuf JS runtime was still on 3.6.0 and thus caused runtime failures when trying to use JSPB messages generated with protoc 3.8.0 (specifically failures that looked like https://github.com/protocolbuffers/protobuf/issues/5930).
Our main protobuf/protoc dep is provided via the TF workspace, so this updates that to 2.0.0-rc0.
cc @jameswex
> Update protobuf and protobuf_js workspace deps to 3.8.0 

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
The run selector has a toggle all runs button.  Before, toggleAll()'s intent is to toggle everything off when the user hasn't interacted with the list and the list is short (<40, everything selected by default).  This logic was broken in [1], which renamed "maxRunsToEnableByDefault" to "maxNamesToEnableByDefault", except for one callsite (causing issue #2614).
This PR fixes the issue and simplifies toggleAll() to rely on "this.outSelected", which already represents the computed selected state.
[1] https://github.com/tensorflow/tensorboard/commit/aacd5cb7ab1076679aa4115191aa3f00e4575f0d
> ui: fix run selector toggle all with many items

- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/debug.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/node_def.proto
- tensorboard/compat/proto/op_def.proto
- tensorboard/compat/proto/resource_handle.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/compat/proto/types.proto
- tensorboard/compat/proto/variable.proto
- tensorboard/compat/proto/verifier_config.proto
Summary:
These are synced to TensorFlow tag `v1.15.0-rc0`, which resolves to
a0163a0a727c9c7af5ac976debd5e28d42275b8c.
There are no new protos or new `import` dependencies, so the existing
build rules and tests suffice.
Test Plan:
Running `bazel test //tensorboard/compat/proto:proto_test` now passes in
a virtualenv with `tensorflow==1.15.0rc0` installed. This is the same as
current TF 1.x nightlies, which are frozen, but _not_ the same as
current TF 2.x nightlies, due to changes in HEAD.
wchargin-branch: proto-sync-v1.15.0-rc0
> proto: sync to TensorFlow v1.15.0-rc0

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/externs.js
- tensorboard/components/tensor_widget/tensor-widget-interop.ts
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
The name, tensor_widget_binary, is unique to rollup_bundle; could not
figure out how to disable such global export in the bundler yet. As
such, we need to explicitly export a module to a global variable.
The externs file was introduced so the exported names are not mangle and
can remain stable.
Internal POC can be found here: cl/268757810
> build: make tensor_widget build with JSComp

- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.css
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.html
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.test.ts
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
- tensorboard/components/tf_ng_tensorboard/header/header.module.ts
Inactive plugins are supposed to show up in the dropdown list.
This change renders the inactive plugins correctly.
Screenshot:
> ng: render inactive plugins

- tensorboard/components/tf_ng_tensorboard/app.component.ts
- tensorboard/components/tf_ng_tensorboard/core/core.effects.ts
- tensorboard/components/tf_ng_tensorboard/core/core.service.ts
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
- readonly for a property that is never modified
- Implement OnInit when implementing ngOnInit
This is one of the action item from cl/267450930
> ng, cleanup: stricter lint

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Before, opening DevTools on Tensorboard showed the single vulcanized html in Sources panel.
In this CL, adding sourceURL lets browser devtools know where a script really came from.  This lets you do things like open a script by name (e.g. DevTools Sources panel > Cmd+P > "run-selector") and have debugging-by-file ([breaks](https://bugs.chromium.org/p/chromium/issues/detail?id=1003497) with pretty-print, sadly).
Note:
- preserving whitespace would be nice, but none of the Closure flags I tried worked
- grouping all the "iron-" elements into a folder would be nice, but is a bit more work
> build: add sourceURL to map scripts in devtools

- tensorboard/components/tf_ng_tensorboard/angular/BUILD
- tensorboard/components/tf_ng_tensorboard/header/BUILD
- material should have a separate definition.
- strict dependency on the type file.
> sync: fix the ng_tensorboard deps definition

- .travis.yml
- tensorboard/compat/tensorflow_stub/io/gfile_s3_test.py
- tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
Like #2654 but without the distro change from Trusty to Xenial in order to make it easier to review these improvements separately from the complexities of changing the distro.
Both flake8 and yamllint have progressively added new tests and some new flake8 tests have been found to have a positive effect on runtime safety.
1. Upgrade flake8 and yamllint to current versions.
2. Add more flake8 tests
3. Fix two instances of __use ==/!= to compare str, bytes, and int literals__ because identity is not the same thing as equality in Python. These instances will raise __SyntaxWarnings__ on Python 3.8 so best to fix them now. https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8
* …
> ci: upgrade flake8 and yamllint

- tensorboard/plugins/hparams/api.py
Summary:
This was an error; the `Experiment` symbol never existed in the final
version of the public APIs. (It existed in earlier drafts, but was
removed for the sake of simplicity.)
Thanks to @tfboyd for reporting this.
Test Plan:
Note that this now matches the invocation in the demo that can actually
be run:
https://github.com/tensorflow/tensorboard/blob/9335e0d3a271293919822aa8a689e9ef04cd6ff8/tensorboard/plugins/hparams/hparams_demo.py#L215-L216
wchargin-branch: hparams-no-experiment
> hparams: remove `Experiment` from public API docs

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
Summary:
This introduces a new flag, `--logdir_spec`, whose behavior is the same
as the old behavior of `--logdir`. The `--logdir` flag now specifies a
single log directory, without special treatment for commas and colons,
though it still has the `expanduser` call for compatibility with users
who use the `--logdir=~/...` form rather than `--logdir ~/...`.
I audited all uses of `flags.logdir` and `context.logdir`, and, other
than those changed in this commit, all really should be using `logdir`
rather than `logdir_spec` (i.e., they do not properly parse the logdir
spec, and so were broken before this commit).
Fixes #2615, fixes #1220, and fixes lots of user confusion.
Test Plan:
Run with the following args:
--logdir ~/data/  # should work as usual
--logdir=~/data/  # should work as usual …
> core: split magic `--logdir_spec` out from verbatim `--logdir`

- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/projector/__init__.py
- tensorboard/plugins/projector/projector_api_test.py
Previously, it used to take an FileWriter as an input so it can infer
logdir to write embedding to. Because summary v2 API deprecated an
ability to get the logdir, we now instead take the logdir as string.
To work with the older code, we make sure we can also take the v1
summary writer.
Addresses #2471, aside from supporting the new checkpoint naming
> projector: visualize_embeddings API change

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
Setting the style manually generally is not recommended as it can
contain JavaScript invoking CSS.
> cleanup: set style using CSS

- .travis.yml
Summary:
Due to <https://github.com/tensorflow/tensorflow/issues/32621>.
This unblocks our CI until tomorrow’s nightlies are pushed.
Test Plan:
Ran this 5-line shell command (with `pip install` changed to `echo) once
with `TF_VERSION_ID` set to each value from the `env` section, and noted
that in all cases it succeeds and that it only prints output in the
correct case.
wchargin-branch: pin-estimator-20190917-nightly
> ci: pin to non-broken estimator nightlies

- tensorboard/pip_package/test_pip_package.sh
- tensorboard/summary/__init__.py
- tensorboard/summary/summary_test.py
This change is for readiness of TensorBoard 2.0 release.
In 2.0, tensorboard.summary should default to v2 symbols.
Fixes #2512
> summary: export v2 symbols as defaults

- README.md
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
- tensorboard/program_test.py
Summary:
Prior to this change, TensorBoard would default to serving on the entire
local network; now, TensorBoard serves to the local machine only, and
the flag `--bind_all` can be used to dual-bind to IPv4 and IPv6 on the
entire local network (the previous default). See #2387 and comments
therein for details.
Test Plan:
On my Debian machine, running with `strace -e trace=%network`:
- running with no `--host` flag:
- can connect to loopback on IPv4 only
- cannot connect over LAN
- `strace` shows binding on `AF_INET`
- a notice about `--bind_all` is printed to stderr
- running with `--host=localhost`:
- same behavior as with no `--host` flag, but no notice is printed
- running with `--host='::1'`:
- can connect to loopback on IPv6 only
- cannot connect over LAN
- `strace` shows binding on …
> core: bind to localhost rather than all interfaces

- tensorboard/examples/plugins/example_basic/smoke_test.sh
Followup from #2500: replace `grep -P` with Perl equivalent, per https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches.
> Make example_basic smoke test work on MacOS

- tensorboard/backend/event_processing/directory_watcher.py
The handling of the StopIteration exception within generators changed in Python 3.7 (PEP 479). 
This broke our handling of empty log directories, causing one test to fail: `directory_watcher_test:TestEmptyDirectory()`.
The backwards-compatible fix is explained at https://www.python.org/dev/peps/pep-0479/#writing-backwards-and-forwards-compatible-code.
This is the only instance of this issue in TensorBoard that causes a test failure.  My reading of the few other appearances of `StopIteration` is that they are legitimate (either catching it, or raising it in a `__next__` method).
> Fix StopIteration issue in Python 3.7 (PEP 479)

- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager.py
Updating the EventsWriter import to _pywrap_events_writer from pywrap_tensorflow.
This is part of a larger effort in TensorFlow to break up pywrap_tensorflow and migrate from SWIG to pybind11. Please refer to [this RFC](https://github.com/tensorflow/community/blob/master/rfcs/20190208-pybind11.md) for more information.
Changes the import package to point to the new one. 
This is an example of a pywrap import and how it works. Unfortunately I cannot provide an exact EventsWriter example, because the nightly binary has not been built yet. 
```
In [1]: from tensorflow.python import _pywrap_utils …
```
> Use _pywrap_events_writer

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Add the ability to show nearest counterfactual example in regression models.
The feature and its use are analogous to the existing counterfactual analysis available in non-regression models.
There is one fundamental difference in the way we compare inference classes. In binary classification, the counterfactual examples are the ones belonging to the alternative class. In regression, we will define them as the ones whose inferred values are farther from the original example than a given delta, which will be defined by the user.
For example, if delta is set to 2 and the inferred value of the selected example is 7, then we'll be looking for most similar example with an inferred value outside of the (5, 9) interval.
* …
> Add counterfactual analysis for regression models (What-If Tool)

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Polymer2 update broke the updating of threshold sliders in WIT when certain optimization buttons are pressed.
Simplified threshold setting data-binding logic. No longer is there a map and a list to the same threshold information that is data-bound to paper-sliders. Now there is a simple list and the map is still used to quickly find items in the list by slice, but the map contains an index to the list and not the same object as is contained in the list. This fixes the issue where the updates to the slider bound values doesn't always cause the physical slider to update its setting.
Ran through demos apps, sliced performance statistics by a feature, …
> Fix threshold optimizations in WIT

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Previously, when using a custom predict function, WIT could consume attribution information for each example along with the standard prediction outputs. This work extends this so that any prediction-time information can be provided to WIT, beyond just attribution values.
Pass dictionary of extra outputs from custom predict models from python to javascript, instead of just passing attribution information. Attribution information would be inside this dict.
Update python logic to handle this dictionary correctly.
Update javascript logic for notebook mode to pass this extra information to WIT.
Update WIT to consume this information and update its visdata and examplesAndInferences structs with this extra data for each …
> Add WIT ability to consume arbitrary prediction-time information

- tensorboard/plugins/interactive_inference/utils/BUILD
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
- tensorboard/plugins/interactive_inference/witwidget/pip_package/setup.py
PD plots didn't work at all in notebook mode with py3 kernels.
Ensure string feature values used in PD plot generation are sent to JS as strings for json serialization, not as bytes, to avoid failing serialization.
Correctly use the bytes when running in py3 as that is what tf.Example expects for bytes_list, whereas in py2 it functions on strings.
Make use of six.bytes_type and encode and decode functions to correctly handle this.
Ran notebooks in py2 and py3 with this change and verified that PD plots are shown correctly (with correct values as well) for both numeric and categorical features.
> Fix PD plots in py3

- tensorboard/program_test.py
Summary:
These tests are currently broken on IPv6-only systems. While it’s valid
to open a _socket_ that binds to `("localhost", 0)` even if the system
only supports IPv6, it’s not valid to start a _Werkzeug server_ with
host `localhost`, because Werkzeug detects `localhost` as an IPv4
address and will open an `AF_INET` socket, causing catastrophe.
This restores the test behavior prior to #2589, which IMHO isn’t great,
but unbreaks these tests on IPv6-only systems.
Test Plan:
This test still works on my dual-IPv4/IPv6 machine, and now also works
on an IPv6-only machine where previously it failed with `EAFNOSUPPORT`.
wchargin-branch: program-test-bind-all
> program_test: bind to all interfaces

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
All Fairness optimization info icons were opening the first one (Custom threshold) when clicked.
Also updated description for Equal Opportunity optimisation, which was inaccurate.
Made function `openDialog` open the next sibling to the clicked element.
Also checked that all `paper-dialog` DOMs were positioned where they should, so that this function would work for all cases -- the only two cases I moved would actually work as they were, but we'd rather have positioned in the same way as the others (they were children; we want siblings).
Only actual change is the Equal Opportunity description.
Open each dialog and confirm …
> Fix Fairness optimization dialogs (What-If Tool)

- tensorboard/components/plugin_util/BUILD
- tensorboard/components/plugin_util/message.ts
- tensorboard/components/plugin_util/plugin-guest.html
- tensorboard/components/plugin_util/plugin-guest.ts
- tensorboard/components/plugin_util/plugin-host.html
- tensorboard/components/plugin_util/plugin-host.ts
- tensorboard/components/plugin_util/test/BUILD
- tensorboard/components/plugin_util/test/iframe.html
- tensorboard/components/plugin_util/test/iframe.ts
- tensorboard/components/plugin_util/test/plugin-test.ts
- tensorboard/components/plugin_util/test/tests.html
TensorBoard, in the near future, will load plugin modules in respective
iframe as was discussed in RFC. This change adds a library that
facilitates communication between main TensorBoard and plugin frames.
> lib: add a library for cross-frame communication

- tensorboard/tools/diagnose_tensorboard.py
Summary:
It appears that this has been deprecated since at least Python 3.5, and
Python 3.7 warns about it.
Test Plan:
Running `python3.7 tensorboard/tools/diagnose_tensorboard.py` without
TensorFlow prior to this commit would emit a warning:
```
tensorboard/tools/diagnose_tensorboard.py:197: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
```
As of this commit, that warning no longer appears. There are no other
occurrences of `.warn(?!ing)` in this file.
wchargin-branch: diagnose-warning
> diagnose: use non-deprecated `logging.warning`

- package.json
- tensorboard/components/tf_backend/BUILD
- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/app.component.html
- tensorboard/components/tf_ng_tensorboard/app.module.ts
- tensorboard/components/tf_ng_tensorboard/core/BUILD
- tensorboard/components/tf_ng_tensorboard/core/core.actions.ts
- tensorboard/components/tf_ng_tensorboard/core/core.effects.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.effects.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
- tensorboard/components/tf_ng_tensorboard/core/core.service.ts
- tensorboard/components/tf_ng_tensorboard/core/testing/BUILD
- tensorboard/components/tf_ng_tensorboard/core/testing/index.ts
- tensorboard/components/tf_ng_tensorboard/header/BUILD
- tensorboard/components/tf_ng_tensorboard/header/containers/header.component.test.ts
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.test.ts
- tensorboard/components/tf_ng_tensorboard/reloader/BUILD
- tensorboard/components/tf_ng_tensorboard/reloader/reloader.component.test.ts
- tensorboard/components/tf_ng_tensorboard/reloader/reloader.component.ts
- tensorboard/components/tf_ng_tensorboard/reloader/reloader.module.ts
- tensorboard/components/tf_ng_tensorboard/types/api.ts
- yarn.lock
tf-tensorboard is responsible for loading data for runs, experiments and
trigger reloading. Without this feature, the runStore will be empty and
will not make the tf-runs-selector operable.
This change implements this behavior in Angular in flux way.
> ng: data loader

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
Bashing bugs before witwidget 1.4 launch.
Fixed datapoint editor panel slider to work in all environments (demos were broken) - by explicitly using the correct dom element and also ensuring some content flex-wraps.
Added checks for when extra outputs is null so it doesn't break WIT when that happens.
Allow fallback in PD plot checking when a string can't be decoded as text (for images).
Fixed boolean setting of if custom distance function set, for correct enabling/disabling of L1/L2 radio buttons.
Ran all demos and verified all features work as expected (including PD plots)
Ran notebook demos that show attributions and extra outputs, along with …
> Various fixes from latest changes

- tensorboard/components/vz_example_viewer/vz-example-viewer.ts
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Updating WIT attribution color scales per mocks
Changed colors and to a 5 color scale for better blending along the gradient.
Removed the duplication of the colors in vz-example-viewer.
Updated at what value the feature value text changes to white due to the background color for attribution.
Ran attribution WIT notebook with attributions with different domains ( all negative, all positive, mix of both) and ensured color and text color looked correct and matched mocks.
> Update WIT attribution colors

- tensorboard/components/tf_dashboard_common/tf-downloader.html
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Before the user selects a run via the downloader dropdown, the "CSV", "JSON" links used to have an href with the word "undefined" in the middle.
In this CL, we
- only builds an href if a run is selected
- only show the download links if a run is selected
> ui: fix downloader links before run selection

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Slicing by numeric features didn't always give the right result.
If number of buckets >= number of unique values, don't do ranges, slice by unique values.
In this case, make sure to delete bucket range information.
Test in demo crossing the unique value threshold in both directions.
> Fix slicing buckets in WIT

- tensorboard/tools/diagnose_tensorboard.py
Summary:
We teach the diagnosis script that the `tensorflow-tensorboard` PyPI
package provides a `tensorboard` module, and thus must not coexist with
either `tensorboard` or `tb-nightly`.
The `tensorflow-tensorboard` package is a legacy artifact, used only by
versions of TensorBoard prior to 1.6.0. It should usually not be
installed, unless one specifically wants to use old versions of both
TensorBoard and TensorFlow.
Test Plan:
Create a virtualenv, and install into it `tensorflow==1.14.0` (and thus
`tensorboard==1.14.0`) and `tensorflow-tensorboard==1.5.1`. Note that
running `tensorboard --logdir .` fails. Running the diagnosis script
prior to this commit turned up no action items. As of this commit, it
detects the problem and prints an action item with suggested invocations
that do …
> diagnose: warn about `tensorflow-tensorboard`

- tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/core/BUILD
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
- tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
sync: unblock by fixing typing on the Angular code 
1. Although it looks perfectly fine, internal TSC fails to correctly
infer return type of the reducer. We now specify the return type
2. Strict deps on typing/api.
3. Sinon type definition differs and it cannot be correctly typed unless
we convert `sinon.Sinon` to `Sinon.Sinon` which seem very brittle.
Typing to `any` and have a policy to now use jasmine.
sync: remove comment after license as per conformance check
merge plan: squash with two commit messages combined.
> Unblock the sync

- tensorboard/components/tf_ng_tensorboard/core/BUILD
core_jasmine_test is missing a dependency on sinon which is not enforced by Bazel rules.
> sync: missing deps on sinon for core test

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
For jscomp-ignored script, we took a special treatment to place it
before the first script tag we found. Not sure why it is done that way
but it does not seem to cause functional regression.
This change allows us to place a script tag before loading polymer
binary (which is jscomp-ignored) so we can enable the Polymer's
strictTemplatePolicy.
test: clicked around 12 plugins and verified that nothing was borked.
>  vulc: jscomp-ignored script in topological order

- tensorboard/plugins/mesh/README.md
Summary:
The mesh plugin has been available by default since TensorBoard 1.14,
and requires no extra setup or nightly packages locally or in Colab.
Test Plan:
Note that `from tensorboard.plugins.mesh import summary` works in a new
Colab notebook, in a TensorFlow 2.0.0 install, and in a TensorBoard 1.15
install.
wchargin-branch: mesh-install
> mesh: remove obsolete installation instructions

- RELEASE.md
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
The UI could make it clearer when sections in a category-paginated-view are expanded/collapsed at first glance, and indicate that expansion is an affordance.
- Adds an iron-icon to the right of the section heading count that is '>' when collapsed, 'v' when opened
-  Truncates long section names to prevent overflow
-  Gives section name text a tooltip when hovered
-  Only show count if there are multiple items
> ui: add expand arrow to category paginated view

- .travis.yml
- tensorboard/examples/plugins/example_basic/smoke_test.sh
- tensorboard/pip_package/test_pip_package.sh
Summary:
As of 2019-10-03, the `tf-nightly` package includes TensorFlow 2.x, and
the `tf-nightly-2.0-preview` package is not expected to be updated.
Test Plan:
Further occurrences of `git grep tf-nightly-2.0-preview` are in
notebooks, which should be updated separately, and the diagnosis script,
which is correct as is.
wchargin-branch: remove-tf2p
> ci: swap `tf-nightly-2.0-preview` to `tf-nightly`

- tensorboard/components/BUILD
- tensorboard/components/tensorboard.html
- tensorboard/plugins/projector/tf_projector_plugin/BUILD
- tensorboard/plugins/projector/tf_projector_plugin/tf-projector-plugin.html
The strictTemplatePolicy caused regression on hparams dashboard as
vaadingrid was not happy about it.
This change disables the policy for TensorBoard but enables the policy
on one of our dynamic plugin, projector, which is okay with it.
> sec: disable strictTemplatePolicy on TB and enable on projector

- tensorboard/backend/http_util.py
This prevents browsers from guessing correct mimetype and make it follow
the content-type given by the server. Please read [1] for more information.
There was no functional regression from the change.
[1]: http://go/mdn/HTTP/Basics_of_HTTP/MIME_types#MIME_sniffing
> core: add x-content-type-options: nosniff

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/path_prefix.py
- tensorboard/backend/path_prefix_test.py
Summary:
This way, we can reason about and test it in isolation as we add more
middleware to the application.
Note that when using `--path_prefix`, loading the main TensorBoard page
without a trailing slash on the URL has long been broken (#1117). This
commit does not fix that, but changes the exact failure mode: rather
than 404ing, we now load a broken TensorBoard (relative URLs don’t
resolve). A follow-up commit will fix this properly.
Test Plan:
Verify that TensorBoard still works fully, with `--path_prefix` and
without it.
wchargin-branch: path-prefix-middleware
> application: extract path prefix logic to middleware

- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/interactive_debugger_plugin.py
http_util.Respond, instead of werzeug.wrapper.Response attempts to
provide good defaults and require parameters to help make TensorBoard
more secure. This change converts few usage of Response to Respond.
> cleanup: use http_util.Respond

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
1. Internal javac complains about untyped ArrayList which seems to be
inferrable from its assignment.
2. specify charset when reading a file content.
merge plan: squash with updated commit message.
> cleanup: miscellaneous improvements to Vulcanize

- tensorboard/components/experimental/plugin_util/test/tests.html
- tensorboard/components/vz_sorting/test/tests.html
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
All usages of vulcanize-noinline can be replaced with jscomp-ignore so
we decided to deprecate the very similar magical attribute,
vulcanize-noinline.
> cleanup: deprecate vulcanize-noinline

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/colormap-test.ts
- tensorboard/components/tensor_widget/colormap.ts
- tensorboard/components/tensor_widget/demo/demo.html
- tensorboard/components/tensor_widget/demo/demo.ts
- tensorboard/components/tensor_widget/health-pill-types.ts
- tensorboard/components/tensor_widget/menu.ts
- tensorboard/components/tensor_widget/tensor-widget-impl.ts
- tensorboard/components/tensor_widget/tensor-widget.css
- tensorboard/components/tensor_widget/types.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
* Continue developing TensorWidget
* Add menu.ts: Include `FlatMenu` and `Menu` classes.
* Add a default menu item to TensorWdigetImpl, one that allows user to switch between text and image representations of numeric tensors.
* Add colormap.ts: Include the base class `ColorMap` and a basic implementation `GrayscaleColorMap`. The latter is used for image rendering of numeric and boolean tensor values.
* Add minimum and maximum values to `BooleanOrNumericTensorNumericSummary`
* Rename terminology: health pill --> numeric summary
* Update demo.ts.
> [tensor-widget] Add support for hierarchical menu and image view of tensor values

- tensorboard/backend/http_util.py
- tensorboard/defs/vulcanize.bzl
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- tensorboard/plugins/core/core_plugin.py
For our HTML-based resources, we now apply the CSP so we do not load
unknown image, styles, and scripts.
Design choice made:
- the CSP is applied at the http_util with one API to configure the hash
part so no response can set the CSP to "unsafe" and make entire
application unsafe. e.g., dynamic resource is served with "unsafe" and
the unsafe script tag gets loaded which now has access to the parent
frame and exfiltrate.
Future work:
- Turn `'strict-dynamic'` off
- Apply CSP to the projector_binary.html.
- CSP needs to work better with the dynamic plugin. One possibility is
to modify our API so the plugins can define static resources which can
be shasumed by TensorBoard.
- Above logic can introduce more complexity to the core_plugin. We
should consider creating richer asset_provider API so …
> sec: Enable CSP and disallow random script tags

- tensorboard/components/experimental/plugin_lib/BUILD
- tensorboard/components/experimental/plugin_lib/index.ts
- tensorboard/components/experimental/plugin_lib/plugin-guest.ts
- tensorboard/components/experimental/plugin_lib/runs.ts
- tensorboard/components/experimental/plugin_lib/test/BUILD
- tensorboard/components/experimental/plugin_lib/test/test.ts
- tensorboard/components/experimental/plugin_lib/test/testable-iframe.html
- tensorboard/components/experimental/plugin_lib/test/testable-plugin-lib.ts
- tensorboard/components/experimental/plugin_util/message.ts
- tensorboard/components/experimental/plugin_util/test/BUILD
- tensorboard/components/experimental/plugin_util/test/plugin-test.ts
- tensorboard/components/experimental/plugin_util/test/tests.html
we would like to consume the experimental plugin library as a ts_library
(as oppposed to tf_web_library using HTML imports). This change
contains:
1. refactor of lib that uses namespace to module
2. genrule "copy" message.ts due to the build system difficulties
Please turn off the white space changes when reviewing.
supersedes #2727.
This is P1. 
WANT_LGTM=any
> experimental: plugin lib as ts_library

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Show ROC curves for multi-class models.
For each class, we can plot a ROC curve considering the class in question as the positive one and all the others as negatives (what is called a *binarized* version of the problem).
To achieve this, we iterate through all examples, populating an object with the following structure:
```> model > slice > label > threshold > classification stats```
Where the classification data contain the number and rates of true and false positives and negatives. This is done for every value of the threshold (every 1% between 0 to 100%), for every class label, for each feature slice (either each value for categorical features or each interval for numeric features), for every model.
The overall case …
> ROC curves for multi-class (What-If Tool)

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
- tensorboard/plugins/core/core_plugin.py
This is a temporary measure to unblock a high priority item. In the
ideal world, we would want some kind of global CSP configuration that
would also know about all static contents in the application.
> csp: make it globally configurable

- tensorboard/components/experimental/plugin_lib/BUILD
- tensorboard/components/experimental/plugin_lib/message.ts
- tensorboard/components/experimental/plugin_util/BUILD
- tensorboard/components/experimental/plugin_util/message.ts
Due to the difference between internal/OSS behavior of tf_web_library,
we now copy the message.ts over to plugin_util. The issues were following:
- Background:
- Internal tf_web_library disallows .ts in the sources. As a result, we
compile the TypeScript source using TSC and sync in JavaScript variant.
- We ignore this process for tf_ts_library.
- We sync in TypeScript file in plugin_lib
- plugin_util uses message.ts by copying the file over using `genrule`
- Copied TypeScript appears at the srcs of the tf_web_library.
We can make plugin_util source of truth, but in that case, tf_ts_library
would be depend on a compiled JavaScript which is another invariant
violation.
Previous attempts to alleviate the sync issue has been unsuccessful
because I was not careful. This time, I manually ran …
> sync: unblock sync by copying message.ts

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
We now allow `style-src`, `font-src`, and  `img-src` to be configured to allow certain domains.
Also few notable changes are:
1. we now check for whitespaces that can be misused to delimit and bypass some of our check
2. allow path in the whitelist as they have legitimate use cases.
3. we  `default-src: 'none'` and explicitly enable CSP items.
> CSP: allow more CSP fields to be configurable

- tensorboard/BUILD
Summary:
Now that the `absl` dependency is unconditional, we should express it in
the build file, even though this is a no-op in open source. (I meant to
include this in #2758, but forgot to amend it into the commit.)
Test Plan:
None.
wchargin-branch: absl-always-dep
> program: add direct `absl.flags` Bazel pseudodep

- .travis.yml
Summary:
There are no more 1.x nightlies, so this is actually a more recent
version of TensorFlow. In particular, it pins `gast==0.2.2`, which will
probably unblock #2639.
Test Plan:
In a new virtualenv, after running `pip install tensorflow==1.15.0rc3`,
the `//tensorboard/plugins/mesh:summary_v2_test` test passes.
wchargin-branch: pin-tf-1.15.0rc3
> ci: pin TF 1.x to 1.15.0rc3, not nightly

- third_party/workspace.bzl
The version in rules_closure is being removed here: https://github.com/bazelbuild/rules_closure/pull/239
> Consume java_import_external from bazel_tools instead of rules_closure

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
This left margin was added by mistake in #2755.
Simply delete the line added by mistake.
Moving tabs back to where they were:
Open demo and verify that tabs are in the same position as in `master`.
N/A
> Fix tabs left margin (What-If Tool)

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Fix cloud model usage with JSON input, broken in 1.4.1
Do not auto-convert examples before passing to custom predict fn, if the custom predict fn is for CAIP, as that has its own example handling logic.
N/A
Test normal custom predict fn and cloud AI model with JSON input and ensure both work.
> Fix cloud model usage with JSON input

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
- tensorboard/pip_package/setup.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/tf_projector_plugin/BUILD
With enabling CSP on TensorBoard, we have broken projector in few ways.
Because we enforce CSP for all text/html response, we need to have
proper sha256s for all scripts including ones for the projector. Several
fixes are:
1. strict-dynamic -> 'strict-dynamic'
2. 'frame-src' is now set for `iframe src="..."`
3. script hashes are piped in for projector
4. `unsafe-eval` because of numericjs [1].
[1]:
https://github.com/sloisel/numeric/blob/656fa1254be540f428710738ca9c1539625777f1/src/numeric.js#L576-L585
Confession: tested projector before applying stricter rules on _all_ `text/html` before :\. Tested on projector now.
> csp: fix bugs and properly treat projector

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
This bug:
The feature to update `featureValueThresholdsIndexMap` was considering
only the first sliced feature, when it should be using the combined
string.
I also tweaked the function that combines these two values to do strict
comparisons for null and empty strings, because it was considering the
value `0 == ''`, ignoring these values.
Slice by two features in the Performance tab and checking that we don't have those `NaN`s.
N/A
> Fix sliced intersection (What-If Tool)

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
WitWidget cloud users need a way to override the cloud service and service version to send requests to.
Added parameters for service name and version to cloud setup functions, defaulting those parameters to the correct default server.
Ran against default server models and a non-default server model.
> Add ml service name and version for CAIP

- tensorboard/BUILD
- tensorboard/components/tf_backend/tf-backend-polymer.ts
- tensorboard/components/tf_storage/tf-storage-polymer.ts
TensorBoard now enforces very strict CSP and this did have a negative
impact on our tf-ng-tensorboard dev mode. Previously, TensorBoard was
able to skip the Vulcanization step of tf_ng_tensorboard because we were
using rollup bundle anyways. This skipping did improve the incremental
build speed of the Angular app. However, now that CSP infrastructure
is built on top of the Vulcanization tooling (or rather, requires shasum
of all script tags to be computed ahead of time), we are now Vulcanizing
AFTER rollup.
We have longer term plans to improve our CSP/assets story which should
improve this.
> ng: fix the dev CSP issue

- tensorboard/components/vz_example_viewer/vz-example-viewer.ts
Currently turning off counterfactual mode doesn't refresh the example viewer display to remove the counterfactual datapoint.
Turned on and off counterfactuals and moved between examples with counterfactuals on and off. Verified correct behavior.
> When turning off counterfactual, correctly update example viewer

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
frame-ancestors is more modern way of doing x-frame-options which
TensorBoard did not set before and defaulted to allow. We, here, want to
explicitly allow all hosts to iframe TensorBoard inside since we have a
usecase like Jupyter notebooks.
> csp: add frame-ancestors *

- tensorboard/BUILD
- tensorboard/program.py
- tensorboard/program_test.py
- tensorboard/util/BUILD
- tensorboard/util/argparse_util.py
- tensorboard/util/argparse_util_test.py
Summary:
This commit adds a subcommand interface to support invocations in the
manner of `apt-get install` or `git commit`. All existing invocations
remain valid, and are now also available under the `tensorboard serve`
subcommand. Other subcommands may be injected programmatically. For
instance, we could migrate the existing `tensorboard --inspect` to
`tensorboard inspect`, which makes more sense semantically (as it does
something quite different from starting a web server).
To support both `tensorboard --flags` and `tensorboard serve --flags`,
we require some hacks first to get off the ground at all in Python 2,
and then to have sane error messages without massive flag duplication in
all Python versions. Even recent Python versions don’t have a notion of
a _default_ subcommand, so we …
> program: add subcommand CLI support

- tensorboard/defs/protos.bzl
Summary:
This commit teaches `tb_proto_library` a new `has_services` flag. When
set, the proto library will be compiled with gRPC service support, and
an additional `*_py_pb2_grpc` `py_library` target will be created.
The `py_proto_library` macro provided by the protobuf build rules no
longer suits our purpose, as it can only create one `*_py_pb2` build
target that includes both the `*_pb2` and `*_pb2_grpc` Python modules.
This is inconsistent with TensorFlow and some Google internal rules. We
now directly use `proto_gen` rather than using `py_proto_library`. This
is fine: that macro is marked as unstable because its interface may
change, and our goal is precisely to change the interface.
Test Plan:
Run
```
bazel query --output=build \
'filter(".*protos_all.*", //tensorboard/...:all)'
``` …
> proto: enable compiling gRPC services

- tensorboard/program.py
Summary:
With old versions of `argparse`, any `set_defaults` on the base parser
will take precedence over any `set_defaults` on the subparsers. This is
Python [bug #9351][bpo-9351], fixed in [af26c15110b7][fix]. Even though
the versions of argparse bundled with Python 2.7 and 3.5 each include
the fix, we can still avoid this pattern for compatibility.
To see if your Python is affected, run:
```python
import argparse
parser = argparse.ArgumentParser()
parser.set_defaults(test="AFFECTED")
parser.add_subparsers().add_parser("sub").set_defaults(test="OK")
print(parser.parse_args(["sub"]).test)
```
If it prints `AFFECTED`, then this patch affects your Python.
Googlers, see <http://b/143087149> for context.
[bpo-9351]: https://bugs.python.org/issue9351
[fix]: …
> program: don’t set default flags on base parser

- tensorboard/defs/BUILD
- tensorboard/defs/protos.bzl
- tensorboard/defs/tb_proto_library_test.py
- tensorboard/defs/test_base.proto
- tensorboard/defs/test_downstream.proto
Summary:
By happenstance, none of our existing proto definitions need build-level
dependencies (dependencies on proto files from other build targets). But
this is no fundamental restriction. We teach `tb_proto_library` a `deps`
argument, pointing to other `tb_proto_library` macro invocations.
Test Plan:
Unit tests added. After building the Pip package and installing it into
a new virtualenv, we can still use `tensorboard.compat.proto` modules.
wchargin-branch: proto-deps
> proto: support build deps

- tensorboard/components/tensor_widget/colormap-test.ts
- tensorboard/components/tensor_widget/colormap.ts
- tensorboard/components/tensor_widget/menu.ts
- tensorboard/components/tensor_widget/tensor-widget-impl.ts
- tensorboard/components/tensor_widget/tensor-widget.css
- tensorboard/components/tensor_widget/types.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
* Continue developing TensorWidget
* Support Ctrl/Alt/Shift + mouse wheel zooming
* Add an optional field to TensorWidgetOptions: wheelZoomKey to allow specifying whether alt, ctrl or shift key activates wheel zooming.
* Add jet colormap
* Add colormap selection menu
* Added a color bar in the value tooltip that indicates where the currently pointed-to value is within the color scale.
* ![image](https://user-images.githubusercontent.com/16824702/66793119-dbc0a100-eeb0-11e9-950d-a72c2599062c.png)
* ![image](https://user-images.githubusercontent.com/16824702/66793166-04e13180-eeb1-11e9-83d3-123802de1247.png)
* ![image](https://user-images.githubusercontent.com/16824702/66793021-5b01a500-eeb0-11 …
> [tensor-widget] Add colormap selection and Ctrl/Alt/Shift+wheel zooming

- tensorboard/BUILD
- tensorboard/util/BUILD
- tensorboard/util/grpc_util.py
- tensorboard/util/grpc_util_test.proto
- tensorboard/util/grpc_util_test.py
- tensorboard/util/test_util.py
Summary:
This commit adds `tensorboard.util.grpc_util`, which provides methods
for consumers of gRPC services.
Original implementation due to @nfelt.
Test Plan:
Unit tests included. They require that the `grpcio` Pip distribution
(which provides the `grpc` Python package) be installed in the enclosing
virtualenv. This is already a dependency of `tensorboard`, so on typical
setups no additional action should be required.
Co-authored-by: Nick Felt <nfelt@users.noreply.github.com>
wchargin-branch: grpc-util
> util: add `grpc_util` with backoff helper

- tensorboard/components/tf_backend/requestManager.ts
- The simultaneous request limit is not needed, since modern browsers have their own internal connection limit scheme.  (although we need to keep the parameter for BaseStore, which assumes we can only make 1 request at a time).
- Increases simultaneous request limit
WANT_LGTM=stephan
> core: increase frontend active request limit

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/notebook.py
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
proxyPort is a relatively new API that lets colab proxy a server from a
port to url given by the method. It installs a serviceworker when
invoked so a request is proxied to the correct kernel.
This API makes:
1. Colab integration simpler
2. allows an iframe to be nestable and, hence, enable dynamic plugin
With this change, we now removed the colab not supported page.
> colab: use proxyPort for dynamic plugin

- docs/tensorboard_profiling_keras.ipynb
Previous creation of resnet110 used 110 residual blocks and was incorrectly named `resnet10`. Fixing name to resnet110 and using 18 resnet blocks to create a 110 layer network.
> Fix creation of resnet110

- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
- Loading the scalars dashboard results in 2x network requests against data/plugin/scalars/scalars.  It turns out that our [data-loader](https://github.com/tensorflow/tensorboard/blob/418fb939fbf2505f31096eb233896733b4641354/tensorboard/components/tf_dashboard_common/data-loader-behavior.ts#L133) fires on both leading and trailing, so 2 calls to loadData() within 100ms will trigger 2 invocations.
- Also, the simultaneous request limit is not needed, since modern browsers have their own internal connection limit scheme.  (although we need to keep the parameter for BaseStore, which assumes we can only make 1 request at a time).
- Removes the leading call (trailing is true by default)
- Increases simultaneous request …
> core: fix double requests in data loader

- .travis.yml
- tensorboard/BUILD
- tensorboard/main.py
- tensorboard/pip_package/setup.py
- tensorboard/uploader/BUILD
- tensorboard/uploader/auth.py
- tensorboard/uploader/auth_test.py
- tensorboard/uploader/dev_creds.py
- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/logdir_loader.py
- tensorboard/uploader/logdir_loader_test.py
- tensorboard/uploader/peekable_iterator.py
- tensorboard/uploader/peekable_iterator_test.py
- tensorboard/uploader/proto/BUILD
- tensorboard/uploader/proto/export_service.proto
- tensorboard/uploader/proto/scalar.proto
- tensorboard/uploader/proto/write_service.proto
- tensorboard/uploader/test_util.py
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_main.py
- tensorboard/uploader/uploader_test.py
- tensorboard/uploader/util.py
- tensorboard/uploader/util_test.py
Summary:
This commit includes a gRPC client for a hosted TensorBoard service,
which is accessible as a new subcommand under the main `tensorboard`
binary.
Test Plan:
Modify `dev_creds.py` to include credentials, then build the Pip package
(`bazel run //tensorboard/pip_package:extract_pip_package`) and install
it into a new virtualenv. Run
```
tensorboard dev --endpoint ENDPOINT upload --logdir ~/tensorboard_data/mnist
```
where `ENDPOINT` is a running API server (like `localhost:12345`), and
verify that the upload succeeds. Then verify that normal `tensorboard`
still works to serve locally.
Co-authored-by: ericdnielsen <ericdnielsen@gmail.com>
Co-authored-by: Karthik Ramasamy <karthikv2k@gmail.com>
Co-authored-by: Nick Felt <nfelt@users.noreply.github.com>
Co-authored-by: Stanley Bileschi …
> Add uploader gRPC client

- .travis.yml
- tensorboard/pip_package/setup.py
Summary:
We depend on `grpc.local_server_credentials`, which was added in 1.24.0.
Installing the Pip package into a fresh virtualenv generally picks this
up, because the `grpcio >= 1.6.3` will install the latest version, but
that won’t suffice for virtualenvs that already have an old version
installed. We now explicitly depend on `1.24.3`.
Travis wasn’t seeing this problem because the `grpcio-testing` dep pulls
in a matching version of `grpcio`.
Test Plan:
Create a new virtualenv and install `grpcio==1.16.0` (e.g.) into it.
Then, install the TensorBoard Pip package. Run
```
python -c 'import grpc; print(grpc.local_server_credentials)'
```
and note that this now passes instead of failing with `AttributeError`.
wchargin-branch: grpcio-1.24.3
> Bump `grpcio` version to 1.24.3

- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
Repro case
----------
1. load scalars
2. simulate slower network connection (on your favorite browser or
proxy)
3. toggle on a run
4. toggle on another run
5. (depending on the dataset) you should see nothing and line chart
defaults to 0-1 scale.
6. if you double click on the line-chart, the line is shown!
Explanation
-----------
Setting: `dataToLoad` was [a, b] and "changes" to [a, b].
Before:
1. requests for [a, b] goes out
2. before the requests resolve, second `loadDataImpl` gets invoked and
cancels Promises for (1).
3. requests from (1) resolve but because Promise was cancelled, it
does not invoke the `onLoadFinish` and domain is not reset
After:
We now invoke `onLoadFinish` if we ever invoke `loadDataCallback` even
once.
1. requests for [a, b] goes out
2. before the requests …
> scalar: fix the timing issues

- tensorboard/uploader/BUILD
Summary:
The code in question was always Google-owned and licensed as Apache 2.0;
this patch declares that explicitly at the build level.
Test Plan:
Note that this is the same as in (e.g.) `tensorboard/plugins/BUILD`.
wchargin-branch: uploader-license
> uploader: add license directive to build file

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Changing the selected runs should not cause new network requests, when the data to load is already loaded.  This was not the case in dashboards with category items that show multiple runs (e.g. scalars, pr curves).
To avoid unnecessary network requests, this PR makes some CategoryPaginatedView items keyed by tag, instead of the default tag+runs.  When runs change and tag remains constant, the new scheme lets dom-repeat efficiently reuse a template instance.
> core: avoid extra network request upon run selection

- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
Polymer.prototype.async without a wait time defaults to next microtask.
Polymer implemented custom microtask scheduling which is not impervious
to some edge case.
Polymer has some internal counter for the microtasks and the `async`
call returns (contrived for illustration) `currentMicroTaskCounter + i`.
When canelling the async, it checks whether the handle is in between
`currentMicroTaskCounter` and `currentMicroTaskCounter` + [numAsyncs]
and it expects callback to exist when it is in between. The problem
happened when a handle is cancelled twice (our `reset` method gets
called more than once in a microtask for hparams) as it cannot find a
callback for the handle.
reference: https://github.com/Polymer/polymer/blob/dc20feca22ed6915eb67a6df2a8475ceba295de7/lib/utils/async.js#L198-L204 …
> data load: prevent JSE when canceling async

- tensorboard/tools/whitespace_hygiene_test.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/uploader_test.py
- tensorboard/uploader/util_test.py
- third_party/mock_call_assertions.patch
- third_party/python.bzl
Summary:
Some of the `//tensorboard/uploader/...` tests are currently disabled in
Python 2 because our backport of `mock` doesn’t support the required
assertions. We can’t easily upgrade the dependency (see #2132), but we
can backport those assertions. The assertions backported are:
- `assert_not_called`
- `assert_called`
- `assert_called_once`
This patch is the combination of (restrictions of) the following
upstream Git commits:
- [`c7d6c7dcafd4482626194528b24f174dd15f5f5e`][1] (2014-04-17)
- [`8882c2fccb9f7d3b8ba2b5534c0dd9d52343725f`][2] (2014-04-17)
- [`7ca5d3afe293d5e4d769c1cb2dfccb0688ba1292`][3] (2016-03-11)
- [`07532a75003ec8e871e494f9f1ab8f28fa246f08`][4] (2018-01-19)
I identified those commits by diffing our pinned version of `mock.py`
(the version at upstream commits `b14e284` …
> Backport `mock` assertions for Python 2 tests

- tensorboard/uploader/uploader_main.py
Summary:
We now emit a nice message so that users don’t think that the uploader
has hung, and we avoid crashing when the user does interrupt it.
Test Plan:
Ran and then cancelled an upload, and saw the following logs:
```
Upload started and will continue reading any new data as it's added
to the logdir. To stop uploading, press Ctrl-C.
View your TensorBoard live at: http://localhost:1234/experiment/123
^C
Upload stopped. View your TensorBoard at http://localhost:1234/experiment/123
```
…after which the process exited with 0.
wchargin-branch: uploader-forever
> uploader: clarify that uploads run forever

- .travis.yml
Summary:
This reverts commit e4a70498e833ba50a008db20a48f1444abb2fa84.
Test Plan:
CI suffices.
wchargin-branch: unpin-estimator-20190917-nightly
> ci: unpin 2019-09-17 estimator nightlies

- tensorboard/uploader/auth.py
- tensorboard/uploader/dev_creds.py
Summary:
In versions of Python 3 prior to Python 3.6, `json.dumps` must take a
Unicode string as argument. (This was relaxed in [bpo-17909].)
[bpo-17909]: https://bugs.python.org/issue17909
Test Plan:
In a Python 3.5 virtualenv, run `tensorboard dev auth revoke`, then run
`tensorboard dev upload --logdir /tmp/whatever`. Note that the OAuth
flow now works properly rather than failing with a `TypeError`. Note
that the only other use of `json.loads` under `tensorboard/uploader/` is
in `exporter_test.py`, and that test passes on Python 3.5.
wchargin-branch: uploader-oauth-unicode
> uploader: parse JSON from Unicode for Python 3.5

- tensorboard/uploader/uploader_main.py
Summary:
The correct invocation is `auth revoke`, not `--auth_revoke`, which was
a vestige of a previous formulation.
wchargin-branch: uploader-auth-revoke-text
> uploader: fix `auth revoke` help suggestion

- tensorboard/uploader/BUILD
- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/util/BUILD
- tensorboard/util/grpc_util.py
- tensorboard/util/grpc_util_test.py
Summary:
This will enable servers to detect when clients are using an old version
and send instructions to show the user how to upgrade, especially in the
case of known bugs.
We could implement this with gRPC’s client-side interceptor API, but
that API is loudly disclaimed as experimental, so I’ve gone with the
manual plumbing for now.
Test Plan:
Ran the new uploader with an existing server and verified that it still
works (extra metadata is safely ignored). Verified that a server can
be modified to read this metadata for all three flows (upload, delete,
export). Tested in both Python 2 and Python 3.
wchargin-branch: uploader-version
> uploader: include TensorBoard version in RPCs

- tensorboard/BUILD
- tensorboard/components/BUILD
- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/app.module.ts
- tensorboard/components/tf_ng_tensorboard/settings/settings_button.component.ts
- tensorboard/defs/defs.bzl
- tensorboard/tools/BUILD
- tensorboard/tools/mat_bundle_icon_svg.sh
- third_party/js.bzl
mat-icon allows many options for loading the assets. For TensorBoard, we
would like to use, instead of a CDN, the embeddable option and serve
either icon-font or SVG from our server.
This change adds dependency on google/material icon repository and
create a build rule similar to that of the internal rule to create a SVG
bundle out of many SVG icons.
> ng: load material icon sources

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Ensure examples are copied out of the config before we set the config object, to avoid errors in Jupyter notebooks.
Remove examples item from config before setting self.config in order to avoid passing the examples as JSON to the front-end, which can cause parse errors and shouldn't be done.
N/A
Test notebooks in both jupyter and colab to ensure correct initialization and rendering. The regression was only tested in colab which was the cause of this. Moving forward, no PR will only be tested in one environment.
N/A
> Fix set examples in jupyter

- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
Summary:
Given `export --outdir "${path}"`, we run `makedirs(dirname(path))`. But
this fails when `dirname(path)` is empty, which occurs when `path` has
no directory separator.
Test Plan:
Unit test added: it fails before this change and passes after it.
wchargin-branch: export-no-slash
> uploader: fix export when outdir has no slash

- tensorboard/uploader/uploader.py
Summary:
Typical requests now include ~4700 scalars instead of ~37000 scalars
(and are correspondingly processed faster by the server). This is now
reliably hitting the client-side rate limiting, so we’re sending one
request per 5 seconds.
Test Plan:
The following patch is useful for testing:
```diff
diff --git a/tensorboard/uploader/uploader.py b/tensorboard/uploader/uploader.py
index 1a6e7951..c3191746 100644
--- a/tensorboard/uploader/uploader.py
+++ b/tensorboard/uploader/uploader.py
@@ -130,6 +130,10 @@ class TensorBoardUploader(object):
request_bytes = request.ByteSize()
-      logger.info("Trying request of %d bytes", request_bytes)
+      total_scalars = sum(
+          len(tag.points) for run in request.runs for tag in run.tags)
+      logger.warning(
+          "Trying request …
```
> uploader: change request batch size to 128 KiB

- tensorboard/uploader/BUILD
- tensorboard/uploader/exporter.py
- tensorboard/uploader/proto/export_service.proto
- tensorboard/uploader/proto/write_service.proto
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_main.py
Summary:
This includes the Terms of Service link in the consent screen, as well
as the explicit disclaimer that all uploaded data is publicly visible.
It also patches the help text (`tensorboard -h`, `tensorboard dev -h`).
Test Plan:
Running `git grep "a hosted"` (…service) no longer returns any results.
wchargin-branch: tensorboard.dev
> uploader: add TensorBoard.dev branding

- tensorboard/uploader/uploader_main.py
Test Plan:
Build the Pip package and install it into a new virtualenv. Using the
new package, revoke auth (`tensorboard dev auth revoke`), then upload an
experiment. Note that the correct Terms of Service and Privacy Policy
documents are clearly displayed in the consent prompt.
wchargin-branch: uploader-prod
> uploader: set default endpoint to production

- tensorboard/uploader/proto/export_service.proto
Export service definition has changed slightly in that all scalars for a given tag are not necessarily all in the same response.  This is to support tags that are too big, for one reason or another, to fit into a single response.
This change updates the comment to reflect the change in understanding.
> Fix comment in export.proto

- tensorboard/uploader/BUILD
- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/uploader_main.py
Large experiments sometimes fail to export due to grpc timeouts.  This change clarifies the situation to the user.
Tested:
Adds unit tests for grpc.CANCELLED case.
> Improve error handling for exporting large experiments

- tensorboard/uploader/uploader_main.py
Summary:
We’ll have a redirect in place, but we’d prefer that this be the
canonical path.
wchargin-branch: uploader-terms-slash
> uploader: link to `/policy/terms/`, not `terms.html`

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Notice: this change only applies when Google Analytics is enabled which,
in OSS, it is not.
This change allows path like /experiment/abc to be logged as
/experiment/abc/scalar.
Do note that, according to [Google Analytics API doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages), `ga('set', 'page',
arg)` is a way of modifying page url often to sanitize PII from the
path. This impacts all subsequent events like pageview or others.
> analytics: send pathname on pageview event

- docs/tensorboard_in_notebooks.ipynb
Confirmed that all ipynb have valid JSON by running below.
```sh
find docs -iname "*.ipynb" | xargs jq . 1>/dev/null
echo $?
```
WANT_LGTM=any
> docs: fix invalid json

- tensorboard/components/experimental/plugin_lib/BUILD
- tensorboard/components/experimental/plugin_lib/test/BUILD
- tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/BUILD
The failing test was not detected by either internal or external CI, for reasons partially understood.
> Fix minor test failure re plugin_lib/test

- tensorboard/backend/application.py
- tensorboard/default.py
- tensorboard/plugins/base_plugin.py
- tensorboard/program.py
One step towards improving plugin authoring is to understand and document the public interfaces.  Authors can write a class that extends base_plugin's `TBLoader`, but its `load()` method was not documented.
Adds a base class method `TBLoader.load()` and updates some related docstrings.
> docs: fix annotations related to TBLoader

- tensorboard/plugins/histogram/summary_v2.py
Manually place bucketing logic in writing histogram to CPU when TPUStrategy is used.
`_buckets()` generates a graph with dynamic shapes which are not supported on TPU. As so, place the function in outside compilation cluster when TPUStrategy is in scope.
> Place histogram bucketing logic on CPU explicitly when using TPUStrategy

- tsconfig.json
VSCode on Mac was getting hung up with 'Initializing JS/TS language features'.  Apparently it was trying (and failing) to walk the `bazel-*` directories that are left after any bazel build.  Excluding those directories from processing via `tsconfig.json` is completely harmless, and restores normal VSCode functioning.
> Make VSCode resolve imports in node_modules instead of bazel-*

- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/audio/summary_v2.py
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/summary_v2.py
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/summary_v2.py
- tensorboard/util/BUILD
- tensorboard/util/lazy_tensor_creator.py
- tensorboard/util/lazy_tensor_creator_test.py
Continuation of PRs #2893, #2894, #2895 by @hongjunChoi .
This takes advantage of a recent change in `tf.summary.write()` as of https://github.com/tensorflow/tensorflow/commit/661f0ac0015184e970f9a3f04e845a9166ebfa7a that allows passing a callable as the `tensor` argument instead of an actual `tf.Tensor`.  With this functionality, `write()` will call the callable to get the tensor only if the tensor is going to be used (i.e. the summary writer exists and the summary recording condition is met).  This avoids overhead in executing preprocessing steps when they are not needed.  Among V2 summaries, only image, audio, and histogram do any real preprocessing, so those are the only ones changed in this PR.
In order to maintain backwards compatibility with the previous `write()` API, this …
> Defer image/audio/histogram v2 summary preprocessing using LazyTensorCreator

- tensorboard/examples/plugins/example_basic/README.md
Motivation for features / changes
In an attempt to improve the onboarding experience for plugin authors, this updates the documentation describing the process.  Changes include:
- Added section on Plugin Lifecycle
- Added code sample showing bare-structure of TBPlugin, TBLoader
- Added documentation on TBContext, EventMultiplexer, frontend_metadata
Sub goals of this change are to:
- More comprehensive coverage of public API in a single place
- Reduce the need to read internal TensorBoard source code
- Focus more on backend API.  In the future, cover frontend with more examples
If the diff is hard to read, a preview can be [found here](https://github.com/psybuzz/tensorboard/tree/docs1/tensorboard/examples/plugins/example_basic)
> docs: update docs for dynamic plugin authors

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-age-demo.html
Want one of our web demos to show attributions
Have regression demo calculate and return attributions to WIT by using vanilla gradients from prediction to input vector.
Ran demo and viewed appropriate attributions displayed.
> Update WIT regression demo with attributions

- tensorboard/BUILD
- tensorboard/pip_package/setup.py
- tensorboard/uploader/BUILD
- tensorboard/uploader/proto/BUILD
- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
Summary:
This commit adds an RPC definition by which the uploader can connect to
the frontend web server at the start of an upload session. This resolves
a number of outstanding issues:
- The frontend can tell the uploader which backend server to connect
to, rather than requiring a hard-coded endpoint in the uploader.
- The frontend can tell the uploader how to generate experiment URLs,
rather than requiring the backend server to provide this information
(which it can’t, really, in general).
- The frontend can check whether the uploader client is recent enough
and instruct the end user to update if it’s not.
- The frontend can warn the user about transient issues in case the
service is down, degraded, under maintenance, etc.
An endpoint `https://tensorboard.dev/api/uploader` on the server …
> uploader: add `ServerInfo` protos and logic

- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/uploader_main.py
Summary:
The new `tensorboard dev list` command prints links to your experiments.
This is implemented by repurposing the `StreamExperiments` export RPC,
which only includes experiment IDs. We can expand this to additionally
show useful metadata: experiment creation time and last-modified time;
total number of scalars; counts of runs, tags, or time series; and
selected run and tag names could all be useful to include.
Test Plan:
Ran `tensorboard dev list` on an account with 12 experiments and an
account with no experiments, starting from both logged-in and logged-out
states. Verified that the printed experiment links resolve correctly.
Verified that the normal export flow still works.
wchargin-branch: uploader-list
> uploader: add simple `list` subcommand

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Adjust position, color and behaviour of the counterfactual controls in the WIT dashboard.
cc @jameswex and @mpushkarna 
Most changes come from discussions with Mahima.
Add an input box to the slider (and remove its pin), make a separate info box for the threshold, rename *Delta* to *Threshold*, disable the slider when the feature is switched off, and adjust the CSS (color, position, font size).
Most changes are merely visual: just open the tool for a regression model, so that the slider also appears.
Besides that, switch the counterfactual toggle on and off and check that the slider behaves accordingly.
* Alternate …
> Improve usability and design of counterfactual controls (What-If Tool)

- .travis.yml
Summary:
I never got around to investigating why these were broken (I couldn’t
reproduce the failure locally and didn’t have time to investigate on
Travis). The failures appear to be fixed now.
This reverts commit 9b188c1bd4b9747f7c6f130f45dd18901a9831d7.
Test Plan:
CI suffices.
wchargin-branch: unpin-20191023-nightly
> ci: unpin 2019-10-23 nightlies

- tensorboard/webapp/BUILD
- tensorboard/webapp/core/effects/BUILD
- tensorboard/webapp/header/BUILD
- tensorboard/webapp/reloader/BUILD
- tensorboard/webapp/settings/BUILD
Two copypasta dependencies broke our internal sync.
Also, internally we enforce strict deps, so I added a bunch that were transitive before. 
There are probably more unused deps that we can clean up later, but that are not blocking as far as I know.
> Remove unused deps blocking sync

- tensorboard/plugins/core/core_plugin.py
This changes the default value from `False` to `None`, which doesn't change the semantics or interpretation (since we check it with `if flags.reload_multifile` so both False and falsy-None will fail that check), but does mean that other code can distinguish whether we're truly using the default or whether `--reload_multifile=false` was explicitly passed on the command line.  This means we can effectively change the flag from opt-in to opt-out in some contexts by setting the flag value to `True` if it's still `None` after parsing.
> Make --reload_multifile default value falsy None instead of False

- tensorboard/webapp/settings/dialog.component.test.ts
Jasmine's toBeTruthy is not a fluent version of mocha's `to.be.true`. It
asserts, as the name suggest, the value is truthy. It is an anti-pattern
to assert using toBeTruthy and one must always  use `toBe(true)`
instead.
> cleanup: assert using value, not casting

- tensorboard/BUILD
- tensorboard/version_test.py
Summary:
This prevents us from accidentally changing our version number to a
non-standard format, which would prevent it from being parsed correctly
by standard functions.
Test Plan:
The test passes as written, and also passes when changing the version
number to `2.1.0.dev20191109` (our `tb-nightly` version scheme), but
fails when changing the version number to `2.1.0a0a`.
wchargin-branch: version-pep440-test
> version: add safety check for PEP 440 compliance

- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
Test Plan:
Running against a local frontend server, `tensorboard/2.1.0a0` shows up
in the server logs where previously there was `python-requests/2.22.0`.
Unit tests also included.
wchargin-branch: uploader-user-agent
> uploader: set user agent for frontend handshake

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/security_validator.py
- tensorboard/backend/security_validator_test.py
http_util enforces good practice in term of security to prevent content
sniffing and the content security policy. However, this is not
enforceable for other plugins.
With this middleware, we would like to tell developer to enhance the
security to protect users. When we go 3.0, we may convert the warns into
hard failures.
> core: security validator middleware

- tensorboard/webapp/BUILD
- tensorboard/webapp/core/effects/BUILD
- tensorboard/webapp/core/store/BUILD
- tensorboard/webapp/core/store/core.reducers.test.ts
Especially when we leverage Angular's module system, we need to use the
ng_module build rules to generate all necessary factory method. Although
it is yet unclear exactly why Angular's JIT compilation does not work
under node environment, the team decided to migrate all tests to the
karma based tooling.
This change addresses:
1. jasmine_node_test to karma_web_test (2 are remaining on tensor
widget)
2. fixed core effects that was using ts_library as oppposed to ng_module
(our app was broken because CoreEffectsModule did not get deps correctly
injected in)
3. migrated off of chai/sinon:
This is tricky and requires some explanation. Normally, when running
test with the karma executor, one would use webpack or its
equivalent to build the binary. This should resolve all packages like
React or …
> cleanup: migrate test over to karma based tooling

- tensorboard/backend/security_validator_test.py
Summary:
This works as written in OSS, but must be imported directly from
`werkzeug.wrappers` internally.
Test Plan:
Googlers, see <http://b/144590350>.
wchargin-branch: security-validator-werkzeug-import
> sync: fix Werkzeug `BaseResponse` import

- tensorboard/defs/BUILD
Summary:
Currently, implicitly exported source files inherit the package default
visibility. The Bazel team intends to change this such that they are
instead package-private by default. For details, see:
<https://github.com/bazelbuild/proposals/blob/master/designs/2019-10-24-file-visibility.md>
This commit updates our build files to be compatible with that change.
cc @aehlig
Test Plan:
Googlers, see test sync: <http://cl/281077794>.
wchargin-branch: build-explicit-export
> build: explicitly export files used by other packages

- tensorboard/BUILD
- tensorboard/components/BUILD
- tensorboard/defs/vulcanize.bzl
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- tensorboard/webapp/BUILD
This change adds an ability to create JavaScript file from
Vulcanization. This is in response to code debt we accrued while adding
Content Security Policy. We decided to keep CSP simple by, instead of
computing shasum on individual script block, serving JavaScript from our
server and have "script-src 'self'".
This change does not yet remove an ability to use shasum but it will be
quickly deprecated afterwards.
Tested the change internally by making changes directly:
cl/280296740
> build: create JavaScript file from Vulc

- tensorboard/components/tf_card_heading/tf-card-heading.html
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
More details here: https://github.com/tensorflow/tensorboard/issues/2935
Enforcing resin causes several styles in TensorBoard to misbehave
because it fails to correctly sanitize content of the `style` attribute.
We use different techniques (such as CSS variable and imperative
JavaScript) to workaround the issue.
This change only addresses the issues on scalars and custom scalars
dashboard.
> polymer: (partial) remove data binding on style

- docs/_project.yaml
Because it's not need here.
See b/144359208 and cl/280710307 for context.
> Remove project metadata file from docs

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
As per our revised design on CSP, we decided to trust everything that
comes from our server. This change lax the style-src requirement a
little to trust styles from the server.
> csp: allow style to be served from 'self'

- tensorboard/uploader/uploader_main.py
Summary:
We’ve deployed production servers that support the handshake protocol
specified in #2878 and implemented on the client in #2879. This commit
enables that protocol by default.
Test Plan:
Running `bazel run //tensorboard -- dev list` still properly connects
and prints valid URLs. Re-running with the TensorBoard version patched
to `2.0.0a0` (in `version/version.py`) properly causes a handshake
failure. Setting `--origin` to point to a non-prod frontend properly
connects to the appropriate backend. Setting `--api_endpoint` to point
to a non-prod backend connects directly, skipping the handshake, and
printing `https://tensorboard.dev` URLs. Specifying both `--origin` and
`--api_endpoint` performs the handshake and overrides the backend
server only, printing URLs corresponding to the …
> uploader: enable handshake by default

- tensorboard/tools/diagnose_tensorboard.py
Summary:
Networking is hard. Everyone’s machine seems to do something different.
We have a lot of special cases in `program.py`, and we keep finding new
configurations. This commit adds a check to `diagnose_tensorboard.py`
that prints the available loopback and wildcard addresses on all address
families.
It could also be nice to check whether it is actually possible to
connect to sockets opened on the loopback address in various
configurations (e.g., with a direct socket-to-socket connection and with
a Python-provided WSGI server and URL fetcher). We defer such a change.
Test Plan:
On my machine, with Python 3, it prints:
```
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = …
```
> diagnose: add check for `getaddrinfo`

- tensorboard/defs/defs.bzl
- tensorboard/defs/web_testing.bzl
- tensorboard/functionaltests/BUILD
Summary:
Web tests take a long time to Vulcanize and run, and some have very
wide-reaching dependencies. For example, `core_test_chromium` depends on
all of `//tensorboard`. They’re also especially flaky when many of them
are run concurrently, as they run out of resources even on capable
machines. All this makes `bazel test //tensorboard/...` prohibitively
expensive for quick incremental iteration. This commit adds build tags
such that one can write
bazel test //tensorboard/... --test_tag_filters=-webtest --build_tests_only
to run all affected tests except web tests. (Using `--build_tests_only`
prevents Vulcanization of targets that match the `//tensorboard/...`
pattern but are only needed by tests tagged as `webtest`.)
Test Plan:
This query used to return all the web tests, and now …
> build: tag all web tests with "webtest"

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Summary:
Arguments to `Vulcanize.java` were previously parsed with hard-coded
indices. Adding an additional argument required manually fixing up all
subsequent indices, which is error-prone and pollutes the blame. This
commit replaces integer literals with a simple counter variable.
Test Plan:
Running `bazel run //tensorboard -- --logdir ~/tensorboard_data/mnist`
still works.
wchargin-branch: vulc-argv
> vulc: simplify argument parsing

- tensorboard/uploader/server_info_test.py
Summary:
On some machines, including standard Ubuntu 16.04, binding to `::1` and
then trying to open an HTTP connection to `localhost` can in some cases
try to connect only over IPv4, which fails. This commit changes a test
to connect to the node name given by the socket rather than hard-coding
`localhost`.
Test Plan:
Tested in an upcoming GitHub Actions workflow. Googlers, see test sync:
<http://cl/281679857>
wchargin-branch: serverinfotest-nodename
> Respect nodename in `server_info_test`

- tensorboard/backend/experiment_id_test.py
Summary:
Empty experiment IDs are handled just like non-empty ones. This is an
edge case that was being handled as intended, but should have a test to
clarify that this is in fact the desired behavior. This commit adds such
a test.
Test Plan:
Newly added test passes.
wchargin-branch: backend-empty-eid-test
> backend: document behavior on empty experiment IDs

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
- tensorboard/defs/vulcanize.bzl
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- tensorboard/pip_package/setup.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/tf_projector_plugin/BUILD
As part of our security hardening and CSP support, we decided to
introduce script checksum as part of the Vulcanization that gets used at
the serving time using http_util.py. We understand that this imposes
a bit too stringent requirements for all and we decided to relax the CSP
comformance a little by trusting JavaScript from our server
(effectively, default-src 'self').
Note that we do not yet remove shasum related code from http_util
because it is being used by the Plugin HTML endpoint in application.py.
For that, we may want to use nonce or separate JavaScript file approach.
> build: deprecate shasum in Vulcanization

- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
If a model returns multiple predictions in a dictionary, make the parsing of this dictionary more fool-proof, improve error statements, and simplify parsing of binary classification results.
For both AI platform models and estimators, if the model returns a dictionary of results and the dictionary only has one key, use that result automatically instead of requiring the user to specify the key name of that only result.
Add more-detailed error string in the case of not being able to parse prediction results correctly.
Use repr(error) instead of str(error) to get better displayed errors in WIT from the backend.
If a classification model only returns a single class score, auto-convert that to be the class score for class 1 …
> Improve WIT parsing of model results

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
Instead of component-level listener for dom-change, we now put the
listener on the specific template (dom-if or dom-repeat) that we care
about.
> cleanup: set targeted dom-change listener

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
Apps that embed TensorBoard backend can now configure `frame-src`, to allow the frontend to render iframes from contexts other than self.
Adds _CSP_FRAME_DOMAINS_WHITELIST.
> csp: allow frame-src to be configured

- RELEASE.md
One commit to round out the 2.0.2 release process: cherry-pick of
2.0.2 relnotes added to RELEASE.md.
> Post-release 2.0.2

- DEVELOPMENT.md
Summary:
Running `bazel run //tensorboard` per the development instructions spits
out warnings in the TensorFlow layer. These warnings are accurate, but
not relevant, so we advise users to ignore them.
Test Plan:
Note that the link resolves correctly.
wchargin-branch: dev-spurious-warnings
> docs: quell fears about spurious warnings

- tensorboard/data/__init__.py
- tensorboard/defs/__init__.py
- tensorboard/examples/plugins/example_basic/__init__.py
- tensorboard/functionaltests/__init__.py
- tensorboard/plugins/interactive_inference/witwidget/pip_package/__init__.py
- tensorboard/tools/__init__.py
- tensorboard/uploader/__init__.py
Summary:
Bazel generates these automatically, but having them in the source tree
is convenient for REPLs and tools like `pydoc`.
Generated with:
```
find tensorboard -type f -name '*.py' |
xargs -n 1 -d '\n' dirname |
sort -u |
xargs -n 1 -d '\n' sh -c 'cp -n tensorboard/util/__init__.py "$1/"' cmd
```
Test Plan:
Running `pydoc tensorboard.data.provider` after this commit successfully
shows useful docs; before this commit, it fails with, “no Python
documentation found for 'tensorboard.data.provider'”.
wchargin-branch: empty-init-py
> Add empty `__init__.py`s where missing

- tensorboard/uploader/util_test.py
Summary:
We mocked out the time zone to UTC for only one of two time-related
function calls. This was asymptomatic externally because [Bazel’s test
runner sets the `TZ` environment variable to `UTC`][1], but the internal
test runner has different semantics.
Test Plan:
Patching this into a sync CL fixes broken tests.
[1]: https://docs.bazel.build/versions/1.2.0/test-encyclopedia.html#initial-conditions
wchargin-branch: util-test-tz
> uploader: fix `util_test` internally

- tensorboard/examples/plugins/example_basic/BUILD
Summary:
See <https://github.com/tensorflow/tensorboard/issues/2987> for context.
Test Plan:
That CI passes suffices.
wchargin-branch: disable-dynplugin-smoke
> Temporarily disable dynamic plugin smoke test to unbreak build

- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/distribution/distributions_plugin.py
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
Summary:
We now raise `errors.NotFoundError` rather than manually propagating an
error message and status code.
The response code was previously 400 Bad Request, but 404 Not Found is
more appropriate, and is consistent with the scalars plugin.
Test Plan:
Requesting `/data/plugin/histograms/histograms?run=foo&tag=bar` yields
an error with the same message as before (but now with a “Not found:”
prefix), and the histograms and distributions dashboards both work.
wchargin-branch: histograms-notfound
> Use `tensorboard.errors` in histograms and distributions

- README.md
Fixes broken links
Adds a way to play with a tensorboard without installing anything.
Just some readme fixes.
> documentaion: Update tensorflow tutorial links.  Add a link to hosted TensorBoard

- docs/tbdev_getting_started.ipynb
Extends getting started example to include 'list' and 'delete' subcommands.
Users didn't know they could list / delete.
Adds a few new cells.
> (colab) Add 'list' and 'delete' to tbdev

- tensorboard/plugins/projector/vz_projector/umap.d.ts
- third_party/js.bzl
Updating umap version to match internal google version.
Just a change to js.bzl
n/a
Manually tested with bazel run tensorboard/plugins/projector/vz_projector:devserver. All seemed to be in order.
n/a
> updating umap version

- tensorboard/backend/event_processing/data_provider.py
Summary:
Per suggestion of @nfelt in post-review comment on #2980. This way, the
functions are only defined once.
Test Plan:
Unit tests pass.
wchargin-branch: mux-toplevel-read-helpers
> data: define `convert_*_event` at module level

- tensorboard/components/BUILD
- tensorboard/components/vz_line_chart2/BUILD
In order for WIT to move to a dynamic plugin, some build rules need to be made visibility public so WIT build can use them.
Building current draft of WIT dynamic plugin in its own repo and needed access to these rules.
> Expose visibility for build rules needed for WIT dynamic plugin

- tensorboard/defs/web.bzl
Summary:
The `+`, `+=`, and `|` operators on depsets, as well as `depset.union`,
are deprecated due to performance problems:
<https://github.com/bazelbuild/bazel/issues/5817>
As of a recent Bazel commit, `.union` is removed is removed entirely, so
the operators may be soon on the chopping block:
<https://github.com/bazelbuild/bazel/commit/693963f44ad2d62d858a24ed5dad4698d3835223>
This commit removes remaining uses from TensorBoard.
Google-internal source: <http://cl/283060975> (thanks, @laurentlb!).
Test Plan:
Running `bazel run //tensorboard` still works.
Co-authored-by: Laurent Le Brun <laurentlb@google.com>
wchargin-branch: remove-depset-union
> web.bzl: avoid depset union operators

- DEVELOPMENT.md
Summary:
Running Python binaries directly through `bazel-bin/` skips the Bazel
wrapper that sets up the environment correctly. This is not guaranteed
to work; users should run `bazel run //tensorboard --` instead.
We included the `bazel-bin/` form before `bazel run` was changed to
release the Bazel server lock, but this was fixed in 2017:
<https://github.com/bazelbuild/bazel/issues/2337>
…so there’s no longer really any reason to promote this form at all.
wchargin-branch: docs-no-bazel-bin
> docs: remove outdated `bazel-bin` instructions

- tensorboard/backend/event_processing/data_provider.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
Experiment IDs must be passed to the data provider, but the multiplexer
provider doesn’t actually need them, so code that forgets to pass the ID
will be silently broken on other providers. This commit updates the
multiplexer provider to explicitly fail when the ID is omitted.
This would have caught bugs in earlier drafts of both #2981 and #2991,
which were written by different people, so clearly the mistake is easy
to make. :-)
Test Plan:
Running with `--generic_data true`, the scalars, histograms, and
distributions dashboards all still work. The graphs dashboard has the
same error as prior to this change (see comments on #2991). Unit tests
have been updated to always pass experiment IDs.
wchargin-branch: muxprovider-safety-eid
> data: require experiment ID in multiplexer provider

- RELEASE.md
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/event.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/util/grpc_util_test.py
- tensorboard/version.py
Four commits to round out the 2.1.0 release process:
- Bump tb-nightly version to 2.2.0a0
- Cherrypick of 2.1.0 relnotes added to RELEASE.md
- Cherrypick the TF proto sync
- Fix a GRPC test that amusingly choked on the version change from 2.1.0a0 to 2.2.0a0.
> Post-release 2.1.0

- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
This fixes the bug in #2991 found by @wchargin.
More importantly, it fixes the test that should have caught that bug in the first place (which has been broken since #1853): expected and actual data were being compared with `assertItemsEqual` instead of `assertEqual`, and so differences were not detected.
> Fix graph plugin with data provider, and its test

- README.md
Summary:
We’ve migrated from travis-ci.com back to travis-ci.org. This restores
the old badge URL, which is still the correct URL as autogenerated by
the Travis UI.
This reverts commit 9b6e29e7c5619e41da1fb29e466a83254333d0a6.
Test Plan:
The link resolves to a valid image, which marks the build as “passing”.
wchargin-branch: readme-ci-badge-org
> readme: update Travis badge to travis-ci.org

- docs/_index.yaml
Replaces an older blog post with a link to the newer blog post about TensorBoard.dev
Purely a documentation change.
> Add link to TensorBoard.dev from tensorboard base page.

- tensorboard/notebook.py
Fixes #3015
Simply imports `html` instead of `cgi` if our Python version is 3.8 or newer, keeps `cgi` otherwise in order to maintain backwards compat.
Importing `html` as `cgi` is kinda ugly IMO, but I'm not really sure on how to fix it without having another if condition when calling `escape()`.
Another option would be to do `from html import escape`, but it seems that it'd break the code style currently going on for external libraries.
> notebook: fix `cgi.escape` for Python 3.8

- tensorboard/webapp/plugins/plugins.component.ts
TypeScript on [1] removed the null type on CSSStyleDeclaration.display.
As a result, our code violates the type checking when we do
`element.style.display = null`. Fixed it.
[1]:
https://github.com/microsoft/TypeScript/commit/29becf05012bfa7ba20d50b0d16813971e46b8a6
Co-authored-by: Martin Probst <martin@probst.io>
> Fixed the typing on ts 3.7+

- tensorboard/webapp/plugins/plugins.component.ts
1. Cannot set `src` without TrustedURL. Fixed it by tricking the
conformance checker for now.
2. `SimpleChanges` is an object whose keys are names of the input or prop.
Prevent variable mangling by accessing via square brackets.
> ng: fixed the TS conformance issue

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/custom_scalar/summary_test.py
- tensorboard/plugins/debugger/debugger_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager_test.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/profile_plugin_test.py
- tensorboard/plugins/projector/projector_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/plugins/text/text_plugin_test.py
Summary:
Per suggestion of @nfelt on #2967. We don’t use Pylint for line length,
and Google style says that imports are exempt from line length limits,
anyway.
Generated with:
```
git ls-files -z '*.py' |
xargs -0 sed -i -e '/from.*import/s@ *# pylint: disable=line-too-long$@@'
```
Test Plan:
Our standard lint still passes:
```
$ flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
0
```
wchargin-branch: unsuppress-long-imports
> pylint: remove long-line suppressions on imports

- tensorboard/backend/application_test.py
- tensorboard/manager_test.py
Summary:
Python has historically been lax about invalid escapes: `"m\n\o"` is a
four-character string `m<Newline><Backslash>o`. As of Python 3.8, this
is a syntax warning. These can all be fixed by explicitly escaping the
backslashes or just using raw strings.
Test Plan:
All of our Python files now parse without warning on Python 3.8:
```
~/git/cpython/python - <<EOF
import ast
import glob
for f in glob.glob("tensorboard/**/*.py", recursive=True):
ast.parse(open(f).read(), filename=f)
EOF
```
wchargin-branch: fix-py38-escapes
> python: fix invalid escape sequences

- tensorboard/compat/tensorflow_stub/errors.py
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/debugger/debugger_server_lib.py
- tensorboard/plugins/interactive_inference/interactive_inference_plugin_loader.py
Summary:
In ec7e68d543a6, we removed `line-too-long` suppressions on import
lines. Most of the remaining `line-too-long` suppressions are also
unneeded, either because they’re around blocks of imports or because
none of the lines that they encapsulate is too long.
Test Plan:
The two remaining matches for `git grep line-too-long` are legitimate.
wchargin-branch: unsuppress-long-import-blocks
> pylint: remove unnecessary long-line suppressions

- tensorboard/pip_package/build_pip_package.sh
Summary:
Our `//tensorboard/pip_package` target is *almost* built hermetically.
It turns out that the only source of skew is file timestamps in the zip
archive. Setting `SOURCE_DATE_EPOCH` fixes that:
<https://github.com/pypa/setuptools/issues/1468>
Test Plan:
The wheels and their container archive are now bit-for-bit hermetic, at
least on my machine:
```
$ bazel build //tensorboard/pip_package
Target //tensorboard/pip_package:pip_package up-to-date:
bazel-bin/tensorboard/pip_package/pip_packages.tar.gz
INFO: Build completed successfully, 3 total actions
$ shasum -a 256 <bazel-bin/tensorboard/pip_package/pip_packages.tar.gz
6a37a171c7e274cd04fb7cb6772e5c93bde604669285b53c0c639127f7bf01f4  -
$ rm -f bazel-bin/tensorboard/pip_package/pip_packages.tar.gz
$ bazel build …
```
> pip_package: strip file timestamps from wheel

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/requirements.txt
- tensorboard/pip_package/requirements_dev.txt
- tensorboard/pip_package/setup.py
Summary:
This commit starts deduplicating our various representations of Python
dependencies. We extract `requirements.txt` for runtime dependencies and
`requirements_dev.txt` for tools, linters, and test-only deps. The CI
configuration will soon be changed to depend on these. (We don’t make
that change atomically because we need this intermediate state to safely
migrate some internal processes.) See #3038 for context.
Test Plan:
The output of `bazel build //tensorboard/pip_package` is bit-for-bit
identical before and after this change. In a new virtualenv (either
Python 2 or Python 3), one can successfully run all tests with the
declared dependencies:
```
pip install \
tensorflow \
-r tensorboard/pip_package/requirements.txt \
-r tensorboard/pip_package/requirements_dev.txt \
&& bazel …
```
> deps: factor out `requirements.txt` files

- tensorboard/defs/web.bzl
- tensorboard/defs/web_testing.bzl
Summary:
Fixes #2643. The proximate cause was that the `rules_closure` web server
tries 10 ports before giving up, so when more than 10 tests are run
concurrently some of them will fail. We fix this by binding to port 0
rather than scanning. With this fix, running all 18 of our web tests
concurrently incurred timeouts, even on a machine with 64 GB of RAM and
a 12-core Xeon W-2135 processor. Increasing the timeouts to moderate
mitigates that problem.
Test Plan:
Running all web tests concurrently now passes:
```
bazel test //tensorboard/... \
--test_tag_filters=webtest --cache_test_results=no
```
It takes 172 seconds on my machine, running with 12-fold parallelism.
wchargin-branch: web-test-flaky
> test: fix concurrent web test execution

- tensorboard/plugins/graph/tf_graph_common/node.ts
Fixes #2900
#2900
Several places in `tensorboard/plugins/graph/tf_graph_common/node.ts` use `getGradient()`, expecting it to return a string.  The function doesn't always return a string, which causes errors in the Graph dashboard.
This PR ensures that `getGradient()` always returns a string.
Retried the repro steps for #2900 and saw that it now works correctly (graph is not visually broken, console errors from before are gone).
I haven't written a test, but given the complexity of GraphV1 and contextual knowledge required, I'd like to know whether it makes sense to write one now, or just wait for GraphV2.
> graph: getGradient should always return a string

- tensorboard/compat/tensorflow_stub/dtypes.py
This makes explicit that as_numpy_dtype(0) returns a scalar value, not a dtype. (And accordingly, we use the dtype instead of the scalar.)
> as_numpy_dtype is a property, not a method

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/summary_v2.py
- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
The `hp.hparams` and `hp.hparams_pb` functions now accept Numpy data
types, like `np.float32` or `np.int32`, as hyperparameter values.
Previously, some such data types happened to work: `np.float64`, for
instance, is a subclass of `float`, and so was being implicitly
converted, but `np.float32` is not. Permitting all Numpy types is a nice
convenience that avoids confusion.
Fixes #3057.
Test Plan:
The newly added tests fail before this change and pass after it.
wchargin-branch: hparams-numpy
> hparams: accept Numpy scalars as hyperparameter values

- .travis.yml
* Unblock TensorBoard Travis CI from using the latest (floating) tf-nightly
* Update to .travis.yml to use Ubuntu 16.04 (xenial)
* Update to .travis.yml to float the tf-nightly version
> Upgrade Travis to Xenial and floating tf-nightly

- tensorboard/webapp/BUILD
mat_icon_module.ts is depending on the angular/material/icon but it does not have an entry for it in the BUILD file. Add the explicit dependency.
> [cleanup] add dependency on material icon

- .git-blame-ignore-revs
- DEVELOPMENT.md
Summary:
A new file lists hashes of commits that should be ignored by typical
invocations of `git blame`. To use this functionality, you must set the
`blame.ignoreRevsFile` Git config variable to point to this file. This
functionality requires Git 2.23 or newer.
Test Plan:
Before running `git config blame.ignoreRevsFile .git-blame-ignore-revs`,
asking for `git blame` on (say) `core_plugin.py` blamed all lines to a
single commit. After running that `git config` command, it blames most
lines to useful, older commits. (Some lines still blame to the reformat
commit, but they tend to be “uninteresting” blank lines or lines with
only punctuation.)
wchargin-branch: git-ignorerevsfile
> Add list of cleanup commits for `blame.ignoreRevsFile`

- tensorboard/webapp/settings/BUILD
Settings test depends on material button, checkbox, icon, and input but without depending explicitly on them. This change explicitly adds one.
> [ng] strict dep on settings test

- .travis.yml
Summary:
A new year, a new dawn. The <https://pythonclock.org/> has expired, and
TensorFlow has dropped Python 2 support:
<https://groups.google.com/a/tensorflow.org/d/msg/developers/ifEAGK3aPls/jlEuWYObBgAJ>
As noted in the above announcement, TensorFlow 2.1.0 will be released
with Python 2.7 support, but we’ve already released the corresponding
TensorBoard 2.1.0, so we no longer need to test with Python 2 at head.
Test Plan:
That CI passes quickly suffices.
wchargin-branch: travis-nopy2
> ci: remove Python 2.7 from `.travis.yml`

- tensorboard/tools/migration/src/helper.ts
- tensorboard/tools/migration/src/polymerelementify.ts
According to [polymer docs](https://github.com/Polymer/polymer-decorators#computedtargets-string), complex properties that require wildcards or special props like 'reflectToAttribute' cannot use the @computed decorator.
> [migration] computed decorator should not be used on complex properties

- ADDING_A_PLUGIN.md
A recent change I made added an image to the [docs](https://github.com/tensorflow/tensorboard/blob/master/ADDING_A_PLUGIN.md) has a broken relative link.
Fixes the relative path to be 'docs/...' instead of 'tensorboard/docs/...'
Checked using Github's edit/preview feature:
> [docs] fix link to image in plugin docs

- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
Summary:
Tests for `plugin_event_accumulator` heavily mock out the internals of
that class to swap in a custom event source, but this source does not
follow the expected contract: it sometimes yields `tf.Event` protos
rather than the expected protos from `tensorboard.compat.proto`. This is
sometimes harmless, but can cause tests to falsely fail if the system
under test references properties that exist on the TensorBoard compat
protos but not the TensorFlow protos.
Test Plan:
After adding a safety check to `plugin_event_accumulator`—
```diff
diff --git a/tensorboard/backend/event_processing/plugin_event_accumulator.py b/tensorboard/backend/event_processing/plugin_event_accumulator.py
index 8a976fd8..2918de27 100644
--- a/tensorboard/backend/event_processing/plugin_event_accumulator.py
+++ …
```
> Fix TensorFlow `Event` proto pollution in test

- tensorboard/tools/migration/src/helper.ts
- tensorboard/tools/migration/src/polymer-html.ts
- tensorboard/tools/migration/src/polymerelementify.ts
- tensorboard/tools/migration/src/script-extract.ts
- tensorboard/tools/migration/src/transfer-import.ts
Tested manually on the plugins/audio/tf_audio_dashboard.
jsToTs only renames the file, so it isn't affected.
> [migrate] preserve preamble in all transforms

- tensorboard/plugins/image/images_demo.py
`bazel run tensorboard/plugins/image:images_demo` failed in TF v2+
modifies calls locations where API changed between v1 + v2
```
bazel run tensorboard/plugins/image:images_demo
tensorboard --logdir /tmp/images_demo
```
May be nice to produce a new version without compat calls (that wouldn't work with tf v1)
> Updates images_demo for TF v2 compatiblity.

- .github/workflows/ci.yml
- .travis.yml
- package.json
Summary:
GitHub Actions is a new first-party CI service offered by GitHub. It
requires no extra permissions. Its concurrency limits are appealing,
at 20 workflows per repo (1 workflow ≈ 1 commit) and concurrent jobs
ranging from 20 (free tier) to 180 (enterprise tier), with the option to
run on your own servers if this isn’t enough.
This commit adds a workflow definition to replace only the lint phase of
our Travis workflow, to take advantage of the improved latency: order of
seconds from pushing a commit to seeing actionable failure messages.
A full workflow for building and running tests is also possible, but is
too slow for comfort because it runs entirely without cache, pending
some proposed improvements to the caching support for GitHub Actions.
Test Plan:
Note that this commit …
> ci: move linting to GitHub actions

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/io_wrapper.py
- tensorboard/backend/event_processing/io_wrapper_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
* Fix https://github.com/tensorflow/tensorboard/issues/2084
* The approach is suggested by @wchargin and @nfelt in https://github.com/tensorflow/tensorboard/issues/2084#issuecomment-570685175
* Split the logic of `IsTensorFlowEventsFile()` into two separate functions
1. An unchanged `IsTensorFlowEventsFile()` function, which only checks the existence of the 'tfevents' substring in the path string.
2. A new `IsSummaryEventsFile()` function, which returns `True` if and only if  `IsTensorFlowEventsFile()` returns `True` for the input path name *and* the path name does not end in the special suffix `.profile-empty`.
* This prevents the `EventAccumulator` implementation from picking up the empty …
> [backend] Split IsTensorFlowEventsFile into two separate functions

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
* Add `serve_execution_digests()` application route to DebuggerV2Plugin. It serves the HTTP requests to `/execution/digests`.
* The logic of this new method is implemented using the `read_blob_sequences()` and `read_blob()`  methods of the `LocalDebuggerV2DataProvider`. As designed, the tags carry semantics specific to this route, as will be the case for other routes.
* Note that there is some slight revision of the original design: we no longer surface the idea of "books" and "pages" in the DataProvider API. These are internal implementation details of data backend that should be hidden at this API level for simplicity.
* `DebuggerV2EventMultiplexer` now has a new method `ExecutionDigests` to fulfill the data requests.
Also in this PR:
* The `/runs` …
> [DebuggerV2] Implement the backend execution/digests route

- tensorboard/backend/event_processing/event_file_loader.py
The former is only available in Python3, in which getargspec was
deprecated. 
This allows to get rid of a deprecation warning when using Python3.
Uses a Python3 drop-in replacement, when available.
Both return a namedtuple with an equivalent "args" attribute, so the
functionality is unchanged.
N/A
Ran event_file_loader_test, in Python2 and Python3.
> When available, use inspect.getfullargspec instead of inspect.getargspec.

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/download_data.py
- tensorboard/plugins/hparams/download_data_test.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/tf_hparams_backend/tf-hparams-backend.html
- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.html
Fixes #2210.
As suggested in #2210, the tables computed in the HParams dashboard are very useful and are currently hard to extract, either by inspecting the DOM or calling the API. This provides a more clear UI to dump the tables and use directly in downstream tasks.
Added another endpoint to the HParams backend to support downloading the table with session groups in different format
Create mock HParams data by using the script at
> bazel run //tensorboard/plugins/hparams:hparams_minimal_demo
And then verifying the download links at 
> bazel run //tensorboard -- --logdir /tmp/hparams_minimal_demo
New tests are run with
> …
> Add download links to HParams plugin

- tensorboard/components/tf_globals/BUILD
- tensorboard/components/tf_globals/globals-polymer.ts
We need to be able to turn off the fake hashing in the storage module when using angular based TensorBoard.
> [ng] Expose tf_globals as Polymer component for interop

- tensorboard/backend/event_processing/data_provider.py
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/metadata.py
Summary:
In the context of the data provider interface, names of experiments,
runs, and tags are never null (`None`). But the ad hoc implementation of
the data provider interface for graph data did use `None` to denote
run-level graphs, and the graphs plugin correspondingly invoked it with
tag `None`. This commit changes both the provider and the plugin to use
a new hard-coded tag name internally (`__run_graph__`; arbitrary). There
are no frontend or HTTP API changes.
Test Plan:
Graphs still work both with and without `--generic_data true`. With
generic data enabled, only run-level graphs are shown in the dropdown
menu, as before.
wchargin-branch: graphs-run-graph-tag
> graphs: use non-null tag name for run graphs

- tensorboard/data/provider.py
Summary:
We don’t generally support Python 2 anymore, but this is required in the
short term for an internal fix. (This fixes an error “expected `None` or
collection of strings” when the list has a `unicode` value.)
wchargin-branch: rtf-six-strings
> data: use `six.string_types` for `RunTagFilter` type checking

- docs/migrate.ipynb
-Use colab's `%tensorflow_version` to skip the 60s install time (this is standard for tensorflow notebooks now).
-Use `tf.range` instead of `range` to prevent function retracing+warnings.
> Fix retracing warnings in the range loop.

- ADDING_A_PLUGIN.md
- README.md
Summary:
TensorBoard goes to great efforts to work fully functionally offline,
vendoring fonts, scripts, and assets. We’ve promised this publicly in
some venues (e.g., [twice][1] in [this talk][2]), but it has never been
explicitly stated in our core documentation. This commit documents our
offline-first principles in our README and plugin development guide.
[1]: https://youtu.be/XcHWLsVmHvk?t=54
[2]: https://youtu.be/XcHWLsVmHvk?t=294
wchargin-branch: offline-privacy-guarantees
> Document offline policy and privacy guarantees

- tensorboard/backend/event_processing/plugin_event_accumulator.py
Summary:
The `plugin_event_accumulator` tries to maintain fine-grained locks for
each plugin, but didn’t properly lock its table of locks, and didn’t
lock around accesses to the table of plugins. This commit replaces the
fine-grained locking with a simple coarse-grained lock.
Because all `dict`s involved are keyed only on Python strings, for which
`__hash__`, `__eq__`, and `__del__` are implemented in C, this should be
a no-op in CPython implementations. But correct concurrency is
[explicitly part of Google style][style], and without this patch some
subsequent changes would need to make this problem worse, so we might as
well just fix it Once and For All.
[style]: https://google.github.io/styleguide/pyguide.html#218-threading
Test Plan:
The primary safety concern due to this change is …
> backend: fix locking for `_plugin_to_tag_to_content`

- tensorboard/program.py
Summary:
The standard library’s `mimetypes.guess_type` can give incorrect results
on Windows, because arbitrary programs can influence its behavior by
writing to the registry. This can be worked around by reinstating the
correct MIME types with `mimetypes.add_type`, as in this patch. Fixes
#3120.
Test Plan:
To check that this patch works at all on Windows, edited the registry to
add a bad content type:
```
reg add HKCR\.js /v "Content Type" /d application/x-testing-123
```
…then verified that before this change, `mimetypes.guess_type("foo.js")`
gives the wrong value and TensorBoard does not render properly (strict
MIME type checking error in Chrome, as expected), whereas after this
change `mimetypes.guess_type("foo.js")` gives the correct value and
TensorBoard returns the correct content …
> windows: explicitly register correct MIME types

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Summary:
Prior to this change, any error thrown by a plugin’s `is_active`
implementation would cause the entire response to 500, which renders
TensorBoard completely inoperable. Now, such failures mark the offending
plugin as inactive and continue with the rest of the response.
Test Plan:
Unit tests added. With this patch installed onto a Windows machine,
TensorBoard now works instead of crashing trying to load the debugger
plugin.
wchargin-branch: robust-is-active
> plugins_listing: handle failures in plugin `is_active`

- tensorboard/plugins/debugger_v2/BUILD
- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Route source_files/list lists all files
* Route source_files/source_file provides access to the content
of a given source file.
* In `debug_data_multiplexer`, now call `self._reader.update()` on a separate thread instead of on the main thread. This prevents blocking the TensorBoad backend for a long time when the size of the debugger data is large. This asynchronous reading behavior is overridden by a mock to a synchronous behavior during unit tests.
* Unit tests added
> [DebuggerV2] Implement backend routes: source_files

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
TB 2.1.0 works great with TF 2.1.0.  However, tip-of-tree TB doesn't work with TF 2.1.0, since ToT TB depends on TF's DebugDataReader, which was introduced after TF 2.1.0.  Running this combination produces:
```
AttributeError: module 'tensorflow.python.debug.lib.debug_events_reader' has no attribute 'DebugDataReader'
```
@caisq, do we plan to support, say, TB 2.2 or ToT TB working with TF 2.1?
If not, we can close this.
> TB versions after 2.1 should work with TF 2.1

- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
Now that the TensorBoard backend core marks plugins as enabled if the
data provider has corresponding data (#3124), plugins can mark
themselves inactive when they don’t have data, rather than being enabled
unconditionally in generic data mode.
Test Plan:
Run TensorBoard against the scalars, images, and histograms demos
(individually), and note that it behaves the same way with generic data
mode enabled or disabled. (Note that the histogram demo has no graphs.)
wchargin-branch: data-isactive-false-by-default
> data: fix `is_active`s in generic data mode

- tensorboard/pip_package/requirements_dev.txt
Systems with older Python versions, say 3.5, will fail to install dev dependencies.  
Require Python 3.6 or higher for Black, in the requirements_dev.txt.
> infra: require Python3.6 to install Black

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Continue developing the backend of the DebuggerV2 plugin
* The route /execution/data is similar to the existing /execution/digests in that
it concerns the top-level execution events. However, it serves the detailed, larger-size
data objects, which additionally includes fields such as input/output tensor IDs, host name
stack frame IDs, tensor debug mode and  debug tensor value (if any).
* Note that the implementation differs from the original design in the TDD in that the impl
permits multiple execution data objects to be served in a batch, using the begin and end
params, in a way similar to the /execution/digests path. This is based on the consideration
that in some cases, multiple detailed data objects are desired …
> [DebuggerV2] Implement routes /execution/data and /stack_frames/stack_frames

- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin_test.py
This removes the `tf.contrib.summary.create_db_writer()` dependency from core_plugin_test.py, which partially addresses #1718 and #1705, and reverts the applicable part of #3143 (a temporary fix).
I've preserved most of the test coverage of the underlying DB-reading code by changing the test data population strategy to instead just use the DbImportMultiplexer logic that already exists within TensorBoard.  That logic doesn't set `started_time` so we lose some coverage in that the test that specifically tests that behavior is now logdir-only, because it didn't seem worth the trouble to get it to keep working.
I also refactored the rest of the tests a little bit to remove cruft and reorganize the test cases a little more logically.  Ultimately a lot of this should be cleaned up further as …
> Rewrite core_plugin_test.py to use DB import mode instead of tf.contrib DB writer

- tensorboard/components/experimental/plugin_lib/message.ts
- tensorboard/components/experimental/plugin_util/message.ts
- tsconfig.json
Stricter TS options allow TensorBoard to capture more errors.
Enables TS's 'strict' compiler option.
Ran Bazel build on tensorboard with+without the `-c dbg` option and observed no errors after fixing plugin_lib.
> Enable strict Typescript option

- .travis.yml
Summary:
The Pip HTTP cache stores all downloaded wheels and is never evicted.
With new `tf-nightly` wheels every day, this adds up quickly. We last
cleared our Travis caches about a month ago, and they’re up to 14.3 GB.
Investigation shows that the Pip HTTP cache accounts for the majority of
the cache (about 70% after about a month of cache accrual), and also
that jobs with larger caches have significantly longer startup times,
with delta on the order of 8 minutes (again, after about a month). Also,
uploading large caches at the end of a job can take minutes, and Travis
doesn’t report success until this finishes. Fetching `tf-nightly` should
be comparatively cheap.
This reverts part of #2278.
Test Plan:
This PR reduces the “before install” time (i.e., time spent by Travis
internals …
> ci: don’t store Pip HTTP cache

- tensorboard/backend/event_processing/data_provider.py
- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
Summary:
The metadata for a blob sequence has historically included the number of
blob values in the most recent blob sequence datum (`latest_max_index`).
The intent of this field was to enable the audio and image dashboards to
determine the total number of “samples” per summary. But the value that
is actually needed here is the _maximum_ length of any datum, not the
length of just the latest datum.
This commit renames `latest_max_index` to `max_length`, keeping aliases
for both the initializer and the accessor property while we migrate
clients. All clients in this repository are migrated in this commit, but
some Google-internal clients need to be handled separately.
Test Plan:
Unit tests show that both the old and new invocations still work. A test
sync shows that relevant …
> data: rename `latest_max_index` to `max_length`

- ADDING_A_PLUGIN.md
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
A proposed change to the URL scheme for plugins would involve describing a plugin-specific URL value like so:
`https://<tensorboard>/#my_plugin&p.my_plugin.key=value`
In this scheme, the prefix `p.` is special, and a period is used to separate a plugin name from a key name.  For the scheme to work, periods need to be disallowed from plugin names to prevent ambiguity.  E.g. is `&p.my_plugin.foo.key` referring to a plugin `my_plugin` with a key `foo.key`, OR a plugin `my_plugin.foo` with a key `key`?
Plugin names are already restricted, so alternatively, we could use some other character like `~` or `*` to distinguish a plugin name from key name in the URL.  e.g. …
> Disallow period from plugin names

- tensorboard/components/experimental/plugin_lib/BUILD
- tensorboard/components/experimental/plugin_lib/core.ts
- tensorboard/components/experimental/plugin_lib/test/test.ts
- tensorboard/components/experimental/plugin_util/BUILD
- tensorboard/components/experimental/plugin_util/core-host-impl.ts
- tensorboard/components/experimental/plugin_util/plugin-host-ipc.ts
- tensorboard/components/experimental/plugin_util/plugin-host.html
- tensorboard/components/experimental/plugin_util/test/plugin-test.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Clients may wish to construct a link to TensorBoard that automatically opens a specific dashboard with a specific view.  This could be achieved with `window.parent.location`, but is discouraged since it is fragile (assumes 1 layer of nested iframe and modifying the URL has wide consequences).
This provides iframed plugins a safer approach to reading the URL through the plugin library.
Adds `getURLPluginData()` to the plugin library.
> plugins: add experimental URL reading API for iframed plugins

- tensorboard/webapp/BUILD
- tensorboard/webapp/app_container.ng.html
- tensorboard/webapp/app_module.ts
- tensorboard/webapp/core/actions/core_actions.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_reducers_test.ts
- tensorboard/webapp/core/views/BUILD
- tensorboard/webapp/core/views/hash_storage_component.ts
- tensorboard/webapp/core/views/hash_storage_container.ts
- tensorboard/webapp/core/views/hash_storage_module.ts
- tensorboard/webapp/core/views/hash_storage_test.ts
- tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
This change emulates the behavior of tf_tensorboard where changing the plugin changes the hash in the URL. 
Ideally, tf_storage should break down into two pieces: utility for formatting data structure as string and one that actually writes data to a medium. In such world, the former can be used by hash_storage_component without depending on tf_storage.
> [ng] Hash storage component to make changes to the hash

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/BUILD
- tensorboard/webapp/angular/BUILD
- tensorboard/webapp/core/effects/BUILD
- tensorboard/webapp/core/views/BUILD
- tensorboard/webapp/header/BUILD
- tensorboard/webapp/plugins/BUILD
- tensorboard/webapp/reloader/BUILD
- tensorboard/webapp/settings/BUILD
Internal build requires explicit dependency on @ngrx/store/testing
instead of just "@ngrx/store". This change adds the dummy rule for
correct conversion.
Reviewer: sorry for extraneous change. My IDE is a bit too rigorous in fixing :(
It is hard to selectively turn it off.
> [sync] add dummy ngrx/store/testing dep

- tensorboard/backend/event_processing/data_provider.py
- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
Summary:
This was replaced with `max_length`, which has the semantics that we
actually want.
Test Plan:
Running `git grep latest_max_index` gives no results.
wchargin-branch: data-remove-latest-max-index
> data: remove `latest_max_index`

- tensorboard/uploader/util_test.py
Summary:
Follow-up to #2978, which added explicit configuration of `TZ=UTC`. In
cPython 3, the time zone used by `datetime.datetime.fromtimestamp` is
[cached when `time` is imported][1] unless explicitly reset, so mocking
the environment variable is no longer sufficient. We now call `tzset`
ourselves; we could also just set `TZ=UTC` before importing `datetime`,
but this seems cleaner.
[1]: https://github.com/python/cpython/blob/2528a6c3d0660c03ae43d796628462ccf8e58190/Modules/timemodule.c#L1752-L1763
Test Plan:
A test sync shows that this test passes in both Python 2 and Python 3,
whereas it previously only passed in Python 2.
wchargin-branch: util-test-tzset
> uploader: make `util_test` py3-compatible internally

- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Summary:
This gets rid of the “Please prefer TensorBoard copy of the proto”
message in the test logs.
Test Plan:
After changing the warnings in `test_util.py` to `AssertionError`s, this
test passes where it used to fail.
wchargin-branch: custom-scalars-tb-proto
> custom_scalars: use `tensorboard.compat` protos in test

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/backend/event_processing/event_file_loader_test.py
This change addresses the most critical part of https://github.com/tensorflow/tensorboard/issues/1711 by relaxing our dependency on PyRecordReader, which was never part of the public TF API and is slated to be removed imminently (cc @av8ramit).  Now when it's missing, we instead use `tf.compat.v1.io.tf_record_iterator` which was recently updated in https://github.com/tensorflow/tensorflow/commit/54f1de4fcf81ed7e25247d84f9dadc761b5a1bb7 to no longer abandon the read offset after reaching EOF (which resolves the issue described in #1711 that prevented us from using it, since we couldn't use it to poll the end of a file for newly appended data).
The implementation here adopts the iterator style throughout, and wraps our legacy PyRecordReader usage inside an iterator API so it can be …
> Change EventFileLoader to use tf_record_iterator when possible

- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/util/test_util.py
Summary:
Some arguments may be passed as TensorFlow protos, TensorBoard protos,
or raw byte strings. We want to warn against the TensorFlow protos, but
were also warning against the raw byte strings. This change fixes all
existing warnings, so we bump the log level to `error` to discourage
regressions.
Test Plan:
After changing the warnings in `test_util.py` to `AssertionError`s, all
tests still pass where 18 of them used to fail.
wchargin-branch: testutil-permit-bytes-protos
> test_util: don’t warn when raw byte strings passed

- tensorboard/BUILD
- tensorboard/dataclass_compat.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/image/images_plugin_test.py
Summary:
This patch teaches the images plugin about the generic data APIs and
newfound blob sequence support, guarded behind the `--generic_data=true`
feature flag.
Test Plan:
Setting `--generic_data` to either `false` or `true` has no observable
effect, even if TensorBoard is patched to never pass a multiplexer to
plugins’ `TBContext` (to prevent accidentally reads along the old path).
Unit tests expanded to cover both the old and new paths.
wchargin-branch: generic-images
> images: add data provider support

- tensorboard/components/tensorboard.html
Summary:
For accessibility; this can control screenreader language choice.
Fixes #3189.
Tested:
The generated HTML now contains `<html lang="en">` as the first tag
(other than doctype and comments).
wchargin-branch: html-lang-en
> main: add `<html lang="en">` tag

- tensorboard/plugins/base_plugin.py
Summary:
It’s customary\* to use `None` as the default value for an argument,
because otherwise clients cannot specify to “use the default value”.
This patch makes `is_ng_component` consistent with all sibling kwargs.
\* In some dialects of Python, including TensorFlow and TensorBoard.
See, e.g.:
<https://unhashable.com/always-use-none-for-default-args-in-python/>
Test Plan:
Unit tests suffice.
wchargin-branch: idiomatic-ng-default
> base_plugin: make `is_ng_component` default idiomatic

- tensorboard/main.py
This updates the comment wording to clarify that setting this env var is no longer needed for recent versions of TF (where it has no effect), but we preserve it to avoid regressions for old versions that are still affected.
> Update main.py comment on setting GCS_READ_CACHE_DISABLED

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/compat/__init__.py
- tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
- tensorboard/plugins/projector/projector_plugin.py
This addresses concern 2 from https://github.com/tensorflow/tensorboard/issues/1711#issuecomment-579512944, namely that the changes in #3185 were sufficient to fall back correctly if `pywrap_tensorflow` no longer contained a `PyRecordReader_New` symbol, but not actually sufficient in the eventual case that `pywrap_tensorflow` disappears entirely and can no longer be imported.  The previous code was using the `tensorboard.compat._pywrap_tensorflow` lazy-loader which would in that case have automatically started using the no-TF stub implementation of pywrap_tensorflow instead, which is undesirable relative to using `tf_record_iterator`.
We fix that by getting rid of `tensorboard.compat._pywrap_tensorflow` entirely, since it was unused elsewhere (the projector plugin imported it but did not …
> Ensure EventFileLoader only uses no-TF stub when required

- tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
Summary:
TFRecords are [always written as little-endian fixed-size fields][1], so
the notf reading code should read them likewise regardless of system
endianness and word size.
[1]: https://github.com/tensorflow/tensorflow/blob/469200828c408f861fd4fb35301133ecb446b034/tensorflow/core/lib/io/record_writer.h#L121
Test Plan:
Sanity-checked that no-TF reading still works on my little-endian
machine, but we don’t have any automated regression tests for this.
wchargin-branch: notf-unpack-endianness
> notf: make `struct.unpack`s portable

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- The /alerts route is based on the recently-added InfNanMonitor
in tfdbg2's tensorflow part.
- The route serves information about:
- How many inf/nan events (InfNanAlert) exist
- Number limit for each type of alerts (currently there is only
one type: InfNanAlert)
- The details of each alert, in the specified begin/end range.
- Modify the dummy TF2 program (`_generate_tfdbg_v2_data()`) in
debugger_v2_plugin_test.py to intentionally generate `inf`s and `nan`s.
- Python unit tests added.
> [DebuggerV2] Backend: Implement basic features of /alerts route

- .travis.yml
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/test_pip_package.sh
Summary:
We no longer support Python 2, and so should not build packages for it,
because they’re not guaranteed to work at all. We likewise should run
the smoke test in Python 3 by default.
Test Plan:
Running `bazel run //tensorboard/pip_package:extract_pip_package` still
succeeds, now extracting only `tensorboard-2.2.0a0-py3-none-any.whl`.
wchargin-branch: pip-py3-only
> pip_package: only build Python 3 wheel

- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_test.py
- tensorboard/plugins/debugger/events_writer_manager_test.py
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/mesh/mesh_plugin_test.py
- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/plugins/text/text_plugin_test.py
- tensorboard/summary/summary_test.py
Summary:
In Python 3.9, `collections.Callable` is slated to be removed in favor
of `collections.abc.Callable` (and likewise with the other ABCs, but
this is the only one that we use).
Fixes #3202.
Test Plan:
Running `git grep -P 'collections\.(?!OrderedDict|Counter)[A-Z]'` no
longer finds any matches.
wchargin-branch: collections-abc-callable
> Import `Callable` from `collections.abc`

- tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
Bug: the view did not paginated when user modifies the input on the
tf_category_paginated_view manually.
As wchargin@ pointed out, the number `<input>` did not have a value for
`valueAsNumber` when modified the input field. We now use the
`input.value` to get its stringified value.
Tested by manually interacting with the UI element.
Fixes #3067.
> pagination: fix pagination input interaction

- tensorboard/components/tf_storage/storage.ts
Clients that link to the What if Tool in TensorBoard may still be using a legacy URL scheme.  This scheme is deprecated, and can be removed once WIT uses the new URL reading API `getURLPluginData()`.  Currently, TensorBoard auto-upgrades WIT params to the new scheme, breaking the WIT's auto-loading of config data.
Until then, we actually need to preserve both the old AND the new scheme to ensure nothing breaks during migration.
e.g.
`https://<tensorboard-url>/#whatif&examplesPath=...&p.whatif.examplesPath=...`
> Keep legacy scheme URL params for WIT

- .travis.yml
Summary:
@davidsoergel made this sensible change in the 2.1 branch; we backport
it to master so that the branches run on consistent versions.
Test Plan:
CI suffices.
wchargin-branch: ci-tf1x-norc
> ci: run TF 1.x builds against 1.15.0, not its RC

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
These constants are declared outside a scope, so attempting to define
them in any other file gives a compile-time error. They’re never used,
so we can just delete them.
Test Plan:
The scalars dashboard still seems to render fine.
wchargin-branch: scalars-no-consts
> scalars: remove unused global constants

- tensorboard/BUILD
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/default.py
- tensorboard/plugins/profile_redirect/BUILD
- tensorboard/plugins/profile_redirect/__init__.py
- tensorboard/plugins/profile_redirect/profile_redirect_plugin.py
- tensorboard/plugins/profile_redirect/profile_redirect_plugin_test.py
- tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/BUILD
- tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Summary:
We add a new `profile_redirect` plugin, called “Profile (moved)” in the
UI, which teaches users how to install the dynamic plugin:
The instructions currently pull in Test PyPI sources; we’ll swap these
out for real PyPI once the package is published.
[ss]: https://user-images.githubusercontent.com/4317806/73811360-229f1300-478e-11ea-9341-f38d59170e3b.png
Test Plan:
Create a new virtualenv, install `tf-nightly`, uninstall `tb-nightly`,
and run `//tensorboard/pip_package:extract_pip_package` and install the
resulting wheel. Launch TensorBoard and note that the “Profile (moved)”
plugin appears in the inactive plugins list. Click the “Copy to
clipboard” button and execute the copied `pip install` command from the
test virtualenv. Relaunch TensorBoard, and note that the dynamic …
> Add plugin to redirect users to new profile plugin

- docs/design/generic_data_apis.md
Summary:
This design doc was written while developing the infrastructure for
TensorBoard.dev. It describes how the TensorBoard frontend, backend, and
plugins can be factored apart from the backing storage layer, so that
new hosted solutions can work with new plugins without many-to-many
coordination.
wchargin-branch: docs-design-generic-data-apis
> docs: publish “Generic data APIs and implementations” design doc

- .github/workflows/ci.yml
- tensorboard/uploader/BUILD
Adds a link check to avoid creating `python_version = "PY2"` BUILD targets (e.g. py_binary or py_test), since we should be running all our python binaries using python3 at this point, so that we can start introducing py3-only code.
This also removes the one violation of this check, which was `//tensorboard/uploader:uploader`.
Tested by ensuring link check failed prior to removing the violation, then passes afterwards.
> add lint check against PY2 BUILD targets

- docs/design/generic_data_ingestion.md
Summary:
This design doc was written while generalizing the support for data
providers beyond just scalar data. It describes an approach for reading
tensor and blob sequence data from disk that is extensible along the
plugin axis (any plugin can write compatible data) and the storage layer
axis (any backend can ingest this data with the same logic).
wchargin-branch: docs-design-generic-data-ingestion
> docs: publish “Generic data ingestion” design doc

- tensorboard/components/experimental/plugin_lib/BUILD
- tensorboard/components/experimental/plugin_lib/polymer-interop.html
- tensorboard/components/experimental/plugin_lib/polymer-interop.ts
- tensorboard/components/experimental/plugin_lib/test/BUILD
- tensorboard/components/experimental/plugin_lib/test/test.ts
- tensorboard/components/experimental/plugin_lib/test/testable-iframe.html
- tensorboard/components/experimental/plugin_lib/test/testable-plugin-lib.ts
- tensorboard/components/experimental/plugin_util/test/BUILD
- tensorboard/components/experimental/plugin_util/test/testable-iframe.html
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
plugin_lib was initially designed to be used with npm package and a
bundler. However, because we have a need to use it under traditional
Polymer code that uses HTML import, we need to devise a way for the
lib to work with tf_web_library.
Changed our test to use the new interop layer.
Also tested whether WIT builds with the library (https://github.com/stephanwlee/what-if-tool/commit/5bc972f544b0e23d1ac488b1c43a2c7c668eba7e). I was not able to check for correctness as wit does not build correct pip package.
> Surface HTML import interop for plugin_lib

- DEVELOPMENT.md
With Chrome 80+ rolling out, debugging UI tests got trickier. There is a
way to work around the issue and this change documents the trick.
> doc: a tip about debugging UI tests

- tensorboard/webapp/webapp_data_source/BUILD
- tensorboard/webapp/webapp_data_source/tb_server_data_source_module.ts
This unblocks the sync which failed because of the strict_deps violation.
- tensorboard/webapp/webapp_data_source/tb_server_data_source_module.ts had extraneous import statement.
- tb_http_client_testing.ts had missing import on BUILD.
> cleanup: fix import statement

- tensorboard/backend/empty_path_redirect_test.py
- tensorboard/backend/experiment_id_test.py
- tensorboard/backend/path_prefix_test.py
Although the werkzeug changelog did not say so, it seem to have removed
certain symbols from `werkzeug`. We now use
`werkzeug.wrappers.BaseResponse` instead.
Context:
https://werkzeug.palletsprojects.com/en/master/changes/#version-1-0-0
Fixes #3229.
> Convert BaseResponse to wrappers.BaseResponse

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_module.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container.ts
* Continue developing DebuggerV2 plugin
* In the Python backend code, add alerts_breakdown, which is a breakdown of all alerts by their types.
* Add an effect in debugger_effects.ts: On non-empty debugger runs, fetch number of alerts and their breakdown
* Add display logic to AlertsComponent to visualize the alerts. 
* Follow-up PRs will add actions and effects for when the alert categories are clicked.
* When alerts are present:
* 
* When there are no alerts:
* 
* Manual testing on a tfdbg2 dataset with nan and inf
> [DebuggerV2] Start fleshing out alerts component

- tensorboard/plugins/core/core_plugin.py
We've gotten feedback that 1 hour is too short for the default (b/145081930 internally), since for various reasons people might write to an event file only every several hours, and currently there is no indication (unless turning on verbose logs) for why the new data is not loading.
Of course, there's no guarantee that 24 hours will always be enough either, but that seems like a better balance for now until we have a more robust approach, some of which are described in the original PR: https://github.com/tensorflow/tensorboard/pull/1867
> Update --reload_multifile_inactive_secs default to 24 hours

- tensorboard/components/tf_trace_viewer/tf-trace-viewer.html
Warn users of tf-nightly who use the trace viewer in the existing Profiler plugin that it is broken.
Within the Trace viewer iframe, detect whether WebComponentsV0 are available.  Show the warning if it is not.
Tested on both Chrome M80 and M79, checked that the warning only shows in the newer version.  Note that, when origin trial is available, the warning should not appear.
> Show warning if trace viewer is used with WebComponents v0

- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
* Lay foundation for displaying experiment metadata (incl. timestamp for creation, name and description) in tensorboard.dev
* Add method `experiment_metadata()` to `DataProvider` base class, with a default return value of `None`.
* Add data class for experiment metadata: `ExperimentMetadata`.
> Add experient_metadata to DataProvider

- tensorboard/uploader/proto/write_service.proto
Whenever we provide a `step`, we should also provide a `wall_time` (as seen in scalar.proto and tensor.proto).  This was inadvertently omitted here before.  Note it's safe to change the proto field IDs because this message is not actually used yet.
> Add wall_time field to GetOrCreateBlobSequenceRequest

- tensorboard/components/tf_backend/environmentStore.ts
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
* To support experiment metadata (e.g., name, description, time created) in tensorboard.dev, we need to make such metadata servable from the backend. 
* This PR implements part of this data pathway in CorePlugin. `CorePlugin._serve_environment()` now calls `DataProvider.experiment_metadata()` and populates its response with data fields in the object when they are present.
* The TypeScript code in `environmentStore.ts` is revised accordingly.
* Unit tests added in core_plugin_test.py
> [CorePlugin] Add experiment metadata to /data/environment route response

- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/proto/BUILD
- tensorboard/uploader/proto/experiment.proto
- tensorboard/uploader/proto/export_service.proto
- tensorboard/uploader/proto/write_service.proto
- tensorboard/uploader/uploader_main.py
This resolves a TODO to refactor the `Experiment` and `ExperimentMask` messages from `export_service.proto` into a standalone `experiment.proto` so they can be more properly shared across RPC service interfaces.
I also updated the comments on fields of the proto to indicate which fields are output-only and cannot be updated directly by RPC clients.  (To see the diff, look at only the second commit; I split the file copy out into the first commit since git's move detection can't handle this.)
Will be synchronized with internal changes; see cl/294800076.
> Extract Experiment/ExperimentMask messages into experiment.proto

- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
Summary:
At this point, the generic data APIs are a fully featured replacement
for the multiplexer APIs, including `is_active` support. We now enable
them by default. They can still be disabled with `--generic_data false`.
Test Plan:
Patch the `MultiplexerDataProvider` to return hard-coded descriptions so
that the generic and non-generic flows are distinguishable, then note
that `tensorboard` uses the generic data APIs with `--generic_data`
either set to `true` or unspecified, and not when set to `false`.
wchargin-branch: data-stabilize-scalars
> scalars: promote generic data to stable

- tensorboard/backend/event_processing/io_wrapper_test.py
According to https://github.com/tensorflow/tensorboard/issues/3260, `testListRecursivelyViaGlobbingForPathWithGlobCharacters` is failing due to a breaking change in tf-nightly's `tf.io.gfile.glob()` implementation.  While that is being resolved, this disables the test to avoid interference with normal TB development.
Renames the test to `skipTestListRecursivelyViaGlobbingForPathWithGlobCharacters`
Ran bazel test on the io_wrapper_target and saw that it passes when it failed before.
> Disable io_wrapper glob test

- tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Summary:
The dynamic profile plugin is now available on stable PyPI:
<https://pypi.org/project/tensorboard-plugin-profile/2.2.0a1/>
Styling updated because the number of lines of text changed.
Test Plan:
The instructions still work in a new virtualenv, pulling in `2.2.0a1`.
wchargin-branch: profile-stable-pypi
> profile: remove Test PyPI index specification

- tensorboard/backend/application.py
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/text/text_plugin.py
Summary:
We add a `sampling_hints` attribute to the `TBContext` magic container,
which is populated with the parsed form of the `--samples_per_plugin`
flag. Existing plugins’ generic data modes are updated to read from this
map instead of using hard-coded thresholds.
Test Plan:
This change is not actually observable as is, because the multiplexer
data provider ignores its downsampling argument. But after patching in a
change to make the data provider respect the downsampling argument, this
change has the effect that increasing the `--samples_per_plugin` over
the default (e.g., `images=20`) now properly increases the number of
samples shown in generic data mode, whereas previously it had no effect.
wchargin-branch: data-downsampling-flag
> data: expose downsampling preferences to plugins

- tensorboard/components/tf_backend/environmentStore.ts
* Support experiment metadata (name, description, creation time) display in tensorboard.dev
* This is a follow-up to https://github.com/tensorflow/tensorboard/pull/3254
* Add three getter methods to environmentStore.
* Manual verify by running a frontend that talks to it (not included in this PR)
> Add experiment name, description and time getters to environmentStore

- tensorboard/BUILD
Summary:
This enables Bazel targets to depend on `tensorboard.notebook` without
pulling in all of the summary writing infrastructure, by explicitly
depending on both `:lib_init_only` and `:notebook`. This results in a
very thin dependency graph: try
```
bazel query 'deps(//tensorboard:lib_init_only + //tensorboard:notebook)'
```
to see.
Test Plan:
A binary that depends on `:lib_init_only` and `:notebook` can import
`tensorboard` and run `tensorboard.notebook.list()`, while trying to
evaluate `tensorboard.summary.scalar` raises an `ImportError`. Googlers,
see <http://cl/296370945>.
wchargin-branch: lib-init-only
> build: add an `__init__`-only `tensorboard` library

- .travis.yml
Summary:
This was previously needed to run `yarn lint`, but we run that on GitHub
Actions now (in parallel with Travis!), so it’s entirely superfluous and
takes about a minute to run.
Test Plan:
Ensure that Travis is still happy.
wchargin-branch: ci-travis-no-yarn
> ci: skip `yarn install` on Travis

- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/list_metric_evals.py
- tensorboard/plugins/hparams/list_metric_evals_test.py
Hparams and Custom Scalars use the Scalars plugin's implementation to
generate data on the frontend.  When --generic_data was enabled by
default, the DataProvider started validating experiment IDs, so
callers of scalars_impl who passed experiment `None` would break.
This fixes https://github.com/tensorflow/tensorboard/issues/3279
by making Hparams, Custom Scalars pass the correct experiment ID.
> Always pass experiment IDs to scalars_impl

- tensorboard/BUILD
Summary:
This target is primarily intended to be used by our Pip package; clients
should not depend on this hourglass dependency.
Test Plan:
All Google-internal dependents have been migrated; a test sync passes.
wchargin-branch: build-lib-internal
> build: clamp down `//tensorboard:lib` visibility

- ADDING_A_PLUGIN.md
- README.md
Summary:
The profile plugin is no longer bundled with TensorBoard, so everything
built in to TensorBoard should now be fully functional while offline.
wchargin-branch: docs-fully-offline
> docs: drop profile plugin offline policy exemption

- tensorboard/data/BUILD
- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
Summary:
This enables us to more easily add and change fields on these objects
without worrying about positional parameters. (Such changes are still
breaking, but these APIs have no stability guarantee.)
Test Plan:
All open-source consumers are already compliant except for tests, which
are updated in this commit. Google-internal clients have already been
updated; a test sync shows that all tests pass.
wchargin-branch: time-series-kwargs
> data: require kwargs for time series initializers

- tensorboard/components/tf_paginated_view/tf-paginated-view-store.html
- tensorboard/webapp/BUILD
- tensorboard/webapp/app_container.ng.html
- tensorboard/webapp/app_module.ts
- tensorboard/webapp/core/actions/core_actions.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_selectors.ts
- tensorboard/webapp/core/store/core_types.ts
- tensorboard/webapp/core/testing/index.ts
- tensorboard/webapp/reducer_config.ts
- tensorboard/webapp/settings/BUILD
- tensorboard/webapp/settings/dialog_component.ts
- tensorboard/webapp/settings/dialog_component_test.ts
- tensorboard/webapp/settings/polymer_interop_container.ts
- tensorboard/webapp/settings/polymer_interop_test.ts
- tensorboard/webapp/settings/settings_module.ts
This implements the pagination setting for Polymer based TensorBoard.
When changing the pagination setting, you can now change how many pages
of categories will be rendered on the Polymer side. Do note that
Angular based components will simply use selector to read the state from
the store instead.
TODO after the PR:
- stylize the settings dialog.
> ng: make Polymer pagination configurable from Ng

- tensorboard/data/provider.py
Summary:
Slight docs omission pointed out by @caisq in #3284.
wchargin-branch: data-timeseries-super-docs
> data: document that `TensorTimeSeries` extends `_TimeSeries`

- tensorboard/components/BUILD
Context:
- JSCompiler adds overhead to our builds.
- ng_tensorboard makes another Vulcanization bundle than regular
TensorBoard.
- in CI, we build both Vulcanized bundles because we do `bazel build
tensorboard/...`.
This change turns off Vulcanization for currently develop only
ng_tensorboard. This change does not impact our Pip package but only CI
and local development.
> Turn off JSCompiler for ng_tensorboard

- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_main.py
- tensorboard/uploader/uploader_test.py
Adds the ability to list, upload, and modify experiments with names & descriptions.
Adds user intent & checking for 
```
bazel run //tensorboard -- dev list
```
```
Total: 17 experiment(s)
https://tensorboard.dev/experiment/F0EqjQjYTOCk4AdY5oskbQ/
Name        this is demoable now.
Description a *description* 💁👌🎍😍
Created     2020-02-21 12:06:42 (23 minutes ago)
Updated     2020-02-21 12:30:07 (6 seconds ago)
Scalars     18807
Runs        21
Tags        7
https://tensorboard.dev/experiment/xDROKjLAS0eKh9Lfpdwamg
Name        [No Name]
Description [No Description]
...
```
bazel run //tensorboard -- dev upload --logdir …
> Support experiment name and description in uploader

- tensorboard/plugins/projector/vz_projector/test/BUILD
- tensorboard/plugins/projector/vz_projector/test/tests.html
Cause: it did not import the library under test. As a result, it was
using symbols that were not defined.
> Fix vz_projector tests

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Forms a basis for the already open https://github.com/tensorflow/tensorboard/pull/3269
* Allow the DebuggerV2 frontend to query alerts that belong to a specific alert type.
* Modify the multiplexer, data provider and serving method to support the "alert_type" parameter in requests.
* Not that there is a slight change to requests to the same route without filters: previously there "alert_type" field was not populated; now it's populated with a `None` (`null`) value.
> [DebuggerV2] Add support for alert-type filtering to /alerts route

- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
This change fixes the regression that erroneously showed graph canvas
when no data was fetched.
Two issues:
- wrong property binding
- inverted conditional (we only want to show tf-dashboard-layout when dataset is `PRESENT`)
Fixes #3004.
> graph: fix no data UI

- tensorboard/backend/experiment_id.py
- tensorboard/backend/experiment_id_test.py
ExperimentIdMiddleware was not able to compose with itself because it
was always setting the WSGI environment variable with a value it
extracted from current path.
I want to be able to do one of two things:
1. Remove experiment_id_middleware in OSS and introduce in application that actually makes use of it. If we were to remove it from application.py, it would break the sync so we have to make a concerted change. We cannot add the experiment_id_middleware in aforementioned app since there cannot be two instances of experiment_id_middleware wrapping one another.
2. (much less important) This change allows there to be alternative implementation of experiment_id_middleware as long as it populates the same WSGI environment key. It is less ideal but also allows us to hack around :\
> Let ExperimentIdMiddleware to be nested

- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/projector/__init__.py
- tensorboard/plugins/projector/metadata.py
- tensorboard/plugins/projector/projector_plugin.py
Summary:
This refactoring enables the public API `:projector` to not depend on
the frontend code. While factoring out these constant, we rename a
couple of them to match conventions in TensorBoard: e.g., `PLUGIN_NAME`
is typically used to represent the plugin name.
This is a helpful step in migrating `base_plugin.py` to use PY3-only
syntax (namely, hard-requiring kwargs to `TBContext`’s initializer).
Test Plan:
After syncing into Google, there are no longer any valid PY2 binaries
that transitively depend on `//tensorboard/plugins:base_plugin`.
wchargin-branch: projector-metadata
> projector: factor metadata out from frontend plugin

- tensorboard/uploader/proto/server_info.proto
Summary:
This enables us to flag features on the server side, so that we can
stage releases, and so that we can roll back in a pinch without
requiring an expedited PyPI push and end user version upgrade.
Test Plan:
No new behavior in this change. The protos still build.
wchargin-branch: uploader-plugincontrol-protos
> uploader: add `PluginControl` handshake protos

- tensorboard/uploader/uploader_test.py
Summary:
Tests create uploaders and request senders with dependency-injected
stubs. As we add more such stubs, the test code bloats and requires
broad changes. By centralizing helpers, we can inject defaults that are
selectively overridden.
Test Plan:
Existing tests suffice.
wchargin-branch: uploader-test-di-helpers
> uploader: factor test defaults into helpers

- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
Summary:
We now emit an experiment’s scalar data to `experiment_123/scalars.json`
rather than `scalars_123.json`. This generalizes more cleanly to writing
multiple files under an experiment’s directory.
Test Plan:
Unit tests updated. One previous test case can no longer be hit and has
thus been removed.
wchargin-branch: uploader-export-subdirs
> uploader: export experiments to subdirectories

- tensorboard/uploader/uploader_main.py
Summary:
This `f`-string has no interpolations, so it *can* be a normal string,
and the Bazel target is marked `srcs_version = "PY2AND3"`, so it *must*
be a normal string.
Test Plan:
This module now parses under Python 2:
```
python2 -c '__import__("ast").parse(__import__("sys").stdin.read())' \
<tensorboard/uploader/uploader_main.py
```
wchargin-branch: uploader-remove-fstring
> uploader: remove inoperative `f`-string

- tensorboard/uploader/BUILD
- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
- tensorboard/uploader/uploader_main.py
Summary:
The `StreamExperiments` RPC response used to send only `experiment_ids`,
but now sends `experiments` with additional metadata. This server-side
change has been live since late November 2019, so we’re confident that
we won’t need to roll it back. Thus, we can drop compatibility for the
old code path in new uploader clients.
Test Plan:
Unit tests updated; verified that the `list` and `export` subcommands
still work.
wchargin-branch: uploader-require-experiment-metadata
> uploader: require experiment metadata from server

- tensorboard/backend/event_processing/event_file_loader.py
This puts a nice 🩹 over the deprecation warning spam emitted to the console by our usage of `tf.compat.v1.io.tf_record_iterator` (which we now do for new TF versions, as of https://github.com/tensorflow/tensorboard/pull/3185).
Actually migrating to something not deprecated is still tracked in #1711.
> Silence deprecation warning spam about tf_record_iterator

- .github/workflows/ci.yml
- pyproject.toml
- tensorboard/data/provider.py
Summary:
In Python as of PEP 3102, function definitions may include keyword-only
arguments after a splat (`def foo(x, *, y)`). But cPython 3.5 has a
parser bug (<https://bugs.python.org/issue9232>) when trailing commas
are used with this syntax, as in `def foo(x, *, y,)`. This is fixed in
Python 3.6 and up, but not backported to 3.5, so for now we should make
sure to omit these trailing commas.
The change to `pyproject.toml` prevents Black from re-introducing these
trailing commas. We leave `py27` in the `pyproject.toml` to avoid a mass
reformat removing `u`-prefixes from Unicode string literals (which is
fine, but should be a separate change for Bazel `srcs_version`).
We don’t run our full test suite on Python 3.5 yet, due to unrelated
issues (primarily, lack of `assert_not_called` and …
> Use cPython 3.5–compatible function definitions

- tensorboard/uploader/uploader_main.py
Test Plan:
Run `tensorboard dev update-metadata --experiment_id x --name z` (which
raises an `InvalidArgumentError` because `x` is not a valid ID). Before
this patch, this crashes with a stack trace:
```
File ".../tensorboard/uploader/uploader_main.py", line 478, in execute
"Server responded: %s" % cm.description()
AttributeError: 'InvalidArgumentError' object has no attribute 'description'
```
Now, it prints a proper error message:
```
Server cannot modify experiment as requested: Invalid experiment ID: 'x'
```
wchargin-branch: uploader-fix-einval
> uploader: fix invalid argument error handling

- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
The image plugin dashboard seems like below : 
Therefore I solved the text of heading to default size which seems :
> Size of text in heading changed to default style in Image plugin dashboard

- WORKSPACE
TensorBoard uses TensorFlow mirror so we do not hit github.com when building
TensorBoard. 
This change adds missing TensorFlow mirror before github.com so our build is
more reliable (it falls back to github.com if the mirror is down).
> cleanup: mirror bazel_{nodejs,sass} rules

- tensorboard/uploader/proto/tensor.proto
Renaming a proto before its been used, to follow the newly set naming scheme.
> Rename TensorPointMetadata to TensorTag

- .github/workflows/ci.yml
- third_party/js.bzl
With autoformatter for JS and Python, we got used to auto-formatting
everything. Similarly, BUILD files can be formatted and validated using
buildifier but we currently do not apply it to .bzl.
However, recently, there were needs to make changes to js.bzl and, due
to its bad formatting, a single line change in js.bzl makes the overzealous
autoformatter change many lines which is quite bad for code review. This
change only auto-formats the js.bzl with buildifier for future edits.
> Buildifier format js.bzl for future edits

- .github/workflows/ci.yml
Summary:
The `flake8`, `black`, and `yamllint` workflows currently install all
dev dependencies even though they only need their respective linters.
This pulls in a bunch of stuff, like `grpcio-testing`, `docker`, and
`boto3`, and takes about 30 seconds per job. It should be significantly
faster to only install the distributions that are actually required.
Test Plan:
Check that the “Install flake8” (etc.) workflow steps now take only a
handful of seconds rather than 25–30 seconds.
wchargin-branch: ci-tight-lint-installs
> ci: tighten Pip installs for linting

- tensorboard/webapp/app_module.ts
- tensorboard/webapp/reducer_config.ts
Previously, even in the debug mode, the logger metaReducer had no
effect. When debugging the issue, it was found that the ngfactory which
is part of Angular's DI system prebuilds injectable for the META_REDUCER
and inlines an empty object [1]. Do note that this problem only manifests
when we try to configure metaReducer in a conditional. Also do note that
calling `isDevMode()` method is disallowed in AOT compiler, which is the
default compiler in Angular 9.
Tested the correct behavior under `bazel run -c dbg` vs. `bazel run`.
[1]: To reproduce, please build without this commit and inspect
bazel-bin/tensorboard/webapp/app_module.ngfactory.js. Look for, in very
dense code, USER_PROVIDED_META_REDUCERS and notice that it provides
an empty array.
> ng: reconfigure MetaReducer to use Injectable

- .git-blame-ignore-revs
Tested by configuring git to use the .git-blame-ignore-revs and `git blame third_party/js.bzl`.
> cleanup: add third_party/js.bzl format to ignore

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/experimental_plugin.py
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/program.py
Allow an administrator of a Tensorboard to mark certain plugins as "experimental" and hidden to users by default. Users would then need to add query parameter "experimentalPlugin=" to the URL to see the experimental plugin.
Introduce simpler marker class ExperimentalPlugin which acts as an annotation on either TBPlugin or TBLoader that indicates a plugin is experimental. TensorBoardWSGIApp() uses isinstance() to determine if a plugin is experimental and passes the information as a list of names, "experimental_plugins", in its call to TensorBoardWSGI()
TensorBoardWSGI._serve_plugins_listing() filters out plugins that are included in experimental_plugins but are not specified in an experimentalPlugin query parameter. …
> Experimental plugins specified using ExperimentalPluginLoader

- tensorboard/components/vz_chart_helpers/plottable-interactions.js
Fixes #3282.
Repro case: when tooltip is shown, slowly move the mouse to an edge of a
chart. We expect the tooltip the disappear when the cursor is on the
edge of the chart.
Cause:
1. For Polymer 2 and its Shadow DOM compatibility, TensorBoard opted out of the
event delegation of Plottable. Plottable, by default, attaches a set of event
listeners on document.body and appropriate callbacks depending on the
circumstances. In Shadow DOM, the event re-targetting broke (harder to identify
`event.target`) so TensorBoard, instead, attaches event listeners on every
Plottable container, SVGs.
2. When mouse leaves (mouseout) the container, Plottable remaps the event as
mouse move and calculate whether the cursor is inside a component
(Interaction.prototype._isInsideComponent, specifically) to …
> bug: fix the tooltip not disappearing issue

- tensorboard/defs/defs.bzl
- tensorboard/webapp/BUILD
- tensorboard/webapp/styles.scss
- tensorboard/webapp/theme/BUILD
- tensorboard/webapp/theme/_tb_palette.scss
- tensorboard/webapp/theme/_tb_theme.scss
Absolute dependencies on "tb-theme" allows us to provide different theme
files for different applications.
Related change: cl/299960760
> ng: refactor theming for reusability

- tensorboard/webapp/BUILD
- tensorboard/webapp/core/actions/core_actions.ts
- tensorboard/webapp/core/effects/core_effects.ts
- tensorboard/webapp/core/effects/core_effects_test.ts
- tensorboard/webapp/header/BUILD
- tensorboard/webapp/header/header_component.ts
- tensorboard/webapp/header/header_module.ts
- tensorboard/webapp/header/header_test.ts
- tensorboard/webapp/header/reload_container.ts
- tensorboard/webapp/testing/mat_icon.module.ts
- third_party/js.bzl
Polymer based TensorBoard renders info icon that brings user to our
documentation on GitHub and reload button for manual reload. This change
enables both in ng tensorboard.
**Screenshot**
> ng: implement reload button and info icon

- tensorboard/plugin_util.py
Summary:
Calling `markdown.markdown(s, ...)` is shorthand for creating a Markdown
converter `md = markdown.Markdown(...)` and calling `md.convert(s)` on
the converter. But the initialization is expensive when extensions are
in play: it requires iterating over package entry points, dynamically
importing modules, and mutating the newly initialized converter.
On my machine, rendering an empty Markdown string takes 123 µs (±322 ns)
with a fresh converter, or 96.7 ns (±1.05 ns) with a cached converter.
By default, the text plugin downsamples to 10 samples per time series,
but each sample can have an arbitrary number of Markdown calls when the
summary data is rank-1 or rank-2. Most non-text plugins also call this
to render summary descriptions. Loading the scalars plugin with my
standard test …
> plugin_util: cache Markdown converter for speed

- .github/workflows/ci.yml
This should hopefully help make this even more self-service by indicating to the PR author exactly what the problem is in the file.
> lint: add --diff flag to show black diff

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/extract_dtypes_from_python.py
- genrule should use `exec_tools` for Python 3 (defaults to Python 2
otherwise).
- chmod -x on the Python file
- import order for lint
> debugger: fix genrule for sync

- tensorboard/uploader/proto/blob.proto
This reverts commit 89f5a6a72c599b3b44578d14f4c032c2a8f279ba.
That commit was submitted prematurely, in that the corresponding internal change was not yet approved, so it broke the sync.
> Revert "Rename BlobState enum values (#3355)"

- third_party/js.bzl
With removal of interactive-interference plugin source from the repo, we
can now get rid of these dependencies.
> cleanup: unused dependencies from js.bzl

- tensorboard/uploader/proto/blob.proto
Reapply commit 89f5a6a aka #3355, after it was reverted in #3363.
The internal changes needed to allow this to sync cleanly have been submitted.
> Rename BlobState enum values (#3355)

- tensorboard/program.py
The TensorBoard log told me to go to `http://laptop-name.corp.domain.tld:6006` and that connection failed, but `http://localhost:6006` worked.
I tested the connection to the host with `socket()`, and if it is closed, the host becomes `localhost`.
No UI changes.
I ran `export PYTHONPATH="$PYTHONPATH:$HOME/code/tensorflow:$HOME/code:tensorboard"; python3 tensorboard/program.py`, which threw this unrelated error (and both repos are in sync with upstream):
```
File "/Users/mmorin/code/tensorboard/tensorboard/data_compat.py", line 24, in <module>
from tensorboard.compat.proto import summary_pb2
ImportError: cannot import name …
```
> Confirm that the connection to tensorboard works or change to localhost

- tensorboard/defs/defs.bzl
- tensorboard/webapp/styles.scss
- tensorboard/webapp/theme/BUILD
- tensorboard/webapp/theme/_tb_theme.template.scss
- tensorboard/webapp/theme/_variable.scss
We have different instances of the TensorBoard that need to be themed
differently (colors and definitions of the colors). Because include_path
of sass_binary is getting deprecated, we decided to use genrules to
conditionally supply correct colors when building the SASS.
Sync: requires cl/300794214. 
End state: cl/300395379
> ng: allow palette to be inlined via genrule.

- tensorboard/compat/tensorflow_stub/io/gfile.py
> Added S3_ENDPOINT variable

- tensorboard/uploader/proto/blob.proto
- tensorboard/uploader/proto/export_service.proto
* Support tbdev uploader's exporting of BLOBs (e.g., GraphDefs)
* Add the following message types to tensorboard/uploader/proto/blob.proto:
* `Blob`, with fields blob_id and state (using the existing `BlobState` message type in the same file)
* `BlobSequence`, which is composed of `Blob`s
* In tensorboard/uploader/exporter_service.proto:
* Add the following message type:  `BlobSequencePoints`, this is in parallel to the existing `ScalarPoints` and `TensorPoints` message types in the same file.
* Change the existing `points` (scalars), `tensors`, and to-be-added `blob_sequences` into a `oneof`.
* Add the following rpc method to `TensorBoardExporterService`: `StreamBlobData`.
Co-author: wchargin@
> Add message types and rpc method to support exporting BLOBs

- yarn.lock
minimist < 1.2.2 is known to be vulnerable to CVE-2020-7598.
This change upgrades all transitive dependencies.
Simply ran `yarn upgrade`. 
`yarn audit` reports no issues after the upgrade.
> sec: update transitive dependencies

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
- tensorboard/uploader/uploader_main.py
Allow uploader users to specify the plugins for which data should be uploaded. It has two-fold purpose: 
(1) Allow users to specify "experimental" plugins that would otherwise not be uploaded.
(2) Allow users to list a subset of launched plugins, if they do not want to upload all launched plugin data.
Add "--plugins" command line option for upload subcommand. The information is sent in the ServerInfoRequest (aka the handshake) and may impact the list of plugins returned in ServerInfoResponse.plugin_control.allowed_plugins.
Sample usage:
tensorboard dev upload --logdir <log dir> --plugins scalars graphs histograms
Outside of these specific changes:
It's expected that supported servers will evaluate the list of plugins …
> Add --plugins option to uploader

- tensorboard/plugins/hparams/BUILD
Test Plan:
Importing `tensorboard.plugins.hparams.metadata` from `dataclass_compat`
no longer causes all the tests to break.
wchargin-branch: hparams-metadata-proto-dep
> hparams: add missing build dep to `:metadata`

- tensorboard/uploader/proto/blob.proto
- tensorboard/uploader/proto/export_service.proto
This reverts commit 2f83ec5ebf40bac5870a20faba10dbeb9ffae167.
* Sync failed due to a name clash. Reverting the PR that introduce the clashing `BlobSequence` message type first. Will fix the internal duplication first.
> Revert "Add message types and rpc method to support exporting BLOBs (#3373)

- tensorboard/uploader/proto/blob.proto
- tensorboard/uploader/proto/export_service.proto
This reverts commit 93759282d4dab7f5b6f3d6899cee719d1249edc6.
* go/tbpr/3373 had proto message type name clashes. It was rolled back to unblock sync'ing of other PRs.
* Now that the name clash should have been addressed through internal code changes, we are rolling the PR forward.
* This PR is an exact rollback of the rollback (go/tbpr/3384)
* As discussed elsewhere, the message type `Blob` can consist of a `string url = 3` field. But I refrained from adding it in this PR, to keep it simple. The field can be added in separate PRs.
> Roll forward "Add message types and rpc method to support exporting BLOBs"

- tensorboard/compat/proto/allocation_description.proto
- tensorboard/compat/proto/api_def.proto
- tensorboard/compat/proto/attr_value.proto
- tensorboard/compat/proto/cluster.proto
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/cost_graph.proto
- tensorboard/compat/proto/debug.proto
- tensorboard/compat/proto/function.proto
- tensorboard/compat/proto/graph.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/node_def.proto
- tensorboard/compat/proto/op_def.proto
- tensorboard/compat/proto/resource_handle.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/saver.proto
- tensorboard/compat/proto/step_stats.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/compat/proto/summary.proto
- tensorboard/compat/proto/tensor.proto
- tensorboard/compat/proto/tensor_description.proto
- tensorboard/compat/proto/tensor_shape.proto
- tensorboard/compat/proto/trackable_object_graph.proto
- tensorboard/compat/proto/types.proto
- tensorboard/compat/proto/variable.proto
- tensorboard/compat/proto/verifier_config.proto
- tensorboard/compat/proto/versions.proto
Summary:
These are synced to TensorFlow tag v2.2.0-rc0 which resolves to
3c1e8c03419266bb6ba379d303d3e03a380617a8
Test Plan:
Running `bazel test //tensorboard/compat/proto:proto_test` now passes in
a virtualenv with `tensorflow==2.2.0rc0` installed.
Fixes #3391
> proto: sync to TensorFlow v2.2.0-rc0

- docs/_index.yaml
Add a link to TensorBoard.dev in the TensorBoard docs home page.
Comments on exact wording are welcome.
> Add link to TensorBoard.dev in the TensorBoard docs home page

- docs/tbdev_getting_started.ipynb
Add the new name and description capability to the [Colab example](https://colab.sandbox.google.com/github/tensorflow/tensorboard/blob/master/docs/tbdev_getting_started.ipynb). This will help new users discover this feature.
> Add name and description to Colab example

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
- tensorboard/uploader/uploader_main.py
This reverts commit 343456b5768f290b9d8bc8483fec954c0074f4b7.
Test Plan:
Running `bazel run //tensorboard -- dev list` now works. Previously, it
failed with:
```
File ".../tensorboard/uploader/uploader_main.py", line 750, in _get_server_info
server_info = server_info_lib.fetch_server_info(origin, flags.plugins)
AttributeError: 'Namespace' object has no attribute 'plugins'
```
wchargin-branch: revert-uploader-plugins-flag
> Revert "Add --plugins option to uploader (#3377)"

- tensorboard/compat/proto/proto_test.py
Improves an error message, giving better advice for how to fix the common issue wherein tf and tb proto common definitions have diverged.
Tested:
*  Deliberately caused a proto mismatch and witnessed the new error message.
*  Fixed the proto mismatched and saw the test passes.
> EngProd: Improve error message for fixing mismatched tf protos.

- package.json
- tensorboard/BUILD
- tensorboard/components/tf_imports/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/monaco/BUILD
- yarn.lock
* Roll forward go/tbpr/3374 with fixes.
* Same as go/tbpr/3374, with the following exception: the `tf_web_library` BUILD targets for requirejs, monaco-editor (core) and monaco-languages are moved to a dedicated BUILD file (tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/monaco/BUILD) to facilitate sync'ing.
* copybara change CL: CL/302218915
* Final state: CL/302222581. Build passes, after some manual reverts deal with JSCompiler artifacts
* Alternative: use copybara rules to make the requirejs, monaco-editor and monaco-languages rules BUILD internally.
* Con: Those transformed …
> [DebuggerV2] Add shim for loadMonaco() method & supporting 3rd-party libraries

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 2.2.0 release process:
- Bump tb-nightly version to 2.3.0a0
- Cherrypick of 2.2.0 relnotes added to RELEASE.md
> Post release 2.2.0

- tensorboard/plugins/graph/keras_util_test.py
- `Sequential.get_config()` is changing
- This PR updates the golden values used in TB tests for Sequential configs
- And also disables the tests to prevent them from failing on the old format
- Please reenable the tests atfer the `Sequential.get_config()` change is merged
> Update golden values and disabled corresponding tests in keras_util_test

- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Previously, we were reloading all stamped dashboards which is not the
behavior of the tf-tensorboard.
Side-effect: because we were reloading scalars dashboard when it was in
the background, the charts could more frequently appear tiny when the
reload kicked in. This change removes that bug.
> ng: reload now only reloads current dashboard

- tensorboard/webapp/BUILD
- tensorboard/webapp/app_module.ts
- tensorboard/webapp/feature_flag/BUILD
- tensorboard/webapp/feature_flag/actions/BUILD
- tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
- tensorboard/webapp/feature_flag/effects/BUILD
- tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
- tensorboard/webapp/feature_flag/feature_flag_module.ts
- tensorboard/webapp/feature_flag/store/BUILD
- tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
- tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_types.ts
- tensorboard/webapp/feature_flag/store/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/webapp_data_source/BUILD
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_testing.ts
We do not currently have a solid design for our flagging (experimental)
system. Regardless of the details of the system, because the flagging
system can impact many things (e.g., UI, data source, etc...), we want
to persist the flagging state in the store.
This is laying that foundation with a QueryParams backed implementation.
> ng: create feature_flag store for enabling exp features

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
* Previously, a source-file content was always loaded from the data source even if it's been loaded already.
* In this PR, we change the behavior so that source files that are already loaded or currently loading are not requested again under the `sourceLineFocused` action.
* Unit test added.
* Verified in a child PR that no repeated request occurs in the browser.
> [DebuggerV2] Avoid loading source files that are loaded or loading

- tensorboard/backend/application.py
- tensorboard/plugins/core/core_plugin.py
Summary:
Until now, `context.data_provider` was provided unless `generic_data`
was explicitly set to `false`. Now, it’s provided in all cases (except
the legacy DB modes). This was always expected to be safe, and has been
live by default since TensorBoard 1.15.0.
This is needed to write plugins that unconditionally assume that a data
provider is available.
A consequence of this is that `is_active`’s use of the experimental
`list_plugins` method is now always on as well. This has been on by
default for two months, but was first released in TensorBoard 2.2.0
(just released), so it’s slightly riskier, but also expected to be safe.
Test Plan:
Run TensorBoard with `--generic_data false`. If pointing at an empty
logdir, no plugins are shown as active. If pointing at a full plugin,
all …
> backend: always provide data provider on context

- tensorboard/backend/application.py
- tensorboard/plugins/hparams/hparams_plugin.py
Summary:
Until now, the hparams plugin has been active only when hparams data is
present *and* the scalars plugin is loaded and active. This cross-plugin
dependency is unique and doesn’t fit well into the data provider world,
so we remove it. The hparams plugin is now active iff hparams data is
available, via the standard `data_plugin_names` API.
Correspondingly, we loosen the error handling in parts of the plugin
that rely on the scalars plugin being active. As long as the scalars
plugin is included in the TensorBoard instance, this should not be a
problem: TensorBoard core loads all plugins before accepting requests to
any of them. If the hparams plugin is used in an installation with no
scalars plugin, the errors will now be 404s instead of 500s. This seems
acceptable, as running …
> hparams: follow standard `is_active` pattern

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
These symbols do not appear to be Tensorflow-specific, and are already part of the standard Closure Compiler externs, which may introduce errors when both definitions are used at the same time.
> Add suppression to externs that conflict with Closure Compiler builtins.

- tensorboard/webapp/feature_flag/BUILD
- tensorboard/webapp/feature_flag/effects/BUILD
- tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
- tensorboard/webapp/webapp_data_source/BUILD
Our test BUILD targets missed strict dependencies on "@angular/core/testing" and "@ngrx/store/testing". 
Resolved all missing deps and fixed the TypeScript conformance error.
Test: cl/303168891
Merge strat: rebase (two logically separate commits)
> ng: unblock sync by resolving missing deps

- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
There are many instances when vz_line_chart can be waiting to be
redrawn: it can wait for debouncing, requestAnimationFrame, and/or data.
One of the way Polymer based TensorBoard solved this asynchronousity is
by "visibility: hidden"ing the plugin container instead of "display:
none". This has an effect of giving the container non-zero width and
allows the vz_line_chart to properly render even in the background.
This change replicates
https://github.com/tensorflow/tensorboard/blob/34530f4789647a81687cc2983866820096b831b1/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L412-L418.
> ng: fix tiny charts

- tensorboard/plugins/audio/audio_demo.py
- tensorboard/plugins/scalar/scalars_demo.py
Summary:
The audio and scalars demos wrote runs with embedded colons, like
`wave:01,sine_wave`. But Windows prohibits colons in file and directory
names. This patch changes the demos to emit paths that Windows likes.
Fixes #3445.
Test Plan:
Run the audio and scalars demos:
```
rm -rf /tmp/audio_demo /tmp/scalars_demo
bazel run //tensorboard/plugins/audio:audio_demo
bazel run //tensorboard/plugins/scalar:scalars_demo
```
Then, check the output to ensure that all filenames use only characters
that are valid on Windows:
```
find /tmp/audio_demo /tmp/scalars_demo -printf '%f\n' |
grep '[<>:"/\\|?*]'
```
Running the same query over a logdir of all existing demo output shows
that audio and scalars were the only offenders.
wchargin-branch: demo-windows-paths
> demos: use Windows-compatible path names

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/list_session_groups.py
This refactors some parts of the hparams plugin to minimize the number of times it calls `context.hparams_metadata()` since each one translates to a `DataProvider.list_tensors()` call that may be expensive.  We do this by basically getting the result of the unfiltered `hparams_metadata()` call (ignoring the tag filters) once at the start of the request, and then refactoring all the subsequent places that would call `hparams_metadata()` so that they just look up the tags they need from that dict rather than making a new call.
The result should be that we now only call `hparams_metadata()` once for both the `/experiment` and `/list_session_groups` routes.  This should be a pretty much strict improvement (no matter how fast the backing RPC is) with the only possible exception being that …
> hparams: minimize calls to context.hparams_metadata()

- tensorboard/uploader/proto/experiment.proto
* Towards fixing b/152749189: displaying the number of blob bytes that an experiment contains int the `tensorboard dev list` command output
* Add a `total_blob_bytes` field to the `Experiment` proto, which is the respnose message type of `StreamExperiemnts`
> Uploader: Add `total_blob_bytes` field to `Experiment` proto

- README.md
I didn't realize GitHub Actions was actually running as CI (rather than just on PRs) so this helps remind folks like me :)
Taken from the "Create Status Badge" button on https://github.com/tensorflow/tensorboard/actions?query=workflow%3ACI.
> README.md: add GitHub Actions CI badge

- docs/r1/overview.md
Fixed 2 broken links that were pointed out in #2814.
Fixes #2814.
> docs: fix broken links in `overview.md`

- tensorboard/uploader/proto/write_service.proto
- tensorboard/uploader/uploader.py
Quota management assumes that the blob's final size is available before we allow the upload to begin.  The existing quota tools correctly allocate or reject based on a known final size, but the backend at present is always passing zero, with a comment that it should be added to the request.
> Include the size of the blob in the WriteBlobRequest

- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
* As we discussed during the code review of #3410, the two py2-compatible file-system functions used by uploader can be removed, because pip releases and bazel tests of the uploader are py3 only now. This will cut some lines of code and reduce complexity and maintenance overhead. 
* Remove the `_open_excl()` and `_mkdir_p()` functions from exporter.py. 
* Remove the no-longer-used custom error class `OutputFileExistsError`
* Remove their unit tests in exporter_test.py
* Replace their usages with the equivalent py3 versions.
> Uploader: remove py2-compatible versions of file-system functions

- docs/migrate.ipynb
This notebook was broken because it didn't have an `import tensorflow as tf`.
TF2 is the default in Colab now.  You can delete these `%tensdorflow_version` from all your notebooks.
> docs: import TensorFlow in `migrate.ipynb`

- .github/workflows/ci.yml
As a developer, it is super easy to erroneously commit fdescribe or
fit. This lint protects against that.
> cleanup: lint and protect against skipped tests

- .github/workflows/ci.yml
Summary:
A new version of `nbfmt.py` enforces that notebooks be identical to the
formatted versions, whereas previously trailing whitespace was ignored:
<https://github.com/tensorflow/docs/commit/04458102aafe1ccc9d703b832db3ac4d038ecd6c>
Test Plan:
All existing docs are correctly formatted and so CI still passes.
Removing the final newline from one of the docs now causes CI to fail:
<https://github.com/tensorflow/tensorboard/runs/552833330>
wchargin-branch: nbfmt-enforce-exact
> ci: update `nbfmt.py` to enforce exact output

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_main.py
- tensorboard/uploader/uploader_test.py
Introduces a new `UploadLimits` submessage within `ServerInfoResponse`, to allow the server to advise the uploader client about limits that it should honor (e.g. things like data sizes, upload rates, and so on).
The only limit actually supported is `max_blob_size`.  The uploader uses this value to skip sending large blobs that the server would end up rejecting anyway. 
Context: b/152312275, b/152770109, and internal email threads.
> Provide upload limits in ServerInfo, and skip uploading blobs that are too large

- tensorboard/uploader/proto/experiment.proto
* Add the field mask for the `total_blob_bytes` field added in #3448
> uploader: Add field mask for total_blob_bytes

- tensorboard/uploader/BUILD
- tensorboard/uploader/flags_parser.py
- tensorboard/uploader/flags_parser_test.py
- tensorboard/uploader/uploader_main.py
Move flag-defining and parsing logic out of uploader_main.py into its own flag_parser.py file.  Add some very basic tests for the moved logic.
Ran new tests for flag_parser.py.
Ran several commands and ensured they ran to completion:
bazel run //tensorboard -- dev list
bazel run //tensorboard -- dev upload --logdir <some log dir> --plugins badplugin1 badplugin2
bazel run //tensorboard/uploader -- upload --logdir <some log dir> --plugins badplugin1 badplugin2
> Move uploader flag parsing to its own file and add basic tests

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Continue developing the HTTP backend of DebuggerV2: the `/graph_execution/digests` serves small-size digest data objects for intra-graph execution events.
* The added route `/graph_execution/digests` is a parallel to the existing route `/execution/digests`
* The underlying methods are also parallels to the existing execution route:
* `DebugDataMultiplexer.GraphExecutionDigests()` --> `DebugDataMultiplexer.ExecutionDigests()`
* `DebuggerV2Plugin.serve_graph_execution_digests()` --> `DebuggerV2Plugin.serve_execution_digests()`
* A follow-up PR will add the corresponding route for serving detailed data objects (i.e, `/graph_execution/data`)
* Unit …
> [DebuggerV2] Add HTTP route /graph_execution/digests

- tensorboard/components/BUILD
- tensorboard/components/polymer_lib.html
- tensorboard/components/tensorboard.uninlined.html
- tensorboard/webapp/BUILD
- tensorboard/webapp/index.uninlined.html
ng_polymer_lib and tensorboard.html should differ in only two things:
- only former has Angular related code bundled separately.
- only latter has entry point for tf-tensorboard
(`<body><tf-tensorboard>`).
This change refactors so that all the Polymer binary without the entry
point is shared between Polymer TensorBoard and Angular TensorBoard.
> build: refactor ng_polymer_lib to be reused.

- tensorboard/BUILD
Summary:
Needed for `tensorboard.__version__` to resolve, as used by (e.g.) the
What-If Tool. Fixes #3484.
Test Plan:
Running `bazel run //tensorboard -- --logdir /tmp/logs` in a virtualenv
with `tensorboard-plugin-wit==1.6.0.post3` installed now works, instead
of failing with:
```
File "/VIRTUAL_ENV/lib/python3.7/site-packages/tensorboard_plugin_wit/wit_plugin_loader.py", line 51, in load
version = pkg_resources.parse_version(tensorboard.__version__)
AttributeError: module 'tensorboard' has no attribute '__version__'
terminate called without an active exception
Fatal Python error: Aborted
```
wchargin-branch: build-include-init
> build: include `__init__.py` in `//tensorboard`

- tensorboard/webapp/BUILD
- tensorboard/webapp/core/BUILD
- tensorboard/webapp/core/core_module.ts
- tensorboard/webapp/core/store/BUILD
- tensorboard/webapp/core/store/core_initial_state_provider.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/views/BUILD
- tensorboard/webapp/core/views/hash_storage_component.ts
- tensorboard/webapp/deeplink/BUILD
- tensorboard/webapp/deeplink/deeplink_module.ts
- tensorboard/webapp/deeplink/deeplink_test.ts
- tensorboard/webapp/deeplink/hash.ts
- tensorboard/webapp/deeplink/hash_test.ts
- tensorboard/webapp/deeplink/index.ts
- tensorboard/webapp/deeplink/types.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Noet that this introduces deeplink module that manages everything
related to deeplinking.
Deeplinking, whether we have a router or not, is a feature want to
support. Since most of the deeplink states are present in the hash, the
module is responsible for read/write with the hash directly.
hash_storage module should be part of the deep link module but since it
is already being used internally, we will have to make a careful changes
while not breaking any apps. The change will be made in a follow up.
> ng: bootstrap core store from hash

- yarn.lock
Summary:
Bazel keeps trying to regenerate this, adding ~25 seconds of latency to
seemingly random `bazel` commands. Hopefully this will fix it.
Generated by checking out a clean copy of origin/master and running
`bazel query //tensorboard`, which has the side effect of updating
`yarn.lock`.
Test Plan:
Ran `bazel query //tensorboard` again, and… it regenerated it, not
making any changes. But I ran it a third time and it did nothing. Only
time will tell.
wchargin-branch: regenerate-yarn-lock-20200406
> build: update `yarn.lock`

- DEVELOPMENT.md
Summary:
TensorBoard only supports Python 3, but on some systems `virtualenv`
defaults to Python 2, so we update the dev instructions to explicitly
specify which Python to use.
wchargin-branch: docs-virtualenv-py3
> docs: specify Python 3 for virtualenv creation

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/get_experiment.py
Summary:
This method makes it easy to accidentally make too many data provider
queries by hiding an `hparams_metadata` call. It only has one caller, so
we just inline it.
Addresses a deferred review comment from #3449.
Test Plan:
Unit tests pass, and the dashboard still behaves as expected for logdirs
with hparams and an experiment summary, with hparams but no experiment
summary, and with no hparams data at all.
wchargin-branch: hparams-inline-experiment
> hparams: inline `Context.experiment`

- tensorboard/plugins/hparams/backend_context.py
Summary:
Addresses a deferred review comment from #3449. This shouldn’t matter in
practice, because `HParamsPluginData` values always supposed to have one
of the `oneof data` fields set, so even an experiment with no hparams,
no metrics, and no start time would have plugin content of `\x12\x00`.
But conceptually this code is trying to check for `None`, not “`None` or
empty”, so this saves future readers from having to convince themselves
that the two conditions are equivalent.
Test Plan:
Unit tests pass and a spot-check of the dashboard checks out.
wchargin-branch: hparams-empty-plugin-content
> hparams: recognize empty plugin content

- docs/tbdev_getting_started.ipynb
Summary:
The Colab image has the latest version of TensorBoard (2.2.0) bundled,
so there’s no need to go through a separate install.
Test Plan:
Clicked “Run all” in Colab, and the whole notebook worked as designed.
wchargin-branch: docs-tbdev-no-pip-install
> docs: remove `pip install` from TensorBoard.dev guide

- docs/tensorboard_profiling_keras.ipynb
* Motivation for features / changes:
1. Saved the notebooks with outputs enabled (and private outputs disabled) as a workaround to prevent broken iframes rendering on tensorflow.org
2. Made some minor text changes and added a link to the Dev Summit 2020 talk
> docs: update profiler tutorial

- tensorboard/components/tf_tensorboard/autoReloadBehavior.ts
- tensorboard/components/tf_tensorboard/test/autoReloadTests.ts
Reduce the load on TensorBoard servers by disabling auto reload if the page is not considered visible.
Do not auto reload if document is not visible according to the Page
Visibility API. When page again becomes visible perform an auto reload
if one has been missed.
Run a local TensorBoard.
Open localhost:6006.
Ensure option "Reload data every 30s." is selected.
Open detached network tab in chrome developer tools.
Watch for several minutes and observe that many network calls are made every 30s.
Open different tab in same window but with chrome developer tools still visible.
Watch for several minutes and observe that no network calls are made.
Switch …
> Disable auto reload if page is not visible

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Continue developing the HTTP backend of DebuggerV2: the `/graph_execution/data` serves full-size data objects for intra-graph execution events.
* This is a followed up #3472 that added the `/graph_execution/digests` route.
* The added route `/graph_execution/digests` is a parallel to the existing route `/execution/data`
* The underlying methods are also parallels to the existing execution route:
* `DebugDataMultiplexer.GraphExecutionData()` --> `DebugDataMultiplexer.ExecutionData()`
* `DebuggerV2Plugin.serve_graph_execution_data()` --> `DebuggerV2Plugin.serve_execution_data)`
* …
> [DebuggerV2] Add HTTP route /graph_execution/data

- tensorboard/plugin_util.py
Summary:
In #3348, we centralized a shared Markdown converter rather than
creating a new one for each call. But this had the effect of sharing the
converter across threads, which is not supported, as the [API docs
helpfully note][1]. This commit splits the globally shared converter
into separate thread-local converters.
[1]: https://python-markdown.github.io/reference/#Markdown
Test Plan:
Prior to this change, some requests would 500 due to internal errors in
the Markdown converter:
```
File ".../markdown/treeprocessors.py", line 187, in __processPlaceholders
for child in [node] + list(node):
TypeError: 'NoneType' object is not iterable
```
This was always nondeterministic, but I haven’t been able to reproduce
it with this patch, even hammering the dashboard with a bunch of Chrome
tabs or …
> plugin_util: use thread-local Markdown converter

- tensorboard/webapp/core/views/hash_storage_component.ts
- tensorboard/webapp/core/views/hash_storage_test.ts
In the Angular version of TensorBoard, we keep the activePlugin state in
the Ngrx Store. In it, when activePlugin was never set, we use `null` to
denote the emptiness. However, this null state was incompatible with how
hash_storage works.
tf_storage coerces the input, which wrongly coerced the null state
(Angular build tools did not catch the wrong typing) in the activePlugin
to "null" and set the hash as "#null".
This change fixes the issue by converting `null` to '' which tf_storage
understands to be the empty state.
> ng: make sure we do not push 'null' onto hash

- tensorboard/uploader/BUILD
- tensorboard/uploader/formatters_test.py
* @stephanwlee brought to my attention a test failure that happens under certain test configs in `//tensorboard/uploader:formatters_test`
* This failure has to do with different timezone settings that are apparently used in different test environments
* Add a helper method that sets system timezone to "UTC" and use the helper method from the unit tests.
> uploader: use fixed (UTC) timezone in formatter unit tests

- tensorboard/components/tf_tensorboard/autoReloadBehavior.ts
- tensorboard/components/tf_tensorboard/test/autoReloadTests.ts
In #3483 I attempted to pause and restart auto reload behavior based on page visibility. 
Unfortunately a change I made to event handling just before merging into master inadvertently disabled the logic. The change happened in a seam in the code that was not covered by tests.
This change fixes the event handling and improves the test coverage.
> Fix 'visibilitychange' event handling in auto reload logic

- tensorboard/BUILD
- tensorboard/backend/process_graph.py
- tensorboard/dataclass_compat.py
- tensorboard/dataclass_compat_test.py
- tensorboard/uploader/uploader.py
There is no point in uploading GraphDef data that won't be displayed anyway.  In particular, the TensorBoard frontend filters out node attributes larger that 1024 bytes, since it has no good way to present those.  So we may as well filter those out before upload to TensorBoard.dev, so as not to waste bandwidth, storage, and read-time processing.
> Prefilter graphs in the uploader

- tensorboard/components/vz_line_chart2/microbenchmark/BUILD
- tensorboard/components/vz_line_chart2/microbenchmark/README.md
- tensorboard/components/vz_line_chart2/microbenchmark/async.ts
- tensorboard/components/vz_line_chart2/microbenchmark/main.html
- tensorboard/components/vz_line_chart2/microbenchmark/main.ts
- tensorboard/components/vz_line_chart2/microbenchmark/polymer_util.ts
- tensorboard/components/vz_line_chart2/microbenchmark/renders_spec.ts
- tensorboard/components/vz_line_chart2/microbenchmark/reporter.ts
- tensorboard/components/vz_line_chart2/microbenchmark/runner.ts
- tensorboard/components/vz_line_chart2/microbenchmark/spec.ts
- tensorboard/components/vz_line_chart2/microbenchmark/types.ts
vz_line_chart2 feels empirically slow at updating and this benchmark is
an attempt to quantify its speed.
> Add microbenchmark for vz_line_chart

- tensorboard/plugins/debugger_v2/BUILD
* The imminent submission of internal CL/290949452 will cause the test to break due to newly-instrumented Const ops, which are previously untracked. Considering the complexity of the sync'ing of tensorflow and tensorboard code, I'll disable the test first. The test will later be fixed to reflect the newly-added Const ops and then re-enabled. See b/153722488.
* Disable the test by applying proper tags.
> [DebuggerV2] Temporarily disable debugger_v2_plugin_test

- tensorboard/BUILD
Summary:
These should both have been internal from the beginning, but team policy
when `data_compat` was created was to be public by default, and we
followed precedent with `dataclass_compat`. There are no remaining
Google-internal non-TensorBoard dependents.
Test Plan:
Googlers, see <http://cl/305916851> for test sync.
wchargin-branch: vis-lock-down-compats
> build: lock down `data_compat` and `dataclass_compat`

- tensorboard/BUILD
- tensorboard/dataclass_compat.py
- tensorboard/dataclass_compat_test.py
- tensorboard/uploader/uploader_test.py
Since #3497, we parse `GraphDef`s in `dataclass_compat.py` during upload.  If a graph is corrupt, that parsing fails.  Here we catch the resulting exception, issue a warning, and continue (omitting the graph).
This also updates tests to use valid GraphDefs where appropriate, as opposed to `bytes(1024)`, which apparently produces inconsistent results with different proto parsers (e.g., OSS vs. Google internal).
> Detect and skip corrupt GraphDefs

- tensorboard/components/vz_line_chart2/microbenchmark/BUILD
webcomponent_tester has transitive dependency on sinon which is
incompatible with our build rules. Remove to unbreak our CI.
Tested: cl/305912155
> benchmark: remove unused deps

- tensorboard/uploader/uploader_test.py
Summary:
The graph uploader test wasn’t actually covering the blob writing code,
and was set up incorrectly such that the request iterator would throw
when forced.
Test Plan:
The new assertions pass, but fail if the RPC changes are reverted.
wchargin-branch: uploader-graph-write-test
> uploader: fix graph RPC test

- tensorboard/summary/_tf/summary/__init__.py
The logic in `tensorboard/summary/_tf/summary/__init__.py` has a routine where it searches a bunch of possible TF package names in `sys.modules` in order to find the v2 summary API symbols that it needs to re-export.  This can have a false positive for the first package - `tensorflow` itself - since depending on the build configuration, i.e. when building with `--define=tf_api_version=1`, this package still contains the v1 rather than v2 API.  We had attempted to guard against this issue by only using `tensorflow` when `tf.__version__` was 2.x, but this check isn't sufficient because it's still possible to build 2.x TF versions with `--define=tf_api_version=1`.  In that case, this logic would mistakenly try to import the symbols from `tensorflow`, resulting in a bunch of deprecation …
> summary: avoid using 'tensorflow' package in import logic

- tensorboard/uploader/uploader_test.py
Summary:
Fixes an oversight in #3507: we can’t assert that the raw bytes are what
was expected because the code under test does a proto serialization
roundtrip, which is permitted to permute keys.
Test Plan:
Tests still pass; a test sync shows that internal tests pass now, too.
wchargin-branch: uploader-test-proto-equal
> uploader_test: check logical equality of protos

- tensorboard/BUILD
- tensorboard/dataclass_compat.py
- tensorboard/dataclass_compat_test.py
- tensorboard/uploader/BUILD
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_test.py
Summary:
We initially used `dataclass_compat` to perform filtering of large
graphs as a stopgap mechanism. This commit moves that filtering into the
uploader, which is the only surface in which it’s actually used. As a
result, `dataclass_compat` no longer takes extra arguments and so can be
moved into `EventFileLoader` in a future change.
Test Plan:
Unit tests added to the uploader for the small graph, large graph, and
corrupt graph cases.
wchargin-branch: uploader-graph-filtering
> uploader: inline graph filtering from `dataclass_compat`

- yarn.lock
This updates our yarn.lock file to bump our `handlebars` dep from 4.7.3 to 4.7.6 (the latest available release), which I did just by deleting the old entry and rerunning yarn install.  This addresses the easy part of #3516 by picking up https://github.com/wycats/handlebars.js/issues/1658 to prune a transitive dependency via `optimist` on an old version of `minimist`.
> Upgrade handlebars 4.7.3 -> 4.7.6 to avoid optimist dep

- tensorboard/webapp/reloader/reloader_component.ts
- tensorboard/webapp/reloader/reloader_component_test.ts
Note that this is the ng_tensorboard version of #3483.
Reduce the load on TensorBoard servers by disabling auto reload if the page is not considered visible.
Do not auto reload if document is not visible according to the Page
Visibility API. When page again becomes visible perform an auto reload
if one has been missed.
Run a local TensorBoard.
Open localhost:6006.
Ensure option "Reload data" is selected and choose a 15s "Reload Period".
Open detached network tab in chrome developer tools.
Watch for several minutes and observe that many network calls are made every 15s.
Open different tab in same window but with chrome developer tools still visible. …
> Disable auto reload if page is not visible in ng_tensorboard

- tensorboard/compat/__init__.py
Similar to #3515, this is problematic because `tf.__version__.startswith("2.")` does not necessary imply that the TF 2.x API is available at the `tensorflow` root API package; in particular this will not be true if TensorFlow was built with `--define=tf_api_version=1`.
Rather than attempting to detect that situation correctly, as in #3515, we sidestep the problem by just always relying on `tf.compat.v2` regardless of what the root API package is providing. This should be safe because we only care about versions of TensorFlow that should consistently provide the `tf.compat.v2` sub-API, and unlike in #3515 where this is resolved as part of the TensorFlow API import process itself, here the `tf2` lazy loader is only invoked at runtime (i.e. after import time) at which point the API should be …
> compat: avoid tf.__version__ in tf2 API lazy loader

- tensorboard/plugin_util.py
- tensorboard/plugin_util_test.py
- tensorboard/plugins/text/text_plugin.py
Summary:
By design, we only expose an API for converting Markdown to *safe* HTML.
But clients who call this method many times end up performing HTML
sanitization many times, which is expensive: about an order of magnitude
more expensive than Markdown conversion itself. This patch introduces a
new API that still only emits safe HTML but enables clients to combine
multiple input documents with only one round of sanitization.
Test Plan:
The `/data/plugin/text/text` route sees 40–60% speedup: on my machine,
- from 0.38 ± 0.04 seconds to 0.211 ± 0.005 seconds on the “higher
order tensors” text demo downsampled to 10 steps; and
- from 5.3 ± 0.9 seconds to 2.1 ± 0.2 seconds on a Google-internal
dataset with 32 Markdown cells per step downsampled to 100 steps.
wchargin-branch: text-batch-bleach
> text: batch HTML sanitization

- tensorboard/plugins/projector/vz_projector/vz-projector-app.html
`<vz-projector-app>` is piping through the `route-prefix` property however the property was not explicitly defined.
> Add the missing `route-prefix` property to `<vz-projector-app>`

- .travis.yml
- WORKSPACE
Bazel is now out of the beta mode (version 0.x). We want to depend on
1+ for better long term support in the future.
> Upgrade min Bazel required and upgrade CI to use 2.1

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_module.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
- tensorboard/webapp/angular/BUILD
* Continue developing DebuggerV2 plugin, specifically its GraphExecutionContainer that visualizes the details of the intra-graph execution events. 
* Add necessary actions, selectors, reducers and effects to support the lazy, paged loading of `GraphExecution`s
* Add a `cdk-virtual-scroll-viewport` to `GraphExecutionComponent`
* The lazy loading is triggered by scrolling events on the `cdk-virtual-scroll-viewport`
* The displaying detailed debug-tensor summaries such as dtype, rank, shape, and numeric breakdown will be added in the follow PRs. This PR just adds displaying of the tensor name and op type in the `cdk-virtual-scroll-viewport`.
* Loaded state: …
> [DebuggerV2] Flesh out graph execution data display

- tensorboard/webapp/core/store/BUILD
- tensorboard/webapp/core/store/core_initial_state_provider.ts
- tensorboard/webapp/core/store/core_initial_state_provider_test.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_types.ts
Internal application would like to use the intialState for other
purposes. Expose it as a public API.
> ng: expose core initialState as public

- .bazelrc
- WORKSPACE
This updates the minimum version of Bazel we require to build to 2.1.0 so it matches our CI.  As the comment describes, these should stay in sync, since if we aren't actually building with the minimum version or running CI against it, it's easy for it to stop working without anyone noticing, at which point it can fail in a way that's harder to understand than the minimum version check.
If anyone really wants to try building with a lower Bazel version, they can always locally revert this change.
Also removes some .bazelrc options to not use Python toolchains; I'm not sure exactly at what point these become obsolete but they don't seem to have any impact on the build.  Tested that building and running TensorBoard without these options still worked as expected.
> Bump Bazel minimum version to 2.1.0 to match CI

- tensorboard/uploader/uploader_test.py
Identify tests in uploader_test.py that specifically target logic in _ScalarBatchedRequestSender and rewrite them to only use _ScalarBatchedRequestSender and none of the other layers in uploader.py.
This is a useful exercise for the work on _TensorBatchedRequestSender.  I was having a difficult time using _ScalarBatchedRequestSender tests to establish a pattern for testing _TensorBatchedRequestSender.
> Refactor tests for _ScalarBatchedRequestSender

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
We identified few several expensive operations going on underneath Plottable.
- When we modified dataset() attached to a plot, Plottable recalculated
domain which in turn triggered redraw of the plot.
- Plot redraw is scheduled but repeated `clearTimeout` and `setTimeout`
take considerable time which was the large part of the dataset update
- Changing a dataset caused us to updateSpecialDataset N times (N =
number of runs)
We addressed the issue by:
- `commit` API after making all the changes
- remember which runs/dataset were changed
- update datasets only once per commit
Empirically, the render time:
- toggling run on the selector went down from 1740ms to 314ms
- triggering the log scale went down from 315ms to 264ms
- from ~670ms to ~620ms when measured from mouse up
Do note that this …
> improve rerender of vz_line_chart

- tensorboard/BUILD
- tensorboard/main.py
- tensorboard/uploader/BUILD
- tensorboard/uploader/flags_parser.py
- tensorboard/uploader/flags_parser_test.py
- tensorboard/uploader/uploader_subcommand.py
Remove standalone uploader binary target that shouldn't be used any longer.
No longer make //tensorboard/uploader a binary target.
Rename uploader_main to uploader_subcommand.
Clean up some BUILD target names by removing "_lib" suffix.
* Testing
Run unit tests.
Run `bazel run tensorboard/uploader -- list` and bazel complains that target no longer exists.
Run `bazel run tensorboard -- dev list` and bazel succeeds at listing experiments.
> Remove standalone uploader binary target

- tensorboard/components/vz_line_chart2/line-chart.ts
When tooltipColumns become shorter after a change, we currently do not
remove the DOM. This can lead to an awkward UX where a column in the
tooltip never updates and go stale.
This change removes the tooltip row column DOM when they are no longer
shown.
> scalars: remove unused tooltip column DOM

- tensorboard/plugins/debugger_v2/BUILD
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* This is a follow-up / clean-up task for adding Const ops to the set of instrumented ops by tfdbg2 (b/153722488)
* In debugger_v2_plugin_test.py, several assertions related to the exact set of ops executed inside tf.functions (Graphs) are updated to reflect the Const ops that weren't instrumented previously but are now.
* Disabling tags for the task are removed from the BUILD file.
> [DebuggerV2] Revise and re-enable debugger_v2_plugin_test for Const ops

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
* Make it clearer in the StackFrameComponent which frame (if any) is being highlighted in the SourceCodeComponent.
* In StackFrameContainer's internal selector, add a boolean field to the return value called `focused`. It is used in the template ng html to apply a CSS class (`.focused-stack-frame`) to the focused stack frame and only the focused stack frame.
* While adding new unit test for the new feature, simplify existing ones by using `overrideSelector`.
* To conform to style guide, replace `toEqual()` with `toBe()` where applicable in the touched unit tests.
* ![image](https://user-images.githubusercontent.com/16824702/80288736-ed102300-8707-11ea-9638-7aa197a23ff6.png)
* Detailed steps …
> [DebuggerV2] Highlight stack frame being shown in SourceCodeComponent

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Summary:
This reverts commit 27d0023e728aba79d0129f890e41c6c2c4c436b9, then
reinstates stubs for the new method definitions due to Google-internal
code that expects them to exist.
Stopgap for #3551 pending real fix.
Test Plan:
Opening the PR curves dashboard and sliding one of the step sliders now
correctly renders the PR curve instead of showing just the final datum.
wchargin-branch: revert-3524
> Partially revert "improve rerender of vz_line_chart (#3524)"

- tensorboard/plugins/pr_curve/pr_curves_plugin.py
Summary:
The last use of this was removed in #3553.
Test Plan:
Tests still pass, and the dashboard still looks fine.
wchargin-branch: pr-curves-dead-create-time-entry
> pr_curves: remove dead `_create_time_entry` helper

- tensorboard/plugins/pr_curve/pr_curves_plugin.py
Summary:
The `/data/plugin/pr_curves/pr_curves` route needs to know the number of
thresholds for each PR curve summary. Instead of reading that directly
from the summary metadata, we now infer it from the shape of the data
array. This allows us to avoid a `list_tensors` call, which should speed
up the PR curves dashboard in environments where data provider calls
require RPCs or are otherwise expensive.
This should be sound: the PR curve summary documents that the written
tensor is “of dimension `(6, num_thresholds)`”.
Resolves #3554.
Test Plan:
All existing tests pass, and the dashboard still looks fine on the
standard `:pr_curve_demo` dataset.
wchargin-branch: pr-curves-infer-num-thresholds
> pr_curves: compute `num_thresholds` from data size

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
Summary:
We now use the data provider APIs by default for the core, histograms,
images, and text plugins (plus scalars, audio, PR curves, and hparams,
which are not new in this patch). This accounts for all summary-based
primary plugins except for the graphs plugin, which only supports
run-level graphs. In case of emergency, users can still opt out by
passing `--generic_data false`. The plan is to release TensorBoard 2.3
in this state and then remove the legacy paths in TensorBoard 2.4.
Note that the patch to the histograms plugin affects both the histograms
and distributions dashboards.
This is not (intended to be) a user-facing change.
Test Plan:
Note that all modified dashboards still behave properly unless the code
is patched to unconditionally remove the multiplexer from the context …
> Stabilize generic data for plugins at parity

- tensorboard/uploader/uploader.py
I recently read a draft python totw that claims a best practice is to use a "bare raise" when reraising a caught exception/error. I am applying that best practice to some code I recently modified, although it doesn't have any real practical impact.
> Use bare raise for reraising _OutOfSpaceError

- tensorboard/backend/event_processing/BUILD
- tensorboard/components/vz_bar_chart/BUILD
- tensorboard/components/vz_chart_helpers/BUILD
- tensorboard/components/vz_example_viewer/BUILD
- tensorboard/plugins/hparams/external_users/BUILD
- tensorboard/plugins/hparams/tf_hparams_backend/BUILD
- tensorboard/plugins/hparams/tf_hparams_dashboard/BUILD
- tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/BUILD
- tensorboard/plugins/hparams/tf_hparams_main/BUILD
- tensorboard/tools/BUILD
- third_party/BUILD
- third_party/chromium/BUILD
- third_party/protobuf/BUILD
Summary:
This patch ensures that all packages have a `default_visibility` setting
of `//tensorboard:internal` or stricter, while preserving each target’s
visibility by adjusting explicitly as needed. This patch is not intended
to actually change the visibility of any target. The purpose of this
patch is to ensure that removing an explicit `visibility` spec on a
target always leaves that target with TensorBoard-internal visibility.
The `third_party/*.BUILD` (e.g., `third_party/urllib3.BUILD`) shims are
excepted.
Test Plan:
Buildozer says that we got ’em all:
```
$ buildozer 'print default_visibility' //tensorboard/...:__pkg__ | sort -u
[:internal]
[//tensorboard:internal]
[//tensorboard/plugins/hparams:__subpackages__]
[//visibility:private]
```
wchargin-branch: vis-default-lockdown
> build: lock down default visibilities

- tensorboard/__init__.py
Summary:
In particular, `tensorboard.lazy` is private. This was always the intent
and is probably not likely to be super confusing, but we might as well
be as explicit as possible about the extent of our public API surface.
Test Plan:
The Pip package smoke test suffices. As an extra check, after installing
the Pip package into a new virtualenv, `from tensorboard import *` only
imports the desired symbols (cf. `list(locals())`).
wchargin-branch: lib-private
> lib: clarify extents of public API

- tensorboard/webapp/header/header_test.ts
- tensorboard/webapp/header/plugin_selector_component.ng.html
- tensorboard/webapp/header/plugin_selector_component.scss
- tensorboard/webapp/header/plugin_selector_component.ts
cause: mat-tab-group emits the changed event in the Angular's equivalent
to `componentDidUpdate`. The problem is that:
1. it emits the [change in a promise](https://github.com/angular/components/blob/58b8d30efb0e71f0f4bbc541405cda1adce26f16/src/material/tabs/tab-group.ts#L207-L213) (next tick)
2. it emits the change when the value is changed programmatically.
While lacking complete understanding of the flow, empirically, I found there to be some kind of event dispatch queue and the emission to not invoke our callback immediately.
Logging result
<details>
```
11:50:44.922 tab-group: scheduling async
11:50:45.086 tab-group: triggering async
11:50:45.153 tab-group: scheduling async
11:50:45.202 tab-group: triggering async
11:50:45.249 tab-group: scheduling async
11:50:45.274 tab-group: …
```
> ng: fix infinite loop when on plugin selector

- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
The removed line of assertion is problematic, because the two ops belong to two tf.function graphs, which can legally have identical op names. Previously, they were different due to the old way in which we create debugger-generated names for Placeholder ops. But a new, improved way of doing it will cause the names of the ops to be the same. This change needs to be sync'ed in order to unblock the submission of CL/309292117.
> [DebuggerV2] Remove a problematic assertion in debugger_v2_plugin_test

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_subcommand.py
- tensorboard/uploader/uploader_test.py
Backends should be able to impose size limits for uploading individual tensor points, similar to how they can impose size limits for individual blobs.
Fallback to a reasonable default value for the time being while we wait for backends to be updated to provide this information.
Maximum size of tensor points is specified in the handshake response with the frontend. If the value is not present then fallback to some reasonable default. 
If a Tensor point larger than the maximum size is encountered, strip it from write requests and log a warning.
Wrote tests.
Ran uploader with a frontend that does not specify max limit and …
> Allow server to specify maximum tensor upload size

- tensorboard/uploader/uploader.py
There is code internal to Google that creates its own instance of TensorBoardUploader and does not pass max_tensor_point_size. Temporarily allow this by making it a named argument and setting a default that effectively disables tensor uploading.
> Don't require max_tensor_point_size to be set

- tensorboard/uploader/BUILD
- tensorboard/uploader/exporter.py
- tensorboard/uploader/exporter_test.py
* Implement the exporting of tensor values (used in Histograms and other tensorboard dashboards)
* Add a new json file in the exported experiment directory: tensors.json. It contains runs, tags, timestamps and pointers to .npy files in the tensors/ subdirectory.
* Tensor values are saved as .npy (numpy uncompressed) files through the `numpy.save()` method to the tensors/ subdirectory. Their file names are deduplicated wall_times followed by the .npy extension.
* Manual testing against a dev api_endpoint.
> uploader: implement tensor exporting

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
* Continue developing DebuggerV2
* Address the issue in which clicking on the "Inf/NaN" category in the alerts section of the app can focus only onto eager-execution events and not intra-graph execution events previously.
* Add selector for `DebuggerState.graphExecutions.focusIndex`
* Set `DebuggerState.graphExecutions.focusIndex` in the reducer for action `alertsOfTypeLoaded`
* Let the `focusIndex` be an input to `GraphExecutionComponent`. The `Component` listens to changes in the input value with `ngOnChange()` and calls the `scrollToIndex()` method of its constituent cdk-virtual-scroll-viewport element during changes.
* Add an indicator div (right-pointing filled triangle) for the currently-focused graph-execution …
> [DebuggerV2] Clicking on Inf/NaN alerts scrolls to the 1st graph execution with Inf/NaN

- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_reducers_test.ts
Previously, we were wrongly setting it to the first plugin in the
object.
Now, we set it to the first active plugin. If nothing is active, set
it to `null`.
> ng: set active plugin to first enabled plugin

- tensorboard/uploader/formatters.py
- tensorboard/uploader/formatters_test.py
- tensorboard/uploader/uploader_subcommand.py
* Enable uploader's `tensorboard dev list` command to display the amount of tensor data in each experiment. The data is already available in the current server implementation.
* Set the field mask for `total_tensor_bytes` to `True`
* Add human-readable "Tensor bytes" field for the non-JSON mode. This is parallel to the existing "Binary object bytes" field.
* Add the key "tensor_bytes" to the JSON mode. This is parallel to the existing "binary_object_bytes" key.
* Non-JSON mode: ![image](https://user-images.githubusercontent.com/16824702/81098891-053a2c00-8ed8-11ea-88b3-9c6231e95c9c.png)
* JSON mode: ![image](https://user-images.githubusercontent.com/16824702/81099627-37985900-8ed9-11ea-9674-2 …
> uploader: display per-experiment tensor bytes in `dev list` output

- tensorboard/webapp/plugins/plugins_component.ng.html
- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Angular version of the TensorBoard never implemented the page.
The copy and UX is almost exactly that of Polymer's (misses data
location; angular version currently does not fetch environments)
Requires #3584 to see the change.
> ng: no active plugin warning page

- tensorboard/webapp/header/plugin_selector_component.ng.html
We would like our webdriver tests to be able to find these nodes without
inspecting the textNode (with plugin name as opposed to plugin id). This
change adds data attribute adds one.
> ng: add plugin-id on tab for testability

- tensorboard/tools/diagnose_tensorboard.py
Summary:
Issues like #3460, #3481, and #3592 are all caused by an incompatibility
between certain versions of TensorBoard and the standalone What-If Tool.
This patch adds a check to the diagnosis script to warn accordingly.
Test Plan:
Install `tensorflow==2.1.0 tensorboard-plugin-wit==1.6.0.post2` into a
new virtualenv, and note that TensorBoard fails to start. Then run the
diagnosis script and note that it prints a suggestion with a command
that, when executed, solves the problem.
wchargin-branch: diagnose-broken-wit
> diagnose: warn on broken What-If Tool version

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
The issue is better described in #3557. Please refer to it.
Our HTML module traversal relies on the `document` so we cannot create
the document without nested document in one go. Instead, we do a post
processing of the document to prune away all the `document` so the
default jsoup's printer can print them without awkward `<#root>`
elements.
index.html size difference:
```
555323 before
554749 after
```
Fixes #3557.
>  vulc: fix mangled DOM due to a bug in the printer

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/microbenchmark/renders_spec.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-line-chart.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
This is a roll forward of 46b6e615a (#3552). The commit partially rolls back
27d0023e7 (#3524) which introduces `commitChanges` which was supposed to be
invoked after setting data, visible series, or metadata.
This change addresses the regression caused by 27d0023e7 which forgot to
call the new API in all places where we use the vz-line-chart2.
> Implement commitChanges on vz-line-chart2

- tensorboard/plugin_util.py
Calls to tensorboard.dev's /data/plugin/scalars/tags endpoint can be surprisingly slow if there are many tags. 
The following call spends ~3.5 seconds in the code that converts tag description markdown into safe html, even though the description tags are empty:
http://tensorboard.dev/experiment/UlN9loBoTwGczi5FlWbYEQ/data/plugin/scalars/tags
It is the call to `bleach.clean()` that takes up almost all of this time because it is always reinstantiating `bleach.Cleaner`.
Similar to recent changes that cache `Markdown` instances per thread, we now cache `bleach.Cleaner` instances per thread.
> Cache bleach.Cleaner for faster conversion of markdown to safe html

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
- tensorboard/webapp/core/effects/core_effects_test.ts
- tensorboard/webapp/core/views/hash_storage_test.ts
- tensorboard/webapp/deeplink/deeplink_test.ts
- tensorboard/webapp/deeplink/hash_test.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
- tensorboard/webapp/header/header_test.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
- tensorboard/webapp/reloader/reloader_component_test.ts
- tensorboard/webapp/settings/dialog_component_test.ts
- tensorboard/webapp/settings/polymer_interop_test.ts
- tensorboard/webapp/settings/settings_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
In Angular 9, `TestBed.get` is deprecated [1] in favor of inject.
This change simply changes to use `inject`.
[1]: https://angular.io/api/core/testing/TestBed
Fixes #3233.
> ng: remove deprecated `get` and use `inject`

- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
After Angular 9 upgrade, it has been throwing deprecation warning below.
```
DEPRECATED: DI is instantiating a token
"QueryParamsFeatureFlagDataSource" that inherits its @Injectable
decorator but does not provide one itself.  This will become an error in
v10. Please add @Injectable() to the "QueryParamsFeatureFlagDataSource"
class.
```
This change specifies `QueryParamsFeatureFlagDataSource` as an
Injectable.
> Specify injectable as injectable.

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Our data location in the runs selector use tf-wbr-string which is
roughly written as `<template>[[prop]]<wbr></template>`. With the pretty
print, this was rewritten as
```
<template>
[[prop]]
<wbr>
</template>
```
which has whitespace and make the browser render the whitespace.
This change fixes the issue by turning off the pretty print.
Test plan: Checked the output of `bazel build tensorboard/components:polymer_lib_binary.html && cat bazel-bin/tensorboard/components/polymer_lib_binary.html | grep -A 5 id=\"tf-wbr-string\"`. Also checked the application and looked at the UI elements more carefully.
> vulc: fix pretty print messing up whitespace

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Continue developing the backend of DebuggerV2.
* Add HTTP route `/graphs/graph`. This is at the same level as `/graphs/op`. But instead of serving information about individual ops, the new route serves information about the graph (its ID, name, relation to other graphs, etc.)
* Use `DebuggedGraph.to_json()` to implement the serving of graph info.
> [DebuggerV2] Add backend route /graphs/graph_info

- tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Summary:
If a Pip package name has hyphens, you can install it either with the
hyphenated name or with underscores (as it would be imported in Python),
so this code still worked, but we might as well suggest the canonical
name. Fixes #3615.
Test Plan:
Running `pip install -U tensorboard-plugin-profile` in a new virtualenv
still successfully installs the plugin.
wchargin-branch: profile-redirect-hyphenated-name
> profile: suggest canonical Pip package name

- docs/tensorboard_projector_plugin.ipynb
Links in projector plugin notebook were copied from image summaries notebook without changing so they are incorrect.
Fixes links to link to the project plugin notebook
Click on the links to view the notebook and verify they link to the projector plugin notebook
N/A
> Fix projector plugin links in docs

- tensorboard/plugins/graph/keras_util_test.py
This is an update for test case. The name of the model will be soon changed when Keras team refactor the class structure between layer, network and model. The functional model will have new class name, which will cause this test to fail.
N/A
This PR is test only.
N/A.
> Update keras_util_test with explicit model name

- tensorboard/uploader/BUILD
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_test.py
* Guard against malformed tensor data points in the uploader: fail during
upload time instead of serving time.
* In `_TensorBatchedRequestSender`, try to parse a `TensorProto` before sending it
to tensorboard.dev server.
* Add unit tests for the catching of malformed tensors.
* Some existing unit tests are modified. They previously used malformed `TensorProto` values.
* ![image](https://user-images.githubusercontent.com/16824702/81740043-51eaad80-946a-11ea-9d35-c8e4d7f19836.png)
* Unit tests added, as stated above.
* Verified error catching using a real logdir with malformed histogram tensors.
* Performance benchmarks:
* …
> uploader: validate tensors before uploading them

- tensorboard/compat/tensorflow_stub/io/gfile.py
> Tolerate boto3 1.13.1 range error code

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_test.py
There are a number of new parameters that impact the throughput of uploading data that we want the TensorBoard.dev frontend to return to the uploader in the handshake. Each of scalar, tensor, and blob now have a max\_[scalars|tensor|blob]\_request\_size and min\_[scalars|tensor|blob]\_request\_interval parameters.
Update the UploadLimits proto to include the new fields. Allow an instance of UploadLimits to be passed to TensorBoardUploader and use this throughout the code instead of the constants that have been used.
None of the clients for TensorBoardUploader are yet updated to pass UploadLimits (there is one in this git repo and there is one internal to Google) so temporarily have TensorBoardUploader construct its own …
> Expand UploadLimits proto and use it in TensorBoardUploader.

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
* Reduce unnecessary selector invocations by leveraging memoization (suggested by @stephanlee in #3611) 
* In `debugger_selectors.ts`, use intermediate selectors whenever applicable. 
* Each newly-added intermediate selection is for a child of `DebuggerState`
* Exceptions are selectors that use data from multiple children of `DebuggerState`.
> [DebuggerV2] Refactor selectors to use intermediate selectors

- tensorboard/uploader/proto/server_info.proto
- tensorboard/uploader/server_info.py
- tensorboard/uploader/server_info_test.py
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_subcommand.py
Continue work to get upload-related parameters from the frontend handshake.
The logic in uploader_subcommand reads UploadLimits from the handshake
and passes it to the TensorBoardUploader.
If any individual field in UploadLimits is missing, use a reasonable
default.
With this and some Google-internal code cleanup we can now delete the
deprecated fields in TensorBoardUploader.
Wrote tests.
Brought up a local frontend and made sure values from it are honored by the uploader.
Ran uploader against prod frontend and ensured it falls back to defaults.
> Uploader uses entire UploadLimits from handshake

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
* Continue developing DebuggerV2, specifically its graph component
* Add three actions: `graphOpFocused`, `graphOpInfoRequested` and `graphOpInfoLoaded`
* Add reducers for them.
* Unit tests are *not* added in the existing debugger_reducers_test.ts, because the file is getting too large in size. Instead, the new unit tests are in a new file in the same folder: debugger_graphs_reducers_test.
> [DebuggerV2] Add basic reducers for graph ops

- docs/r1/graphs.md
Fixes broken link to estimator tutorial from docs r1.  This is a docs-only change to markdown.
> Update broken link to r1 estimators tutorial in graph.md

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/core/core_plugin.py
This logic is used both by the WSGI app side (passed to TBContext as `sampling_hints`) and by the event ingestion / data provider side (used for `tensor_size_guidance`), which are going to be split apart in coming changes.
Rather than create a utility that both places have to reference, it seems straightforward enough just to do the parsing within the flag definition itself.  This will require a corresponding update to any code that set this flag after parsing (i.e. in `tensorboard.program.TensorBoard.configure()`) of which there is one instance internally.
> Migrate _parse_samples_per_plugin() into flag definition itself

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
- tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
This is a CSS/layout optimization for areas that renders a lot of DOM
Nodes including the scrollable area.
- will-change: transform <- hints browser to put the DOM in different
GPu layer
- contain <- hints browser that certain operations can be done by
reasoning children only. For instance, when `size` is present, browser
can calculate size/bounds by only reasoning with the child nodes.
For more information, refer to the [doc][contain].
[contain]: https://developer.mozilla.org/en-US/docs/Web/CSS/contain.
> perf: apply layout/layer bound where possible

- tensorboard/uploader/proto/export_service.proto
* In the experimental `ExperimentFromDev` class, support getting metadata including
experiment name and description.
* In the `ExperimentalFromDev.get_scalars()`, support progress indicaor.
* Add non-streaming rpc method `GetExperiment()` to `ExporterService`.
* Add `Experiment` as a one-of response data type to `StreamExperimentDataResponse`
* Con: In the current takeout paradigm, this leads to duplicate information.
* Con: Wasteful when only the `Experiment` (metadata) is needed and all the scalars, tensor and blob sequences are not needed.
> uploader: add rpc method GetExperiment to ExporterService

- tensorboard/data/experimental/BUILD
- tensorboard/data/experimental/base_experiment.py
- tensorboard/data/experimental/experiment_from_dev.py
- tensorboard/data/experimental/experiment_from_dev_test.py
- tensorboard/data/experimental/test_binary.py
* Improve the usability of the (experimental) DataFrame API
* Change the default value of the kwarg `pivot` to `False`.  Rationale: 
* Many experiments don't have identical sets of steps across all tags. Raising an error at the end is not nice.
* Raising a warning for missing values is potentially okay, but introduces users not seeing them and/or spamming stderr too much and hence users ignoring them. We don't want users to be misled.
* As discussed else where, we will provide good examples and documentation to explain how to get the pivoted DataFrame that many users want (i.e., it's just setting `pivot=True` for experiments that meet the requirement.)
* Detailed steps to verify changes work correctly (as executed by …
> DataFrame API: Let pivot default to False

- tensorboard/uploader/proto/export_service.proto
Reverts tensorflow/tensorboard#3614 to resolve internal proto service
method name duplication. Will roll forward with fix later.
> Revert "uploader: add rpc method GetExperiment to ExporterService"

- .github/workflows/ci.yml
- tensorboard/plugins/mesh/Mesh_Plugin_Tensorboard.ipynb
`nbfmt.py` previously tolerated several errors that should have been failures.  That is fixed in https://github.com/tensorflow/docs/commit/f10110518e0fa60bc855e77354ae3eea156532c7.
Here we use the new version of `nbfmt.py`, and fix the remaining missing license issue to allow CI to pass.
> CI: Apply new Jupyter Notebook formatting checks (and fix the resulting failure)

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Small changes to make it easier to use `TensorBoardWSGIApp` directly:
- Clarify that `plugins` can accept several types, not just plugin loader instances (pursuant to the follow-up comments of https://github.com/tensorflow/tensorboard/pull/2884/files#r342324613)
- Change `assets_zip_provider` so that it's actually optional to omit, in which case we use a placeholder dummy zipfile that contains only an index.html
> core: make TensorBoardWSGIApp args a bit easier to use

- tensorboard/components/tf_dashboard_common/dashboard-style.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
When window height is small (especially on smaller laptop), run
selectors completely collapse and do not show any item for the run.
This resulted in suboptimal experience and we would like to solve it by
giving a minimum height to the runs selector and allowing option to be
scrollable.
For the review, I strongly recommend enabling hide whitespace:
> Give min-height to run selectors

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/debug_tensor_value/debug_tensor_value_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
* Continue developing the graph-related frontend of DebuggerV2
* Add a click event listener to each tensor name in GraphExecutionComponent
* Change the tensor name element from a `<div>` to a `<button>` to reflect the
fact that it is clickable.
* The listener dispatches the `graphOpFocused()` action with the corresponding
`graph_id` and `op_name`, so the the `GraphComponent` can bring up the
local graph structure view of the op.
* Button outline CSS in GraphOpComponent to avoid extraneous outlines when
focused.
* ![image](https://user-images.githubusercontent.com/16824702/82565840-14141600-9b49-11ea-8f38-be93e7a2a580.png) …
> [DebuggerV2] Clicking tensor in graph execution component brings up graph view

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Two commits (ebaf5b5 and 3777aec) introduced a bug where rel="import"
in the middle of the document causes the printer to print "<#root>".
> Reverts Vulcanization printer changes

- tensorboard/pip_package/build_pip_package.sh
Summary:
The `//tensorboard/pip_package` target currently doesn’t build on
machines where `virtualenv(1)` defaults to using Python 2, because the
`bdist_wheel` invocation can’t parse the syntax:
```
File "/tmp/tensorboard-pip.QY3U1MVs3Y/tensorboard/data/experimental/base_experiment.py", line 24
class BaseExperiment(metaclass=abc.ABCMeta):
^
SyntaxError: invalid syntax
```
Test Plan:
Running `bazel build //tensorboard/pip_package` previously failed on my
machine, even when in a Python 3 virtualenv, and now works.
wchargin-branch: build-pip-package-with-py3
> build: fix Pip package creation to use Python 3

- tensorboard/BUILD
- tensorboard/__init__.py
- tensorboard/data/BUILD
- tensorboard/data/experimental/BUILD
- tensorboard/data/experimental/__init__.py
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/setup.py
* Put the experimental `ExperimentFromDev` API (accessing tensorboard.dev
scalars as `pandas.DataFrame`s) under a public import path:
`tensorboard.data.experimental.ExperimentFromDev`.
* Add the necessary `__init__.py` and the associated BUILD targets.
* In build_pip_package.sh, add the line `pip install -r requirements.txt`,
because we know have lines in the files imported from the
`__init__.py` files that import third-party dependencies such as grpc and
numpy.
> DataFrame API: Add ExperimentFromDev to namespace tb.data.experimental.*

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
* Continue developing DebuggerV2 plugin.
* Specifically, connect the graph ops with the StackTraceComponent and
StackTraceContainer in order to display the original stack traces of graph ops.
* Add `codeLocationFocusType` enum to the ngrx state
* This state is updated by actions `executionDigestFocused` and `graphOpFocused`
* In `StackTraceComponent`, add additional inputs and html for displaying
* Whether the stack trace of an eager execution or a graph op's original creation
is being displayed
* The type of the op
* In the case of graph op, the name of the op
* CSS adjustments in `StackTraceComponent` to accommodate the newly added
elements
* For eager execution: …
> [DebuggerV2] Generalize StackTrace component to accommodate graph ops

- README.md
When I first read, it sounded as if matmult was a summary operator.  adding 'just' and 'and', I feel, makes all the difference.
I had to read a couple of times.  Also difficult for ESL readers though perhaps grammatically correct.
Clarify that matmult is NOT a summary op.
> docs: clarify that `matmul`, etc. are not summary ops

- RELEASE.md
- 2.2.1 relnotes are rolled into this PR as well
as it seemed to not have been done previously
> 2.2.2 Post-release: Add 2.2.2 relnotes to RELEASE.md

- tensorboard/plugins/projector/projector_plugin.py
Update projector config to better handle multiple runs. If multiple runs are present, only one set of config/metadata needs to be present in the root directory, which will be used for any runs without config explicitly set.
> Projector config at root becomes default config for any present runs

- tensorboard/plugins/projector/projector_plugin.py
.OPTIMIZER_SLOT values in TF2 checkpoints have the same shape as embeddings, but are not embeddings.
> do not misconstrue Optimizer slot values as embeddings

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
Summary:
Some tests imported `@ngrx/store/testing` without declaring a build
dependency, which broke the internal sync
Test Plan:
A test sync fails before this patch (<http://cl/314143306>) and passes
with it (<http://cl/314146699>).
wchargin-branch: debugger-fix-build-20200601
> debugger: add missing `:expect_ngrx_store_testing` deps

- .github/workflows/ci.yml
Summary:
This appears to be needed for the `load-on-top` to actually have any
effect: we currently suppress that lint, but even after enabling it lint
still passes with Buildifier 0.29.0 and properly fails only with a later
version.
wchargin-branch: ci-buildifier-3.0.0
> ci: update `buildifier` to 3.0.0

- tensorboard/plugins/projector/projector_plugin.py
Support loading tensor stored in binary format to reduce tensor saving/loading time and file size. This is already supported in the [standalone embedding projector](https://github.com/tensorflow/embedding-projector-standalone), but not in the opensource tensorboard projector.
Added a function `_read_tensor_binary_file` to load tensor in binary format. The speedup is about 2-3  orders of magnitude for tensors of moderate size.
```python
In [1]: import numpy as np
In [2]: data = np.random.random((10000, 128)).astype(np.float32)
In [3]: data.tofile("vec.bin")
In [4]: np.savetxt("vec.txt", data, delimiter="\t")
In [5]: def read_tensor_tsv_file(fpath):
...:     with open(fpath) as f:
...:         tensor = []
...: …
```
> [projector] support tensor stored in binary format

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container_test.ts
* Improve the usability of DebuggerV2, specifically it's timeline component.
* Previously, the mat-slider (see screenshot below) triggers actions on its
`(change)` output, which means users won't see the eager-execution
timeline update when dragging the slider thumb. They'll see it change
only after they release the drag.
* This PR changes the mat-slider output we listen to from `(change)` to
`(input)`. This lets the eager-execution timeline update smoothly as
the user drags the thumb of the mat-slider.
* Previously, the loading state of all execution digests are lumped into a single
boolean in the ngrx store, namely `state.executions.executionDigestsLoaded.state`.
This is not adequate, especially given that the …
> [DebuggerV2] Improve the scrolling experience of the eager timeline

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
We now have different shell around dashboards. Especially the Angular
can now reason better on when the data should be fetched. Currently, all
dashboards `reload` as soon as mounted and we would like to be able to
control that.
Note that this change does not fix/address hparams since the logic is
deeply embedded into query-pane and makes request using observers which
fire on `ready` (props get set on ready and gets fired then).
> Introduce reload-on-ready prop to dashboard

- tensorboard/components/tf_runs_selector/BUILD
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_wbr_string/BUILD
- tensorboard/components/tf_wbr_string/test/BUILD
- tensorboard/components/tf_wbr_string/test/tests.html
- tensorboard/components/tf_wbr_string/test/tfWbrStringTests.ts
- tensorboard/components/tf_wbr_string/tf-wbr-string.html
- tensorboard/plugins/graph/tf_graph_info/BUILD
- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
- tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
tf-node-info assigns some user-generated value to an element using innerHTML.  It does this because it augments the user-generated value with some \<wbr\> tags.  Need to find a way to do this that is less prone to attack.
There is a nice tf-wbr-string component that already does what we want. Refactor to a common location and allow callers to specify the delimiter for \<wbr\> insertion.
Run tensorboard and manually inspect DOM in the run selector and in the graph node info title to ensure \<wbr\>s are being properly inserted in text.
For the graph node, more specifically, have to drill down several layers in the debug model to generate a node title …
> Use tf-wbr-string in tf-node-info

- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/distribution/distributions_plugin.py
- tensorboard/plugins/distribution/metadata.py
We need to reliably access the distributions plugin name from Google-internal code.
Like other plugins, move distributions plugin name into its own `metadata.py` file.
Loaded TensorBoard on logdir with histograms and ensured distributions plugin still works.
> Refactor distributions plugin name into metadata file

- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Cause: dashboards, on Polymer's `ready` invoke `reload`. That means,
when the Angular's plugin_component mount the Polymer dashboard onto the
DOM, it will fetch the `data` right away. In addition to that, on
plugin_container mount, we fetch the `plugins_listing` and upon its
completion, invoke `reload` again.
To be clear, the fact that `reload` was getting triggered based on last
fetch time of `plugins_listing` was not ideal; it does imitate the way
Polymer based tf-tensorboard does (Promise.then) and it does tie with
the reloader but using the last loaded time as a proxy to user's action
(e.g., reload button click) is not correct. Ideally, we should only make
the data requests from `effects` but our Polymer code is ill-suited for
that.
Addressed the issue by ignoring first two triggers …
> ng: prevent double dashboard reload on mount 

- tensorboard/default.py
- tensorboard/main.py
Summary:
The `tensorboard.program.TensorBoard` API now includes dynamic plugins
by default; previously, it only included static plugins. Fixes #3683.
We effect this change by modifying the internal `default.get_plugins`
method to return all the plugins to prevent this kind of confusion in
the future.
Test Plan:
Launch TensorBoard from a small Python script:
```python
import tensorboard as tb
program = tb.program.TensorBoard()
program.configure(logdir="/tmp/logs", bind_all=True)
program.main()
```
…and note that the projector plugin now shows up in the list of plugins,
whereas previously it was not loaded (neither active nor inactive). Note
that normal `tensorboard(1)` also still shows the correct plugins.
wchargin-branch: program-include-dynamic-plugins
> program: include dynamic plugins by default

- tensorboard/notebook.py
Users will frequently want to run TensorBoard in environments where they are not allowed to open up or expose additional ports. For those cases [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) allows forwarding web traffic to other services running on the system without opening new ports. (The Google Colab integration also works around this same issue of not being able to directly expose the port that TensorBoard runs on.)
This PR allows users to *optionally* pass the TensorBoard traffic through jupyter-server-proxy by setting the `TENSORBOARD_PROXY_URL` environment variable. When this variable is not set TensorBoard will behave as normal.
This adds support for a new optional environment variable `TENSORBOARD_PROXY_URL` which if set will be used as the URL's path …
> Support jupyter-server-proxy (and other proxies)

- tensorboard/components/tf_runs_selector/BUILD
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_wbr_string/BUILD
- tensorboard/components/tf_wbr_string/test/BUILD
- tensorboard/components/tf_wbr_string/test/tests.html
- tensorboard/components/tf_wbr_string/test/tfWbrStringTests.ts
- tensorboard/components/tf_wbr_string/tf-wbr-string.html
- tensorboard/plugins/graph/tf_graph_info/BUILD
- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
- tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
This is a rollforward of #3633 with fixes after a rollback in #3699.
Original PR description:
tf-node-info assigns some user-generated value to an element using innerHTML.  It does this because it augments the user-generated value with some \<wbr\> tags.  Need to find a way to do this that is less prone to attack.
There is a nice tf-wbr-string component that already does what we want. Refactor to a common location and allow callers to specify the delimiter for \<wbr\> insertion.
Run tensorboard and manually inspect DOM in the run selector and in the graph node info title to ensure \<wbr\>s are being properly inserted in text.
For the graph node, …
> Rollforward "Use tf-wbr-string in tf-node-info"

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
* Fix #3661: graph ops are indexed by TensorFlow op names, which are theoretically
possible to collide with JavaScript Object's built-in properties such as `toString`
and `hasOwnProperty`. This PR uses `Map`s to resolve this danger.
* In debugger_types.ts, change the following two states in the ngrx state from
`Object` to `Map`:
* `graphs.ops`
* `graphs.loadingOps`
* All related reducer, selector, and effect code is updated.
* All related unit tests are updated.
* Made sure tests pass.
* Manual verification against a real tfdbg2 logdir.
> [DebuggerV2] Use Map for graph ops

- tensorboard/backend/event_processing/data_provider_test.py
- tensorboard/data/provider.py
Summary:
The data provider `read_*` methods have always taken an integer-valued
`downsample` parameter, but the interpretation of that parameter has
hitherto been left to the imagination. We now specify some of the
properties that we expect implementations to satisfy. These properties
(a) are historically supported by TensorBoard’s native event file
reading, (b) are motivated by user experience (i.e., users complain when
these aren’t satisfied), and (c) are relied upon by code that expects
the native TensorBoard logic, and so should be specified in the general
case, too.
Fixes #3436.
wchargin-branch: data-spec-downsampling
> data: specify more precise downsampling semantics

- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Reverts tensorflow/tensorboard#3589
This change causes regression that makes plugin, when newly mounted, do not
fetch any data.
> Revert "ng: prevent double dashboard reload on mount "

- tensorboard/webapp/plugins/plugins_component.ng.html
- tensorboard/webapp/plugins/plugins_component.ts
This assigns a CSS class so we can hide it in screenshot tests, since it's not deterministic.
Confirmed to work in internal testing.
> ng: make error page last reload time hideable

- tensorboard/backend/application.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/security_validator.py
- tensorboard/backend/security_validator_test.py
- tensorboard/encode_png_benchmark.py
- tensorboard/plugins/audio/metadata.py
- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/beholder/video_writing.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/debugger_server_lib.py
- tensorboard/plugins/debugger/tensor_store.py
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/histogram/metadata.py
- tensorboard/plugins/image/metadata.py
- tensorboard/plugins/pr_curve/metadata.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/scalar/metadata.py
- tensorboard/plugins/text/metadata.py
- tensorboard/program.py
- tensorboard/uploader/exporter.py
* `warn()` is deprecated. `warning()` should be used instead for code hygiene.
* This PR replaces usage of `logger.warn()` with `logger.warning()` through
*.py files in the tensorboard/ directory.
* Also updates mock patching accordingly.
> Unify instances of logger warn() to warning()

- tensorboard/uploader/BUILD
- tensorboard/uploader/dry_run_stubs.py
- tensorboard/uploader/dry_run_stubs_test.py
- tensorboard/uploader/flags_parser.py
- tensorboard/uploader/upload_tracker.py
- tensorboard/uploader/upload_tracker_test.py
- tensorboard/uploader/uploader.py
- tensorboard/uploader/uploader_subcommand.py
- tensorboard/uploader/uploader_test.py
* Improve the usability of the tensorboard.dev uploader
* Add `--dry_run` flag, which when enabled, causes the uploader to only read data
from the logdir and display the statistics (if `--verbose` is the default `1`) and upload
*no* data to the server.
* This is implemented through a dry-run stub: `DryRunTensorBoardWriterStub`.
* Add `--one_shot` flag, which when enabled, causes the uploader to exit immediately
after all existing data in the logdir are uploaded.
* This mode prints a warning message if the logdir doesn't contain any uploadable
data.
* Screenshots
* Dry run, one shot, non-empty logdir: ![image](https://user-images.githubusercontent.com/16824702/83833211-6dd41e80-a6b9-11ea-835e-7dce20abb66b.png)
* Dry …
> uploader: add options --dry_run and --one_shot

- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
* Remove flakiness in `testRunInBackgroundRepeatedlyThreeTimes` for the method
`debug_data_multiplexer.run_repeatedly_in_background()`
* The flakiness stems from the following fact: after the the `interrupt_event.set()` call
the test checks the value of `state["counter"]` immediately. It doesn't wait for the
background thread to stop (due to the deliberately-raised `StopIteration`), hence the
counter may not have had a chance to increment to 3 before the assertion happens. 
Hence the failure (2 != 3)
* This change lets `run_repeatedly_in_background()` return the background thread,
so that the test can use its `join()` method to ensure that the assertion is made after
the termination of the thread.
* Detailed steps to …
> [DebuggerV2] Remove flakiness in a Python unit test

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_helpers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
* Remove transitive dependency on modules meant to be used only by the ngrx 
store of debugger-v2.
* #3682 introduced a module meant to be used to be used only the ngrx store:
debugger_store_utils, as marked by the BUILD visibility. Specifically, a 
helper function (`getFocusedStackFramesHelper`) was added to the file
debugger_store_utils.ts.  However, the file (debugger_store_utils.ts) contains
some pre-existing functions that are not meant to be store-internal; they are 
already used by non-store parts of debugger-2. 
* This doesn't cause any build/test error in bazel because it seems to allow
transitive dependencies on internal BUILD targets. But this causes errors in
internal test infrastructure, which disallow …
> [DebuggerV2] Remove transitive dependency on store-internal helper

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
* Fix a few CSS issues in DebuggerV2's overall layout
* The issues fixed include:
1. The top-section and bottom-section of the overall layout doesn't have
`box-sizing: border-box;` and hence overflows by the amount of border
and padding, causing scroll bars to appear. This is fixed by applying the 
said CSS property.
2. The top section has three children. They some times wrap undesirably 
(e.g., when zoom ratio is <100%) This is fixed by applying
`white-space: nowrap`.
3. The stack trace component at the lower-right corner doesn't have `height`
set and hence grows downward beyond the bound. This is fixed by
`height: 100%`
* Before: ![image](https://user-images.githubusercontent.com/16824702/84164271-5346d000-aa40-11ea-9 …
> [DebuggerV2] Fix a few CSS issues in overall layout

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
* Roll forward #3582 with change, in order to fix #3557.
* The solution is primarily due to @stephanwlee. When such midway imports are found,
a `RuntimeException` is thrown with an error message describing the cause and the
offending element.
> Roll forward vulcanization printer change with check for outside-head link importing

- tensorboard/plugins/projector/projector_plugin.py
Summary:
Previously, the projector plugin would look for checkpoints in the root
logdir only if there were no other logs. This led to a confusing
discontinuity: if you add logs to a subdirectory of a logdir with only
projector data, suddenly your projector data would disappear in the UI.
This patch changes the projector plugin to _always_ look in the root log
directory for checkpoints. Fixes #3686.
Test Plan:
Three cases to test:
- checkpoints in root logdir, no other data
- checkpoints and summary data in root logdir
- checkpoints in root logdir, summary data in non-root run
Verify that each of these cases lets the projector plugin render and
that the data shows up only once (i.e., it’s not duplicated).
wchargin-branch: projector-always-check-root
> projector: always check root logdir for embeddings

- tensorboard/components/tf_paginated_view/tf-dom-repeat.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
Cause: due to the limitation of the tf-dom-repeat, we were rendering
custom scalars card inside a container which got in the way of `width:
100%` (since the said container is written to wrap the content, not the
container width).
Fix: tf-dom-repeat used to assign a slot attribute to the DOM we stamp.
However, if the stamped DOM is "dom-if" or "dom-repeat", then DOM will
be dynamically appended to the container _without_ the `slot="items"`.
Without it, the DOM stamped by dom-if does not show up in the items slot
in the container. We fixed it by using MutationObserver and dynamically
appending the slot property to any DOM that is created in the
tf-dom-repeat container.
Test plan:
- tested with the custom scalars demo. 
- made sure other plugins (i.e., scalars and images) did not regress.
> Fix custom scalars full width mode

- tensorboard/webapp/core/store/core_types.ts
To minimize the change between Polymer based TensorBoard and the Angular
one, we want to make the defaults congruent.
Currently, the Polymer's default is defined to be 12 and is defined in
paginatedViewStore.ts
> ng: change default page size

- tensorboard/components/tf_runs_selector/tf-runs-selector.html
Summary:
The data location (`--logdir` path shown beneath the runs selector) is
meant to be clipped when it’s very long, with an option to show the
whole thing in a modal, but this was broken in two ways. First, the data
location was simply missing due to a JS type error. Second, the link to
open the modal was accidentally nested inside a `tf-wbr-string` element
because that tag is not self-closing. This patch fixes both errors.
Test Plan:
Run with `--logdir /tmp/"$(for i in {1..100}; do printf abc/; done)"`
and navigate to the scalars dashboard. Note that: before this patch, the
data location is not shown at all; with just the JavaScript change, the
data location is shown, but the modal-opening ellipsis is not; with this
patch, the data location is shown, and the all-important link is, …
> tf-runs-selector: fix data location clipping behavior

- tensorboard/webapp/core/views/hash_storage_component.ts
- tensorboard/webapp/core/views/hash_storage_test.ts
We are, when modifying the history to set the plugin id in the URL,
using replaceState as opposed to pushState on the initial plugin id set.
When done incorrectly, we can pushState and leave awkward intermediate
null plugin id in the URL.
Currently, our logic to use the `firstChange` of Angular's seem flaky
and often result in incorrect state. To remedy, we will replaceState
only when moving from `null` to non-null.
Test:
- tested by launching with `#images` and checked the history stack
- tested by launching with no hash and checked the history stack (after it changing to `#scalars`)
> ng: use replaceState for null pluginId to non-null

- tensorboard/components/tf_tensorboard/style.html
- third_party/polymer.bzl
This addresses b/156301620 by removing our dependency on the [global paper-styles CSS rules][1], which include a bunch of default behavior (like small-caps for all <a> tags) that we don't actually want, and as a result we either have to override the defaults or they bleed into pages in unwanted ways.
This primarily affects ng-tensorboard, since ng-tensorboard is not using Shadow DOM so its components are not immune to global CSS styles.  For Polymer tensorboard, the only rules that had any effect were those defined on <body>, which we've ported into tf_tensorboard/style.html (adapting them slightly; e.g. we omit the font-family rule since there is already a font-family rule in that CSS stylesheet that can take precedence).
The main impacts to the visual appearance are:
- subtle font …
> ng: remove paper-styles global style rules

- tensorboard/webapp/plugins/plugins_component.ts
Angular, by default, encapsulates styling using some component specific
hash attached to the DOM when stamping them. Unfortunately, the iframe
is not created by Angular, thus, need to be styled a bit differently.
This change allows iframe to be styled without the hash stamped out.
cc @caisq
> ng: fix iframe plugin rendering

- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
VzLineChart2 clients can already set the series data and manually
trigger `resetDomain`. However, it is hard to know when to redraw.
TensorBoard may update data every 30s, so redrawing upon every
data change may disrupt users who are interested in examining a
specific region they panned/zoomed into.
To allow better UX offerings, this exposes internal chart state, so
that VzLineChart2 clients may redraw only when the chart scales
have no transformation applied (e.g. not panned/zoomed).
See also cl/316522213
> Expose line chart "scaled to fit" state

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
* Improve the layout of debugger-v2
* The two rightmost sections in the layout of DebuggerV2, namely
GraphExecutionsComponent at the top-right corner and the
StackTraceComponent at the bottom-right, previously did not have a
min-width, and instead had only a percentage-based width relative
to their parents. This cause these regions to shrink to a very
small with when the size of the browser window is limited (e.g.,
<1400px or so), cutting off important information such as the
warning-color nan/infinity information.
* This CL addresses this issue by adding min-width to these two
components. The two sections grow and shrink in size in sync (see
screenshot).
* Also in this CL:
- Improve no-data message in the …
>  [DebuggerV2] Improve CSS layout of rightmost sections

- tensorboard/components/vz_line_chart2/log-scale.ts
The recently added `isDataFitToDomain` relies on computing the transformed
viewport domain and extent of values. Calling `getTransformationExtent()`
works on TensorBoard's LinearScale because it extends
`extends Plottable.Scales.Linear`, but fails for LogScale which doesn't have
the method.
This adds the missing `getTransformationExtent()` so that LogScale supports
`isDataFitToDomain`.
> Support transformation extent method for log scale charts

- tensorboard/components/experimental/plugin_util/BUILD
- tensorboard/components/experimental/plugin_util/plugin-host.html
- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
In order to make the experimental plugin API work, we needed to register
an iframe to the experimental host library. This change adds the call
necessary to make it work.
Detail: we now expose the API via the Polymer component hack to cross
the binary boundary.
> ng: integrate the experimental api

- tensorboard/webapp/BUILD
- tensorboard/webapp/angular/BUILD
- tensorboard/webapp/tbdev_upload/BUILD
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
- tensorboard/webapp/testing/mat_icon.module.ts
- third_party/js.bzl
TensorBoard.dev upload dialog contains a sample command to upload to TensorBoard.dev. We want to add a button to make it easier for the user to copy.
Add an icon button to the left of the sample text. A click copies it to the clipboard.
I have local changes (not part of the PR) that embed the TensorBoard.dev upload button and dialog into the app.  I open the dialog.  I press the copy button. I paste text from the clipboard into a text element and note that it is the sample command text.
> Add ability to copy sample command in TensorBoard.dev upload dialog

- tensorboard/plugins/debugger/health_pill_calc.py
* Fix https://github.com/tensorflow/tensorboard/issues/3775
* `np.float` and `np.floating` don't mean the same thing exactly.
* The former is a concrete dtype; the latter is a super class of dtypes
such as float32, float64, etc.
* `np.issubdtype()` used to allow the second arg to be `np.float` and it would
interpret it as `np.floating`. But that deprecated behavior has been
removed in the latest release of numpy (1.19.0).
* This PR brings the code up to date with that by removing the usage
of the deprecated behavior of `np.issubdtype()`.
* Tested:
* Tested the code against a local virtualenv of tensorflow 1.15.0 and numpy
1.19.0.
> [Debugger] Fix a failing test due to usage of deprecated numpy API

- tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/summary_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/util/tensor_util.py
This change replaces the following deprecated numpy calls:
- [`numpy.asscalar`](https://numpy.org/doc/stable/reference/generated/numpy.asscalar.html) deprecated since 1.16 --> `numpy.ndarray.item()`
- [`numpy.ndarray.tostring()`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html) deprecated since 1.19 --> `numpy.ndarray.tobytes()`
> Fix numpy deprecation warnings

- tensorboard/program.py
- Increase the port scanning range from 10 to 100 so that more users can start Tensorboard processes with default parameters in multi-tenant notebook environments.
- See https://github.com/tensorflow/tensorboard/issues/3752 for more context.
> program: increase port scan limit from 10 to 100

- tensorboard/webapp/header/BUILD
- tensorboard/webapp/header/header_component.ts
- tensorboard/webapp/header/header_module.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
This is a revert of a revert of https://github.com/tensorflow/tensorboard/pull/3773 with additional changes to fix Google-internal compilation errors with one of the tests.
See https://github.com/tensorflow/tensorboard/commit/b270a281090cd6e70ed9f92570c96f0b6ff1e0fd for the new changes.
See https://github.com/tensorflow/tensorboard/pull/3786 for the original revert.
Original PR description:
Show the "Upload" button to users who load a TensorBoard on localhost. This Upload button is an entry point to the "Upload to TensorBoard.dev" dialog with instructions on how to create a TensorBoard.dev experiment with the event data.  We restrict to localhost users so we can be more certain that the user is the owner of the TensorBoard.
* Technical description of …
> Add "Upload" button to header for local users

- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
* Motivation for features / change
Google-internal linter says some recently added members in the tbdev_upload code should be marked as readonly.
Add readonly modifier to some members in tbdev_upload code.
> Mark new tbdev_upload class members as readonly

- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
This makes the scalars plugin `/scalars` route behave consistently for both the legacy bare multiplexer and the new data provider in that it will ignore tags that exist but aren't scalar summaries.  Previously, the bare multiplexer route would instead try to parse the summary data as a scalar tensor value anyway, which would lead to uncaught numpy exceptions.
The existing tests for this were broken and were using the wrong tag name and therefore passing incorrectly; I confirmed that the fixed tests failed before fixing the bug.
(This is pre-work to a later PR that eliminates this weird `should_work` test pattern in the scalars tests entirely.)
> scalars: return not found for existent but non-scalar tags

- tensorboard/webapp/header/header_component.ts
Summary:
This updates the top-left “TensorBoard” wordmark to use the standard
tracking and positioning. This is consistent with the TensorBoard.dev
wordmark and is also consistent with the legacy Polymer interface.
Styles cribbed from `tf-tensorboard.html`.
The margin to the right, between the brand and the plugin list, is still
inconsistent, but this is fine because the TensorBoard.dev word mark is
a different width, anyway (because of the “.dev” suffix).
Test Plan:
Open both `/` and `/legacy.html` in tabs, and note that the text is
aligned when switching between them.
wchargin-branch: ng-brand-styling
> ng: make brand styling consistent

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/text/text_plugin.py
Summary:
In #3265 and #3559, we changed many plugins to use data providers by
default. But the implementation was flawed: when `context.flags` was not
provided (usually in tests), it still defaulted to off rather than on.
This means that tests weren’t testing what they were supposed to test.
Test Plan:
Adding `assert 0` to `_get_generic_data_individual_image` now causes
tests to fail.
wchargin-branch: data-on-without-flags
> Fix “data provider on by default” logic

- tensorboard/plugins/scalar/scalars_plugin_test.py
This pulls the test improvements from #3782 out into their own PR, since they have independent value even if that PR might not be the right solution.  The changes here remove the `should_work` indirection and the use of all 3 data fixtures for each test method (even when only one is used for any given test) by flattening them out into just having 3 separate tests for each case that only test the JSON response version.
To preserve and improve CSV and JSON format download behavior coverage, we add two HTTP-level tests using the werkzeug test client.
> scalars: add HTTP-level tests of download behavior

- tensorboard/BUILD
- tensorboard/components/BUILD
- tensorboard/pip_package/test_pip_package.sh
- tensorboard/webapp/BUILD
This commit changes the default route (e.g., localhost:6006/) to the
Angular based TensorBoard.
More an entire minor version, we intend to keep the legacy build around
as an escape hatch.
- This PR will be submitted only after July 6th for the tb-nightly on July 7th.
- Propose this change to make it into TensorBoard 2.3.0 release.
- We should cut TB 2.3.0 release by July 17th (should confirm the real date with TF).
WANT_LGTM=all+date
> Change default FE to Angular TB

- tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.html
When clients of `vz-histogram-timeseries` change the color by setting the
`colorscale` property on the element, the histogram lines and fill colors
update, but the circles that appear on hover/mousemove do not.
This updates the redraw logic to ensure that colors for the mouse-tracking
circles also update.
Manually tested by setting `.colorscale` on a histogram and observing that
the dots change color in both Overlay and Offset mode.
> Update dots when changing histogram color scale

- .github/workflows/ci.yml
- tensorboard/compat/tensorflow_stub/BUILD
Summary:
This exemption only had one offender, so we just fix it.
Test Plan:
The output of
```
bazel query 'labels(srcs, //tensorboard/compat/tensorflow_stub)' | sort
```
is unchanged by this patch.
wchargin-branch: ci-enforce-constant-glob
> ci: enforce `constant-glob` lint warning

- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
This fixes the custom scalars dashboard so the data download links work again.  They have been failing on the backend with the following error due to an argument mismatch from when the `experiment` support was added:
```
File ".../python3.7/site-packages/tensorboard/plugins/custom_scalar/custom_scalars_plugin.py", line 126, in download_data_route
body, mime_type = self.download_data_impl(run, tag, response_format)
TypeError: download_data_impl() missing 1 required positional argument: 'response_format'
```
To prevent regressions we port the download behavior HTTP-level tests from #3793 to the custom scalars dashboard.  Also tested manually by launching tensorboard with test data and confirming the downloads now work as expected.
> custom-scalars: fix bug in data download logic and add tests

- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Summary:
Currently, the logic for the custom scalars plugin’s `is_active` method
checks that there is data for both the `scalars` and `custom_scalars`
plugins. This doesn’t fit directly into the `data_plugin_names` approach
to determining activity, which requires a disjunction rather than a
conjunction. We could enhance that approach to support more complex
activity conditions, but in this case it seems fine to just stipulate
that the custom scalars dashboard is active whenever `custom_scalars`
data exists; the case where a custom layout exists but there is no
scalar data seems like only a transient edge case, and the failure mode
is just that an empty dashboard appears.
Test Plan:
When pointing at a directory without custom scalar layout data, the
plugin appears as inactive; when …
> custom-scalars: activate iff custom layout exists

- tensorboard/webapp/tbdev_upload/BUILD
This adds missing dependency in the BUILD file to unblock syncing (internally, we require strict deps).
> cleanup: added missing ngrx/store/testing deps

- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/webapp/deeplink/hash.ts
This fixes the broken dynamic plugin API method `getURLPluginData`, which was
broken after the Angular entry point switch. `storage.ts` has an initial call to read
from the URL hash, but this is actually a no-op, since before `setUseHash(true)`
is called, it assumes it should use the "fake hash" by default (for tests only).
In the Polymer entry point world, `tf-tensorboard.html`'s `ready` callback will
`setUseHash(true)` before calling `migrateLegacyURLScheme`, which will
read from the real URL hash and normalize it.
This adds a similar call to the Angular side, in HashDeepLinker.  See #3809.
Manually checked that the repro steps now pass:
> Fix getURLPluginData in Angular entry point

- tensorboard/webapp/deeplink/deeplink_test.ts
The recently landed #3811 broke a unit test, and was landed improperly.
This fixes the broken test by providing the correct mock.
> Fix broken deeplink test

- tensorboard/webapp/core/BUILD
- tensorboard/webapp/core/actions/BUILD
- tensorboard/webapp/core/actions/core_actions.ts
- tensorboard/webapp/core/store/BUILD
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_reducers_test.ts
- tensorboard/webapp/core/store/core_selectors.ts
- tensorboard/webapp/core/store/core_selectors_test.ts
- tensorboard/webapp/core/store/core_types.ts
- tensorboard/webapp/core/testing/index.ts
- tensorboard/webapp/core/types.ts
This change adds a concept of `runs` in Angular so we can render the runs selector.
- We would like to port Polymer dashboards into Angular
- While transitioning, there will be a mixture of Angular and Polymer component
- For consistency, while transitioning, we want to use Polymer based tf-runs-selector
rendered in the Angular
- tf-runs-selector takes current runs as an input and we should supply that in Angular
- Angular should, more and more, understand the notion of runs.
- Add a `runs` state in the store
- [in farther future] create a `runs` feature separate from the `core` feature.
> Add the run state in the core state

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/log-scale.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
When clients of VzLineChart2 update the `colorScale` externally, the x/y axis
auto-scales to fit the domain. This may be unwanted behavior if clients want
to allow users to change a chart's color frequently without losing a carefully
crafted viewport domain.
This preserves the existing domains upon changes that recreate the
entire chart (color, xAxisType, yScaleType, tooltipColumns).
> Preserve domains in line chart when changing settings

- tensorboard/webapp/app_module.ts
We started to use `Map` in the store. This change turns off the runtime check.
> ng: turn off state serialiability check

- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
First mention of "TensorBoard.dev" in "Upload" dialog description should be a link to "http://TensorBoard.dev". 
* Technical description
Add link; Use Angular theming to color the link; Remove the underline by request of UX designers.
> Linkify first mention of "TensorBoard.dev" in Upload dialog

- tensorboard/data/BUILD
- tensorboard/data/auth.py
- tensorboard/data/auth_test.py
Summary:
This patch adds two new types for integrating authentication into the
data provider API. The `AuthProvider` type defines an interface for
extracting a specific kind of credential (say, an OAuth token) from a
WSGI environment. The `AuthContext` type lets clients ask for a
credential from a specific type of `AuthProvider`.
As written, `AuthContext` is not threadsafe. Making it truly threadsafe
is tricky if we assume that the `AuthProvider`s’ `authenticate` methods
do anything that Python code can, including obtaining a reference to the
very same `AuthContext` and calling its `get` method with a different
auth provider. (This would be a Bad Idea on the part of the caller, but
deadlocking would still be unfortunate.) Since most requests are handled
by a single thread, anyway, this …
> data: add `AuthProvider` and `AuthContext`

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Summary:
This function used to have some manual argument-munging to facilitate
use as a method decorator (necessary due to the extra `self` argument).
But we removed the only such usage in #2732, so we can now just follow
the standard WSGI interface.
Test Plan:
That unit tests pass suffices.
wchargin-branch: application-simplify-handling-errors
> application: simplify `_handling_errors` plumbing

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Domain preservation logic added in https://github.com/tensorflow/tensorboard/pull/3813
introduced a regression where changing the tag filter, tooltip sort settings
would reset the domain of axes to Plottable's default [0, 1] range.
This results in charts that appear blank, because it's out of view.
> Revert logic that preserves axis domains

- tensorboard/BUILD
- tensorboard/auth.py
- tensorboard/context.py
Summary:
Some straggling transitive Google-internal dependencies still require
Python 2 source…
Test Plan:
```
$ python2 -c 'import ast; print(ast.parse(open("tensorboard/auth.py").read()))'
<_ast.Module object at 0x7f796a5c1050>
$ python2 -c 'import ast; print(ast.parse(open("tensorboard/context.py").read()))'
<_ast.Module object at 0x7f44c4c23c90>
$ bazel query 'attr(srcs_version, PY3, deps(//tensorboard:plugin_util))'
INFO: Empty results
```
wchargin-branch: auth-context-py2
> Make `auth` and `context` py2-compatible

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
* Improve the usability of DebuggerV2's GraphExecutionComponent
* The tensor names in GraphExecutionComponent are displayed with a
`button` of fixed length and automatic ellipses, which makes long tensor
names (common in large model) are to understand. This PR improves
the situation by adding a title to those `button`s
* Add a `title` attribute to the `button` element that holds the tensor name
in the GraphExecutionComponent
* Refactor the code that computes the tensor name based on op name
and output slot to a helper method in `GraphExecutionComponent`
* ![image](https://user-images.githubusercontent.com/16824702/87226548-78da3880-c362-11ea-8b4f-6a0e44d5925e.png)
> [DebuggerV2] Add title to tensor names in GraphExecutionComponent

- tensorboard/default.py
* Remove the requirement to use the `experimentalPlugin=debugger-v2` in the
URL in order to see the Debugger V2 plugin, as discussed offline.
This is a part of the plan to launch the plugin with tensorflow and tensorboard 2.3.
* Remove the `ExperimentalPlugin` wrapper for the Python class of
`DebuggerV2Plugin` in tensorboard/default.py.
* When *no* DebuggerV2 data is found:
* ![image](https://user-images.githubusercontent.com/16824702/87050795-c0c75700-c1cc-11ea-9f61-a8ee4b502c1e.png)
* When Debugger V2 data is found
* ![image](https://user-images.githubusercontent.com/16824702/87050893-df2d5280-c1cc-11ea-8d10-2474d7e262f6.png)
* Detailed steps to verify changes work correctly (as executed …
> [DebuggerV2] Remove experimental status of plugin

- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
`resin`, a security plugin to Polymer, does not like the property bound to the style.
This change implements the border using the CSS variable instead.
> resin: use CSS variable instead of prop->style binding

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
When clients of VzLineChart2 update the colorScale externally, the x/y axis
auto-scales to fit the domain. This may be unwanted behavior if clients want
to allow users to change a chart's color frequently without losing a carefully
crafted viewport domain.
This preserves the existing domains upon property changes that recreate
the chart, but do not affect the position of points.
Historical record:
- Introduced in https://github.com/tensorflow/tensorboard/pull/3813
- Reverted in https://github.com/tensorflow/tensorboard/pull/3828
due to multiple regressions
1) Changing settings that affect position of chart points (e.g. xAxis type)
would not re-fit domain to data. Users may set xAxis to "Relative", and think
that the data was missing, when it was only outside of the viewport.
This is …
> reland: preserve domains in line chart when changing settings

- tensorboard/plugins/beholder/README.md
- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
This marks the Beholder dashboard and plugin as deprecated, for the reasons outlined in https://github.com/tensorflow/tensorboard/issues/3843.
For the Python APIs (the `Beholder` and `BeholderHook`) classes we add a warning emitted at the callsite with a link to this issue, for example:
```
tensorboard/plugins/beholder/beholder_demo.py:215: UserWarning:
======================================================================
Beholder is deprecated and will be removed in a future TensorBoard
release. See https://github.com/tensorflow/tensorboard/issues/3843
======================================================================
beholder = beholder_lib.Beholder(logdir=LOG_DIRECTORY)
```
For the dashboard, we add a deprecation message in a banner with a link to this issue:
> beholder: add deprecation warning and UI banner

- tensorboard/plugins/projector/projector_plugin.py
This reverts commit 12f6234e0608d7b8703540fb3473372de88f788e.
The changes in https://github.com/tensorflow/tensorboard/pull/3653 allowed TensorBoard to
use the root directory's projector config and apply it to each subdirectory.
If the root dir's config specifies a "sprite" that does not exist in every subdirectory, it
causes the Projector frontend to hang when loading a run.
See https://github.com/tensorflow/tensorboard/issues/3840 for details on the issue.
Confirmed that this fixes the issue by running TB on a directory with:
- ./projector_config.pbtxt
```
embeddings {
tensor_name: "EMNIST_Letters:0"
metadata_path: "metadata.tsv"
sprite {
image_path: "sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
```
- alongside a subdirectory `profile_demo_new` that contains a …
> Revert "[Projector] make root directory config default for available runs"

- tensorboard/BUILD
- tensorboard/__init__.py
Summary:
All the other submodules are lazy. We originally made `errors` eager
because it seemed like a small surface (#2631), but some Google-internal
Python 2 binaries unnecessarily transitively depend on `errors` because
of this edge. Moving it to a lazy dependency makes it easier to make
`errors` use py3-only features.
Test Plan:
Existing smoke test in `test_pip_package.sh` suffices.
wchargin-branch: lib-lazy-errors
> lib: make `errors` submodule lazy

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
- tensorboard/errors.py
- tensorboard/errors_test.py
Summary:
We add a new type to distinguish authentication errors (“we can’t
confirm who you are”) from authorization errors (“we know who you are,
but you’re not allowed to perform this operation”). This was omitted
from the initial draft of the `errors` module because the natural status
code is HTTP 401, but HTTP 401 responses are required by RFC 7235, §3.1
to include a `WWW-Authenticate` challenge header. In this patch, we add
the necessary error handling machinery to support that header.
Test Plan:
Unit tests suffice for the core implementation. As a manual test,
changing a `NotFoundError` to an `UnauthorizedError` with an arbitrary
challenge in `scalars_plugin.py` properly sends a 401 with the intended
response and challenge header. Since this patch changes `:errors` to
include Python …
> errors: add `UnauthenticatedError`

- .travis.yml
Summary:
Fixed upstream: <https://github.com/tensorflow/tensorflow/issues/41388>
This reverts commit d24e136ede5bab292afed0e62b813a2740c0a648.
Test Plan:
CI suffices.
wchargin-branch: unpin-20200712-nightly
> ci: unpin 2020-07-12 nightlies

- tensorboard/webapp/BUILD
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_reducers_test.ts
- tensorboard/webapp/core/store/core_selectors.ts
- tensorboard/webapp/core/store/core_selectors_test.ts
- tensorboard/webapp/core/store/core_types.ts
- tensorboard/webapp/core/testing/index.ts
- tensorboard/webapp/runs/BUILD
- tensorboard/webapp/runs/runs_module.ts
- tensorboard/webapp/runs/views/legacy_runs_selector/BUILD
- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_component.ts
- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_container.ts
- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_module.ts
- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_test.ts
For the ease of our development in Angular, especially for porting a
fixing dashboard without any functional differences, we decided to just
wrap a Polymer based runs selector. This change introduced that.
However, do note that the selection state is in the ngrx store so you
must use the regular Angular pattern to render and access the data
related to runs.
Demo of it being applied to the app_container.ng.html.
> Added the Angular wrapper for tf-runs-selector 

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Summary:
Clients of `TensorBoardWSGIApp` may now inject middleware around the
core TensorBoard app routing but still within the experiment ID, path
prefix, request context, etc. middlewares. This is useful for handlers
for extra routes that need to access the request context.
Test Plan:
Unit tests included.
wchargin-branch: application-middleware-injection
> application: add injection point for middleware

- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
The "Upload to TensorBoard.dev" dialog provides a couple anchor links to http://TensorBoard.dev. We do not pass referer information to TensorBoard.dev since it may contain sensitive information but TensorBoard.dev would still like to know the source of the traffic.
Append a utm_source query parameter to the URL, which will be used by TensorBoard.dev's Google Analytics library to identify the traffic as coming from "tensorboard". The value of the parameter was suggested by PM.
For the moment we intentionally exclude other GA utm parameters since we're not interested in other dimensions and they pollute the URL further.
> Add utm_source to outbound TensorBoard.dev links

- tensorboard/data/dispatching_provider_test.py
Summary:
Per comment of @nfelt on #3847, we can still test for delegate equality:
<https://github.com/tensorflow/tensorboard/pull/3847#discussion_r457698571>
wchargin-branch: data-dispatch-test-bare
> data: simplify dispatching provider tests

- tensorboard/backend/event_processing/data_ingester_test.py
Python 3.8 includes breaking changes to the `os.path.expanduser` method,
which no longer reads from the `HOME` environment variable on Windows,
but rather uses `USERPROFILE`.
This broke the `data_ingester_test.py`, which tries to emulate platform specific
expansion by setting `os.environ["HOME"]`. To allow this test to run on both
Python 3.8 and before, this change makes the test simulate home directory
expansion by setting both environment variables.
Manually tested that the test fails before and passes after this change, with
`bazel run //tensorboard/backend/event_processing:data_ingester_test`.
Note that our Travis config does not use Python 3.8, so our CI does not validate
whether this change works.
See https://bugs.python.org/issue36264
> fix data_ingester_test on Python 3.8

- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/cost_graph.proto
- tensorboard/compat/proto/resource_handle.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/compat/proto/update.sh
While testing the pip candidate locally, it fails on the proto_test.
The helpful message says this expected when TF's protos update.
This change was created by checking out `git checkout v2.2.0-rc0`
in a TensorFlow local repo, and running
`./tensorboard/compat/proto/update.sh PATH_TO_TENSORFLOW_REPO`.
> Update protos for TF v2.3.0-rc2

- .travis.yml
- RELEASE.md
- tensorboard/version.py
Prepared for the 2.3.0 pip package release.
Created from HEAD @ a64659b4a17001c6ac860153139be14d760ddb4a
Cherry-picks: none (for real)
Previous attempts (https://github.com/tensorflow/tensorboard/pull/3860, https://github.com/tensorflow/tensorboard/pull/3865) were made without important changes to
compat/proto_test and other Python 3.8-sensitive tests (https://github.com/tensorflow/tensorboard/pull/3861, https://github.com/tensorflow/tensorboard/pull/3862).
After those previous attempts, we deleted the 2.3 branch and recreated it at
the newer HEAD commit, so there are no cherry-picks.
> TensorBoard 2.3.0 (on recreated 2.3 branch)

- RELEASE.md
- tensorboard/version.py
Two commits for the 2.3.0 release:
- Bump tb-nightly version to 2.4.0a0
- Cherrypick of 2.3.0 relnotes added to RELEASE.md
> Post-release 2.3.0

- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_component.ts
- tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_test.ts
Bug: currently, the initial state of the legacy runs selector is not reflected in the store.
Fix: read the state from the Polymer component and fire an action.
> run selector interop: populate initial state

- BUILD
- tensorboard/defs/defs.bzl
- tsconfig-lax.json
Our Polymer based UI is currently built by our custom tooling that
incorporates tsc and JSCompiler. The build macro had a built-in tsconfig
which was quite lax and allows improper typing. This change introduces
the relaxed tsconfig based on internal rule, the minimum bar we should
try to meet when migrating.
> migration prep: introduce relaxed tsconfig

- tensorboard/components/vz_chart_helpers/plottable-interactions.ts
This change removes Plottable license from our forked code.
Our policy is that the release unit (built binary) should contain
licenses of our libraries but not all libraries.
After this change, we had made sure that the Pottable licenses are kept
in the built binary.
Confirmed manually that the licenses are coming from `@license` in our
tf_imports module like https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/tf_imports/plottable.html#L1-L23.
Do note that we are able to provide licenses from their respective sources
for few packages (like d3) but not all dependencies would automatically
get the license in the built binary without explicit license statements in
tf_imports.
> cleanup: remove extraneous license header

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Remove references to CompilerOptions#setRemoveUnusedPrototypePropertiesInExterns for Closure Compiler compatibility
CompilerOptions#setRemoveUnusedPrototypePropertiesInExterns is becoming a noop (internal change cl/322445084).   Even before the change "remove unused prototype properties in externs" would do nothing if "remove unused prototype properties" was disabling so this isn't necessary.
> Remove setRemoveUnusedPrototypePropertiesInExterns

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/tensor-widget-style.uninlined.ts
- tensorboard/tools/BUILD
- tensorboard/tools/inline_file_content.py
Now, the TypeScript code can import the CSS for tensor widget in Polymer
3 compatible way.
> Polymer style for tensor widget in TypeScript

- tensorboard/components/tensor_widget/BUILD
- tensorboard/components/tensor_widget/tensor-widget.html
After #3898, we started to require TypeScript in order to provide the
dom-module for the TensorWidget style. This scheme is incompatible with
internal build so we reverted that part.
> Allow existing tf_web_library to provide Polymer css without TypeScript

- tensorboard/components_polymer3/polymer/BUILD
- tensorboard/components_polymer3/polymer/legacy_element_mixin.ts
- tensorboard/components_polymer3/tf_dashboard_common/BUILD
- tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/components_polymer3/tf_dashboard_common/tf-dropdown-trigger.ts
- tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-dropdown.ts
- tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components_polymer3/tf_dashboard_common/tf-option-selector.ts
- tensorboard/components_polymer3/tf_markdown_view/tf-markdown-view.ts
- tensorboard/components_polymer3/tf_paginated_view/BUILD
- tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
- tensorboard/components_polymer3/vz_chart_helpers/BUILD
- tensorboard/components_polymer3/vz_chart_helpers/vz-chart-tooltip.ts
- tensorboard/components_polymer3/vz_line_chart2/BUILD
- tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/BUILD
- tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.ts
Internally, the legacy mixin requires additional build target. In order
to work around that quirk, we decided to use a module and contain the
complexity in it.
Made sure impacted targets build by manually building them.
> polymer3: add indirection for legacy mixin

- tensorboard/components_polymer3/polymer/BUILD
- tensorboard/components_polymer3/polymer/paper_inky_focus_behavior.ts
- tensorboard/components_polymer3/tf_dashboard_common/BUILD
- tensorboard/components_polymer3/tf_dashboard_common/tf-dropdown-trigger.ts
Internally, the `paper-behaviors` package dependencies are divided up
into more modular parts. As a result, we need to make sure the part that
depends on InkyBehavior depend explicitly on something stable that we
can safely search and replace.
> sync: allow InkyBehavior to be imported internally

- tensorboard/components_polymer3/tf_storage/storage.ts
tsetse, internal conformance, complained about use of the location API.
It seems to ignore the history counterpart (although it looks equally bad :))
> sync: unblock sync by not using location API

- tensorboard/components_polymer3/polymer/BUILD
- tensorboard/components_polymer3/polymer/utils_mixin.ts
- tensorboard/components_polymer3/tf_dashboard_common/BUILD
- tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
Internally, we require separate build target for the mixin utils to
appear. This change makes the internal sync more manageable.
> sync: breakout polymer mixin lib out

- tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
- tensorboard/components_polymer3/vz_chart_helpers/vz-chart-tooltip.ts
- tensorboard/components_polymer3/vz_line_chart2/line-chart.ts
Internally, our build fails when you export a class that extends the
LegacyElementMixin. While the details are unclear, we see no evidence
that it works.
Example of error:
```
error TS4020: 'extends' clause of exported class 'DataLoader' has or is using private name 'LegacyElementMixinConstructor'.
error TS4020: 'extends' clause of exported class 'DataLoader' has or is using private name 'PropertiesChangedConstructor'.
error TS4020: 'extends' clause of exported class 'DataLoader' has or is using private name 'PropertiesMixinConstructor'.
error TS4020: 'extends' clause of exported class 'DataLoader' has or is using private name 'PropertyAccessorsConstructor'.
error TS4020: 'extends' clause of exported class 'DataLoader' has or is using private name 'PropertyEffectsConstructor'.
error …
```
> sync: remove export on class that extends LegacyElementMixin

- tensorboard/components_polymer3/polymer/register_style_dom_module.ts
Changes:
1. import dom-module (require appropriate internal change) explicitly. We now no longer have to wait for the `dom-module` to be registered.
2. Removed the asynchronous `dom-module` customElement registration which caused timing issue (we were including styles when style dom modules were not registered yet)
3. setAttribute -> Object.assign (tsetse still cannot detect it 🤫)
> polymer3: fixed broken/faulty register_style

- tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/components_polymer3/tf_line_chart_data_loader/BUILD
- tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
- tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
This is a roll forward from #3927.
Cause of the bad CI:
- two PRs that were related were merged one after another
- one removed `export` from `DataLoader` while another made changes to use the symbol.
- both CIs ran against master before each other's submission
Confirmed that the new change builds internally and, this time, CI should be enough to catch
the build breakage.
> migrate: tf-line-chart-data-loader

- tensorboard/components_polymer3/vz_line_chart2/line-chart.ts
Previously we got 'untyped function calls may not accept type
arguments.'
> sync: work around type error

- tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.ts
Our run filter was broken because the callback was keep returning a
function instead of doing anything useful.
> fix: run filter in the runs selector

- tensorboard/components_polymer3/tf_dashboard_common/dashboard-style.ts
When using `iron-flex` style dom-module, we need to have hard dependency
on the `iron-flex-layout-classes` for the dom-module definition to be
pulled in.
> fix: import iron-flex by depending on appropriate module

- tensorboard/components_polymer3/polymer/BUILD
- tensorboard/components_polymer3/polymer/register_style_dom_module.ts
Two issues:
- When adding children to template, we need to set it to `dom.template`. Added the style include in the appropriate part of the DOM
- added explicit dependency on `@polymer/polymer`
> fix register_style_dom_module for styleIncludes

- tensorboard/components_polymer3/tf_categorization_utils/tf-tag-filterer.ts
- tensorboard/components_polymer3/tf_runs_selector/tf-runs-selector.ts
Our Polymer based storage utility required Polymer class instance for
the initializer (so we can set the component prop value when hash
changes). This broke in the class syntax so we reinstated it by
explicitly passing `this`.
Co-authored-by: William Chargin <wchargin@gmail.com>
> fix: call *Initializer with reference to

- tensorboard/webapp/BUILD
- tensorboard/webapp/index.uninlined.html
- third_party/fonts.bzl
Do note that after the library upgrade, we need to explicitly tell
Polymer not to fetch Roboto from CDN.
Manually ran the application to check for no regression.
Note that the roboto genrule file change does not impact Polymer 2.
> add explicit global HTML style and add roboto dependency

- tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
Bad quoting; caught when getting the scalars dashboard working.  Correct syntax has no internal quotes: https://polymer-library.polymer-project.org/3.0/docs/devguide/observers#complex-observers
> migrate: fix data-loader-behavior.ts observer spec

- tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.ts
- tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
Details:
- we add redundant import to cause side-effect of importing Polymer module. Previously, we were importing specific symbols for type checking and the Polymer modules were tree shaken
- Removed `readOnly`. Even in Polymer 3, `readOnly` creates an implicit method (if prop name was `foo`, Polymer creates `_setFoo`) which is impossible to type. We just removed it for now.
- Removed the default value on `_contentActive` so the consumer can override it with a getter.
Co-authored-by: William Chargin <wchargin@gmail.com>
> migrate: misc fixes

- tensorboard/components_polymer3/polymer/BUILD
- tensorboard/components_polymer3/polymer/plottable-style.uninlined.ts
- tensorboard/components_polymer3/vz_line_chart2/BUILD
- tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
This fills in the missing `<style include="plottable-style"></style>` dep for `vz-line-chart2`.  It will also probably be needed for the distributions plugin chart which has a similar dep, but that isn't migrated yet so no changes here.
TESTED=scalars dashboard is marginally closer to working locally with this change
> migrate: add plottable-style DOM module for vz-line-chart2

- tensorboard/defs/vulcanize.bzl
With this change, when you `bazel run` a target, loading the HTML file in the browser will work since
extracted JavaScript would be served by the server.
Previously above flow failed since the server never served the JavaScript file.
> Allow tensorboard_html_binary to serve JS file in the devserver

- tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
tf-dom-repeat and tf-category-paginated-view were weird because the sub
class was implementing `_contentActive` protected Polymer property via
getter (because it was a computed property). It looks like it is
impossible for subclass to override a property using a getter.
For instance, in pure JavaScript,
```js
(function() {
class Foo {
foo = 'foo';
}
class Bar extends Foo {
foo =  'bar';
}
class Baz extends Foo {
get foo() {
return 'baz';
}
}
console.log(new Bar().foo); // 'bar'
console.log(new Baz().foo); // 'foo'
})();
```
This change no longer implements `_contentActive` setting via getter.
> bug: fix broken contentActive in tf-dom-repeat

- tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.ts
Followup to #3958, the import has a few two many `..`'s.
> migrate: fix irons_and_papers import in tf-multi-checkbox.ts
