tensorflow/tensorboard

tensorboard/BUILD, tensorboard/components_polymer3/BUILD, tensorboard/components_polymer3/polymer3_lib.ts, tensorboard/defs/defs.bzl, tensorboard/plugins/core/core_plugin.py, tensorboard/webapp/BUILD, tensorboard/webapp/index_polymer3.uninlined.html
This adds a parallel set of build rules to build Polymer 3 versions of `index.html` and `index.js` and bundle them into `webfiles.zip`, and then updates the WSGI app to map `/` to that `index.html` if it detects the `TB_POLYMER3` environment variable set to `1`.
The goal is to make it possible to check in the converted Polymer 3 dashboards and test them without having to maintain patches.
Tested by spot-checking the binary as executed without any special env vars, and it seemed to still behave normally.  With `TB_POLYMER3=1` it can successfully load the text and profile_redirect dashboards (though profile_redirect seems like its copy-paste command is not working correctly).  The projector plugin has also been converted but requires a bit of extra plumbing in order for this to work, which …
=> migrate: enable Polymer 3 frontend with `TB_POLYMER3=1`

tensorboard/webapp/types/api.ts
Certain variants of TensorBoard (TensorBoard.dev, for example) retrieve experiment metadata when loading the "Environment". We want to properly expose that as part of the `Environment` that we store in the ngrx store.
Add a few new properties to the `Environment` object. The data is already retrieved and stored by TensorBoard.dev - it just needs to be exposed officially in the internal API.
Mainly make sure this change doesn't break TensorBoard.
* Build and run TensorBoard from source.
* Load TensorBoard in a browser.
* Pay particular attention the TbdevUploadButton, which is the only current Angular component to use `Environment` object.  Make sure …
=> Expose experiment metadata as part of the Environment object in the ngrx store.

tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
Fixes the usual issues, i.e. the component doesn't actual attach correctly.
=> migrate: fix vz-line-chart2 to call super.ready()

tensorboard/components/tf_imports/BUILD, tensorboard/components/tf_imports/roboto.html, tensorboard/plugins/projector/polymer3/tf_projector_plugin/BUILD, tensorboard/plugins/projector/polymer3/vz_projector/BUILD, tensorboard/plugins/projector/polymer3/vz_projector/standalone_lib.html, tensorboard/webapp/BUILD, tensorboard/webapp/index.uninlined.html, tensorboard/webapp/index_polymer3.uninlined.html
Roboto internally is bundled very differently; instead of downloading
the source of the roboto file, it uses the CDN approach. As such, we
need to use a different strategy when bundling the roboto and for that
reason, we will create a stable roboto re-export.
Note that it is okay to remove roboto dependency for index.unlined.html because
roboto is bundled as part of the polymer_lib.html (tf-tensorboard/style.html)
=> sync: create indirection for roboto

tensorboard/components_polymer3/BUILD, tensorboard/components_polymer3/experimental/plugin_util/BUILD, tensorboard/components_polymer3/polymer3_lib.ts
This includes a few fixes to enable the dynamic plugin host API (without this, the `tf-experimental-plugin-host-lib` custom element definition cannot be found, so we see a failure like `TypeError: this.experimentPluginHostLib.registerPluginIframe is not a function`).
I'm not entirely sure that the way this is linked in makes sense in the long term, since the actual dependency seems to come from Angular (plugins_component in particular), but as it exists today this mechanism seemed most similar to the other Angular<->Polymer interop bits and importing it there worked, so that's what I went with.
Tested by enabling the projector plugin (see dependent PR #3963) and confirming this fixes the TypeError.
=> migrate: enable dynamic plugin host API for polymer3 app

tensorboard/plugins/projector/polymer3/vz_projector/scatterPlot.ts, tensorboard/plugins/projector/polymer3/vz_projector/scatterPlotVisualizerSprites.ts
Due to internal quirks, threejs symbols are not available during the
module load time. To work around this issue, we will use it only during
component creation time.
=> sync: remove usage of THREE during module resolution

tensorboard/plugins/projector/polymer3/vz_projector/vz-projector-projections-panel.ts
Internal build tool cannot deal with the circular module dependencies
and hard fails us. Since it is not used in a meaningful way aways, we
will remove it.
=> sync: break circular deps

tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.ts
This fixes the run selector run name regex filtering; without this you get `Uncaught TypeError: this.$$ is not a function`.
Tested via `TB_POLYMER3=1 bazel run tensorboard -- --bind_all --logdir /tmp/text_demo`
=> migrate: fix tf-multi-checkbox to use LegacyElementMixin

tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
Summary:
A component that extends `DataLoaderBehavior` gains a `reload` method.
This patch declares that on the interface so that clients can call
`reload` even if the component doesn’t override it. Extracted from #3659
as this is needed by both histograms and distributions, and this change
is safer to land.
wchargin-branch: dlb-reload
=> data-loader-behavior: define `reload` on interface

tensorboard/components_polymer3/experimental/plugin_util/core-host-impl.ts, tensorboard/components_polymer3/tf_storage/storage.ts
Closure compiler mistreats exported object and importing an object by reference. 
Instead of abusing ambiguous behavior, we now return a reference to an object via get method.
=> sync: refactor to make exported object more robust

tensorboard/pip_package/BUILD, tensorboard/plugins/projector/vz_projector/bh_tsne.ts, third_party/BUILD, third_party/bh_tsne.LICENSE
We currently have two licenses for our pip package: (1) one on LICENSE
in pip package and (2) inlined in JavaScript bundle. For ease of our
conformance to the rules, we decided to inline Karpathy's TSNE license
to (1).
=> license: extract bh_tsne license out and bundle it

tensorboard/defs/rollup_config.js
Projector depends on Weblas, a 3rd party dependency that throws runtime
errors when run in a browser's strict mode: https://github.com/waylonflinn/weblas/issues/52
To workaround the error, this changes our Rollup config to generate output
files in non-strict mode.  Manually checked that the standalone target now
works (errored with `p is not defined` before):
blaze run tensorboard/plugins/projector/polymer3/vz_projector:standalone
=> sync: relax rollup config for imperfect deps

tensorboard/components_polymer3/BUILD, tensorboard/components_polymer3/experimental/plugin_util/BUILD, tensorboard/components_polymer3/polymer3_lib.ts, tensorboard/pip_package/setup.py, tensorboard/plugins/projector/BUILD, tensorboard/plugins/projector/projector_plugin.py
This adds logic similar to #3961 but for the projector plugin (which requires a different approach since it's a dynamic plugin).  Once again we bundle both the Polymer 2 and Polymer 3 assets but under different paths, and then use the `TB_POLYMER3=1` env var condition to select which ones we serve under the canonical routes.
Tested by running locally and verifying that the projector loads normally without any special configuration, and with `TB_POLYMER3=1` it seems to load the Polymer 3 version (but it's still broken because of some three.js error, see below).  At least, the routes resolve and `projector_binary.js` includes what appears to be the polymer3 version.
I also tested building a pip package and installing it to check that the setup.py changes work.
The remaining error on the …
=> migrate: enable projector polymer3 with TB_POLYMER3=1

tensorboard/components_polymer3/polymer/irons_and_papers.ts
This component is used in a few places.  Tested against my scalars WIP branch; without including this import, the spinner doesn't actually appear since the custom component isn't found.
I don't actually see any usage of plain `paper-spinner` anywhere, but to play it safe I figure we might as well still include it.
=> migrate: include paper-spinner-lite in irons_and_papers

tensorboard/components_polymer3/polymer/BUILD, tensorboard/components_polymer3/polymer/dom.ts
Summary:
The `PolymerDom` module requires special treatment for syncing into
google3, so we route it through an indirection module.
Googlers, see <http://cl/325337988> for corresponding internal change.
Test Plan:
The image dashboard migration (PR soon to come) uses this and succeeds
at build time, link time, and runtime.
wchargin-branch: polymer3-indirect-dom
=> polymer3: add indirection for `PolymerDom`

tensorboard/plugins/scalar/BUILD
scalars_plugin.py is referencing metadata.py, but the dependency is not set up in the BUILD file.
=> Adding back in a missing dependency

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/plugins/text_v2/BUILD, tensorboard/webapp/plugins/text_v2/text_v2_module.ts, tensorboard/webapp/plugins/text_v2/views/text_dashboard/BUILD, tensorboard/webapp/plugins/text_v2/views/text_dashboard/text_dashboard_component.ts, tensorboard/webapp/plugins/text_v2/views/text_dashboard/text_dashboard_module.ts
This creates a skeleton for text_v2 plugins upon which we will build features.
Because we only render hard coded string, it is as boring as this:
=> text_v2: add skeleton to the application

tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
This fixes an issue in `DataLoaderBehavior` that was noticed with `tf-line-chart-data-loader` where it doesn't reload data when `data-to-load` changes (I haven't checked if it affects other elements that mix in `DataLoaderBehavior`).  The most obvious way to trigger this is to try to add a new time series to the chart (i.e. if you start with runs deselected at load, and then select new runs, they don't appear on the chart).  This seems to be caused by the fact that the [`Node.isConnected`](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected) property on `tf-line-chart-data-loader` is returning `undefined` when it should be `true`, which is a problem since `DataLoaderBehavior` gates data loading in response to `dataToLoad` changes using `if (this.isConnected)`.
My best guess …
=> migrate: replace Node.isConnected with manually wired property

tensorboard/components_polymer3/polymer/BUILD, tensorboard/components_polymer3/polymer/dom-repeat.ts
Summary:
The `dom-repeat` module, which provides typings for the `DomRepeat`
interface, requires special treatment for syncing into google3, so we
route it through an indirection module.
Googlers, see <http://cl/325485393> for corresponding internal change.
Test Plan:
Work-in-progress migration for the custom scalars dashboard seems to be
happy with these type definitions.
wchargin-branch: polymer3-indirect-dom-repeat
=> polymer3: add indirection for `dom-repeat`

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/oss_plugins_module.ts, tensorboard/webapp/plugins/BUILD
plugins_module is responsible for providing plugins registry and view
for rendering a plugin. Now, this module should not have enumeration of
all possible plugins in TensorBoard because whether an application wants
to embed a plugin or not is an application logic. For instance, we do
not intend to show debugger_v2 in TB.dev for now.
Diffbase #3984.
=> refactor: tease out plugin enumeration from plugins_module

tensorboard/plugins/custom_scalar/polymer3/tf_custom_scalar_dashboard/BUILD
Summary:
Because of this `tf_web_library`, the `javascript` branch has the
compiled `*.js` version of a source `*.ts` file, which makes the custom
scalars migration diff apply less cleanly to that branch. This patch,
once merged and integrated into the `javascript` branch, should restore
the original `*.ts` file.
Test Plan:
Fingers crossed.
wchargin-branch: custom-scalars-remove-tfwl
=> custom_scalars: remove Polymer 3 `tf_web_library`

tensorboard/plugins/graph/polymer3/tf_graph_common/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_controls/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_loader/BUILD
To facilitate an internal script workflow, this removes *.ts files from
`tf_web_library` rules in the graph's polymer 3 migration folder.
This allows the 'javascript' branch to reflect these *.ts files as-is,
rather than converting them into *.js.
=> migrate-graph: remove ts srcs from tf_web_library

tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
Summary:
In #3719, we taught `tf-dom-repeat` to properly set `slot="items"` on
children dynamically added by other templating elements, like `dom-if`.
This patch forward-ports that fix to the Polymer 3 version. This is
needed for the custom scalars dashboard.
Test Plan:
Works in an upcoming custom scalars migration.
Co-authored-by: Stephan Lee <stephanwlee@gmail.com>
wchargin-branch: tfdr-mutation-observer
=> tf-dom-repeat: port `MutationObserver` to Polymer 3

tensorboard/plugins/graph/polymer3/tf_graph/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_app/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_board/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_common/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_controls/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_dashboard/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_debugger_data_card/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_info/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_loader/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_node_search/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_op_compat_card/BUILD
Summary:
Unblocks sync. Some of these generate Google-internal test targets that
fail to build due to the sibling deps that no longer exist. These would
be removed in the migration process, anyway.
Follow-up to #3999.
Test Plan:
A test sync at this commit now succeeds: <http://cl/325560211>.
wchargin-branch: migrate-remove-graph-legacies
=> migrate: remove graph `tensorboard_webcomponent_library`s

tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
Internally, py_binary exists in the ambiently, and will cause errors if
loaded manually. This removes the unnecessary `load` for py_binary.
Tested internally with: cl/325902456
=> Remove unnecessary py_binary loader

tensorboard/components_polymer3/BUILD, tensorboard/components_polymer3/polymer3_lib.ts, tensorboard/plugins/graph/polymer3/tf_graph/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_app/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_board/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_common/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_controls/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_dashboard/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_debugger_data_card/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_info/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_loader/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_node_search/BUILD, tensorboard/plugins/graph/polymer3/tf_graph_op_compat_card/BUILD
Diffbase: https://github.com/tensorflow/tensorboard/pull/4004
This is the last in a series of changes to convert plugins/graph to
Polymer 3. This change
- removes `tags=["manual"]`
- enables the dashboard
Tested externally with `TB_POLYMER3=1 bazel run tensorboard`
and internally. Googlers, see cl/325351322.
=> migrate: enable the converted graph dashboard part 4

tensorboard/defs/defs.bzl, tensorboard/webapp/BUILD, tensorboard/webapp/plugins/text_v2/BUILD, tensorboard/webapp/plugins/text_v2/actions/BUILD, tensorboard/webapp/plugins/text_v2/actions/index.ts, tensorboard/webapp/plugins/text_v2/actions/text_actions.ts, tensorboard/webapp/plugins/text_v2/data_source/text_v2_server_data_source.ts, tensorboard/webapp/plugins/text_v2/effects/BUILD, tensorboard/webapp/plugins/text_v2/effects/index.ts, tensorboard/webapp/plugins/text_v2/effects/text_effects.ts, tensorboard/webapp/plugins/text_v2/effects/text_effects_test.ts, tensorboard/webapp/plugins/text_v2/store/BUILD, tensorboard/webapp/plugins/text_v2/store/testing.ts, tensorboard/webapp/plugins/text_v2/store/text_v2_reducers.ts, tensorboard/webapp/plugins/text_v2/store/text_v2_selectors.ts, tensorboard/webapp/plugins/text_v2/text_v2_module.ts, tensorboard/webapp/plugins/text_v2/types.ts, tensorboard/webapp/testing/BUILD, tensorboard/webapp/testing/require_js_karma_config.js
Note that we still are not implementing reducers.
Details:
- sample data flow:
1. load the text plugin, it fires pluginChanged action. That fetches
runTag map
2. based on the run tag map, we draw few tag groups. Few tag groups
will be opened by default and some won't. The opened ones fire action
for their visibility changes with <run, tag> tuple of current page
3. that will trigger data fetches
4. on reload, we will reload what is currently on screen
About somewhat extraneous looking karma change:
transitive dependency uses lodash and it does not exist on the global without it.
While our build toolchain uses node resolve (rollup), karma uses concatjs (for faster build)
and requires all of our dependencies to be loaded by requirejs. The karma configuration
essentially provides a mapping …
=> text_v2: actions and effects

tensorboard/components_polymer3/BUILD, tensorboard/components_polymer3/polymer3_lib.ts
This change enables mesh plugin in the Polymer 3 world.
=> polymer3: integrate mesh plugin to the migrated code

docs/tbdev_getting_started.ipynb
Missing metadata was breaking import.
Fixed by:
*  Open the notebook in colab
*  Download the notebook from colab using 'download ipynb'
*  Reformat the downloaded notebook using `nbfmt`
Tested:
*  Uploaded to colab and ran.
=> Fix missing metadata in tbdev getting started notebook.

tensorboard/uploader/upload_tracker.py, tensorboard/uploader/uploader.py, tensorboard/uploader/uploader_test.py
When `--one_shot` flag is provided, the user expects the uploader
to pass through the logdir exactly once and then quit.
This change replaces the log line "Listening for new data in logdir"
with a more accurate line "Done passing through logdir", but only
when `--one_shot` is provided.
Tested:
*  Adds a unit test.  
*  Checked uploading from my account.
=> Clarifies output during `--one_shot` upload.

tensorboard/components_polymer3/polymer/BUILD, tensorboard/components_polymer3/polymer/legacy_class.ts
Allows TensorBoard to use mixin.
=> polymer3: add indirection for polymer/lib/legacy/class

tensorboard/webapp/core/effects/core_effects.ts, tensorboard/webapp/core/effects/core_effects_test.ts
This change on purpose introduces one of the anti-pattern of ngrx usage
in our app: composite action.
Background: plugins are rendered when user interacts with the plugins
selector on the header and plugins know to fetch data (if empty) when
`changePlugin` action fires. However, there is other condition in
which the activePlugin can change: (1) user launched with specific
plugin id deep link or (2) plugins listing is loaded. In the past, for
plugins to fetch the data on load, it had to write necessary code for
detecting such nuances which has been a source of pain and a source of
bug.
This change: in the core effects, that understands the core reducers the
best, detects the condition in which the initial non-null value of
activePlugin is set to dispatch `changePlugin` action without user …
=> ng: dispatch changePlugin action when store change

tensorboard/components_polymer3/tf_runs_selector/tf-runs-selector.ts
Because we were using readOnly and was setting the value in the
constructor, the delimiter pattern was never set.
=> polymer3: fix data location rendering

tensorboard/plugins/hparams/polymer3/tf_hparams_session_group_details/tf-hparams-session-group-details.ts, tensorboard/plugins/hparams/polymer3/tf_hparams_table_view/tf-hparams-table-view.ts
This fixes a couple regressions we noticed in the HParams plugin table view:
* The "Show Metrics" column was slightly too narrow in some browsers, pushing the final "s" to the next line.  Rather than just increasing the fixed width up from `5em` I opted to enable `autoWidth` - this is by default just calculated once after the initial load, but that should be sufficient for our case here since the widest part of the column is going to be the header text which will always be included (and the cells just contain checkboxes).
* Broken interactions in `<dom-repeat>` elements nested inside the table view's `vaadin-grid` - various errors would be thrown (typically TypeErrors due to trying to access non-existent properties) when updating the table view contents by selected and deselecting various …
=> migrate: fix regressions in hparams table view

tensorboard/backend/http_util.py, tensorboard/backend/http_util_test.py, tensorboard/backend/security_validator.py
TensorBoard depends on vaadin package and it uses data uri to bundle the
font icons.
This change also removes the global CSP whitelist validation since we
already have validation in the security validator module.
=> add 'data:' to font-src CSP

package.json, tensorboard/components_polymer3/BUILD, yarn.lock
In this change, we use genrule to inline the content since the module
cannot be safely imported from TypeScript internally. In order to have
congruent build system, we just use genrule to concatenate already
compiled sources.
=> polymer3: add web-animations-js shim to Polymer 3

tensorboard/BUILD, tensorboard/components/tf_tensorboard/BUILD, tensorboard/components/tf_tensorboard/default-plugins.html, tensorboard/components_polymer3/tf_tensorboard/BUILD, tensorboard/components_polymer3/tf_tensorboard/default-plugins.html, tensorboard/default.py, tensorboard/plugins/audio/BUILD, tensorboard/plugins/image/BUILD
* This PR removes the references to the deprecated debugger (v1) plugin.
This plugin has been marked as deprecated and for removal in the 2.3.0
release notes. The code itself will be removed in a follow-up change.
* Removes external references to tensorboard/plugins/debugger, from
BUILD files, Python modules and Polymer .html files that are not a part of
plugins/debugger.
* During testing, it was discovered that the BUILD files in plugins/audio and plugins/images
needed to be fixed (i.e., dependency on the ":metadata" BUILD target added in
each respective BUILD file) after plugins/debugger is removed. This probably was due
to an unmasking of transitive dependencies of some sort.
* Detailed steps to verify changes work …
=> [Debuggger V1] Remove external reference to the deprecated plugin

tensorboard/components/tf_backend/BUILD, tensorboard/components/tf_dashboard_common/BUILD, tensorboard/components/tf_imports/BUILD, tensorboard/components/tf_storage/BUILD, tensorboard/components/tf_tensorboard/BUILD, tensorboard/components/vz_chart_helpers/BUILD, tensorboard/components_polymer3/tf_backend/BUILD, tensorboard/components_polymer3/tf_dashboard_common/BUILD, tensorboard/components_polymer3/tf_storage/BUILD, tensorboard/components_polymer3/tf_tensorboard/BUILD, tensorboard/components_polymer3/vz_chart_helpers/BUILD, tensorboard/plugins/graph/tf_graph_board/BUILD, tensorboard/plugins/graph/tf_graph_common/BUILD, tensorboard/plugins/graph/tf_graph_loader/BUILD, tensorboard/plugins/graph/tf_graph_node_search/BUILD, tensorboard/plugins/hparams/tf_hparams_backend/BUILD, tensorboard/plugins/hparams/tf_hparams_main/BUILD
Summary:
We’ve migrated all internal dependencies off of these targets, so we can
now lock them down to prevent backsliding. Generated via Buildozer with:
```
buildozer 'remove visibility //visibility:public' \
//tensorboard/components{,_polymer3}/...:\* \
//tensorboard/plugins/...:%tf_web_library \
;
```
…which imposes `//tensorboard:internal` or stricter due to #3566.
Test Plan:
A test sync (<http://cl/326725258>) passes presubmits, and a build graph
query shows that these targets don’t have direct reverse dependencies
from outside the internal package group.
wchargin-branch: polymer-lockdown
=> polymer: lock down component visibility

tensorboard/components/tensor_widget/BUILD, tensorboard/components_polymer3/polymer/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/BUILD
We were asked to help with an internal Large Scale Change. Some excerpts:
> Migrate genrules that use a Python 3 tool from tools to exec_tools.
>
> genrule.tools uses blaze's host mode and forces to be Python 2, ignoring the py_binary.python_version attribute. <snip>
>
> This CL corrects the use of the Python 3 tool so that it runs Python 3 instead of Python 2 by using exec_tools (if there are 
> no upstream host dependencies).
> 
> Difference between tools and exec_tools:
>
> genrule.tools uses host mode, which ignores the py_binary.python_version attribute and always use Python 2 (to be
> changed to Python 3)
> genrule.exec_tools uses exec mode, which respects the py_binary.python_version attribute (unless an upstream host 
> dependency forces all …
=> Use exec mode instead of host mode for these Python tools

tensorboard/BUILD
When TensorBoard 2.3.0 shipped Angular based entry, we supported the
legacy Polymer based entry via "/legacy.html" route. Since the endpoint
was meant to be used very temporary, and since the release is already
cut and released, we are now removing the legacy entry point.
=> cleanup: remove the legacy build in the TensorBoard

tensorboard/components_polymer3/tf_runs_selector/tf-runs-selector.ts, tensorboard/plugins/graph/polymer3/tf_graph_dashboard/tf-graph-dashboard.ts, tensorboard/plugins/graph/polymer3/tf_graph_debugger_data_card/tf-graph-debugger-data-card.ts, tensorboard/plugins/graph/polymer3/tf_graph_node_search/tf-graph-node-search.ts, tensorboard/plugins/hparams/polymer3/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts, tensorboard/plugins/hparams/polymer3/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts
Summary:
In Polymer 3, using `@property({readOnly: true})` on a property that
also has a TypeScript initializer is always a silent error: the Polymer
decorator will add a getter, causing the initialization code added to
constructor by `tsc` to be a no-op. This patch removes all such
occurrences, as identified by running
```
git grep readOnly \
'tensorboard/plugins/*polymer3*.ts' \
'tensorboard/components_polymer3/*.ts' \
;
```
and checking manually for initializers.
Test Plan:
Not manually tested. As for completeness, with `-A4` added to the above
`git grep`, the only `=`-sign is a false positive.
wchargin-branch: polymer3-no-readonly
=> polymer3: remove `readOnly` from initialized props

README.md
Summary:
Before `--samples_per_plugin` existed, the only way to change the
sampling thresholds was to patch `application.py` manually. But the flag
has been the right way to do this since #1138, and manual patching has
been insufficient since the flag value was exposed to plugins in #3271.
There’s no need to discuss this implementation detail any more.
wchargin-branch: readme-remove-application-reference
=> readme: remove reference to `backend/application.py`

tensorboard/webapp/plugins/plugins_component.ng.html, tensorboard/webapp/plugins/plugins_component.ts, tensorboard/webapp/plugins/plugins_container.ts, tensorboard/webapp/plugins/plugins_container_test.ts
Previously, we only showed a warning when a given logdir does not
result in activePlugin selection. This change introduces similar warning
for the case when a user erroneously typed incorrect plugin id that we
do not know about.
This change also renders the data location in the warning page.
Fixes #3856.
=> bug: show warning when pluginId do not match known ids

tensorboard/components_polymer3/tf_backend/canceller.ts, tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts, tensorboard/plugins/custom_scalar/polymer3/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.ts, tensorboard/plugins/custom_scalar/polymer3/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.ts, tensorboard/plugins/distribution/polymer3/tf_distribution_dashboard/tf-distribution-loader.ts, tensorboard/plugins/histogram/polymer3/tf_histogram_dashboard/tf-histogram-loader.ts, tensorboard/plugins/hparams/polymer3/tf_hparams_session_group_details/BUILD, tensorboard/plugins/hparams/polymer3/tf_hparams_session_group_details/tf-hparams-session-group-details.ts, tensorboard/plugins/pr_curve/polymer3/tf_pr_curve_dashboard/tf-pr-curve-card.ts, tensorboard/plugins/scalar/polymer3/tf_scalar_dashboard/BUILD, tensorboard/plugins/scalar/polymer3/tf_scalar_dashboard/tf-scalar-card.ts
Summary:
The data loader behavior maintains a fine-grained cache of key-value
pairs. This is useful because when the set of requested keys expands,
only the new keys need to be fetched. But, until now, the behavior has
been hard-coded to fire a separate request for each key-value pair.
Clients can have either fine-grained cache invalidation or efficient
batched requests, but not both at the same time. This patch enriches the
behavior to support just that.
In a future change, the scalars dashboard will take advantage of this to
batch requests for multiple runs and a single tag. This will only
require changing the `requestData` function in `tf-scalar-card`.
In doing so, we need to shuffle around the API a bit. Instead of asking
clients to provide `getDataLoadUrl: (Item) => string` plus a …
=> data-loader-behavior: add fine-grained batching support

README.md
With the Angular based TensorBoard, we've changed our policy to turn off
the auto reload by default. Unfortunately, due to my oversight, we have
failed to capture this in the change log.
This change adds a warning that it has changed.
=> doc: add a note that auto-reload is turned off by default

tensorboard/webapp/angular/BUILD, tensorboard/webapp/plugins/npmi/data_source/BUILD
Summary:
Needed to unblock internal sync.
Test Plan:
Test sync CL: <http://cl/327722605>
wchargin-branch: npmi-data-source-angular-deps
=> npmi: add missing `expect_*` Angular deps

README.md
We will soon launch the hparams dashboard in TensorBoard.dev. It should be listed along with other dashboards available in TensorBoard.dev.
=> Add hparams to list of launched TensorBoard.dev dashboards

.travis.yml
This change should have no visible effect to the product.
The Travis flow is updated to ignore the build, test steps that
come after the `bazel fetch`.
2 followups will re-add bazel build, test steps to rebuild the
Travis cache.
See https://github.com/tensorflow/tensorboard/issues/4091
=> [infra] updating Travis cache with fetch-only flow (1/3)

.travis.yml
This change should have no visible effect to the product.
The Travis flow is updated to reinstate the build step, but
keep ignored the test steps that come after the `bazel build`.
This PR adds the components_polymer3/ dir to the bazel build
step.  Followups will re-add remaining steps.
See https://github.com/tensorflow/tensorboard/issues/4091
=> [infra] update Travis cache with built components_polymer3 (part 2)

.github/workflows/ci.yml
Due to the internal build quirks, we cannot import the hourglass dependency for the
angular material using "@npm//@angular/material" (and likewise for cdk). Instead,
we need to import a specific module and the indirection helps with that.
Over some time, we've made the same mistake over and over and this change catches
the mistake at the PR time. 
This change is expected to fail since npmi currently violates the rule.
The issue is expected to be addressed in #4082
=> ci: disallow importing directly from angular/material and cdk

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/core/views/BUILD, tensorboard/webapp/core/views/page_title_component.ts, tensorboard/webapp/core/views/page_title_container.ts, tensorboard/webapp/core/views/page_title_module.ts
Summary:
This behavior is slightly different from Polymer TensorBoard, in that if
the window title is set but then the server restarts and the window
title is no longer set, it will revert to “TensorBoard” instead of
retaining its previous value.
This implementation uses a new view instead of an effect so that we can
read the environment information from the store without violating our
policies about composite actions.
Test Plan:
Launch TensorBoard with `--window_title one`, and note that the title is
properly set. Keep the frontend open, and relaunch the server with
`--window_title two`. Press the in-app “Reload” button, and verify that
the title updates. Finally, relaunch the server with no `--window_title`
and verify that the frontend resets the title to “TensorBoard”.
No TypeScript …
=> core: fix `--window_title` in Angular TensorBoard

tensorboard/pip_package/requirements_dev.txt, tensorboard/pip_package/test_pip_package.sh
On 8/31/2020, CI runs for PRs started failing with the error (see [1])
on tf-nightly jobs.
`ModuleNotFoundError: No module named 'setuptools'`
This unblocks the broken CI by bumping the dev dependency on
`virtualenv`. One side effect is we now need to specify arguments
to virtualenv separately, otherwise `virtualenv -qp ...` throws:
`virtualenv: error: argument -q/--quiet: ignored explicit argument 'p'`
Tested locally by running these:
`bazel run //tensorboard/pip_package:test_pip_package -- --tf-version ""`
`bazel run //tensorboard/pip_package:test_pip_package -- --tf-version tf-nightly`
[1] https://travis-ci.org/github/tensorflow/tensorboard/jobs/722758663
=> [infra] bump 'virtualenv' dev dependency version

tensorboard/plugins/projector/polymer3/vz_projector/BUILD, tensorboard/plugins/projector/polymer3/vz_projector/bundle.ts, tensorboard/plugins/projector/polymer3/vz_projector/standalone_lib.html
Remove dependency on HTML based analytics.
Because now we need to provide `ga` symbol, we moved the import order.
=> refactor: remove analytics.html dependency

.github/workflows/ci.yml, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/BUILD, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/BUILD, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_operator/BUILD, third_party/workspace.bzl
This change unbreaks the sync with some misc fixes:
- Removes licenses() comments under npmi's metric_arithmetic/
- Removes unused 'loads' in workspace.bzl
Drive by changes to workspace.bzl:
- Added to CI lint checks, to catch future instances where it may
not pass Buildifier
- Reformatting slightly via Buildifier
- Remove unused 'com_google_protobuf_js'
Googlers, see
example failure: cl/329551428
example success: cl/329569832
=> chore: misc sync fixes (unused in workspace.bzl, license comments)

.git-blame-ignore-revs
Summary:
Merged in #4122.
Test Plan:
The output of `git blame tensorboard/components/tf_backend/backend.ts`
no longer has any lines blaming to the commit in question.
wchargin-branch: prettier-2.1.1-unblame
=> blame: ignore Prettier 2.1.1 reformatting

package.json, tensorboard/webapp/testing/BUILD, tsconfig-lax.json, tsconfig-test.json, tsconfig.json, yarn.lock
Changes a few frontend dependencies:
- tsconfigs now pull in 'es2020' rather than 'es2018' typedefs.
Despite TS docs [1] not mentioning es2020 as an option, our
version of TS supports this option [2]. Notably this adds
typing support for `Array.prototype.flat()` (part of ES2019).
- tsconfigs have some more strict options that were not
part of the flags [3] included by `"strict": true`.
- rxjs bumped to 7.0.0beta0. The changelog [4] notes several
breaking changes, but none seem to affect us. Notably this
new version includes the `combineLatestWith` operator.
Manually clicked around the UI, and behavior seems unaffected.
[1] https://www.typescriptlang.org/docs/handbook/compiler-options.html
[2] https://github.com/microsoft/TypeScript/pull/29167
[3] …
=> infra: upgrade FE deps

tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
Fixed incorrect behaviour of hidden annotations toggle. When turned of, then on, annotations did not come back.
=> [nPMI] Showing Hidden Annotations on Toggle

tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts, tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_component.ts, tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_container.ts
The two views on the right (annotations list and parallel coordinates) now react to window and sidebar width changes.
=> [nPMI] React to both Sidebar Width and Window Width Changes

tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts, tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
When a metric filter is added, now automatically sorts by this filter.
=> [nPMI] Automatically Change sorting when Metric Filter Added

tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts, tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
Summary:
Legitimate build failure due to presubmit-submit skew.
This reverts commit 19e23ed79e18d1cc3e7d69368fc505d168d127bf.
Test Plan:
Running `bazel build //tensorboard` now completes successfully; before,
it failed as in this build log:
<https://travis-ci.org/github/tensorflow/tensorboard/jobs/725312692>
Errors were:
- Object literal may only specify known properties, and 'sorting' does
not exist in type 'NpmiState'.
- Cannot find name 'SortingOrder'.
wchargin-branch: revert-4133
=> Revert "Automatically Change sorting when Metric Filter Added (#4133)"

tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts, tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
Summary:
This rolls forward commit 19e23ed79e18d1cc3e7d69368fc505d168d127bf with
minor name changes (`sorting` to `sort`, `SortingOrder` to `SortOrder`)
so that it builds.
Test Plan:
Running `bazel build //tensorboard` still completes successfully.
wchargin-branch: roll-forward-4133
=> Roll forward "Automatically Change sorting when Metric Filter Added (#4133)"

tensorboard/backend/http_util.py, tensorboard/backend/http_util_test.py
Google Analytics can use `post` method and requires `connect-src`.
This change does not add Google Analytics in the allowlist but merely it configurable.
=> csp: make connect-src configurable

tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.scss, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_component.scss, tensorboard/webapp/plugins/npmi/views/main/main_component.scss, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.scss, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ts, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_component.scss
Changed remiaining css throughout the plugin where color templates were not yet used.
=> [nPMI] Changed to Use Template Colors throughout CSS

tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
When the PC plot was minimized, the annotations list showed whitespace at the bottom. This has been fixed by increasing the buffer size.
=> [nPMI] Fixed MinBuffer for Scrolling when PC gets minimized.

.github/workflows/ci.yml, docs/dataframe_api.ipynb, docs/get_started.ipynb, docs/graphs.ipynb, docs/hyperparameter_tuning_with_hparams.ipynb, docs/image_summaries.ipynb, docs/migrate.ipynb, docs/scalars_and_keras.ipynb, docs/tbdev_getting_started.ipynb, docs/tensorboard_in_notebooks.ipynb, docs/tensorboard_projector_plugin.ipynb, tensorboard/plugins/mesh/Mesh_Plugin_Tensorboard.ipynb
This formatting change scrubs notebooks with the latest `nbfmt`. The updated behavior removes any field not explicitly allowed. In https://github.com/tensorflow/docs/commit/174c9a5c1cc51a3af1de98d84824c811ecd49029 I've accounted for `metadata.colab.resources` used by the TensorBoard-in-Colab UI. It also makes sure all cells have a `metadata.id` (used by the new translation workflow).
This also updates the `nbfmt`CI test to use a recent version from the [TensorFlow docs notebook tools](https://github.com/tensorflow/docs/tree/master/tools/tensorflow_docs/tools).
=> nbfmt updates

package.json, tensorboard/plugins/projector/vz_projector/BUILD, tensorboard/plugins/projector/vz_projector/data.ts, tensorboard/plugins/projector/vz_projector/knn.ts, tensorboard/plugins/projector/vz_projector/util.ts, tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts, tensorboard/plugins/projector/vz_projector/vz-projector.ts, tensorboard/webapp/third_party/BUILD, tensorboard/webapp/third_party/tfjs.ts, yarn.lock
We were using weblas for the matrix multiplication in GPU. Since the
library is not maintained regularly and depends on vulnerable versions
of libraries, we break the dependency to weblas by replacing it with
TensorFlow.js.
When the demo was run with tf.js, I did not see anything out of
ordinary.
Plan afterwards: will remove dependency on weblas.
=> cleanup: break projector dependency on weblas with tf

tensorboard/plugins/projector/README.md
The mentioned `devserver` target does no longer exist in the build file. It has been renamed to `standalone`.
=> Plugin/Projector: Document renaming of standalone build target

tensorboard/compat/proto/cluster.proto, tensorboard/compat/proto/config.proto, tensorboard/compat/proto/cpp_shape_inference.proto, tensorboard/compat/proto/debug.proto, tensorboard/compat/proto/event.proto, tensorboard/compat/proto/meta_graph.proto, tensorboard/compat/proto/rewriter_config.proto, tensorboard/compat/proto/saved_object_graph.proto, tensorboard/compat/proto/saver.proto, tensorboard/compat/proto/struct.proto, tensorboard/compat/proto/tfprof_log.proto, tensorboard/compat/proto/trackable_object_graph.proto, tensorboard/compat/proto/verifier_config.proto
Summary:
This pulls in routine updates since v2.3.0-rc2, plus new `go_package`
directives just added in:
<https://github.com/tensorflow/tensorflow/commit/e1a7896aaf934632eceefaaedb3f4fb9b91cfd67>
Test Plan:
The `proto_test` actually still fails with today’s nightly, because some
changes are fresh in TensorFlow head today. But the test diff, as
rendered with #4162, shows only `go_package` additions, as expected. The
test should pass on tomorrow’s `tf-nightly==2.4.0.dev20200915`.
wchargin-branch: proto-sync-e1a7896aaf93
=> proto: sync to TensorFlow e1a7896aaf93 (2020-09-14)

docs/design/route_namespaced_state.md
Adds a design doc on frontend routing, originally created internally.
Test plan:
Ran a test sync and saw that this creates an empty sync
cl/331809580
=> [oss-timeseries] migrate internal design doc on routing

tensorboard/compat/proto/proto_test.py
Summary:
We now list the diffs of all proto definitions that aren’t up to date
rather than just the first one.
Test Plan:
This test currently passes, but if you revert #4163 and use current
`tf-nightly`s then it will fail. Do so, then run the test manually
(`bazel test //tensorboard/compat/proto:proto_test`) and note that the
output contains diffs from 9 files.
wchargin-branch: proto-test-show-all-failures
=> proto_test: on failure, show all non-empty diffs

tensorboard/webapp/angular/BUILD
Adds build targets for specific Angular material components,
including:
material_button_toggle
material_menu
material_paginator
material_progress_spinner
material_sort
material_table
material_expansion
cdk_drag_drop
=> [oss-timeseries] add angular material build targets.

tensorboard/plugins/metrics/BUILD, tensorboard/plugins/metrics/http_api.md, tensorboard/plugins/metrics/metadata.py, tensorboard/plugins/metrics/metrics_loader.py, tensorboard/plugins/metrics/metrics_plugin.py, tensorboard/plugins/metrics/metrics_plugin_test.py
Adds the plugin backend for Time Series to OSS, originally internal.
Googlers, this PR is made by copying changes as is from
cl/331838160, removing unused imports, and running the `black`
formatter.
See that CL for manual changes introduced.
=> [oss-timeseries] migrate metrics backend

tensorboard/webapp/BUILD, tensorboard/webapp/testing/BUILD, tensorboard/webapp/testing/dom.ts, tensorboard/webapp/testing/lang.ts, tensorboard/webapp/testing/mat_icon_module.ts, tensorboard/webapp/testing/material.ts, tensorboard/webapp/types/BUILD, tensorboard/webapp/types/ui.ts, tensorboard/webapp/util/BUILD, tensorboard/webapp/util/colors.ts, tensorboard/webapp/util/colors_test.ts, tensorboard/webapp/util/lang.ts, tensorboard/webapp/util/lang_test.ts, tensorboard/webapp/util/ngrx.ts, tensorboard/webapp/util/ngrx_test.ts, tensorboard/webapp/util/string.ts, tensorboard/webapp/util/string_test.ts, tensorboard/webapp/util/types.ts, tensorboard/webapp/util/value_formatter.ts, tensorboard/webapp/util/value_formatter_test.ts
Diffbase: https://github.com/tensorflow/tensorboard/pull/4171
Adds testing/, types/, util/ folders for Time Series.
The 1st commit contains pre-reviewed code. Manual changes
to be reviewed are found in this PR's commits after the 1st.
Googlers, see test sync cl/332324994 for confidence that this
does not block the sync.
=> [oss-timeseries] add testing/, types/, util/

tensorboard/webapp/app_routing/BUILD
PR [1] introduced a sync-breaking change, due to app_routing/
having a transitive dependency that it did not depend on
explicitly. This change fixes the strict dep.
The test sync cl/332324994 from PR [1] actually failed.
Googlers, see the newer test sync cl/332491049, which should
actually work this time.
[1] https://github.com/tensorflow/tensorboard/pull/4173
=> [oss-timeseries] fix missed app_routing/ dep needed for sync

tensorboard/plugins/scalar/BUILD, tensorboard/plugins/scalar/scalars_demo_eager.py
Previous demo worked with TF 1 mode.  New demo illustrates how to work in simpler eager mode. 
Creates a new binary `scalars_demo_eager` which, when executed, creates a logdir with a user configurable set of random scalars.
cmd
```
$ bazel run tensorboard/plugins/scalar:scalars_demo_eager
```
output
```
0917 17:00:43.593062 4585397696 scalars_demo_eager.py:67] Created 1 runs, each with 1 tags, and 1 scalar values in each tag
I0917 17:00:43.593160 4585397696 scalars_demo_eager.py:69] Output saved to /tmp/scalars_logdir.
I0917 17:00:43.593215 4585397696 scalars_demo_eager.py:84] 
You can now view the scalars in this logdir:
Run local: 
tensorboard --logdir=/tmp/scalars_logdir
Upload to …
```
=> Update scalars demo for TF2

third_party/workspace.bzl
The functional tests rely on downloading and launching a
Chromium browser snapshot, currently pinned to version
68.0.3440.0 in the `org_chromium_chromium` target in
third_party/workspace.bzl.
Chromium 68 lacks some new modern features, such as
Array.prototype.flat(), so this change bumps the browser
snapshot version to a more recent 84.0.4147.0.
Tested on Mac via
`bazel test //tensorboard/webapp:karma_test_chromium-local`
For Chromium version information, see
https://omahaproxy.appspot.com/
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html
Fixes https://github.com/tensorflow/tensorboard/issues/4175
=> chore: bump Chromium version used in functional tests

tensorboard/webapp/plugins/BUILD, tensorboard/webapp/plugins/plugins_component.ng.html, tensorboard/webapp/plugins/plugins_component.ts, tensorboard/webapp/plugins/plugins_container.ts, tensorboard/webapp/plugins/plugins_container_test.ts
We want to render more helpful error messages for cases where the TensorBoard server is not responsive or has an error. We want to allow other flavors of TensorBoard to customize these errors.
In https://github.com/tensorflow/tensorboard/pull/4186 we improved error handling for `data/runs`, `data/plugins_listing` and `data/environment` HTTP requests. Errors from those requests are translated into a `failureCode` field in the `pluginsListLoad` state.
In this PR we render those errors in the `plugins` component, given that we want to render the errors in a similar way to the errors the component already renders.
We also provide a mechanism for parent component to specify custom error templates. This will allow other …
=> Render PluginLoadState errors in the UI and allow parent components to override error UI

docs/tensorboard_in_notebooks.ipynb
This addresses #4169
This allows the local browser to access tensorboard running inside docker, as the guide does. Without this, tensorboard UI will not be accessible from outside the container
=> docs: add bind_all to allow docker access

tensorboard/uploader/BUILD, tensorboard/uploader/uploader_subcommand_test.py, tensorboard/uploader/uploader_test.py
I thought UploadIntent was untested before because I didn't notice it at the bottom of `uploader_test.py` (and apparently neglected to search for it).
=> uploader: move UploadIntent tests to uploader_subcommand_test.py

tensorboard/webapp/index_polymer3.uninlined.html
An internal build of tensorboard does not properly load UI because dependencies are loaded in an incorrect order.
Load polymer3 portions of app before angular portions.
* Verify `bazel run tensorboard -- --logdir <logdir>` continues to work.
* Verify that internal builds now work.
=> Load polymer3 portions of app JavaScript before Angular portions.

tensorboard/uploader/BUILD
Internal tests are broken by https://github.com/tensorflow/tensorboard/pull/4199. Internally we expect grpc_testing to be an explicit dependency in the BUILD file.
Use appropriate placeholder BUILD dependency.
=> Expect grpc_testing to be included in internal BUILD files.

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts, tensorboard/webapp/app_routing/location.ts
Enabling the upcoming Time Series dashboard [1] requires the
AppRoutingModule to be in effect with routes. Internal tests
caught a race condition, in which "setting the plugin hash",
e.g. `/#scalars` was done before the AppRouting effects.
AppRouting then replaced the entire URL hash on initial
navigation, losing important state.
This change adds an exception in AppRouting to allow the
initial navigation to preserve the hash. Non-initial navigations
can still safely discard, as we expect DeepLinkProviders to
manage things.
An alternative considered was to make HashStorageContainer
re-set the hash upon navigations. This also works, but the
drawback is that it introduces a dependency from Core on
AppRouting, and having the HashStorageContainer know about
routing side effects is non-ideal. …
=> Fix URL hash loss upon initial navigation

tensorboard/compat/tensorflow_stub/BUILD, tensorboard/webapp/runs/data_source/runs_data_source_test.ts
The Google internal sync warns on a couple
miscellaneous changes. This removes an incorrect
LICENSE export line and removes an unused TS
variable.
Merge plan: rebase, resulting in 2 commits
[1] https://github.com/tensorflow/tensorboard/pull/4204
=> misc: fix sync warnings for LICENSE and TS

tensorboard/components/tf_backend/router.ts, tensorboard/plugins/projector/vz_projector/vz-projector.ts, tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
See https://github.com/tensorflow/tensorboard/issues/4207 for details.
Several callsites in TB's Angular and Polymer codebases read
directly from `window.location.search`. For example, scalar cards
read the `?tensorboardColab=true` param at arbitrary times in
the TB session, to know whether TB is running inside Colab.
AppRoutingEffects has an initialization step that clears/discards
all existing URL queryParams, causing breaking behavior.
Since AppRouting is not yet a complete source of truth for URL
query params, this change makes all callsites that read from
`window.location.search` do so on the initial app load, before
AppRouting can interfere.
An alternative considered was making AppRoutingEffects aware
of a hardcoded list of reserved queryParam keys, and preserving
them whenever …
=> bug: fix AppRouting interference with URL queryParam-reading components

tensorboard/program.py
Summary:
Recent changes (<http://cl/334534610>) override this function in the
Google-internal build of TensorBoard, so changes in OSS should be
careful if making backward-incompatible changes to it, even though it
looks to be a private API.
wchargin-branch: program-note-google-sigterm-patch
=> program: note Google-internal signal handling patch

tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.ts
Hparams dashboard does not work in Google-internal colab environments because they do not support POST requests. 
Reuse mechanism introduced in #4191 that provides a 'tensorboardColab' query parameter in the URL to indicate a colab environment. If the value for the parameter is true then the Hparams dashboard will send GET requests. Otherwise it sends POST requests.
There already existed code that purported to determine if the hparams dashboard was running in a colab environment but this code has not worked for some time, possibly since #2798. The code in this PR simply replaces that code. The plumbing to pipe this through other layers had already been implemented.
* Tests
I loaded a local tensorboard with the query …
=> Use GET instead of POST requests for hparams in colab environment.

tensorboard/uploader/uploader_subcommand.py
Modifies whitespace in the uploader stdout to improve readability.
Previous message:
```
Data for the "hparams" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Upload started and will continue reading any new data as it's added
to the logdir. To stop uploading, press Ctrl-C.
```
New message:
```
Data for the "hparams" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Upload started and will continue reading any new data as it's added
to the logdir.
To stop uploading, press Ctrl-C.
```
Verified that a new experiment is still created.
=> Add a newline to improve output readability

tensorboard/plugins/histogram/summary_v2.py
Check for tf.distribute.TPUStrategy for special handling since tf.distribute.experimental.TPUStrategy was renamed/deprecated.
Fix failures when writing histogram summaries on TPUs.
See Summary.
* Screenshots of UI changes:
N/A
Ran a test in tensorflow, confirmed that TPUs
Supporting dynamic shapes on TPU.  Large amount of future work.
=> histogram: update symbol name for TPU summary special-case

tensorboard/webapp/app_container.ts
Color picker has different modes: inline vs. modal. In our case, since
we use the color picker in the scrollable area of the runs table, we
need it to escape the scrollable container and absolutely position by
injecting component on the body. For that, in order for ngx-color-picker
to properly position without using Angular cdk component, it requires to
know the root component.
This change injects ViewContainerRef which is what ngx-color-picker
requires but details of how that lets descendent components know of the
root component escape us at the moment.
=> fix timeseries color picker positioning

.bazelrc, tensorboard/uploader/server_info_test.py
Summary:
Python protocol buffer bindings have parsing and serialization
implementations in pure Python and in C++. The C++ ones are much faster.
Our built Pip package already uses those because they’re on by default
in the standard `protobuf` wheel, which we depend on. But our binaries
built with Bazel don’t, because we express protobuf dependencies via
Bazel (rather than just ambiently via the Pip package), and in Bazel
land they are not on by default. This patch flips that flag.
This unfortunately adds a fair amount of buildspam to our logs—on top of
the rest of our build spam, which is already entirely due to protobuf
(and which I have tried and failed to fix in the past). I have tried to
reproduce this to file an upstream issue, but getting a Bazel workspace
to depend on protobuf …
=> bazelrc: use fast Python protos

tensorboard/webapp/app_module.ts, tensorboard/webapp/feature_flag/actions/BUILD, tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts, tensorboard/webapp/feature_flag/store/BUILD, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
Followup: https://github.com/tensorflow/tensorboard/pull/4224
Introduces a selector on the ngrx FeatureFlagModule to detect
whether the app is opened within a Colab environment, using
the existing `?tensorboardColab=true` scheme.
Code in both Angular and Polymer codebases already detect
this URL queryParam. This change just makes it readable from
the ngrx store.
Googlers, see test sync cl/336078907
=> Add feature flag ngrx selector for Colab environment

tensorboard/components/tf_markdown_view/BUILD, tensorboard/components/tf_markdown_view/sanitize.ts, tensorboard/components/tf_markdown_view/tf-markdown-view.ts
Several Google-internal instances of TensorBoard require an html sanitization step for user-provided markdown.
Define a sanitize() function for usage by tf-markdown-view before it renders user-provided markdown. The default implementation returns the input html without modification.
Internally at Google we wil override the implementation of this sanitize() operation.
Googlers please see cl/336163444 for corresponding internal CL, which will have to be submitted before this PR is merged.
Ran local tensorboard for OSS with text plugin and ensured user markdown is still rendered properly.
Patched the changes from this PR into a Google-internal …
=> Add overridable sanitize() step to tf-markdown-view.

tensorboard/plugins/metrics/metrics_plugin.py, tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/feature_flag/actions/BUILD, tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts, tensorboard/webapp/feature_flag/store/BUILD, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_http_client.ts, tensorboard/webapp/webapp_data_source/tb_http_client_module.ts, tensorboard/webapp/webapp_data_source/tb_http_client_test.ts, tensorboard/webapp/webapp_data_source/tb_http_client_testing.ts, tensorboard/webapp/webapp_data_source/tb_http_client_types.ts, tsconfig.json
Diffbase: https://github.com/tensorflow/tensorboard/pull/4223
Time Series relies mainly on POST requests to the /timeSeries
endpoint. This change updates the Python plugin backend to
support GET requests.
In general, we'd like to fallback to GET instead of POST for any
frontend components that make network requests while in a
Colab environment, until internal Colab supports POST.
Manually checked via the DevTools network panel that opening
the Time Series dashboard makes GET requests when the URL
contains `?tensorboardColab=true`, and POST requests when
it does not.
Googlers, see test sync cl/336394977
=> Avoid POST requests in TBHttpClient when in Colab

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
Followup: https://github.com/tensorflow/tensorboard/pull/4220
AppRoutingEffects recently added logic to preserve URL hash
upon the initial 'navigated' action (see [1]). While this fixed cases
where the URL needs to be read upon initial page load, it does
not address an upcoming case needed for deeplinking pins in
Time Series.
Flow: pin a card, DeepLinkProvider serializes `?pinnedCards=`
in the URL which drops `#timeseries`, reload the tab, the
selected dashboard is no longer Time Series.
Expected: Time Series remains selected upon tab reload.
This change overcomes this issue the DeepLinkProvider by
preserving the hash upon same-RouteId navigations.
Manually checked internal TB embedders that navigating to
a different route id still clears the hash.
Googlers, see sync cl/335688801
[1] …
=> AppRouting should preserve hash on same-RouteId navigations

tensorboard/webapp/metrics/data_source/types.ts, tensorboard/webapp/metrics/store/BUILD, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts, tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/types.ts
Diffbase: https://github.com/tensorflow/tensorboard/pull/4219
Followup: https://github.com/tensorflow/tensorboard/pull/4221
Adds ngrx reducer logic and types to support storing
pinned cards that originate from URL storage. Before
'tagMetadataLoaded' creates real cards, TensorBoard is now
able to keep track of pinned cards from the URL, in the ngrx
store.
A followup will implement the actual deeplink provider.
Googlers, see test sync cl/335717460
=> Update ngrx store for pinned cards from storage

tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
The /scalars_multirun endpoint triggers errors when TensorBoard is
hosted with a Google Cloud Spanner backend. This change reverts
TensorBoard back to using `_requestDataGet` unconditionally.
Once [1] is synced into Google, we plan to re-enable the
`_requestDataPost` path for non-Colab environments.
Manually checked that the scalars dashboard makes GET requests
to `/data/plugin/scalars/scalars` with and without the
`?tensorboardColab=true` flag.
Googlers, see b/170675710.
[1] https://github.com/googleapis/python-spanner/pull/144
=> Temporarily disable usage of scalars_multirun endpoint

tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
Bookmark loading currently fails in the projector plugin (see issue #4159)
The failure is because of a missing type check in `getParentDataIndex()`, crashing on `getAttribute()`. This change makes sure the object that is checked against is actually an HTMLElement.
Same as described in issue #4159 
There is probably be a better way to find the data-index of the selected bookmark. The current approach seems a bit hackish. But that's beyond the scope of the bug fixed here.
=> Projector Plugin: Fix bookmark loading (issue #4159)

tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Found the instance with: `rg 'console.log' -g '**/*_test.ts'`
There are no other instance of console.log in test.
=> cleanup: remove extraneous console.log in test

tensorboard/webapp/plugins/npmi/npmi_container_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_search/annotations_search_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/data_selection_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_operator/metric_arithmetic_operator_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/metric_search/metric_search_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_test.ts, tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts, tensorboard/webapp/plugins/npmi/views/selected_annotations/selected_annotations_test.ts, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_test.ts, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_test.ts
Angular test specs have their own way of compiling and specifying
modules. As a result, when building Angular template, it can resolve to
a different implementation or nothing (e.g., <mat-icon> without
importing MatIconModule resolves to nothing). This makes Angular's *Ivy*
compiler write warning (instead of throwing exception and halting the
build) and litters our test.
Ideally, there should be a way to assert on console.warn and fail the
test but we will not invest much time in infrastructure in this PR, at
least.
Used this script to modify BUILD files (which resulted in no-op)
```sh
test_files="$(git show --pretty="format:" --name-only HEAD | grep _test.ts)"
for test_file in $test_files; do
fullname=$(bazel query "$test_file")
target=$(bazel query "attr('srcs', $fullname, …
```
=> cleanup: NO_ERRORS_SCHEMA to avoid noise in test

tensorboard/webapp/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool_test.ts
This is one of the foundational library for the new upcoming feature:
Gpu based line chart. In the new line chart, we would like to leverage
OffscreenCanvas which allows worker thread to manipulate the canvas.
In doing so, we are creating a small library that maintains worker
instances so we don't spawn off unbounded number of workers.
This is a roll-forward of a reverted commit 5c82a48 (#4237)
Notice additional changes to doc on worker.ts and minor changes to
worker_pool_test.ts. Internal conformance hate any sight of `Worker`
that is used for non-type purposes.
Reference sync: cl/337249437
=> line-chart: create reusable worker

tensorboard/webapp/BUILD, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/routes/BUILD, tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts, tensorboard/webapp/routes/index.ts
Diffbase: https://github.com/tensorflow/tensorboard/pull/4220
When cards are pinned/un-pinned in Time Series, their
state is now reflected in the URL, while the user is on a
route of kind EXPERIMENT or COMPARE_EXPERIMENTS.
Pinned cards will persist across tab reloads. This behavior
can be configured per-route via updating the use of
CoreDeepLinkProvider.
Googlers, see test sync cl/335898836
=> feat: persist pinned cards in URL with DeepLinkProvider

tensorboard/webapp/metrics/BUILD, tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/metrics_module.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts, tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts, tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts, tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
Diffbase: https://github.com/tensorflow/tensorboard/pull/4244
Prevents the "toggle pin" button from creating a new pin,
if we already have the max number of pins allowed.
Unresolved pins still count towards the quota.
This enforced limit prevents the URL from overflowing,
see https://github.com/tensorflow/tensorboard/issues/4242
Googlers, see test sync cl/338344567
=> [time series] prevent pinning cards from exceeding limit

tensorboard/defs/defs.bzl
Few details first:
1. TensorBoard uses webfiles.zip to serve assets
2. TensorBoard uses SASS and compiled CSS has sourcemap url to their
respective original source path
3. TensorBoard yet does not have dev target and does not bundle in
sourcemaps in the webfiles
Given that we would want to take very different approach when doing dev
assets for bundling reasons too, we should safely turn off sourcemap
options in the sass binary which currently is littering on the console
due to missing resources.
=> infra: remove sourcemap for sass

tensorboard/uploader/exporter.py, tensorboard/uploader/exporter_test.py
The exporter for TB.dev would save arrays containing text in a pickled format rather than an end-user, easily verifiable format.
Force the dtype of the numpy array to a fixed length text dtype, when it was set to np.object, which is only used internally for string/string_refs.
none.
Unit tests updated to test the type converson.
Manually inspected the exported files, loadable without setting allow_pickle. text is relatively easy to inspect with "more".
We can't fix this before the data gets to the client due to the nature of the conversions within the client.  This approach …
=> Remove pickling of text arrays on export

tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/types.ts
This module is anaologous to d3.scale. While doing performance
explorations, we found d3.scale operations to cause a lot of GC
impacting performance very significantly; a simple math operations were
taking a significant time that we would be spending more time converting
coordinate system than drawing.
This change introduces two kinds of scale; linear and log based 10. Some
utility method on the scales are pure wrapper around d3 method but for
the critical path, we wroute our own.
For posterity, we did look into using GPGPU to support mass coordinate
conversions but it introduced more noises and, near half the time, it
was slower than simple CPU based implementation.
=> line chart: added scale libraries

tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
Due to the build quirk, our webapp cannot depend on d3 directly. To work
around, we can depend on our indirection under
//tensorboard/webapp/third_party. This change does that.
=> sync: depend on third_party d3 indirection

tensorboard/uploader/uploader.py, tensorboard/uploader/uploader_subcommand.py, tensorboard/uploader/uploader_subcommand_test.py
https://github.com/tensorflow/tensorboard/issues/4225
Modifies UploadIntent to quit with a helpful message when executing on a non-existent logdir in `one_shot` mode.
Modifies Uploader to output a message with delete instructions for when a user uploads an empty but existing directory in `one_shot` mode.
* Testing
Adds a unit test.  Simplifies a previous unit test to restrict testing to the UploadIntent behavior, and not test the underlying Uploader behavior.
Manually tested uploading a normal directory, an empty directory, and a missing directory. 
Sample output when one_shot uploading an existing but empty directory.
```
$ bazel run tensorboard -- dev upload --logdir=~/tensorboard-logdirs/emptydir/ --one_shot
INFO: …
```
=> Improve messaging when uploading empty experiments

.github/workflows/ci.yml
Due to our internal build quirk, we have tensorboard/webapp/third_party.
We would like to guard against direct dependency on d3 using lint.
=> CI to detect the direct dependency to "@npm//d3"

tensorboard/webapp/BUILD, tensorboard/webapp/alert/BUILD, tensorboard/webapp/alert/alert_action_test.ts, tensorboard/webapp/alert/types.ts, tensorboard/webapp/alert/views/BUILD, tensorboard/webapp/alert/views/alert_display_snackbar_container.ng.html, tensorboard/webapp/alert/views/alert_display_snackbar_container.scss, tensorboard/webapp/alert/views/alert_display_snackbar_container.ts, tensorboard/webapp/alert/views/alert_snackbar_container.ts, tensorboard/webapp/alert/views/alert_snackbar_test.ts, tensorboard/webapp/app_state.ts
The Alert feature includes a snackbar view, which
renders the alert message. This change adds a 'dismiss'
button to make all alerts close-able on user gesture.
Clients of AlertActionModule may now register a followup
action, which can generate a dispatched action (along
with payload from the store) when the user clicks on the
followup action label.
Googlers, see test sync cl/339525644
Screenshots (hypothetical usage):
=> Support followup actions in alert snackbar

tensorboard/webapp/alert/views/BUILD, tensorboard/webapp/alert/views/alert_display_snackbar_container.ng.html, tensorboard/webapp/alert/views/alert_display_snackbar_container.scss, tensorboard/webapp/alert/views/alert_display_snackbar_container.ts, tensorboard/webapp/util/string.ts, tensorboard/webapp/util/string_test.ts
Diffbase: https://github.com/tensorflow/tensorboard/pull/4257
Note to reviewer: please review only the commits *after* the diffbase.
e.g. all commits after the one titled "unused":
https://github.com/tensorflow/tensorboard/pull/4260/commits/39313de17480687eb24d87326c9dc4638e1db0bf
I made a mistake and should have pushed these branches to the source
repo rather than my own.
In the recently added Alert snackbar view, messages may include
URLs that could be linkified to benefit the user. This change
automatically linkifies URLs within the message.
Googlers, see test sync cl/339528257
=> Linkify text in alert message UI

tensorboard/webapp/experiments/types.ts
Summary:
Google-internal TensorBoard instances want to show some related links in
the UI for the header card: think, “link to logdir in online filesystem
viewer”, or “link to training job health status”. This patch updates the
types to permit the backend to send down such links.
Test Plan:
That TypeScript is still happy suffices.
wchargin-branch: experiments-related-links
=> experiments: add `related_links` field

tensorboard/uploader/upload_tracker.py, tensorboard/uploader/upload_tracker_test.py, tensorboard/uploader/uploader.py, tensorboard/uploader/uploader_subcommand.py, tensorboard/uploader/uploader_subcommand_test.py
Motivation for features / changes
Clarify some uploader messaging when using oneshot.
**Oneshot — Upload an existing but empty directory.**
*  No longer tells the user we will continue to upload new data as it is added to the logdir (oneshot).
*  timestamped "Uploader started" is replaced with "Started scanning" and paired with "Done scanning"
*  Empty directory message language is slightly simplified.
```
$ bazel-bin/tensorboard/tensorboard dev upload --logdir=~/tensorboard-logdirs/emptydir/ --one_shot
New experiment created. View your TensorBoard at: 
https://tensorboard.dev/experiment/peQEJLy7QymNaZwRmK5T2A/
[2020-10-28T12:48:35] Started scanning logdir.
[2020-10-28T12:48:35] Done scanning logdir.
Tensorboard was run in `one_shot` mode, but did not find any uploadable data in the …
```
=> Uploader messaging oneshot

tensorboard/webapp/alert/views/alert_snackbar_module.ts, tensorboard/webapp/runs/BUILD, tensorboard/webapp/runs/runs_module.ts
The recently introduced Alerts ngrx feature offers an affordance
for modules to register alerts. This registers the `fetchRunsFailed`
action to show a message to the user when runs fail to fetch.
In non-Ivy Angular, the entryComponents is required so that
the component factory will be generated, even though it is loaded
on-demand (by snackbar).
Googlers, see sync cl/339774223
=> Show alert on fetch run failures

tensorboard/webapp/metrics/views/main_view/filter_input_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
Current copies are a bit ambiguous as to whether it supports regex or
not. This change makes it a bit more explicit.
=> ui: add 'regex' to the run and tag filter

tensorboard/webapp/plugins/plugins_component.ts, tensorboard/webapp/plugins/plugins_container_test.ts
background: when launching TensorBoard and when inspecting the network
tab on your favorite dev tools, you will notice multiple calls for runs,
tags, and, maybe, scalars. This happened because our Polymer based
dashboards have logic to reload the data on its `ready` lifecycle. On
top of it, on the Angular side, we have a logic to reload the data when
timestamp for plugins list loaded changes for our automatic reloads.
Roughly speaking, there are two ways to solve above problem: (1) make
Angular not invoke reload on new dashboard creation or (2) disable
reload on ready and make sure Angular invokes the reload on the right
condition. In this change, we decided to take the second approach since
we would like to move logic more to the Angular side and we would like
to make it consistent with …
=> bug: prevent double data fetch on stamp

tensorboard/webapp/plugins/npmi/util/filter_annotations.ts, tensorboard/webapp/plugins/npmi/util/filter_annotations_test.ts
The filtering of null values was not working correctly. This has now been fixed.
Fixed the filtering code as well as the test for said code.
bazel test //tensorboard/webapp:karma_test_chromium_local
=> Now Correctly filters out Null Values

tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
Image cards rendered in Time Series may appear blurry, which
can be misleading if the written image is composed of discrete
values-per-pixel. This changes the Time Series image cards to
use the same 'image-rendering' CSS prop as the Image dashboard.
See [plugins/image/tf_image_dashboard/tf-image-loader.ts](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.ts;l=169?q=image-rendering%20pixelated&sq=)
Manually checked in Chrome and Firefox that the image looks
pixelated.
Googlers, see b/32560663, cl/113307097.
(Screenshot of image-rendering: pixelated for above image (below
image is default) in Chrome).
=> [time series] render images as pixelated

tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
After the /scalars_multirun endpoint was introduced, it was
disabled due to b/170675710. Now that the bug is fixed on
the server side, we can re-enable the endpoint call on the
client side.
=> Re-enable scalars multirun endpoint

.github/workflows/ci.yml, tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
We use a layer of indirection when importing d3 that makes sure d3 and
its types are imported correctly in all environments.
This change cleans up a manual typing import.
=> cleanup: remove dangling type import on d3

tensorboard/tools/license_test.sh
Summary:
It should be okay to have files without a license header comment in your
working tree if they’re ignored by Git. Now, it is.
Test Plan:
Create an empty file `tensorboard/foo.txt` and add it to `.gitignore`.
Note that the old license test fails and the new one passes.
wchargin-branch: license-test-gitignore
=> license_test: use `git-grep` to respect gitignore

.github/workflows/ci.yml, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.build_const-0.2.1.bazel, third_party/rust/remote/BUILD.crc-1.8.1.bazel
Summary:
Version 0.7.0 of `cargo-raze` was just released. Some visible changes:
- can now set `[package.metadata.raze]` instead of `[raze]` to avoid a
Cargo warning: <https://github.com/google/cargo-raze/pull/274>
- build files have been renamed and restructured to be more compliant
with Buildifier: <https://github.com/google/cargo-raze/pull/260>
If you have an old version installed, run `cargo install cargo-raze` to
update to the most recent version.
Changes to `third_party/rust/` generated with:
```
(rm -rf third_party/rust/ && cd tensorboard/data/server && cargo raze)
```
The changes to `Cargo.toml` and `third_party/rust/` are independent.
Test Plan:
Run `(cd tensorboard/data/server && cargo test)` and note that the tests
run without an “unused manifest key: raze” warning. Note further …
=> rust: regenerate build with cargo-raze 0.7.0

tensorboard/data/server/BUILD, tensorboard/data/server/lib.rs, tensorboard/data/server/scripted_reader.rs
Summary:
This is a [`Read`][r] implementation (i.e., input stream) that takes a
“script” of responses and yields data from at most one at a time. The
standard library has a [`Cursor`][c] type for much the same purpose, but
we need to simulate files that are being continually written.
[r]: https://doc.rust-lang.org/std/io/trait.Read.html
[c]: https://doc.rust-lang.org/std/io/struct.Cursor.html
Test Plan:
Unit tests included; run `bazel test //tensorboard/data/server/...`.
wchargin-branch: rust-scriptedreader
=> rust: add `ScriptedReader` test helper

tensorboard/compat/proto/config.proto, tensorboard/compat/proto/cpp_shape_inference.proto, tensorboard/compat/proto/saved_object_graph.proto, tensorboard/compat/proto/types.proto
While testing the pip candidate locally for 2.4, it fails on the proto_test.
This change was created by checking out git checkout v2.4.0-rc1
in a TensorFlow local repo, and running
`./tensorboard/compat/proto/update.sh PATH_TO_TENSORFLOW_REPO`.
=> Update protos for TF v2.4.0-rc1

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.byteorder-1.3.4.bazel
Summary:
The [`byteorder`] crate facilitates working with fixed-endian values.
For TFRecords, we need to read little-endian numbers from a data stream.
[`byteorder`]: https://crates.io/crates/byteorder
Test Plan:
It builds: `bazel build //third_party/rust:byteorder`.
wchargin-branch: rust-dep-byteorder
=> rust: add `byteorder` dependency

WORKSPACE
Summary:
We pull in bazelbuild/rules_rust#468 to make it easier to build protos,
while not pulling in bazelbuild/rules_rust#463, because that would
require us to update Bazel to 3.0.0. Happily, the commit that we need
merged immediately before the commit that we don’t want! (Yes, this is a
wee bit precarious; we’re working on the Bazel upgrade: #4277.)
Test Plan:
With both Bazel 2.1.0 and Bazel 3.7.0, everything builds, all tests
pass, and TensorBoard looks okay enough.
wchargin-branch: rules-rust-20201105a
=> workspace: upgrade to newer `rules_rust`

tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts, tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts
During the Polymer 2 to 3 migration, we missed this case in the
hparams dashboard and improperly migrated a property setting
site. Properties with the `notify: true` config do not get Polymer's
implicit `_setPropertyName(value)` method defined. Instead, they must
be set the regular way: `this.propertyName = value`.
Note that, unlike some other properties with `notify: true; readonly: true`,
these *SessionGroup properties may be set from outside the element
via bindings, so they should not use `readonly`.
Manually tested that hovering/clicking over lines in the parallel
coordinates view and dots in the scatter plot properly show the table
of params for the current session group.
Fixes #4309
=> Fix mouse interaction in hparam parallel coords, scatter plot

tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts, tensorboard/webapp/widgets/line_chart_v2/lib/drawable_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts, tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts, tensorboard/webapp/widgets/line_chart_v2/lib/types.ts
This change introduces a concept of a drawable. A drawable is a region
in a view where an implementation can draw shapes using PaintBrush with
coordinate converted data.
The DataDrawable abstract class manages data (and its coordinate system
conversion) and render caching on behalf of a subclass. As a subclass,
you only need to implement `renderFrame` and focus on drawing operations
taking coordinate system converted data and render cache maintenance.
=> line chart: data drawable, a class that renders

tensorboard/data/server/BUILD, tensorboard/data/server/rustboard_core_doc_server.py
Summary:
The Rust Bazel rules provide a `rust_doc` rule for documentation, but it
generates a zipfile with long file paths, which is inconvenient to
consume. This patch adds a simple Werkzeug server to serve from the
generated documentation. It’s compatible with `ibazel run`: just change
a Rust source file and refresh your browser tab to see your changes.
I have a [pending upstream patch for this][upstream], but I’m still
working on it, and it’s on my back burner. In the meantime, this is
helpful for both Rust authors and Rust reviewers on TensorBoard.
[upstream]: https://github.com/bazelbuild/rules_rust/pull/475
Test Plan:
Run `bazel run //tensorboard/data/server:rustboard_core_doc_server` and
navigate to port 6005:
a standard rustdoc output format][ss]
[ss]: …
=> rust: add documentation server

tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/runs/views/runs_table/runs_table_component.ts, tensorboard/webapp/runs/views/runs_table/runs_table_module.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
This change is in preparation for potential virtual scrolling in the
runs table.
About virtual scroll: Run selector can possibly render many runs; in
real user cases, the run selector had to render more than a thousand
runs. While minor in the grand scheme of things, Angular rendering
thousands of elements with nested components can contribute to AFT or
initial meaning paint.
Virtual scroll module does not seemingly support mat-table and it
requires the items to be rendered via cdkVirtualFor. This change, for
now, renders using ngFor which is API compatible with cdkVirtualFor.
=> refactor: runs-table from mat-table to ngFor

RELEASE.md, tensorboard/version.py
Followup to the 2.4.0 release:
- Bump tb-nightly version to 2.5.0a0
- Cherrypick of 2.4.0 relnotes added to RELEASE.md
=> Post-release 2.4.0

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.thiserror-1.0.22.bazel, third_party/rust/remote/BUILD.thiserror-impl-1.0.22.bazel
Summary:
The [`thiserror`] crate facilitates defining structured error types for
libraries. It makes it easy to specify how errors are converted from
other errors (e.g., an underlying I/O error) and how they are converted
to strings for display.
[`thiserror`]: https://crates.io/crates/thiserror
Test Plan:
It builds: `bazel build //third_party/rust:thiserror`.
wchargin-branch: rust-dep-thiserror
=> rust: add `thiserror` dependency

.github/workflows/ci.yml, tensorboard/data/server/DEVELOPMENT.md
Summary:
I didn’t realize that this also updates locks for transitive deps, which
can cause the Raze check to fail as it pulls in new versions.
Test Plan:
At master, running `cargo generate-lockfile` is *not* clean, even though
it passed at submit time, because `tokio` has been updated. Running
`cargo fetch` does not change the lockfile, but does add to it if you
add a new dep (e.g., `anyhow = "1.0.33"`).
wchargin-branch: ci-no-generate-lockfile
=> ci: don’t update Cargo lockfile

tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts
drawable, which is recently introduced, has a renderCache which never
changes. This change adds readonly qualifier to it.
=> cleanup: add readonly to not changing prop

tensorboard/webapp/feature_flag/BUILD, tensorboard/webapp/feature_flag/actions/BUILD, tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts, tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts, tensorboard/webapp/feature_flag/store/BUILD, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_feature_flag_testing.ts
Key-value allows just about anything and it is not that great for
typing. This change removes the key-value part of the FeatureFlag and
forces all apps to strongly type it. We can reintroduce it when we
absolutely need it.
=> refactor: feature flag typing remove key-value

tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
The RunsTableComponent offers a filtering UI with checkboxes
for discrete hparams and metrics. When the filter menu opens,
row items with checkboxes have a small click target, so clicking
the empty space will not toggle.
This expands the clickable region for usability.
Previous click target:
New click target:
While investigating this bug, I went down a rabbit hole of trying
to make the menu item row element (not the mat-checkbox)
be the clickable target.  However, this turned out to fail unless we
provide `clickAction: 'noop'` via DI for the
`MAT_CHECKBOX_DEFAULT_OPTIONS` token. Doing so would
require new injection tokens, since providing options:
`{clickAction: 'noop'}` overrides the color/ThemePalette property
on checkboxes, and also requires splitting out the hparam checkboxes
from the …
=> bug: widen click target for hparam/metric filter checkboxes

tensorboard/webapp/feature_flag/actions/BUILD
feature_flags action requires types but BUILD file is lacking the
dependency
=> sync: fix build

tensorboard/webapp/feature_flag/effects/BUILD, tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
This change adds a new unconnected flag `fastChart`.  The flag is intended to used for enabling
new GPU based line chart in time series in the future.
=> feat: add an ability to enable gpu line chart

tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
This is a recent regression from previous mat-table implementation where
we used to have the data-id attribute per row.
This regression is blocking the sync which is currently relying on the data
attribute.
=> sync: add data-id to runs-table for testability

tensorboard/webapp/BUILD, tensorboard/webapp/metrics/BUILD, tensorboard/webapp/metrics/types.ts, tensorboard/webapp/routes/BUILD, tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts, tensorboard/webapp/routes/core_deeplink_provider_types.ts, tensorboard/webapp/selectors.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
This change reads the state from the store and use our DeepLinkProvider
to add the query parameter to the URL.
Note that no navigation will cause the state to change since we want to
keep it immutable.
=> infra: persist experimentalPlugin to URL

tensorboard/webapp/feature_flag/effects/BUILD, tensorboard/webapp/webapp_data_source/BUILD
With the recent changes in the feature flag typing and because of inadequate strict_deps checking,
our sync is blocked again. This change corrects the dependency.
This time, we have tested the sync manually to make sure it no longer is borked (cl/342383238).
=> sync: fix strict_deps on feature_flag_testing

tensorboard/data/server/BUILD, tensorboard/data/server/gen_protos_tool.rs, tensorboard/data/server/lib.rs, tensorboard/data/server/tensorboard.data.pb.rs
Summary:
In #4314, we added a proto definition for the data provider interface.
We now generate the corresponding Rust bindings.
Generated with `bazel run //tensorboard/data/server:update_protos`.
Test Plan:
Run the `:rustboard_core_doc_server`, and note that the `proto` package
has bindings for both the normal messages and the gRPC service.
wchargin-branch: rust-data-protos
=> rust: build `tensorboard.data` protos

tensorboard/backend/http_util.py, tensorboard/backend/http_util_test.py, tensorboard/backend/security_validator.py
Hi! I'm a dev working on adding TensorBoard support to the [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) extensions for [VS Code](https://code.visualstudio.com/). We'd like to enable users to view TensorBoard inline in our[ Jupyter notebook experience within VS Code](https://code.visualstudio.com/docs/python/jupyter-support).
Currently this doesn't work because the `frame-ancestors *` directive prevents VS Code from framing TensorBoard. This is because VS Code is an Electron application, and Electron appears to be unable to frame websites which set `frame-ancestors *` in its response headers: https://github.com/electron/electron/issues/26369
This PR essentially reverses …
=> Remove `frame-ancestors *` CSP directive

tensorboard/data/proto/data_provider.proto, tensorboard/data/server/tensorboard.data.pb.rs
Summary:
Suggested by @nfelt on #4314. This hits a flexibility/usability middle
ground between “omitted messages are implied to be empty” (which makes
it easy to accidentally set `num_points: 0` and wonder why the result is
empty) and “you may not set `num_points: 0`” (which excludes legitimate
use cases).
Test Plan:
None needed; this is just a doc update for now, as the service does not
yet have any clients or servers.
wchargin-branch: data-downsample-required
=> data: make `downsample` required, but permit zero

tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
Moved the Scale interface definition to the type so dependents do
not have to load the implementation and keep it private to the `lib`.
=> line chart: refactor to move interface for Scale to types file

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel
Summary:
The [`tempfile`] crate is the standard Rust library for handling
temporary files and directories. We anticipate using this for tests that
want to set up a directory of event files.
[`tempfile`]: https://crates.io/crates/tempfile
Test Plan:
It builds: `bazel build //third_party/rust:tempfile`.
wchargin-branch: rust-dep-tempfile
=> rust: add `tempfile` dependency

tensorboard/data/server/Cargo.toml, third_party/rust/remote/BUILD.libc-0.2.80.bazel
Summary:
When setting up the transitive dep on `libc` in #4316, I had originally
passed `--cfg=libc_align`, because that fixed the build for me and on
CI, and I couldn’t figure out the right cross-platform fix. But @faern
[helpfully points out that we just need to run the build script][1],
which detects the OS and Rust compiler version to determine the
appropriate flags. Bazel `rules_rust` can handle this, if we just ask.
(I should have followed my own `DEVELOPMENT.md` suggestions!)
[1]: https://github.com/rust-lang/socket2-rs/issues/130#issuecomment-726741410
Test Plan:
It still builds—`bazel build @raze__libc__0_2_80//:libc`—and the demo
server still works and accepts requests following #4318’s test plan.
wchargin-branch: rust-libc-gen-buildrs
=> rust: run `libc` build script

tensorboard/webapp/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD, tensorboard/webapp/widgets/line_chart_v2/sub_view/axis_formatter.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/axis_formatter_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/chart_view_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/sub_view_module.ts
Sub-view is a region in a chart that allows content rendering or adding
interactivity. In this instance, we are writing these sub-views in
Angular for drawing axis and grid.
This design choice absolves us from inventing our own layout system
within canvas while allowing us to add interactivity in line chart and
axis in the future.
Other implicit pros:
- do not have to render text in WebGL which is a bit challenging
- interactivity, which occurs in the main thread, does not have to be
propagated to the worker based canvas renderer.
=> line chart: sub view for axis and grid

tensorboard/data/server/BUILD, tensorboard/data/server/lib.rs, tensorboard/data/server/reservoir.rs, tensorboard/data/server/types.rs
Summary:
We’d defined a `Step` [newtype] in the `reservoir` module, but that type
will be useful more broadly. We thus move it into a new `types` module,
and define `WallTime` and `Tag` siblings, which we’ll need shortly.
[newtype]: https://doc.rust-lang.org/rust-by-example/generics/new_types.html
Test Plan:
Most behavior is just `#[derive]`d; unit tests included for the rest.
wchargin-branch: rust-types-module
=> rust: create `types` module with primitives like `Step`

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
This change trivially adds a selector to already existing state in the
feature flag reducer. With this change, we are able to discern whether
user manually enabled the faster line chart implementation.
=> feat: selector to read fastChart feature flag

tensorboard/data/server/BUILD, tensorboard/data/server/event_file.rs, tensorboard/data/server/masked_crc.rs, tensorboard/data/server/tf_record.rs
Summary:
Our errors now have nice string formatting, easier `From` conversions,
and `std::error::Error` implementations.
Test Plan:
Included some tests for the `Display` implementations. They’re often not
necessary—one benefit of deriving traits is that you can be confident in
the implementation without manually testing it. But sometimes, if the
format string is non-trivial, it can be nice to actually see the full
text written out.
wchargin-branch: rust-use-thiserror
=> rust: use `thiserror` for error types

tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
This change builds on top of already existing feature of deep linking to
persist a state in the feature flag reducer for convenience of a user.
With this change, when launching tensorboard with `?fastChart=true`, it
will stay in the URL across navigations.
=> feat: persist fastChart feature flag to url

.github/workflows/ci.yml, third_party/rust.bzl
Summary:
Rust 1.48 is out today! I’ve been eagerly awaiting one feature in
particular: intra-doc links. As of this release of rustdoc, you can link
to other doc items as Markdown links:
```markdown
Each reservoir has an associated [`Basin`].
This contains a [`summary::value::Value`], which represents the
underlying `oneof value` field (a `simple_value`, `tensor`, etc.). It is
not to be confused with a [`summary::Value`], which is….
[`summary::Value`]: `pb::summary::Value`
[`summary::value::Value`]: `pb::summary::value::Value`
```
Full [release announcement here][announce].
If you have local toolchains installed, you can update them by running
`rustup update stable`.
[announce]: https://blog.rust-lang.org/2020/11/19/Rust-1.48.html
Test Plan:
I’ve already been using this syntax in our docs, …
=> rust: upgrade to Rust 1.48.0

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.same-file-1.0.6.bazel, third_party/rust/remote/BUILD.walkdir-2.3.1.bazel
Summary:
The [`walkdir`] crate facilitates recursively walking a directory.
We need this to find all event files under a log directory.
[`walkdir`]: https://crates.io/crates/walkdir
Test Plan:
It builds: `bazel build //third_party/rust:walkdir`.
wchargin-branch: rust-dep-walkdir
=> rust: add `walkdir` dependency

tensorboard/plugins/graph/BUILD, tensorboard/plugins/graph/graph_util.py, tensorboard/plugins/graph/graph_util_test.py, tensorboard/plugins/graph/graphs_plugin.py
Previously, graph plugin combined multiple graphs traced by creating one
monolith of a GraphDef. In doing so, we checked whether, for example,
node names are unique to detect a case when our graph vis can result in
faulty UI.
To alleviate the poor UX, we decided, instead, to duplicate all nodes in
one giant GraphDef container  prefixing all names. While this creates
some bloat, (1) users should see the confusing error less and (2)
combined graphs make it very clear that we have traced multiple graphs.
=> feat: combine graph by prefixing with unique name

tensorboard/webapp/BUILD, tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/testing.ts, tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_module.ts
This change adds the Angular entry point for rendering a line chart using the
GPU line chart framework; it composes sub views and the charting library we've
been working on.
The major complexity lies in two aspects:
- detecting condition in which it should reset the viewBox
- making the minimal imperative API calls to the chart library depending on prop
changed.
=> line chart: Angular entry point to line chart

.github/workflows/ci.yml, tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
This change disallows direct usage of ng_module and fixes one regression that we incurred recently.
We require indirection since in newer version of the rules_nodejs, they deprecated ng_module and 
dependency upgrade causes larger change than intended when there is no such indirection exists.
=> infra: error on dep on ng_module

tensorboard/plugins/graph/graph_util_test.py
lint tool suggested using `Parse` instead of `Merge` for creating protobuf
from a txtproto. This change simply mechanically changes the API we use.
=> cleanup: use Parse instead of Merge

tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/demo.html, tensorboard/webapp/widgets/line_chart_v2/demo_main.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD, tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_module.ts
This change adds a demo module that tests integration of the line chart
component. After integrating all the features into time series
dashboard, the module will be removed.
Since it is a temporary demo change, we are not introducing tests.
=> line chart: temporarily add demo component

.travis.yml, WORKSPACE, ci/bazelrc
This change disables large part of CI so we can safely populate the
Travis cache to unblock other infrastructural upgrade.
Note that there are total of 4 PRs to be submitted.
=> infra: upgrade Bazel to 3.7.0 (1 of 4)

tensorboard/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
When the demo was exercised, it revealed several issues with the
GpuLineChart.
Issues are:
- worker resource files are not served by the app
- requestAnimationFrame used by chart.ts in context of worker misses
reference to `window` and causes invocation error as is.
- refactored the "MainThreadChart" to "ChartImpl" since it is not
meant to only be used in the "main thread"
=> line chart: fix issues with line chart

tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.ts
Histogram reverse sorts by step number and, previously, the first step
was the darkest while the last step was the faintest. While this works
for most colors, it does not work well for gray based colors.
Now, it is true that we have a different set of color palettes in time
series and it is less of the problem but now that we let users tweak the
run color, it is easy to imagine user picked color being a problem in
the histograms.
To alleviate the problem, we gave the most important step, the last one,
the most salient color.
=> feat: reverse fill color for histograms

tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/data_transformer.ts, tensorboard/webapp/widgets/line_chart_v2/data_transformer_test.ts
This change ports logic in the vz_line_chart for our consumption in new
GpuLineChart.
Future integration note: unlike vz_line_chart, smoothing is not built-in
to the line chart; previous pattern made the line chart more logic-ful
and made it harder to adopt other smoothing strategies or data
transformation logic. Instead, we decided to have a notion of `aux` or
auxiliary data series and let the consumer pass the smoothed data
series.
=> line chart: add utility for smoothing line chart

.github/workflows/ci.yml, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
ng_module will change shortly and we require some indirection for our
convenience. This change makes changes to the debugger_v2 code and
change our CI lint check to guard against any usages of ng_module.
=> cleanup: debugger to use tf_ng_module

tensorboard/data/server/BUILD, tensorboard/data/server/lib.rs, tensorboard/data/server/run.rs, tensorboard/data/server/writer.rs
Summary:
The run loader tests write sample events to files. These utilities will
also be useful for testing the logdir loader, so we factor them out into
a test-only helper module.
This uses the *[extension trait]* pattern: we define a new interface and
then implement it for _all_ other writers. This way, as long as you have
`SummaryWriteExt` in scope, you can call `.write_event(...)` on any
implementation of `Write`, like a file, a cursor, or a buffered writer.
Extension traits aren’t special or magic; they’re just a useful
consequence of how traits work in Rust.
[extension trait]: https://rust-lang.github.io/rfcs/0445-extension-trait-conventions.html
Test Plan:
Unit tests for the run loader updated to use the new helpers, which
themselves are also tested. …
=> rust: extract test utils for writing event files

tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/types.ts
lib/public_types.ts is not really meant to be imported by consumer of
the line chart as (1) peeking into `lib` folder is a bit messy and (2)
it exports more types than what consumers really need.
The new `types` module is provided as part of the line_chart_v2
dependency and it only contains the types that consumers would need.
=> line chart: export types for consumer of line chart

tensorboard/data/server/DEVELOPMENT.md
Summary:
This includes a valid example invocation, plus some miscellaneous
advice, especially for Googlers.
wchargin-branch: rust-grpc-cli-dev-guide
=> rust: add `grpc_cli` tips to DEVELOPMENT.md

tensorboard/defs/web.bzl
After our build system upgrade, we no longer use tf_web_library to build
the TypeScript files. Instead, we use the rules based on rules_nodejs
and ts_library.
Test CL: cl/344187444
=> cleanup: remove TypeScript build from tf_web_library

tensorboard/components/tensor_widget/BUILD, tensorboard/components/tensor_widget/colormap-test.ts, tensorboard/components/tensor_widget/dtype-utils-test.ts, tensorboard/components/tensor_widget/selection-test.ts, tensorboard/components/tensor_widget/shape-utils-test.ts, tensorboard/components/tensor_widget/string-utils-test.ts
Angular works the best when using jasmine and most of our codebase
already adopted jasmine. To avoid using multiple libraries, we decided
to refactor existing tests into jasmine.
=> cleanup: refactor chai/mocha test to jasmine

package.json
package.json had requirejs in both devDep and dep. `yarn` is supposed to autoclean
but it does not seem to do a great job there.
=> cleanup: remove duplicate requirejs dep

tensorboard/webapp/index_polymer3.uninlined.html
Summary:
Since TensorBoard is rendered entirely client-side with Angular and
Polymer, the screen is entirely blank when JavaScript is disabled. This
patch adds a simple “please enable JavaScript” `<noscript>` message.
Fixes #4401.
Test Plan:
In both Chrome and Firefox, the message appears when JavaScript is
disabled but not otherwise. It’s properly centered at wide window sizes
and doesn’t create a horizontal scrollbar at narrow ones. Looks like:
JavaScript”, followed by a message, “Please enable JavaScript and
reload this page.” Both are rendered in Roboto, and appear to be
centered in the screenshot.][ss]
[ss]: https://user-images.githubusercontent.com/4317806/100648627-0b6d7b00-32f6-11eb-9781-68af70d7cb1f.png
wchargin-branch: noscript-message
=> webapp: add noscript message

tensorboard/data/server/BUILD, tensorboard/data/server/main.rs
Summary:
This patch outfits `//tensorboard/data/server` with a nice CLI, courtesy
of [`clap`]. The flags are a subset of the main TensorBoard flags, but
with kebab-case rather than snake-case (per everyone-other-than-Google
style, via `clap` defaults). Since we now accept a `--port` argument,
which may be `0`, we also print the port to which the server is bound.
The `clap` approach to argument parsing is “define a struct all of whose
fields implement `FromStr`, then mark it `#[derive(Clap)]` to generate
an argument parser”. This is great on both the static typing and runtime
performance fronts. To add more arguments, we just add more fields to
`struct Opts`. See <https://docs.rs/clap/3.0.0-beta.2> for details (this
syntax is introduced in `clap` v3.x, which is still in beta).
[`clap`]: …
=> rust: add nice command-line argument parsing

tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Currently, we are making things "brighter" in rgb color space which does
not look correct. Since brightness or opacity is better represented via
light in HSL, we use the hsl color space.
=> line chart: adjust opacity in webgl using HSL

tensorboard/manager.py
Summary:
When the `%tensorboard` cell magic is invoked, we compute a cache key
for the “hermetic environment”, primarily args to `%tensorboard` and the
working directory. We first check whether any running TensorBoard
instances match that cache key, and launch a new instance if none do.
But then, while polling for the new instance to have launched, we had a
different matching criterion, checking for a process ID match instead of
a cache key match.
The idea was that “is this TensorBoard instance’s PID equal to the PID
of the subprocess that we just spawned?” would be a more reliable check.
But on Windows ((╯°□°）╯︵ ┻━┻) this is not the case, presumably because
the `tensorboard` console script has some kind of wrapper process in
certain versions of Python. This manifested as “`%tensorboard` …
=> notebook: don’t filter polled instances by PID

.git-blame-ignore-revs
Summary:
From #4409; see also #4406 for discussion.
Test Plan:
The output of `git blame tensorboard/backend/application.py` no longer
has any lines blaming to either of the commits in question.
wchargin-branch: black-20.8b1-unblame
=> blame: ignore Black v20.8b1 and py27/py35 reformattings

tensorboard/data/server/main.rs
Summary:
If `tensorboard` is to launch RustBoard as a subprocess rather than
relying on the user to launch it concurrently, then we should try hard
not to leave around a zombie server. An easy solution is an `atexit`
handler in Python TensorBoard, but this doesn’t handle the case when
TensorBoard crashes or gets SIGTERMed. On Linux, we can be notified when
our parent dies by setting the parent-death signal (`man 2 prctl`), but
this isn’t portable. On portable Unix, the child can poll its PPID to
see when it changes to `1` or the PID of some subreaper, but this isn’t
portable to Windows, which doesn’t update PPID when the parent dies.
Windows is not my strong suit, but some web searching didn’t turn up an
easy and clean solution portable to both Windows and Unix (any Windows
internals like …
=> rust: add option to kill server at stdin EOF

tensorboard/manager.py
Summary:
CI skew between #4409 and #4407 that I didn’t realize.
Test Plan:
GitHub CI suffices.
wchargin-branch: black-reformat-manager
=> black: reformat `tensorboard/manager.py`

tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
Also, this change improves testing around `niceDomain` and we assert on
non-positive value clipping.
This change partially address #4362 for the new gpu line chart. We will later
integrate the new scale to the legacy vz_line_chart.
=> line chart: fix the nice domain for small constant

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/store_module.ts
This modularization allows other applications to provide the crucial set
up code without importing the entire `AppModule`.
=> refactor: extract store provider to a separate module

tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
The smoothing slider setting affects line charts. In the Scalars
dashboard, the maximum value has traditionally been 0.999, not
1.0. The Time Series dashboard allows the slider to go all the way
to 1, which "flattens the curve" onto the x-axis, often much less
meaningful than a "close to 1" number, which still shows the
general shape of the curves.
This updates the Time Series' scalar cards to be use a max
smoothing of 0.99 when dragging the slider, and 0.999 when
entering a value in the input field.
Before:
After:
=> Limit max scalar smoothing to 0.99 / 0.999

tensorboard/webapp/widgets/dropdown/dropdown_component.ts
This introduces a new field on the `DropdownOption` public interface
to let clients of the `<tb-dropdown>` component specify options that
are non-interactable.
=> ui: allow disabled dropdown options

tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss, tensorboard/webapp/widgets/dropdown/dropdown_component.scss
The Time Series settings panel uses dropdowns and text
input fields. This fixes 2 issues:
- When the dropdown is focused, there is no visual indication
- In Firefox, the smoothing input flows offscreen
Before
After
=> ui: fix styles in dropdowns, smoothing input

tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts
Internally, due to conformance reasons, we cannot support a relative
path for the worker resource. As such, we are now modifying the contract
and accompany the change with a check.
=> line chart: improve worker doc and check for assumption

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts
This change backports some logic from vz-chart-helpers to ignore y
dimension outliers when computing the default viewBox.
=> line chart: implement ignoreOutlier

tensorboard/plugins/mesh/mesh_plugin.py, tensorboard/plugins/mesh/mesh_plugin_test.py
Summary:
The mesh plugin’s `is_active` method had a hard dependency on the event
multiplexer, which is not always available, as `TBContext` documents.
In fact, the entire `is_active` method can just be `return False`, since
TensorBoard core will treat the `"mesh"` plugin as active when `"mesh"`
data is available, and that’s all that it was checking, anyway.
Test Plan:
The mesh plugin appears active in a logdir with mesh data and inactive
in one without it, and when launching with `--load_fast` (and thus no
multiplexer) there’s no longer any log spam about “Plugin listing:
is_active() for mesh failed”.
wchargin-branch: mesh-isactive
=> mesh: fix `is_active` without multiplexer

tensorboard/data/server/server.rs
Summary:
In #4399, we decided to recommend `..Default::default()` on struct
initializers for protos whose source of truth is not in our repo. This
patch removes trivial `..Default::default()`s from struct initializers
for `tensorboard.data` protos, which *do* live in our repo. We still use
it sometimes: e.g., some requests have a `run_tag_filter` field that we
don’t always care to set.
This patch will make it harder to add new fields to these protos, but
makes the code a bit easier to read in the meantime.
Test Plan:
Compilation suffices; unit tests are a nice sanity check.
wchargin-branch: rust-remove-default-frus
=> rust: remove some `..Default::default()`s

.github/workflows/ci.yml
Summary:
This extends our current GitHub Actions CI workflow to run nightly at
05:00 PST (06:00 PDT, 13:00 UTC). The [docs for scheduled events][1]
indicate that such a job will run on the default (master) branch. This
job should run with write access to the build cache.
[1]: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
Test Plan:
Note that the workflow parses and normal CI still runs on this job.
We’ll wait for tomorrow to see if it actually runs.
wchargin-branch: ci-gh-nightly
=> ci: add nightly scheduled GitHub Actions job

tensorboard/data/provider.py, tensorboard/plugins/metrics/metrics_plugin.py
Summary:
Not all data providers support tensors and blob sequences. The methods
are optional in the `DataProvider` interface, and (e.g.) the gRPC data
provider does not yet implement them, nor does the RustBoard server.
This patch teaches the time series dashboard to gracefully omit image
and histogram data if the needed data classes aren’t available.
Test Plan:
Point TensorBoard at an MNIST dataset with all three kinds of data, and
note that scalars appear if `--load_fast` is passed, and all data
appears otherwise. Prior to this patch, the requests would 500 under
`--load_fast`, and so nothing would be displayed at all.
wchargin-branch: metrics-degrade-tensors-blobs
=> metrics: gracefully degrade without tensors/blobs

tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts
Illegal value is defined by a scale where, in some situation, we can
support all finite values while, in other cases, we can only support
positive finite numbers.
This change takes predicate on the extent calculation code and properly
calculate extent of log scale.
=> line chart: calc extent without illegal values

tensorboard/data/server/cli.rs
Summary:
Previously, the data server defaulted to host `::0`, the IPv6 wildcard
address and analogue of `0.0.0.0`, ~a.k.a. `--bind_all`. But we can
safely restrict this to just `::1`, the loopback address and analogue of
`127.0.0.1`, allowing localhost connections only. @psybuzz reports that
macOS shows a security dialog about incoming connections to the data
server, and that this fixes it.
Test Plan:
Running `tensorboard --load_fast` still works fine, since TensorBoard is
connecting to a data server running on the same machine.
wchargin-branch: rust-default-bind-loopback
=> rust: bind server to `::1` by default

tensorboard/data/server/run.rs
Summary:
We don’t yet apply data-compat conversions to tensor and blob type
summaries, so we usually don’t see `data_class` set to anything other
than “unknown” or “scalar”. But @psybuzz points out in #4436 that nPMI
data is explicitly `DATA_CLASS_TENSOR`, which triggers a panic in the
data server. This patch replaces that panic with a warning. Of course,
the warning will go away entirely when tensor support is implemented;
for now, this just prevents crashing, which is nice.
Test Plan:
Run `//tensorboard/plugins/npmi:npmi_demo` to get test data if you don’t
have it already, then point the server at that logdir and note that it
successfully finishes a load cycle:
```
$ bazel run //tensorboard/data/server -- --logdir /tmp/npmi_demo -v
listening on [::]:6806
[2020-12-09T06:52:29Z INFO …
```
=> rust: fix panic when reading explicit tensors/blobs

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Previously, we were trying to render NaN values on the line chart
interactive layer (circle to indicate where the tooltip is at). This
caused SVG to complain and populate error messages on the console.
=> line chart: omit nan from interactive view

tensorboard/webapp/feature_flag/feature_flag_module.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts
Code cleanup.
Use vscode to rename FEAUTURE_FLAG_FEATURE_KEY to FEATURE_FLAG_FEATURE_KEY.
Ran server after rename and ensured that tensorboardColab query parameter still impacted behavior of the scalars dashboard.
=> Rename FEAUTURE_FLAG_FEATURE_KEY to FEATURE_FLAG_FEATURE_KEY.

.github/workflows/ci.yml
Summary:
Previously, we had separate linting jobs for Python, docs, build, and
miscellaneous checks. Now that we have our main heavyweight build on
GitHub Actions as well (#2953), we spend more time in actions overall,
and queuing behavior becomes more important. This patch collapses some
of those jobs together.
I haven’t actually run into any issues here. This is just an ounce of
prevention.
The advantage is that we spin up fewer VMs and thus use our resources
more efficiently. The disadvantage is that we fail faster: e.g., an
error in Python style will now prevent ipynb lints from running. This
seems fine to me, since the checks are still fast and we don’t usually
have large Python changes and large docs changes in the same PR. If it’s
a problem, we could probably rig it to run all …
=> ci: collapse some build jobs

tensorboard/BUILD, tensorboard/plugins/metrics/BUILD, tensorboard/plugins/scalar/BUILD, tensorboard/summary/BUILD
This makes our `//tensorboard:expect_tensorflow_installed` placeholder target (reflecting a dep on the TF pip package from the virtualenv) include a dep on `//tensorboard/summary:tf_summary`.
This fixes "for once and for all" the problem wherein code within TensorBoard that depends on TF but not on our `tf_summary` shim logic prints the annoying `Limited tf.compat.v2.summary API due to missing TensorBoard installation.` message, and then fails to actually include the `tf.compat.v2.summary.scalar` endpoint.  Consequently we can remove ad-hoc additions of `tf_summary` deps from a few places.
This arrangement is also a better analog to the internal situation.
Confirmed that this syncs internally with a copybara change - see cl/346894347.
=> make TF deps include //tensorboard/summary:tf_summary

tensorboard/plugins/graph/graphs_plugin.py
Summary:
The graph plugin still defaults to the multiplexer code path, since not
all functionality is implemented in the data provide code path (only run
graphs are implemented). But when a data provider is available and a
multiplexer is not, it should still try to use the data provider. Now,
it does so. This fixes a failure in `is_active`, which previously tried
to call `PluginRunToTagToContent` on `None`.
Test Plan:
Run TensorBoard with `--load_fast` (causing it to provide a gRPC data
provider but no multiplexer) and launch the web server to trigger a
request to `/plugins_listing`. Note that this no longer prints an error
that “is_active() for graphs failed”.
wchargin-branch: graph-data-provider-fallback
=> graph: use data provider if no multiplexer available

tensorboard/webapp/core/store/core_initial_state_provider.ts
Remove an unnecessary TypeScript type cast of the initial CoreState. Could lead to obscuring future problems that the compiler would normally catch.
Remove unnecessary TypeScript type cast.
Ran tests. Launched UI and ensured Scalars dashboard loads.
=> Remove unnecessary type cast to CoreState.

tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts, tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts, tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
In the near future we will want feature flag default values to be customizable by different flavors of Tensorboard (TensorBoard.dev vs OSS TensorBoard vs TensorBoard.corp).
Currently default values are, in practice, set by the QueryParamsFeatureFlagDataSource. This is not the mechanism that we want to use to specify default values so we remove this responsibility out of the DataSource.
* Change TBFeatureFlagDataSource interface so that a Partial<FeatureFlags> can be returned. 
* QueryParamsFeatureFlagDataSource returns Partial<FeatureFlags> only if corresponding query parameter was specified on URL.
* Reducers ignore unspecified FeatureFlag properties from the data source and instead fall back to those already in …
=> Do not specify default values in QueryParamsFeatureFlagDataSource. Rely on initialState defaults instead.

tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
This change adds a renderer's ability to draw circle and triangles.
Use cases:
- We need to draw triangles for NaN values in the line chart
- We need to draw circles to denote length 1 scalar points
This change:
- refactors the line drawer to share the common material/style
modification code
What will be done:
- the direction of the triangle shape needs to be a function of
coordinator or its y-direction. Will address it in a follow up.
=> line chart: add circle and triangle drawer

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
In FF and Chrome, block element under grid takes the full height with
`height: 100%` but it seems to behave a bit differently with Safari.
This change changes block to flex which fixes short axes, small grid,
and weird interactivity.
=> line chart: fix layout in Safari

tensorboard/webapp/widgets/source_code/BUILD, tensorboard/webapp/widgets/source_code/source_code_component.ts, tensorboard/webapp/widgets/source_code/source_code_container.ts
This updates a few type annotations in the SourceCode component,
mainly relating to the use of `monaco`. Now, Monaco editor uses are
typechecked.
Test plan:
Manually changed an instance of `this.monaco.editor.create` to
`this.monaco.editor.create2` and saw that `bazel build tensorboard`
fails.
Googlers, see associated Copybara change: cl/347056094.
=> chore: typecheck 'monaco' types in source code component

tensorboard/data/server/BUILD, tensorboard/data/server/Cargo.toml, tensorboard/data/server/bench.rs
Summary:
A new `bench` binary takes a `--logdir` parameter, loads the logdir to
completion, and then exits. This should report similar times to those
given by the info logs on the server itself, but is useful as a
standalone target because it exits upon completion. This makes it easier
to use with tools like `time(1)` or `hyperfine(1)` for automated studies
of performance over time.
I looked into using [`criterion`], which provides nice statistical
analysis over time. It works as advertised, but we want to be able to
point this benchmark at arbitrary logdirs and use it as a benchmarking
*tool* rather than just a fixed benchmark of a function. Same
justification for not using `cargo bench`.
The difference between the time reported in the `info!` logs and the
process runtime as reported by …
=> rust: add logdir loading benchmark

tensorboard/webapp/widgets/source_code/BUILD, tensorboard/webapp/widgets/source_code/editor_options.ts, tensorboard/webapp/widgets/source_code/source_code_component.ng.html, tensorboard/webapp/widgets/source_code/source_code_component.ts, tensorboard/webapp/widgets/source_code/source_code_container_test.ts, tensorboard/webapp/widgets/source_code/source_code_diff_component.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts, tensorboard/webapp/widgets/source_code/source_code_module.ts, tensorboard/webapp/widgets/source_code/testing.ts
The existing SourceCode components are used in the Debugger V2 dashboard
to provide a readonly view of source code. This change branches the
NgComponent into a variant used solely for rendering a diff view. Source code
diffs may render 2 text contents side-by-side or as 1 unified inline diff.
Drive-by: migrated the existing (non-diff) SourceCode component to also
use the ResizeDetector.
Manually tested that resizing the Debugger V2 plugin still works:
Notes:
Why isn't this just part of the existing SourceCodeComponent?
The underlying Monaco classes are different. While they share common
functionality (autoresize, scrolling text into view, selecting regions [1]), the
2 subclasses have some fundamental differences.
- DiffEditor manages 2 source code models, each of which can have its
own …
=> Introduce a source code diff view component

tensorboard/components/vz_line_chart2/BUILD, tensorboard/components/vz_line_chart2/linear-scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
We are in midst of working on the new version of the line chart. In
doing so, we rewrote a scale library with a bit more tests.
This change integrates the new scale library so small constant values do
not result (e.g., 0.05) in  [-1, 1] domain.
Fixes #4362.
=> bug: apply new scale niceDomain to vz-line-chart

tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts, tensorboard/webapp/widgets/line_chart_v2/lib/coordinator_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/threejs_coordinator.ts
Previously, we had a camera coordinate system where we had a fixed camera
view point. This was great because irrespective of the actual DOM size,
we could keep the objects position static. However, this approach has a
major problem. Now that we want to render shapes like triangle and
circle, geometry that is defined in the camera coordinate system has to
account for mismatch in camera coordinate aspect ratio vs. DOM camera
coordinate aspect ratio.
We want circle that is not an oval in browser pixel location. To do
that, when creating a geometry in the camera coordinates, we need to
account for discrepancy in aspect ratio, which generally is harder than
just matching the camera view point to that of the DOM size. As such,
this change removes the camera coordinate system separate from DOM …
=> line chart: make threejs coordinator match DOM size

tensorboard/webapp/metrics/views/main_view/BUILD, tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html, tensorboard/webapp/metrics/views/main_view/main_view_module.ts
The new line chart uses cdk overlay to render the tooltip. It currently
has three strategies it can take when scrolled in the scroll container.
Strategies aside, we need a way for the overlay to be able to detect a
scroll event in a scroll container and adding `cdkScrollable` is one way
to register a scrollable container to the cdk library.
=> line chart: make sure tooltip repositions when scrolled

tensorboard/webapp/feature_flag/feature_flag_module.ts, tensorboard/webapp/feature_flag/store/BUILD, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts
Some instances of TensorBoard (notably, TensorBoard.dev), might want to provide different default
values for feature flags.
Define injection token that allows us to provide and consume a StoreConfig<FeatureFlagState>. StoreConfig
allows an initialState value to be specified for the state.
Provide a fallback StoreConfig that simply defines initialState to be. . . the initialState we already use.
* Load local TensorBoard and ensure Scalars and TimeSeries dashboards successfully load scalar data.
* Test that tensorboardColab query parameter impacts how TimeSeries dashboard loads scalar data.
* Patch changes into internal repo and modify TensorBoard.dev …
=> Provide and consume FeatureFlagState StoreConfig, allowing other Tensorboards to override default feature flag values.

tensorboard/plugins/graph/BUILD, tensorboard/plugins/graph/graphs_demo.py
Summary:
The graphs plugin is most frequently used to visualize run graphs, but
supports more than that. This patch adds a demo that generates data for
all the data types that the graphs plugin currently supports.
Test Plan:
Run `bazel run //tensorboard/plugins/graph:graphs_demo`, then point
TensorBoard at `/tmp/graphs_demo`. Open the graphs dashboard and inspect
the contents of the `/data/plugin/graphs/info` response. Note that it
contains:
- tags with op graph but no other data
- …via Keras (`keras/train:batch_2`)
- …via trace (`profile:prof_g`)
- tags with both profile and op graphs (`profile:prof_f`)
- tags with conceptual graph only (`keras/train:keras`)
- runs with `run_graph` set to `true` (`tagged`)
- tags with profile data only, via `RunMetadata` (`tagged:step_0000`) …
=> graph: add demo for exotic graph types

tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts, tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts, tensorboard/webapp/widgets/line_chart_v2/lib/testing.ts
This change adds the feature of vz-line-chart of rendering null values
as triangles.
Business logic:
- for non-first NaNs: carry the y value from the last non-NaN value
- for starting NaNs with non-NaN values in the series: assign y values
from the first non-NaN value.
- for all NaNs: assign 0 to y.
=> line chart: draw NaN with triangle

tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD, tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts, tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/plugins/BUILD, tensorboard/webapp/plugins/plugins_component.ng.html, tensorboard/webapp/plugins/plugins_component.ts, tensorboard/webapp/plugins/plugins_container.ts, tensorboard/webapp/plugins/plugins_container_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We want to be able to use the FeatureFlags mechanism to modify behavior in dashboards.
The Scalars dashboard, for example, could use two FeatureFlags:
* `isColab`, which maps to the `tensorboardColab`  query parameter. The Scalars dashboard already independently
reads this query parameter but it is more consistent to get it from FeatureFlags.
* `scalarsBatchSize`, which is new functionality. TensorBoard.dev will use FeatureFlags to modify the /scalars_multirun
batch size.
* plugins_component on Angular side, which manages dashboard creation, now waits for FeatureFlags to be
loaded before loading dashboards. It passes the featureFlags property of each dashboard, which can choose to
use or ignore it as a polymer …
=> Pass FeatureFlags to CUSTOM_ELEMENT dashboards; use in Scalars dashboard for inColab and scalarsBatchSize.

tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series_test.ts
We premature optimized thinking that we should allocate less memory
using Float32Array where possible instead of Float64Array. The thing
is, with 32 bit precision, it is not possible to represent the date
serialized to integer.
This changes the data transfer layer only. We will diagnose and change
other places where we use Float32Array as needed (for instance, WebGL
uses 32 bit precision and threejs internally uses Float32Array a lot.
Having more precision does not help in all cases)
=> line chart: transfer data with 64 bit precision

tensorboard/plugins/graph/graphs_plugin_test.py, tensorboard/plugins/graph/graphs_plugin_v2_test.py
Summary:
Now that the data provider code path has replaced the multiplexer code
path entirely, we can remove the test indirection in favor of more
simple straightline setup. This follows the pattern of tests for the
scalars plugin.
Test Plan:
That tests pass suffices; if the data weren’t getting set up properly,
tests would return the wrong data and fail.
wchargin-branch: graph-simplify-tests
=> graph: simplify tests

.github/workflows/ci.yml
Summary:
The `build-data-server-pip` job runs on two platforms on every push, and
each run takes about 5 minutes. The vast majority of this time (85%) is
spent building all dependencies from scratch. Since [macOS minutes are
priced at 10× the rate of Linux minutes][pricing] and this is our only
macOS job, we may as well spend a modicum of effort to improve this.
[pricing]: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions
The docs at <https://github.com/actions/cache> say that a repository can
have up to 5 GB of caches. The cache for our other Rust job is ~200 MB,
and we don’t have any other caches, so adding two more of those caches
seems okay. The caches are also …
=> ci: persist Rust caches for Pip package build

tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts
This change implements temporal scale using d3.scaleTime.
While it _can_ be a performance hotspot, transforming data in temporal
dimension is non-trivial so, for now, we decided to adopt d3.scaleTime
as is.
=> line chart: add temporal scale

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts, tensorboard/webapp/widgets/line_chart_v2/types.ts
This change implements tooltip for the new line chart. The line chart by
default only provide very high level information and does not contain
any information about smoothed value, original value, and wall time.
This change attempts to reach some feature parity with the existing
scalar card.
=> scalar card: implement full tooltip

tensorboard/plugins/text/text_demo.py, tensorboard/uploader/uploader.py
When tensor are dropped for being too long, the end-user has no way of identifying which tensor was dropped.  The user needs to know in case it is a critical tensor to their visualizations.  And we'd like to get concrete reports from users about if our current limits work or are too restrictive, so we need users able to say which tensors they needed, and which ones were ok to skip.
Adding additional data to the log message.
Before: "Tensor too large; skipping.  Size NNNNN exceeds limit of 16384 byte."
After "Tensor (name, step: NNN) too large ...."
The line wraps,  it wrapped before though.
Ran a --dry-run before and after
* Alternate designs / …
=> Identify which tensor is too large, when dropping from upload

tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
In OSS, we can depend on `@angular/material` but we cannot do the same
internally. As such, we have a redirection module
(`tensorboard/webapp/angular:expect_*`) and this change uses that.
=> sync: fix missing material dependency

tensorboard/webapp/widgets/source_code/source_code_diff_component.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts, tensorboard/webapp/widgets/source_code/testing.ts
The SourceDiff component uses the Monaco editor for rendering a diff either
as side-by-side editors or as a unified, inline diff editor. Before, it did not
respect changes in the `renderSideBySide` input property. Now, it calls
Monaco's `updateOptions()` to allow changing the setting in an existing
editor.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditor.html#updateoptions
=> Allow SourceDiff clients to update 'renderSideBySide'

tensorboard/auth_test.py, tensorboard/data/server_ingester_test.py, tensorboard/lazy_test.py, tensorboard/uploader/uploader_test.py
Summary:
To set a value in an outer scope from within a nested function, we’ve
historically used the pattern of “boxing” the value in a length-1 list:
```python
count_box = [0]
def foo():
count_box[0] += 1
...
foo()
assert count_box[0] == 1
```
Now that we use Python 3 everywhere, we can avoid the box and just use
the `nonlocal` keyword instead:
```python
count = 0
def foo():
nonlocal count
count += 1
...
foo()
assert count == 1
```
This patch fixes up uses of this pattern, all of which are in tests.
Part of #4488.
Test Plan:
Running `git grep -F '_box = ['` no longer matches any results.
wchargin-branch: box-to-nonlocal
=> Use `nonlocal` rather than `box[0]` in tests

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
- do not wrap tooltip content when there isn't enough space
- vertical align the fob
- reposition tooltip and optionally right align against the chart when
inconvenient.
=> line chart: tooltip UX improvements

tensorboard/plugins/projector/projector_plugin.py
Summary:
The projector uses `multiplexer.RunPaths()` to find each run’s logdir on
disk, but it’s not clear from the code how this stays up to date as more
runs are loaded. The answer is insidious: `RunPaths` returns the raw
underlying dictionary, not a shallow copy of it, so changes to the
internal structures of the multiplexer are immediately reflected in the
projector plugin. This is a bit terrifying, since it means both that the
code is wildly non-threadsafe and that it’s hard to tell when the data
has actually changed. (The terror is somewhat abated by remembering that
concurrency safety around dicts in Python is all just pretend, anyway.)
This patch modifies the projector plugin to always shallow-copy the
result of `RunPaths`, and makes the necessary follow-up changes to
observe …
=> projector: fix `RunPaths` result aliasing

tensorboard/plugins/projector/projector_plugin.py
Summary:
Some Google-internal, non-TensorBoard code depends on the projector and
monkey patches out its internals in a way that is not compatible with
the changes in #4479. This is clearly not ideal and should probably be
fixed downstream, but pending investigation we revert #4479 to unbreak.
This reverts commit 638014e1c12e43aeb090e8b101e0cf41c518c650.
Test Plan:
Test sync at this tree passes all tests.
wchargin-branch: projector-revert-4479
=> Revert "projector: fix `RunPaths` result aliasing (#4479)"

tensorboard/components/tf_backend/requestManager.ts, tensorboard/components/vz_line_chart2/microbenchmark/async.ts, tensorboard/components/vz_line_chart2/microbenchmark/polymer_util.ts, tensorboard/plugins/projector/vz_projector/data-provider.ts, tensorboard/plugins/projector/vz_projector/data.ts
Summary:
When creating a new promise in JavaScript, calling `resolve()` is
equivalent to calling `resolve(undefined)`. But [TypeScript 4.1 forbids
the implicit form][ts-relnotes]:
> Expected 1 arguments, but got 0. Did you forget to include 'void' in
> your type argument to 'Promise'?
This patch updates our code to explicitly patch `Promise<void>` where
appropriate, which for some reason suppresses the error, and to
explicitly pass `undefined` in places where `Promise<void>` is wrong.
Call sites found by manual `git grep -F 'resolve()'` and filtering out
matches for `Promise.resolve`, which may still be invoked without
argument.
[ts-relnotes]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises
Googlers, see …
=> ts: pass explicit args to promise resolvers

tensorboard/notebook.py
Summary:
The `html.escape` function superseded `cgi.escape` in Python 3.2, prior
to which the `html` module did not exist. We now unconditionally import
`html`, without falling back to `cgi`.
Part of #4488.
Test Plan:
Tested the Pip package in Jupyter. When rebased on top of #4507, which
removes the `unittest.mock` backport, a `git grep -A1 '^try:'` shows
that the remaining top-level conditional statements are okay: a bunch of
TensorFlow compatibility incantations for summaries, and one conditional
import of `botocore`.
wchargin-branch: py3-html-escape
=> py3: use `html.escape` unconditionally

tensorboard/compat/proto/BUILD
Summary:
The Bazel Go proto rules require that each proto file have its own Go
package and its own build target. This patch splits up `protos_all`
accordingly, retaining an hourglass target for Python code.
Generated by running
```sh
(
cd tensorboard/compat/proto/ &&
for f in *.proto; do
printf 'tb_proto_library(\n'
printf '\tname = "%s",\n' "${f%.proto}"
printf '\tsrcs = ["%s"],\n' "$f"
if grep -q '^import "tensorboard/' "$f"; then
printf '\tdeps = [\n'
grep '^import "tensorboard/' "$f" |
sed -e 's#.*compat/proto/\([^.]*\).*#\t\t":\1",#'
printf '\t],\n'
fi
printf ')\n\n'
done | expand -t4
)
```
and copying the output into `tensorboard/compat/proto/BUILD`, then
replacing `protos_all`’s `srcs` with `deps` and running Buildifier.
Test Plan:
All targets build and all tests pass. After a test …
=> proto: split `protos_all` into individual targets

.github/workflows/ci.yml, tensorboard/data/server/downsample.rs, tensorboard/data/server/event_file.rs, tensorboard/data/server/lib.rs, tensorboard/data/server/logdir.rs, tensorboard/data/server/server.rs, tensorboard/data/server/types.rs, tensorboard/data/server/writer.rs
Summary:
We run Clippy to catch common errors, but by default Clippy only runs on
non-test code. We noticed this in #4487, when Clippy would have caught a
real error (test doing nothing due to `unit_cmp`). This patch adds the
`--tests` flag to our Clippy invocation and fixes all existing warnings.
Test Plan:
The first draft of this PR included only the workflow change, and thus
properly failed on CI. Once the fixes were included, CI passed.
wchargin-branch: rust-clippy-tests
=> rust: run Clippy on tests and fix existing errors

tensorboard/data/server/logdir.rs
Summary:
We import `OsStr` but only use it in tests that don’t run on macOS,
which causes an `unused_imports` warning: harmless, but should be fixed.
Test Plan:
Note that the `build-data-server-pip` macOS CI job’s “Test” step emits a
warning before this patch but not after it.
wchargin-branch: rust-unused-import-macos
=> rust: fix test warning on macOS

tensorboard/tools/whitespace_hygiene_test.py
Summary:
Noticed in the original, failed CI run of #4507 that this script ran in
Python 2, since its `print()` caused an extra `()` to be printed (since
we turned off `print_function` in #4503). This happens because its
shebang specifies the system’s default `python` and the CI job that
invokes it doesn’t set up a Python 3 virtualenv. The script still works,
since it’s effectively bicompatible, but for consistency we should still
make sure that everything runs on Python 3 only (else the tasks in #4488
are not necessarily sound).
Test Plan:
`git grep bin/python` only matches this line, and we have no uses of
`/usr/bin/env python`, either.
wchargin-branch: py3-whitespace-test
=> py3: run `whitespace_hygiene_test.py` in Python 3

tensorboard/plugins/graph/tf_graph_common/render.ts
color histograms method spammed "no pairs found" onto console which
makes console quite unusable for a large graph. This change removes it.
=> cleanup: remove dev print for graph

tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
This change treats time axis a bit specially and hardcodes logic for
rendering times. Time ticks, unlike simple numbers, can result in
massive confusion if we encode one to fit into 50px. For instance, if I
were representing 2020/12/31 12:31:12.442 as "12.442", you lose all the
important date, hour, and minute. We are definitely using `<title>` so
user can see more complete information but we lose the "glance-ability".
To mitigate the issue (not perfectly solving the issue), show a major
tick only for date which shows a bit higher level information (datetime)
when certain conditions are right. This business logic definitely is not
perfect but it is a great start and found it to be helpful.
I find special treatment for time scale encoded in line_chart_v2 a bit
unfortunate but it is the …
=> line chart: temporal axis

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
This change re-implements a feature of vz-line-chart, tooltip sorting.
We sort the tooltip based on few criterions:
- ascending/descending of `y`
- nearest: distance to the cursor
- default: just the order of the runs from... (unclear and it confuses
people)
=> line chart: implement tooltip sort order

tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD, tensorboard/webapp/widgets/line_chart_v2/sub_view/internal_types.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/testing.ts
We now allow:
- middle click drag to pan around
- altKey to pan (used to be only shift)
- show cursor according to the internal state
=> line chart: improve interaction

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view_test.ts
Due to the bug, we were using xScale when calculating y-positions of the
grid. This change fixes that and adds a test.
=> line chart: use yScale for y-axis in grid

tensorboard/data/server/server.rs
https://github.com/tensorflow/tensorboard/issues/4422 Plugin listing task
* Implements plugin listing by iterating over all Runs / Tags in the commit and reducing to a set of pluginnames, which are moved into a list in the response.
* Adds tests.
=> rust: implement `ListPlugins` RPC

tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts, tensorboard/plugins/graph/tf_graph_common/common.ts, tensorboard/plugins/graph/tf_graph_common/layout.ts, tensorboard/plugins/graph/tf_graph_common/node.ts, tensorboard/plugins/graph/tf_graph_common/util.ts
Background: since SVG text does not support CSS's
text-overflow:ellipsis, we manually measure the text dimension using
`SVGTextElement.prototype.getComputedTextLength`.
Problem: `getComputedTextLength` causes relayout/restyle which ends up
spending nearly 10ms per operation which is prohibited expensive. This
process is repeated with O(n) and causes larger graph rendering to take
~160s in a text set.
Fix: instead of using SVG's getComputedTextLength, we now use canvas and
its measureText. Do note that we need to know the fontSize and, to
prevent invoking `computedStyle` (which will invoke restyle), we
estimate the fontSize which may cause less than ideal layout.
After the change, we no longer see restyle or relayout in performance
profiling and saw the last render step ("build scene") …
=> perf: improve graph build performance

tensorboard/plugins/audio/summary_test.py, tensorboard/plugins/audio/summary_v2.py
Audio summaries have always assumed that examples in the dense
tensor shaped [batch_size, num_frames, num_channels] all have the same
length. This is frequently not the case when building audio models, such as
text-to-speech models, where the output length of the model varies per batch
item. When ragged tensors of substantially different shapes are batched
together, this can be wasteful. Additionally, the padding after the end of each
record is included in the resulting WAV file, which is misleading because these
samples were not present in the source signal. The consumer of the audio summary
has no way to determine what the original true lengths of each example were.
This change adds a lengths keyword argument to …
=> Add a lengths argument to tensorboard.summary.audio.

tensorboard/plugins/projector/tf_projector_plugin/index.js, tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.ts, tensorboard/webapp/plugins/plugins_component.ts
https://github.com/tensorflow/tensorboard/issues/4313
Unnecessary scrollers in Chrome and firefox 
1. Replace margin with padding for the content of projector text block to prevent the body height exceeds the iframe
2. The script tag ahead of nested iframe creates a small extra height for firefox. Apply line-heigh 0 to the body 
* Chrome
Firefox
=> Fix unnecessary scroller bar in firefox and chrome

.github/workflows/ci.yml, tensorboard/data/server/pip_package/build.py, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py, tensorboard/data/server_ingester.py
Summary:
The `tensorboard-data-server` package now supports a universal build
configuration. When built in this configuration, the package does not
actually contain a binary, and returns `None` when interrogated for its
path. But it can be installed on any platform, so it serves as a
fallback. Thus, `tensorboard` can depend on `tensorboard-data-server`
while maintaining install-time compatibility on all platforms.
Closes #4533; see that issue for details.
Test Plan:
Running `build.py` with `--universal` successfully creates a Pip package
called `tensorboard_data_server-0.1.0a0-py3-none-any.whl` that contains
no binary. Running TensorBoard with `--load_fast` prints the new error
message and exits. When re-installing the native wheel, TensorBoard can
still find it. The existing codepaths …
=> rust: build universal data server with no binary

tensorboard/plugins/graph/tf_graph/tf-graph.ts
Polymer's property setter invokes binding and causes ripple of changes.
Previously, with new Hierarchy() measurement, we were measuring time it
takes to propagate `renderHierarchy` changes which internally redoes
layout and rendering. As such, `new Hierarchy` was measuring,
"tf-graph-scene (layout)" and "tf-graph-scene (build scene)".
=> refactor: tweak graph const. measurement

tensorboard/components/tf_categorization_utils/categorizationUtils.ts, tensorboard/components/tf_paginated_view/tf-dom-repeat.ts, tensorboard/defs/BUILD, tensorboard/defs/defs.bzl, tensorboard/defs/strict_type_check.d.ts, tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts, tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts, tensorboard/plugins/mesh/tf_mesh_dashboard/array-buffer-data-provider.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/metrics/views/main_view/main_view_test.ts, tensorboard/webapp/plugins/npmi/npmi_container_test.ts, tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_test.ts, tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_test.ts, tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts, tensorboard/webapp/plugins/text_v2/data_source/text_v2_server_data_source.ts, tensorboard/webapp/plugins/text_v2/store/testing.ts, tensorboard/webapp/plugins/text_v2/store/text_v2_reducers.ts, tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
When you create a Map without values, TypeScript has to infer the type
and, sometimes, it is imperfect and types cannot unsafe. This change
forces valueless Map constructor to specify the types so we rely less on
the inference.
To emulate the internal enforcement, we are making a necessary changes
to `tf_ts_library` but do note that it is imperfect and sometimes misses the
cases. Also do note that it somehow leaks its way into targets with
`strict_check = False` which is unintended but bearable.
Do note that this requires sync changes.
Test CL with necessary change patched: cl/350867815
=> infra: better type Map

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.base64-0.13.0.bazel
Summary:
The [`base64`] crate provides Base64 encoding and decoding, for a
variety of alphabets (including both [RFC 3548 alphabets][rfc]) and with
optional padding. We’ll use this to encode blob keys.
[`base64`]: https://crates.io/crates/base64
[rfc]: https://tools.ietf.org/html/rfc3548#section-3
Test Plan:
It builds: `bazel build //third_party/rust:base64`.
wchargin-branch: rust-dep-base64
=> rust: add `base64` dependency

tensorboard/webapp/metrics/effects/index.ts, tensorboard/webapp/metrics/effects/metrics_effects_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
In the new gpu line chart, we have an option to use Worker process to
render the line chart but its initialization can be heavy as it requires
to download the worker resources (or even parse script and create a
process). To make the AFT better, we only stamp and create line chart
component when it is actually visible on the screen.
=> timeseries: stamp scalar only when first visible

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.ryu-1.0.5.bazel, third_party/rust/remote/BUILD.serde-1.0.118.bazel, third_party/rust/remote/BUILD.serde_derive-1.0.118.bazel, third_party/rust/remote/BUILD.serde_json-1.0.61.bazel, third_party/rust/remote/BUILD.syn-1.0.48.bazel
Summary:
The [`serde`] crate is a key ecosystem framework, providing a bridge
between data formats (JSON, YAML, CBOR, etc.) and serializable structs.
A Rust struct can `#[derive(Serialize, Deserialize)]` and then operate
with any data format, such as [`serde_json`]. Most pressingly, we want
these for encoding structs within blob keys.
[`serde`]: https://crates.io/crates/serde
[`serde_json`]: https://crates.io/crates/serde_json
Test Plan:
They build: `bazel build //third_party/rust:{serde,serde_json}`.
wchargin-branch: rust-dep-serde
=> rust: add `serde` and `serde_json` dependencies

tensorboard/plugins/audio/summary_test.py, tensorboard/plugins/audio/summary_v2.py
Reverts tensorflow/tensorboard#4502
We need to pass this through an internal review process first since the change affects the TensorFlow API, and that can take up to a week, so reverting for now to avoid blocking our internal sync.
=> Revert "Add a lengths argument to tensorboard.summary.audio."

tensorboard/pip_package/requirements.txt
Summary:
As of #4510, we don’t need `six`, so we can remove it from the Pip
package requirements.
Part of #4488.
Test Plan:
Running `:extract_pip_package` and installing it into a virtualenv still
installs `six` as a transitive dep, so this is actually no functional
change for now. Maybe one day.
wchargin-branch: py3-norequire-six
=> py3: remove `six` from requirements

.github/workflows/ci.yml, RELEASE.md, tensorboard/version.py
Cherrypicks:
- #4423: ng: support path_prefix at router level
- #4332: Remove `frame-ancestors *` CSP directive
To be merged with rebase. Closes #4547.
=> TensorBoard 2.4.1

tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
Graph plugin's main UI affordance is double click a node to
expand/collapse. This, without this change, by browser default selects
text in a node which is often not user's intention and offers less than
ideal user experience. This change disables that.
=> graph: disallow double click to select text

tensorboard/webapp/widgets/line_chart/line_chart_component.ts, tensorboard/webapp/widgets/line_chart/line_chart_test.ts
Summary:
The TensorBoard backend sends wall times in floating-point seconds since
epoch, and the scalars dashboard interprets them accordingly. But the
time series dashboard was interpreting them as milliseconds since epoch,
causing recent dates to be rendered around January 1970. This patch
fixes the frontend to multiply by 1000, as the scalars dashboard does.
This bug also affected relative times, which were shown compressed by a
factor of 1000 on the horizontal axis (but not in the tooltips). This
bug did not affect GPU line charts.
Fixes #4541.
Test Plan:
Before: the wall time spans a single second, labeled “06:16:46 PM
January 18, 1970”. After: the wall time starts on “04:31 PM July 17,
2019” and ends at “04:35 PM July 17, 2019”.][ss]
[ss]: …
=> metrics: fix wall time rendering

tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Inactive or no-data graph plugin should show the sidebar #4451
Move `tf-dashboard-layout` and `tf-graph-controls` out of the template condition to always show the sidebar.
Conditionally show graph or "no data" view instead
=> graph: Display sidebar for no data and inactive graph

RELEASE.md
One commit to round out the 2.4.1 release process: cherry-pick of
2.4.1 relnotes added to RELEASE.md.
=> Post-release 2.4.1

tensorboard/plugins/core/core_plugin.py, tensorboard/plugins/core/core_plugin_test.py
Previously, TensorBoard never cached the resource even when its contents
never change in a given pip package. While this is tolerable in the
local instance setting, it is not the best especially when we start to
use worker where the resources would have to be fetched per worker
instance,
This change enables caching for one day (for now) when JavaScript
resources with `_file_hash` query parameter is requested. While this
approach works for any resources, there is no strong reason to do so and
we will start with restrictive caching at first. In the future, we may
apply the query parameter to more resources and enable caching of SVG
and other resources.
=> core: cache on JS resources when hash is present

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.pin-project-lite-0.2.4.bazel, third_party/rust/remote/BUILD.tokio-1.0.2.bazel, third_party/rust/remote/BUILD.tokio-stream-0.1.2.bazel
Summary:
The [`tokio-stream`] crate makes it easier to work with async streams,
and in particular to iterate over them. This is useful for test code
that needs to iterate over the responses of server-streaming RPCs like
`ReadBlob`.
[`tokio-stream`]: https://crates.io/crates/tokio-stream
Test Plan:
It builds: `bazel build //third_party/rust:tokio_stream`.
wchargin-branch: rust-dep-tokio-stream
=> rust: add `tokio-stream` dependency

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
Line chart axis is relying on Angular's behavior to combine `class` set
by parent and one set with `HostBinding`. While it works okay in OSS, it
breaks internally.
As such, we refactored the axis to reliably set the class name.
=> line chart: fix axis layout

tensorboard/data/server/commit.rs, tensorboard/data/server/data_compat.rs, tensorboard/data/server/run.rs, tensorboard/data/server/writer.rs
Summary:
The `Commit` structure now has a `blob_sequences` store in addition to
its `scalars` store. For now, we only actually load run graphs into
memory (since it’s trivial, and everything else is merely easy).
Test Plan:
Unit tests included. There are no user-facing changes to the RPC layer.
Loading an MNIST dataset with scalars, graphs, and images no longer
prints warnings about `graph_def`s, and still serves scalars properly.
wchargin-branch: rust-load-graphs
=> rust: load graphs into memory as blob sequences

tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_pool.ts
Internally, we cannot create Worker with string. As such, we need to
alter the types of parameter of Worker factory and this change allows
there to be different type signatures of the WorkerPool.
=> line chart: refactor worker typing

tensorboard/data/server/data_compat.rs
Summary:
We now support TF 1.x images, TF 2.x images, and any tensors that have
an explicit blob sequence data class.
Test Plan:
Unit tests included. As an end-to-end test, images now appear in
TensorBoard with `--load_fast`, in both the images and time series
dashboards.
wchargin-branch: rust-images-generic-blobs
=> rust: support images and generic blob sequences

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/app_root_module.ts, tensorboard/webapp/app_routing/app_routing_module.ts, tensorboard/webapp/app_routing/views/app_routing_view_module.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_http_client.ts, tensorboard/webapp/webapp_data_source/tb_http_client_test.ts
Some frontend components, including the Time Series dashboard, make
HTTP requests using absolute paths, which fail under --path_prefix, since
the TensorBoard application may not be served under '/'.
This change amends TBHttpClient to add the 'app root' as a prefix when
the requested resource is an absolute path. Internal schemes of the form
'/experiment/some_dynamic_id/...' (e.g. TB.dev) should be compatible, if
the 'app root' is '/' in those cases.
Manually tested with/without `--path_prefix=/foo/bar` that the Time Series
dashboard loads data. Pointing the logdir at npmi demo data did not load
anything in the dashboard, so I was not able to confirm that it works as
intended.
Note that Debugger V2's code viewer still fails to load Monaco under path
prefix. It does not use TBHttpClient for …
=> bug: fix requests to absolute paths under path_prefix

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
In the timeseries dashboard, we keep track of cards that are in the
view. With this information, we can opt out of updating the charts that
are outside of the viewport and save CPU cycles.
This change propagates the visibility information via `enableUpdate`
flag and make sure to apply changes only when the card is visible in the
viewport.
=> line chart: update only visible charts

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/cli.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
This PR bumps the data server version number from 0.1.0a0 to 0.1.0, and
then to 0.2.0a0. Plan: merge with rebase, then release from the data
server binaries at the first commit as built by GitHub CI.
Notes:
- Rust versions use <https://semver.org>, so prerelease specifiers are
like `0.2.0-alpha.0` rather than Python `0.2.0a0`.
- We could use `version = clap::crate_version!()` in the Rust code to
avoid having to duplicate across `Cargo.toml` and `cli.rs`. This
works fine when building with Cargo. But `CARGO_PKG_VERSION` is not
set when building with Bazel, so for now I’m doing the simple thing
and duplicating the string manually.
Test Plan:
Note that `cargo run -- -h` and `bazel run . -- -h` both print the
correct version.
=> tensorboard-data-server 0.1.0

tensorboard/data/server/bench.rs, tensorboard/data/server/cli.rs, tensorboard/data/server/event_file.rs, tensorboard/data/server/logdir.rs, tensorboard/data/server/run.rs
Summary:
Instead of computing checksums for every record, we can now compute
checksums only for records that fail proto parsing. This means that bit
flips in payloads like string fields may not be caught. But it comes
with a significant performance improvement:
- 2.42× (±0.24×) faster for `mnist` (125 ms → 50 ms)
- 1.20× (±0.03×) faster for `edge_cgan` (10.4 s → 8.7 s)
- 1.23× (±0.01×) faster for `nndiv` (182 s → 148 s)
Both the main RustBoard binary and the `bench` binary now take
`--checksum`/`--no-checksum` flags, defaulting to `--no-checksum`.
Test Plan:
Unit tests extended. Benchmarked with:
```
hyperfine -w3 \
'./target/release/bench --logdir ~/testdata/edge_cgan/ {cksum}' \
-L cksum --checksum,--no-checksum
```
wchargin-branch: rust-optional-crc
=> rust: make CRC checking optional

tensorboard/data/server_ingester.py
Summary:
Since `tensorboard` will eventually depend on `tensorboard-data-server`,
the data server will be installed in our normal dev virtualenvs. When
developing the Rust server with `--define=link_data_server=true`, we
want local changes to take precedence. This patch updates the server
ingester to check for a bundled server binary before checking for a
dynamically imported Python package.
An explicit `TENSORBOARD_DATA_SERVER_BINARY` environment variable still
overrides both of the other mechanisms.
Test Plan:
Run with `--load_fast --verbosity 0` and watch the “Server binary” log
line to see how the bundle is being resolved, in these configurations:
- no `--define`, no Python package: should fail
- `--define`, no Python package: should use Bazel binary
- `--define`, with Python package: …
=> rust: prefer Bazel-built server to Python dep

tensorboard/tools/diagnose_tensorboard.py
Summary:
If `tensorboard-data-server` is installed, the diagnostic script will
now print the Python version, the binary path, and the data server
version (as determined by invoking the server binary with `--version`).
Test Plan:
Tested: with no data server package; with the universal wheel, which
provides the data server Python package but no actual binary; and with
the Linux wheel, which does have a server binary.
wchargin-branch: diagnose-data-server
=> diagnose: print data server info

tensorboard/backend/event_processing/data_ingester.py, tensorboard/plugins/core/core_plugin.py
Summary:
In #1001, we changed the interpretation of `--reload_interval` such that
negative values caused event files not to be read at all. This was to
accommodate DB mode: when loading from a database, reading event files
was superfluous. But DB mode is gone, and the corresponding distinction
for a Rust-based data provider is handled by the ingester system
instead. That is, `event_processing/data_ingester.py` now always loads
event files, and `data/server_ingester.py` never loads event files.
This is technically a backward-incompatible change, but DB mode was
always experimental, so the only stable use of this was to launch a
TensorBoard instance that never loaded any data at all. I’m okay with
breaking such use cases.
Test Plan:
Running with `--reload_interval` set to `0` or `1` or …
=> core: drop support for negative `--reload_interval`

tensorboard/data/server/cli.rs, tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py, tensorboard/program.py
Summary:
The TensorBoard `--reload_interval` flag now affects the flags passed to
the data server. To faithfully interpret the flag, we also teach the
data server to accept `--reload once`, corresponding to what TensorBoard
calls `--reload_interval 0`. We introduce this separate syntax to keep
the interpretation of `--reload N` continuous in `N`.
Test Plan:
Run with `--load_fast --verbosity 0 --reload_interval N` for various
values of `N`. Note that with `--reload_interval 0`, the data server
prints info logs for only one loading cycle, whereas with positive
intervals it delays for the correct amount of time. Note that fractional
intervals don’t cause a crash (they truncate).
wchargin-branch: rust-plumb-reload-interval
=> rust: plumb reload interval to data server

tensorboard/plugin_util.py
My particular use case is dumping a json config file, but the fenced code syntax is pretty common in markdown and I suspect it will have lots of uses.
https://www.markdownguide.org/extended-syntax/#fenced-code-blocks
Just adds the `fenced_code` extension.
Log a text event with a fenced code block, verify it renders correctly.
I don't know another good way to include a block of preformatted text.
=> text: support fenced code blocks in Markdown

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/cli.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.1.0:
- performance improvements: checksums off by default; Tokio 1.0
- `--reload once`, to support TensorBoard `--reload_interval`
- suppressed “listening on [::1]:PORT” spam
the version numbers are 0.2.0.
(Supersedes 0.1.1 from #4586. Let’s use minor releases for now so that
the version numbers advance monotonically with commits.)
=> tensorboard-data-server 0.2.0

tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
We want to add application-specific feature flags for varieties of TensorBoard. Part of this work requires implementing application-specific children of QueryParamsFeatureFlagDataSource. There is some logic from the base class that we'd like to share with children, so we can avoid duplicating some testing hooks.
We expose a new protected method getParams() in QueryParamsFeatureFlagsDataSource. It returns util.getParams(), which can be overriden in tests for the child classes.
Googlers, see http://cl/353022802 for some more context.
=> Expose getParams() in QueryParamsFeatureFlagDataSource

tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts
Currently, TensorBoard reflects the feature flags as is to the URL. This
means, we cannot differentiate overrides from defaults and makes
changing the defaults harder.
For instance, soon, we want to change fastChart to default true but, in
that case, we don't want the URL to say anything about fastChart. Also,
in that world, we would like to support fastChart=false which should
remain in the URL since it is an explicit override user has requested.
This change now differentiate overrides from default values in the
reducer.
=> feature flag: persist only overridden flags

.github/workflows/ci.yml
Summary:
Running CI on tags seems sensible on its own merits, and also enables us
to trigger CI on data server releases by tagging them rather than using
a temporary branch.
Test Plan:
The workflow run for this PR should show that the definition is still
valid. After merging, push a new tag for a commit that includes this
patch, and check that it starts a CI run.
wchargin-branch: ci-trigger-on-tags
=> ci: run on pushes to tags

tensorboard/webapp/BUILD, tensorboard/webapp/app_container.ts, tensorboard/webapp/app_test.ts
Only after the router is initialized, we can make sure we are at the
correct routes only at which point we should start to initialize and
make requests. Otherwise, we can make requests at the wrong paths which
may/may-not be correct.
With this change, we fire the coreLoaded after router is initialized
which is confirmed by checking for non-nullness of the activeRoute.
=> ng: dispatch coreLoaded after router is initialized

tensorboard/webapp/BUILD
Commit 73f6e98540d1498a415f0d49f484fef06df29f46 omitted required
dependency on Angular and ngrx testing dependencies. This change adds
them.
=> deps: add explicit dependency to test libs

tensorboard/compat/proto/config.proto, tensorboard/compat/proto/graph.proto, tensorboard/compat/proto/op_def.proto, tensorboard/compat/proto/rewriter_config.proto, tensorboard/compat/proto/saved_object_graph.proto, tensorboard/compat/proto/summary.proto, tensorboard/compat/proto/types.proto, tensorboard/data/server/tensorboard.pb.rs
Summary:
Pulls in [TensorFlow commit b565087c5cd7][c], which updates the docs for
the `DataClass` enum. Miscellaneous updates included as well.
[c]: https://github.com/tensorflow/tensorflow/commit/b565087c5cd72fc222a0610011335a381d7f7ac7
Generated with:
```
$ tensorboard/compat/proto/update.sh ~/git/tensorflow
$ bazel run //tensorboard/data/server:update_protos
```
Test Plan:
Changes are all either backward-compatible or to experimental messages
that we don’t use, so unit tests should suffice.
wchargin-branch: protos-sync-b565087c5cd7
=> Update protos for TF 2021-01-25 head

tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts
WebGL enabled line charts have been using a thinner line thickness
by default, due to a limitation in WebGL [1]. A common workaround
is to render line thickness manually, turning each line segment into
a rectangle composed of 2 triangles. This change uses the approach
to restore the 2 pixel line width found in stable TensorBoard.
Notably, line segments used to be representable by 2 vertices are
now represented with 6 vertices (2 triangles), so performance is
expected to degrade.
This change does not take into account the "end caps" of each line,
so minor artifacts are noticeable when examining the joint between
two consecutive line segments carefully. Addressing the end caps
may require adding more triangles, which adds a decent amount
of complexity without significant noticeable benefit. …
=> line chart: restore thicker line width

tensorboard/data/server_ingester.py
This extends the current propagation of `INFO`-level logging to also apply to `DEBUG` - we just pass `--verbose` a second time if the Python code is logging at `DEBUG`.
=> rustboard: propagate --verbosity=debug to tensorboard-data-server

tensorboard/compat/proto/BUILD
Summary:
As of #4516, `//tensorboard/compat/proto/...` has separate targets for
each proto file, to support generating Go protos. The recent proto
update in #4600 added an `import` statement, which works fine for our
`protos_all` monotarget, and also happens to work for the separate
target since there was already a corresponding transitive dependency.
But this fails inside Google because of an extra strict deps check.
This patch manually adds the offending edge to unbreak the sync. We’ll
look into preventing further such regressions in a follow-up patch.
Test Plan:
Note that #4600 only adds one import statement, and that it corresponds
to this edge. Check that a test sync passes: <http://cl/353789753>.
wchargin-branch: proto-op-def-resource-handle-dep
=> proto: add dep from `:op_def` to `:resource_handle`

tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts
Existing ngrx selectors in the Run feature store offer ways to get a `Run`
from its associated `runId`, and a list of `Run`s for a specific
`experimentId`. However, it would be convenient for consumers who
wish to convert a batch of `runId`s into a batch of `Run`s without having
to do a combination of multiple `getRun()` calls.
This introduces a convenience selector that returns a map that
consumers can use for easy lookup.  For example,
```ts
// Container
<component [handyMap] = "store.select(getRunMap) | async">
```
```ts
// Component
@Input handyMap;
// ...
const run = this.handyMap.get(runId);
```
This change is intended to offer support for
https://github.com/tensorflow/tensorboard/pull/4592
=> Introduce a selector providing a RunId to Run map

tensorboard/uploader/BUILD, tensorboard/uploader/flags_parser.py, tensorboard/uploader/flags_parser_test.py, tensorboard/uploader/uploader_subcommand.py, tensorboard/util/grpc_util.py, tensorboard/util/grpc_util_test.py
Summary:
A new `grpc_util.ChannelCredsType` enum represents the user-facing
variants for channel credentials. Flag parsing and consumption now
delegate to that enum rather than hand-enumerating all cases. The goal
is to enable defining a parallel flag to main TensorBoard to configure
the connection to the data server.
We define one method to create both channel creds and options so that
callers are less likely to get credentials but forget to set options,
which would cause `SSL_DEV` to behave incorrectly.
Test Plan:
Unit tests included. As end-to-end tests:
- `tensorboard dev list` still works
- `tensorboard dev --grpc_creds_type=ssl list` also still works
- `tensorboard dev --grpc_creds_type=local list` successfully parses
and then fails to connect to addresses, which is expected
- …
=> grpc_util: extract channel creds parsing and logic

tensorboard/BUILD, tensorboard/main.py, tensorboard/main_lib.py, tensorboard/program.py
This cleans up our main.py to reduce boilerplate needed for the minimal functionality:
1) We migrate a few lines of global initialization (which are themselves short, but have longer comments) into a new `global_init()` helper in a `main_lib.py` library; this supersedes `program.setup_environment()`.  (We don't want to just move everything into `program` since we don't want it to pick up a dependency on TensorFlow.)
2) We remove some fallback logic in `main.py` that handled the case where we don't have `absl` available.  It's been a required dep for years (since #1654).
This is intended to simplify the process of forking `main.py` as is being done in #4588.
=> cleanup: reduce amount of boilerplate needed in main.py

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view_test.ts
The GPU line chart does not account for space when creating tick string.
This can of course lead to clipping which is kind of fine except it can
sometimes lead to a confusing chart when the substring can make a lot of
sense. While this is mitigated by `<title>` and tooltips, we lose the
glance-ability.
To give user a hint that the tick string might be clipped, we now use
faded mask on the tick strings.
=> line chart: put fades around start&end of text

tensorboard/BUILD, tensorboard/main.py, tensorboard/main_dev.py, tensorboard/program.py, tensorboard/program_test.py
New `tensorboard:dev` target provides a development instance of the
application which optimizes for development experience. While the
changes are omitted in this commit for brevity, we are looking to stream
line the FE building to optimize for its incremental build time.
=> infra: create dev target

tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts, tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts
This is a roll-forward of #4593 (rolled back by #4599)
Currently, TensorBoard reflects the feature flags as is to the URL. This
means, we cannot differentiate overrides from defaults and makes
changing the defaults harder.
For instance, soon, we want to change fastChart to default true but, in
that case, we don't want the URL to say anything about fastChart. Also,
in that world, we would like to support fastChart=false which should
remain in the URL since it is an explicit override user has requested.
This change, to prevent breakage internally, types `defaultFlags` and
`flagOverrides` as optional while keeping the `features` as required.
The steps to move forward and deprecate the `features` are:
1. [GH] this change
2. [Internal] change every usage of `features` to also provide …
=> feature: differentiate overridden flags from default

tensorboard/data/server/logdir.rs, tensorboard/data/server/run.rs, tensorboard/data/server_ingester.py
Addresses the online commits task from #4422.
RunLoader's `reload()` method now ensures that we commit all time series data staged from the run at a regular interval (which I've hardcoded to 5 seconds), rather than waiting until all event files in the run have been read to exhaustion before committing any data.  I did a little refactoring to facilitate making this change which I've broken out into separate commits.
Based on a minimal amount of benchmarking against the ~20GiB event file from `gs://tensorboard-bench-logs/nndiv_100m/events.out.tfevents.1549560561.hostname`, it looks like this adds about 1% overhead in reading the file to completion (first is unmodified code; second is with this PR):
```
$ hyperfine -m 5 'bazel-bin/tensorboard/data/server/bench --logdir …
```
=> rust: make RunLoader commit periodically while loading a large run

tensorboard/components/tf_markdown_view/sanitize.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/plugins/plugins_component.ng.html, tensorboard/webapp/routes/core_deeplink_provider.ts, tensorboard/webapp/routes/core_deeplink_provider_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
The common typo was caught by the internal lint tool.
=> chore: fix typo of "overriden" to "overridden"

tensorboard/data/server/DEVELOPMENT.md
Summary:
We sometimes refer to `mnist`, `edge_cgan`, and `nndiv_100m` datasets.
These are stored in a world-readable GCS bucket. This patch adds that
information to the README.
Test Plan:
Check that the link resolves to a helpful README listing the datasets.
wchargin-branch: rust-test-data-bucket
=> rust: list test data bucket in `DEVELOPMENT.md`

tensorboard/data/server/BUILD, tensorboard/data/server/data_compat.rs, tensorboard/data/server/gen_protos_tool.rs, tensorboard/data/server/tensorboard.pb.rs, tensorboard/data_compat.py, tensorboard/data_compat_test.py, tensorboard/plugins/audio/BUILD, tensorboard/plugins/audio/metadata.py, tensorboard/plugins/audio/plugin_data.proto, tensorboard/plugins/image/BUILD, tensorboard/plugins/image/metadata.py, tensorboard/plugins/image/plugin_data.proto
Summary:
In TensorFlow 1.x, image and audio data are represented with a separate
time series for each batch item (`input_image/image/0`, etc.). In
TensorFlow 2.x, a time series may include multiple batch items. This
patch adds a field to image and audio metadata protos to indicate that
they have been automatically converted (by `data_compat`) from TF 1.x to
TF 2.x. This way, downstream code can tell that a TF 1.x time series may
be part of a larger batch even though it only contains a single sample.
Since this new annotation is a proto field that is `true` only for
legacy data, summary metadata for TF 2.x summaries is unchanged.
Test Plan:
As end-to-end tests, verified that the images and audio dashboards both
still work with TF 1.x data, and checked with `grpc_cli` that the data
server …
=> data_compat: mark converted image and audio data

tensorboard/plugins/graph/metadata.py
Summary:
These docs attempted to guess the future. They guessed wrong, but the
future is now here, so we can guess the present instead: much easier.
wchargin-branch: graph-metadata-docs
=> graph: update metadata docs on plugin names

tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
We are using CSS `grid` to render the new line chart and this resulted
in an awkward missing pixel at the "origin". To illustrate this with
simple diagram:
```
|
|
|
missing ->x------
```
With this change, we are now rendering the missing origin rectangle with
a span.
About seemingly unrelated change: when using SVG path to render the axis
lines, it was not as crisp as a border and resulted in noticeable visual
jank with the rectangle.
=> line chart: fill the origin with a rectangle

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
For vz-line-chart, Angular code was imperative API call and, for
brevity, we reproduced the pattern.
=> line chart: support Fit domain button in timeseries

tensorboard/BUILD, tensorboard/webapp/dev_assets/BUILD, tensorboard/webapp/dev_assets/main_dev.ts
With this change, dev assets are significantly different than prod one.
To enumerate the differences:
- Angular application now loads in dev mode allowing ngrx to print
diagnostic information on console
- No longer vulcanize. Previously, we vulcanized to inline CSS, HTML,
and resources and combined JavaScript into a single source. With this
change, we no longer inline/concat sources and load them separately.
- this breaks roboto.html loading as it internally uses rel="import"
but we intend to get rid of it to remove dependency on
tensorboard_html_binary which pulls in Java dependency.
~temporary: this change contains PR #4588~
=> infra: implement dev assets

tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
chart library tries to minimally update the content and we forgot to
update the content when the axis change.
Added integration test to test regression against it.
=> line chart: update chart content when axis changes

tensorboard/BUILD, tensorboard/assets.py, tensorboard/assets_test.py, tensorboard/main.py, tensorboard/main_dev.py, tensorboard/program.py, tensorboard/program_test.py
Summary:
This patch reverts the backward-incompatible changes to `program` made
in #4588, while retaining the new functionality in that change.
Specifically, we restore the calling convention of `TensorBoard`
(reordering the parameters was a breaking change, as was removing the
default value). For clarity, the data dependency to `webfiles.zip` lives
in a new Python module, `//tensorboard:assets_lib`. The `program` module
late-imports this only if no assets zip provider is given, in which case
the caller is expected to have a build dep on `:assets_lib`. The main
`//tensorboard` binary does so; `//tensorboard:dev` does not.
Test Plan:
Tested `//tensorboard`, `//tensorboard:dev`, and the Pip package in a
new virtualenv. There is no build path from `:dev` to the prod assets:
```
$ bazel query …
```
=> program: restore default assets zip provider

tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts, tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
Fix file upload control function (fixes #4556 #1613)
Previously the board render either the graphboard or no-data messages. Now it renders both and uses css display to control their appearances.
Select file:
Normal loading:
=> graph: fix file upload control when no initial data loaded

tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Wne user manually changes the viewBox (by scrolling or dragging), we
tend to honor the fixed viewBox even when data/visibility/etc...
changes. While this is reasonable in most cases, when scaleType changes,
it can lead to an illegal domain (e.g., log scale cannot render viewBox
that is negative) which is not great for UX.
As such. this change resets and overwrites the fixed viewBox when
user changes the viewBox.
=> line chart: auto reset viewBox when scaleType

tensorboard/BUILD, tensorboard/defs/py_repl.bzl
This adds a `py_repl` build rule that makes it simpler to spin up an interactive Python shell that includes a specified set of Bazel deps, which is useful for ad-hoc exploration of a library interface.
In a conventional Python setup a regular old `python` would work, but with Bazel this is more of a pain to get the correct runfiles, including files potentially generated by Bazel itself (e.g. `_pb2.py` files generated from protos, or genrule-created files).  Using a `py_binary` solves that, but it's a little annoying to clutter the codebase with a nearly empty main.py, and you have to remember the right invocation of `PYTHONINSPECT=1` to have it drop you into the REPL.  This build rule essentially just prepackages all of that for you.
=> introduce py_repl() rule for a convenient Bazel-aware python shell

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
For line chart, we are using Angular overlay to create, adjust, and
position the tooltip. The overlay supports a position preference
configuration which tries to fit the overlay in the available viewport
space in the order provided in the preference.
Problem: our configuration was a bit faulty and offset[X,Y] were using
wrong signs causing tooltip to overlap with the chart (by 5px) when the
tooltip was placed above the chart. Instead of pushing the tooltip down
by 5px, we meant to place 5px above.
Fix: reviewed the configuration again for their signage and adjusted the
amount for better UX.
=> line chart: adjust tooltip positions

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, third_party/rust/BUILD.bazel, third_party/rust/crates.bzl, third_party/rust/remote/BUILD.crossbeam-channel-0.5.0.bazel, third_party/rust/remote/BUILD.crossbeam-deque-0.8.0.bazel, third_party/rust/remote/BUILD.crossbeam-utils-0.8.1.bazel, third_party/rust/remote/BUILD.rayon-1.5.0.bazel, third_party/rust/remote/BUILD.rayon-core-1.9.0.bazel
Summary:
The [`rayon`] crate provides easy data parallelism: change `iter()` to
`par_iter()` and you’re off to the races—but not the data races, which
are prevented at compile time. We can use it to load runs concurrently.
[`rayon`]: https://crates.io/crates/rayon
Test Plan:
It builds: `bazel build //third_party/rust:rayon`.
wchargin-branch: rust-dep-rayon
=> rust: add `rayon` dependency

tensorboard/context.py
This changes the WSGI `environ` key used for `RequestContext` from being a sentinel object to being the ordinary string `tensorboard.request_context`.
Although a sentinel object is elegantly collision-proof and would be fine in a normal dict, a close read of the WSGI spec reveals that `environ` is meant to contain only string keys:
> Finally, the `environ` dictionary may also contain server-defined variables. These variables should be named using only lower-case letters, numbers, dots, and underscores, and should be prefixed with a name that is unique to the defining server or gateway. For example, `mod_python` might define variables with names like `mod_python.some_variable`.
> -- from the bottom of https://www.python.org/dev/peps/pep-0333/#environ-variables
This updates our key to …
=> change RequestContext WSGI environ key to comply with spec

tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
When the line chart is initialized but never resized, currently our
`domDimension` and `viewBox` which is updated lazily after content is
initialized is not reflected to the template and their children. This is
because we use OnPush change detector and we never explicitly ask
Angular to detect changes.
This bug manifests especially when you spam on the tag filter and get
the timing right.
=> line chart: fix line chart not updating bug

tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts
We are in process of upgrading our FeatureFlag store to divide default
flag vs. overrides. Previously, everything was mixed into `features`
making certain UX impossible.
Because there is a corresponding code internally, we cannot just switch
immediately so this change is the 3rd of 5th step to safely migrate all
use caess.
=> types: set `defaultFlags` as required property

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts
In the selector where we still need to support `features`, we check for
existence of a property to refine the type for backwards compatibility.
=> types: make `features` omittable by typing

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts
Reverts tensorflow/tensorboard#4648
This change breaks the sync as it can violate certain types defined internally. Until internal codes can take this change, this PR is reverted.
=> Revert "types: make `features` omittable by typing"

tensorboard/components/BUILD, tensorboard/defs/defs.bzl, tensorboard/webapp/dev_assets/BUILD
While the Angular bundle incremental build time was improved
with the `tensorboard:dev` mode, the Polymer 3 bundle still
relies on Rollup. After Terser was introduced in the build, the
Polymer incremental build time can take 30+ sec on top of the
TypeScript compilation time.
This change removes the Terser step from the Polymer bundling
phase, only for the dev assets mode.
=> Disable terser on polymer bundle in dev assets mode

tensorboard/components/BUILD, tensorboard/defs/defs.bzl, tensorboard/webapp/dev_assets/BUILD
Reverts a commit that breaks the internal sync.
=> Revert "Disable terser on polymer bundle in dev assets mode (#4651)"

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph_common/render.ts, tensorboard/plugins/graph/tf_graph_common/scene.ts, tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts, tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts
Small CL to remove unused imports from code in the graph plugin
frontend. These were detected by an IDE using TypeScript language
services.
=> cleanup: remove unused imports in graph code

tensorboard/components/tensor_widget/slicing-control.ts, tensorboard/components/tensor_widget/tensor-widget-impl.ts, tensorboard/defs/strict_type_check.d.ts, tensorboard/plugins/projector/vz_projector/data-provider-server.ts, tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts, tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.ts, tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
Increases strictness of `JSON.parse`s typing to match internal
policies.
Tested by running `bazel run tensorboard:dev` and seeing that
it builds successfully.
Googlers, see b/179426717 and test sync cl/355885039.
=> chore: stricter types for JSON.parse

tensorboard/components/BUILD, tensorboard/defs/defs.bzl, tensorboard/webapp/dev_assets/BUILD, tensorboard/webapp/index_polymer3.uninlined.html
**Status**: this PR was originally a roll-forward, but that was
abandoned after we reverted (#4655) the offending sync blocker.
This PR is now a re-land of the original #4651 with modifications.
Re-lands the change in #4651 that was reverted in #4655.
The original change used the `compile` option on `tf_js_binary`
as a signal to skip the Terser minification step. However, this
broke internally because `compile=False` has special semantics
in Google.
Now, the reland does the same minification skip when a new
rule attribute `dev_mode_only=True` is present. Internally,
this attribute is ignored.
Googlers, see test sync cl/355919112.
Before this is landed, cl/355772570 must be submitted first,
to fix syncing issues.
=> Reland "Disable terser on polymer bundle in dev assets mode (#4651)"

tensorboard/plugins/core/core_plugin.py, tensorboard/plugins/core/core_plugin_test.py, tensorboard/program.py, tensorboard/program_test.py
ReusePort scenario: 
parent process occupies the port, then share the port through service such as ZooKeeper and [TonY](https://github.com/linkedin/TonY) (TensorFlow on Yarn), and then child process (TensorBoard process) reuse the port.
=> Support http server port reuse

tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
When there is a NaN value in the line chart, we render a triangle in place of the NaN based on some business logic. However, when number of NaN becomes high (e.g., entire dataset has millions of NaNs), the new line chart mostly chokes because it simply creates way too many three.js objects. While we have not delved too deeply into it, it spends considerable amount of time in our updater as well as three.js renderer when having too many objects at least compared to one object with many vertices.
To supply the assessment with an imprecise data, when rendering 20 runs, we achieve about 15 FPS with lines (it draws many triangles for the thickness) while it achieves about 2 FPS (~600ms per frame) when drawing all points as triangles. 
For consecutive NaNs, instead of drawing many number of …
=> line chart: add trapezoid renderer

tensorboard/components/tb_debug/types.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_common/loader.ts, tensorboard/plugins/graph/tf_graph_common/util.ts, tensorboard/plugins/graph/tf_graph_controls/BUILD, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_node_search/BUILD, tensorboard/plugins/graph/tf_graph_node_search/tf-graph-node-search.ts
The Graph code includes instrumentation to notify when timing events
occur for debugging. This change adds new instrumentation points
for non-timing related user-initiated actions, such as expanding a node,
performing a search, and toggling the "Trace Inputs" control.
Notably, these non-timing debug events have their own category,
and use the `eventLabel` optionally, instead of the `eventValue` field
required for timing-related events.
Test plan:
Manually checked that events are notified by adding a `console.log`
from inside `notifyActionEventFromPolymer()`, and observed the
output
Googlers, see test sync cl/355952339
=> graph: instrument debug events for user actions

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Previously, in the interactive_view, we used simple arithmetic to
propose new viewExtent based on scroll magnitude and velocity, but it
did not account for the scale. As such, we are now using scale to
compute the next extent based on the position and speed of the cursor
and scroll.
=> line chart: scale aware scroll to zoom

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts, tensorboard/webapp/feature_flag/store/testing.ts
This change retypes the feature flag store to allow for complete removal
of the `features`. Do note that we internally still define `features`
and as such, we need to keep the `features` around with a union type.
=> type: allow complete omission of `features`

tensorboard/uploader/proto/server_info.proto
Summary:
The [gRPC docs] indicate that the default scheme for a channel address
is `dns:///`, but inside Google this is not always the case (Googlers,
see <http://b/179805849>.) Thus, we now require that the API endpoint to
the TensorBoard.dev gRPC server include an explicit scheme. The current
prod servers don’t follow this, but they will soon following internal
changes.
[gRPC docs]: https://github.com/grpc/grpc/blob/master/doc/naming.md
wchargin-branch: docs-grpc-scheme
=> docs: require scheme for TBdev gRPC API endpoint

docs/debugger_v2.md, tensorboard/plugins/debugger_v2/debugger_v2_plugin.py, tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Summary:
The DebuggerV2 plugin reads data outside of the usual summary-based
workflows, and has its own loading infrastructure for doing so. Until
this patch, the plugin would start recursively scanning the user’s log
directory at plugin initialization time—even before the server launches.
This can take a lot of resources and introduce a lot of contention,
especially on remote file systems.
This patch defers all such logic until users of the frontend explicitly
activate the plugin. Startup time improves greatly (see below).
Test Plan:
When pointing at `gs://tensorboard-bench-logs`, the time between process
start and the “server ready” line drops from 9.5 seconds to 1.7 seconds,
as measured by:
```
bazel-bin/tensorboard/tensorboard --logdir gs://tensorboard-bench-logs 2>&1 \
| ts -s …
```
=> debugger_v2: start multiplexer lazily

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/lib.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.2.0:
- separate runs are loaded in parallel
- large runs will display data incrementally as it loads, updating
about every 5 seconds
- GCS support: `--logdir gs://bucket[/prefix]`
the version numbers are 0.3.0.
=> tensorboard-data-server 0.3.0

tensorboard/data/server/BUILD, tensorboard/data/server/gcs/client.rs
Summary:
We now let `gcs::Client::read` return `Bytes` rather than `Vec<u8>` so
that it can pass the response body directly from the HTTP client to the
caller, without additional copying.
For end-to-end speed, benchmarks suggest that this is inconclusive:
dataset     | before (s)   | after (s)   | improvement factor
------------|--------------|-------------|--------------------
`mnist`     | 1.12 ± 0.14  | 1.05 ± 0.06 | 1.05 ± 0.14
`edge_cgan` | 21.0 ± 2.0   | 20.1 ± 0.6  | 1.05 ± 0.11
The confidence intervals clearly overlap. But this change eliminates a
large copy and simplifies the code a bit, so it’s nice to have anyway.
Test Plan:
Type checking suffices; smoke testing `gs://tensorboard-bench-logs/mnist`
with `--load_fast` also checks out.
wchargin-branch: rust-gcs-read-no-copy
=> rust: remove copy in GCS reading

tensorboard/data/server_ingester.py, tensorboard/pip_package/requirements.txt
Summary:
The `tensorboard` Pip package now depends on `tensorboard-data-server`.
Thus, users of standard TensorBoard may now pass `--load_fast` on
supported platforms. Users can still install TensorBoard even on a
platform that does not support the data server, because the data server
package includes a universal binary (`*-py3-none-any.whl`). This package
can always be installed, but does not implement any functionality, and
so attempting to use it with `--load_fast` will fail at runtime.
For now, we pin to exactly the v0.3.x minor series so that we can more
comfortably make breaking changes to the data server.
Test Plan:
Run `//tensorboard/pip_package:extract_pip_package` and install the
resulting wheel into a fresh virtualenv. Note that both TensorBoard and
the data server are …
=> pip: depend on `tensorboard-data-server`

docs/get_started.ipynb, docs/graphs.ipynb, docs/hyperparameter_tuning_with_hparams.ipynb, docs/image_summaries.ipynb, docs/scalars_and_keras.ipynb, docs/tensorboard_in_notebooks.ipynb, docs/tensorboard_projector_plugin.ipynb
These will be uncommented in the site-import pipeline.
The goal here is to make the output less confusing when run in colab.
The code to make these replacements was:
```
import pathlib
import re
for path in pathlib.Path('.').rglob('*.ipynb'):
content = path.read_text()
new_content = re.sub('(<.*?tfo-display-only-on-site.*?/>)', r'', content)
if content != new_content:
print(path)
path.write_text(new_content)
```
see cl/356365619 , b/124898762 for context.
=> Move the tfo-only images into comments.

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/feature_flag_types.ts
This is last of the type upgrades we are making. This change removes
last remains of `features` in favor of `defaultFlags` and
`flagOverrides` in the FeatureFlag reducers.
=> types: remove `features` from FeatureFlag

.github/workflows/ci.yml, third_party/rust.bzl
Summary:
Rust 1.50 is out today! I don’t see anything in the [release notes] that
I’ve been particularly waiting for, but we skipped updating to 1.49.0,
so it’s nice to get back on the stable train.
Benchmarks show no significant change in runtime performance.
[release notes]: https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html
wchargin-branch: rust-v1.50.0
=> rust: upgrade to Rust 1.50.0

tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Now that the default stable language_in value for Closure Compiler is ES2020,
there's no value to explicitly specifying an older language version.
In the future, we plan to get rid of settings older than the current default.
=> Remove unnecessary "language in" setting

tensorboard/plugins/projector/vz_projector/knn.ts
Previosuly, we were using weblass for GPGPU which had to be replaced for
its lack of security patch. In doing so, we replaced the matmul with
TF.js but we did an incorrect cosine distance computation because we did
not transpose the matrix but instead reshaped it.
With this change, we now calculate the cosine distance better and even
more efficiently using the batch/slice to move less data away from GPU.
Fixes #4687.
=> projector: fix the KNN algorithm

tensorboard/data/server/bench.rs, tensorboard/data/server/cli.rs, tensorboard/data/server/logdir.rs, tensorboard/data/server/run.rs, tensorboard/data/server/types.rs, tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py, tensorboard/program.py
Introduces a `--samples-per-plugin` flag on the Rust data server, which
takes the `--samples_per_plugin` flag from standard TensorBoard's CLI.
At the moment, this change makes the value of `0` interpreted as
"create a reservoir with capacity 0", while traditionally the value would be
interpreted as "create a reservoir with unbounded capacity". This
discrepancy will be fixed in a separate PR.
Test plan:
Added unit tests and ran with `cargo test`.
Ran `bazel run tensorboard:dev --define=link_data_server=true -- --load_fast --logdir <logdir> --bind_all --samples_per_plugin=scalars=5,images=0` and observed that scalar charts that normally show lots of points now only show 5, while images do not appear at all.
Associated issue: "samples per plugin" item in the Rustboard task list #4422
=> Plumb --samples_per_plugin to Rust data server

tensorboard/uploader/uploader.py, tensorboard/uploader/uploader_test.py
Fix miscounting error when reporting size of uploads.
The uploader posts values to the upload tracker, which in turn intermittently reports summaries of those values to the user during uploads.  When the upload is complete, upon user termination or after a `--one_shot` upload the total count is reported.  This change fixes a small error where there was over counting.
Specifically, the counts were double incremented in cases where the batch request had met a limit and, instead of acctually inserting a new value, a batch update request was sent.
Adds unit test to cover the case.
Verified uploading a directory of exactly 10k scalars reports exactly 10k scalars
```
$ bazel run tensorboard:tensorboard -- dev upload --logdir ~/tensorboard-logdirs/benchmark_scalars/1e1runs_1e0tags_1e4steps …
```
=> Fix uploader counts of scalars and tensors

tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
This change enables the GPU line chart, the new line chart
implementation, on by default in the time series dashboard. We will, in
the future*, remove the old implementation.
To disable the new implementation, you can pass `?fastChart=false` in the query param.
*: Probably after major/minor release of TensorBoard.
=> line chart: enable GPU line chart by default

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Previously, types flow through Observable in the scalars card container
was quite confusing with its typing and naming. This change refactors a
bit so it is easier by reorganizing and added certain types to be more
explicit.
=> timeseries: refactor scalar container data fetch

tensorboard/data/server/Cargo.toml, tensorboard/data/server/rustfmt.toml
This makes my emacs formatting work again now that we use `async`: https://github.com/rust-lang/rustfmt/issues/4454
The ideal solution would probably be if `rust-mode` were to inspect `Cargo.toml` and pass the edition from there into `rustfmt`, but this is a quicker fix than trying to send them that patch.  Also they previously "fixed the glitch" by [just defaulting `rust-mode` to 2018 edition](https://github.com/rust-lang/rust-mode/pull/338) so I'm not sure they would even take the patch; I still ran into this issue since internal to Google `rust-mode` is outdated.  Besides, it seems technically more correct to have the `rustfmt` edition derived from the repo rather than set to a global default that happens to work for our project.
=> rust: add rustfmt.toml to set `edition = "2018"`

tensorboard/webapp/alert/store/BUILD, tensorboard/webapp/alert/store/alert_reducers.ts, tensorboard/webapp/alert/store/alert_reducers_test.ts
The `Alerts` feature's views are responsible for handling and surfacing
alerts from actions in a "toast" UI. Modules may register a `followup`
action to explicitly show a "retry" style button that triggers a followup
action.
The retry button did not appear as expected, since the reducer was
only storing the `localizedMessage` field. This change includes the
optional `followupAction` as well.
Tested by manually modifying `metrics_module.ts`'s `alertFromAction`
registration to return a followup action:
```ts
return {
localizedMessage: 'whoah message',
followupAction: {
localizedLabel: 'whoah label',
getFollowupAction: async () => {
console.log('yay')
return actions.cardStepSliderChanged({cardId: 'blah', stepIndex: 0});
},
}
};
```
then after clicking the 'Pin' icon on a card to trigger the …
=> alerts: plumb followupAction into store

tensorboard/data/server/data_compat.rs, tensorboard/data/server/run.rs
Summary:
Nothing critical: some unnecessary `.into()`s from #4677 and some
unnecessary `&Box<T>` double-indirection from #4689.
wchargin-branch: rust-clippy-fixes-20210225
=> rust: fix a few Clippy warnings

tensorboard/data/server/commit.rs
Partial work towards rustboard tensors support (subtask of https://github.com/tensorflow/tensorboard/issues/4422).
This just adds a `tensors` field to `RunData` inside `Commit`.  We use `pb::TensorProto` as the value type since that's what we will end up reading off disk and sending over the wire, although it's not terribly ergonomic to manipulate in Rust since we lack Numpy and the `tf.make_tensor_proto()` and `tf.make_ndarray()` conversion methods.  (I looked briefly at [`ndarray`](https://docs.rs/ndarray/0.14.0/ndarray/) which seems nice but probably overkill at this point?  We can see if we end up needing to do enough tensor manipulation to make it worthwhile.)
That in and of itself is a one-line change, but we also extend `CommitBuilder` to support constructing commits that contain …
=> rust: add tensors to Commit and CommitBuilder

tensorboard/plugins/graph/README.md
This introduces a README in `tensorboard/plugins/graph/README.md`,
similar to other plugins. The main motivation is to:
- Catch users inspecting the repo who may want to know how the Graph
dashboard works, and may have missed the tutorial.
- Have a place where we can add technical details that document the
dashboard's internals.
It is **not** meant to be a replacement to the TensorFlow documentation
site's guide.  The official tutorial contains a Colab, is more stable (no TF1
references), and no implementation details of the dashboard's internals.
A followup change expands upon the technical details section:
https://github.com/tensorflow/tensorboard/pull/4705
=> graph: create initial README with user instructions

tensorboard/plugins/graph/README.md, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
This adds technical details to the Graph plugin's README.md.
It includes a glossary of terms, how a graph's data is loaded
and parsed, and discusses key processing steps.
It is not exhaustive and leaves many TODOs deliberately.
Diffbase: https://github.com/tensorflow/tensorboard/pull/4704
=> graph: update README with technical details

tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts, tensorboard/webapp/metrics/views/card_renderer/utils.ts, tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
Please refer to #4696 for definition of the monotonic step and what
problem we are trying to solve.
This change adds integration of the user setting to detect non-monotonic
step changes and split runs into sub runs. While this change is only
applied to the new GPU line chart, it can easily transfer to the legacy
one.
=> timeseries: implement runs x-axis splitter

tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_app/BUILD, tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_common/render.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts, tensorboard/plugins/graph/tf_graph_debugger_data_card/tf-graph-debugger-data-card.ts, tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts, tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
Minor, non-exhaustive set of TypeScript annotation changes related
to Graph code.
Googlers, see test sync cl/360315680.
=> graph: fix TS types for SlimGraph, Hierarchy, RenderGraphInfo usage

tensorboard/webapp/plugins/npmi/util/umap_test.ts
`projections` are typed as just a key-value or string to boolean yet it
is accessed via `.` accessor. This breaks the type checker inside.
=> npmi: tweak typing for sync

docs/text_summaries.ipynb
Adds a tutorial for how to use text summaries.  The tutorial is very basic and only covers adding text under different tags, as well as how to use markdown.  An example is included for how to use markdown to nicely format a json object. 
Added a ipynb file by generating it on my local machine and testing in jupyter.
=> Add ipynb tutorial for text summaries

tensorboard/plugins/projector/vz_projector/BUILD, tensorboard/webapp/plugins/npmi/util/BUILD, tensorboard/webapp/plugins/npmi/util/umap.ts
Internally, we have conformance check to not include certain sources
into our service binaries and vz_projector dependency violates the
conformance.
This change simply copies one method and reimplement the range.
=> npmi: remove vz_projector dependency

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/render.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
This adds a toggle (next to "trace inputs") which turns automatic high-degree node extraction off.
Automatic aux node creation can break the graph up in unwanted ways. For some graphs, the high-degree heuristic is not useful (graphs that have high-degree internal nodes, e.g., if you concatenate lots of towers or some such)
This adds an argument to the hierarchy constructor which if passed, avoids calling the high-degree node extraction code. It also removes the hard-coded PARAM entry for node extraction (which turned off all node extraction, but wasn't user settable).
- build
- upload graph known to be broken apart verify it's broken apart
- toggle …
=> Add a toggle that turns automatic high-degree node extraction off

tensorboard/data/BUILD, tensorboard/data/grpc_provider.py, tensorboard/data/grpc_provider_test.py, tensorboard/data/server/server.rs
Implements RPC-level support for the tensor data class in Rustboard (part of #4422).  In particular we include tensor time series when generating the `ListPlugins` response, and we wire up `ListTensors` and `ReadTensors` on both the server and client.  The latter RPCs are almost identical to the scalars ones; the only nontrivial differences involve handling the actual `TensorProto` values, where we have to explicitly clone them out of the `Commit` on the server side, and convert them into numpy arrays on the client side.
This doesn't yet render any data on its own, since nothing populates the `tensors` fields in the commit (which were introduced by #4710), but with coming PRs that implement the population side, I've tested end-to-end that this correctly renders the expected dashboards. …
=> rust: implement tensor RPCs and client

tensorboard/data/server/data_compat.rs, tensorboard/data/server/run.rs, tensorboard/data/server/writer.rs
This wires up `data_compat.rs` handling for tensors, as part of the tensor support subtask of #4422, which includes:
- adding `initial_metadata()` special-cases for tensor-dataclass plugins
- adding `into_tensor()` for enriching tensor values
- calling `into_tensor()` from within RunLoader
- tests for the above
I also adjusted some naming of other tests within `data_compat.rs` to be (IMO) slightly more precise and clear now that we have the new tensor test methods.
Note that we don't yet handle A) events with no summary value that should nonetheless be treated as having implicit Tensor values (the use case being hparams metadata persistence), and B) legacy histogram data stored in `HistogramProto`.  I've left those for later PRs.
Test plan: I confirmed that with this change and the …
=> rust: implement data_compat.rs basic tensor support

tensorboard/plugins/graph/BUILD, tensorboard/plugins/graph/graphs_plugin.py, tensorboard/plugins/graph/graphs_plugin_test.py
Summary:
When requesting a blob that doesn’t exist, we intend to 404, but instead
500 because the error type is called `NotFoundError`, not `NotFound`.
Test Plan:
Regression test included.
wchargin-branch: graph-notfound
=> graph: fix `NotFoundError` typo

tensorboard/data/server/data_compat.rs
This adds a small macro to convert a given array of numeric types that have a `.to_le_bytes()` method into the concatenation of their LE byte representations, as a `bytes::Bytes` instance.  We need a macro (AFAICT) because `.to_le_bytes()` isn't part of a trait, so we can't achieve this using a function with a type parameter.
The actual macro body has a couple of intermediate `Vec` materializations that would be nice to avoid, but after banging my head against it for a while I couldn't figure out a better way until Rust 1.51 when `array::IntoIter` will be available, and it's only test code.
This doesn't save much effort in the existing code, but it's nice to have in the forthcoming histogram tests where we want to test code that emits significantly larger `tensor_content` fields, and this …
=> rust: add `to_le_bytes!` macro for generating tensor_content fields

tensorboard/webapp/runs/actions/runs_actions.ts, tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts, tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts, tensorboard/webapp/runs/store/runs_types.ts, tensorboard/webapp/runs/store/testing.ts, tensorboard/webapp/runs/types.ts, tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_component.ts, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
This change completes the implementation of the runs table sorting.
Previously, we only supported sorting by experiment name and runs name.
However, with this change, we want to sort by an arbitrary hparam or
metric key user provided.
=> runs table: support hparam and metrics sorting

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/BUILD, tensorboard/plugins/graph/tf_graph_common/node.ts, tensorboard/plugins/graph/tf_graph_common/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph_common/tf-node-icon.ts, tensorboard/plugins/graph/tf_graph_common/view_types.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts, tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts, tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.ts
Refactors types for:
- ColorBy: merges 2 duplicate types found in tf_graph and tf_graph_controls
- templateIndex: previously often typed as a generic `Function`
Diffbase: none
Followup: https://github.com/tensorflow/tensorboard/pull/4725
=> graph: minor type fixes for ColorBy, templateIndex (1)

tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/graph.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_common/loader.ts, tensorboard/plugins/graph/tf_graph_common/node.ts, tensorboard/plugins/graph/tf_graph_common/render.ts, tensorboard/plugins/graph/tf_graph_common/template.ts, tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts, tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
- Merges Hierarchy with HierarchyImpl, since no subclasses are planned
- Introduces LabeledGraphOptions, an options object that configures
how graphlib.Graph is created.
- Extracts the Hierarchy's template computation operation into a separate
method that, in the future, could be called lazily.
Diffbase: https://github.com/tensorflow/tensorboard/pull/4724
Followup: https://github.com/tensorflow/tensorboard/pull/4741
=> graph: refactor Hierarchy, GraphOptions (2)

tensorboard/data/server/data_compat.rs
This implements support in Rustboard for converting legacy TF 1.x histogram summaries that use `HistogramProto` into the k-by-3 tensor format that TensorBoard expects.  We adopt the same logic as `data_compat.py` for consistency, even though the semantics are a bit dubious.
Test plan: unit tests, plus I manually generated an organic TF 1.x histogram summary and confirmed that it now A) shows up in Rustboard-backed TB and B) looks the same as in slow-loading TB.
Part of #4422 tensor support sub-task.
=> rust: support legacy TF 1.x histogram summaries

tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
Starting in Chromium 89, zooming in on nodes in the Graph dashboard
yields very pixelated rendering artifacts. See details in [1]. This
regression is a result of changes to Chromium's SVG renderer [2].
To workaround the symptom, this change replaces the
`will-change: transform` CSS with `transform: translateZ(1px)`. Newer
Chromium versions take the former `will-change` as a hint to use the
rasterized result at initial scale, which renders faster at the cost of
image quality.
Note that we intentionally do not do `transform: translateZ(0)`. The
`1px` is important to avoid introducing a blurry text regression in
Firefox [4], for unknown reasons. The "#root" node does not have
`transform: translateZ(1px)` because this would interfere with
panning the graph.
The `will-change` rule was added in …
=> graph: fix pixelated SVG for Chromium

tensorboard/data/grpc_provider.py, tensorboard/data/grpc_provider_test.py, tensorboard/data/provider.py, tensorboard/data/provider_test.py, tensorboard/data/server/cli.rs, tensorboard/data/server/server.rs
Summary:
This patch implements `GetExperiment` for the Rust data server and the
Python data provider. The server only populates the data location field,
because we don’t actually have any other experiment metadata.
Test Plan:
Tested with `--load_fast` using a local logdir and a GCS logdir.
wchargin-branch: rust-data-location
=> rust: implement data location

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
In very limited use cases of the wall time or temporal scale, the new
line chart shows a major axis to avoid overcrowding of the minor ticks
with long labels.
Previously, the major tick labels were placed only on the "beginning"
which often can be outside of the viewport. For example, for minor ticks
from "4:23" to "4:59", if the major tick goes from "<Date> 4:00" and
"<Date> 5:00", you may not be able to see the label for "4:00" at all.
This change fixes that by putting a border around, using previous
example, 4:00 to 5:00, and centering the label in the available space.
Other things you might notice are:
- refactor how ticks are generated and its data structure
- instead of using `x` and `y` property on SVG, we use padding and
margin to position axes now (with little to no visual …
=> line chart: improve major axis render

tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py
Summary:
The `rustboard` binary, as a well-behaved CLI application, does not
perform tilde expansion on its arguments, because that is the job of the
shell. However, TensorBoard historically _has_ performed tilde
expansion, and so, when `--logdir '~/foo'` is given, `--load_fast` is a
breaking change.
This patch teaches `server_ingester.py` to also perform tilde expansion.
This way, we recover the same user experience without tarnishing the
integrity of `rustboard` itself, or my precious sensibilities.
Test Plan:
Run `tensorboard --logdir '~/tensorboard_data/mnist'` or something: note
the quotes, preventing tilde expansion in the shell. Note that this
resolves to the same directory as if it had not been quoted, as visible
from the data location in the UI. Note that `--load_fast` now …
=> server_ingester: perform tilde expansion on logdir

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_common/util.ts, tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
The motivation behind these changes is to allow the `.templates` field,
currently stored in the Hierarchy, to be computed lazily, e.g. only if/when
the user selects the "Color by structure" mode.
This introduces a "Dispatcher" class, used to give the `Hierarchy` the
traits to allow it to dispatch events and let Hierarchy clients register to
listen to those events. Doing so allows components inside `<tf-node-info>`
and `<tf-graph-scene>`, who currently read the templates, to listen for
changes.
For reference, the hierarchy of Polymer components looks like:
```html
- <tf-graph-dashboard>
- <tf-graph-dashboard-loader {{graphHierarchy}}>; creates GraphDef, SlimGraph, Hierarchy, also used externally
- <tf-graph-controls>; also used externally
- <tf-graph-board [[graphHierarchy]]>; also used …
```
=> graph: notify consumers when Hierarchy's templates update (3)

tensorboard/data/server/cli.rs, tensorboard/data/server/reservoir.rs, tensorboard/data/server/run.rs, tensorboard/data/server/types.rs, tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py
Summary:
The `--samples-per-plugin` argument now understands inputs like
`scalars=100,images=all`. This indicates that some reservoirs should
have unbounded capacity.
Reservoir constructors take `impl Into<Capacity>` so that passing a bare
`usize` is still valid, enjoying all the concision of dynamic typing
alongside the safety of sound static analysis.
Test Plan:
Due to #4752, passing `--samples_per_plugin=scalars=0` to TensorBoard
does not actually work, with or without `--load_fast`. But unit tests
have decent coverage, and manual end-to-end tests against a live data
server show that it really does return lots of data.
wchargin-branch: rust-unbounded-reservoir
=> rust: support unbounded reservoirs

tensorboard/components/tb_debug/types.ts, tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/common_test.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_common/node.ts, tensorboard/plugins/graph/tf_graph_common/view_types.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
The "Color by structure" mode can be very expensive to compute,
often consistently freezing TensorBoard for minutes with some large
graphs. This introduces a new "Color by none", which does not color
groups by structure.
Opening TensorBoard's Graphs with a small graph will still default to
"structure" coloring, but when loading a large graph, it will
automatically switch to "none", requiring the user to opt-in by clicking
on the radio button.
The condition for a large graph is "10K+ nodes && 10K+ edges", but
this can be tuned. These were determined by examining several
graphs manually:
| (# nodes, # edges)  | Time computing templates (sec) | Time to load (after) | Notes
| ------------- | ------------- | -------- | ----- |
| (12, 19)  | 0.004  | <3s |
| (125, 144)  | 0.007  | <3s |
| (233, …
=> graph: color large graphs by 'none' instead of 'structure' by default (4)

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
Some Polymer element classes in the Graph dashboard are exported
for use as types in other files. This breaks the sync inside Google, so
this change removes the `export`s. Note, there is no functional change.
A working hypothesis is that TSC is run with `--declaration` internally,
and we might want to consider adding that in OSS as well.
Googlers, see test sync cl/361900919
=> sync: fix graph symbols exported improperly

tensorboard/default.py, tensorboard/default_test.py
Summary:
We use Python [entry points] to discover dynamic plugins and load their
entry points using the `load` method. It turns out that this does more
than expected: it updates the global working set, analyzes requirements,
and throws an error in some cases where it shouldn’t (see #4761). This
patch switches `.load()` to `.resolve()`, which [actually just resolves
the symbol][resolve].
Fixes #4761.
[entry points]: https://packaging.python.org/specifications/entry-points/
[resolve]: https://github.com/pypa/setuptools/blob/b2f7b8f92725c63b164d5776f85e67cc560def4e/pkg_resources/__init__.py#L2452-L2460
Test Plan:
Run `//tensorboard/data/server/pip_package:install` to install RustBoard
version 0.4.0a0 into a virtualenv with a `tb-nightly` that requires it
at version `<0.4.0`. Launch …
=> default: switch to `EntryPoint.resolve`

tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/minimap.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
The "Download as PNG" button in the Graph dashboard was broken
during the Polymer 2 -> 3 migration. Before, `<tf-graph-minimap>`
relied on assumptions that `<tf-graph-controls>` would provide an
`<a>` tag for downloading in the DOM. This is broken functionally
because the element is not accessible from another shadow subtree.
This fixes the download button by properly plumbing a 'click' event
handler from the controls to trigger code in the minimap.
Manually tested that clicking the button properly opens or saves
a PNG to the filesystem using Chrome and Firefox.
Googlers, see test sync cl/362151624
Fixes https://github.com/tensorflow/tensorboard/issues/3714
For reviewers, the component tree structure looks like:
```html
- <tf-graph-dashboard>
- <tf-graph-controls>
- <tf-graph-board>
- …
```
=> graph: fix PNG download button

tensorboard/backend/event_processing/plugin_event_accumulator.py, tensorboard/backend/event_processing/plugin_event_accumulator_test.py
Summary:
Fixes #4743. A supervisor may use `SessionLog.START` events whenever it
starts, so the first such event does not indicate a *restart* and does
not require preemption. Events like graphs sometimes(?) appear before
the first `SessionLog.START`. This patch changes the accumulator to only
preempt on non-initial `SessionLog.START` events to retain that data.
Test Plan:
The updated unit test fails before this patch and passes after it. Also,
the dataset in #4743 now shows a graph in the graphs dashboard rather
than an internal 404. For posterity, the salient structure of that event
file comprises this sequence of events, all implicitly at step 0:
{ file_version: "brain.Event:2" }
{ graph_def: "..." }
{ meta_graph_def: "..." }
{ session_log { status: START } } …
=> accumulator: ignore first `SessionLog.START` event

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/lib.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.3.0:
- tensor support: histograms, text, PR curves, hparams
- `--samples_per_plugin` support
- data location support
- bug fix for relative paths (#4684)
the version numbers are 0.4.0.
=> tensorboard-data-server 0.4.0

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
The new line chart now differentiate the state between viewBox overridden
vs. default. When it is put on the default, any changes in the data will
automatically be reflected in the new domain calculation while when
overridden, the viewBox will be "stuck".
This was one of the older feature requests from the users where they
wanted the line chart to clearly indicate whether it will "auto scroll"
to fit the data or it will be stuck.
With this change, we will improve the feature in a minor way by
disabling the "fit to domain" button when it is already at the default
to indicate that the data updates will trigger a domain update as well.
Do note that the `title` is actually not working inside a mat-menu on a
`disabled` button but we will find a way to make it work in a follow-up.
=> line chart: conditionally disable fit to domain

tensorboard/data/server/DEVELOPMENT.md, tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py, tensorboard/plugins/core/core_plugin.py, tensorboard/program.py
Summary:
The `--load_fast` argument now takes a tri-state value: one of `false`,
`true`, or `auto`. If set to `auto`, it uses a data server iff one is
available and installed. This is equivalent to “try to use `--load_fast`
but degrade gracefully if that would fail”.
With this change, `--load_fast` *must* take a value. The old behavior of
`--load_fast` is now spelled `--load_fast true`. The default value is
still `false`, so the default behavior is unchanged.
Test Plan:
Try with the following configurations:
- via Bazel with `--define=link_data_server=true`
- without Bazel-bundled binary, but with `tensorboard-data-server`
- with universal wheel of `tensorboard-data-server` installed (should
fail, because this does not actually include a data server)
- with nothing installed (should fail) …
=> cli: add `--load_fast=auto` option

tensorboard/data/dispatching_provider_test.py, tensorboard/data/grpc_provider.py, tensorboard/data/grpc_provider_test.py, tensorboard/data/provider.py, tensorboard/data/provider_test.py
Summary:
The `experiment_metadata` call is now required to return a non-`None`
value, but the fields now all have default values. This way, we can more
easily add new fields in a backward-compatible way. See #4777.
A few Google-internal data providers still have cases where they can
return `None`, so `core_plugin` (the unique call site) still tolerates
that deviation.
Test Plan:
Note that TensorBoard still looks the same: the `/data/environment`
response has some extra fields, but we don’t render a header bar or
anything.
wchargin-branch: metadata-required
=> data: make metadata required, providing defaults

tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html, tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
`getEmbeddingDataSet` is typed as something that can return an undefined
but component is typed as non-nullable which is incorrect. Angular does
not correctly type check across the component tree and resulted in
incorrect typing.
This change fixes the case when we try to access property in an
undefined in a template.
=> npmi: fix the undefined in the selector

tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
When you zoom in a lot on a line chart, current line chart tries to
cramp labels with many digits into the small space causing them to
overlap and cause major visual jank.
With recent improvements to the major ticks to work on y-axis too, when
we detect small differences in the extent, we now show a major ticks for
the linear scale, too, and remove a lot of redundant long prefixes from
the minor ticks.
This PR contains #4727
=> line chart: improve small number on linear scale 

tensorboard/BUILD, tensorboard/data/server/data_compat.rs, tensorboard/dataclass_compat.py, tensorboard/plugins/custom_scalar/BUILD, tensorboard/plugins/custom_scalar/custom_scalars_plugin.py, tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Summary:
This patch replaces the multiplexer code in the custom scalars plugin
with data provider code. It is not gated behind a flag.
We treat the layout protos as tensors, since they are of scalar shape
and are expected to be small. A case could be made for representing them
as blob sequences with a datacompat shape conversion, but this is
simpler and the plugin doesn’t get a ton of use.
Test Plan:
The dashboard still works with the standard demo data, both with and
without `--load_fast=true`.
wchargin-branch: custom-scalars-generic
=> custom_scalar: add generic data support

tensorboard/program.py
Summary:
We’d like to set `--load_fast=auto` as the default for TensorBoard 2.5.
To make that less surprising, we now print an informational message when
`--load_fast` is set to `auto` and the data server is actually used. We
don’t show it with `--load_fast=true`; if you pass that, we assume that
you know what you’re doing. The message looks like:
```
$ tensorboard --logdir /tmp/logs --bind_all --load_fast=auto
2021-03-17 11:41:51.151546: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-17 11:41:51.151567: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your …
```
=> cli: note when data server is used implicitly

tensorboard/webapp/notification_center/_views/BUILD
Summary:
Recent changes in #4769 added an import of `@ngrx/store/testing`, which
works fine here but requires an extra build dep internally.
Test Plan:
Test sync now builds: <http://cl/363586736>.
wchargin-branch: sync-20210317-ngrx-store-testing
=> sync: fix `@ngrx/store/testing` import

tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py
Summary:
In #4689, we decided to only pass `--samples-per-plugin` to the data
server conditionally, because at the time the latest public release of
the data server did not support that flag. Since then, v0.4.0 has been
published, so we can pass the flag unconditionally.
Test Plan:
Verified that with latest `tb-nightly`’s dependencies, the server
behaves as expected both with and without `--samples_per_plugin`.
wchargin-branch: data-always-pass-samples
=> data: pass `--samples-per-plugin` unconditionally

tensorboard/data/server/cli/dynamic_logdir.rs, tensorboard/data/server/gcs/auth.rs, tensorboard/data/server/gcs/gsutil.rs
Summary:
Failure cases when obtaining GCS credentials are now handled in a more
structured manner. Instead of just logging ad hoc warnings, we return
error details to the caller. In particular, this lets the caller
distinguish the case where the user has credentials of a format that we
don’t support, such as service account private keys.
The log messages are nicer, too: in case of a service account key, we
recognize and explain the problem instead of just emitting a JSON error.
Test Plan:
To test each error case, set `GOOGLE_APPLICATION_CREDENTIALS` to:
- `/enoent` or `/etc/shadow` to test `Unreadable(...)`;
- `/dev/null` to test `Unparseable(...)`;
- a service account credentials file to test `Unsupported(...)`.
(Or, just a valid JSON file without the needed fields.)
Then note that both …
=> rust: improve GCS credential error handling

tensorboard/data/server/cli.rs, tensorboard/data/server/cli/dynamic_logdir.rs, tensorboard/data/server/gcs.rs, tensorboard/data/server/gcs/auth.rs, tensorboard/data/server/gcs/client.rs, tensorboard/data/server/gcs/gsutil.rs
Summary:
RustBoard currently writes normal logs to stderr, and also writes any
fatal startup errors to stderr. This makes it impossible to detect and
capture startup errors without also suppressing the log output. As of
this patch, you can pass `--error-file FILE` to ask RustBoard to write
fatal errors to `FILE` instead, so you can leave stderr unencumbered.
In this patch, we also improve error handling for unknown protocols
(like `--logdir wat://mnist`), which complements `--error-file` by
making the startup errors themselves more helpful.
This will be used in `tensorboard(1)` to gracefully fall back to the
legacy multiplexer in case of unsupported invocations: i.e., option (3)
as discussed in #4786.
Test Plan:
Run the data server with `--logdir wat://`, or point to a GCS logdir
while …
=> rust: improve startup error handling

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/lib.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.4.0:
- Added support for Custom Scalars, Mesh plugin data
- Improved error messages for unsupported GCS credentials
- Added `--error-file` option to extract startup errors
the version numbers are 0.5.0.
=> tensorboard-data-server 0.5.0

tensorboard/pip_package/requirements.txt
Summary:
We’ve released tensorboard-data-server==0.5.0. This patch updates the
dependency from TensorBoard to the data server.
Test Plan:
Run `//tensorboard/pip_package:extract_pip_package` and install the
wheel into a new virtualenv. Note that the new data server is installed
and that --load_fast with Custom Scalars, Mesh dashboards works as
desired.
=> pip: require tensorboard-data-server 0.5.0

.github/workflows/ci.yml, tensorboard/pip_package/requirements.txt
Summary:
Installing `tf-nightly` pulls in `tb-nightly` and its dependencies. This
installs over our `requirements.txt`, which matters when there are
version differences. In particular, a PR that upgrades a dependency in
`requirements.txt` should be tested on the new version, not the old one.
Test Plan:
A prior version of this PR also upgraded a package version. The “Check
Pip state” action showed that we now test on the upgraded version.
wchargin-branch: ci-fix-deps-install-order
=> ci: install TensorBoard deps after TensorFlow

tensorboard/data/server/cli.rs
Summary:
We now interpret `--host` as a string that can be `getaddrinfo`d rather
than requiring it to be a literal IP address. Thus, we can support
hostnames like `localhost` that [may have multiple resolutions][play]:
```
[src/main.rs:3] ("localhost", 6006).to_socket_addrs().unwrap().collect::<Vec<_>>() = [
127.0.0.1:6006,
[::1]:6006,
]
```
[play]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15504b49f87e983b4748ca976dcb3bd1
Thus, we change the default `--host` from `::1` to `localhost` to
support systems where `::1` may not be available. Should fix #4801.
We also improve the error message on bind failure: it’s pretty-printed
instead of `Debug`-formatted, and it includes the problematic address.
Test Plan:
From `tensorboard/data/server/`, run `cargo build`, …
=> rust: support and default to `--host localhost`

tensorboard/plugins/scalar/summary_v2.py
update documentation for `tf.summary.scalar`.
Includes an example and a link to our featured demo notebook.
#API_FIXIT_3_18_21
=> docs: update `tf.summary.scalar()`

tensorboard/data/server/Cargo.lock, tensorboard/data/server/Cargo.toml, tensorboard/data/server/lib.rs, tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.5.0:
- bind to `localhost` with system’s preferred IP stack, fixing some
Docker issues (#4801)
the version numbers are 0.6.0.
=> tensorboard-data-server 0.6.0

tensorboard/pip_package/requirements.txt
Summary:
We’ve released `tensorboard-data-server==0.6.0`. This patch updates the
dependency from TensorBoard to the data server.
Test Plan:
Run `//tensorboard/pip_package:extract_pip_package` and install the
wheel into a new virtualenv. Note that the new data server is installed
and that, with `RUST_LOG=rustboard_core::cli=debug`, the parsed
command-line options include `host: "localhost"` rather than `::1`.
wchargin-branch: require-data-server-0.6.0
=> pip: require tensorboard-data-server 0.6.0

tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_node_search/tf-graph-node-search.ts
This polishes the UI in the Graph dashboard's left sidepane, mainly
to improve visual consistency.
- All text now titlecase, no ending periods
- "Choose file" button moved next to other buttons
- Only 2 font sizes
- Radio and toggle controls are left aligned and grouped into sections
- Legend items specific to the "Color by" mode now appear in the "Legend" section
Manually tested that clicking the upload button to load a graph from the
local filesystem still works. Examined the 'Color by' device, TPU compat
modes and they seem fine.
Note to reviewers: please enable the "Hide whitespace changes"
to avoid distracting diffs due to indentation.
Screenshots
=> graph: ui polish for sidepane controls

tensorboard/program.py
Summary:
Cosmetic mistake in #4794: while refactoring around this logic,
I accidentally the line to print the `--load_fast=auto` message.
Test Plan:
Run with `--load_fast auto` and observe the expected `NOTE: ...`.
wchargin-branch: program-advisory-message
=> program: fix data server advisory message

tensorboard/webapp/BUILD, tensorboard/webapp/angular/BUILD, tensorboard/webapp/metrics/BUILD, tensorboard/webapp/metrics/metrics_integration_test.ts, tensorboard/webapp/metrics/metrics_module.ts, tensorboard/webapp/metrics/store/BUILD, tensorboard/webapp/metrics/store/metrics_initial_state_provider.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/runs/views/runs_selector/runs_selector_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/testing/BUILD, tensorboard/webapp/testing/integration_test_module.ts, tensorboard/webapp/testing/mat_icon_module.ts
This change introduces DI for the time series' redux state to allow
different application to provide the default settings. Do note that this
pattern CANNOT be used for a route aware states.
Also do note that this change introduces some infrastructure for
integrational style testing using Jasmine to better test the behavior
provided by the metrics_module which otherwise is not really tested.
Extraneous looking changes are due to the integration test which,
for instance, does not provide certain values from the store (due to a
lacking experimentId from the route) and break certain assumptions.
=> timeseries: customizable settings w/ DI

tensorboard/webapp/metrics/data_source/metrics_data_source.ts, tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts, tensorboard/webapp/metrics/data_source/types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.scss, tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.ts, tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_container.ts, tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_test.ts, tensorboard/webapp/metrics/views/card_renderer/data_download_module.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/runs/types.ts
With this change, when user clicks on overflow menu, one will find a
menu item for downloading the data. When user clicks on it, time series
will bring up a dialog which user can interact with to select a run to
download for the tag selected.
Do note that this is not yet implemented for the histograms and image
data types.
Sync is not tested yet and will be tested after a code review.
=> time series: download link

tensorboard/plugins/core/core_plugin.py
Summary:
Running `tensorboard` now defaults to the fast data loading codepath
when available. This *does not* affect systems where RustBoard is not
installed, including on platforms where it’s unavailable. It also does
not affect invocations in which RustBoard detects that it is not
suitable for the job, such as an unsupported remote filesystem or
credential set. In such cases, TensorBoard will automatically fall back
to the legacy multiplexer paths. This selection is silent unless
`--verbosity 0` is given.
Because of this automatic fallback detection, this change is expected to
be “safe”. There may of course be undiscovered bugs in RustBoard, in
which case users have `--load_fast=false` as an escape hatch.
Users can also set `--load_fast=true` to bypass the selection logic,
suppress the …
=> cli: enable fast Rust data loading by default

tensorboard/plugins/graph/tf_graph/tf-graph.ts, tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts, tensorboard/plugins/graph/tf_graph_common/common_test.ts, tensorboard/plugins/graph/tf_graph_common/graph.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
TensorBoard detects series of nodes (e.g. 'add_1', 'add_2', 'add_3', ...)
and visually collapses them into a single "series node". Currently, the
"ungroup this series" button in the right, floating info pane is broken.
Vestiges indicate that at one time, the button would modify the
`HierarchyParams.seriesMap` object, and rebuild a new `Hierarchy`
using the modified `HierarchyParams`.
This change properly wires up the handlers, but instead of modifying
the `seriesMap` in place, it creates a fresh new `seriesMap` and new
`HierarchyParams` for the new `Hierarchy` to use. This avoids a bug
where ungrouping a series then selecting a different graph to view
would cause the stale `seriesMap` from the previous graph to carry
over.
Fixes https://github.com/tensorflow/tensorboard/issues/4732
To …
=> graph: fix 'ungroup this series' button

package.json, tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-viewer.ts, tensorboard/plugins/projector/vz_projector/scatterPlotVisualizer3DLabels.ts, tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerPolylines.ts, tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts, yarn.lock
Upgrading to the newer Three.js 0.125.0 to silence dependabot warnings.
Notable changes:
- `Material`'s `vertexColors` is now a boolean
- `BufferAttribute.setArray` was removed in favor of
`BufferedGeometry.setAttribute`
- Words like `texture` became reserved keywords when used in Three.js'
shaders
Manually checked that the mesh demo, projector demo, and some custom
projector example with sprite images look as expected. I did not test the
"polylines that connect multiple points in a dataset" feature in the Projector
since I do not know how it works. Line charts in the Time Series look normal
as well.
See the Three.js changelog: https://github.com/mrdoob/three.js/wiki/Migration-Guide
Will be rendered obsolete: https://github.com/tensorflow/tensorboard/pull/4715
Googlers, see b/150083780, …
=> chore: upgrade threejs to 0.125.0

tensorboard/plugins/image/summary_v2.py
Update documentation for `tf.summary.image`.
#API_FIXIT_3_18_21
From what I understand, OSS is the source of truth, but the
TF Devsite is not updated immediately without manually doing
an internal process to update the devsite.
=> docs: update `tf.summary.image()`

tensorboard/plugins/histogram/summary_v2.py
Update documentation for `tf.summary.histogram`.
#API_FIXIT_3_18_21
From what I understand, OSS is the source of truth, but the
TF Devsite is not updated immediately without manually doing
an internal process to update the devsite.
=> docs: update `tf.summary.histogram()`

tensorboard/webapp/metrics/views/card_renderer/data_download_module.ts
Internally, we still need the entryComponents property to make work.
Without it, the MatDialog cannot mount the component.
=> time series: fix the data download module

tensorboard/plugins/graph/tf_graph_common/common_test.ts, tensorboard/plugins/graph/tf_graph_common/hierarchy.ts, tensorboard/plugins/graph/tf_graph_common/loader.ts, tensorboard/plugins/graph/tf_graph_common/parser.ts, tensorboard/plugins/graph/tf_graph_common/util.ts
Before, these nodes [add_0, add_1, add_2, ...] could be collapsed into
a single "series group node", while [add1, add2, add3, ...] could not.
This change relaxes the strict regex check to allow names without
underscores.
Note that the "minimum 5 node series length" constraint still applies,
as the main heuristic that guards against overly aggressive series
grouping.
=> graph: relax the aggressive numeric node series detection

tensorboard/plugins/histogram/BUILD, tensorboard/plugins/histogram/histograms_plugin.py, tensorboard/plugins/histogram/metadata.py
Summary:
We’re considering making changes to the histogram data format, most
immediately to resolve dynamic shape issues, but maybe also to generally
improve the sampling and binning behavior. This patch teaches the
histograms plugin to check the summary metadata’s `version` field and
complain if it’s not not `0` (the default, and the implicit value).
This way, if users try to use an old TensorBoard version to read data in
the new format, they’ll see a nice message instead of potential crashes
or misrepresented data.
It’d be reasonable to adopt something similar for all our plugins, but
let’s start here for now.
Test Plan:
Changing the check to `md.version != 777` properly causes a message to
be printed once (only) and no data to appear in the UI. …
=> histograms: warn when metadata version is too new

tensorboard/backend/event_processing/data_provider.py, tensorboard/backend/event_processing/data_provider_test.py, tensorboard/data/dispatching_provider.py, tensorboard/data/dispatching_provider_test.py, tensorboard/data/grpc_provider.py, tensorboard/data/grpc_provider_test.py, tensorboard/data/provider.py, tensorboard/plugins/core/core_plugin.py, tensorboard/plugins/core/core_plugin_test.py
Summary:
This has been folded into `experiment_metadata`, per #4777.
Test Plan:
The only remaining match for `data_location(` is the `@property`
definition on `ExperimentMetadata`.
wchargin-branch: rm-data-location
=> data: remove `data_location` method

tensorboard/data/server_ingester.py, tensorboard/data/server_ingester_test.py, tensorboard/plugins/core/core_plugin.py, tensorboard/program.py
Summary:
The main `tensorboard(1)` now proxies any `--extra_data_server_flags` to
the data server binary invoked as a subprocess. This would have been
useful as a less invasive workaround for #4801, and may serve as a
similar escape hatch in the future.
The argument to `--extra_data_server_flags` undergoes POSIX word
splitting, so you can pass multiple arguments by separating them by
spaces, quoting appropriately. Thus:
```
tensorboard --extra_data_server_flags="--host 'localhost or something'"
```
You can’t override flags that `tensorboard(1)` already passes, though,
because the data server will complain about conflicting arguments.
Thus, this interface is marked as unstable and is not intended to ever
be stabilized.
Test Plan:
Unit tests suffice. …
=> cli: add `--extra_data_server_flags`

tensorboard/plugins/pr_curve/BUILD, tensorboard/plugins/pr_curve/metadata.py, tensorboard/plugins/pr_curve/pr_curves_plugin.py
Summary:
Analogue of 5e220deb33ca for PR curves instead of histograms. Might go
ahead and factor this out into a common utility, but for now let’s start
with this in case changes for TF 2.x compatibility want changes to the
serialized form.
Test Plan:
Same as in 5e220deb33ca.
wchargin-branch: pr-curves-version-warning
=> pr_curves: warn when metadata version is too new

.github/workflows/ci.yml, third_party/rust.bzl
Summary:
Rust 1.51 is out! The [release notes] have the rundown, but the headline
feature is minimal viable const generics, or “non-type template
parameters” by analogy to C++. In particular, items can now be generic
over the length of arrays, which we’ve wanted to do a few times.
Benchmarks show no significant change in runtime performance.
[release notes]: https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html
wchargin-branch: rust-v1.51.0
=> rust: upgrade to Rust 1.51.0

.github/workflows/ci.yml
Summary:
It looks like GitHub Linux VMs have Rust [installed by default][1], so
when we use `actions-rs/toolchain` to install toolchains at a later
version, we need to explicitly set them as default, and also install any
needed extra components (rustfmt, clippy).
[1]: https://github.com/actions/virtual-environments/blob/ff9f3f0a8bc69e64fad8790abcc61ff266277b76/images/linux/Ubuntu2004-README.md
wchargin-branch: ci-rust-toolchain-default
=> ci: set manual Rust toolchains as default

tensorboard/BUILD, tensorboard/plugin_util.py, tensorboard/plugins/audio/BUILD, tensorboard/plugins/audio/audio_plugin.py, tensorboard/plugins/audio/metadata.py, tensorboard/plugins/histogram/BUILD, tensorboard/plugins/histogram/histograms_plugin.py, tensorboard/plugins/histogram/metadata.py, tensorboard/plugins/image/BUILD, tensorboard/plugins/image/images_plugin.py, tensorboard/plugins/image/metadata.py, tensorboard/plugins/mesh/mesh_plugin.py, tensorboard/plugins/mesh/metadata.py, tensorboard/plugins/mesh/metadata_test.py, tensorboard/plugins/metrics/metrics_plugin.py, tensorboard/plugins/npmi/BUILD, tensorboard/plugins/npmi/metadata.py, tensorboard/plugins/npmi/npmi_plugin.py, tensorboard/plugins/pr_curve/BUILD, tensorboard/plugins/pr_curve/pr_curves_plugin.py, tensorboard/plugins/scalar/BUILD, tensorboard/plugins/scalar/metadata.py, tensorboard/plugins/scalar/scalars_plugin.py, tensorboard/plugins/text/metadata.py, tensorboard/plugins/text/text_plugin.py, tensorboard/plugins/text_v2/text_v2_plugin.py
Summary:
This abstracts over the metadata warnings for histograms and PR curves,
recently added in 5e220deb33ca and fea085ba5c5b, respectively. The
plugin code is now just a few lines. The new helper is in `plugin_util`,
but underscore-named to show that it’s meant for TensorBoard-internal
use only.
This functionality is now supported by the scalars, custom scalars,
images, audio, distributions (implicitly), histograms, text, PR curves,
mesh, and time series dashboards.
It’s not supported by the graphs dashboard, since graphs have a
non-standard summary metadata version format. It’s not supported in
hparams just because the backend is more complex with more moving parts,
so the fruit hangs not quite as low. It’s not supported in the debugger,
profile, What-If Tool, or projector dashboards …
=> plugin_util: factor out summary metadata version checker

tensorboard/data/server/cli.rs, tensorboard/data/server/server.rs
Summary:
While watching @jonhoo’s latest [“Crust of Rust” video on atomics][jh],
I realized that we can just convert this irritating `&'static Commit`
leaked reference into a jointly owned `Arc<Commit>` while still meeting
the `T: 'static` bound for the RPC handler type. It’s not really a big
functional difference, because the commit would live for the whole
program anyway, but it’s nice to not have to worry about it. It should
also reduce the peak memory usage during tests, since we used to box up
and leak a new commit in each test case.
(In fact, this probably makes server shutdown a tad slower. If we really
wanted to recover that performance, we could make the server generic
over `T: Deref<Target = Commit>`, and pass `Box::leak(...)` in the main
program and an `Arc<Commit>` in tests. …
=> rust: hold commit in `Arc` instead of leaking

tensorboard/plugins/graph/tf_graph_common/common_test.ts, tensorboard/webapp/core/effects/core_effects_test.ts, tensorboard/webapp/runs/data_source/testing.ts, tensorboard/webapp/widgets/source_code/load_monaco_shim_test.ts, yarn.lock
This simply upgrades all the transitive dependencies using `yarn
upgrade` using the version spec specified in the package.json.
Do note that this change upgrade `y18n@4.0.0` (to 5.0.5) which is known
to have a security vulnerability, CVE-2020-7774.
=> infra: upgrade FE dependencies

tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/plugin.py
Raw Scalars example plugin was using PluginMultiplexer which is
deprecated and now throws RuntimeError.
Do note that the deprecation was not caught because the tests were run
manually, not in CI.
=> example: raw_scalars: use DataProvider

tensorboard/pip_package/requirements_dev.txt
Summary:
Running `pip install pandas==1.0.3` on Python 3.9 hangs for a few
minutes and then crashes with 20K lines of C compilation errors. The
latest version of `pandas` works with 3.9, but not with 3.6, which we
also support (and run in CI). This patch relaxes our dep to `~=1.0`,
which should pick an appropriate version in both 3.6 and 3.9.
wchargin-branch: pip-pandas-1.x
=> pip: relax `pandas` dep to 1.x

tensorboard/components/experimental/plugin_lib/core.ts, tensorboard/components/experimental/plugin_util/BUILD, tensorboard/components/experimental/plugin_util/core-host-impl.ts, tensorboard/components/experimental/plugin_util/message_types.ts, tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts, tensorboard/webapp/BUILD, tensorboard/webapp/core/store/core_selectors.ts, tensorboard/webapp/selectors.ts
This change introduces `tb_plugin_lib.experimental.core.setOnReload(()
=> {})` API. It gets invoked when TensorBoard finishes reloading the
data automatically and manually.
=> plugin api: implement reload listener

tensorboard/data/BUILD, tensorboard/data/server_ingester.py
Summary:
Issue #4844 shows that there are circumstances when communication
between TensorBoard and the local data server process cannot be
established. As of this patch, we send a trivial RPC to the data server
and wait for its response before committing to use the new loading
paths. This adds about 1–5ms total time to the happy path on my machine,
with a worst case penalty of 5s due to the timeout. If the server is not
reachable, we print a warning and fall back to the legacy paths.
Test Plan:
- Test with normal working TensorBoard.
- Simulate failed data server connection by changing the definition of
`addr` to `"localhost:%d" % (port + 777)` on line 175. This should
print the `UNAVAILABLE`/“failed to connect” message from #4844.
- Simulate slow data server by adding the following to …
=> data: check liveness before blessing data server

tensorboard/compat/tensorflow_stub/io/gfile.py, tensorboard/compat/tensorflow_stub/io/gfile_s3_test.py, tensorboard/compat/tensorflow_stub/io/gfile_test.py, tensorboard/summary/writer/event_file_writer.py
`tf.io.gfile.makedirs` correctly handles existing directories so this PR removes unnecessary calls to `tf.io.gfile.file_exists`. This can be beneficial when working with object storage where listing files or checking for the existence of a directory might be expensive.
=> Remove unneeded `tf.io.gfile.file_exists` checks

tensorboard/components/experimental/plugin_util/BUILD
Internal quirk requires explicit dependency on `@ngrx/store/testing`.
=> sync: add missing ngrx store dep

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
The scalar line chart in the time series has had the feature where we
automatically fit domain to the new data when it is unaltered. However,
because it was hidden inside the overflow menu and because there was no
clear visual indication when the chart will fit to the domain or not, it
was largely confusing. With the recent changes to make it more salient
with `title` and `disabled` on the button, we improved in this area but
was still not too obvious.
To fix this problem, we are now moving the control out of the overflow
menu into the chart header so there is a clearer visual difference
between domains overridden vs. not.
=> time series: move the fit button to header

tensorboard/webapp/notification_center/_redux/notification_notes.ts, tensorboard/webapp/notification_center/_views/BUILD, tensorboard/webapp/notification_center/_views/notification_center_component.ng.html, tensorboard/webapp/notification_center/_views/notification_center_component.scss, tensorboard/webapp/notification_center/_views/notification_center_test.ts, tensorboard/webapp/notification_center/_views/views_module.ts
This change integrates the markdown renderer with the notification
center. Now the content of the notification can be any markdown string
as long as it does not contain certain dangerous elements like script
tag.
This change also makes few visual modification to the markdown renderer
for the optimal rendering in the small widthed screen.
=> notification center: integrate markdown renderer

WORKSPACE, third_party/tensorflow.patch
This is a workaround for #4862 - see that issue for all the gory details.
The tl;dr is that we want to fix an omission in the TF python configuration rules, where they only list a small number of environment variables that their [repository rules are sensitive to](https://docs.bazel.build/versions/master/skylark/lib/globals.html#repository_rule). In particular they don't include `PATH` (or `PYTHONPATH` or `PYTHONHOME`), even though these are all actually used by the toolchain resolution rules to find the active python binary and python lib directory.  So we just patch them in, which ameliorates #4862.  (In theory we could try to upstream this, but we're currently pinned to TF 2.3.0 rules and having to upgrade will probably be painful.)
Tested: ran repro script from #4862 and verified that …
=> build: patch TF python_configure to fix genrule toolchain issues

tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Currently, the interactable elements are stacked on top of each other on
the runs table; sort -> filter button. Without the stopPropagation,
clicking on a filter menu button will trigger a sort which is not what
we want.
=> runs: prevent sort when filter button is clicked

tensorboard/util/grpc_util.py, tensorboard/util/grpc_util_test.py
Towards making uploader asynchronous (for upload speed to TensorBoard.dev).  Actually making the uploader use this new utility will follow in a separate PR.  This portion is submitted separately in the spirit of smaller, easier to understand PRs.
Creates a new util API `async_call_with_retries` which mirrors the existing `call_with_retries` but (unsurprisingly) returns right away and completes the gRPC call asynchronously, using the gRPC `future` API.   The retry functionality is implemented as a recursive call where the continuation calls the same API with a decremented number of remaining tries.
* Test Plan:
Adds unit tests covering cases very similar to the `call_with_retries` functionality.   I've also tested that …
=> Add `async_call_with_retries` method to grpc_util.

tensorboard/webapp/notification_center/_views/BUILD
Now that we use the NO_SCHEMA_ERROR from `@angular/core`, we need the explicit dep.
=> sync: add missing dep on angular/core

tensorboard/plugins/graph/tf_graph_common/common_test.ts, tensorboard/plugins/graph/tf_graph_common/graph.ts
This fixes an issue where the Graph dashboard would die with "Graph: Failed Normalizing names" when trying to parse a graphdef containing a node with a mis-formatted `_output_shapes` attr.  In particular, it fails if the `_output_shapes` attr doesn't contain the top-level `list` property (either it's empty, or has only other properties).  The fix is just to guard the logic by checking for that property's existence before dereferencing it.
This attr is generated when calling `as_graph_def(add_shapes=True)` and I'm pretty sure that when constructed normally it should always have the `.list.shape` property if it's present on the node at all:
- https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/framework/ops.py;l=3304;drc=5e0c8476f0d8473e6246897ad1065ec4621bf73e
- …
=> graph: fix bug in parsing of _output_shapes attr

tensorboard/components/BUILD, tensorboard/components/experimental/plugin_util/BUILD, tensorboard/components/experimental/plugin_util/core-host-impl.ts, tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts, tensorboard/components/tf_globals/BUILD, tensorboard/components/tf_storage/BUILD, tensorboard/components/tf_storage/storage.ts, tensorboard/components/tf_storage/storage_utils.ts
Core API requires dependency on tf_storage for reading the hash and that
module depends on lodash. Lodash, technically, is not an issue but it
seems to double bundle on the dev target of the internal application and
breaks the build.
Also, this change guts the bazel dependency of plugin_host to the
polymer binary (saving changes to the plugin_host code does not trigger
rebuild of Polymer anymore!)
=> plugin api: cut tie to lodash and polymer

.github/workflows/ci.yml, tensorboard/data/BUILD, tensorboard/data/server_ingester.py, tensorboard/version.py
This PR is created to see and diagnose potential CI quirks.
This change has following commits:
version bump to 2.5.0.
cherrypick of #4851.
Merge: rebase (not squash).
=> TensorBoard 2.5

tensorboard/plugins/core/core_plugin_test.py
This re-enables the test cases that were previously under `CorePluginTestBase`, which wasn't actually being executed - it used to be a common base class in between two subclasses that actually were `tf.test.TestCase` instances, but these subclasses were removed in #3539 without converting the parent class into a `TestCase` in its own right.
In addition, I've refactored the test cases to consolidate most of them into a single `CorePluginTest` class for simplicity, since they have a lot of common functionality and IMO they were just making it harder to understand where to add a new test method.  See individual commits for each consolidation step that was made.
=> core: re-enable CorePluginTest and consolidate test cases

tensorboard/uploader/BUILD, tensorboard/uploader/uploader.py, tensorboard/uploader/uploader_errors.py, tensorboard/uploader/uploader_subcommand.py, tensorboard/uploader/uploader_test.py
Precondition for factoring `*BatchedRequestSender` into their own modules, so as to simplify uploader logic.  That factoring, in turn, is a precondition for enabling faster asynchronous uploads.'
Moves public errors into their own module.
Tests still pass
There is also the internal _OutOfSpaceError.  It will be moved into the individual BatchedRequestSender.  There is no need to expose this error type or that is must be common across the BatchedRequestSenders
=> Factor public uploader errors into their own module.

docs/debugger_v2.md
The demo code is not consistent with the API and
caller will get a "TypeError: enable_dump_debug_info()
got an unexpected keyword argument 'logdir'" error.
=> fix(doc) : fix API demo of debugger V2

RELEASE.md, tensorboard/version.py
Two commits to round out the 2.5.0 release process:
- Bump tb-nightly version to 2.6.0a0
- Cherrypick of 2.5.0 relnotes added to RELEASE.md
=> Post-release 2.5.0

tensorboard/BUILD
Summary:
The `RequestContext` type is already public via `plugin_util.context`.
Some plugins need to access it directly to create a background context,
as done in the projector plugin or tensorflow/profiler#298. This module
is designed as a public API, so it can be made globally visible.
Googlers, see <http://cl/368909135>.
wchargin-branch: context-public
=> visibility: make `tensorboard.context` public

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
In a rare case, the ScalarCardComponent does not read the correct value
from the `newLineChart && newLineChart.getIsViewBoxOverridden()` causing
the fit-to-domain button to have the wrong state (enabled when it should
be disabled). This bug was identified in our screenshot based test where
this hard to reproduce timing issue was found.
Fixed the issue by manually propagating the view box overridden state
using the `Output()` which seems to have made the screenshot test very
stable (150 runs).
Relates to b/185595590.
=> timeseries: fix fit-to-domain state issue

tensorboard/webapp/webapp_data_source/tb_http_client.ts
Currently, we manually typed the bodies of `put` and `post`. Instead, we
want to extend that of the `HttpClient` so we now do that.
=> types: improve TbHttpClient types

tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
As part of the Closure compiler cleanup, we are asked to remove the dep.
Relates to cl/369541878.
=> infra: remove the closure/goog/deps.js dep

tensorboard/webapp/metrics/views/card_renderer/card_view_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
Internal Angular compiler caught this bug correctly and noted that the
`runColorScale` is no longer an input to the `scalar-card`. This change
addresses that.
=> sync: fix the unknown input `runColorScale` issue

tensorboard/webapp/header/plugin_selector_component.scss
TensorBoard customizes the material tab header component to have less
visual jank and have consistent behavior as the Polymer based
TensorBoard. This caused the scroll calculation to be incorrect (about
36 * 2 pixels) and a plugin like "text" where the tab label is very
short caused the bug to manifest quite obviously.
This change fixes that by changing how the mat-header is styled by
overriding few of its internals.
Fixes #4841.
=> core: fix the header pagination

tensorboard/plugins/hparams/BUILD
hparams_utils is a binary. Make its building rule publicly visible to allow other rules to depend on it (e.g. to package it).
None.
=> Making hparams_utils publicly visible

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/BUILD, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
In #4890, we incorrectly fixed the issue where scalar-card-component
does not update its DOM based on changes.
Background
----------------
while gory details are not yet known personally to me,
Angular, roughly speaking, has very strict condition in which it will
update the DOM. To name a few I know, they are (1) browser event, (2)
async (e.g., setTimeout), and (3) async pipe. In the earlier change, we
assumed that the `@Output` is one of them but it does not appear so.
Assumption
---------------
Angular updates DOM top to bottom (component tree wise) and
even if child component communicate information upwards when it mounts,
it _can_ be too late for parent component to actually apply the update
to the DOM.
Fix: we now use the AsyncPipe and Observable to communicate the
information …
=> timeseries: correctly fix fit-to-domain

tensorboard/webapp/header/plugin_selector_component.scss
To fix the wrong width calculation on the mat-tab-header, we use a weird
technique with opaque background. The color we picked wrongly set the
`700` causing a visual jank in an internal version.
Was able to confirm that omitting `700` suffices.
Example of the bad color:
=> core: fix the plugin selector color

tensorboard/plugins/core/core_plugin.py, tensorboard/plugins/core/core_plugin_test.py
We want to read the note content in BE. The design is to bundle the note json file with webfile. Thus we have /notifications_note.json to redirect to.
- return .json if notifications_note.json present.
- If the file is absent, the return is 404, error of which is caught in notification_center component (_data_source/ to be specific)
- for OSS and .dev, this endpoint should never be called
=> what's new: utilize redirect for BE to read note  json file

tensorboard/defs/internal/html.bzl, tensorboard/defs/web.bzl, tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD, tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java, tensorboard/plugins/graph/tf_graph_app/BUILD, tensorboard/plugins/projector/tf_projector_plugin/BUILD, tensorboard/plugins/projector/vz_projector/BUILD, tensorboard/webapp/BUILD
TensorBoard no longer uses JSCompiler in a meaningful way. For the most
TypeScript/JavaScript source, we use rollup via rules_nodejs. Hence, we
now remove the JSCompiler portion from the Vulcanization.
Soon after, vulcanize.bzl will be completely removed accordingly.
=> infra: remove JSCompiler from Vulcanize

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts, tensorboard/webapp/app_routing/internal_utils.ts, tensorboard/webapp/app_routing/internal_utils_test.ts, tensorboard/webapp/app_routing/programmatical_navigation_module_test.ts, tensorboard/webapp/app_routing/programmatical_navigation_types.ts
When wanting to navigate to a compare route with a programmatical API,
we need to form the navigation parameter correctly, knowing its encoding
scheme. Not wanting to leak the business logic for encoding alias and
id, we now changed the interface for the compare route navigation with a
translation to an AppRouting Route in the AppRouting effects.
=> routing: improve compare navigation

tensorboard/uploader/uploader_subcommand.py, tensorboard/uploader/uploader_subcommand_test.py
Ensure that both name and description are returned when using the tensorboard dev list command.
A recent refactoring that enforced a more consistent use of the fieldmask wasn't aware of this call site, and we had no tests.
=> Ensure name and description are set in the exporter mask

tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
In the new GPU line chart, we were using the `addAttribute` API of
three's which is now throwing a deprecation warning on the console when
testing. This change uses the new `setAttribute`.
=> cleanup(line-chart): use un-deprecated API

tensorboard/uploader/BUILD, tensorboard/uploader/uploader_subcommand.py
--one_shot uploading should work for non local filesystem
Googlers, this is internal bug b/186244973
=> Fix `--one_shot` for remote file system.

tensorboard/webapp/BUILD, tensorboard/webapp/core/effects/BUILD, tensorboard/webapp/core/effects/core_effects.ts, tensorboard/webapp/deeplink/BUILD, tensorboard/webapp/deeplink/hash.ts, tensorboard/webapp/tb_polymer_interop_types.ts, tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
Currently, the Polymer interop components like `tf-storage` are poorly
typed. While we try to type them better, they are not properly
typed/annotated that more advanced compiler wrongly mangles the symbol.
This change makes the interop components Klutz friendly.
=> type: better type Polymer-Angular interops

tensorboard/webapp/hparams/_redux/utils.ts, tensorboard/webapp/hparams/_redux/utils_test.ts
The utility used in the selector was mutating the list of experimentIds
passed. This is not an allowed operation especially in the view where
this selector was being used and experimentIds was passed as a prop.
=> hparams: prevent experimentIds mutation

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/routes/dashboard_deeplink_provider.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
After launching the GPU line chart, we now disallow falling back to the
old Polymer based implementation.
=> deflag: remove enableFastChart feature flag.

tensorboard/data/server/cli.rs, tensorboard/data/server/disk_logdir.rs, tensorboard/data/server/logdir.rs, tensorboard/data/server/run.rs
Summary:
For `--port-file` and `--error-file`, we only need output data to be
flushed to the operating system, not to actual disk. In addition to
making things a bit faster, `/dev/null` can now be used with these
arguments without raising `EINVAL`.
Uses not in `cli.rs` are all in tests.
Test Plan:
Running the data server with `--logdir /tmp/foo --port-file /dev/null`
now works as desired, and normally running `tensorboard` works, too.
wchargin-branch: rust-flush
=> rust: switch `sync_all` calls to `flush`

tensorboard/webapp/app_routing/types.ts, tensorboard/webapp/experiments/types.ts
- experiments/types which is used to type the backend response should
not be mangled.
- route parameter, since defined as strings in the route configurations,
cannot be mangled.
=> types: declare types to be public

tensorboard/webapp/app_routing/route_registry_module.ts, tensorboard/webapp/app_routing/route_registry_module_test.ts
tensorboard.dev will set up a `Not found` page for all unknown routes by default.
=> routing: permit registering RouteKind.UNKNOWN

tensorboard/plugins/core/core_plugin.py, tensorboard/plugins/core/core_plugin_test.py
This fixes the `/data/notifications` redirect (to `../notifications_note.json`) so that it is preserved over the wire to the browser as a relative path, rather than being normalized by the server into an absolute URL.
Werkzeug, our HTTP request/response framework, does this normalization automatically to be "RFC conformant", but that's outdated; the current HTTP/1.1 RFC does [explicitly allow relative paths](https://tools.ietf.org/html/rfc7231#section-7.1.2) and browser support is apparently not an issue per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location).  We don't want the redirect to be normalized because that bakes the incoming request URL as seen by the WSGI app into our HTTP response, but that isn't necessarily the right URL for the browser to use if our …
=> core: fix relative redirect for /data/notifications

tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts, tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
Change the api path for reading the notification note file.
We only have one note file per environment and it should be a fixed path and should not depends on the experiment id params etc.
Now we called `....com/experiment/:id/data/notification` and it will direct to `....com/experiment/:id/notifications_note.json`
while what we actually want is  call `....com/data/notification` and redirect to  `....com/notifications_note.json`
=> what's new: adjust notification api path to absolute path

tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
This change is a follow up to #4929 where we are:
- adding a test for reload actions whilst the plugin is inactive
- adds `changePlugin` as a condition for refreshing the data to follow the
timeseries.
=> debugger-v2: refresh data on change plugin

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/bootstrap.ts, tensorboard/webapp/dev_assets/main_dev.ts
Angular component-based dashboards currently fail to render. The
JS error at runtime points to the lack of an import of Angular's new
"localize" module, required for applications using Ivy and Angular 9+.
See https://angular.io/guide/migration-localize for details.
Note that the `//tensorboard:dev` target is fine. For some reason,
only the "prod" target `//tensorboard` is affected.
Manually tested by running `bazel run tensorboard -- --logdir logs --bind_all`, opening the 'Time Series' dashboard, and seeing the panel appear.
Googlers, see test sync cl/372052576
=> Fix broken Angular dashboards in need of localization module

tensorboard/webapp/notification_center/_data_source/backend_types.ts, tensorboard/webapp/notification_center/_views/notification_center_component.ng.html, tensorboard/webapp/notification_center/_views/notification_center_component.scss, tensorboard/webapp/notification_center/_views/notification_center_test.ts
Remove full note link button when there is not
- add attribute in BE type
- render <a> only when the attribute shows
- if not, the `extended-button` element still renders for css convenience (need margin at the bottom of the menu)
TODO: valid link based on the future requirement (open new page or new route for the full note) 
without link
with link
click full note link (test link)
https://user-images.githubusercontent.com/1131010/116291559-92aa0800-a749-11eb-98a7-0959464696be.mov
=> what's new: add full note link attribute

.github/workflows/ci.yml, third_party/rust.bzl
Summary:
Rust 1.52 is out! The [release notes] have the rundown, but I’m excited
in particular for [`str::split_once`] and a [caching fix for Clippy].
[release notes]: https://blog.rust-lang.org/2021/05/06/Rust-1.52.0.html
[`str::split_once`]: https://doc.rust-lang.org/std/primitive.str.html#method.split_once
[caching fix for Clippy]: https://github.com/rust-lang/rust-clippy/issues/4612
wchargin-branch: rust-v1.52.0
=> rust: upgrade to Rust 1.52.0

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_types.ts, tensorboard/webapp/runs/store/testing.ts, tensorboard/webapp/runs/types.ts
This change simply readies the runs redux state from understanding the
notion of the color grouping.
=> runs: add groupBy enum and state to the reducer

tensorboard/webapp/runs/store/runs_reducers.ts
Runs reducers no longer contain the hparam and metric filters yet we
still were providing their default values. This change removes it and
removes type casting which is faulty.
=> cleanup: remove vestigial hparams from runs reducer

tensorboard/components/experimental/plugin_util/BUILD, tensorboard/components/experimental/plugin_util/core-host-impl.ts, tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts, tensorboard/components/tf_storage/storage.ts, tensorboard/webapp/tb_polymer_interop_types.ts
Currently, `getURLPluginData()` always returns empty data, because its
code path has `useHash() === false`. "core-host-impl.ts" directly imports
Polymer's `tf_storage_utils`, producing a separate scope with state that
is not shared with the Polymer side. When `deeplink/hash.ts` sets the flag
via `document.createElement('tf-globals').tf_globals.setUseHash(true)`,
the variable that updates is different from the one that is read by the
plugin host.
This change makes the plugin host read Polymer state via manually
instantiating a Polymer CustomElement, rather than via direct import.
Googlers, see b/187854773 and test sync cl/373276716
For reference, there are 2 ways for an Angular TS module to use a Polymer TS module.
A) direct import
```ts
import * as globals from 'tf_globals'; …
```
=> plugin-api: fix getURLPluginData()

tensorboard/webapp/notification_center/_views/notification_center_component.ng.html, tensorboard/webapp/notification_center/_views/notification_center_component.scss
Suggesting a few small tweaks to make it a little easier to read the contents:
- Widens the dialog from 280px to 350px (the 350px width was being suppressed due to mat-menu-panel max-width)
- Adjusts font sizes to be 13px throughout for consistency w/ rest of TB in body text (e.g. run selector uses 13px, so does the "data location").
- Use a more coarse-grained date format. Including the exact time of the notification is a little misleading since it suggests a precision that we don't really support (since the notification isn't "held back" until that time, and the push isn't going to happen at the exact time of the notification). If we have more time-critical notifications in the future we could always revisit, and the full timestamp is available as a tooltip still.
Before:
After:
=> what's new: small cosmetic changes to improve readability

docs/design/rustboard.md
Summary:
This shipped to users in TensorBoard 2.5.0 and is on by default. We’ve
heard of a few issues but nothing show-stopping, so it seems appropriate
to update this status accordingly.
wchargin-branch: rustboard-status-shipped
=> docs: mark RustBoard status as shipped

tensorboard/components/experimental/plugin_util/BUILD
Internal targets are currently broken by the sync because of
attempts to load lodash 2x. This removes the dep on tf_storage
from the Angular plugin host module, leaving no more than 1
place where tf_storage is included in the Blaze dep path.
Test sync cl/373696993
=> Fix sync by removing tf_storage dep

tensorboard/plugins/text/summary_v2.py
Fixes: https://www.tensorflow.org/api_docs/python/tf/summary/text
The \n is interpreted by python as a new-line.
When building the site, we dedent the text. After that newline there is zero indentation.
0 is the floor, so none of the text is dedented.
When converted to markdown the 4-space indent is interpreted as preformatted text.
=> Use an r-string so the \n doesn't break the site.

tensorboard/webapp/app_routing/app_routing_module.ts
In a couple Google-internal CLs (including one I'm now working on) we've noticed that RouteRegistryModule has to be imported whenever AppRoutingModule is imported. This is because RouteRegistryModule is a runtime dependency of AppRoutingModule's features. Instead AppRoutingModule should import RouteRegistryModule directly.
=> Import RouteRegistryModule from AppRoutingModule since it is a runtime dependency.

tensorboard/webapp/routes/dashboard_deeplink_provider.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Currently, the feature flag is not configurable via URL and this change
enables the serialization and deserialization of the flag.
=> flag: add feature flag for enableColorGroup

package.json, yarn.lock
Commands done:
- `yarn upgrade`
- `yarn upgrade -L karma @bazel/karma`
Do note that we had karma version pinned to quite the old one which had
several CVEs open on the downstream dependencies.
This change also fixes the incremental builds of the test where we no
longer get `EPIPE` error.
=> infra: upgrade dependencies

tensorboard/webapp/widgets/filter_input/filter_input_component.ts, tensorboard/webapp/widgets/filter_input/filter_input_test.ts
The sync broke in https://github.com/tensorflow/tensorboard/pull/4938
because of property renaming-related errors. This change also fixes a
minor lint warning.
Test sync cl/374274713
=> Fix sync errors about property renaming and linting

tensorboard/webapp/core/core_module.ts, tensorboard/webapp/core/store/core_initial_state_provider.ts, tensorboard/webapp/core/store/core_initial_state_provider_test.ts, tensorboard/webapp/core/views/hash_storage_component.ts, tensorboard/webapp/core/views/hash_storage_test.ts, tensorboard/webapp/deeplink/BUILD, tensorboard/webapp/deeplink/deeplink_module.ts, tensorboard/webapp/deeplink/testing.ts, tensorboard/webapp/deeplink/types.ts, tensorboard/webapp/testing/BUILD, tensorboard/webapp/testing/integration_test_module.ts
Some cleanup surrounding DeepLinkModule:
* DeepLinkerInterface is the provided token and HashDeepLinker is the implementation that the Module provides for that token.
* References to HashDeepLinker have been removed from the remainder of the code base. They use the DeepLinkerInterface instead.
* The TestableNoopHashDeepLinker has been refactored out of IntegrationTestModule to a shareable location. It's not used by anything currently in this code base but will be used by Google-internal code.
=> Cleanup how HashDeepLinker is provided in prod and test code.

tensorboard/webapp/settings/BUILD, tensorboard/webapp/settings/settings_module.ts
Settings module reads states from the Core feature. This change adds
"explicit" dependency on it.
=> settings: add dependency on CoreModule

tensorboard/webapp/runs/actions/runs_actions.ts, tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts
This change implements the color reassignment when the groupBy state
changes.
Product consideration:
- while we can keep the run color override, we are starting by resetting
all the manual changes for now.
=> runs: re-assign colors on runGroupByChanged event

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
With this change, we now modify the URL before `navigated` is fired so
all the downstream can send request right away without having to confirm
that the route change is indeed reflected in the URL bar.
Context: previously, our router modified the URL only when the
`navigated ` action is fired. Often, this action is listened to by many
views/effects so they can do a cleanup or a data fetch for the new
route. Now, because the URL was only modified after `navigated ` is
fired, there could be a timing issues where, depending on the order of
execution, we can be making requests to the unmodified URL, causing
issues.
Now, we are changing the semantics of the `navigated` to really really
mean, 'hey, the navigation is now complete and everything is settled'.
Tested this change internally.
=> router: change URL in between navigating & navigated

tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts
Previously, we did not need to use the groupBy information in the view.
Now that we do (need to render the selected groupBy setting in the
menu), we are exposing the public API for views to read the state.
=> runs: add selector for groupBy.

tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/BUILD, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/axes.ts, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/interaction_manager.ts, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/lines.ts, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts, tensorboard/plugins/hparams/tf_hparams_query_pane/BUILD, tensorboard/plugins/hparams/tf_hparams_types/BUILD, tensorboard/plugins/hparams/tf_hparams_types/types.d.ts
Bug
---
Previously, we were setting the width of the container based on count of
all hparams and metrics without considering the visibility. This had
caused the UI to be in very awkward state where each visible hparams and
metrics are spaced a lot even if the selection count is quite low.
Fix
---
We layout the parallel coordinates based on number of visible
{hparam,metric}s. The change is a bit larger because:
- I had to add type information and refactor it a little for
understanding the code (minimally added the types).
- Undo the performance optimization where we do not mutate the layout
unless important piece of information in the configuration has
changed. To detect the old configuration vs. new configuration, we
have to now remember an additional state in the component.
Fixes #3414. …
=> hparams: fix the parallel coordinate layout

tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Prepares for a TensorFlow change which will make tf.constant run an op, which would otherwise have upset the assertions in this test.
=> Move constant creation in debugger_v2_plugin_test

tensorboard/webapp/BUILD, tensorboard/webapp/runs/views/runs_table/BUILD, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_component.ts, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts, tensorboard/webapp/testing/mat_icon_module.ts, third_party/js.bzl
This change introduces:
- checkbox for displaying the selected groupBy setting
- dispatch actions when you use a menu item
With this change, now, colorBy "runs" and "experiments" are functional.
=> runs: fully implement color group by UI

tensorboard/webapp/metrics/BUILD, tensorboard/webapp/metrics/data_source/BUILD, tensorboard/webapp/metrics/data_source/metrics_data_source.ts, tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts, tensorboard/webapp/metrics/data_source/types.ts, tensorboard/webapp/metrics/internal_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/util/BUILD, tensorboard/webapp/util/local_storage.ts, tensorboard/webapp/util/local_storage_testing.ts
Background
----------
Currently, TensorBoard forgets settings (at least on the Angular side)
when browser refreshes and even for the ones that are persisted in the
URLs do not carry over to other experiments or other TensorBoard browser
tabs.
This change
-----------
This change is a part of the greater effort to mitigate the usability
issue by persisted few settings (for now) to LocalStorage. Do note that
this is not a panacea as users can change port number and the states
will be forgotten.
The DataSource API is created with hosted services in mind where we may
add a HTTP API or DataProvider API for persisting user settings.
=> timeseries: add data source for persisting setting

tensorboard/plugins/text/text_demo.py
Minor update to the text demo to match how users would
write text summaries.
Manually tested by running `bazel run //tensorboard/plugins/text:text_demo` and checked that the demo still works.
=> docs: update text demo

tensorboard/plugins/npmi/csv_to_plugin_data_demo.py, tensorboard/plugins/npmi/npmi_demo.py, tensorboard/plugins/npmi/npy_to_embedding_data_demo.py
Minor updates that assume the TensorFlow installation is TF2.
Test plan
Did not check that the following targets: `:csv_to_plugin_data_demo` and
`npy_to_embedding_data_demo`, since I do not have a valid csv/npy file
for the plugin.
Manually checked that `bazel run //tensorboard/plugins/npmi:npmi_demo`
still produces a logdir that properly renders in TensorBoard when adding
`?experimentalPlugin=npmi` to the TensorBoard URL.
=> docs: update npmi demo

tensorboard/webapp/app_routing/deep_link_provider.ts
Interfaces should have JSDoc.
Just adds JSDoc.
=> Add JSDoc to DeepLinkProvider interface definition

tensorboard/plugins/image/BUILD, tensorboard/plugins/image/images_demo.py
Update the images demos to ensure they are TF2 (rather than TF1) APIs.  
Additionally simplify the demo so its easier to understand and only highlight how to use the summary writer.  For a deeper investigation/instruction in how to use images in an ML system, refer to the images tutorial: https://www.tensorflow.org/tensorboard/image_summaries
The embedded plugins/<plugin_name>_demo.py are intended primary to create representative data for testing dashboards rather than for being canonical ML pipelines.
Reference image of the new demo output:
=> Update images_demo to be TF2-friendly, and simpler.

tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts
PR #4966 inadvertently changed the order of the spread operations and
changed the test specs changing the desired behavior.
This change restores it and makes the color override win over the
default value.
=> runs: fix the colorMap override feature

tensorboard/webapp/metrics/data_source/metrics_data_source.ts
`unsanitizedObject` was typed as a Record or just an object whose
property we are trying to access. To make it survive the mangling, we
need to supply proper typing information for the `JSON.parse`d object
which is now assigned as `SerializableSettings` which is capable of
surviving the mangling (`declare`d).
This change unblocks the sync.
=> sync: fix object property accessor

tensorboard/webapp/metrics/data_source/BUILD, tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts
toPromise is deprecated checked by tslint. use lastValueFrom or firstValueFrom. Choose lastValueFrom.
=> core: toPromise is deprecated. use lastValueFrom instead

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/effects/BUILD, tensorboard/webapp/metrics/effects/index.ts, tensorboard/webapp/metrics/effects/metrics_effects_test.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts
This is a continuation of #4991 where we are attempting to persist
several settings from TimeSeries to improve frustrating user experience
of having to reset settings over and over.
This change integrates the DataSource with the MetricsEffects so persist
new settings when it changes and bootstrap the application state from
the state in the LocalStorage.
Product choice: this change persist the smoothing value user may provide
in the URL since it felt more natural that way.
=> timeseries: persist and read settings

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts
When the extents are small and is close to 0, we were falling into the
case where major axes were missing and minor axis formats were simply
off. They were supposed to have truncated number but instead had
`.…0000535` because we were removing common prefix between "0" and
"0.0000535" and blindly adding `…` in it.
This change addresses the corner case by adding test specs and special
casing major ticks being `0`s.
Previous:
New:
=> line chart: improve major axis for numbers

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/BUILD, tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts, tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
Previously, we were showing close to the "raw" value in the tooltip
often leading to very long nonsense especially with the floating point
math errors. The impact of said errors are often seeing a number like
'0.3000000000004' where the last digit `4` often is meaningless. To work
around this, we are using d3.format to remove unnecessary precision
which just often adds visual noises.
=> timeseries: improved formatting on tooltip

tensorboard/plugins/scalar/scalars_demo.py
Updates scalars demo to use TF2 conventions.
Somewhat of a major update.
Manually tested by running `bazel run tensorboard/plugins/scalar:scalars_demo` and checked that the demo works and produces standard visual output.
=> docs: update scalars demo

tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/demo.py, tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/demo.py
Minor updates to example plugin demos to assume that
TF1 is no longer used.
=> docs: update example plugin demos

tensorboard/plugins/audio/audio_demo.py
Updates the audio_demo
- TF1 to TF2 style
- More minimal
Test plan
Manually ran the demo with `bazel run //tensorboard/plugins/audio:audio_demo`, opened TensorBoard and saw that the audios appeared properly.
=> docs: update audio demo to TF2

tensorboard/webapp/metrics/data_source/BUILD
metrics_data_source_test now has dependency on the @ngrx/store/testing.
=> sync: add missing ngrx/store/testing dep

tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
When a `<runs-table-component>` has height = 100px, the .table-container
also had height = 100px which is not what we intended. We intended it to
have 100px - heightOfFilterRow. We now use the proper flex syntax for
the proper layout.
This purely visual bug is hard to test in unit test and will be covered
via screenshot tests internally.
Fixes #5019.
=> timeseries: fix runs table scrollable issue

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts, tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts, tensorboard/webapp/runs/store/runs_types.ts, tensorboard/webapp/runs/store/testing.ts
When we work on our setting persistence, we want to be able to change
our default behavior. However, if we always persist the groupBy value in
the store to the URL, current business logic will be ingrained into
every dashboard URLs and its bookmark can lead to a case where we cannot
change our default behavior.
this change simply refactors so initial value of `groupBy` is separated
from the overridden value.
=> runs: create groupBy override vs. initial value

tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
Recently [1], we introduced a `<tb-input-filter>` component that replaced
the runs selector's filter input field in Time Series. That change included a
regression where the input's click target was no longer full width.
This change restores the full width click target.
Manually ran `bazel tensorboard:dev` and checked that clicking in the
space to the right of the placeholder text still focuses the run selector's
input field in the Time Series dashboard.
This bug was discovered in an offline bug hunt.
[1] https://github.com/tensorflow/tensorboard/pull/4938
=> runs: fix run filter click target width

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/utils.ts, tensorboard/webapp/runs/store/utils_test.ts, tensorboard/webapp/runs/types.ts
Color groups the runs by regex. No UI/UX involved.
- Match regex with name (not id)
- Construct the group key by the capture groups connected with '_'
- If there are no capture group, use the matched string as the group key
- if there are no capture group, use keyword `matches` to group all matched runs
- check invalid regex
- check empty input
=> color grouping: group runs by regex

tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss
This change makes the runs table header sticky to the scrollable
container.
Tested sync and it exhibits no discernible visual changes at all.
=> timeseries: keep runs table header sticky

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Currently, TimeSeries or the new line chart uses scientific notation for
display steps. Steps being a very integral number, SI number often is a
better fit. This is what traditional TensorBoard used to do, too.
=> timeseries: use SI unit for STEP axis

tensorboard/webapp/BUILD, tensorboard/webapp/customization/BUILD, tensorboard/webapp/customization/customizable_component.ts, tensorboard/webapp/customization/customization_module.ts, tensorboard/webapp/customization/customization_test.ts
CustomizableComponent enables **dynamic customization** of components without having every single layer above it being aware of the change (see [Angular InjectionToken](https://angular.io/api/core/InjectionToken) for more details).
This is the first break-down step of @bmd3k's prototype for the customization approach. 
Example usage:
1. Define a customizable Component, for example adding a button:
```
const CustomizableButton = new InjectionToken<Type<unknown>>('Customizable Button');
```
2. Where the customization point is desired, use `tb-customization` component to wrap some default behavior with the `[customizableComponent]` attribute:
```
<tb-customization [customizableComponent]="customButtonIfProvided">
<div>There is no button by default.</dev>
</tb-customization>
```
3. In the …
=> infra: add customization component

tensorboard/webapp/customization/BUILD
Explicit dependency `//tensorboard/webapp/angular:expect_angular_core_testing` for `import @angular/core/testing` is necessary for Google, (even thought it's not required for OSS).
=> Fix BUILD for @angular/core/testing import.

tensorboard/webapp/metrics/store/metrics_initial_state_provider.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/types.ts, tensorboard/webapp/routes/dashboard_deeplink_provider.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
Background: currently, from view's and deep linker's perspective, there
is no way to discern a setting that was overridden vs. default. This
makes the deep linking particularly finicky since, if a different
application provides a different default for smoothing, for example, it
will show up in the deep link as it does not match OSS's default 0.6.
Change: this change separates default away from overrides while making
it largely transparent to views.
=> metrics: separate default settings from override

tensorboard/webapp/styles.scss, tensorboard/webapp/theme/_tb_theme.template.scss
Currently, loading the tb_themes SASS module re-creates Angular material
theme style rules and cause Angular inline CSSes to repeatedly include
those styles when the component actually use those material components.
=> styles: refactor how material comps are styled

docs/_index.yaml
Adds a button alongside the "Get Started" button, but to TensorBoard.dev.   Mostly for SEO.
=> Add button to TensorBoard.dev from main page.

tensorboard/plugins/projector/BUILD, tensorboard/plugins/projector/projector_demo.py
This slims down the projector plugin using totally fake data, rather than training a real embedding, so that it can be run much more quickly and easily.  As such we convert it from using a `tf.Checkpoint` to just providing the `tensor.tsv` file of tensor data.  The realistic walkthrough is still available as the full tutorial here: https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin
The fake embedding is just generated by using length-26 vectors representing which ASCII lowercase letters appear in the label, so "proximity" in the vector space is roughly representative of "how similar is the letter distribution of these two words".  This generates something that at least looks roughly plausible in PCA (full screenshot below).  It's quite likely that with a little more …
=> projector: simplify demo using fake data

tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
We are not actually ready to turn on the feature in OSS for people who
are using media query and is using tb-nightly regularly. Until we are
more ready with integration tests, we will disable the media query based
automatic enablement of the dark mode feature.
mode feature
=> dark mode: disable media query based feature

tensorboard/components/tf_dashboard_common/dashboard-style.ts, tensorboard/components/tf_dashboard_common/tensorboard-color.ts, tensorboard/components/tf_dashboard_common/tf-option-selector.ts, tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts, tensorboard/components/tf_runs_selector/tf-runs-selector.ts, tensorboard/components/vz_line_chart2/vz-line-chart2.ts, tensorboard/plugins/scalar/tf_scalar_dashboard/tf-smoothing-input.ts, tensorboard/webapp/metrics/views/metrics_container.scss, tensorboard/webapp/plugins/BUILD, tensorboard/webapp/plugins/plugins_component.ng.html, tensorboard/webapp/plugins/plugins_component.scss, tensorboard/webapp/plugins/plugins_component.ts, tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss
This change adds SASS variable for dark theme and conditionally applies
the dark modified styles on Angular Material components. This change
also adds imperfect theme supports on the Plugin stamper.
To exemplify its functionality, we have manually fixed the scalars
plugin as an experiment and added its changes accordingly.
After this change, scalars plugin look okay.
Do note that we had to adjust the colors to use one from variable and it
will cause certain colors to adjust in a minor way that would be caught
by the screenshot tests.
=> dark mode: enable dark mode at PluginComponent

tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Internally TypeScript tool complains when an unreachable code is
detected. This is a bit too strict and we get around it by simply
commenting out unwanted code.
=> sync: remove unreachable code

tensorboard/components/tf_dashboard_common/tensorboard-color.ts, tensorboard/components/tf_dashboard_common/tf-dashboard-layout.ts, tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts, tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts, tensorboard/plugins/graph/tf_graph_common/tf-graph-icon.ts, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts, tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts, tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.ts, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts, tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts, tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts, tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.ts, tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.ts, tensorboard/webapp/theme/_tb_theme.template.scss
This change fixes the visuals of hparams, graph, mesh and profile
redirection plugin under the dark mode.
Do note that we did not attempt to have a generic solution for all
iframe based plugin since it becomes wildly more difficult to reliably
apply dark styles. Instead, we will show the default light mode which
will be quite jarring but that's the best we can do as of right now.
=> dark mode: fix hparams, graph, mesh, and profile

tensorboard/webapp/metrics/views/_common.scss, tensorboard/webapp/metrics/views/card_renderer/card_view_container.scss, tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/metrics/views/main_view/card_grid_component.scss, tensorboard/webapp/metrics/views/main_view/card_groups_component.scss, tensorboard/webapp/metrics/views/main_view/filter_input_component.scss, tensorboard/webapp/metrics/views/main_view/main_view_component.scss, tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss, tensorboard/webapp/metrics/views/metrics_container.scss, tensorboard/webapp/metrics/views/metrics_container.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss, tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss, tensorboard/webapp/widgets/filter_input/filter_input_component.scss
This change improves how TimeSeries dashboard looks under the dark mode.
It largely looks okay but the gpu line chart is a bit broken under it.
Do note that some of the color change will cause minor screenshot test failures.
For instance, we were using white + opacity for border color on TimeSeries
runs table which had to change to a opaque color.
=> dark mode: improve visuals of time series plugin

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts, tensorboard/webapp/runs/store/runs_selectors.ts, tensorboard/webapp/runs/store/runs_selectors_test.ts, tensorboard/webapp/runs/store/runs_types.ts, tensorboard/webapp/runs/store/testing.ts
One of the two color grouping by regex ui option is to align the filter run regex and color grouping regex.
Move the regexFilter attribute from ui state to data state.
=> color grouping: move regexfilter attribute from runUi to runData

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
Since we had to enable the transparency mode on the GPU line chart for
the grid line, the task got a lot easier; we just have to set the
background and color to inherit from ancestor. Yes, GPU line chart is 
snappier with alpha channel turned off but gridding and what not is very
convenient with alpha channel.
Even with the opacity, we still have to propagate it since we calculate
a concrete opaque color value for WebGL renderer and it needs to 
know the color mode in order to properly calculate the concrete color.
=> dark mode: improve GPU line chart under dark mode

tensorboard/webapp/BUILD, tensorboard/webapp/app_container.scss, tensorboard/webapp/header/BUILD, tensorboard/webapp/header/header_component.scss, tensorboard/webapp/header/header_component.ts, tensorboard/webapp/header/plugin_selector_component.scss, tensorboard/webapp/theme/_tb_palette.scss, tensorboard/webapp/theme/_tb_theme.template.scss, tensorboard/webapp/theme/_variable.scss
This change fixes the style of app-header under the dark mode.
Previously, it was a bit too bright for the dark mode and, as such, we
now use more darker material orange. This improves legibility of the
font as it increases the contrast with the white font.
=> dark mode: improve app-header under dark mode

tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
In debugger v2 reducers, we were, by mistake, modifying values of
previous state. This mistake manifested in a form of runtime error for
writing to the read-only property.
This mistake was corrected by testing with a frozen objects in the
tests. Should we make more mistakes like this in the future, we may
really want to consider requiring all reducer tests to use `deepFreeze`.
=> debugger: fix mutating object by ref in reducers

tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ng.html, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ts, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container.ts, tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts, tensorboard/webapp/widgets/source_code/source_code_component.ts, tensorboard/webapp/widgets/source_code/source_code_container.ts, tensorboard/webapp/widgets/source_code/source_code_container_test.ts, tensorboard/webapp/widgets/source_code/testing.ts
Debugger v2 currently shows read-only source code is its plugin with
monaco editor. Since the editor has its own theming APIs and semantics,
we need to pipe the information through to make it know about the dark
mode.
=> dark mode: support dark mode in the source-code

tensorboard/webapp/theme/_tb_theme.template.scss, tensorboard/webapp/theme/_variable.scss
Theme objects are created from `tb` variables like `$tb-primary`,
`$tb-accent` and others. These variables, however, may not look the best
again the dark background and we have to support different values for
dark version.
This change makes sure that the variable like `$tb-dark-primary` are
defined if it is not already defined to their light counter part,
`$tb-primary`.
This change applies the change by making the primary color a bit darker
orange, making it look better against the dark theme.
=> dark mode; allow dark theme to use different vars

tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
Now that the debugger v2 depend on the feature flag feature (dark mode
in the SourceFileContainer), we have to provide appropriate stub or
remove it in the `import` path. This change refactors how the test is
authored so we do not have to stub out selectors from other containers.
Source of the error
===================
The error of 'accessing property `defaultFlags` of
undefined' was happening reliably but was throwing in the `afterEach`
which has made the test runtime/reporter behavior flaky (when we were
lucky, the test failed and when we were unlucky, the exception slipped
through the crease). We were able to get the error reliably when run
with `runs_per_test=100` though.
More importantly, the source of the error is the structure of the test.
The unit test had imported the real sub …
=> debugger: deflake debugger v2 test

tensorboard/webapp/widgets/source_code/source_code_component.ts, tensorboard/webapp/widgets/source_code/source_code_container_test.ts, tensorboard/webapp/widgets/source_code/testing.ts
Previously, when manually tested against the only user of the feature,
the source-code component lazily created the monaco editor when the data
was present. However, as I have refactored the code a little bit, the
assumption has toppled and resulted in a bug where initial values are
not set properly. The order of events are following:
- source-code component gets mounted and `ngOnChanges` get triggered
with the theme value. Because the monaco is not fetched yet by the
container, it early returns and theme value never gets set.
- when source-code container finally loads the monaco editor,
ngOnChanges only include the value, `monaco`, and our theme applier
never gets triggered.
Fix this by detecting the condition in which we have to apply the
settings to the editor.
=> source-code: bug fix where dark mode did not apply

tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss
This change fixes link styling globally.
Unlike in other places, we decided to take a little bit more global
approach in styling the anchor elements as correct styling for all links
is a bit tedious.
This change applies the fix to the tbdev upload dialog component.
=> dark mode: fix link styling

tensorboard/webapp/theme/_tb_theme.template.scss
Color palette has a notion of `default`, `ligher`, `darker`, and `text`
and we can access the said color via name.
This change makes use of the `default` when getting the primary color.
=> dark mode: specify app-bar color via `default`

tensorboard/plugins/histogram/histograms_demo.py
Update TF1 to TF2 style
Test plan:
Manually ran the demo with `bazel run //tensorboard/plugins/histrogram:histrogram_demo`
=> docs: update histogram demo to TF2

tensorboard/webapp/widgets/source_code/editor_options.ts, tensorboard/webapp/widgets/source_code/source_code_component.ts, tensorboard/webapp/widgets/source_code/source_code_container_test.ts, tensorboard/webapp/widgets/source_code/source_code_diff_component.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container.ts, tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts, tensorboard/webapp/widgets/source_code/testing.ts
Apparently, monaco does not let each editor specify theme but rather it
is specified at the global scope: `monaco.editor.setTheme` vs.
`monaco.editor.create().setTheme()`. Interestingly, `create` method does
take an additional `theme` property so you may be able to customize it
at the creation time but when user wants to toggle dark mode and thus
circulate VS code theme, we _may_ get into trouble.
For now, this change simply fixes the breakge by properly using the API.
=> source code: fix dark mode support

tensorboard/webapp/theme/_tb_theme.template.scss
This is the final iteration of the change. Previously, we had thought
that using `default` value to `mat-color` would be sufficient but we
were incorrect.
Background is the following. In other variants of TensorBoard, we
elected to use very dark primary color. It looks nice under the light
theme but under the dark theme, its lightness is too close to that of
background so we had to make its primary default color to be light. With
previous change, now, our app-bar under dark mode would be super light
which is certainly not what we had wished.
With other hackier theme template munging set aside, now, we are
choosing to declare `app-bar` as one of special variable that can be
customized like `tb-primary` that is, when provided, will be used in the
theme object.
=> theme: allow customizable `app-bar` theme var

tensorboard/webapp/widgets/source_code/load_monaco_shim_test.ts
Previously, we were using `async/await` and arity based jasmine async
test (i.e., `(done) => {}`). This has caused the test runner to spam the
log saying there is an uncaught exception. Instead of fighting the
runtime, we can now use more contemporary API for dealing with async
(`expectAsync`; https://jasmine.github.io/api/3.7/async-matchers.html).
Example of said log spam:
> 'DEPRECATION: An asynchronous before/it/after function took a done callback but also returned a promise. This is not supported and will stop working in the future. Either remove the done callback (recommended) or change the function to not return a promise. (in spec: loadMonaco shim rejects if require.js is unavailable)'
=> chore: prevent test log spam

tensorboard/components/polymer/BUILD, tensorboard/components/polymer/dark_mode_mixin.ts, tensorboard/components/tf_dashboard_common/BUILD, tensorboard/components/tf_dashboard_common/tensorboard-color.ts, tensorboard/components/tf_dashboard_common/tf-dashboard-layout.ts, tensorboard/plugins/graph/tf_graph/BUILD, tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts, tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts, tensorboard/plugins/graph/tf_graph_common/BUILD, tensorboard/plugins/graph/tf_graph_common/tf-graph-icon.ts, tensorboard/plugins/graph/tf_graph_controls/BUILD, tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts, tensorboard/plugins/graph/tf_graph_info/BUILD, tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts, tensorboard/plugins/graph/tf_graph_op_compat_card/BUILD, tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/BUILD, tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts, tensorboard/plugins/hparams/tf_hparams_table_view/BUILD, tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts, tensorboard/webapp/core/views/dark_mode_supporter_container.ts
Firefox does not support `:host-context()` selector which is crucial for
the Polymer theme support. To work around it, we are introducing a
mixin that grabs a value from the `body` and append a class name
accordingly.
=> dark mode: fix UI in Firefox

tensorboard/plugins/projector/vz_projector/BUILD, tensorboard/plugins/projector/vz_projector/data.ts, tensorboard/plugins/projector/vz_projector/knn.ts, tensorboard/plugins/projector/vz_projector/knn_test.ts
There were several issues with the code.
1. `Tensor.prototype.transpose` symbol no longer exist. Replaced it with
`tf.transpose` instead.
2. KNN reuse was flawed as reused version would return a different
number of outputs than what it would return normally.
3. `tf.split` expects all returned members to have the equal size where
it previously could not guarantee that. We now pad the matrix so the
equal size can be formed even if we discard useless padded elements.
In the future, we may want to disable GPU based computation acceleration
as it is actually slower than just doing it on CPU.
=> projector: fix broken KNN

.github/workflows/ci.yml
With the latest nightly (20210616), TensorBoard CI fails because hparams
API fails to load properly when importing TensorFlow inside TensorBoard
project.
Specifically, below fails.
```sh
cd tensorboard
python
>>> import tensorflow as tf
```
This may have to do with summaries are exported under TensorFlow and
requires a bit more precise diagnosis. Until then, we will pin the
tf-nightly to the last good version.
Suspected breaking change: https://github.com/tensorflow/tensorflow/commit/2e6acf753381cb7902017bcab03e204bb41b7091
=> ci: pin tf-nightly to 20210614

tensorboard/plugins/histogram/summary_v2.py
Reverts tensorflow/tensorboard#5066. Broke AutoOutsideCompilationWithKerasTest in internal CI: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/tests/automatic_outside_compilation_test.py
Needs further investigation before relanding.
=> Revert "histogram: avoid data transfer overhead for TPU outside compilation"

tensorboard/webapp/feature_flag/effects/BUILD, tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts, tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts, tensorboard/webapp/feature_flag/store/BUILD, tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/testing.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We want to slowly enable the dark mode based on media query on
app-by-app basis. This change allows each application to configure 
whether the media query based dark mode is possible.
=> feature flag: add flag for controlling dark mode

tensorboard/webapp/header/header_component.scss
Previously, we set the global anchor element style to appeared blue and
purple (for visited links). This has impacted how links are drawn in the
header which we wanted to keep as white (for saliency with the header
color).
For un-visited links, this should have no changes but will change
visited links back to our normal color.
=> theme: color all links in header as white

tensorboard/plugins/projector/vz_projector/BUILD
Internally, libraries like UMAP and threejs are loaded a bit differently
and the proxy genrule allows us to precisely add and side load the
runtime dependencies.
=> projector: allow lib to be side loaded

tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/widgets/range_input/range_input_component.scss
Runs table was sparingly use tf-slate which was looking quite odd in the
dark mode. Instead, we now use the lighter mat-grey while the main
content is the same as the default background color.
This change also includes dark-themification of range-input which was
forgotten before.
=> dark mode: improve style of range_input & run table

tensorboard/components/vz_line_chart2/line-chart.ts
Please see #5077 for more details. Because of the tight tolerance,
Plottable was setting `visibility: hidden` on the axis label when it
really shouldn't since we have sufficient space.
Fixes #5077.
=> scalar: fix axis label on Firefox

tensorboard/pip_package/setup.py
With `python_requires`, we can disallow other versions of Pythons from
installing TensorBoard. Removal in the earlier change was done without
completely understanding its intent.
=> pip: explicitly require Python 3.6 above

tensorboard/plugins/distribution/vz_distribution_chart/vz-distribution-chart.ts, tensorboard/plugins/histogram/vz_histogram_timeseries/BUILD, tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.ts, tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/run_name_component.scss
- Histograms: hover color and default outline color are now more dark
mode friendly. Hover colors are white while outline colors are more
subdued.
- Distribution: axes are now visible
- Time series: histograms' and image cards' subtitles are now properly
colored
Before
After
Before
After
Before
After
=> dark mode: improve viz UX under dark mode

tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
In our first phase we only want to show color group by run and by experiment. This pr temporary removes "group by regex". The pr is needed for launch our first phase and for the screenshot tests. The "group by regex" would be brought back when we have a clear plan on the wording and the educational tutorial for this more advanced feature.  (and the item would be added under another feature flag)
In the tests, either last item in an array is removed or the whole test case is commented.
=> color grouping: temporary remove regex

tensorboard/plugins/hparams/BUILD, tensorboard/plugins/hparams/_keras.py, tensorboard/plugins/hparams/_keras_test.py, tensorboard/plugins/hparams/api.py, tensorboard/plugins/hparams/api_test.py
This renames the `keras.py` module within the hparams plugin directory to `_keras.py` (prefix with an underscore), to avoid an import collision with the widely used `keras` package, and resolve the failure that we had to circumvent https://github.com/tensorflow/tensorboard/pull/5068.
Background: unfortunately, the way Python import resolution works, the directory of the original script that the interpreter is executing is automatically placed first in `sys.path`, so sibling modules that match the names of modules your code tries to import will magically take precedence over third-party pip-installed modules that are found later in `sys.path`.  [PEP 328](https://www.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports) halfway-fixed this by ensuring standard library modules are …
=> hparams: rename keras.py to avoid import collision

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/notification_center/_views/notification_center_component.scss, tensorboard/webapp/widgets/range_input/range_input_component.scss
Sass 1.33.0 deprecates usage of the '/' forward slash character as a
math division operator [1]. We expect a future release to remove it.
According to [2], TensorBoard is still using Sass 1.32.8 from Bazel, but
internal efforts motivate us to be ready for the upcoming Sass changes
sooner.
This fixes existing uses of '/' to use the '*' multiplication operator
instead, for now. Unfortunately there is no enforcement of avoiding the
slash-as-division until we either upgrade the Sass version used via
Bazel.
Googlers, see also cl/380056496, b/189862812
[1] https://sass-lang.com/documentation/breaking-changes/slash-div
[2] https://github.com/tensorflow/tensorboard/blob/master/WORKSPACE
=> Avoid using slash as division in sass

tensorboard/webapp/core/effects/core_effects.ts, tensorboard/webapp/core/effects/core_effects_test.ts
Polymer based TensorBoard is unaware of notion of an experiment and to
naively support it, we have made changes to the runs endpoint so it
returns a unique name of a run per experiment by prefixing name of an
experiment. However, it is not as simple as just that.
Because name of an experiment can be arbitrary large and can contain
illegal character like "/", we have a notion of alias per experiment.
The run-selector is unaware of anything experiment simply knows about
list of run names (not ids) and communicates with other Polymer based
components using the run names. As a result, whenever alias changes, we
need to refresh the runs data and reload the whole Polymer dashboard so
all components display and speak the same run name.
This change triggers Polymer run load whenever alias …
=> core: fetch runs when alias changes

tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/store/testing.ts
This change enables the dark mode in OSS. The feature will turn on by
default when user's browser says they prefer the dark mode.
The feature can be mnaually turned off with `?darkMode=false`. In the
future, we will add a button that lets user toggle the dark mode in the
header.
=> dark mode: enable media query based dark mode

.github/workflows/ci.yml
Reverts the pinning part of https://github.com/tensorflow/tensorboard/pull/5068 now that we have a durable workaround from #5085, while preserving the refactoring that allows us to pin our TF version without needing to update the CI required checks configuration on GitHub.
=> ci: unpin tf-nightly (from 20210614)

tensorboard/webapp/app_routing/internal_utils.ts, tensorboard/webapp/app_routing/internal_utils_test.ts
RouteId is a unique opaque identifier for a route. Previously, we
included display names as part of the unique identifier but we decided
to drop it for improve the UX.
Specifically, we would like to be able to let user change display name
dynamically without causing a routeId changes (which will cause router
to actually do a route change).
=> route: omit displayName from routeId.

tensorboard/components/experimental/plugin_lib/BUILD
Bazel users with access to the TensorBoard workspace from their
repo now have visibility into `ts_library`-like targets for importing
the experimental plugin library, which were previously not
Bazel-public.
=> plugin-lib: expose plugin lib for consumption

tensorboard/webapp/app_routing/internal_utils.ts, tensorboard/webapp/app_routing/store/app_routing_selectors.ts, tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts, tensorboard/webapp/app_routing/types.ts, tensorboard/webapp/core/effects/core_effects.ts, tensorboard/webapp/core/effects/core_effects_test.ts
In certain variants of TensorBoard, there are no routes defined for the
router. In this case, the application assumes that the backend knows how
to attain experiment id from the URL and, thus, we should assume that it
is about the same as RouteKind.EXPERIMENT. Because we have a strict
filter on fetching runs and plugins listing for only dashboard route
kinds, the legacy flow is broken so we would like to reinstate some part
of that by formalizing "no routes set" which is defined with RouteKind
=== RouteKind.NOT_SET.
Test sync: cl/381353956
=> core: fix data load when there are no routes

tensorboard/webapp/core/actions/BUILD, tensorboard/webapp/core/actions/core_actions.ts, tensorboard/webapp/core/store/BUILD, tensorboard/webapp/core/store/core_selectors.ts, tensorboard/webapp/core/store/core_types.ts
In https://github.com/tensorflow/tensorboard/pull/5090 I moved some properties from `core` to `settings`, along with the corresponding redux. There were some compatibility shims left behind in `core` for google-internal code. Now that all google-internal code has been migrated, we remove the shims.
Tested:
* Patched this change into a local repository and verified that other versions of tensorboard still built and behaved propertly.
=> Remove remnants of settings properties from core.

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts, tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
Depending on order of definition, when using routeContextedReducerUtil,
there are cases when the initialState is completely empty. This happens
because the first instance of the initialState in the `composeReducers`
get used.
While it might be advisable not to rely on order of reducers
defined in the `composeReducers`, the order is not specified as part of
the spec and TensorBoard specifies them in arbitrary order. In such
case, we don't want a broken or misbehaving application with missing
initial value.
As such, we now populate the correct initialState and wrote appropriate
test that would have caught the issue.
=> router: set correct initialState in reducers

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts, tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
Previously, the optional third parameter to the route contexted reducer
helper only allowed the utility to specify a state [re]setter that
reasons with the state alone. However, there are cases when we need to
set the initial value of a store based on the routeKind. For instance,
we would like our colorGroup settings to be `GroupBy.EXPERIMENT` when
user is navigating to an `COMPARE_EXPERIMENT` routeKind while keeping
it `GroupBy.RUN` in other cases. Since the initial state is a function
of the new route (`routeKind`, really), this change expands the
API signature to allow for reasoning with the route.
=> router: allow onRouteIdChange to reason with route

tensorboard/webapp/header/BUILD
From #5096, we had forgotten to add an explicit dependency on the
material menu in the testing lib. This change adds one.
=> sync: add missing dependency on material menu

tensorboard/components/tf_dashboard_common/data-loader-behavior.ts, tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
For better WebDriver testing, we would like to distinguish not_loaded,
loading, and loaded_at_least_once. By using a separate attribute on the
vz-line-chart, we were able to discern these differing states and
ultimately made our tests a bit more stable.
This change introduces another internal state in the
data-loader-behavior with which we can set the attribute onto the
vz-line-chart.
=> line-chart: set attribute when data is loaded once

tensorboard/components/tf_dashboard_common/tensorboard-color.ts, tensorboard/components/tf_markdown_view/tf-markdown-view.ts, tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.ts
We had previously not tested the plugin thoroughly enough and have
missed its dark mode-ification. This change simply addresses UX issue
under dark mode and screenshots will be applied separately.
=> dark mode: fix text plugin under dark mode

tensorboard/webapp/app_routing/testing.ts, tensorboard/webapp/runs/store/BUILD, tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts
When it's experiment comparison view, we want to color group by experiment even thought the user has not explicitly set it.
- check and update `initialGroupBy` on `createRouteContextedState`. It checks the routekind everytime the route changes.
- Also fixes groupruns bug: when userSetGroupByKey is 0, it means group by run. However the previous logic does not correctly check null and misjudge group by run as invalid.
=> color grouping: default group by experiment on comparison view

tensorboard/webapp/plugins/plugins_component.scss
This change applies proper `color` on `.warning-message`. Warning
message is not a plugin content and thus is not getting proper `color`
set when in dark mode.
Before: 
After:
=> dark mode: apply color on warning message

tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
In older TensorBoard, our run names, in experiment aware world, used to
have run names prefixed with experiment name to uniquely identify a run
in an experiment. Our users may expect that behavior in our run selector
so we implement to match the older behavior.
=> runs: filter based on experiment name and classic name

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts
We want to remove the color assignments for the non-matched runs; this will mark them as "inactive" and apply gray borders on them.
This improves the ux of the group by regex functionality. 
Before: 
After:
=> color grouping: group by regex, set non-matched runs to inactive

tensorboard/webapp/reloader/reloader_component_test.ts, tensorboard/webapp/settings/_redux/settings_reducers.ts, tensorboard/webapp/settings/_redux/settings_reducers_test.ts, tensorboard/webapp/settings/_redux/settings_selectors.ts, tensorboard/webapp/settings/_redux/settings_types.ts, tensorboard/webapp/settings/_views/settings_test.ts, tensorboard/webapp/settings/testing.ts
Refactor SettingsState so that actual settings properties are in their own subproperty 'settings' of type 'Settings'.
In the future we plan to make Settings (or Partial<Settings>) the return type of any Settings-related data sources.
=> Refactor settings in state to their own object.

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts, tensorboard/webapp/routes/dashboard_deeplink_provider.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We want to bring up color group by regex gradually by adding a feature flag `enableColorGroupByRegex`
The feature flag is added in global (also shown in OSS) and we want to flip the flag in tb.corp only later (no concrete plan to bring color grouping in OSS yet)
- show "Regex" under feature flag
- the edit row is not yet added. thus click the regex won't do any effect (cause regexString is empty and no way to edit it now)
with `?enableColorGroupByRegex=true` we can see third item on the dropdown. Click it should emit;
=> color grouping: add group by regex under feature flag

tensorboard/program.py
This changes the program to print a message that explicitly
indicates `--logdir_spec` is unsupported with `--load_fast`
behavior.
See https://github.com/tensorflow/tensorboard/issues/4802
=> docs: show explanation when --load_fast and --logdir_spec are passed

tensorboard/webapp/header/header_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss
There are some cases when a hyperlink is visually styled as a material
button. Due to our recent changes that globally style all hyperlinks,
those hyperlink-mat-buttons were also styled like one and it has caused
visual jank. This change undoes that by styling hyperlinks without
mat-*-button classes as hyperlink.
Prior to this change, "Learn More" below were styled as purple.
=> theme: style mat-button not as hyperlink

tensorboard/webapp/core/BUILD, tensorboard/webapp/core/views/page_title_container.ts
Fixes for:
- Deprecation warnings for selectors with props (GetExperiment)
- Type error for `customBrandName` (should accept `null`)
- `TB_BRAND_NAME` initialization error ([details](https://fusion2.corp.google.com/invocations/dfcc9be9-250e-4bf8-8182-b7588ea9267b/targets/%2F%2Fthird_party%2Ftensorboard%2Fwebapp%2Fcore%2Fviews:test_lib;config=b7b0423d5e2c3613de291426e5174dedca769b7600ec4129989b00744534613e/log))
=> fix build and lint errors in google3

tensorboard/webapp/runs/store/runs_selectors_test.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
* Motivation for features / changes!
add regex edit row to the dropdown
click to pop out the dialog
if there is no regexString set, display "(none set)" text
1. apply `?enableColorGroupByRegex=true` in url
2. navigate to TIME SERIES and click palette icon
3. click the last row (pencil icon) and text (none set)
=> color grouping: Regex edit

tensorboard/webapp/core/views/page_title_container.ts
`customBrandName` which is an optional injectable is currently typed as
`undefined`. Empirically, when there are no provider, it actually
returns `null` instead.
=> type: missing optional injectable is null

tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
When passing down the experiment id, it was overlooked in rund_group_menu_componet, which results in `OnRegexEdit` fails to function. Added it back and attach tests about regex editing.
=> color grouping: fix expid pass bug

tensorboard/webapp/core/views/page_title_container.ts, tensorboard/webapp/core/views/page_title_test.ts
To ensure that title$ emits even when experimentName$ doesn't, so that when navigating away from single experiment page, page title would change accordingly.
=> core: make title$ also listen to route kind observable

tensorboard/webapp/BUILD, tensorboard/webapp/app_module.ts, tensorboard/webapp/persistent_settings/BUILD, tensorboard/webapp/persistent_settings/_redux/BUILD, tensorboard/webapp/persistent_settings/_redux/persistent_settings_actions.ts, tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts, tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects_test.ts, tensorboard/webapp/persistent_settings/persistent_settings_module.ts
This change includes Redux changes that glues the Settings configuration
with DataSource. When there are configurations for global settings, the effects
now subscribe to the store changes, and when value changes, we persist the
setting in the local storage using the DataSource.
Note that this change does not yet migrate Metrics or notification_center to
use the new persistent_settings.
=> persistent_settings: glue config and data_source with Redux

tensorboard/webapp/runs/views/runs_table/BUILD, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- move cancel/save buttons to the right bottom
- add title and intro paragraph (see doc)
- click `Try (...)` to fill the example
Note:
- UI finalization WIP and screenshot tests come later
- live grouping result updates not included
=> color grouping: group by regex, fill example and some diaglog wording

tensorboard/webapp/metrics/metrics_module.ts, tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects_test.ts, tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts, tensorboard/webapp/persistent_settings/persistent_settings_config_module_test.ts
Passing a selector whose value is evaluated by invoking a method is
incompatible with AOT (ahead-of-time) compilation. This change makes
changes to the API so that it takes a factory that returns a selector.
~Test change: cl/385652976~ No longer valid.
=> persist storage: use factory instead of selector

tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts, tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts, tensorboard/webapp/persistent_settings/_data_source/types.ts, tensorboard/webapp/persistent_settings/_redux/BUILD, tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts, tensorboard/webapp/persistent_settings/index.ts, tensorboard/webapp/settings/BUILD, tensorboard/webapp/settings/_redux/BUILD, tensorboard/webapp/settings/_redux/settings_reducers.ts, tensorboard/webapp/settings/_redux/settings_reducers_test.ts, tensorboard/webapp/settings/settings_module.ts
With this change, now we remember reload, reload period, and pagination
size in our persistent setting storage system (LocalStorage for now).
=> settings: persist settings in storage

tensorboard/webapp/tb_polymer_interop_types.ts
The JS Closure compiler offers stricter optimizations such as property renaming.
In our app, the Polymer bundle and Angular bundle communicate using a set of
interop types defined in TypeScript.  To ensure that Angular code referencing
fields do not fail due to the Closure renaming in a separately-built Polymer
bundle, we use the `declare` keyword, respected internally as a way to define
interfaces as externs.
While TensorBoard does not currently enable the property renaming optimization,
this moves it one step closer to doing so.
Googlers, see test sync cl/385887792, property renaming debugging cl/385883631
Related: b/193918192
=> chore: guard against property renaming for Angular-Polymer interop types

tensorboard/webapp/app_routing/route_config.ts, tensorboard/webapp/app_routing/route_config_test.ts, tensorboard/webapp/app_routing/route_config_types.ts, tensorboard/webapp/app_routing/route_registry_module.ts
Previously, we only allowed very static route definition. Concrete route
aside, even the redirection route definition took path for "from" and
"to".
However, there now are the cases when we want to redirect, depending on
incomign path parts, redirect to different paths or route kinds. Now,
with this change, you can specify a definition that would be invoked on
a path match by invoking app specified `redirector`.
=> router: allow programmatical route definition

tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
In projector view, when the image sprites are transparent, transparent pixels are not rendered correctly. See images below. This change fixes this rendering issue. 
Proper rendering of transparent pixels also allow users to display non-square images as sprites, as long as they pad their image with transparent pixels.
Added a condition to fragment shader that checks if a the texture to be rendered is transparent at that coordinate; if so, it discards the texture.
Before:
After:
Make some pixels in the sprites transparent.
I tried changing the `depthTest`, `depthWrite`, and …
=> projector: draw transparent sprites correctly

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts, tensorboard/webapp/app_routing/route_config.ts, tensorboard/webapp/app_routing/route_config_test.ts, tensorboard/webapp/app_routing/route_config_types.ts
This change adds advanced feature to the router where a redirector can
redirect to a path with query parameter.
Imagine following use case. We want to add a nice redirection route
where, depending on path part value, we can redirect to EXPERIMENT or
EXPERIMENTS and, in the latter case, from the path part value, we'd like
to also pre-populate the user token. This would require
DeepLinkProvider-like module that would also reason and pre-populate
state from a path part (as opposed to value in the query parameter) and
that's farther in the realm of possible designs than what is proposed
here.
Here, we are proposing that the redirector can create almost
`Navigation` like payload where it can specify both pathname and query
parameter to a next route. Do note that this feature is clamped down to …
=> router: redirect with query parameter

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/store/BUILD, tensorboard/webapp/app_routing/store/app_routing_selectors.ts, tensorboard/webapp/app_routing/store_only_utils.ts, tensorboard/webapp/app_routing/store_only_utils_test.ts
Ideally, we want to populate store with an information that exists in
the comparison string. However, router only provides the information in
an opaque `experimentIds` (typed as string) without an ability to reason
with the structure inside.
Ideally, RouteParameter should have a way to construct a structured data
structure and pass it through `navigated` action but that makes
AppRoutingEffects even more complex while making the RouteConfig more
elaborate.
For now, we are exposing the utility for stores to use instead.
=> Expose CompareExperimentStr parser as util

tensorboard/plugins/histogram/summary_test.py, tensorboard/plugins/histogram/summary_v2.py
_Note: This is my third attempt to land this change; the previous attempts (first edition #5066 and second edition #5093) had to be reverted due to internal test failures - see b/194203115._
This updates the histogram summary TPU outside compilation workaround logic (needed until #2885 is fixed) so that we only invoke it when summaries will actually be written, to avoid the overhead of transferring data to the CPU only to be discarded.
cc @kenfranko 
The delta from the previous edition, #5093, is as follows:
- I realized that the graph mode test was disabled; I've re-enabled it in #5155 (also included in this PR as the first commit)
- Once that test is active, it exposes two failure modes of the previous scope-preservation logic I added in the second edition (to avoid the tag name changes …
=> histogram: avoid data transfer overhead for TPU outside compilation (3rd edition)

tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Currently we have four items on the dropdown menu. The forth one is editing the regex string. However while there is no regexString and user clicks `Regex` item, we fire `groupByChanges` with empty Regex string. Now we want to prop user to input the string by opening up the dialog.
=> color grouping: on clicking `Regex`, open dialog if regex string is empty

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts
Currently the regexString is preserved in url and can be rehydrated from url to state. Yet we miss one step to preserve the regexString in the state `colorGroupRegexString`. This pr is to fix it.
Because of our type structure (`GroupBy` and `RegexGroupBy`), when `runGroupByChanged` is trigged and `key` attribute is `REGEX`, it will always comes with the attribute`regexString`. 
Thus we only need to consider two cases:
1. it is not group by regex: we take the current `state.colorGroupRegexString`
2. it is group by regex: we always have `regexString`. Even tho the value of `regexString` is the same as `state.colorGroupRegexString` and the assign is meaningless. Since the outcome is the same so I did not particular handle …
=> color grouping: preserve regexString when groupBy regex is fired

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts
Currently when users click buttons to save regexString, we preserve this information in the url. Yet when the browser refreshed afterward, we did not rehydrate the string back to our state and the information disappears. This pr aims to address that.
=> color grouping: rehydrated regexString from url

tensorboard/webapp/widgets/histogram/BUILD, tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_v2_component.scss, tensorboard/webapp/widgets/histogram/histogram_v2_component.ts, tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
This change is a start of the rewrite for the histogram widget.
Currently, the component was written as a shallow wrapper around our
Polymer based vz-histogram-timeseries component. This wrapper was not
easy enough to make changes to address some of the user feedbacks and
implement a new feature.
To that end, we are rewriting the component so bulk of the logic resides
in the Angular land without Polymer. Do note that goal is _not_ to
remove Polymer but is to have more manageable visualization code with
much better types. Even the Polymer component is a thin wrapper around
d3 and the most interesting logic resides in the `draw` method. To be
clear, we are not completely gutting out d3 as it still serves useful
purposes for axis, formatting,
This change is the first of more to follow. This …
=> histogram: axis for Angular histogram widget

tensorboard/webapp/widgets/histogram/BUILD, tensorboard/webapp/widgets/histogram/histogram_module.ts, tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_v2_component.scss, tensorboard/webapp/widgets/histogram/histogram_v2_component.ts, tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
This change builds on top of the Angular version of the histograms
component where we had axex rendering implemented. This change finally
draws the histogram like the Polymer counterpart. Most of the UX
considerations are mostly replica of that of Polymer part and I did not
intend to have much changes besides minor color changes (now use theme
variable instead of hardcoded hex value).
This change does not include:
- interaction like tooltips
- redraw on resize
=> histogram: render Overlay and Offset charts

tensorboard/webapp/widgets/histogram/BUILD, tensorboard/webapp/widgets/histogram/histogram_module.ts, tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_v2_component.ts, tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
This change integrates new histogram visualizer with ResizeDetector, a
directive that lets Angular component detect resizes.
After detecting resize, we re-measure the DOM, sets value on scale, then
trigger re-render.
=> histogram: re-render on resize

tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
Provide QueryParamsFeatureFlagDataSource implementation in its raw form in addition to providing it as an implementation of TBFeatureFlagDataSource.
This allows other app-level implementations of TBFeatureFlagDataSource to inject QueryParamsFeatureFlagDataSource as a dependency and reuse the logic.
Longer term we have discussed possibly providing multiple TBFeatureFlagDataSource implementations and joining them at a higher level.
=> Provide QueryParamsFeatureFlagDataSource implementation

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Some number is off when we truncate the runs (display at most ten or five runs in a group), now all set to 5 runs per group.  Added a test to catch this.
=> color grouping: fix number and add tests

tensorboard/webapp/widgets/histogram/histogram_v2_component.scss
This change adds dark theme support for the new Angular based histogram
component.
=> histogram: support dark mode in Angular version

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/store_only_utils.ts, tensorboard/webapp/app_routing/store_only_utils_test.ts
Expose `getExperimentIdsFromRouteParams` and `getRouteId` as external utils, `experimentIds` and `routeId` will be able to be retrieved from navigation.
=> router: expose getExperimentIdsFromRouteParams and getRouteId

tensorboard/webapp/BUILD, tensorboard/webapp/widgets/intersection_observer/BUILD, tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts, tensorboard/webapp/widgets/intersection_observer/intersection_observer_module.ts, tensorboard/webapp/widgets/intersection_observer/intersection_observer_test.ts, tensorboard/webapp/widgets/intersection_observer/intersection_observer_testing_module.ts
TensorBoard had use IntersectionObserver so optimize for rendering.
Since we have done that manually several times, we are now widgetizing
it so it is easier to create an element that would use the relatively
new browser API.
=> widget: intersection observer directive

tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
See [g3-no-void-expression](go/tslintrule/g3-no-void-expression) for details.
=> lint: fix g3-no-void-expression lint failure

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts
This change adds basic reducers for setting and changing linked time
value. The states and actions in this changeset is highly experimental
and is prone for changes in the future when we implement UI features
along with it.
=> linked time: add basic data model

tensorboard/webapp/webapp_data_source/BUILD, tensorboard/webapp/webapp_data_source/query_params.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts, tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
This PR refactors internals of a class that are referenced in several places in the Google-internal repo. I have an accompagnying CL to submit "atomically" with these changes: cl/388460177
Replace QueryParamsFeatureFlagDataSource.getParams() with a dedicated injectable QueryParams class.
QueryParams simplifies testing for some TBFeatureFlagDataSource implementations by:
1) providing a single class that needs to be mocked/stubbed.
2) eliminating the need to peek into the implementations of other TBFeatureFlagDataSource implementations.
Googlers, see the type of pattern I'm attempting to fix in this parallel internal CL:
cl/388460177
=> Replace QueryParamsFeatureFlagDataSource.getParams() with injectable class.

tensorboard/backend/http_util.py
There are several statements in http_util.py that are just the names of some lists.
They don't seem to have any impact.
They are likely artifacts from previous refactoring.
We remove them.
=> Remove unnecessary statements in http_util.py.

tensorboard/webapp/metrics/views/main_view/filter_input_container.ts, tensorboard/webapp/metrics/views/main_view/filter_input_test.ts, tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts, tensorboard/webapp/metrics/views/main_view/main_view_test.ts
This change ignores casing when matching tags with regex or strings.
=> time series: ignore case when matching tags

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts, tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
This change improves visual aspect of the color group. Specifically, it
improves the dialog under very narrow screen.
Before:
After:
=> color group: improve visuals of the component

README.md
Added an example of what good and bad event files might contain.
As a less than full-time user of TB, I see this problem a lot, and I would really love to see good and bad examples so I more easily know what I'm seeing.
Alternative suggestions welcome.
* Motivation for features / changes: It wasn't clear to this user what an empty event file looked like.  Let alone a good one.
* Technical description of changes:  Added the --inspect output from a good and a bad event file.
* Screenshots of UI changes: N/A
* Detailed steps to verify changes work correctly (as executed by you): Documentation change only.
* Alternate designs / implementations considered: Would love to see better examples.
=> Update README.md to include no-data example

tensorboard/webapp/core/views/page_title_test.ts, tensorboard/webapp/experiments/store/experiments_reducers.ts
Cherry-pick #5190.
Only internal (corp) version should show experiment name on the tab title.
Tested locally:
=> 🍒: OSS TensorBoard page title should be `TensorBoard` (#5190)

tensorboard/webapp/metrics/internal_types.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
This change adds a vertical bar when there is a single time step
selected by a user. To accomplish this change, we are expanding the
APIs of the `line_chart_component` to allow for visual customization
which `scalar_card` uses to render the vertical bar.
This is first of many to follow so it, by no means, is ready for
consumption.
=> linked time: scalar single time step visuals

tensorboard/webapp/widgets/dropdown/dropdown_component.scss, tensorboard/webapp/widgets/dropdown/dropdown_component.ts
The 'tb-dropdown' widget now better handles items that are very
long. The dropdown menu width grows to fit content, up to a point,
and longer text will wrap.
Googlers, see b/193896469, and cl/388827477 for more.
=> ui: increase width and allow long dropdown items to wrap

tensorboard/webapp/settings/_redux/settings_reducers.ts, tensorboard/webapp/settings/_redux/settings_reducers_test.ts, tensorboard/webapp/settings/_views/settings_dialog_component.ts, tensorboard/webapp/settings/_views/settings_test.ts
Because of the discrepancy between store and view on the minimum reload
period, when you set the reload period to be less than 30s, it appeared
correct while it functionally was not true. This change fixes that.
This change also allows user to set 30s sharp which was previously
disallowed (this was a bug).
=> core: make reload dialog functional

tensorboard/webapp/settings/_redux/settings_reducers.ts, tensorboard/webapp/settings/_redux/settings_reducers_test.ts, tensorboard/webapp/settings/_views/settings_dialog_component.ts, tensorboard/webapp/settings/_views/settings_test.ts
Cherry-picking cf438df778c800113da065e4cbe7a4db2eef38ac 
From original commit:
Because of the discrepancy between store and view on the minimum reload
period, when you set the reload period to be less than 30s, it appeared
correct while it functionally was not true. This change fixes that.
This change also allows user to set 30s sharp which was previouisly
disallowed (this was a bug).
=> cherry-pick: core: make reload dialog functional (#5200)

tensorboard/compat/proto/proto_test.py
Improve error message for proto_test
* Add step for generating protos for RustBoard.
* Add instructions on how to handle new files that must be copied over
to TB for the BUILD to succeed.
=> Improve error message for proto_test

tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
Change from "Group runs by" to "Color runs by". Align with color group by regex dialog.
=> color grouping: change tooltip wording

tensorboard/webapp/plugins/plugins_component.scss
This change fixes the UI when data reload fails. Previously, without an
opaque background, the warning message awkwardly printed on top of
existing dashboard making the UI very janky.
By placing a color on the background, we now have the UI that we
intended.
Previously:
New:
=> core: no data warning message UI fix

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
This change adds a fob, a visual indication of the step selection, on
the x-axis. Soon, this component will be interactible but until then, it
is a read only component.
=> linked time: scalar: put fob on axis for selected step

RELEASE.md, tensorboard/version.py
Two commits to note:
* Bump nightly version to 2.7.0a0
* Cherry-Pick 2.6.0 release notes
=> Update master post-2.6.0 release.

tensorboard/webapp/widgets/range_input/range_input_component.ts, tensorboard/webapp/widgets/range_input/range_input_test.ts
In some combinations of width of the widget, `min`, and `max`, the widget
emitted `value` event whose payload contained floating point math noises.
This is natural in JavaScript (and Python) where it uses IEEE 754. This made
UX quite janky as scrolling through the range input would all of the
sudden emit very long numeric string.
This change attempts to filter out the arithmetic noise simply by
truncating to 10th signficant decimals.
Example of bad case:
=> range_input: fix floating point noise

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
This change implements visual for the ranged time selection for the
scalars visualization.
Ideally, I want the content of the line chart to have opacity preferably without changing the implementation of the line_chart_component but I could not get the `backdrop-filter: opacity` to work (it seems to be about opacity or strength of the filter?) and the only thing that I could find was this opaque overlay. If you know of a better way, I am all ears for the suggestion.
=> linked time: range view for scalars

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
We show preview of what runs a regex string would match. When regex
string does not match any runs, we showed nothing in the preview
potentially confusing our users. This change now prints a warning when
non-empty regex matches no entries.
=> color group: show message when regex does not match anything

tensorboard/webapp/app_routing/internal_utils.ts, tensorboard/webapp/app_routing/internal_utils_test.ts, tensorboard/webapp/app_routing/programmatical_navigation_module.ts, tensorboard/webapp/app_routing/programmatical_navigation_module_test.ts, tensorboard/webapp/app_routing/programmatical_navigation_types.ts, tensorboard/webapp/app_routing/store_only_utils.ts, tensorboard/webapp/app_routing/store_only_utils_test.ts
This includes 2 changes to the app router.
- The 'compare' route now accepts a URL that defines experiments with
an 'id' and no display 'name' / alias. For example,
'http://localhost/compare/:unnamedExpId,baseline:secondNamedExpId'
- Registering a `ProgrammaticalNavigation` now allows providing a
lambda which may conditionally return `null`, to indicate that a
navigation should not occur when the specified action is fired.
These changes are a step towards allowing a TensorBoard app to craft a
URL that automatically uses default experiment aliases computed at
runtime without the URL having to specify them.
Googlers, see b/195683550 and proof of concept cl/389664527
=> router: support conditional navigations and empty experiment names

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
Especially with the customizable interactive view, the line chart
interactive view is no longer on top of all the other DOM. This makes
our zoom instruction which should appear above all is getting clipped or
getting masked by other components. This change simply uses z-index: 1
(we do not use it elsewhere so 1 is sufficient; we rely on DOM ordering
for the most part) to lift the DOM up.
=> line chart: zoom instruction show on top of other

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Previously we listen to `input` of the input, it does not get triggered when user click `try (train|eval)` button, which modify the input value. Now we manually trigger `regexInputChange` method when the `try` button is clicked.
=> color grouping: generate preview for example filling

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/right_pane/BUILD, tensorboard/webapp/metrics/views/right_pane/right_pane_module.ts, tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html, tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This change adds initial visual shim of the settings for the linked time
that conditionally renders if the feature is enabled and if current time
unit is STEP.
Do note that we are still fiddling with the data model and UI affordance
so the code is highly experimental. This change is not the completed 
feature as it is missing an ability to accurately set `min` and `max` on
step ranges. The feature will be more complete in the follow ups.
=> linked time: settings on the right pane 

tensorboard/plugins/pr_curve/pr_curve_demo.py, tensorboard/plugins/pr_curve/pr_curves_plugin.py, tensorboard/plugins/pr_curve/pr_curves_plugin_test.py, tensorboard/plugins/pr_curve/summary_test.py
* Motivation for features / changes:
* The thresholds generated and shown in the PR curve plugin are incorrect (AFAICT) compared to the thresholds used in the PR curve `summary.op`.
* The thresholds used in `summary.op` are:
`[0.0, 1/(num_thresholds-1), 2/(num_thresholds-1), ..., 1.0]`
... but prior to this change, the thresholds generated in `_make_pr_entry` and displayed in TensorBoard are:
`[1/num_thresholds, 2/num_thresholds, ..., 1.0]`.
* Technical description of changes:
* Modified `_make_pr_entry` to instead generate thresholds like `sumamry.op`, as described above.
* Cleaned up the code in `_make_pr_entry` to be a bit easier to read / check for correctness.
* Added tests for `summary.op` that verify the thresholds used are indeed what are described above.
* Changed the number of …
=> Fix PR curve plugin to display correct thresholds

tensorboard/webapp/runs/store/runs_reducers.ts, tensorboard/webapp/runs/store/runs_reducers_test.ts, tensorboard/webapp/util/colors.ts
Currently we do not set any color to non-matched runs, which makes the chart cannot be read at all. Now we set light gray (#ececec) on those non-matched ones.
=> color grouping: set non-matched runs to light gray

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts
This change introduces state in the Metric reducers to remember which
visualizations user wants to view.
UI that leverages the state will come in a following change.
Demo of final experience:
=> timeseries: state for remembering vis filter

tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
Angular, while compiling, was not able to discern that the `disabled` is
not the `Input` to `tb-range-input` although it is a valid HTML
attribute on HTMLElement. This change explicitly instructs Angular to
put the property on the attribute.
This change unblocks the sync.
=> sync: fix attr.disabled issue

tensorboard/webapp/core/store/core_types.ts, tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
This change is a combination of two very minor commits that tweaks visuals of recently introduced components.
Specifically,
- button-toggle in metrics now have consistent appearance inside Google and in OSS
- sidebar default width is smaller 
I plan on merging these with rebase instead of squash.
=> Minor tweaks to the appearance of sidebar and button-toggle

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts, tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Under some scenario (the filter run regex has been edited), when users hit ctrl+z, the focus goes back to the filter run input and the dialog input lost the focus. Although we do not prevent the ctrl+z happen, we can exam what is the new activeElement and move the focus back if the new activeElement is not within the regex dialog.
Listen to regex dialog component `focusout` event firing 
use timeout to wait for the `activeElement` to move from the input to new one (Step 2 to 3 in the below flow)
Focus change event sequence: (credit to @stephanwlee)
1. user tabs from input
2. foucsout (or blur); activeElement is still the input
3. focus actually moves and updates activeElement to the next focusable element.
4. focusin …
=> color grouping: trap focus in the dialog

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
In case there are no dirty update selectors specified, the whole
AppRoutingEffects broke as we are waiting on `combineLatest` on an empty
list which never emits. This change fixes that by only conditionally
waiting on the selectors when they are non-empty
=> app routing: fix case when there are no selectors on registry

.github/workflows/ci.yml, WORKSPACE
This change checks whether WORKSPACE is formatted using buildifier.
buildifier now is able to format WORKSPACE files, too.
=> chore: buildifier WORKSPACE file

tensorboard/webapp/app_routing/BUILD, tensorboard/webapp/app_routing/index.ts
This change exports public symbols of the AppRouting component. Notably,
it currently exports all the public types and exposes an utility that
would be used when defining a route.
=> app_routing: expose symbols

WORKSPACE
By default, no matter what version of Node you have installed,
rules_nodejs loads node 12.13.0. This version is not too compatible with
the newer dependencies (a package may use `engine` on package.json to
denote compatibility with a version of a node runtime). This change
bumps the node requirement to 12.21.0 which is good enough for our use
case.
=> chore: require node.js 12.21.0

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/internal_types.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html, tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts, tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This change introduces a new state that keeps track of minimum and
maximum step values from all time series data. This is so we can render
the range_input with its minimum and maximum according to the data.
This change also updates the data structure on the `LinkedTime` to drop
`wallTime` field which is not used meaningfully and only causes the data
inconsistency.
=> linked time: range on sidebar step selector

tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.scss, tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.ts, tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_module.ts
We now show a small read "i" when an x-axis extent (extremums) of the
line chart is not intersecting with the selected time. This "i"
informs user that the data presented below is not within the linked
time. In that situation, we will clip the selectedTime to the minimum or
maximum of the dataset so something is visible on the screen.
Do note that the "i" treatment will be there for other kinds of visualizations
thus is pulled out as a separate component.
=> linked time: marker when extent is outside of linked time

tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Removes a stray 'debugger' statement from a web test.
=> test: drop stray debugger statement

tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts, tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_test.ts, tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Each line chart component in the Time Series dashboard gets its own canvas and
webgl rendering context. After scrolling through too many line charts (for my
device after ~30), the page issues warnings in the console like "Too many active
WebGL contexts. Oldest context will be lost".
When the browser decides there are too many contexts, it disposes old ones
causing blank line charts. This change adds an event dispatched by the line chart's
internal `ChartImpl` to notify clients when the rendering context is lost.
This only applies to the WebGL renderer for now.  A followup change addresses the
remediation of blank scalar cards.
Googlers, see b/196294346.
Diffbase: none.
Followup: https://github.com/tensorflow/tensorboard/pull/5239
=> line chart: introduce onContextLost renderer callback

tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts, tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts, tensorboard/webapp/notification_center/_data_source/testing.ts
There were cases when the notification payload we handcrafted is in the
future and since we only dismiss the notification by recording the last
read time (NOW), there were cases when new notifications in the future
are never dismissable. To prevent developer mistakes, we can clip the
date to start of the day so a notification can never been in the future.
=> notification: clip the date to today

tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
With this change, we are now clipping content of the custom axis
visualization so it is contained inside the axis container. Previously,
linked time step scrubber extruded out of the container and left very
awkward UI.
Before:
After:
=> linked time: clip axis UI from leaving bound

tensorboard/webapp/metrics/views/main_view/filter_input_container.ts, tensorboard/webapp/metrics/views/main_view/filter_input_test.ts
Image cards are a bit odd; unlike others, the same tuple of run and tag
can appear more than once and that is because it has the third
axis--sample. When there are more than one sample for a run+tag, the tag
filters previously showed the duplicate entry which this can
de-duplicates.
=> time series: deduplicate tags in the search

tensorboard/webapp/metrics/internal_types.ts, tensorboard/webapp/metrics/store/BUILD, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/routes/BUILD, tensorboard/webapp/routes/dashboard_deeplink_provider.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts, tensorboard/webapp/routes/dashboard_deeplink_provider_types.ts, tensorboard/webapp/routes/testing.ts
The Time Series dashboard tag filter is now synced with the URL's
"?tagFilter" query param.
Manually tested that typing in the tag filter updates the URL, and
that crafting a URL with "?tagFilter=batch" and navigating to it
makes the dashboard show the appropriately matching cards.
Googlers, see b/182797564.
Blocked on: https://github.com/tensorflow/tensorboard/pull/5239
=> timeseries: persist tag filter in the URL

tensorboard/webapp/widgets/dropdown/dropdown_component.scss, tensorboard/webapp/widgets/dropdown/dropdown_component.ts
Long items within tb-dropdown are supposed to wrap onto multiple
lines. Our CSS was incorrectly using a selector without enough
specificity, and Angular was overriding our classname.
Before
After
=> ui: fix wrapping of dropdown items

tensorboard/webapp/metrics/views/card_renderer/card_lazy_loader.ts, tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/main_view/card_grid_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
This addresses 2 non-trivial sources of memory leaks observed when
filtering tags in the Time Series dashboard.
a) CardObserver used to track Elements that were destroyed via
ngOnDestroy and stored them in a `Set<Element>`. Now with a WeakSet
instead, we cover cases when the browser's IntersectionObserverEntry
is not handled for some reason.
b) The rxjs operator "shareReplay" has some known gotchas [1], [2].
When more observables subscribe to a source containing
`shareReplay(1)` in its operator chain, the source remains subscribed
even after the other observables unsubscribe. This change uses the
`takeUntil(ngUnsubscribe$)` pattern to ensure any component using a
`shareReplay` will not keep it subscribed after the component is gone.
Alternatively we could use `refCount`, but this opts for …
=> timeseries: fix memory leaks involving CardObserver and shareReplay

tensorboard/webapp/metrics/internal_types.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Image plugin has a notion of sample which was previously not visible to
user. This change shows sample, when it is relevant, in the image card.
When step number is large and the card is tiny:
=> time series: show sample on image

tensorboard/webapp/metrics/views/_common.scss, tensorboard/webapp/metrics/views/main_view/card_groups_component.scss, tensorboard/webapp/metrics/views/main_view/filtered_view_component.scss, tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html, tensorboard/webapp/metrics/views/main_view/main_view_component.scss, tensorboard/webapp/metrics/views/main_view/main_view_test.ts, tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
You may want to treat the pinned UI as the shopping cart and want to add
cards to the "cart" while filtering. In the past, the shopping cart did
not show up when filtering so it was difficult to understand all the
items in the shopping cart. To fix that, we now show pinned cards below
the filter view each with their own scrollable container.
=> timeseries: show pinned view while filtering

tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts, tensorboard/webapp/widgets/histogram/histogram_v2_component.ts, tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
This change knocks off one of the TODO on the histograms. Instead of
a function that would return a color, this change pipes color to
histograms component instead.
=> histogram: pass color instead of scale

tensorboard/webapp/metrics/views/_common.scss, tensorboard/webapp/metrics/views/main_view/main_view_component.scss, tensorboard/webapp/runs/views/runs_table/runs_table_component.scss, tensorboard/webapp/theme/_tb_theme.template.scss
This change contains three visual improvements for TimeSeries:
- now, the section headers have shadow to give a sense of height
- color picker no longer causes scrollbar on the app to show up for a
brief moment
- Correct value for `contain` on the grid container for better paint
containment
- Scrolling on left pane no longer causes repaint.
Before
New
=> styles: TimeSeries UI improvements

tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/card_renderer_module.ts, tensorboard/webapp/metrics/views/card_renderer/card_view_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/card_view_component.ts, tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts, tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
This change adopts the "isEverVisible"-ness to all types of
visualization. The premise of this change is following: some users wants
high number of pagination size with many distinct tag groups. For those
users, we optimized line chart render by deferring render until the card
is visible on the screen. With the optimization, we were able to reduce
number of DOM nodes we mount at the start of the page load. This change
expands the optimizations to defer rendering card headers and rendering
other visualization types like image and histograms.
=> timeseries: improve first paint

tensorboard/pip_package/requirements.txt
`google-auth` recently published a 2.0.0 release which removed support for Python 2.7. `google-auth` now requires Python >=3.6. No other breaking changes were made. You can see the full list of changes [here](https://github.com/googleapis/google-auth-library-python/commit/560cf1ed02a900436c5d9e0a0fb3f94b5fd98c55).
I am opening PRs to expand google-auth version ranges for packages that meet either of the following criteria:
* Package has >10,000 monthly downloads as of June 2021
* Package is owned by a Google team
`google-auth` is a dependency of many different libraries that interact with Google APIs. Increasing the time and number of packages with compatible pins on `google-auth` lowers the chance end developers who use multiple libraries will see dependency conflicts. 
If possible, …
=> Allow `google-auth < 3`

tensorboard/webapp/widgets/histogram/histogram_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_component.scss, tensorboard/webapp/widgets/histogram/histogram_component.ts, tensorboard/webapp/widgets/histogram/histogram_test.ts
Paint is one of the most expensive operations when you have too many
items painting at the same time. One technique to prevent that is to use
`transform` and `will-change` which often put the DOM in the GPU context
instead. All in all, using `attr.transform` still causes repaint while
`style.transform` does not so we chose to use latter instead.
=> histogram: use `transform` to prevent repaint

tensorboard/webapp/metrics/views/main_view/card_groups_component.ts, tensorboard/webapp/metrics/views/main_view/filter_input_component.ng.html, tensorboard/webapp/metrics/views/main_view/filter_input_component.scss, tensorboard/webapp/metrics/views/main_view/filter_input_container.ts, tensorboard/webapp/metrics/views/main_view/filter_input_test.ts, tensorboard/webapp/metrics/views/main_view/filtered_view_component.ts, tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts, tensorboard/webapp/theme/_tb_theme.template.scss
In performance profiling, there were two medium sized opportunities for
optimization:
1. we were spending significant CPU cycles for rendering all tag matches
in the autocomplete and it was taking non-trivial amount of time
(~100ms) when there were 3000 tags. This definitely contributed to
slowness when every keystroke is expected to be very responsive.
2. `compareTagNames` were taking a significant amount of time. Given
that the list of tags/cards does not change unless the underlying data
from backend changes, we really do not need to sort on every keystroke
that changes tagFilter. We can pre-sort the tag list before we apply the
filter.
These two changes, combined, gave significantly subjectively snappier
experience.
=> timeseries: improve tag filtering

tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts, tensorboard/webapp/metrics/views/main_view/main_view_test.ts
This puts debounce on the tag filter changes. Tag view does not have to
change on every keystroke so we put some debounce period so we can be
more performant by not updating too much.
This change also moves the plugin type filtering up since it does not change
too rapidly.
=> timeseries: debounce tag filter changes

tensorboard/webapp/theme/_tb_theme.template.scss
In Scalars plugin, or any Polymer plugin, when you click on the settings
that bring up the Angular overlay, you see a scrollbar render on the
`body` level. This is because we put `contain: strict` on the body
recently which can be omitted for now.
Buggy TensorBoard (found in screenshot test)
=> bug: prevent scrollbar when angular dialog presents

tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts, tensorboard/webapp/widgets/intersection_observer/BUILD, tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts, tensorboard/webapp/widgets/intersection_observer/intersection_observer_test.ts
This change adds support for optional parameter on the
IntersectionObserver that lets us specify the margin for triggering the
IntersectionObserver.
=> widget: support margin on IntersectionObserver

tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
When users change tabs in the same dashboard or edit query parameters in the same list view, unsaved updates should be kept without warnings.
Googlers, see [issue](https://b.corp.google.com/issues/197321281) for more details.
#edit_exp
=> router: do not warn users about dirty updates on the same page

WORKSPACE
This change upgrades rules_sass which recently added a new BUILD rule
that allows us to upgrade `@angular/material` in the future.
=> infra: upgrade rules_sass deps

package.json, tensorboard/defs/defs.bzl, tensorboard/webapp/BUILD, yarn.lock
This change introduces new rule for external SASS dependencies and use
it to add `@angular/material` dependency.
=> infra: upgrade `@angular/material`

tensorboard/webapp/app_routing/actions/app_routing_actions.ts, tensorboard/webapp/app_routing/effects/app_routing_effects.ts, tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts, tensorboard/webapp/app_routing/route_registry_module.ts, tensorboard/webapp/app_routing/store/app_routing_reducers.ts, tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts, tensorboard/webapp/app_routing/store/app_routing_selectors.ts, tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts, tensorboard/webapp/app_routing/store/app_routing_types.ts, tensorboard/webapp/app_routing/store/testing.ts
This change introduces a new state in the AppRouting so we can control
features based on how routes are registered in the application.
=> app_routing: expose registered route kinds

tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts, tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts, tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts, tensorboard/webapp/feature_flag/testing.ts, tensorboard/webapp/feature_flag/types.ts
Soon, we want to promote TimeSeries plugin to the 1st place in the list
of plugins making it the default experience. As it may be jarring for
some users, we want to warn and explain the rationale.
=> timeseries: add feature flag for butter bar

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/views/BUILD, tensorboard/webapp/metrics/views/metrics_container.scss, tensorboard/webapp/metrics/views/metrics_container.ts, tensorboard/webapp/metrics/views/metrics_container_test.ts, tensorboard/webapp/metrics/views/metrics_promo_notice_component.ng.html, tensorboard/webapp/metrics/views/metrics_promo_notice_component.scss, tensorboard/webapp/metrics/views/metrics_promo_notice_component.ts, tensorboard/webapp/metrics/views/metrics_promo_notice_container.ts, tensorboard/webapp/metrics/views/metrics_promo_notice_types.ts, tensorboard/webapp/metrics/views/metrics_views_module.ts
This change adds some messages and placeholders for the TimeSeries
promotion. It also adds two buttons users can use to navigate to
scalars, old experience, or dismiss the promotion.
=> timeseries: second draft of TS promotion

tensorboard/webapp/metrics/metrics_module.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/metrics_container.ts, tensorboard/webapp/metrics/views/metrics_container_test.ts, tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts, tensorboard/webapp/persistent_settings/_data_source/types.ts
This change makes the promotion butter bar dismissable and the state to
be persisted in the local storage.
=> timeseries: make promo dismissable

tensorboard/webapp/metrics/views/main_view/empty_tag_match_message_component.ts, tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Minor tweak since the existing wording for the empty match warning was a bit confusing to me.  In particular it felt hard to scan with the tag count in between the two different filters.  I'm assuming the idea was to distinguish that the tag filter filters "tags" and the plugin type filter instead filters "cards", but practically speaking I think we can treat them as equivalent here, and "tag filtering" is the term used in the section header and in the search field placeholder.
Here's the proposed wording:
=> timeseries: adjust wording of empty match warning

tensorboard/components/tf_runs_selector/tf-runs-selector.ts
When the file path to the logdir has a long title without any delimiting characters([/=_,-]) the path is truncated. This line of css stops that truncation by moving the truncated text to a new line.
Googlers, see b/181583629.
=> Use overflow-wrap on location data text.

tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
Pagination controls were improperly themed and this change fixes that.
Now, the secondary-text colors are correctly picked based on current
theme settings and the `<input>` is hard themed (instead of relying on
OS settings and browser's default dark styling). It also styles disabled
button so when the "Previous" or "Next" button is disabled, we have a
visual cue.
=> timeseries: theme group control

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
In SASS, they have deprecated use of slash for division
<https://sass-lang.com/documentation/breaking-changes/slash-div>. This
change replaces division with multiplication instead.
=> chore: remove instance of `/` in SASS

tensorboard/webapp/metrics/effects/index.ts, tensorboard/webapp/metrics/effects/metrics_effects_test.ts
Previously, we were only waiting for navigation and plugin change events
none of which is useful when freshly loading dashboard since
`activePlugin` will be null until we can fetch the plugins listing at
least once. This change, to fix the problem, also listens to plugins
listing loaded event to assert and fetch the data.
=> timeseries: fix tags not fetching issue when loading

tensorboard/webapp/widgets/histogram/histogram_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_component.scss, tensorboard/webapp/widgets/histogram/histogram_component.ts, tensorboard/webapp/widgets/histogram/histogram_test.ts
This change implements fill/color for the linked time feature. When in a
single step mode, if there exists a histogram data with the matching
step, we will highlight it by putting subdued color for non-matching
ones while showing a color for the match. For the range selected time
mode, this change does the same for match/non-match creating a range of
colored histograms.
For single:
For range:
=> linked time: implement histogram color for linked time

tensorboard/webapp/widgets/histogram/histogram_component.ng.html, tensorboard/webapp/widgets/histogram/histogram_test.ts
This change adds the axis indicator for the end of the selected time
range. This change only adds visual elements.
=> linked time: render end range fob in histogram

.github/workflows/ci.yml, tensorboard/BUILD, tensorboard/compat/tensorflow_stub/BUILD, tensorboard/compat/tensorflow_stub/io/gfile.py, tensorboard/compat/tensorflow_stub/io/gfile_fsspec_test.py, tensorboard/pip_package/requirements_dev.txt, tensorboard/summary/writer/BUILD, tensorboard/summary/writer/event_file_writer_fsspec_test.py
This adds support for fsspec filesystem backends to the gfile compat library. This allows for tensorboard to be used with a wider range of file system backends.
See: https://github.com/tensorflow/tensorboard/issues/5165
This adds a new GFile filesystem backend that's used if no other registered filesystems are present. In that case fsspec is checked to see if it has an available one and then returns a wrapped version.
fsspec provides similar semantics to normal usage however, it doesn't support seeking for files opened in text mode which can be problematic for longer text files. However, this seems to work regardless since most of tensorboards larger files are in a binary format.
* Detailed steps to verify changes work …
=> gfile: add support for fsspec filesystems

tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/card_renderer/BUILD, tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss, tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/histogram_card_module.ts, tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/utils.ts, tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.scss
When linked time selection is not in the range of the data, we clip the
time selection and show a little indicator warning user of the clipping.
This change applies the indication on the histogram vis.
=> linked time: clipping indicator on histogram 

tensorboard/plugins/histogram/summary_test.py, tensorboard/plugins/histogram/summary_v2.py
Working around a user issue. It's intended as a temporary fix, but keeping it long-term doesn't have any downsides that I know of.
Adds tf.stop_gradient in tf.summary.histogram. The function is not differentiable, and building gradient graphs for its conds have been causing some issues. This should be a no-op with a tiny positive performance impact for most users, and will work around an error for those using XLA with multiple/persistent tf.GradientTapes (due to XlaDynamicUpdateSlice not having a gradient defined; there is a separate TensorFlow bug about the op with no gradient, which is the more satisfying medium-term solution here).
N/A; this just changes the implementation of a summary …
=> Add tf.stop_gradient in tf.summary.histogram

tensorboard/webapp/core/views/hash_storage_component.ts, tensorboard/webapp/core/views/hash_storage_test.ts
For hash storage, we are using "onhashchange" to listen to the hash
changes but it apparently is quite faulty.
Repro case:
```js
window.onhashchange = () => console.log("hash changed!");
window.location.hash = "yo"
// prints "hash changed!"
window.history.back();
// prints "hash changed!"
window.history.forward();
// prints "hash changed!"
const url = new URL(window.location.toString());
url.search = "random"
window.history.replaceState(null, '', url.toString());
window.history.back();
// prints nothing
window.history.forward();
// prints nothing
```
To fix this, instead of listening to onhashchange, we now listen to
onpopstate which gets triggered in all cases (hash + search + pathname).
=> hash: fix issues with the app router.

tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts, tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
This change improves line chart axis by measuring how big the label is
so a label does not overlap with another.
Instead of using DOM to measure the dimension, this uses 2D Canvas to
measure the text which is a lot performant as it would not have to cause
reflow.
Do note that we can be smarter with the tick filtering but this
iteration is quite dumb and only filters from the start.
=> line chart: skip axis label render based on visibility

tensorboard/components/tf_dashboard_common/dashboard-style.ts, tensorboard/components/tf_dashboard_common/tensorboard-color.ts, tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts, tensorboard/plugins/hparams/tf_hparams_main/tf-hparams-main.ts
As reported in #5309, links in some error messages in dark mode are difficult to see. It turns out this is potentially a more general problem: there is no attempt to style any links for dark or light mode in the polymer part of the code base.
1. Mirroring definitions for the Angular part of the code base we add --tb-link and --tb-link-visited definitions in tensorboard-color.ts.
The corresponding Angular definitions can be found in: 
https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/theme/_tb_theme.template.scss
2. We use --tb-link and --tb-link-visited in dashboard-style.ts, applying the styling for most dashboards.
3. We use --tb-link and --tb-link-visited in the graphs and hparams …
=> dark mode: Style link colors in both dark and light modes in polymer plugins.

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts, tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
Currently, we are showing relative time in the tooltip only when you are
using x-axis type == relative. Instead of conditioning like that, we are
now showing the time all the time. This change, to support that,
refactored the data type a little bit to always compute the relative
wall time between the point (which required a lot of test refactors).
=> timeseries: show relative time in tooltip

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts, tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts, tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts, tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts
To make the step values more meaningful, e.g. display `1,001,001` instead of just `1M`.
Visualization:
Googlers, see [issue](https://b.corp.google.com/issues/200663497).
=> timeseries: keep all digits for step values in scalar cards

tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html, tensorboard/webapp/metrics/views/main_view/main_view_component.scss, tensorboard/webapp/metrics/views/main_view/main_view_test.ts
This change hides pinned section from the main view when you are
filtering. It takes up too much space and is bad for UX when a screen
size is small.
=> timeseries: hide pinned section while filtering

tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html, tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
Previously, when using range selection, the fob was incorrectly placed.
This change fixes that.
Before:
After:
=> linked time: fix fob positioning on scalar

tensorboard/plugins/hparams/get_experiment.py, tensorboard/plugins/hparams/hparams_plugin.py, tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
Reduce non-essential errors in the logs for easier debugging.
Googlers, see [issue](https://b.corp.google.com/issues/199306961) for more context.
#onduty
=> cleanup: log as a warning instead of an error when HParams-plugin experiment data is not found

tensorboard/plugins/hparams/get_experiment.py, tensorboard/plugins/hparams/hparams_plugin.py, tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
Reverts tensorflow/tensorboard#5323, which causes sync failures.
=> Revert "cleanup: log as a warning instead of an error when HParams-plugin experiment data is not found"

tensorboard/webapp/metrics/views/main_view/BUILD, tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html, tensorboard/webapp/metrics/views/main_view/card_grid_component.ts, tensorboard/webapp/metrics/views/main_view/card_grid_container.ts, tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
Previously when you changed pages to grouping that had less cards it could cause a jarring and confusing effect as the size of the grouping changed. Many times this would case the graphs you were looking for to go completely off your screen and you had to scroll to see them. 
Now after the new page appears Tensorboard will automatically scroll to the same position relative to the new size of the grouping.
Googlers see b/160888098.
=> timeseries: Adjust scroll position after pagination

tensorboard/webapp/metrics/views/main_view/BUILD
Our test was depending on cdk/scrolling without explicitly specifying
the dependency. This change adds the missing `deps`.
=> sync: add missing cdk scrolling dep

.git-blame-ignore-revs
Summary:
Merged in #5326 
Test Plan:
The output of `git blame  --ignore-revs-file .git-blame-ignore-revs tensorboard/components/polymer/dark_mode_mixin.ts`
no longer has any lines blaming to the commit in question
=> blame: ignore Prettier 2.4.1 reformatting

tensorboard/plugins/histogram/summary.py, tensorboard/plugins/histogram/summary_test.py, tensorboard/plugins/histogram/summary_v2.py
This is to avoid the accumulating floating point errors in `tf.reduce_sum` when using `float32` where large sums are truncated to `2^24` as described in https://github.com/tensorflow/tensorflow/issues/36128.
=> histogram: cast tf.reduce_sum input to float64

tensorboard/webapp/experiments/store/testing.ts, tensorboard/webapp/runs/views/runs_table/BUILD, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts, tensorboard/webapp/util/BUILD, tensorboard/webapp/util/matcher.ts, tensorboard/webapp/util/matcher_test.ts, tensorboard/webapp/util/ui_selectors.ts, tensorboard/webapp/util/ui_selectors_test.ts
Previously, to allow regex string also match run selection, we have
extend the utility selector to match run selection against the regex.
The logic, however, was massively flawed--instead of matching against
name of a run, experiment, alias, and legacy run name, the
implementation matched against runId which coincidentally contained run
name but was supposed to be an opaque id. This caused an obvious match
like `/^foo/` not to match anything especially when an opaque id is not
created to start with "foo".
In the end, this change basically re-implements the run selection based
on regex more correct.
In the process, we refactored how a run is matched against regex so the
behavior is more congruent in our app.
=> timeseries: match selection using same logic

tensorboard/webapp/metrics/views/main_view/main_view_test.ts, tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss, tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts, tensorboard/webapp/metrics/views/main_view/pinned_view_container.ts
The reason why we decided to show pinned section during search is
because we wanted to make pinning more intuitive while you are filter
searching (previously, when you pinned a card, there was no visual
indication of an action besides a small fill on the pin icon which is
occluded by the cursor). This change makes the section a bit smaller but
compensate for the small UI with an indicator for new pinned card.
=> timeseries: show indication when there is a new pin

tensorboard/webapp/metrics/views/main_view/main_view_test.ts, tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts
We added the `[data-id]` on a span to uniquely identify a DOM newly
stamped when new pin gets pinned. Bucause AOT Angular compiler complains
about binding to a property in `<span>`, we are instead explicitly
binding to `data-id` attribute on the DOM instead.
=> sync: change data-id binding to attribute

tensorboard/webapp/hparams/_redux/utils.ts, tensorboard/webapp/hparams/_redux/utils_test.ts, tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
When hparams specs in comparison mode are not compatible (e.g., an
experiment has Discrete one while for the same name another experiment
has Interval one), we currently throw a RangeError. That error manifests
as very violent error that breaks entire app and make the TimeSeries
plugin not functional. Since TimeSeries does not really render hparams,
it does not make sense for this error to so violently throw error. Now,
with this change, we do not even read the hparams value when in
TimeSeries.
Also, as a bonus, we have relaxed the constraint a bit and try to
reconcile with incompatible filters if any of the compatible ones are
empty.
=> run selector: subdue violent exception when hparams are invalid

tensorboard/plugins/histogram/summary_test.py
Temporarily remove the test for further debugging.
=> sync: remove test that causes segmentation fault

tensorboard/plugins/hparams/BUILD, tensorboard/plugins/hparams/get_experiment.py, tensorboard/plugins/hparams/hparams_plugin.py
Reduce non-essential errors in the logs for easier debugging. 
`"HParams error: Can't find an HParams-plugin experiment data in the log directory. Note that it takes some time to scan the log directory; if you just started Tensorboard it could be that we haven't finished scanning it yet. Consider trying again in a few seconds."` should be logged at `INFO` level.
Tested sync locally. 
Googlers, see [issue](https://b.corp.google.com/issues/199306961) for more context.
#onduty
=> cleanup: log as info when no hparams experiment data is found

tensorboard/plugins/histogram/BUILD, tensorboard/plugins/histogram/summary_test.py
This reverts commit 9529cf7dce77c5928ee1f80e841e3703ba3fe70d.
Also increase the summary_test size from `small` to `medium` to get more RAM. 
Tested the sync locally.
=> histogram: add back the test for large counts

tensorboard/uploader/proto/experiment.proto, tensorboard/webapp/experiments/types.ts
Features under development for TensorBoard.dev require access to the owner of an experiment.   The cleanest way to return this information is to plumb it through the call stack using the Experiment proto.  This is more future proof and correct against various other features compared to re-injecting the current user into an owner field at a higher level of the stack.
Addition of the owner field (string) to the Experiment proto and the corresponding bool to the mask.
Note: this changes nothing on the write path, during upload we still only use the authentication credentials on the rpc call and this new field would be ignored -- we don't populate it ourselves and if someone else did, we'd still ignore it.
=> Add owner field to experiment proto.

tensorboard/plugins/hparams/BUILD, tensorboard/plugins/hparams/backend_context.py, tensorboard/plugins/hparams/backend_context_test.py, tensorboard/plugins/hparams/get_experiment.py, tensorboard/plugins/hparams/hparams_plugin.py
Fixes #5347.
This updates the HParams plugin's `Context.experiment_from_metadata()` to always return an `Experiment` proto, regardless of whether there are any HParams summaries.  The experiment computation already has logic that handles the case where no experiment-level HParams summary was logged by synthesizing an experiment from the existing session-level summaries (which results in an experiment with hparam and metric infos, but no name, description, user, or started time).  This PR simply adjusts that logic so that we return the synthetic experiment even when there are no session-level summaries, in which case we return empty hparam and metric info repeated fields as well.
This is done to address #5347 and ensure that the HParams endpoints don't return 400 errors for the common and …
=> hparams: treat no data as an empty experiment rather than an error

tensorboard/webapp/runs/views/runs_table/runs_table_test.ts, tensorboard/webapp/util/matcher.ts, tensorboard/webapp/util/matcher_test.ts
Runs table, when in comparison mode, is capable of rendering experiment
alias and show the full experiment name in the hover text. However,
because we are matching regex against experiment name that is not
visible without a user interaction, the match is quite surprising and is
surprising users.
This change removes an ability to match against the experiment name.
=> runs-table: do not match against exp name

tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html, tensorboard/webapp/theme/_tb_theme.template.scss
ngx-color-picker is capable of automatically position w.r.t. the view
port. However, because:
1. we hard coded "bottom-right" position, and
2. we had flicker of color-picker positioning incorrectly in the
viewport because of lack of `overflow: hidden`
it miscalculated the dialog's position and free space w.r.t. to the view
port. By putting the `overflow`, it knows to only take available pixels
in the view port (instead of making the page scrollable and think that
there exists more space below the view port) into account.
Previous:
New:
=> runs table: fix color-picker position

tensorboard/webapp/settings/_views/BUILD, tensorboard/webapp/settings/_views/settings_dialog_component.ng.html, tensorboard/webapp/settings/_views/settings_dialog_component.ts
We have plans to add more features to the dialog and having the template
in the TypeScript file is hard to read and understand. This change
simply moves the template out into its own file.
=> refactor: move settings template in to html

tensorboard/webapp/metrics/actions/index.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors.ts, tensorboard/webapp/metrics/store/metrics_types.ts, tensorboard/webapp/metrics/testing.ts, tensorboard/webapp/metrics/views/main_view/main_view_container.ts, tensorboard/webapp/metrics/views/main_view/main_view_test.ts
This change refactors so that the settings pane opened state is moved to
the Redux store instead of Angular container.
Besides the refactor, there are no functional changes.
=> time series: move settings pane opened state to store

tensorboard/webapp/metrics/metrics_module.ts, tensorboard/webapp/metrics/store/metrics_reducers.ts, tensorboard/webapp/metrics/store/metrics_reducers_test.ts, tensorboard/webapp/metrics/store/metrics_selectors_test.ts, tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts, tensorboard/webapp/persistent_settings/_data_source/types.ts
This change puts the settings pane opened state in the global settings
storage so the view remain the same as how user has left it.
=> time series: remember settings pane open state

tensorboard/webapp/runs/views/runs_table/runs_table_container.ts, tensorboard/webapp/util/matcher.ts, tensorboard/webapp/util/matcher_test.ts, tensorboard/webapp/util/ui_selectors.ts, tensorboard/webapp/util/ui_selectors_test.ts
ui_selector which provides a convenience selector for getting the run
selection was throwing a JavaScript exception violently when experiment
metadata did not load but runs list was loaded.
Above case can happen when the backend implements /data/experiments
incorrectly and inadvertently apply `limit` on the list of experiments
passed. As such, TensorBoard may not fetch an experiment metadata ever
when list of experiment ids go above `N`.
In theory, there should be a fix to the backend, but we also do not want
the web code to violently throw and henceforth break the app completely.
Especially since the web code never makes use of the experiment name
anymore when filtering, we can easily guard against the case, hence the
change.
=> bug: prevent violent error when Experiment metadata is missing
