- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
WebGL render for the line chart can be problematic if user's system has
limited memory or browser is configured to limit number of WebGL
context. This can manifest, to user, as empty charts or randomly
disappearing lines.
Without an ability to induce the problem and as an emergency mitigation,
we are default using SVG renderer instead of the WebGL one.
In the future, we may want to make this configurable so a user can
change the configuration more robustly.
> time series: force use SVG renderer

- tensorboard/data/experimental/BUILD
- tensorboard/data/experimental/experiment_from_dev.py
- tensorboard/data/experimental/utils.py
`_pivot_dataframe` doesn't depend on `ExperimentFromDev`. Moving it to a separate module allows it to be re-used outside of `ExperimentFromDev`.
> DataFrame API: move ExperimentFromDev._pivot_dataframe to a separate utils.py

- tensorboard/plugins/histogram/tf_histogram_dashboard/BUILD
- tensorboard/plugins/histogram/tf_histogram_dashboard/histogramCore.ts
- tensorboard/plugins/histogram/tf_histogram_dashboard/histogram_core_test.ts
Changes:
- Add special handling for single value data case in legacy histogram visualization logic to support v3 format.
- Also add tests for `histogramCore.ts`.
Visualization with **v3** histogram data input:
- overlay mode: 
- offset mode: 
Visualization with **v2** histogram data input:
> histogram: make legacy histogram visualization compatible with v3 data format

- tensorboard/webapp/widgets/histogram/histogram_util.ts
- tensorboard/webapp/widgets/histogram/histogram_util_test.ts
Change the timeseries histogram visualization logics, before the count of a 0-width bin is split into two halves, now each zero-width bin count will be full allocated to one bin, with the restriction that all redistributed bins (or ranges) are closed-open except the last one.
- Current visualization implementation with **v3** histogram data input:
- Current visualization implementation with **v2** histogram data input:
> histogram: make timeseries histogram visualization compatible with v3 data format

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/route_registry_module.ts
- tensorboard/webapp/app_routing/route_registry_module_test.ts
Change RouteRegistryModule.getRouteConfigs() to have non-nullable return type. Instead of null, we return a RouteConfig with no underlying RouteDefs. This simplifies call sites -- callers can rely on RouteConfig.match() to return null instead of special casing the case where RouteConfig is null.
> Change RouteRegistryModule.getRouteConfigs() to have non-nullable return type.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/app_routing/testing.ts
It seems like at some point the `Navigation` type had a queryParams property. It no longer does but some places that create instances of `Navigation` still set the queryParams object. This cleans up those remaining references.
> Remove unnecessary property from some Navigation-related actions.

- tensorboard/webapp/widgets/experiment_alias/experiment_alias_component.scss
Alias visual component previously put simple faint border around the
text. In order to make it more visually prominent, this change does
following:
- puts chip color
- puts padding so it looks like a chip-esque
- put distinct text color so text is legible under the faint chip color
> alias: improve visuals of alias

- tensorboard/webapp/BUILD
- tensorboard/webapp/widgets/content_wrapping_input/BUILD
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.scss
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.ts
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_module.ts
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_test.ts
This change open sources content_wrapping_input, a component that
behaves a lot like content-editable element that tightly wraps content.
A conventional `<input>` element has a fixed width invariable to size of
the content. If content is too long, there exists mechanisms to scroll
within the input. This behavior is not something that we do not want in
some UI elements and this widget helps with that.
> widget: content wrapping input

- tensorboard/webapp/widgets/experiment_alias/BUILD
- tensorboard/webapp/widgets/experiment_alias/experiment_alias_component.ts
- tensorboard/webapp/widgets/experiment_alias/experiment_alias_module.ts
- tensorboard/webapp/widgets/experiment_alias/experiment_alias_test.ts
Depending on whether the alias component is in an edit mode or not, it
renders a content-wrapping-input.
> alias: implement edit mode

- tensorboard/data_compat.py
- tensorboard/data_compat_test.py
Remove empty buckets on both ends to avoid having `backwards` (left edge > right edge) buckets.
Ran the change internally: cl/407885499
Visualization change:
- before: 
- after: 
> histogram: remove `backwards` buckets in v1 histogram migration

- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/histogram/summary_v2.py
Make sure the output shape wouldn't be dynamic in single value data case.
> histogram: make `summary_v2.histogram_pb` TPU compatible

- tensorboard/webapp/routes/dashboard_deeplink_provider.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_types.ts
- tensorboard/webapp/routes/testing.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/runs/types.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
Time Series does not remember regex query put in the run filter. We remember this by adding it to the URL.
> Time Series: preserve run regex filter string in URL

- tensorboard/plugins/histogram/summary.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/histogram/summary_v2.py
- tensorboard/plugins/metrics/metrics_plugin_test.py
Set V3 implementation as default, dynamic shapes will be eliminated.
Ran internally: cl/408885623
> histogram: set v3 as default

- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
When rehydrate state from url, I shouldn't directly set value to `colorGroupRegexString` and `userSetGroupByKey` of state. This bug only happens for color group by regex. Add one more test to check changes on both regexFilter and color group by regex.
However, It's not caught by the unit test (specifically `'sets regexString on groupBy REGEX'` )is because the state we built up for unit tests allow attribute overwrite.
> Time Series: fix color group preserve bug

- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
For SVG renderer, which is current default, when a line path updates
while invisible, we never update its path leading to very subtle issue.
Repro steps:
1. Find a scalar card with more than two runs (all toggled on here)
2. Toggle all runs off
3. Toggle on run on
4. Zoom in and change viewBox
5. Toggle on another run. Observe that the run line is positioned where
it was in (1).
Fixes b/206638910.
> line chart: fix bug where line does not update

- tensorboard/webapp/BUILD
js_binary cannot build when it misses JS_INFO in the provider
internally. Since sass library does not provide js_info, we are
omitting the dependency
> build: omit SASS target on js_binary

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/BUILD
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
- tensorboard/webapp/theme/_tb_theme.template.scss
Fixes some missing renaming from #5421
> chore: Fix Angular Material style naming

- tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.scss
Fix dark mode color for collapsible groups
before 
after 
light mode
> Time Series: fix dark mode color

- .github/workflows/ci.yml
Newer `@angular/material` disallows using these ambient mixins and color
definitions. This change enforces that via lint.
> chore: guard against mat-color and $mat-*

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Some tag name on cards might be too long and be truncated. We want to provide users a setting to adjust the card width. This pr only includes the part of metrics/ and the card with would be set based on the state value.
Only update the max width of the card in css. The range of the max width is 30-100vw.
> Time Series: adjust card width (UI)

- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
> timeseries: preserve card width setting in local storage

- tensorboard/webapp/BUILD
The alias was introduced to facilitate better migration. Now it serves
no purposes and thus removed.
> chore: remove now defunct webapp:angular_material_theming

- tensorboard/webapp/app_routing/BUILD
- tensorboard/webapp/app_routing/actions/app_routing_actions.ts
- tensorboard/webapp/app_routing/effects/BUILD
- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
- tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/store/app_routing_types.ts
- tensorboard/webapp/app_routing/store/testing.ts
- tensorboard/webapp/app_routing/testing.ts
- tensorboard/webapp/core/effects/core_effects_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
As part of the work to migrate to "time-namespaced state" (Googlers, see http://go/tb-timenamespaced-state) we need to refactor namespace id generation from route_contexted_reducer_helper.ts to app_routing_effects.ts.
This requires changing the navigated() action to include the namespace information - beforeNamespaceId and afterNamespaceId. So there is a somewhat high blast radius. I've tried to ensure that the changes will not break the build. I'll also comment on the PR to try to make sense of the changes.
There is also a new property in app_routing state: activeNamespaceId. We use this to populate the beforeNamespaceId value.
> [time-namespaced state] Generate namespace ids in app_routing_effects.

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Add a feature flag for the new behavior to namespace state sequentially by time rather than by id.
Googlers, see http://go/tb-timespaced-state.
> [time-namespaced state] Add feature flag for time-namespaced state.

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
Motivation: Googlers, see user's latest feedback at b/202013641.
Preview: 
#timeseries
> timeseries: make the slider control min card width

- tensorboard/webapp/app_routing/testing.ts
After https://github.com/tensorflow/tensorboard/pull/5439 we have removed Google-internal usage of buildNavigatedActionFull(). We can now remove the symbol from this repo.
> [time-namespaced state] Remove buildNavigatedActionFull.

- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
A new feature flag was added in #5440 but I forgot to follow the suggestion to name it enableTimeNamespacedState.
> [time-namespaced state] Rename enableTimespace flag to enableTimeNamespacedState.

- tensorboard/webapp/metrics/effects/metrics_effects_test.ts
- tensorboard/webapp/metrics/internal_types.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
In the list of tooltip sorting method, we remove "default" and replace with "alphabetical order". The alphabetical order is based on the display name.
> Time Series: tooltip sort by alphabetical order

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/testing.ts
- tensorboard/webapp/app_routing/types.ts
Moves navigationOptions out of the Route. 
navigationOptions currently only has a `replaceState` property, which is an internal detail of app_routing_effects. Nothing else in the code base depends on this value. I will be adding another property `resetNamespace` to navigationOptions in a followup change, which is another navigation-related internal detail of app_routing_effects.
In practice navigationOptions (replaceState and resetNamespace) is a separate concern from Route. It describes properties that we consider between possible Route transitions rather than a property of Routes themselves.
> [time-namespaced state] Move navigationOptions out of Route.

- tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-viewer.ts
Currently in mesh plugin camera is positioned automatically which may not be convenient for applications where the model predicts both scene mesh/point cloud as well as camera position and orientation. This PR will allow to specify initial camera position and orientation as following:
```
const plugin_config = {
'camera': {
'position': [0, 0, 0],
'look_at': [1, 1, 1]
}
}
```
> Allow camera to have initial position and look-at vectors.

- tensorboard/components/tf_storage/storage_utils.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/app_routing/testing.ts
- tensorboard/webapp/app_routing/types.ts
Support time-namespaced state for back and forward browser buttons and, really, any navigation to a point in browser history. As user navigates we store the namespace id with the history entry. When user navigates using browser history then we read the namespace id to determine which namespace to use.
Most of the changes in app_routing_effects are actually just improvements to the typing for data. We formalize the progression of data transformation -- from Navigation, to RouteMatch, to Route -- and we attach well-typed "NavigationOptions" to the data.
> [time-namespaced state] Support back and forward browser button for time-namespaced state.

- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
After DOM structure refactor, manual extent setting feature was broken
on the x-axis only. This is due to it having `customVis` specified for
it and the customVis was taking all the pointer events, causing :hover
not to function.
This change puts `pointer-events: none` on `.custom-vis` in all cases
and also improved the CSS a little bit.
This will be tested via screenshot tests internally.
> line chart: x-axis extent editable

- tensorboard/webapp/core/views/layout_container.scss
- tensorboard/webapp/metrics/views/metrics_container.scss
Notice that mouse move was causing large paints that it should not.
Putting `contain: strict` which informs browser to put a bound to style
calculation helped alleviate the issue.
Repro: in time series dashboard, with "Rendering > Paint Flashing"
option enabled, mouse move in the dashboard.
> style: optimize paint by putting `contain: strict`

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
PR #5030 divided up the default setting from overrides and, in selector,
we have mixed two values in selectors to make a concrete settings value.
When reset, overriden values were set to `undefined` and caused the
settings to be very wrong.
```ts
// This resolves to {a: undefined}
{...{a: 1}, ...{a: undefined}}
```
Object spread (or `assign`) does not skip a property whose value is
`undefined` and causes settingOverride with undefined value to take
precedence over the default value which, in the end, resolves the image
brightness/contrast values to `undefined` unlike what the types
indicated.
In the end, this is a fault of the type system since the interface is
defined as `Partial<>` and a value should really not have `undefined`
value. To illustrate,
```ts
interface Foo {
bar: number;
} …
```
> timeseries: fix setting reset causing weird behavior

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/app_routing/location_test.ts
- tensorboard/webapp/app_routing/views/router_link_directive_container.ts
So it becomes getFullPathFromRoute().
Migrate the one call to getFullPathFromRouteOrNav() that used a Navigation
to instead call getResolvedPath() directly since this is effectively all
it wanted anyways.
This simplifies the code by allowing us to get rid of the isNavigation()
check.
> [time-namespaced state] Remove Navigation support for getFullPathFromRouteOrNav().

- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts
This change makes two improvements to WebGL support for the line chart.
1. Better feature detection. We now also listen to
`webglcontextcreationerror` which gets emitted when browser fails to
create webgl context from a canvas. This can be a good indication
that user's system may not be able to handle WebGL renderer.
2. Better removal of JavaScript object. When an Angular components get
scrapped, we get a chance to clean more stuff up. With the signal, we
now instruct Three.js renderer to dispose all the objects more
explicitly for better freeing of WebGL context + Three.js objects.
There is no great way to unit test to guarantee correctness of the
utility and the operation. Thus, we will leave such test to an
integration test that would exercise browser capabilities.  For now, we
are …
> line chart: better WebGL edge case handle

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_container_test.ts
- tensorboard/webapp/alert/alert_action_test.ts
- tensorboard/webapp/alert/store/alert_reducers.ts
- tensorboard/webapp/alert/store/alert_reducers_test.ts
- tensorboard/webapp/app_routing/route_config.ts
- tensorboard/webapp/app_routing/route_config_test.ts
- tensorboard/webapp/experiments/store/experiments_reducers.ts
- tensorboard/webapp/experiments/store/testing.ts
- tensorboard/webapp/experiments/types.ts
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/effects/metrics_effects_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/card_lazy_loader.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
- tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
- tensorboard/webapp/plugins/npmi/store/npmi_types.ts
- tensorboard/webapp/plugins/npmi/testing/index.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- tensorboard/webapp/settings/_redux/settings_reducers.ts
- tensorboard/webapp/webapp_data_source/tb_http_client.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils_test.ts
- tsconfig.json
Before this change, below held true:
```ts
interface Foo {
bar?: number;
}
// Legal
const foo1: Foo = {bar: undefined};
// Legal
const foo2: Foo = {};
```
After this change,
```ts
interface Foo {
bar?: number;
baz: number|undefined;
}
// Illegal; `bar` cannot be `undefined` and must be number.
const foo1: Foo = {bar: undefined, baz: undefined};
// Illegal; `baz` property must exist. Must be one of `number` of
// `undefined`.
const foo1: Foo = {};
// Legal; `bar` property does not exist while `baz` is specified.
const foo2: Foo = {baz: undefined};
```
When a property is defined as `?:`, it does not mean that the property
can be `undefined` but it means a property can be omitted altogether or
it must exist with the value of the type as defined. As such, when a
property is written with …
> type: enable `exactOptionalPropertyTypes` option 

- tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_test.ts
On Firefox, IntersectionObserverInit's rootMargin property must have a
unit value and thus cannot be an empty string. As such, our recent
refactor which populated its default value as `""` threw in Firefox
(while Chrome was lenient) causing cards to not appear in TimeSeries
dashboard. This change optionally populates the `rootMargin` property in
`IntersectionObserverInit` instead of default setting values.
The bug was caught in an integration test. Added unit test to fail faster in
the future.
> fix: timeseries rendering issue on Firefox

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/app_routing/testing.ts
Set it whether enableTimeNamespacedState is true or false.
It has no practical impact on the behavior of the application (we don't yet read this value in any case where enableTimeNamespacedState is set to false).
This is a prelimary change to fix some of the navigation issues detailed in b/211018035 (sorry, for Googlers only. I promise to be a bit more descriptive in the PR that actually fixes the issues). I made this change separate from the rest to limit the size of the PR.
In order to minimize impact on tests, a lot of which assert on the number of calls to Location.replaceState(),  I refactored Location.replaceState(data, url) into two separate calls: Location.replaceStateUrl(url) and Location.replaceStateData(data). I can additionally rationalize this by pointing out that …
> (time-namespaced state) Always set namespace id in browser history state.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
This change ensures that we read and reuse namespace id from browser history if a page is reloaded.
Consider the situation where user:
1. Selects to view an experiment and sets tag filter to 'A'.
2. Adds an experiment to the comparison and then sets the tag filter to 'B'.
3. Refreshes the page.
All these actions are supposed to take place in the same namespace. But currently the page refresh breaks this - a page load always generates a new namespace and new namespace id. So if user navigates back to the single view they will see tag filter set to 'A' instead of to 'B'.
> (time-namespaced state) Reuse namespace id on page reload if it exists.

- tensorboard/pip_package/requirements_dev.txt
Upgrade pinned version of black to fix error when running on local desktop. The upgrade doesn't have any side effects. No formatting has changed.
When running `black` in tensorboard, I have been getting following error:
```
File "/usr/local/google/home/bdubois/virtualenv/tensorboard/bin/black", line 5, in <module>
from black import patched_main
File "/usr/local/google/home/bdubois/virtualenv/tensorboard/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
from typed_ast import ast3, ast27
File "/usr/local/google/home/bdubois/virtualenv/tensorboard/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
from typed_ast import _ast3
ImportError: /usr/local/google/home/bdubois/virtualenv/tensorboard/lib/python3.9/site-packages/typ …
```
> infra: Upgrade pinned version of black to 21.10b0.

- tensorboard/uploader/BUILD
- tensorboard/uploader/flags_parser.py
- tensorboard/uploader/uploader_subcommand.py
- tensorboard/uploader/uploader_subcommand_test.py
https://github.com/tensorflow/tensorboard/issues/4765
Modifies flag to support a comma-separated list of experiment ids (while retaining functionality of just one id)
Expected use case:
```
$ ./bazel-bin/tensorboard/tensorboard dev delete --experiment_id=S0kpfaQeTvaSjCA2nTMQFw,K8vwol4qSoi8UqViDj7q0Q
Deleted experiment S0kpfaQeTvaSjCA2nTMQFw.
Deleted experiment K8vwol4qSoi8UqViDj7q0Q.
```
No auth:
```
$ ./bazel-bin/tensorboard/tensorboard dev delete --experiment_id=S0kpfaQeTvaSjCA2nTMQFw,K8vwol4qSoi8UqViDj7q0Q
***** TensorBoard Uploader *****
This will delete the 2 experiments on
https://tensorboard.dev with the following experiment ID:
['S0kpfaQeTvaSjCA2nTMQFw', 'K8vwol4qSoi8UqViDj7q0Q']
You have chosen to delete an experiment. All experiments uploaded
to TensorBoard.dev are publicly …
```
> TensorBoard.dev : Uploader delete functionality supports more than one experiment_id at a time.

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
Previously within a namespace, when experiments are added or removed the load tag metadata is not fired. Now we fire the loading on changes of route id. The key change for this pr is cardMetadataMap is reset. The map contains data from previous route and, because the namespace does not change, the map is outdated (includes card id of removed experiments). It is safe to reset the map because the metadata loaded action is fired after receiving complete tag metadata.
Other corresponding state updated include nextCardToPinnedCopy nextPinnedCardToOriginal.
> [time-namespaced state] Fix tags and pinned cards on experiments adding/removal

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/store/app_routing_types.ts
- tensorboard/webapp/app_routing/store/testing.ts
As desribed in detail in b/211018035 (sorry, Googlers only), there is tension between ngrx-managed state and state as described in the URL.
We can get in situations where user navigates back and forward in browser history and the state rehydrated from the URL overwrites ngrx-managed state. In the case of namespaced state it can often overwrite the WRONG state since the rehydration happens before namespace resolution is completed.
The solution we propose is to rehydrate state from the URL less frequently. We skip rehydration from URL if navigating to a namespace that we already have tracked in ngrx-managed state.
This approach will solve a bunch of navigation bugs in route-namespaced state but will also avoid some weird potential navigation bugs in the new time-namespaced state.
It does …
> (time-namespaced state) Only rehydrate state from url for namespaces not seen since page load.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/internal_utils_test.ts
- tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
- tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/testing.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
After removing most of routeId in #5464 and then following up with changes to internal code, we can complete the removal of the term "RouteId". Notable changes:
* `getRouteId` ngrx selector is removed.
* `route_contexted_reducer_helper`'s `onRouteIdChanged` argument is renamed to `onRouteKindOrExperimentsChanged`.
* test helper function `buildNavigatedToNewRouteIdAction` is renamed to `buildNavigatedToNewExperimentAction`.
* The one remaining usage of "RouteId" is for generating namespace ids for App Routing. We therefore rename the internal function `getRouteId()` to `getRouteNamespaceId()` to signal the narrowed purpose of the function. Note that we will remove `getRouteNamespacedId()` with the launch of go/tb-timespaced-state.
> (time-namespaced state) Complete removal of routeId.

- tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
- tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/hparams/_redux/types.ts
- tensorboard/webapp/metrics/store/metrics_initial_state_provider.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_types.ts
Update route_contexted_reducer_helper to use "Namespace" instead of "Route" for symbols. Try to update the remainder of the code base to match. At a high level, make the following replacements in the code:
RouteContexted => NamespaceContexted
Routeful => Namespaced
Routeless => NonNamespaced
Also update the documentation in route_contexted_reducer_helper to reflect the "Namespace" concept and be less route-centric.
We do not update the file names (route_contexted_reducer_helper(_test).ts) at the moment but will in a subsequent change.
Note that this change should be safe to import into the Google-internal repo after cl/417855741 is submitted.
> time-namespaced state: Update symbols in route_contexted_reducer_helper.

- tensorboard/compat/proto/BUILD
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/coordination_config.proto
- tensorboard/compat/proto/full_type.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/compat/proto/trackable_object_graph.proto
In preparation for TensorBoard 2.8.0 release we update our compat protos to match tensorflow v2.8.0-rc0.
> chore: Update tensorboard compat protos using tensorflow v2.8.0-rc0.

- tensorboard/compat/proto/BUILD
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/coordination_config.proto
- tensorboard/compat/proto/full_type.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/compat/proto/trackable_object_graph.proto
Cherry-picked from master.
In preparation for TensorBoard 2.8.0 release we update our compat protos to match tensorflow v2.8.0-rc0.
> Cherry-pick: Update tensorboard compat protos using tensorflow v2.8.0-rc0. (#5484)

- .github/workflows/ci.yml
Follow release instructions to update CI configuration for 2.8 branch to refer to tensorflow 2.8 release candidate.
> chore: Update 2.8 branch CI to use tensorflow 2.8.0rc0.

- third_party/html5lib.BUILD
- third_party/python.bzl
As noted by https://github.com/tensorflow/tensorboard/issues/5478 , tensorboard fails when run in a python 3.10 environment. The reporter fortunately discovered that the problems would be fixed with an upgrade of our html5lib dependency.
I tested by building a python3.10 virtualenv on my machine (this required building python 3.10 from source as we don't have it natively).
```
$ virtualenv -p /usr/local/bin/python3.10 ~/virtualenv/tensorboard-python-3.10
$ source ~/virtualenv/tensorboard-python-3.10/bin/activate
$ python3.10 -m ensurepip --upgrade
$ python3.10 -m pip install tensorboard
$ tensorboard --version
File "/usr/local/google/home/bdubois/virtualenv/tensorboard-python-3.10/bin/tensorboard", line 5, in <module>
from tensorboard.main import …
```
> chore: Upgrade html5lib to version 1.1.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
Changing the preferred renderer back to WebGL after crash mitigations.
> Prefer the WebGL Renderer

- tensorboard/defs/defs.bzl
- tensorboard/defs/terser_config.json
Users have reported problems loading TensorBoard in Safari: https://github.com/tensorflow/tensorboard/issues/5489
Thanks to @severo and @bileschi we were able to identify the problem to an incompatibility between threejs (which we use for WebGL rendering) and terser (which we use for minimizing/optimizing our code). 
Angular encountered this problem last year and worked around it by changing their terser config by reducing number of passes from 3 to 2: 
* https://github.com/angular/angular-cli/issues/21107
* https://github.com/angular/angular-cli/commit/2c2b499193fb319e1c9cb92318610353b7720e2b
In our case I have to reduce the number of terser passes from 3 to 1. For some reason reducing to 2 does not solve the problem.
This change surprisingly appears to reduce binary size. Before this …
> Change terser configuration to workaround threejs/terser incompatibility.

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/data_ingester.py
- tensorboard/backend/event_processing/data_ingester_test.py
Conditionally import `tensorflow_io` module for additional cloud file system support (https://www.tensorflow.org/io). If the module is missing, prompt the user to run `pip install tensorflow_io`. 
Relevant issues:
- https://github.com/tensorflow/tensorboard/issues/5359
- https://github.com/tensorflow/tensorboard/issues/5480
> gfile: conditionally import tensorflow_io

- tensorboard/webapp/core/views/layout_container.scss
When the sidebar got resized and the width is small enough, we collapsed it. The bug is the expander used to reopen the sidebar disappears and the sidebar can never be expanded again. (What's worse is we remember this setting in local storage)
before 
after
The contain style is used to optimize the rendering, indicating the element might be independent of the rest of the dom tree. But for the expander, the width can't be sized without its descendants' sizes (the icon). Updates the contain to remove size from the consideration. `contain: content;` is equivalent to `contain: layout paint`
> layout: adjust contain style to show the expander

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/data_ingester.py
- tensorboard/backend/event_processing/data_ingester_test.py
Current sync failure: cl/421703176
- Use `tensorboard.compat.tensorflow_stub.errors` instead of `tf.errors`
- To fix: `module 'tensorflow' has no attribute 'errors'`
- Properly mock `import` errors
- Remove `autospec=True` for failed tests:
-  `testCheckFilesystemSupport_importTFIO` and `testCheckFilesystemSupport_raiseError`
Tested internally:  cl/421719230
> Fix errors in copybara import.

- tensorboard/backend/event_processing/data_ingester.py
- tensorboard/backend/event_processing/data_ingester_test.py
Add test for `getattr(tf, "__version__", "stub")` condition, to fix the mutation testing error in cl/421703176.
Also sort the imports alphabetically for lint.
> copybara: fix mutation testing error 

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
fix experiment data initial loading on timeNamespacedState enabled.
This only happens when the browser is initiated on experiment view and timeNamespacedState is enabled from the param. `NamespaceUpdateOption` is set to `NEW` initially and gets updated to `UNCHANGED` on any navigation afterwards.
However in loading experiment view initially there is no navigation actions therefore the option remains `NEW`, which generates a new namespaceId. 
In the fix we set the value to `UNCHANGED` after the first run of app navigation flow. However this is tircky to add the unit tests. InitAction perfectly ran only once of the changed part and trigging any follow up actions triggers navigation$.
Add webtests to catch this. (googlers, please see cl/421637297)
> time-namespaced state: fix experiment data initial loading on timeNamespacedState enabled

- .github/workflows/ci.yml
My attempt to pin 2.8 branch CI to tensorflow==2.8.0rc0 (#5486) was incorrect. The instructions on how to pin CI to a specific version of tf were stale.
> Pin 2.8 branch CI to TF 2.8.0rc0 for real.

- RELEASE.md
Please view commit https://github.com/tensorflow/tensorboard/commit/52857c3463b6b0131728012f686576b20ed6906a for the changes since the original attempt to add release notes in https://github.com/tensorflow/tensorboard/pull/5487.
> Add release notes for Tensorboard 2.8.0.

- RELEASE.md
- tensorboard/version.py
As per release instructions (go/tensorboard-release, step 8), bump up the version and cherry-pick the release notes.
> Update master branch after 2.8.0 release.

- tensorboard/webapp/app_routing/namespaced_state_reducer_helper.ts
- tensorboard/webapp/app_routing/namespaced_state_reducer_helper_test.ts
- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/runs/store/BUILD
- tensorboard/webapp/runs/store/runs_reducers.ts
Instead of listening on navigated action in feature reducer, we should implement `onRouteKindOrExperimentsChanged` and pass into `createNamespaceContextedState` which then runs on route (rout kind or experiments) changed. 
However it might be unclear for reducers that the state it returns only takes place when route changed (if there is no route change, the new state is not effective)
We tgeb move this logic out of app_routing and let feature reducers decide what they want to do on `navigated` action.
For the current metrics/ and runs/, the states are updated on route changed.
> time-namespaced state: generalize navigated callback function on createNamespaceContextedState

- .github/workflows/ci.yml
The 2.7 branch ci.yml does not correctly specify which tensorflow to use for testing - it uses tf-nightly. Update to use tensorflow 2.7.0.
> Fix 2.7 branch ci to use tensorflow 2.7.0.

- .github/workflows/ci.yml
The 2.6 branch ci.yml does not correctly specify which tensorflow to use for testing - it uses tf-nightly. Update to use tensorflow 2.6.2.
> Fix 2.6 branch ci to use tensorflow 2.6.2.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/programmatical_navigation_types.ts
Adds support to programmatical navigation to allow resetNamespacedState to be set. This is similar to how the routerLink directive supports a resetNamespacedState attribute.
If unspecified then it is treated as false (aka NamespaceUpdateOption.UNCHANGED).
I tested it by importing into the internal repo and modifying one of the programatical navigations to set this to true. I loaded the app with enableTimeNamespacedState and observed that performing the corresponding action reset the namespaced state.
> time-namespaced state: Support resetNamespacedState in programmatical navigation.

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_file_loader_test.py
Small cleanup (tracking issue: #2007) before making some additions to this test. We don't actually need real TF for this test, so it's better to avoid the dependency.
> backend: remove unnecessary TF dep from event_file_loader_test.py

- tensorboard/webapp/runs/actions/runs_actions.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/runs/store/runs_selectors.ts
- tensorboard/webapp/runs/store/runs_selectors_test.ts
- tensorboard/webapp/runs/store/runs_types.ts
- tensorboard/webapp/runs/store/testing.ts
- tensorboard/webapp/runs/store/utils.ts
- tensorboard/webapp/runs/store/utils_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- tensorboard/webapp/util/ui_selectors.ts
- tensorboard/webapp/util/ui_selectors_test.ts
Convert run selection state to be namespaced so that run selection is preserved as users navigate within time-namespaced scenario.
It's not clear to me why this wasn't already namespaced. Instead the run selections were keyed by "RouteKey" -- the set of experiments from the route -- effectively making it behave like namespaced state for the route-namespaced scenario. The documentation makes some claims that we'd want to share the state in some special way between experiment list and dashboard but, in practice, you can't do run selections in experiment list. None of the tests give any hint, either.
With the refactoring I'm also able to move run selection state to "UI" state rather than "Data" state, thus satisfying an old TODO.
How I tested: Imported internally and ran all tests. Ran …
> time-namespaced state: Convert run selection state to be namespaced.

- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_storage/storage_utils.ts
We discovered an odd navigation-related bug in internal TensorBoards, described in detail in http://b/216307695. TensorBoard, in certain circumstances, will create extra entries on the browser history by modifying `window.location.hash` unnecessarily.
In short, the most relevant causes of this problem:
1. Sometimes `HashStorageComponent` will (unnecessarily) clear the plugin id. (Fortunately, by the time the page finishes loading the plugin id will be restored.) 
2. Further down the call stack, `storage_utils.unsetFromURI()` will clear the plugin id from the url hash. Unfortunately it will do this by directly modifying `window.location.hash`, creating an unnecessary entry in the history state.
This change address cause 2, allowing unsetFromURI() to modify the url hash using …
> Use window.location.replaceState when unsetting plugin hash.

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/backend/event_processing/event_file_loader_test.py
This implements an optional mode in our Python `EventFileLoader` that will attempt to detect and handle the case when an event file is replaced entirely with a new version of the file containing additional data (rather than the new data being appended to the existing file, the normal behavior we expect).
This situation occurs for example when using `rsync` as described in #349.  When run without the `--inplace` option, `rsync` will transfer data to a temporary file and then swap it in for the final file, but this means that TensorBoard will only ever see the first version of that file and never shows any updates to it until it's restarted.  A similar issue happens for internal users - Googlers, please see b/201113906 for context.
The new logic uses `stat()` to monitor the size of the …
> backend: implement event file replacement detection

- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
This updates plugin_event_accumulator_test.py to use real mocking (aka `unittest.mock`) rather than hand-written monkey-patching.  This simplifies the logic, and makes it robust to changes in the arguments that are propagated from the accumulator to the underlying generator (since we're ignoring all the arguments in the mocks anyway).
This is pre-work for #5530.
> cleanup: use real mocking for plugin_event_accumulator_test.py

- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/data_ingester_test.py
- tensorboard/plugins/core/core_plugin_test.py
We have a few FakeFlag instances in our tests.  We periodically have to add flags to these (for new flags that we're introducing or existing flags we're using in new places), but since the flags aren't in any particular order, it's kind of messy and hard to tell where to put the flag / whether a flag is already present.
This resolves this by just alphabetizing the flags.  We also make them all keyword args (rather than special-casing `logdir` to be a positional argument).
This is pre-work for #5530.
> cleanup: alphabetize argument order for FakeFlags

- tensorboard/backend/event_processing/data_ingester.py
- tensorboard/backend/event_processing/data_ingester_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
- tensorboard/program_test.py
Add the `--detect_file_replacement` flag to control the behavior introduced in #5529, and all the associated plumbing in between.
Note: since this flag would currently be pointless for RustBoard (`--load_fast=true`) we disallow the combination, and in the default automatic selection logic (`--load_fast=auto`), we check for this flag and don't use RustBoard if it was passed.
Tested: ran TensorBoard with these changes enabled (including behavior-introducing PR) and confirmed that it now picks up new data when replacing an event file entirely rather than appending to it, writes the appropriate log messages, disables RustBoard, etc.
Diffbased on top of #5543 and #5544.
Cc: #349.
> core: add --detect_file_replacement flag and plumbing

- tensorboard/backend/event_processing/data_ingester.py
- tensorboard/backend/event_processing/data_ingester_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
- tensorboard/program_test.py
_This is a re-do of #5530, which I accidentally merged into the wrong branch (the temporary one I was using as a diffbase, rather than the intended destination of `master`)._
Add the `--detect_file_replacement` flag to control the behavior introduced in #5529, and all the associated plumbing in between.
Note: since this flag would currently be pointless for RustBoard (`--load_fast=true`) we disallow the combination, and in the default automatic selection logic (`--load_fast=auto`), we check for this flag and don't use RustBoard if it was passed.
Tested: ran TensorBoard with these changes enabled (including behavior-introducing PR) and confirmed that it now picks up new data when replacing an event file entirely rather than appending to it, writes the appropriate log messages, disables …
> core: add --detect_file_replacement flag and plumbing (redo)

- tensorboard/plugins/graph/tf_graph_common/minimap.ts
- tensorboard/plugins/graph/tf_graph_common/util.ts
- tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-loader.ts
- tensorboard/plugins/projector/vz_projector/data-provider.ts
- tsconfig-lax.json
The internal languages team wants to turn on the useUnknownInCatchVariables compiler option and asked us to upstream some changes. Googlers, see: http://b/215141918 and http://cl/420753218.
This impacts the polymer codebase only, which compiles in a non-strict mode (whereas the Angular codebase is compiled in strict mode and, so, was already subject to useUnknownInCatchVariables).
I turned on the useUnknownInCatchVariables and tried to run the app. I fixed each error by typing the caught exception as `: any`. I then cross referenced with http://cl/420753218 to ensure I made the correct changes.
> chore: Enable useUnknownInCatchVariables for polymer code.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/internal_utils_test.ts
- tensorboard/webapp/app_routing/location.ts
- tensorboard/webapp/app_routing/location_test.ts
- tensorboard/webapp/app_routing/namespaced_state_reducer_helper_test.ts
- tensorboard/webapp/app_routing/route_config.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/store_only_utils_test.ts
- tensorboard/webapp/app_routing/testing.ts
- tensorboard/webapp/app_routing/types.ts
- tensorboard/webapp/app_routing/views/router_outlet_test.ts
- tensorboard/webapp/util/ui_selectors_test.ts
Move pathname and queryParams from the broadly-used Route type into app_routing_effects's InternalRoute. These properties are only really used by app_routing_effects. 
Deleting the properties means I can delete meaningless references to them in many tests.
> time-namespaced state: Move pathname and queryParams out of Route.

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/internal_utils_test.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers.ts
- tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
- tensorboard/webapp/app_routing/store/app_routing_types.ts
- tensorboard/webapp/app_routing/store/testing.ts
- tensorboard/webapp/app_routing/types.ts
There are some browser history navigations where we were not appropriately rehydrating URL state. The root cause was that we were only rehydrating URL state at most one time for each namespace. But, in reality, we might need to do it multiple times: one time for the experiment list view and another time for the dashboard view.
(Googlers, see internal bug b/216829997).
This change fixes the issue by adding another dimension when determining whether we can rehydrate URL state. The dimension is based on `RouteKind` but actually represented by a new `DeepLinkGroup` enum.
The mapping of `RouteKind` to `DeepLinkGroup` is explicitly defined in the app routing code:
* `DeepLinkGroup.EXPERIMENTS` = `[RouteKind.EXPERIMENTS]`
* `DeepLinkGroup.DASHBOARD` = `[RouteKind.EXPERIMENT, …
> time-namespaced state: Improve how we decide when to rehydrate state from URL.

- package.json
- tensorboard/defs/defs.bzl
- tensorboard/defs/internal/js.bzl
- tensorboard/webapp/testing/require_js_karma_config.js
- yarn.lock
Upgrade `marked` to version 4.0.10 to fix a [security vulnerability](https://github.com/tensorflow/tensorboard/security/dependabot/yarn.lock/marked/open).
Original request: https://github.com/tensorflow/tensorboard/pull/5506
Tested internally: cl/424877602
> chore: upgrade marked to version 4.0.10

- tensorboard/plugins/graph/keras_util.py
`layer_config` could be a keras Policy object. Gracefully fall with checking the type. #5548
> keras: skip config if it's a policy obj

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/internal_utils_test.ts
To avoid repeated timestamp causing name space id collision, we add a random generated prefix.
> time-namespaced: adding unique index on generating name space id

- tensorboard/webapp/runs/store/runs_selectors.ts
- tensorboard/webapp/runs/store/runs_selectors_test.ts
- tensorboard/webapp/util/BUILD
- tensorboard/webapp/util/ui_selectors.ts
- tensorboard/webapp/util/ui_selectors_test.ts
#5525 introduced a regression in some multi-experiment environments where the runs from experiments no longer included in the dashboard view were still being displayed in charts. (Googlers, see b/216530111)
We no longer store run selection keyed by the experiments in a route (again, because of #5525). So instead of relying on the state layer naturally filtering the runs for us, we must now do it in the ui_selectors layer. We use runIdToExpId map to filter the runs to only those in the existing set of experiments.
> time-namespaced state: Filter runs to include only those in current route.

- tensorboard/plugins/core/core_plugin.py
The help doc is stale. "Setting `"images=0"` to show all samples" is not supported anymore. Updates it to match the actual implementation. #5550
> core: updates `--samples_per_plugin` help command

- tensorboard/backend/event_processing/data_ingester_test.py
This fixes an internal order-dependent error (b/218420006). Mocking lazy-loaded TF symbols before actually loading them is problematic, the mocked modules won't unmock properly. In the future we should avoid mocking such symbols.
Googlers, see b/150299895 for more details.
> backend: load the lazy-loaded TF module before mocking them

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
The small black "tick" shown on hover in Angular `<mat-slider>` is actually created by background (with `repeating-linear-gradient`) which is not customizable. It is difficult to create dots as well as control how many ticks we want to show. 
I then created another layer on top of it to generate the gray dots. In single selection, only a single tick shows. In range selection, those ticks included in a range appears. 
There is no control over the thumb position for now. 
single selection (the steps of this image is 0 to 7)
range selection
steps included in partial range
> linked time: Adds gray ticks to sliders on image cards

- docs/migrate.ipynb
Preview: https://github.com/yatbear/tensorboard/blob/summary_docs/docs/migrate.ipynb
#tf_summary #v1_to_v2
> docs: update migration guide to include TF2 invocation in TF1 summary APIs

- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
The background of charts in scalar card have black backgrounds. It is because of the threejs upgrades https://github.com/tensorflow/tensorboard/commit/420916a6e4c80740432f1e2bd0c83d6dd145da10. Before we find a long-term solution, we can set the background opacity to zero as the temporary fix 
before 
after
> scalar: manually set background to transparent

- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Removes self-provided context in threejs WebGLRenderer to let alpha attribute applied to the context. 
It is suggested by threejs developers yet I am not sure why it is not affecting our chart (the background is still transparent with provided context param)
screenshot
googlers please see cl/363052284 for webtests result
> scalar: removes self-provided context param in WebGLRenderer

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
- tensorboard/webapp/widgets/range_input/BUILD
- tensorboard/webapp/widgets/range_input/range_input_component.ng.html
- tensorboard/webapp/widgets/range_input/range_input_component.scss
- tensorboard/webapp/widgets/range_input/range_input_component.ts
- tensorboard/webapp/widgets/range_input/range_input_module.ts
- tensorboard/webapp/widgets/range_input/range_input_test.ts
Now on single selection we only provides a slider to drag while under range selections there are two input area to set the exact selected steps. We want to enable users to set exact number in single slider too. 
By doing this we extend `tb-range-input` component to also cable of rendering single slider. The output of the component now contains `singleValue` in addition to `rangeValues`. In addition, an action is dispatched on upperValue removed. This is for syncing the `useRange` to decide it is single or range selection across the app. (for example, we need to update the fob(s) from two to one or vice versa)
Summary of changes:
* The "use range" checkbox is removed.
* `<mat-slider>` is moved from`settings_view_component` to inside `<tb-range-input>`
* `handleInputChange()` handles the …
> linked time: updates range input to contain single selection

- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Previously we have those gray ticks to show the selected step(s) in linked time. This pr moves the thumb to the selected step, the image also changes correspondingly. There is still one tick rendered but it will be covered by orange thumb.
Note that this pr only moves the thumb (controlled by `stepIndex`) when selected step matches. Not move to the closest step. Also because of the nature of image cards (which shows one image at a time) we do not move the thumb on range selection for now before more complicated decision is made. 
demo
https://user-images.githubusercontent.com/1131010/154165453-efe655ff-864a-4af1-90f3-52ab9fa162fa.mov
> linked time: moves Image thumb slider on single selection

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
I was renaming the param of range input and overlooked the one in settings.  This pr should fix it.
This was not caught due to unused attr of tb-range-input. This pr also removed useless tests to avoid false tests pass. The elements inside tb-range-input is not testable in settings_view component.
before 
after (without checked enabled the input stays disabled)
> linked time: fix range input param rename

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
Property 'enabled' comes from an index signature, so it must be accessed with ['enabled'].
Googlers, please see cl/363052284 for sync result.
> sync: fix index signature accessed 

- docs/debugger_v2.md
> Changing the broken link as the existing link throws 404 error
> Fixing the broken link in debugger_v2.md for `Transformer model` in [this section](https://www.tensorflow.org/tensorboard/debugger_v2#performance_overhead)
> No UI change and its just a documentation fix
> Added the correct hyperlink for transformers folder in models repo.
> None
> Update debugger_v2.md to fix an invalid link

- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Previously we have gray ticks indicate selected steps in range. This pr further colors the range. The coloring also supports selected steps does not have data (image here).
Current Image slider places ticks with the number of steps not the step values makes us cannot directly use end step and start step to calculate the tracker width. I choose to check the unit where start/end step exists and make the width proportional to the value. For example, we have steps [10,20,30,100] and range [20,65]. The range slider looks like:
The track takes 50% of the unit between step 30 and 100.
Screenshots
start step and end step in between two steps: track with no gray ticks
steps are patricianly in range
Summary of technical changes:
* Hide the slider of `<mat-slider>` (only keeps the thumb) when it is …
> linked time: color image slider in range selection

- tensorboard/webapp/core/types.ts
- tensorboard/webapp/plugins/plugins_component.ng.html
- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Currently on data load failure the plugin page can render two different templates, "unknown" and "not found", but they are used only by tb.dev. Therefore the default template, which is showing "Data could not be loaded" without further information, is shown most of the time.
Now we want to show meaningful message on the page when the error return from server is **permission denied**.  The plugin component now also takes the permission denied template input if provided.
Googlers, please see cl/432024734 for screenshots and test result.
> plugins: extends plugins component to take permission denied template

- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
On single selection currently histogram card only show data with the matched step. We want to enable color displaying on those hovered steps.
This could not be done in css (using `:hover`) is because the color comes from d3 (with `d3ColorScale`). Thus we add/remove `.no-color` class on mouse enter/leave.
Screenshot: selected step 0, hover over step 235
> linked time: Show histogram with color on mouse hovering

- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Previously on single selection we only move the thumb to steps when it is exactly matched with selected step. Now we want to move the thumb (to show the corresponding image) when the selected step is "close enough".
We define the "close enough" to be 10% of the distance between two step values. For example we have steps [20, 50, 200, 400]. We move the thumb to 50 when its range is within 47-65. Calculated by 10% of (50-20) and 10% of (200-50).
screenshot shows the step is 91800 and the thumb moved to the step when selected time is 918100.
Note: this pr also includes some refactor of tests hierarchy, most of the tests are not intended to be re-reviewed. Only four new tests are added into "single selection"
Test hierarchy
```
linked time
|-ticks
|-render sliders
|-thumb movement
|-single …
```
> linked time: moves thumb to closest step on single selection when they're "close enough"

- tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
In #5582  we added "Permission denied" to the failure code. Here in this pr we check the return http error code; if it is 403 then we set the failure code to be `PERMISSION_DENIED`
> plugins: add permission denied code to tb server

- tensorboard/webapp/BUILD
- tensorboard/webapp/widgets/dropdown/BUILD
- tensorboard/webapp/widgets/dropdown/dropdown_component.ts
- tensorboard/webapp/widgets/dropdown/dropdown_test.ts
This is the first step for b/222085838. The additional argument is needed due to the formatting (bold alias prefix) for each dropdown option.
> alias: add displayAlias to DropdownOption

- tensorboard/webapp/angular/BUILD
- tensorboard/webapp/widgets/dropdown/BUILD
- tensorboard/webapp/widgets/dropdown/dropdown_component.ts
- tensorboard/webapp/widgets/dropdown/dropdown_test.ts
The list of `mat-option` elements are rendered in a separate overlay container outside the DOM instead of as a descendent of `mat-select`, therefore we cannot directly query by css to check the text contents. Fortunately we can use the Angular component test harnesses ([MatSelectHarness](https://material.angular.io/components/select/api#MatSelectHarness)) to properly interact with `mat-select` and `mat-option` in the test environment.
Tested internally: cl/433235493
> alias: test mat-option DOM using Angular test harnesses

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_module.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
As the escalation mark shown in histogram and scalar card when linked time is clipped, we want to add the same for image card by reusing module `vis_selected_time_warning` The logic follows what already used by histogram/scalar card. 
screenshot
> linked time: adds clipped text hint on image card

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_warning_component.ts
Replace the current `*ngIf=` with the param `isClipped` to apply `selected_time_warning_module`. This PR should not change current behavior and existing tests.
Note: Adding ``isClosestStepHighted`` is blocked.
The reasoning usage for `isClosestStepHighted` is to pass in a method. 
```
// ...ng.html
<vis-selected-time-warning
[isClosestStepHighted]="isClosestStepHighted()"
></vis-selected-time-warning>
// ..componet.ts
isClosestStepHighted() {
return ..;
}
```
For scalar/histogram, we want to move the fob position, which is blocked by fob implementation.
For image card, the movement of stepIndex is moving to reducer in #5615 . That is to say, at the views level, it does not know if the stepIndex has been adjusted based on selected time change. We will need to introduce additional state for …
> linked time: rendering warning component with isClipped param

- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
When adding a extra layer to include `vis-selected-warning` module in #5612, I accidentally named the layer the same name as `<tb-truncated-path>` (both named as "tag"). Luckily the extra css effects did not change the style. 
Rename the inner layer to "tag-path".
> linked time: rename truncated path class

- tensorboard/webapp/widgets/linked_time_fob/linked_time_types.ts
Creates interface definition that will be used to implement a draggable fob in both histogram and scalar cards
> add FobCardAdapter interface definition

- tensorboard/webapp/widgets/histogram/BUILD
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_test.ts
- tensorboard/webapp/widgets/histogram/histogram_module.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_types.ts
This is a refactoring of the logic used for dragging the linked time fob in the Histogram Card. The previous implementation did not allow for the use cases needed in the Scalar Card. Our goal is to pull out the logic that will be histogram specific into a class that is generalizable. The CardFobAdapter interface created in #5623 is the generalization that will be implemented in both the Histogram and Scalar cards to allow for different uses of the draggable fob.
> Create histogram fob adapter component and use with LinkedTimeFobControllerComponent

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss
- tensorboard/webapp/widgets/histogram/histogram_component.scss
The small histogram tooltip can be cutoff by the top or right edges (Googlers, see b/226775031).
A couple of ancestor elements of the tooltip element currently set `overflow: hidden`. We change these elements so that the effective value is 'overflow: visible'.
This has the somewhat unintended side effect of exposing an additional ~1px height flat line just above the x axis (because the set of lines in the '.content' element ever so slightly overflow). This is probably ok since we'd prefer for the user to see all histogram lines. We should consider in the future tightening up the histogram rendering so that all the lines fit nicely into the '.content' element. (Googlers, see screenshot diffs in cl/437279846).
* …
> Show histogram tooltips that bleed out of content box.

- tensorboard/pip_package/requirements.txt
werkzeug package 2.1.0 is released, which BaseResponse is no longer supported in that latest version.
https://werkzeug.palletsprojects.com/en/2.0.x/wrappers/
This breaks our py tests (#5637) in both tb-nightly and CI as the env install tf-nighly with the requirement of `>=0.11.15`. This PR limit the `werkzeug` pkg version to be less than `2.1.0`. This makes the syntax in current tests are still available.
> pip: limit werkzeug version to less than 2.1

- tensorboard/backend/application_test.py
- tensorboard/backend/empty_path_redirect_test.py
- tensorboard/backend/experiment_id_test.py
- tensorboard/backend/path_prefix_test.py
- tensorboard/backend/security_validator_test.py
- tensorboard/examples/plugins/example_raw_scalars/test.py
- tensorboard/pip_package/requirements.txt
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/mesh/mesh_plugin_test.py
- tensorboard/plugins/projector/projector_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/uploader/server_info_test.py
werkzeug package is updated to 2.1 which `BaseResponse` is no longer supported. 
https://werkzeug.palletsprojects.com/en/2.0.x/wrappers/
This PR updates all `BaseResponse/BaseRequest` usage to the newer `Response/Request` and removes the constraint of werkzeug version
> pip: updates werkzeug to use Response in werkzeug 2.1

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_controller.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_types.ts
This change moves the AxisDirection definition from the linked_time_fob_controller_component.ts file to the linked_time_types.ts file.
The AxisDirection is used in multiple places and going to be used in more places in the future. It makes more sense to have it's type definitions in the file specifically made for types.
Also, I realized the ScalarCardComponent was still using AxisDirection when it did not need to so I simply removed it instead of updating the path.
> Move AxisDirection definition to linked-time-types file

- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Motivation and full context please see https://github.com/tensorflow/tensorboard/pull/5615.
This PR updates stepIndex on range selection:
* Removes the stepIndex in image_container entirely
* Moves the logics (update within/outside range) to `metrics_store_internal_utils`
* Moves corresponding tests in `image_card_test` to `metrics_store_internal_utils_test` cause the thumb movements are no longer updated in the view
This PR also includes some clean up in `metrics_store_internal_utils_test.ts`
> linked time: stepIndex moving: moving thumb movement of range selection to stepIndex update in reducer

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
We've updated cardStepIndex on and only on select time changed. This causes issue when select time is enabled the very first time, there is no linked time set yet and the card step index remain unchanged. However, in settings panel we still show the min step and single selection (while the select time is null in ngrx state). This causes a bad ux when the image steps actually matches the min step: logically we should move the step index but we did not. 
This PR sets card step index when linked time is enabled. `generateNextCardStepIndexFromSelectedTime` is reused. If select time is not set, we take the min step and apply single selection to update the image card step index.
Full context please see #5615 
Note: we did not test `generateNextCardStepIndexFromSelectedTime` on …
> linked time: updates cardStepIndex on selected time toggled

- tensorboard/webapp/widgets/dropdown/dropdown_component.scss
- tensorboard/webapp/widgets/dropdown/dropdown_component.ts
Long options within a tb-toolbar would wrap in an overlapping way.
Added a span around the option, with the non-truncated/full value as the title and the suppressed the wrapping.
> Fix option wrapping within tb-toolbar

- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
Adds tests for `generateNextCardStepIndexFromSelectedTime` usage in `metrics_reducer`. Full context please see #5615 
The changes of `selectedTime` in this reducer have been tested. The logics of the method also have been tested in `stor_internal_utils` and not intent to repeat here. The tests on this higher reducer level is just to test the method returns `cardStepIndex`, which used to update (or not update) the next `cardStepIndex` state.
> linked time: stepIndex moving: tests for card step updated on timeSelectionChanged

- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.scss
This fixes a bug that centers the fob in the wrong direction when the axisDirection is set to horizontal.
The horizontal-fob class is currently not used but, it will be used when the LinkedTimeFobController is used in ScalarCards. Therefore there is currently no functional change.
> Horizontal fobs should be centered on X axis not Y axis

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
As in previous PR comment #5624 from @bmd3k, the "value" in "stepValues" are meaningless. This PR simply renames all "stepValues" to "steps" for image card.
No additional logic are addressed.
> linked time: cleanup: rename stepValues to steps

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
This PR creates the ScalarCardLinkedTimeFobController. This will be used to replace the fob logic in ScalarCardComponent and will eventually be used to implement the fob dragging feature.  Currently it only implements enough to handle the placement of the fobs.
This new component will be used in a similar way to the [HistogramLinkedTimeController](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_controller.ts).
> linked time: Create minimal usable ScalarCardLinkedTimeFobController

- tensorboard/webapp/settings/_views/settings_dialog_component.ts
Tensorboard has a couple `FormControl`s which will be broken when typed forms lands in v14 inside google3. Ordinarily, you'd want to use the opt-out symbol (`UntypedFormControl`). However, since Tensorboard needs to be simultaneously compatible with both v12 (on Github) and v14 (inside google3), we can use this cast as a trick to disable the new types.
Forward compatibility with upcoming changes in google3.
Add casts to `FormControl` in order to prevent type inference.
N/A -- types only change. No runtime effect is possible.
`blaze build //third_party/tensorboard/webapp/settings/_views:_views`
* Alternate designs / …
> angular: update FormControl usages to be forward compatible with typed forms.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
This PR replaces the linked time fob and all the logic for that fob inside the ScalarCardComponent with the ScalarCardLinkedTimeController. Currently the ScalarCardLinkedTimeController only has logic for fob placement. Therefore the only functional change here is that the fob will now be centered properly(this resolves #5656 )
The goal is to eventually implement all the necessary logic to add the fob dragging feature in the Scalar Card. Currently pointer events are set to none(this is done [here](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/components/vz_line_chart2/vz-line-chart2.ts;l=572)) so clicking and dragging does nothing. Once the logic for dragging is added that will be turned on.
> linked time: utilize ScalarCardLinkedTimeFobController in the ScalarCardComponent

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
* Motivation
In image card, when there is no data on selected step, we automatically move the thumb position to the closest step. We don't want to confused user to think about the data exist on this selected step so we add an icon indicator on the top of the card to show user something is happening.
* Technical context
Previously we moved the logics of adjusting index to reducer to avoid "flashing"(#5615). Thus there is no way in view level to know whether the step index has been adjusted or not. For example, for steps [10,20,30], we only want to show the indicator when selected step is 11 but not 10. But both of them set the cardStepIndex to 0 (step 10).
As a result, to solve this we need to have a variable remember whether the step index has been "auto adjusted" in the reducer level. …
> linked time: displays indicator when thumb is moved to closest step

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
In order to allow the LinkedTimeFobController to implement dragging it must be able to dispatch the timeSelectionChanged action. This pulls that action into the ScalarCardContainer and passes it down to give the controller access.
> linked time: Wire up timeSelectionChange action

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
We decided to rename this parameter in a similar location in PR #5665. So I am doing it here for consistency.
> linked time: Rename parameter to indicate newness

- tensorboard/defs/BUILD
updates `nodejs_binary` build rule to specify flag `templated_args = ["--nobazel_run_linker"],`.
This is to fix the build in environments without `--worker_sandboxing`, such as in the machine which pushes `tensorboard-nightly`.
Tested:
*  With this change the bazel build in our CI machine works both at head and at `9fbcf8255`, the first change that exhibits consistent breakage.
(Explanation courtesy of @devversion)
"""
A little context: The Bazel NodeJS rules rely on a linker tool for emulating/creating a `node_modules` directory in the execroot (for build actions). Previously, in older versions of the Bazel NodeJS rules the NodeJS module resolution got patched to support runfiles.
This linker concept/the creation of the `node_modules` directory in the execroot is *very* brittle for …
> Disable Bazel node modules linker.

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
- tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
When there is no selected step on histogram card in single selection, it's easy to get confused (no color). We want to highlight the closest step with data on this case.
Summary: update `this.selectedTime$` in `histogram_card_container.ts`
On histogram, to determine whether this card is "clipped" we have created "ViewSelectedTime" type and make the decision in histogram_container. Similarly, we adjust the step (to be specific, `startStep`) of `selectedTime` to the closest step accordingly. This makes sense to me because "selectedTime" is type "ViewSelectedTime". This type is to use in view only. 
Also all these changes are in view.  We don't change the LinkedTime-type state. Adjust the step here, and propagates it to …
> linked time: highlight the closest step in histogram

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.scss
This is the final change needed to implement a feature which allows users to drag the linked time fob on Scalar Cards as a way to alter the selectedTime.
We have decided to consider scalar charts as continuous. This means that we assume there is a step at any point along the chart. Therefore we return the step that is directly at the mouse position. This is different from the histogram which jumps to steps with data. This means that getStepHigherThanAxisPosition and getStepLowerThanAxisPosition will return the same thing.
https://user-images.githubusercontent.com/8672809/163608806-8721a20d-37b8-4924-a151-a578c70a1111.mp4
> Implement Scalar Dragging

- tensorboard/webapp/customization/customizable_component.ts
Googlers, see cl/443089340 for an example of usage.
As part of effort to enabel strict Angular template checking in our internal code base, I need to make an adjustment to CustomizableComponent's @Input type. It is now typed as Type\<Component\> - this is what the callers are all actually passing, so it is strictly a better type.
We still cast the constructor to Type\<unknown\> when passing it to the underlying ComponentFactoryResolver to satisfy the TypeScript compiler.
> Adjusts Input type for CustomizableComponent for better template type checking.

- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
After hitting refresh button on the top right, the order of pinned cards is different from the pin sequence. (It becomes the order of cards, sorted by the tag name). This PR fixes the bug. (TODO: add webtest)
The order of pinned cards is based on the insertion order of `cardToPinnedCopy` Map ([code](https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/metrics/store/metrics_selectors.ts;l=231?q=%5C%5B.*%5C.values%5C(%5C)%5C%5D&ss=tensorflow%2Ftensorboard), [Map mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values)). However when hitting refresh button we reload the tag metadata, which generates the next `cardToPinnedCopy` Map in …
> time namespaced: fix pinned card order

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
When fixing a previous bug where pinned cards disappear after hitting reload button (#5663), I also assign "" for `stateRehydratedFromUrl` action. Yet the assignment for `metricsTagMetadataLoaded` action was incorrect, which make `cardToPinnedCopyCache` identical to `cardToPinnedCopy`, which makes the initial purpose (#5627) not working.
This PR removes the assignment.
The unit tests are "unpins a pinned copy", which we _should_ update `cardToPinnedCopyCache` and "updates pinned/original cards mapping on pinned cards removal" which we should _not_ update `cardToPinnedCopyCache` but `cardToPinnedCopy`
TODO: add webtests after sync (actually, this bug was caught in the process of adding the tests)
> time namespaced: fix preserving pinned card of previous experiments 

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
Show indicator when we highlight the closest step in histogram card. Yet we don't want to show it if the card is clipped (only show the clipped value).
With reusing of "vis-selected-time-warning" module we only need to pass down "isClosestStepHighlighted" from container, which is based on the "viewSelectedTime". Previously we adjust start step to be closest step if no data on selected step. We only need to check if the start step is different from getMetricsSelectedTime value.
selected step=36, closest step=35
card is clipped
What is _not_ included in this PR: 
rename of "selectedTime" in `histogram_card_component`
> linked time: add indicator on highlighting the closest step for histogram

- .github/workflows/ci.yml
Bazel build CI is getting clogged with many warnings of the form:
`external/com_google_protobuf/python: warning: directory does not exist.`
The correct fix for this is to incorporate a version of proto which includes https://github.com/protocolbuffers/protobuf/issues/6049.   In the meantime, this kludge will make it easier to debug genuine issues.
Googlers: see b/222706811
> Suppress external/com_google_protobuf warning in CI.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/linked_time_fob/BUILD
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.scss
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_module.ts
This changes adds the button for deselecting a fob. That button currently does not work(feature is currently behind a flag so a useless button is ok). Logic will be added later to remove the fob when clicked.
These changes are all for style. I tried my best to make it look as I would expect a delete button to look. 
The button looks like this:
When the mouse is hovering over the button it looks like this(screenshot did not show mouse):
> linked time: add deselect button

- tensorboard/compat/proto/attr_value.proto
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/coordination_config.proto
- tensorboard/compat/proto/full_type.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/trackable_object_graph.proto
Preparing for 2.9 release
```
$ cd ~/tensorflow
$ git fetch origin --tags
$ git checkout tags/v2.9.0-rc1
$ cd ~/tensorboard
$ ./tensorboard/compat/proto/update.sh ~/tensorflow
```
Ran tests & verified the server runs & spot checked a logdir.
> Update protos to match 2.9rc1

- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
This is part of a chain of PRs([the first PR](https://github.com/tensorflow/tensorboard/pull/5681) in this change added the button) that is intended to implement a feature to deselect the fob for the linked time feature. This change adds the logic which decides what to do when the button is clicked. Since there could be 1 or 2 fobs at any point there needs to be logic that handles each situation.
When in range selection(which means we have a start and an end fob) deselecting a fob will leave the remaining fob in place. This means we switch to single selection. If the end fob is deselected we simply remove it. However, if the start fob is deselected we must change the end fob to the start fob before removing the end …
> linked time: Implement fob deselect logic

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
This PR finishes the deselect fob feature. When in single selection(only 1 fob) deselecting the fob toggles the entire selected time. The logic for when this happens was added in [my previous pr](https://github.com/tensorflow/tensorboard/pull/5685). However it emitted an event that was not linked to anything. This PR gets the correct action from the ScalarCardContainer and the HistogramCardContainer and passes it as an event all the way down to the LinkedTimeFobControllerComponent.
This change is pretty straight forward. The tests however had to be done differently for the ScalarCard and the HistogramCard. In the ScalarCardTest file we are able to do a full integration test all the way down to the …
> linked time: Wire up onSelectTimeEnableToggle action for deselecting fob

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.scss
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_test.ts
Previously we can edit the step within the fob with the help of adding an input element. The actions were double clicking the div and then click to focus the input. This PR refactor removes input and directly use contenteditable in span element, which allows user to click the number and edit it right away.
In `linked_time_fob_component.ng.html`, input element is removed; add `contenteditable ` attribute to span element. 
Since editing the content makes `{{ step | number}}` rendering buggy. (It will not render anything once it's cleared). We change it to set innerHtml once step input changed in `ngOnChanges`
Naming changes: 
removeStep --> fobRemoved; stepChange --> stepChanged
before
after …
> linked time: refactor fob step editing with contenteditable

- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ts
When dragging the fob, we want the number in the fob to reflect the step change. With the change of contenteditable, we need to change the html of the span element. Previously we grab the element and change ".innerText" directly. I didn't check and do any kind of sanitization at all. That was a mistake.
Angular has its way of making sure the html is safe with "[innerHtml]" attribute, which use Angular’s [DomSanitizer](https://angular.io/api/platform-browser/DomSanitizer). We can directly use this attribute to set the (updated) step.
Googlers, please see sync check 
before: [link](https://fusion2.corp.google.com/invocations/07040fed-a465-4b63-82f7-becf95a779e5/targets/%2F%2Fthird_party%2Ftensorboard%2Fwebapp%2Fwidgets%2F …
> linked time: use 'safe' way of setting innerHTML

- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
This flips the default value of feature flag `enabledTimeNamespacedState` to `true`.
This has no practical impact on OSS or any other TensorBoard (this
feature is already turned on in places where it does matter). This will
allow us to begin removing old code for the old route-based namespace mechanism.
> timenamespaced state: Turns time namespaced state on by default.

- tensorboard/plugins/histogram/summary_v2.py
Currently it is not mentioned anywhere in the API documentation that the number of histogram buckets defaults to 30 if not set: https://www.tensorflow.org/api_docs/python/tf/summary/histogram
#tf_summary_v2 #histogram
> docs: clarify the default number of histogram buckets in summary API doc

- tensorboard/default.py
The "Time Series" dashboard is a unified view of scalars, histograms, and images data. It has been available for some time but is generally the last dashboard listed in the TensorBoard header. After quite a bit of work improving it and using it internally at Google, we've decided it is time to elevate it to be the first dashboard.
Please find more information or feel free to leave feedback at https://github.com/tensorflow/tensorboard/issues/5704.
> Time Series: Elevate "Time Series" dashboard to first dashboard.

- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.scss
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
We want to make the dash line in scalar also draggable to update the linked time as the current fob (gray oval) does. 
This PR adds an element to `linked_time_fob_controller_component`. Name it as "extended-line" to potentially make it both vertical and horizontal. (For now we only needs vertical line and we don't really have any css for horizontal line)
Default
Hover 
TODO: add dragging tests; since the line position is same as the fob, now the position in test will be exactly the same as previous test cases
> linked time: adds extended-line element to fob component

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.scss
- tensorboard/webapp/widgets/histogram/histogram_linked_time_fob_test.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.scss
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
Remove "axis-overlay" from linked_time_fob_controller and make scalars and histograms both responsible for properly positioning the linked_time_fob_controller in the page layout.
The histograms card was relying on axis-overlay to properly position the linked_time_fob_controller rather than doing itself. Scalars card, however, was already properly positioning the linked_time_fob_controller itself. Since axis-overlay was becomign a small maintenance burden we just remove it and change histograms to behave more like scalars in this response.
The changes have no practical impact on the feature but it does require some adjustments in test.
Googlers, see cl/448303779 for results of internal sync.
> linked time: Remove axis-overlay from linked_time_fob_controller.

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
We have created an extended line in fob. The line is draggable to change the selected time as our fob. This PR turns on the line rendering for scalar card and applies some css changes.
* Moves `scalar-card-linked-time-fob-controller` out of x-axis component and makes it cover the space of "series view + x-axis".
* The "out-of-selected-time" component inside line-chart "interactive-utils" is to just for the visual effects. We keep it for fade-out like effect on range selection with only remove the border style (which now replaced by the extended line in fob controller)
https://user-images.githubusercontent.com/1131010/168173413-787c9a07-eda1-4772-a520-13a3aeb9e482.mov
TODO: updates webtest …
> linked time: reconstruct scalar html for fob extended line

- .github/workflows/ci.yml
`tf-nightly==2.10.0.dev20220514` broken TensorBoard CI, pin to the latest working version,  `tf-nightly==2.10.0.dev20220427`
CI Log https://github.com/tensorflow/tensorboard/runs/6434770729?check_suite_focus=true
Googlers please see bug report b/232717508
> ci: pin tf-nightly to 20220427

- .github/workflows/ci.yml
Unpin tf-nightly as it is fixed in version `2.10.0.dev20220518`. Revert #5709
Googlers, please see b/232717508 and rollback cl cl/449359447
> ci: unpin tf-nightly from 20220427

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/internal_utils_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We have migrated all TensorBoards from route-namespaced state to time-namespaced state.
This PR removes the enabledTimeNamespacedState feature flag and removes any remaining route-namespaced-specific logic.
Googlers, see cl/449305283 for a clean copybara import.
> time-namespaced state: Remove timeNamespacedStateEnabled flag.

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_module.ts
This is the first change towards adding a dedicated table to hold the data for a selected time in the Scalar Card. This change simply adds the basic structure of the DataTable widget which will be a component which displays the data passed to it. For more context on where this is headed see https://github.com/tensorflow/tensorboard/pull/5719. 
This just adds the structure to stand up a widget which will be implemented in later CLs.
This PR makes no UI changes but we eventually plan to add a table that will probably look something like this:
The look of that table is still subject to change.
* Alternate designs / …
> Add DataTable Basic structure

- tensorboard/webapp/BUILD
- tensorboard/webapp/angular/BUILD
- tensorboard/webapp/feature_flag/BUILD
- tensorboard/webapp/feature_flag/feature_flag_module.ts
- tensorboard/webapp/feature_flag/http/BUILD
- tensorboard/webapp/feature_flag/http/feature_flag_http_interceptor.ts
- tensorboard/webapp/feature_flag/http/feature_flag_http_interceptor_test.ts
This adds a mechanism that dumps the client-side FeatureFlag object into each HTTP request that originates from the TB Angular code base.
(Googlers, see: http://go/tb-client-feature-flags-in-data-provider for the motivation and high level design.)
The data is dumpted into a custom header. The format is effectively:
`X-TensorBoard-Feature-Flags: JSON.stringify(currentFeatureFlags)`
We implement this by introducing an HttpInterceptor. It allows us to intercept each request in the Angular HTTP pipeline and inject the new header. The HttpInterceptor is provided in the existing FeatureFlagModule so all instances of TensorBoard will receive this behavior without any additional configuration.
Additional things worth noting:
* This will send ALL feature flags in the request header rather than a …
> Adds mechanism to include feature flags in Angular HTTP requests.

- .github/workflows/ci.yml
Reverts https://github.com/tensorflow/tensorboard/pull/5722.
#onduty #ci
> ci: unpin tf-nightly from 20220521

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/client_feature_flags.py
- tensorboard/backend/client_feature_flags_test.py
- tensorboard/context.py
- tensorboard/context_test.py
Add a client_feature_flags property to the DataProvider's RequestContext object. Also add a middleware that extracts the feature flags from the HTTP request and sets them on the RequestContext.
client_feature_flags represents feature flags set in the TB webapp client. They will be injected into many HTTP requests originating from the webapp and will be of the form:
X-TensorBoard-Feature-Flags: JSON.stringify(currentFeatureFlags)
We expose these values as a Dict in the RequestContext object, with string keys and values of arbitrary types (but, in practice, mostly booleans and sometimes arrays of strings). Usage of client_feature_flags should be aware of the key names and the value types.
(Googlers, see: http://go/tb-client-feature-flags-in-data-provider for motivation, more details, and …
> Adds client_feature_flags to DataProvider's RequestContext.

- tensorboard/backend/client_feature_flags.py
- tensorboard/backend/client_feature_flags_test.py
In https://github.com/tensorflow/tensorboard/pull/5721 we added ClientFeatureFlagsMiddleware. It decodes the feature flag payload from JSON into a dict.
Reviewer suggested we validate that the decoded result is indeed a dict and I claimed that this was not a valid scenario to worry about. I realized not long afterwards that I was wrong.
> Validate that decoded client_feature_flags is a dict.

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
This adds a feature flag to allow for development of the Data Table behind this flag that is not seen by regular users. This will also allow us to launch the Data Table as a standalone feature.
This PR makes no UI changes. However to help give context to the Data Table feature here is a screen shot of what the feature may look like:
I just tested this with console logs.
> data table: Add data table feature flag

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
While renamign the linked time fob to be card fob (https://github.com/tensorflow/tensorboard/pull/5732), a scss file was overlooked. This PR rename `scalar_card_linked_time_fob_controller.scss` to `scalar_card_fob_controller.scss`.
Googlers, please see cl/438908607 for webtest
Before
After
> linked time: decouple fob from linked time: fix scalar scss file rename

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This is part of the work to separate the "sticky data table" (aka step selector) to its own feature. This PR adds the checkbox to enable/disable step selector. The checkbox is hided behind feature flag (enableScalarDataTable).
Add visual component to settings panel and wiring toggle action. (no dispatch action yet)
TODO: add ngrx state to control enabling time selector and plump them together
TODO: consider renaming feature flag
> step selector: add control to settings panel behind feature flag

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This is part of the work to wiring the "sticky data table" (aka step selector) to its own feature. Following up #5734, we create the ngrx state and toggle to change the state status, which will be used to turn on/off the feature.
> step selector: add step selector toggle state and action

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_component.ts
This is one pr in a chain intended to add a data table feature. This change adds data types and gathers the data needed for the table. For more context on where this is headed see https://github.com/tensorflow/tensorboard/pull/5743
The ScalarCard now decides which columns we will have on the table(currently this is hard coded but, we plan to allow for the user to select which columns they want so this is built with that in mind). It also uses the selectedTime to decide which points of data will be displayed.  Eventually we will replace selected time with a more narrow step selection that is specific for that card. 
This PR makes no UI changes but, for reference we are aiming to make a table …
> step selector: gather data for data table

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
Recently the test core_plugin_test.py::test_js_cache began to fail in some environments with the following error:
```
... core_plugin_test.py", line 196, in test_js_cache
self.assertEqual(
AssertionError: 
- private, max-age=86400
+ no-cache, must-revalidate
```
The root cause is that these systems have now been configured to return 'text/javascript' as the mimetype for js files, where they were previously returning 'application/javascript'. This means the 'Cache-Control' header was not set by this line:
https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/core/core_plugin.py;l=137;drc=c061b659f50cde9dd9da5aa906ecb682ecdc68d4
```
expires = (
JS_CACHE_EXPIRATION_IN_SECS
if request.args.get("_file_hash")
and mimetype == "application/javascript"
else 0
)
```
After …
> Recognize text/javascript as valid js mimetype for caching purposes

- RELEASE.md
- tensorboard/pip_package/requirements.txt
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/version.py
Cherrypicks:
* 174d8a6d35d Force protobuf dependency < 3.20.
* 28201b437ef Recognize text/javascript as valid js mimetype for caching purposes
> TensorBoard 2.9.1

- tensorboard/backend/http_util.py
- tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
- tensorboard/program.py
While investigating the test failure that lead to #5746, we realized that RFC 9239 (https://www.rfc-editor.org/rfc/rfc9239) has changed the preferred js mimetype to 'text/javascript' from 'application/javascript'.
To be a good citizen of the internet, this change modifies the logic introduced in #3128 to force the mapping of js files to mimetype 'text/javascript'. We must also modify http_util.py to ensure that the proper charset is included in the Content-Type header. And, finally, we modify the example plugin to use 'text/javascript' as mimetype.
To Test:
* I ran local tensorboard and used the chrome developer tools to verify that the Content-Type for js files fetched by the browser was 'text/javascript; charset=utf-8'.  I did a basic sanity test ensuring both Angular and Polymer …
> Change mimetype mapping of js files to 'text/javascript'.

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
This is part of the work to disconnect fob from linked time. When linked time is disabled, we want to updates the fob location (and corresponding data table) for this scalar card only. This PR adds a new attribute "internalSelectedTime" which exists in component only.
* We build "internalSelectedTime" inside scalar card. The initial value comes from the min step in this card.
* We only dispatch timeSelectionChanged when "LinkedTime" is enabled. Whether linkedTime is enabled based on selectedTime inside scalar_card_component, aka `selectedTime===null` if linkedTime is not enabled.
* Remove feature flag `isDataTableEnabled` and eventually replace with "internalSelectedTime" (The current data table still using …
> step selector: add internalSelectedTime to scalar card

- tensorboard/data/server/DEVELOPMENT.md
Update instructions about how to update Rust dependencies, based on my experiences with https://github.com/tensorflow/tensorboard/pull/5755.
Notably:
* Recommend using `cargo update -p <dependency name>` instead of `cargo fetch` when updating an existing dependency. `cargo fetch` will work when updating a dependency to a new major release but will not work when updating a dependency to a new minor release.
* Recommend updating crate-specific metadata versions in `Cargo.toml` based on the update to crate versions in `Cargo.lock`. Do this before running `cargo raze` to avoid unnecessary confusion.
* The targets to test are actually in `//tensorboard/data/server/cargo`. There do not appear to be valid targets in `//third_party/rust`.
* Run `bazel test …
> Add instructions on how to update Rustboard dependencies.

- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Fixing the following error when running internally:
```
error TS2345: Argument of type 'Element | null' is not assignable to parameter of type 'Element'.
Type 'null' is not assignable to type 'Element'.
```
Also fixed tslint (redundant type annotation).
#refactor
> fix argument type error and tslint

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Currently the data table with selected step data when step (i.e.,`<tb-data-table>`) is rendered only when linkedTime is enabled (aka `selectTime!==null`). We want to render the table when step selector is enabled.
This PR adds OR condition on `<tb-data-table>` rendering and the selected step fallback to `internalSelectedTime` if `selectTime` is null. 
`<tb-data-table>` is rendered when "Step Selector" is enabled but "Link visualization" is disabled
> step selector: renders data table element on feature enabled

- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Wait 100ms before repinning the card and checking the indicator, to avoid the following flakiness:
```
Chrome Headless 84.0.4147.0 (Linux x86_64) metrics main view pinned view new pinned indicator shows the indicator when the same card gets pinned toggled FAILED
Error: Expected <span _ngcontent-a-c329 class="new-card-pinned" data-id="1000">...</span> not to be <span _ngcontent-a-c329 class="new-card-pinned" data-id="1000">...</span>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
at <Jasmine>
at UserContext.<anonymous> (tensorboard/webapp/metrics/views/main_view/main_view_test.ts:1690:56 <- org_tensorflow_tensorboard/tensorboard/webapp/metrics/views/main_view/main_view_test.js:1228:68)
at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-testing-bundle.js:407:30)
at …
```
> fix flaky test

- tensorboard/webapp/feature_flag/http/BUILD
Change `tensorboard/webapp/feature_flag/http:const` target to use `tf_ts_library` instead of `tf_ng_module`. const.ts does not have any dependency on Angular so using `tf_ng_module` was unnecessary and created a transitive dependency from our polymer codebase to Angular, which we don't like (this was caught by internal tests).
> Remove transitive dep from tensorboard polymer on Angular.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
To cope with launch phases we only apply single selection to step selector for now. Therefore when dragging fob to new selected time, we update start step and sets end to null. This prevents having two fobs after linked time launch, which enables users to set range selection. The type of internalSelectedTime is still LinkedTime, which reserves future extension to range selection of step selector.
On fob changed, we set the start step instead of LinkedTime object.
https://user-images.githubusercontent.com/1131010/172928846-f19ab1e5-0582-4526-8a57-e80a4ba7f43b.mov
> step selector: updates selected time to single selection only

- .github/workflows/ci.yml
The `setup-node` GH Action currently specifies `version` (which has been
deprecated since October 1, 2019) instead of `node-version`.
Current action output:
After this change:
> Remediate setup-node GH Action warning

- package.json
- yarn.lock
Removes the unused dependency on the npm package @angular/bazel.
The rules_nodejs documentation actually has recommended against its use:
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.0
`For most applications, we no longer recommend depending on the @angular/bazel package. The only rule needed from it was ng_module which you can replace with the faster equivalent ts_library(use_angular_plugin=True)`
We transitioned from ng_module to ts_library(use_angular_plugin=True) in https://github.com/tensorflow/tensorboard/pull/4376.
Steps to complete:
1. `yarn remove @angular/bazel`
2. Run the following commands: `bazel clean --expunge`, `rm -rf node_modules`, `yarn`
3. Build and run tensorboard and manually inspect it works.
4. Build and run tensorboard angular tests.
> deps: Remove unused @angular/bazel dependency.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
We have put a data table inside the scalar card but the table is squeezed in the original card space. We want to create extra height for the card when the table is rendered. Please see screenshots below 
There is a pre-defined class `height-with-table` which increase the min height from the original card height (320px) to 100px more. This is not perfect in many scenarios but good enough for now. Also I guess for those not-so-good-looking scenarios it does not happen often. (for example, histogram card and scalar card under the same tag and placed in the same row)
Before 
After 
Known css flaw:
1. All cards on the same row will have the same height. Therefore if step selector is enabled and …
> step selector: extends the height of scalar card when step selector is enabled

- .github/workflows/nightly-release.yml
Update the nightly release workflow to release to PyPI instead of
TestPyPI now that we've validated the functionality for a few days.
> Release tb-nightly to PyPI

- package.json
- yarn.lock
This PR introduces yarn-deduplicate as a dependency of ours and runs it.
Two motivating factors:
* More immediate: During an attempt to upgrade our Angular dependencies to the most recent Angular 12 patch release, the build was broken until manually eliminating duplicate `tslib` dependencies from the yarn.lock file.
* Longer term: It seems like good hygiene to try to remove unnecessary duplicate dependencies in our yarn.lock file and `yarn check` itself complains about these:
```
warning "@ngrx/effects#tslib@^2.0.0" could be deduped from "2.3.1" to "tslib@2.3.1"
warning "@ngrx/store#tslib@^2.0.0" could be deduped from "2.3.1" to "tslib@2.3.1"
warning "ngx-color-picker#tslib@^2.0.0" could be deduped from "2.3.1" to "tslib@2.3.1"
warning "plottable#@types/lodash@^4.14.109" could be deduped …
```
> deps: Install yarn-deduplicate and clean duplicate deps.

- tensorboard/webapp/widgets/data_table/BUILD
The file data_table_test.ts as added in https://github.com/tensorflow/tensorboard/pull/5767 uses `@angular/core/testing`, and for that import, we require this placeholder dep in order to sync properly internal to Google.
> step selector: add missing dep for @angular/core/testing

- .github/workflows/nightly-release.yml
Move the nightly build back two hours to ensure it's run before East
Coast working hours start.
> ci: Update nightly build time

- tensorboard/webapp/app_routing/store_only_utils.ts
- tensorboard/webapp/app_routing/store_only_utils_test.ts
`getCompareExperimentIdAliasWithNumberSpec` used to remove experiments with empty aliases from the map returned. This functionality was not being used anywhere and got in the way of detecting experiments with missing aliases.
None
I ran the app and didn't see any visible changes (or errors thrown in the console), the I ran the tests and they passed (after deleting two).
Create a new function doing the same thing as `getCompareExperimentIdAliasWithNumberSpec` but not removing experiments with empty aliases.
I could potentially have updated the deprecated function `getCompareExperimentIdAliasSpec` as well but …
> Stop removing empty aliases from experiment id to alias map

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
The behavior of deselect fob still connects to linked time behavior (update "selectTimeEnableToggled", which is for linked time). We want to make the fob disappear when we deselect it in step selector single selection. This PR checks whether linked time is enabled and fires `stepSelectorEnableToggled` or `selectTimeEnableToggled` actions accordingly.
1. fire `stepSelectorEnableToggled` action when linked time is not enabled. The "onSelectTimeToggle" is for linked time change selected time in ngrx state. When it's step selector, we do not have selected step in state (storing in each card level)
2. fix step selector checking bug: it's probably misunderstanding and misuse. `isScalarStepSelectorFeatureEnabled` is about …
> step selector: deselect fob in step selector

- WORKSPACE
- third_party/grpc.patch
- third_party/protobuf.patch
This PR allows TensorBoard to build and run with Python 3.10.
There are incompatibilities in the protobuf and grpc dependencies, which are quite old but we are unable to upgrade (see: #5561 , Googlers: http://b/219030239). We patch the necessary fixes from those projects into our older versions using the `patches` property of the `http_archive` rule.
For grpc we patch https://github.com/grpc/grpc/commit/dbe73c9004e483d24168c220cd589fe1824e72bc to avoid the following compile-time error:
```
Error in fail: Python Configuration Error: Problem getting python include path for /usr/local/google/home/bdubois/virtualenv/tensorboard/bin/python.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential …
```
> Patch protobuf and grpc dependencies to be Python 3.10 compatible.

- WORKSPACE
As noted in a comment for #5793, the instructions for generating grpc.patch would be more accurate if they referred to the commit that corresponds to the grpc archive instead of referring to the nearest tag. I've updated the instructions to refer to the commit.
I tested by following the updated instructions and copying grpc.patch to my tensorboard repo. git did not find a diff in the generated files.
> Make grpc.patch instructions more accurate.

- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
In future changes the Step Selector Checkbox will be part of a larger feature which encompasses more than just scalar cards. We wanted to keep the checkbox in the same location to not confuse users so we are moving it out of Scalar Settings into General Settings now.
> Step Selector: Move Step Selector to General section of Settings panel

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
This fixes a bug where the fob disappears when the user types in a step larger than the max step or smaller than the min step.
Googlers see: b/238666726
I added a lazy load of the min and max steps to avoid unnecessary calculations.
Considered moving this logic to the ScalarCardContainer but the changing of the value in the observable and emitting the change to all subscribers became a hacky mess so I kept this in the component.
> Do not update internalSelectedTime outside card range

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Previously when displaying the run column we display the run name. Yet when comparing multiple experiments we missed the alias number and text. This PR adds it to the table.
Extract alias info from metadata and combine with Run name. A space is added between alias number and text. We do have alias component, however introducing the component adds too much unnecessary complexity (the data_table widget needs to treat it "special" as color run and also customize the background color of alias number). I decide to no involve this component and just simply add alias as part of RUN column.
Before 
After
> step selector: add alias in run name if any

- package.json
- tensorboard/pip_package/setup.cfg
- tensorboard/webapp/metrics/actions/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_types.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_test.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- yarn.lock
Current we define a `CardFobController` and implements the methods at CardFobController level (e.g. `ScalarCardFobController`) and pass "this" to child component. However,  Angular will not detech the data changes within `ScalarCardFobController` (in our case, minMax and axisSize) because as far as it concerns, "this" does not change.
This causes the bug when minMax and axisSize are updated (changing window size, expand card group..) it does not cause card_fob_component to be re-rendered and the fob position is off.
To handle this, we need to modify the method `getAxisPositionFromStep` which transform step to position, to two separate methods, getAxisPositionFromStartStep and getAxisPositionFromEndStep, and execute …
> Step Selector: Fix fob position rendering bug and remove CardFobAdaptor

- .github/workflows/ci.yml
According to https://github.com/actions/virtual-environments/issues/5583, macos-10.15 is no longer supported and fails our ci flow. Upgrade t o macos-11.
> ci: update to macos 11

- tensorboard/webapp/widgets/histogram/BUILD
- tensorboard/webapp/widgets/histogram/formatter.ts
- tensorboard/webapp/widgets/histogram/formatter_test.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ts
Using SI notation for histogram bins smaller than 1 causes confusion.  '500m' can mean many things, not just '0.5'.  Googlers see b/238492397
Replaces tick formatter with a 3 way switch.  SI notation for small values, Exponential notation for large values, and natural notation for middle values.
before:  
----
after:
----
Ran TensorBoard standalone locally and compared across a very wide range of histogram bin bucket sizes.
It may be possible to update tensorboard/webapp/widgets/histogram/histogram_component.ts and re-use formatters from there.   Did not pursue as it would …
> Adds specialized formatter to histogram component.

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
For now we only emit actions on linked time time selection changes but not step selector changes. The reason is that only linked time changes update ngrx state. However, we need the action for step selector to perform internal analysis. This PR creates a new step selector time selection action and fires when linked time is disabled.
The most noticeable change is adding linkedTimeEnabled on scalar card container level. Previously we do not need this because we will update the linked time selection even it is not enabled. This does not make sense now. Linked time selection should not be updated when it is disabled. Please see below demo for flow details.
* Demo
Updates linked time also updates step selector (within the …
> Step Selector: add step selector selection change action

- tensorboard/webapp/widgets/data_table/data_table_component.ts
The number formatter being used to format the step number was converting it to scientific notation. This changes the formatter to the same one being used int he tooltip which will simply add commas.
googlers see b/238666738
> Step Selector: Use intlNumberFormatter for step formatting

- tensorboard/webapp/routes/dashboard_deeplink_provider.ts
- tensorboard/webapp/routes/feature_flag_serializer.ts
- tensorboard/webapp/routes/feature_flag_serializer_test.ts
Apparently TBCorp has different (and sometimes conflicting) lint rules so `feature_flag_serializer_test` was unable to be imported.
While "updating" the typing there I also cleaned up some of the typing in the related files.
#5717
> Bug Fix: Updating typing surrounding `feature_flag_serializer_test.ts`

- tensorboard/webapp/app_routing/effects/app_routing_effects.ts
- tensorboard/webapp/app_routing/programmatical_navigation_types.ts
Programatic routing should be able to amend the route rather than redirect the user. This comes up in situations like updating route params.
> Feature: Add route specific configuration for replaceState

- tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
We always override the value of `forceSvg` regardless of whether a value is set in localStorage. This is an existing bug that is only coming to light now that we persist feature flags to the queryParams.
#5717 
1) Clear localStorage
2) Visit tensorboard and note that the `forceSVG` query parameter is not set.
> Bug Fix: Only override forceSvg from localStorage when the key is present

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
Googlers, see b/240338417 "Clicking the refresh UI button unpins pinned graphs".
When a user loads a TensorBoard with pinned cards in the URL then clicks on the TensorBoard reload button, the  pinned cards disappear!
Explanation:
* Soon after page load, when handing tag metadata, unresolved pins are resolved into actual pinned cards. Unfortunately, the cardToPinnedCopyCache property is not provided with the information:
* https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/metrics/store/metrics_reducers.ts;l=565;drc=2f5661647c264a3cd5758a04a7de0beb0c604747
* When user then presses the TensorBoard reload button and then tag metadata is reloaded, the cache is considered empty and the actual set of pinned cards is also cleared:
* …
> Update cardToPinnedCopyCache when resolving unresolved pins.

- tensorboard/webapp/app_routing/programmatical_navigation_types.ts
Followup to https://github.com/tensorflow/tensorboard/pull/5832, rearrange the replaceState property in NavigateToCompare and NavigateToExperiments to keep its place consistent.
> Rearrange NavigateToCompare, NavigateToExperiments for consistency.

- tensorboard/webapp/routes/BUILD
- tensorboard/webapp/routes/dashboard_deeplink_provider.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
- tensorboard/webapp/routes/index.ts
This would make it easier to extend the set of feature flags in TBcorp.
Go to tensorboard with a feature flag overridden by a query parameter.
Assert that the query parameter is not removed.
While changes to TBcorp would be possible without this (by extending and then deduplicating query parameters) this would be much cleaner.
> Update `DashboardDeeplinkProvider` to get feature flag metadata dynamically

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_metadata_test.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
- tensorboard/webapp/routes/feature_flag_serializer.ts
- tensorboard/webapp/routes/feature_flag_serializer_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
When we introduced `FeatureFlagMetadata` in https://github.com/tensorflow/tensorboard/pull/5717, we included the`isArray' property, which allowed us to support feature flags that (1) have array type and (2) can be overriden with query parameters. There is only a single feature flag that satisfies this - enabledExperimentalPlugins/experimentalPlugin.
The isArray support adds complexity to the feature flag framework - parsing and encoding logic need special handling for array types in addition to basic types. I wondered if we could eliminate the complexity from the feature flag framework and instead isolate the array-handling to a narrower scope.
The idea: We can simplify the `experimentalPlugin` query parameter and then simplify FeatureFlagMetadata and the surrounding infrastructure.
We …
> Simplify how experimentalPlugin query param works so we can simplify the feature flag infrastructure.

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
The reset button for "Card Width" does not effectively reset the property. Pressing it resets it to the value that it was set to when the page was loaded. (So, for example, if the value is 535px on page load, pressing reset will reset it to 535px and not reset the property entirely).
The reasoning is:
* Pressing the reset button will remove the property from state, effectively making it undefined:
* https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/metrics/store/metrics_reducers.ts;l=709;drc=2059b53ef0f6875dbaa8bca4362653c07d0069fd
* The PersistentSettingsDataSource does not update the field in local storage if the value is undefined:
* https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/persistent_settings/_data_source/persistent_s …
> Fix "Card Width" property reset button.

- tensorboard/plugins/graph/tf_graph_common/contextmenu.ts
Its usage could lead to XSS and it's not compatible with Trusted Types.
> Replace d3.selection.html with .text.

- tensorboard/plugins/metrics/metrics_plugin_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text_v2/text_v2_plugin.py
Fix tests to be compatible with numpy>=1.23.0 and python>=3.9.0.
It's possible nobody has run these tests locally in a while because I have numpy 1.23.1 and python 3.10.5 installed on my machine and these tests failed for me.
Note that the numpy changes, specifically, were originally proposed internall in cl/465149745, which states:
> NumPy 1.23 removes support for non-tuple indexing of NumPy arrays ([https://numpy.org/devdocs/release/1.23.0-notes.html#expired-deprecations](https://www.google.com/url?sa=D&q=https%3A%2F%2Fnumpy.org%2Fdevdocs%2Frelease%2F1.23.0-notes.html%23expired-deprecations)). The workaround is to convert multidimensional indices to a tuple.
Python 3.9.0 removes collections.Callable. We should now use collections.abc.Callable.
> Fix tests to be compatible with numpy>=1.23.0 and python>=3.9.0.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
This change adds the "Smoothed" column to the data table which we expect users to want. It also helps align the data table more closely with the tooltip.
Since this column is more dynamic and should only appear when smoothing is enabled I moved the dataHeaders construction to the container where I made it dependent on the smoothingEnabled$ Observable.
> Step Selector: Add smoothed column in data table when enabled

- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
We recently added the ability to double click a run checkbox to select it only and deselect the other runs.
User feedback (googlers, see b/238365158#comment9) said it was not discoverable. 
This change adds a tooltip to the checkbox, which includes a hint about double click.
I use "title" instead of "matTooltip" just because we have many icon buttons that also use this and the behavior is more consistent with those buttons.
> Add tooltip to run selection to hint about double click.

- tensorboard/plugins/metrics/metrics_plugin.py
I noticed that for TensorBoards with only image events that the Time Series dashboard does not appear.
I suspect this was just an oversight when Images were added to the Time Series dashboard. There is a function in the Metrics (aka "Time Series") plugin, `data_plugin_names()` which lists all data types for which the plugin should be enabled. It currently lists scalars and histograms but does not list images. This change just adds images to that list.
> Enable Time Series dashboard when only image events are available.

- tensorboard/plugins/metrics/metrics_plugin.py
Cherry-picks the fix in #5852.
> 🍒: Cherry-pick fix that elevates Time Series dashboard for image only events to 2.10 branch

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_test.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
Some strange behavior was observed when trying to drag the step selector. The root cause of this behavior was that when clicking and dragging in certain places the mouse was triggering other events(such as trying to move an entire graphic or highlighting text. This PR stops the propagation of those mouse clicks so that only the dragging that we want to occur occurs.
Googlers see b/241921321
> Stop event propagation when starting to drag step selector

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_metadata_test.ts
- tensorboard/webapp/routes/feature_flag_serializer.ts
In the newly-added FeatureFlagMetadataMap, we are specifying parseValue functions for a number of feature flags that don't need them.
This change improves the typing of FeatureFlagMetadata so we only specify parseValue functions when they are required - that is, when the metadata includes a queryParamOverride value.
This makes the type a bit more strict. This allows us to get rid of the parseBooleanOrNull parser.
> Improve FeatureFlagMetadata type so parse only specified when required.

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/routes/feature_flag_serializer.ts
In TBcorp and TBdev it is useful to build feature flag metadata maps based on unions of types. This typing was unnecessarily restrictive and prevented the creation of clean unions.
Make some ugly type casts in internal code?
> Update generics in feature_flag_metadata and feature_flag_serializer

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
In settings panel we want to move "linked time" to be nested into our "step selector". These two features are related: using linked time means step selector is used. (while turning on step selector does not mean linked time is turned on too)
This PR purely moves them together visually. The toggling connection will come afterward.
* step selector has been launched so the feature flag is set to true in testing
* This PR also includes some right_panel test cleanup and refactoring, remove unused `selectors.getMetricsLinkedTimeRangeEnabled`.
Inactive when xAxis is not step
> linked time: move "link step" into step selector in settings panel

- tensorboard/plugins/scalar/scalars_demo.py
Resets the default writer every time before writing scalar summaries, to fix the error: https://github.com/tensorflow/tensorflow/issues/25707#issuecomment-1212190906
```
Node: 'temperature/current/write_summary'
Resource localhost/_AnonymousVar0/N10tensorflow22SummaryWriterInterfaceE does not exist.
[[{{node temperature/current/write_summary}}]] [Op:__inference_one_step_62]
```
Googlers, see b/239742608.
Tested locally:
Also tested generating demo data internally in cl/466983681.
#onduty
> scalar: fix scalar_demos

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
"Linked time" is considered a subset of "step selector". We want to 
1. Enable "Enable step selection and ..." while "Link by step" is toggled to enable
2. Disable "Link by step" when "Enable step selection and ..." is disabled
Please see demo video below
Add extra handling on reducer for this two toggle actions. The reason is that we do not want to fire multiple actions on one  user toggle behavior.
https://user-images.githubusercontent.com/1131010/184249196-ff3bc223-8d98-4011-8075-4ea78396503a.mov
> linked time: toggle relations between step selector and linked time

- tensorboard/plugins/core/core_plugin.py
Found a typo error, so sending this PR
(historgrams -> histograms)
> fix typo in tensorboard/plugins/core/core_plugin.py

- tensorboard/webapp/feature_flag/BUILD
- tensorboard/webapp/feature_flag/store/BUILD
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/store/feature_flag_types.ts
- tensorboard/webapp/feature_flag/store/testing.ts
- tensorboard/webapp/feature_flag/testing.ts
Add `metadata?: FeatureFlagMetadataMapType` field to FeatureFlagState and populate it in OSS TensorBoard.
We have use cases for accessing the Metadata through NgRx state and this is the first step to safely integrating that metadata into state for all TensorBoard instances, internal and external.
The optionality of the field will be removed when internal TensorBoards are updated to also populate the metadata field.
> Add optional `metadata` field to FeatureFlagState.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
When we launch linked time we will be allowing a range selection. The data table needs to be able to handle range values when in that mode. This change adds the Start Step and End Step columns so the user knows which step is selected for each run.
> Linked Time: Add Start and End Step values to data table

- tensorboard/webapp/widgets/data_table/data_table_component.scss
When scrolling through the data table it will be useful to continue seeing the headers. Also we plan to use these headers and controls for sorting. 
Just a css change.
https://user-images.githubusercontent.com/8672809/184069538-238f1f35-bf7f-4a69-99bc-471746d0028f.mp4
> Linked Time: Stick the data table headers

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
When we launch linked time we will be allowing a range selection. The data table needs to be able to handle range values when in that mode. This change adds the Start Value and End Value columns so the user knows which step is selected for each run. 
> linked time: add start and end value column to data table

- .github/workflows/ci.yml
- tensorboard/data/server/pip_package/setup.py
- tensorboard/pip_package/setup.py
Python 3.6 is well past its [EOL](https://peps.python.org/pep-0494/#lifespan), so we should require 3.7+.
Contributes to #5725
> build: explicitly require Python 3.7+

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_types.ts
- tensorboard/webapp/routes/BUILD
- tensorboard/webapp/routes/dashboard_deeplink_provider.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
- tensorboard/webapp/routes/index.ts
We can now consume metadata field from FeatureFlagState. In #5876 we added the metadata field to FeatureFlagState optional and are in the process of updating internal Google code to specify this field universally (Googlers, see cl/467745607).
We update DashboardDeeplinkProvider to use metadata from FeatureFlagState instead of via constructor. The constructor argument is left optional for the time being, until we can update internal code to remove usage.
We also make the metadata field mandatory now that it is specified universally.
> Use FeatureFlagMetadata from state in DeepLinkProviders.

- tensorboard/webapp/widgets/card_fob/card_fob_component.scss
The dismiss button for the linked time fob was off center when the chrome font size was greater than medium.
The reason it was off center was because the size of the container was hard coded to 11px and the font size property was not set.
Before
After
1) go to Chrome settings(chrome://settings/)
2) select appearance on the left side menu
3) Change the "Font size" option to "large"
4) open tensorboard at http://localhost:6006/?enableLinkedTime=true&enableDataTable=true#timeseries
5) observe the fob
Allow the size of the fob to expand along with browser font size by replacing …
> Bug Fix: Fix centering of linked time fob dismiss button

- tensorboard/components/tf_backend/requestManager.ts
- tensorboard/components/tf_feature_flags/feature-flags-test.ts
- tensorboard/components/tf_feature_flags/feature-flags.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
- tensorboard/webapp/feature_flag/http/BUILD
- tensorboard/webapp/feature_flag/http/feature_flag_http_interceptor.ts
- tensorboard/webapp/feature_flag/http/feature_flag_http_interceptor_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/tb_polymer_interop_types.ts
In all requests from the TensorBoard application to the HTTP server we currently populate the "X-TensorBoard-Feature-Flags" header with the entire set of feature flags and values. We decided we only want to send the set of feature flags that are relevant to the HTTP Server and whichever DataProvider implementation backs it.
This change limits the feature flags in two ways:
* Introduce the "sendToServerWhenOverridden" metadata field. Only flags that are marked as "sendToServerWhenOverridden" can be sent to the HTTP Server.
* Only send flags which have been overriden by the user.
So for a flag value to be included in "X-TensorBoard-Feature-Flags" it must both have "sendToServerWhenOverridden" set to true and it must be overridden by the user.
Note that none of the flags in Standalone …
> Limit feature flags sent to server.

- tensorboard/webapp/feature_flag/effects/BUILD
- tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
- tensorboard/webapp/webapp_data_source/BUILD
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Now that we can use feature flag metadata from state (https://github.com/tensorflow/tensorboard/pull/5876) we use it in FeatureFlagOverrideDataSource instead of hardcoding the FeatureFlagMetadataMap value.
This will actually allow us to delete all internal implementations of TBFeatureFlagDataSource (googlers, see cl/469204869) since all feature flag parsing logic is now controllable via metadata.
> Get FeatureFlagsMetadata via state in FeatureFlagOverrideDataSource.

- tensorboard/webapp/widgets/card_fob/card_fob_types.ts
The existing enums using numeric values prevented them from being compared and made some internal logic much more complicated.
1) Use the change in internal tensorboard.
2) Perform actions to dispatch effected analytics events
3) Use the analytics dashboard to ensure the events are unchanged.
Using a `record` instead would potentially be more complicated but would also remove the need to map enums to strings.
> Update affordance `enums` to use string values

- tensorboard/webapp/widgets/data_table/data_table_component.scss
Currently the background color of the header is hard coded to white. This is a problem when users are in dark mode. This PR sets the background the the correct theme color based and changes it for dark mode.
Before:
After:
> Change data table header background based on theme

- tensorboard/util/encoder_test.py
Tests that expect zlib to produce a particular bitstream for some input
data are brittle, because the output of zlib is variable for different
implementations and different tunings.
We trust the underlying zlib `encode_png` op does the right thing if it
has a valid PNG header and is of a reasonable size.
> Fix brittle Zlib-dependent test

- tensorboard/util/encoder_test.py
The encoded data length is something that can change over time with
improvements to the underlying compression. We trust the underlying
`encode_op`, so just checking that that we have a valid PNG header is
sufficient.
> Remove extraneous check on encoded data length

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
The values update between step selector and linked time have been an hidden and ambiguous part. They are largely undependable prior to this PR: (1)updates on step selector will not reflect on linked time (2)updates to linked time will only update to a single step selector only when users dragging on _that_ fob. 
In FE team we made a preliminary decision to change case (1): the latest update on step selector will be _remembered_ and set as the linked time selection (as opposed to always set to min value in the dashboard).  case (2) is still true.
* The `affordance` attribute on firing linkedTimeSelectionChanged was designed as optional. i.e., it's already possible that we fire this action without providing affordance …
> linked time: updates linked time selection to latest step selector update

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
Before user check "Link by step" we show them what is the step we are going to link across cards.
This only works on 
* single selection (we can think about extend to range selection later)
* when linked time is disabled: we don't want to have two identical numbers shown up close and updated at the same time
https://user-images.githubusercontent.com/1131010/186510747-88776ec2-7d86-42f8-8011-9345658c519d.mov
> linked time: displays expected step for link by step in settings

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_types.ts
1) We had two different data types that were being used inconsistently.
2) Each place that the object was used redeclared the type which made it difficult to track and update.
There should be no functional changes.
I played with both the scalar and histogram cards to ensure they still worked, then imported the code internally and stepped through it with a debugger to ensure the desired effect was met.
Ignore the inconsistent data structures and just add the new property where needed.
> Refactor TimeSeletionChanged events

- tensorboard/webapp/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- third_party/js.bzl
In our next phase of launching linked time we introduce the range selection. This has a whole new set of columns in the data table. These new columns have already been added however, after discussions with the team and with users we want to change the ordering and text in the headers. This PR makes those changes to the headers.
This change is mostly text changes and some css. The only real logic added was to add an ngswitch inside the data_table_component.ng.html file which adds the triangle mat-icon(which is called "change_history" for some reason).  This is also the first time we added that icon so I had to add it to our build in the js.bzl file.
> Linked Time: Clean data table headers

- tensorboard/webapp/feature_flag/views/feature_flag_page_component.scss
While the modal coloring looks pretty good in OSS internal tensorboard uses a different color palette that does not look as good.
Honestly it should always have been this color anyway.
Before
After
1) Start start tensorboard
2) Navigate to localhost:6006/?showFlags
3) Assert that the modal colors have changed
> Change color of warning message in feature flag modal

- tensorboard/webapp/widgets/range_input/range_input_component.scss
- tensorboard/webapp/widgets/range_input/range_input_component.ts
While messing around with the slider I found some issues. The propagation of the event caused some problems so I stoped that. Also, the change in [this PR](https://github.com/tensorflow/tensorboard/pull/5908) makes it unclear if you are dragging the thumb when there are few steps. Changing the cursor to a grabber helps give that indication and also helps range slider align with the single slider.
Before:
After:
> Linked Time: Clean up slider

- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/widgets/range_input/range_input_component.ts
- tensorboard/webapp/widgets/range_input/range_input_test.ts
Steps are discrete. It does not make sense to have a slider which chooses steps to use floating point. This forces that slider to round to the nearest integer.
Since the slider is a widget I wanted to allow the user of the widget to decide if floating point was something that they wanted. Therefore I made it an optional input.
This is what is looks like in the edge case with only 2 steps.
> Linked Time: Round to nearest integer when dragging range slider

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
Event propagation was causing some when dragging the line above the fob. This prompted us to stop propagation for startDrag events. However, that propagation is needed on the fob to allow users to type in the step. This change adds logic to allow propagation of mouse events on fob clicks.
Before change:
After change:
> Allow event propogation on Fob clicks

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
With the introduction of the data table in Scalar Cards many more useful features become available. One of these features is sorting that data table. This change adds the ability for users to sort by any column by clicking on the header to that column.
The sortingInfo object, which holds the information about which column and what order we are sorting, is stored in the ScalarCardComponent. It is currently not put into the ngrx state. It is piped through the ScalarCardDataTable and into the DataTableComponent. The ScalarCardDataTable uses this information to sort the data passed to the DataTableComponent and the DataTableComponent itself uses the information to update the header UI and inform the information emitted …
> Linked Time: Sort Data Table based on header clicks

- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
This makes the feature flags modal much more useful
1) Prior to making the change open TensorBoard with the `?showFlags` query param.
2) Change a flag to a non default value.
3) Open a fresh tab and note that it no longer appears and overridden in the modal.
4) Apply the change and note that it now appears as overridden.
> Load Feature Flags from `localStorage`

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_types.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
Recent changes broke a feature in Histogram Cards which allowed users to enable range selection by clicking on the chart. This fixes that breakage.
The onLinkedTimeSelectionChanged event was still emitting a simple TimeSelection object. However, the function being called on that event was expecting a TimeSelectionWithAffordance object.  This changes the object to emit a TimeSelectionWithAffordance and created a new type of affordance to use in this event.
> Linked Time: Use TimeSelectionWithAffordance for onLinkedTimeSelectionChanged event

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
This is how it behaves in the settings panel so it stands to reason that the fobs on the chart should behave the same.
Change the fob currently being dragged when they collide
1) Start TensorBoard
2) Navigate to [localhost:6006?enableLinkedTime&enableDataTable](http://localhost:6006?enableLinkedTime&enableDataTable)
3) Enable "Link by step" in the settings panel
4) Set a value for the end step
5) Validate you can drag the start fob past the end fob
6) Validate you can drag the end fob past the start fob
> Swap card fobs when one is dragged past another

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_test.ts
When zooming on the scalar card the min and max values become floating points. Then when you drag the fob passed these values it sets those fobs to floating point steps. Since steps are discrete this is unwanted behavior. This change ensure that we show the min or max step instead of the value(often floating point) at the edge of the chart.
Before
After
> Linked Time: Round to next step in fob controller

- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_test.ts
This is a followup to PR #5911 which added the sorting functionality to the data table. This is purely a UI change to help indicate to users that you can click the header to sort and help make the feature look better.
> Linked Time: Sorting Header css cleanup and hover indication

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
We plan to launch a new feature which allows users to enable a range instead of a single for scalar cards. This is the first PR towards that goal.
This PR adds a feature flag and then uses that flag to enable or disable a checkbox in the settings panel. The checkbox currently has no functionality. That will come in later PRs.
> Linked Time: Add Range Checkbox behind new flag

- tensorboard/webapp/theme/_tb_theme.template.scss
Corresponding changelist: [cl/474442341](http://cl/474442341)
Get off deprecated use of old Angular Material theming API
Switch to using a map to create new themes
> Use current Angular Material theming API

- tensorboard/webapp/theme/_tb_theme.template.scss
Theme configurations used internal to Google will soon be required to define all three keys of the theme config: "color", "typography", and "density".
Setting `typography: null` and `density: 0` is a no-op that has no affect
> Use all theme configuration keys

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
When the fobs are dismissed you expect the fob to disappear. However, when "Link by step" is enabled it only goes into "step selection" mode which still has the fob in Scalar Cards. This change make the dismissal disable step selection so that the fob always disappears. For consistency this also disables step selection when dismissing For on Histogram Card.
Before this change
After this change
> Linked Time: Disable Step Selection when dismissing single fob

- tensorboard/pip_package/requirements.txt
The conda-forge feedstock for tensorboard is attempting to move forward with protobuf support: https://github.com/conda-forge/tensorboard-feedstock/pull/64
@ngam @h-vetinari @hmaarrfk
This PR bumps the upper bound on the protobuf dependency to `< 4`. According to https://github.com/protocolbuffers/protobuf/issues/10051, the only backwards incompatible change that was introduced was between 3.X and 4.X, not between 3.19 and 3.20, hence the change in major version number.
N/A
The conda-forge feedstock for tensorboard now uses protobuf 3.20 without issue, as far as I can tell. …
> Support protobuf 3.20

- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
There is a bug where the lines on the histogram chart do not align with the ticks in the YAxis. This because of some fault logic around the maximum number ticks to be shown there. The issue will occur when the number of lines (steps) is fewer than the height of the chart / 15 (a seemingly arbitrary value).
I updated the logic surrounding the number of ticks to be shown so that the number of ticks <= number steps.
Before
After
1) Start tensorboard with a log directory containing histogram data. Below is some python code. which should generate valid logs.
2) Navigate to …
> Bug Fix: Update Histogram YAxis Values to match those shown in the chart

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Googlers, see cl/474322268 for an internal request to stop using some deprecated constructors within the jsoup library. In all cases here we are unnecessarily passing some baseUri value to a tree node constructor.
They are all unused according to the documentation for older versions of jsoup: 
https://javadoc.io/doc/org.jsoup/jsoup/1.12.1/org/jsoup/nodes/DocumentType.html
https://javadoc.io/doc/org.jsoup/jsoup/1.12.1/org/jsoup/nodes/DataNode.html
https://javadoc.io/doc/org.jsoup/jsoup/1.12.1/org/jsoup/nodes/TreeNode.html
And the constructors are entirely removed in more recent versions of jsoup: For example: 
https://javadoc.io/doc/org.jsoup/jsoup/latest/org/jsoup/nodes/DataNode.html
I did some basic sanity: 
* Ensure generated tensorboard/webapp/index.html and index.js are unimpacted by …
> Fix usage of deprecated jsoup constructors.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Tests will be added once the open question is answered
After zooming on the scalar card with step selection enabled the fob(s) are not guaranteed to be visible.
~### Open Questions:~
While this is an awkward user experience the user will have to get themselves into this situation so we are electing to leave this as is.
* Updated the `line_chart_component` to emit an event when the zoom level is changed.
* This event is then bubbled up to the `scalar_card_container` which is responsible for deriving the `TimeSelectionView` (i.e. the clipped `MinMaxStep` used to to determine the fob position).
* Created an `observable` around this event which is then combined with the existing `observable` listening to the series data change to ensure the `TimeSelectionView` is always recomputed
Zooming on …
> Scalar Card Fob: Move fob when zoom changes

- tensorboard/webapp/metrics/views/card_renderer/vis_linked_time_selection_warning_component.scss
- tensorboard/webapp/theme/_tb_theme.template.scss
Angular Material theme configs put color in a "color" map in the theme config. The colors stored on the first-level are deprecated and copies for backwards compatibility, and will soon be removed.
Also, explicitly include typography rather than including it via core. This exclusion will soon be required for all apps
> Access colors through theme color config

- README.md
a user correctly reported that our documentation incorrectly reported the default value of the reload_multifile_inactive_secs in #5936 . This PR corrects the README to correctly reflect implementation.
> doc: Correct reload_multifile_inactive_secs default in docs

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Sorting in a column which contains `NaN` in the data table used to break the sorting.
Sorting was broken because `NaN` values were actually being passed in as strings which lead to all the values in the column being sorted as though they were strings. To resolve this I translate all values into "sortable" versions which serves to additionally guard against other potentially problematic types.
1) Start tensorboard with a logdir which contains runs with `NaN` values.
2) Go to localhost:6006?enableDataTable
3) Enable step selection and select a step in a scalar card where some but not all values are `NaN`
4) Sort the table by the `value` column and …
> Bug Fix: Fix data table sorting of nans

- tensorboard/webapp/widgets/histogram/histogram_component.scss
When the fob is dragged to the bottom of the histogram it is cut off and hidden behind a box shadow
Remove the problematic box shadow and enable overflow.
Note: Overflow should be fine because the fob is bounded
Before
After
2) Go to localhost:6006?enableLinkedTime
3) Enable linked time in the settings panel (the fob only appears on the histogram card when linked time is enabled)
4) On a histogram card drag the fob to the bottom and note the appearance does not change
5) Drag fobs around on a scalar card and note that it is unchanged.
> Bug Fix: Histogram fob fades when dragged to the bottom

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_test.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
We used to modify the timeSelection Input object in the ScalarCardComponent. Since #5941 This object is now updated in the ScalarCardContainer as it should be. However, the modifications in lower level components are still there. This change removes those modifications and completely relies on the container changes. 
I also took the opportunity to do some cleanup that I thought was nice. I moved the lineChartZoom$ declaration down to the other BehaviorSubject definitions and defined it as readonly. I also made the minMaxStep Observable a BehaviorSubject so that I can use the value to check the new timeSelections before modifying it. This check was previously done in the ScalarCardComponent since we did not have access …
> Step Selector: Stop modifying timeSelection Input

- tensorboard/webapp/feature_flag/BUILD
force_svg_data_source_test.ts is run multiple times in our test suite. We want to run it only one time.
It gets run multiple times because it is grouped with tensorboard/webapp/feature_flag/testing.ts in the same tf_ts_library and thus is accidentally depended on by multiple karma test suite targets.
This change refactors force_svg_data_source_test.ts into its own tf_ts_library and changes tensorboard/webapp/feature_flag:karma_test to explicitly depend on that library. Thus the force_svg_data_source_test.ts is run exactly once as part of feature flag tests.
> cleanup: Run force_svg_data_source_test only once.

- RELEASE.md
This change cherry-picks the 2.10.1 release notes into master. (Googlers, see step 8 in http://go/tensorboard-release).
> cherry-pick: Add 2.10.1 relnotes to RELEASE.md

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
- tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
- tensorboard/webapp/metrics/views/card_renderer/vis_linked_time_selection_warning_component.ts
Change the definition of "clipped" to "A portion of the time selection cannot be shown"
Currently when a the entirety of the time selection is outside of a chart it is determined to be "clipped" and a section is chosen to be shown.
When a card is "clipped" an icon is shown
The current behavior is somewhat confusing as it can lead to states where the card does not show all the content but still does not register as "clipped"
The issue is then further compounded by "zooming"
I updated the `maybeClipTimeSelection` method to always return the maximum time selection available within the bounds of the `minStep` and `maxStep` provided and setting `clipped` to `true` if the `timeSelection` has been changed.
Zooming with linked time enabled without range to include current step
Zooming with linked …
> Bugfix: Fix zooming with linked time by changing the definition of "clipped"

- tensorboard/webapp/metrics/actions/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
We want to track some metrics to see if users are utilizing the sort by feature in the data table. In order to do that we need to fire an action when sorting. This PR fires that action. Note: currently nothing happens on this action but, it sill get hooked into the metrics logging from the internal code for our hosted services.
I created a reducer which fired from that action and console logged the info just to ensure it fired. Then removed that reducer.
> Step Selector: Add action to sorting data table for metrics

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
~Blocked by #5962~
~Blocked by #5965~
We would like the feature to view data related to a range of steps.
Now that both step selection and linked time selection both support range selection I am merging the object used to pass their values down through the scalar card component tree. This provides an opaque interface for the sub-components to utilize without needing to care about whether linked time is enabled.
1) Start tensorboard with an experiment containing a scalar and histogram card
2) Navigate to http://localhost:6006?enableLinkedTime&enableRangeSelection&enableDataTable
3) Click the "Enable Range Selection" checkbox
4) Assert the the scalar card has two fobs
5) Assert the scalar card data table is in range mode
6) Disable "Enable Range Selection
7) Assert the second fob disappears …
> Step Selector: Enable Range Selection for Scalar Card

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
- tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
When toggling range selection the remaining fob was being set to the min value in the range.
Range Enabled:
Range Disabled:
See it in action
Zooming Still Works:
2) Go to localhost:6006?enableRangeSelection
3) Enable range selection in the settings panel
4) Move both fobs on the scalar card
5) Disable range selection either via the checkbox or by removing a fob
6) Assert the remaining fob is not effected.
8) Renable range selection
7) Zoom in on the chart and assert both fobs are visible.
> Bug Fix: Prevent toggling range from resetting time selection

- tensorboard/defs/py_repl.bzl
Building tensorboard/summary:repl in the internal Google repo does not succeed:
```
$ blaze clean
$ blaze build third_party/tensorboard/summary:repl
<snip>
ERROR: /google/src/cloud/bdubois/hgtb/google3/third_party/tensorboard/summary/BUILD:199:8: Symlinking //third_party/tensorboard/summary:repl failed: failed to create symbolic link 'blaze-out/k8-fastbuild/bin/third_party/tensorboard/summary/repl': file 'blaze-out/k8-fastbuild/bin/third_party/tensorboard/summary/repl.sh' is not executable
Target //third_party/tensorboard/summary:repl failed to build
```
Notably this means we cannot `blaze build third_party/tensorboard/...`
Explicitly set repl.sh to executable when creating the file. ctx.actions.write() already has a …
> chore: Explicitly mark tensorboard/summary:repl.sh as executable.

- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
There are bugs in the hparams dashboard (Googlers, see b/239749612 and b/239749837) where the root cause appears to be the fact that some hparams are excluded from session_groups requests. Attempting to sort by the excluded column or any column to the right of it, column "i", would in fact sort by column "i+1". We have an "off-by-one" error.
The code that excludes the column from the session_groups request is here: 
* https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts;l=822-829;drc=dc4754cf27d55c289b85a5ae77591f8d96fb682b
* The column is being excluded because its metadata does not include a filter.
Digging further, we see that this particular column is excluded because …
> hparams: Include hparams without filterable values in session group requests

- tensorboard/plugins/text/metadata.py
There is a library that emits b"{}" as the plugin's metadata, which triggers 500 errors in the Text Plugin server code ([b/250789176](https://b.corp.google.com/issues/250789176)):
```
google3.net.proto2.python.public.message.DecodeError: Error parsing message with type 'tensorboard.TextPluginData'
```
This commit handles the edge case by returning a TextPluginData default proto without parsing the metadata. 
- For the edge case that feeds in b"{}", users will see something like <img width="1213" alt="image" src="https://user-images.githubusercontent.com/88216042/195389659-a75660ce-01e4-4ecd-ace3-19b11cadfa07.png"> rather than an "Internal server error" page. 
Open the browser and enter the TextPlugin metadata endpoint of an experiment that generates the invalid metadata, e.g. …
> Avoid parsing Text Plugin metadata b"{}"

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html.ts
Inside the projector plugin, a legend for labels/colors should appear when selecting a field from the "Color by" drop-down menu yet is not displayed.
The `dom-if` property is misconfigured for the `vz-projector-legend` template.
Before: 
After: 
- Run the vz-projector in standalone mode
- Use the default [`standalone_projector_config.json`](tensorboard/plugins/projector/vz_projector/standalone_projector_config.json) as config file (if run locally you need a simple webserver to serve the file via http)
- Select the *Iris* tensor, then select "Class" under the "Color by" drop-down menu.
- See the label/color legend appear just below
> projector: fix label/color legend

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
#5968
The card fob would dispatch a `timeSelectionChanged` event on mouse up even if the time selection had not changed...
2) Go to http://localhost:6006
3) Enable step selection
4) Open the console and clear it
5) Dismiss the fob by clicking this button
Add a `mousedown` event listener to the dismiss button which prevents propagation. Unfortunately this would prevent clicks starting on the dismiss button from dragging the fob.
> Bug Fix: Prevent Card Fob from dispatching duplicate events when a fob is removed

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
ubuntu-18.04 is deprecated and experiences periodic brownouts.
See: https://github.com/actions/runner-images/issues/6002
I initially attempted to upgrade to ubuntu-22.04 but could not solve problems running karma and ChromeHeadless driver.
```
[1018/165541.955009:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 6 time(s)
[1018/165541.955035:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```
This problem does not appear to exist on ubuntu-20.04.
> chore: Upgrade github actions to use ubuntu-20.04.

- WORKSPACE
- package.json
- patches/@bazel+concatjs+5.7.0.patch
- patches/BUILD
- patches/README.md
- yarn.lock
* Motivation
Karma tests are failing in chrome in certain environments (including, most recently, some internal Google machines) with errors like:
```
[1019/144854.100947:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 1 time(s)
[1019/144854.140417:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 2 time(s)
[1019/144854.174092:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 3 time(s)
[1019/144854.241059:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 4 time(s)
[1019/144854.253018:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 5 time(s)
[1019/144854.265413:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 6 time(s)
[1019/144854.265453:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. …
```
> Patch @bazel/concatjs to run karma tests outside sandbox and fix test runtime errors.

- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
The new step selection feature currently must be enabled every time you load Tensorboard. This is annoying for users who like this feature and have to turn it on constantly. This change persists the settings in LocalStorage so it can stay enabled on that machine until it is disabled.
Just followed the pattern of settings that are already persisted.
> Step Selector: Persist step selection settings.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
For Googlers [b/254089050](b/254089050)
Run names are currently sorted differently in the data table than in the tool tip. I'm changing the sorting to be consistent with the tooltips alphabetical sort.
2) Visit localhost:6006?enableDataTable&enableRangeSelection
3) Click the "Enable Range Selection" checkbox in the settings panel
4) Sort the scalar card data table
5) Assert that the table is sorted by the run name only (not the alias or alias id)
I considered creating a column alias map but this approach seemed more flexible.
> Data Table: Sort Run Names Without Id and Alias

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_test.ts
The "minMax" input of scalar fob controller is actually the viewExtend/viewBox, not the min max step, while it's got used as the min max step. Visually the extend is larger than the min/max step and it is what we need for forward and reverse function.
```
A   B   (chart)   C   D
|---|-------------|---|
```
axis size: A to D
minMax:  A to D
line chart area: B to C
min step: B
max step C
This wasn't noticed because we clip the time selection at the scalar card level to prevent the fob go out of the valid range (B to C)
This PR adds another minMaxStep input and rename the old minMax to minMaxHorizentalViewExtend. 
(Note: skip the rename in test since that matters less)
Everything should be the …
> linked time: update scalar to "real" min max step

- tensorboard/webapp/feature_flag/views/feature_flag_page_component.ng.html
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.scss
In hosted services we have too many flags to fit on many screens. Before this change that meant the bottom flags and the reset button were cut off. Now we can scroll down to see all flags and the reset button.
> Add scrolling functionality to feature flag page

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
This is pre-work of placing prospective fob at the mouse position. First we want to get the position which reflects the prospective step.
Same structure as how we get start/end fob position, just create another one for prospective fob.
Small styling (opacity and cursor)
Not visible yet. Sets step directly for unit test only.
> linked time: set prospective fob position from prospective step

- README.md
The links to the compatibility badge and page do not exist any more (added at https://github.com/tensorflow/tensorboard/pull/2328). Also checked a few other repos under TensorFlow, none of them have compatibility badge.
Preview:
#oncall
> doc: replace the compatibility badge with pypi package badge in the readme

- tensorboard/summary/writer/event_file_writer.py
- tensorboard/summary/writer/event_file_writer_fsspec_test.py
- tensorboard/summary/writer/event_file_writer_test.py
Specifies source metadata for event files as `tensorboard.summary.writer.event_file_writer` for the TB summary writer.
> Add summary source metadata to the TB summary writer output

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
The new implementation of Linked time moved away from this template but it has not been removed. This PR has no visible change in UI or features but removes a lot of unused code.
We have now switched over to using the lineChartCustomXAxisVis for all linked time needs.
> Linked Time: Removed old customVisTemplate that is no longer used

- tensorboard/compat/proto/update.sh
In TF 2.11 the tensorflow/tsl/protobuf directory is created(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tsl/protobuf). This directory has a histogram.proto file which is referenced from summary.proto(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/summary.proto#L5). Additionally that proto is imported with the public keyword which we previously were not looking for.
> Bring proto update script up to date to deal with new protos in TF2.11

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
We would like to be able to enable step selection using a prospective fob. The prospective fob is currently implemented withing the fob_controller_component which has a required `timeSelection` parameter.
None
2) Go to [http://localhost:6006?enableDataTable=true&enableProspectiveFob=true](http://localhost:6006?enableDataTable=true&enableProspectiveFob=true)
3) View a scalar card
4) Assert that no fobs are shown
5) Enable step selection
6) Assert that a single fob is shown
> Linked Time: Make `timeSelection` optional in fob controllers

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
On mouse hovering the axis, we want to show the prospective fob. On mouse leaving, we want to remove the fob. This PR creates that element and implement the mouse leaving part.
A new div element to take the mouse event for displaying the prospective fob.
The element is placed beneath start/end fob then those events will not be triggered when start/end fob hovered and ready to be dragged. 
The range of this area is subjected to change. I made something seems reasonable to me for now. We can also think of extending the area or do something else about it (might be similar to the dragging flow) but that will come later if we feel the need to improve the flow.
Not visible still, but the area in …
> linked time: create listen area for fob and set step to null on mouseleave

- README.md
Right now only pushes to our master branch have a build status badge. This adds an additional badge for the nightly scheduled build. See [here](https://github.com/groszewn/tensorboard/tree/ci_badge#readme) for what the updated README would look like.
> doc: Add github badge for nightly builds

- tensorboard/manager.py
- tensorboard/manager_test.py
This is a follow-up PR after https://github.com/tensorflow/tensorboard/pull/5998.
Tested locally with:
```
bazel run //tensorboard -- --logdir /tmp/log_set_11-08-2020/ --bind_all
```
Tested internally: [cl/483980532](http://cl/483980532)
#oncall
> cleanup: replace namedtuple with dataclass - part 2

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/backend/event_processing/event_util.py
- tensorboard/backend/event_processing/event_util_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
Motivation:
Googlers, see go/tb-writer-source-metadata for context.
Note that:
- The current assumption is that each run would have at most one source writer.
- The maximum allowed length for the writer name is set to 128. 
- For simplicity, only source writer name rather than the entire `SourceMetadata` proto is parsed (since this is the only field). 
- In the future if more fields are added, the `SourceWriter` property can be easily generalized to `SourceMetadata` in the `EventAccumulator`. 
Tested locally with:
```
bazel run //tensorboard --  --logdir [path_to_logs] --bind_all
```
#source_metadata
> Source Metadata: Parse source writer information from the first event of each run

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
~Blocked by #6005~
We would like to be able to enable step selection using a prospective fob. Now that #6005 is merged, the fob controller can safely be rendered with an undefined `timeSelection`
None
> Linked Time: Render card fob controller when prospective fob feature is enabled

- tensorboard/webapp/widgets/card_fob/card_fob_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_test.ts
It does not make sense for a prospective fob to have a deselect button
Add a prop to the card fob component which controls the appearance of the deselect button.
None
There should be no changes.
> Linked Time: Conditionally remove fob deselect button

- tensorboard/compat/proto/BUILD
- tensorboard/defs/protos.bzl
This is needed to fix internal build after the `HistogramProto` location change in https://github.com/tensorflow/tensorboard/pull/6010. In OSS we don't need the `tb_proto_library` to actually use the `exports` arg since we could use the `public` symbol (https://developers.google.com/protocol-buffers/docs/proto3#importing_definitions) without additional changes. The signature change for `tb_proto_library` is required internally.
Corresponding internal change: cl/485927103 (see cl description for full details).
Tested internally at cl/485864749.
> build: export histogram proto declaration in summary proto

- tensorboard/plugins/projector/vz_projector/projectorScatterPlotAdapter.ts
- tensorboard/plugins/projector/vz_projector/vz-projector.ts
Fixes a regression where sprites are shown as black squares when first loaded and when any sprite is deselected. This ultimately stemmed from a null check (which colored the legend point white when null) being passed over when `strictNullChecks` was introduced.
This allows `legendPointColorer` to take a null value. If `colorOption` does not exist, it doesn't make sense to still go over the full dataSet color assignment. Instead, return early to get `noSelectionColor`.
Googlers, see b/255947072.
> Fix projector legend point coloring

- tensorboard/plugins/projector/vz_projector/vz-projector.html.ts
- tensorboard/plugins/projector/vz_projector/vz-projector.ts
On the embeddings projector, on the top left corner of the scatter plot there's an help icon (with a question mark) that when clicked should open a dialog showing an help for the controls in 3D and 2D mode.
Currently the icon doesn't work and if clicked nothing happens.
Set a custom function on the `on-click` event of the `paper-icon-button`.
- Open the embeddings projector
- Click on the help icon (question mark, tooltip "Help with interaction control")
- The help dialog should appear at the center of the page
> projector: fix controls help dialog button

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
To resolve the latest comments in https://github.com/tensorflow/tensorboard/pull/6014:
- Replace `SourceMetadata` property with `GetSourceWriter()`
- Log at `info` instead of `warning` when multiple source writers are found for the same run.
#source_metadata
> Source Metadata: cleanup

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
There is a bug (that cannot currently be replicated) when the `enableProspectiveFob` feature is enabled where a prospective fob will appear even when the axis is not in `STEP`
NONE
1) Go to the future 
2) Start tensorboard
3) Go to http://localhost:6006?allowRangeSelection=true
4) Change the horizontal axis to anything other than STEP
5) Hover your cursor on the X Axis of a scalar card chart
6) Assert nothing happens?
> Linked Time: Fix issue with prospective fob when axis is not step

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
Some other changes to be compatible with the 22.04 image:
* Bump python version for lint-python-yaml-docs. 3.6 no longer supported.
* Force downgrade of protobuf in lint-python-yaml-docs.
Note: We recently updated github actions to use ubuntu-20.04 in https://github.com/tensorflow/tensorboard/pull/5984 but subsequently unlocked ubuntu-22.04 with https://github.com/tensorflow/tensorboard/pull/5989.
> chore: Upgrade github actions to use ubuntu-22.04.

- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
Blocked by #6022
We believe the many check boxes in the settings panel to not be very discoverable and a generally poor user experience. To avoid needing as many check boxes we're adding a "Prospective Fob" which will be shown when hovering the axis of a chart. 
This PR just starts rendering the feature while #6017 will add the click interactions.
2) Nagivate to http://localhost:6006/?enableDataTable=true&allowRangeSelection=true&enableProspectiveFob=true#timeseries
3) Hover a scalar card chart
4) Assert a prospective fob appears
> Linked Time: Render a prospective fob on the scalar card when the feature is enabled

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
We currently have two sources of truth for determining if range selection is enabled, the existence of the timeSelection end step AND the state variable `rangeSelectionEnabled`. This means that when range selection is disabled we need to clear the end step.
In a future PR I will stop the end step from being removed when range selection is disabled.
None
2) Go to http://localhost:6006?enableRangeSelection
3) Enable range selection
4) Ensure a second fob appears on the scalar card
5) Disable range selection
6) Assert the end fob is removed.
> Linked Time: Render end fob based on the status of `rangeSelectionEnabled`

- tensorboard/defs/internal/html.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
https://bazel.build/extending/rules#configurations
Googlers, see b/258839383 and cl/487924665.
> Migrate bazel cfg from "host" to "exec"

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_types.ts
Blocked by #6006 and #6016
We believe the many check boxes in the settings panel to not be very discoverable and a generally poor user experience.
To remedy this we would like to shown a "Prospective Fob" when the user hovers over the scalar card chart. When the user clicks on this "prospective fob", a fob will be placed at the corresponding location and step selection / range selection will be enabled as appropriate.
Step Selection Disabled
Step Selection Enabled
2) Navigate to http://localhost:6006?enableDataTable=true&allowRangeSelection=true&enableProspectiveFob=true
3) Hover over the X Axis of a scalar card chart
4) Assert a prospective fob is shown and has no deselect button
5) Click on the prospective fob
6) Assert step selection is enabled and the data table …
> Linked Time: Make Prospective Fob Interactive

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
Enabling range selection by clicking a prospective fob then disabling range selection via the checkbox (or another card) resulted in the prospective fob being shown.
The prospective fob appears based on the value of the prospectiveStep. When the prospective fob is clicked setting the step to null ensures that disabling range selection cannot trigger it to reappear.
Look ma, it's gone
2) Navigate to http://localhost:6006/?enableDataTable=true&enableLinkedTime=true&allowRangeSelection=true&enableProspectiveFob=true#timeseries
3) View a scalar card and click on the xaxis to add a start fob
4) Click …
> Linked Time: Remove prospective fob when it is clicked

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
For googlers b/259092516
When linked time is enabled fobs are shown on the histogram card. There is currently a bug where the end fob is now shown on the histogram card. This is because of a #6033 changing the circumstances under which the end fob is shown.
After #6033 the end fob is only rendered when the `CardFobControllers` `rangeSelectionEnabled` prop is set. I missed setting it from the Histogram Card and thus it does not appear.
Before:
After:
2) Nagivate to http://localhost:6006?enableDataTable=true&enableLinkedTime=true&allowRangeSelection=true
3) Enable range selection and linked time in the settings panel
4) Ensure two fobs are shown on the histogram card
> Linked Time: Fix histogram range selection bug

- tensorboard/webapp/theme/_tb_theme.template.scss
Googlers, see [b/259074873](https://b.corp.google.com/issues/259074873).
http://go/tbpr/5951 increased the size of our Angular js bundle from 4,418,195 bytes to 5,440,612 bytes. The root cause was adding an @include statement to a sass "Partial" file (_tb_theme.template.scss) that is included by many many TensorBoard components. The contents of the @included sass file were therefore duplicated many many times and included many many times in our js bundle.
The Angular team advised us that "Partial" sass files should not contain @include statements at the top-level. These particular @include statements probably should really only be invoked once for the entire application so we add them to the `tb-global-themed-styles()` mixin, which is already included once in the project by …
> Reduce js bundle size by eliminating duplicate sass rules.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view_test.ts
Fixes #5932 
My solution is to make the card fob non interactive while the user is interacting with the chart.
This is achieved by piping events from the `line_chart_interative_view` component up to the `line_chart_component` and then to the `scalar_card_fob_controller` component through the use of the existing view template.
> Bug Fix: Fix issue with zooming over the step selector

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/types.ts
There is a plan to add customization features to the new data table in Scalar cards. This prepares for those changes by adding a flag that these features can hide behind while in development.
This simply follows the same pattern as other feature flags.
> Column Customization: Add feature flag

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
When clicking a prospective fob with a value less than the existing fob both values are set as the maximum.
This only happens when linked time is enabled.
For Googlers https://screenshot.googleplex.com/XbTQfkKUaPkkRGM
This seems to have been caused by setting the start step to a value which is greater than a end step.
Look! It's fixed!
2) Navigate to http://localhost:6006?enableLinkedTIme&enableRangeSelection&enableProspectiveFob
3) Enable Linked Time in the settings panel
4) View a scalar card and click someplace on the X Axis to enable step selection
5) Click someplace to the left of the current fob …
> Bug Fix: Emit correct timeSelection when prospective fob is clicked

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
- tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
When changing the zoom on the scalar card with an the end fob the end fob was always placed at the maximum possible step.
For Googlers b/259562961
The `StepSelectorTimeSelection` derived by a subscription to a bunch of other Observables. The main issue was that it simply never checked if an existing end step existed. The code was also kinda hard to read(:raised_hand_with_fingers_splayed: my fault) so I went ahead with a bit of a cleanup there.
Before:
Zooming In:
Resetting Zoom Level:
After:
2) Navigate to http://localhost:6006?enableRangeSelection&enableDataTable
3) Place two fobs on the scalar card
4) Zoom in on a segment of the chart which contains both fobs (much easier now that #5932 is closed)
5) Assert neither fob has moved
6) Reset the chart zoom level
7) …
> Linked Time: Fix bug with zooming always maximizing end step

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
This reverts commit b08e2f8e907b10932fb707b30ab87eac7db85f3b.
I was wrong. This template is still used to shade out the area outside of a range selection.
> Revert "Linked Time: Removed old customVisTemplate that is no longer used"

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
See #6055 for motivation and styling
Unfortunately I broke the zoom functionality with that PR and thus reverted it via #6068
There was [discussion](https://github.com/tensorflow/tensorboard/pull/6055#issuecomment-1322855915) around removing the DOM restructure present in #6055 and because that was ultimately to blame for the breakage I am resubmitting the PR but without the DOM restructure.
> Linked Time: Update prospective fob styling

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
This fixes a bug where the start step was sometimes initialized as INFINITY.  Math.min([]) returns INFINITY and Math.max([]) return -INFINITY. This makes sense for some applications but for us this was causing bugs. I went ahead and forced the value to be the other way around when the array was empty. This fixed the bug.
> Bug: Initialize proper minMaxSteps when there are no points.

- tensorboard/defs/web.bzl
- tensorboard/plugins/projector/tf_projector_plugin/BUILD
- tensorboard/plugins/projector/vz_projector/BUILD
- tensorboard/plugins/projector/vz_projector/standalone.html
See: https://github.com/tensorflow/tensorboard/issues/6065 
We document the ability to run the projector plugin in standalone mode:
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/README.md
But it doesn't work.
The first thing to fix is to get the ":standalone" target to be executable and bring up a working server:
* Hard to know exactly where things went wrong. I have found evidence that this worked as late as [September 2020](https://github.com/tensorflow/tensorboard/issues/4158). I suspect things went wrong in [April 2021](https://github.com/tensorflow/tensorboard/pull/4906/files), when tensorboard_html_binary() was replaced by tb_combine_html().
* In the case of vz_projector it seems we can just delete the current ":standalone" target and rename the …
> projector: Fix standalone vz_projector server.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
When users have smoothing enabled the raw values on the scalar chart are faded and hidden in the background while the smoothed lines are highlighted and in the foreground.  However, while in range selection mode the data table only showed values based on the real values. This was confusing for users. This changes the data table to use the smoothed and highlighted values on the chart in the data table.
We simply changed the calculations to use the "y" property on the ScalarCardPoint object instead of the "value" property.
> Data Table: Use smoothed values in table

- tensorboard/plugins/hparams/summary.py
Boolean typed values should be checked before integers:
```shell
>>> isinstance(True, int)
True
>>> isinstance(True, bool)
True
>>> isinstance(False, (float, int))
True
>>> isinstance(1, bool)
False
```
See https://stackoverflow.com/questions/8169001/why-is-bool-a-subclass-of-int for context.
For Googlers - this came up in cl/492278796.
> hparams: fix type check bug

- package.json
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
- tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts
- tensorboard/webapp/testing/lang.ts
- yarn.lock
Upgrade to TypeScript 4.8.4 following instructions in https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md#adding-updating-or-removing-frontend-dependencies.
This upgrade is also a good opportunity to remove some @ts-ignore annotations that were added to the codebase to satisfy the internal upgrade to TS 4.8.4. See https://github.com/tensorflow/tensorboard/pull/6075 and https://github.com/tensorflow/tensorboard/pull/6037. Removing the annotations did indeed lead to build errors that I then fixed with some type adjustments. There is no change in behavior.
Verified by:
* Running the Angular test suite.
* Building and running the TensorBoard app and clicking around.
* `cd tensorboard; grep -r "ts-ignore" *` and ensuring all relevant @ts-ignore annotations have been removed.
> Upgrade to TypeScript 4.8.4.

- .github/workflows/ci.yml
Moving to the latest Rust release version, [1.65.0](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html) for CI.
> Upgrade rust version for CI to latest

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.scss
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
#6081 but with only css
Enabling the  prospective fob feature prevents the X Axis from being edited on the scalar card.
The prospective fob area lies directly on top of the X Axis and thus prevents it from being hovered.
To resolve this I used CSS reach across the components and change the visibility of the extent edit button when the prospective fob area is hovered.
2) Navigate to http://localhost:6006/?enableLinkedTime=true&enableDataTable=true&allowRangeSelection=true&enableProspectiveFob=true#timeseries
3) Hover the X Axis of a scalar card
4) Assert the axis edit button appears
#6081
I considered reordering the DOM to place the fobs within the axis component but thought there would be issues with the lines. While this seems possible it doesn't seem worth the …
> Bug Fix: Make axis edit button appear when prospective-fob-area is hovered

- .github/workflows/ci.yml
Moving to the latest Rust release version, [1.65.0](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html) for CI lint.
> Update rust lint version for CI to latest

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
The smoothed column in the scalar card data table does not render when smoothing is disabled. The logic for removing this column previously occurred in the ScalarCardContainer where it removed the column entirely from the list of headers. This causes some strange behavior which needs to be handled when dealing with changing the order of the columns. 
This change removes the special treatment of the Smoothed column everywhere except for when it is rendered.
No changes.
> Refactor: Handle Smoothed column logic in DataTable

- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
- tensorboard/webapp/widgets/experiment_alias/experiment_alias_component.ts
For Googlers b/259431435
We abbreviate the name of the experiment which can lead to confusion. By showing the full name in a tooltip we provide users a way of accessing that information.
Tooltips are generally created by setting the `title` attribute. However, this particular column is a custom element and thus required me to pass the attribute through.
IDK how to screenshot tooltips :shrug: 
I tested this on internal tensorboard where the experiment column gets used.
> Feature: Add a tooltip to the runs table experiment name column

- tensorboard/data/server/pip_package/build.py
When building tensorboard-data-server from source on Linux aarch64, pip install raises the following error:
```
pip._internal.exceptions.UnsupportedWheel: tensorboard_data_server-0.6.1-py3-none-manylinux2010_aarch64.whl is not a supported wheel on this platform.
```
From what I can tell, manylinux2014 is the first version that supports aarch64. TensorFlow also moved to manylinux2014, so there should be no issues with us updating as well: https://pypi.org/project/tensorflow/#files
N/A
I don't have access to Linux aarch64 myself (this was discovered in our CI) but anyone who does should be able to confirm that this works …
> tensorboard-data-server: add Linux aarch64 support

- third_party/rust.bzl
The latest rust version is `1.65.0`, which is now being used in CI. Additionally, `rust_repositories` is [deprecated](https://github.com/bazelbuild/rules_rust/blob/main/rust/repositories.bzl#L214) in favor of [rules_rust_dependencies](https://github.com/bazelbuild/rules_rust/blob/main/rust/repositories.bzl#L47) and [rust_register_toolchains](https://github.com/bazelbuild/rules_rust/blob/main/rust/repositories.bzl#L102).
> Update `rules_rust` to point to the latest rule version and update deprecated API call

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.ng.html
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.scss
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.ts
- tensorboard/webapp/feature_flag/views/feature_flag_page_container.ts
- tensorboard/webapp/feature_flag/views/types.ts
The feature flag modal has a couple UX bugs
1) The modal does not scroll when there are too many flags.
2) The reset all button does not visually update the modal
3) There is a subtle difference between Default states and states overridden with the default value that is not stated.
* There was a typo on one of the css class names.
* The modal was only being updated when the default flags changed while it should really have been when the overridden flags changed
* I added some text that only appears when relevant describing the distinction between default and overridden with default value.
OSS without needing to scroll
OSS when the window is tiny
Internal Screenshot for Googlers (contains messages about default flags)
https://screenshot.googleplex.com/LCiK2xtBVa2SpP4
1) Start TensorBoard …
> Improve the feature flags modal

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
The upgrade to Angular 13 caused debugger_v2 tests to fail flakily with errors like "Error: Injector has already been destroyed."
Others have run into this problem: https://github.com/angular/angular/issues/44186
The suggested workaround is to set `destroyAfterEach` to false. The default value for `destroyAfterEach` changed in Angular 13.
The Angular team suggests this means we "have scope leakage in [our]  tests" but we haven't been able to pinpoint the leakage.
Tested by running `bazel test //tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin:karma_test_chromium-local --nocache_test_results --runs_per_test=20`. Prior to the fix this would reliably fail for a good fraction of the test runs. After the fix all runs pass.
> Eliminate flakiness of debugger_v2 karma tests.

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
Our goal is to allow users to select which columns they what displayed in the data table and in which order. To do this we have to have a notion of which columns are enabled and which are disabled. This change makes the column headers in the ngrx state objects with have a type and an enabled boolean so that this info can be stored and utilized.
> Column Customization: Refactor Column Headers to include enabled

- tensorboard/compat/tensorflow_stub/dtypes.py
`numpy.bool8` is just a deprecated alias of [`numpy.bool_`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool_). Removed here to get rid of the deprecation warnings (https://github.com/tensorflow/tensorboard/issues/6110).
Googlers, see cl/498031924 for internal tests.
#oncall
> Remove deprecated alias `numpy.bool8`

- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/data_provider_test.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/backend/event_processing/io_wrapper_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/backend/event_processing/reservoir_test.py
- tensorboard/compat/tensorflow_stub/io/gfile_tf_test.py
- tensorboard/manager_e2e_test.py
- tensorboard/manager_test.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/hparams/_keras_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/npmi/npmi_plugin_test.py
- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/projector_plugin_test.py
- tensorboard/plugins/text/text_plugin_test.py
- tensorboard/plugins/text_v2/text_v2_plugin_test.py
- tensorboard/uploader/util.py
- tensorboard/util/tensor_util.py
This PR
- replaces deprecated alias `assertItemsEqual` with `assertCountEqual`: 
- `sed -i 's/assertItemsEqual/assertCountEqual/g' tensorboard/**/*.py`
- replaces `text_format.Merge` with its non-lossy version `text_format.Parse`
- uses `fromtimestamp` with UTC timezone
- `utcfromtimestamp()` returns a timezone-naive UTC datetime, which is bug-prone: [https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp](https://www.google.com/url?sa=D&q=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fdatetime.html%23datetime.datetime.utcfromtimestamp)
- uses list comprehension
Googlers, see the linting suggestions in cl/499227915.
#oncall
> refactor python files

- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
For googlers, refer to b/264288347
This PR disables certain tests that currently fail with internal TensorFlow changes that are going to be pushed. Once those changes are propogated to tf-nightly, these tests will be re-enabled and updated.
> Disable tests in Debugger V2 Plugin

- .github/workflows/ci.yml
This PR upgrades the following Github actions to reduce the deprecation warnings for commands `save-state` and `set-output`:
- `actions/setup-python` to `v4.3.0` 
- https://github.com/actions/setup-python/issues/524
- `actions/upload-artifact` to `v3.1.1`
Note that `cache` action isn't upgraded here since `actions/cache@v3` still returns deprecation warnings: https://github.com/actions/cache/issues/1045.
Googlers, see b/257310824.
#oncall
> ci: upgrade `setup-python` and `upload-artifact` actions

- tensorboard/uploader/auth.py
- tensorboard/uploader/auth_test.py
- tensorboard/uploader/uploader_subcommand.py
The OOB auth flow has been deprecated. We concluded that the limited-input device flow is appropriate for our use case where the uploader runs in an environment where a browser is not available.
Implements a new auth flow which calls an RPC to fetch a device_code, verification_url and user_code, and asks user to visit the verification_url in another device and enter the user_code; then starts polling for the access token after the user authorizes the access from another device.
N/A
- Wrote test script that uses this class, and tested the auth flow and was able to print the credentials.
- Wrote tests.
* Alternate designs / …
> Implements limited-input device auth flow, to replace deprecated OOB auth flow.

- tensorboard/backend/event_processing/event_accumulator.py
This PR reattempts the changes reverted in https://github.com/tensorflow/tensorboard/pull/6013 and fixes https://github.com/tensorflow/tensorboard/issues/5725.
Googlers, see prerequisite internal changes at [cl/b:234007753](http://cl/b:234007753) and global internal test at cl/499266633.
#oncall
> cleanup: replace namedtuples with dataclasses in `event_accumulator`

- tensorboard/plugins/npmi/csv_to_plugin_data_demo.py
- tensorboard/plugins/pr_curve/summary.py
Numpy library deprecated some type aliases in version 1.20.0 [1], and then removed them in version 1.24.0 [2], which was released on Dec 18, 2022.
Without this change, our build would be broken when using numpy version >= 1.24.0,
with error `AttributeError: module 'numpy' has no attribute 'float'`.
The fix suggested in release notes from numpy version 1.20.0 is to replace these types with the equivalent primitive python types. (In this case, simply `float`.)
[1] http://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated  
[2] http://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations
Newer numpy versions break our build. This code is exactly equivalent, as the identifiers used …
> Updates references to numpy deprecated type aliases.

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
This feature is complete and we would like people to use it
The Linked Time feature is controlled by 4 feature flags:
* `enabledScalarDataTable`
* `enabledLinkedTime`
* `allowRangeSelection`
* `enabledProspectiveFob`
Settings Panel:
Prospective Fob:
Data Table with Range Selection:
1) Start TensorBoard
2) Navigate to `localhost:6006` (Note the lack of feature flags)
3) Ensure the settings panel contains the step selection, range selection, and linked time checkboxes
4) Hover a scalar card X Axis
5) Assert a fob with a border appears
6) Click that fob
7) Assert a permanent fob is created there
8) Assert the table appears on that card
9) Assert you can create a second fob in the same way as the first
10) Click the "Link By Step" checkbox in the settings panel
11) Assert the step selectors …
> Linked Time: Enable Linked Time

- RELEASE.md
- tensorboard/compat/tensorflow_stub/dtypes.py
- tensorboard/plugins/npmi/csv_to_plugin_data_demo.py
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/uploader/auth.py
- tensorboard/uploader/auth_test.py
- tensorboard/uploader/uploader_subcommand.py
- tensorboard/version.py
A patch release to replace the deprecated OOB auth flow, and remove deprecated aliases
that were removed in numpy 1.24.0.
- Prevent regression in TensorBoard.dev uploader authentication by replacing deprecated OOB auth flow with limited-input device flow. (#6107)
- See [deprecation announcement](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html).
- Fix compatibility with numpy 1.24.0 by removing deprecated type aliases (#6117, #6140)
> TensorBoard 2.11.1

- tensorboard/uploader/auth.py
- tensorboard/uploader/auth_test.py
There's a bug in the limited-input device auth flow.
The tests did not catch this issue because the config is read from a JSON string, and the test was using an "already parsed" config (dictionary), with a different structure from the json downloaded from our GCP project.
Unwraps the parsed client_config from the "installed" layer, and updates test with a "realistic" configuration (which uses this structure).
N/A
Ran both auth flows manually (with and without browser), and updated tests.
N/A
> Fixes bug with the config passed to the "limited-input device" auth flow

- RELEASE.md
- tensorboard/uploader/auth.py
- tensorboard/uploader/auth_test.py
- tensorboard/version.py
- Fixes bug introduced in #6107, which was included in release 2.11.1. (#6142)
> TensorBoard 2.11.2

- .github/workflows/ci.yml
- tensorboard/pip_package/setup.py
Fixes #6138.
Python 3.7 is almost at EOL (coming up in [a few months](https://devguide.python.org/versions/#supported-versions)), and has already been [dropped by TensorFlow](https://github.com/tensorflow/tensorflow/commit/53ffdf135db0cc35ed8fc601d10fdfcd27df2295).
This updates our CI to use Python 3.8. It also marks Python 3.11 as supported (it was released to stable last fall).
Tested: confirmed that TensorBoard works as expected with Python 3.11, as follows:
```
$ docker run -it -p 6006:6006 --mount source=$HOME/scratch/demodir,destination=/logs,readonly python:3.11 bash
root@dac67b60b6af:/# python --version
Python 3.11.1
root@dac67b60b6af:/# pip install tensorboard
...
root@dac67b60b6af:/# tensorboard --logdir /logs --bind_all
...
```
> infra: drop support for Python 3.7 and mark 3.11 as supported

- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
These tests were disable to allow for a change in the tensorflow code this relies on. We are now re-enabling them.
Googlers, see b/264288347.
> re enable tests which were temporarily disabled

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
Different flavors of TensorBoard have different feature flags. If you have saved a feature flag to `localStorage` then switch to running a different version a null pointer exception will occur until you clear the key from `localStorage`.
This could also happen if a feature flag is removed but still stored in some clients `localStorage`.
* The null pointer exception was occurring in the `getFeatureFlagsToSendToServer` function thus I added a null check. This is not a strictly necessary change.
* I then filtered the feature flags being loaded to ensure unsupported feature flags are not loaded.
N/A
1) Start TensorBoard
2) Navigate to http://localhost:6006?showFlags
3) Store some flags to …
> Bug Fix: Stop `tb_feature_flag_data_source` from loading unsupported feature flags

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
- tensorboard/webapp/metrics/views/main_view/main_view_component.scss
- tensorboard/webapp/metrics/views/main_view/main_view_component.ts
- tensorboard/webapp/metrics/views/main_view/main_view_container.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This affordance will be used to house the column customization menu. For reference to where we are heading please see this branch(https://github.com/tensorflow/tensorboard/compare/master...JamesHollyer:tensorboard:EditColumnMenu).
The slideout affordance is added to the mainViewComponent as it must be able to move outside the settings menu. When it is toggled we add the .slide-out-menu-expanded class which moves it to be in view. This with the transition property make the slide out animation.
> Column Customization: Add slideout affordance and toggle button

- .github/workflows/ci.yml
The macOS `latest` runner image has been updated to point to `macOS-12` (Monterey) as of last week (actions/runner-images#6901), while we still specify `macOS-11` (Big Sur). Given that macOS 13 (Ventura) is already available, we should at least update to `macOS-12`. There is currently no EOL specified for `macOS-11` (Big Sur), but changing to `macOS-latest` should help us ensure we're always validating with a relatively recent version of macOS and avoid missing any future deprecation windows.
> ci: Update macOS platform to `macOS-latest`

- .github/workflows/ci.yml
To avoid deprecation warnings in our workflows, update `checkout` to the latest version to avoid `save-state` and `set-output` deprecation warnings.
> ci: Update checkout action to 3.3.0

- .github/workflows/ci.yml
Updates to use the latest (3.6.0) release of
[setup-node](https://github.com/actions/setup-node) and bumps the Node.js version to 16.
This should get rid of some deprecation warnings we're seeing in our workflow actions (for example,
https://github.com/tensorflow/tensorboard/actions/runs/3388287772). However, some other actions still need releases to finish cleaning up these warnings (see #6155).
Contributes to #6123.
> ci: Update setup-node and cache actions to latest versions and specify Node.js 16

- .github/workflows/ci.yml
- tensorboard/data/server/commit.rs
- tensorboard/data/server/data_compat.rs
- tensorboard/data/server/event_file.rs
- tensorboard/data/server/gcs/auth.rs
- tensorboard/data/server/gcs/logdir.rs
- tensorboard/data/server/run.rs
- tensorboard/data/server/types.rs
[actions-rs/toolchain](https://github.com/actions-rs/toolchain) and [actions-rs/clippy-check](https://github.com/actions-rs/clippy-check) have not been updated in the last two years. There are multiple GH action warnings coming from our usage of these actions (Node.js version, `save-state`, `set-output`), so we need to replace these.
[dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) is maintained and is roughly a drop-in replacement (modulo one of two arguments to the action itself).
`clippy-check` seems to have been generally broken for us, since it [can't post lints as annotations back to the PR if it comes from a fork](https://github.com/actions-rs/clippy-check/issues/2) (which most of our PRs do). Instead, we can simply define the `cargo clippy` command directly in …
> ci: Replace unmaintained actions-rs GH actions

- .github/workflows/ci.yml
Specifying `macOS-latest` results in a GH warning that "macOS-latest pipelines will use macOS-12 soon. For more details, see https://github.com/actions/runner-images/issues/6384".
To clean up the warnings, let's just pin to macOS-12 for now.
> ci: Specify macOS-12 explicitly

- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
These properties(which were introduced in #6146) were leftover from testing the slide out feature and are not needed. Moreover, it causes sizing problems with certain scrollbars.
> Remove unnecessary style properties

- tensorboard/webapp/notification_center/_data_source/backend_types.ts
- tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts
- tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
The way we handle `Notification.dateInMs` continues to be confusing and error prone, despite attempts to address this in #5240.
The error case that hit us recently: If you set `dateInMs` to a day in the future, then the notication red dot will reappear every day until that day passes. (Note: #5240 only addressed problems when you set `dateInMs` to hours in the future, not days).
I propose we change the semantics of `dateInMs` to make it a little less error prone. It would now mean "do not show/notifiy this message until `dateInMs` or later".
The code filters out the notification at the TBNotificationCenterDataSource level.
To test, I imported the code into an internal repo and configured some notifications with `dateInMs` in the future. I verified that they do not appear until the time in …
> What's New: Do not show notifications from the future.

- tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts
- tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
- tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
These are some adjustments to how time series cards change size as their content changes.
The fundamental change is for the card-view to have a minimum height ('320px' in practice) but to otherwise allow the height of the card to be determined by the content of the card. Each card-view is enclosed in a card-space. The card-space grows in height with other card-spaces in the same row of cards. But the card-view is protected from this and continues to just maintain the height of its content.
We can think of each type of card to have an "always visible" portion of content. The "always visible" portion of each card also has a minimum height of '320px' but can grow if its card-parent's height grows, too.
* In the case of scalar cards, the "always visible" content is all content except the data …
> Step Selection: Make card size more responsive to card content.

- tensorboard/data/server/Cargo.lock
- tensorboard/data/server/Cargo.toml
- tensorboard/data/server/lib.rs
- tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Changes since 0.6.1:
* [Add Apple M1 Support](https://github.com/tensorflow/tensorboard/pull/5715)
* [Add Linux aarch64 support](https://github.com/tensorflow/tensorboard/pull/6101)
* [Use gcp_auth for GCP authentication](https://github.com/tensorflow/tensorboard/pull/5939)
the version numbers are 0.7.0.
> tensorboard-data-server 0.7.0

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
This is part of the Column Customization effort to allow for more columns in the scalar data table. This PR adds the actions which the Column Edit Menu will need when making changes.
These were tested in this [POC branch](https://github.com/tensorflow/tensorboard/compare/master...JamesHollyer:tensorboard:EditColumnMenu)
> Column Customization: Add Column Edit actions and reducers

- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_header_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_header_component.scss
- tensorboard/webapp/widgets/data_table/data_table_header_component.ts
- tensorboard/webapp/widgets/data_table/data_table_header_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
The goal here is to enable reusability for the data table headers. We want the column editor menu to display the headers in the exact same way as the headers themselves. This new component will be imported into that menu.
This simply creates a new component for the header and moves the logic from the data_table_component to the data_table_header_component.
There are not functional changes from this PR.
> Column Customization: Encapsulate data table header into separate component

- tensorboard/webapp/widgets/data_table/data_table_header_component.scss
In PR #6169 I introduced the DataTableHeaderComponent. This change was not supposed to have any affect on the UI. However, since the mat-icon was not set in that component it defaulted to a larger size than previously and that shifted some things around in an unwanted way. This remedies that.
Without the height set:
After this PR with the height set:
> Set mat-icon height in DataTableHeaderComponent

- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
- tensorboard/webapp/widgets/histogram/histogram_card_fob_controller.ts
- tensorboard/webapp/widgets/histogram/histogram_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_component.ts
This loosens the relationship between card-specific step selection and global step selection state. 
Before getting into technical details, here are some of the practial impacts:
* Linked time behavior remains unchanged. When linked time is enabled, changes in one card impact all other cards.
* When linked time is disabled:
* Changes to step selection in one card do not impact step selection in other cards. Even if you turn on/off step selection or turn on/off range selection.
* If you click the "Enable step selection" checkbox in settings to turn step selection on/off, step selection will turn on/off for all cards .
* If you click the "Enable range selection" checkbox in settings to turn range selection on/off, range selection will turn on/off for all cards.
There are three main changes …
> Linked time: Make card step selection slightly independent of global step selection state.

- tensorboard/summary/writer/event_file_writer.py
- tensorboard/summary/writer/event_file_writer_test.py
To address https://github.com/tensorflow/tensorboard/issues/6167
This is a bug fix for possible deadlock when writing events through `EventFileWriter`. The PR adds logic in `_AsyncWriterThread` to catch exception to propagate it to the calling thread and adds logic to `_AsyncWriter` to propagate exception raised in `_AsyncWriterThread`
New unit test that is not passing on master
* Instead of popping an item from the queue on exception, it's possible to make `wait`/`flush` methods re-check the status periodically
* Instead of raising an exception in the foreground thread, it's possible to ignore the raised exception altogether and just start dropping events
* It's possible to drop the data after it cannot be added to the queue for a certain period of time
> Fix EventFileWriter deadlock on exception in background thread

- tensorboard/webapp/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/main_view/BUILD
- tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
- tensorboard/webapp/metrics/views/main_view/main_view_module.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/BUILD
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_container.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_module.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
- tensorboard/webapp/widgets/data_table/data_table_header_module.ts
This is part of the larger column customization effort. This PR adds the actual menu which will be used to edit the columns.  This menu's current functionality includes displaying the columns for both range and single selection as well as checkboxes which allow the enabling and disabling of those columns. The dragging to reorder functionality will come in a later PR.
Side note: I renamed the fobState attribute in the dataTableColmnEdited action. This was supposed to happen in a previous PR but was overlooked.
The editor menu is added as its own component with it's own container. This follows the precedence set by the other components included directly into the MainViewComponent.
> Column Customization: Add Scalar Column Editor

- WORKSPACE
We inadvertently resolved #6115 via #6147, so we no longer need to pin to a maximum Bazel version of 5.4.0.
That said, I think it's still a good idea to retain a maximum compatible version, since Bazel major version upgrades have reliably resulted in our build breaking in the past. That way, when Bazel 7.0.0 arrives, we'll get a clean error message, and if we then try to remove the pin, we'll either be pleasantly surprised that it's fine, or we'll be expecting a build failure and know the cause (rather than encountering a build failure during a routine build, and then wasting time debugging before realizing Bazel was silently upgraded).
Putting this in place now also ensures this protection extends to older commits, rather than doing it reactively, which then relies on people syncing past …
> build: bump max bazel version from 5.4.0 to end of 6.x series

- WORKSPACE
- tensorboard/BUILD
- tensorboard/defs/protos.bzl
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/hparams/BUILD
- tensorboard/uploader/BUILD
This PR changes how we depend on the Python protobuf runtime library when running under Bazel. Now, we follow the same approach we use for depending on TensorFlow, numpy, etc and expect the package to be importable from the environment, non-hermetically. We introduce an `:expect_protobuf_installed` dummy target to facilitate syncing to our internal repository. (Note: this PR has no effect on the actual generated pip package, which has always imported `protobuf` from the environment in this way.)
Previously, when running under Bazel (e.g. `bazel test` or `bazel run`), the Python protobuf runtime was provided hermetically as part of the build via the target `@com_google_protobuf//:protobuf_python`. This target was used in two different ways:
- Our generated Python protobuf code (produced by …
> build: depend on protobuf runtime from pip rather than Bazel

- tensorboard/pip_package/requirements.txt
- tensorboard/version_test.py
Code in version_test.py relies on behavior of `pkg_resources.parse_version` in a way that was broken by changes in setuptools 66+ (see https://github.com/pypa/setuptools/issues/3772). The new logic throws an `InvalidVersion` exception when given a non-PEP440-compliant version, rather than returning `LegacyVersion`.  This PR updates our test to work with either behavior.
Test plan: ran test with both setuptools 65 and 66, and confirmed it now passes for both, rather than failing for 66.
> build: fix version_test.py to work with setuptools >= 66

- tensorboard/compat/proto/BUILD
- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/projector/BUILD
While working on #6186, I noticed that we have many files that import `protobuf` but don't have an explicit dependency on it (easy to have happen without strict deps enforcement). This adds those missing dependencies.
I generated all the changes in this PR with the following command, which essentially 1) finds all files containing a `from google.protobuf` import line, 2) uses bazel query to go from the set of files to the set of python BUILD targets that depend on those files, and then 3) uses buildozer to add the `expect_protobuf_installed` dep to those targets.
`buildozer 'add deps //tensorboard:expect_protobuf_installed' $(bazel query 'let files = set('$(git grep -l -E '^from google.protobuf')') in kind("py", rdeps(//tensorboard/..., $files, 1))')`
This has no actual impact on the open …
> build: add missing protobuf deps as implied by imports

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 2.12.0 release process:
Bump tb-nightly version to 2.13.0a0
Cherrypick of 2.12.0 relnotes added to RELEASE.md
> Post-release 2.12

- tensorboard/webapp/metrics/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/internal_types.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/BUILD
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_container.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
This is part of the effort to allow users to customize their data table. This PR adds the ability to drag headers in the editor around to change the order in the tables. 
Here is a screenshot taken mid drag:
> Column Customization: Add Scalar Column Editor Dragging

- tensorboard/webapp/testing/BUILD
This was breaking an internal sync (cl/5093062630)
Look it works
cl/509312933
> Bug Fix: Add sentinel build dependency to testing utils build rule

- .github/workflows/ci.yml
- tensorboard/tools/set_nightly_version.sh
- tensorboard/version.py
This addresses an issue we had with the `update_version.sh` script in the most recent release, where running it on a branch where the version number did not end in the placeholder `a0` produced an invalid version and caused CI to fail. We make two changes:
- Stop running that script (and building the pip package) if we aren't going to use the resulting pip package. Doing so just adds extra latency to the build, and we already do build and test the pip package as part of the CI earlier, so I don't think it adds meaningful coverage except for the version update script itself
- Make the version update script itself more robust by avoiding reliance on hard-to-read `grep` regexes with multiple non-capturing groups, and favoring just using Python and bash primitives. I made it fail with an …
> build: make nightly version update script more robust

- WORKSPACE
- tensorboard/webapp/metrics/actions/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
With the upcoming plans to make tensorboard links shareable we need to ensure the entire state is persisted to redux. In preparation for that I am adding card specific settings to redux which will help with rehydrating cards.
I'm adding the `tableExpanded` in preparation for #6200.
The current redux state contains a number of card specific mappings `Map<CardId, SomeDataType>`. This is starting to get clutterie and doesn't scale very well. To get around that I am adding new type `CardSettings` and a `Map<CardId, CardSettings>` to redux. Whenever a new card specific setting is added, this will be an easy place to add it.
None
Tests should pass, see #6200 for UI testing
> Linked Time: Add card specific settings to redux

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.scss
~Blocked by #6202~
The data table seems to be a popular feature but its limited size makes it hard to use. Given the current size is arbitrary I would like to add the ability to resize it dynamically.
Most of the changes in this PR are CSS updates. The exception is the expand / collapse feature which stores its state in redux.
* I updated the redux state to store more information about the state of each card (is it expanded) to ensure this feature is forwards compatible with the upcoming share feature.
New Drag Handles and a resize button
Resize button in action
Manual Resize + using the resize button
Big Card Mode
Resizing the chart
I did all the things in the gifs above
I explored lots of different placements for the expand/collapse button
I also explored adding the ability to hide the …
> Linked Time: Add lots of different ways to resize the data table

- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.ts
We are looking into building more hparam support in the timeseries dashboard. In order to make a more informed decision we want to log how often users are selecting other views from the plugin. Analytics are only available on our hosted services so there is some logic to do nothing when in OSS.
> Add HParam Plugin tab click telemetry

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
After #6200 merged, we noticed a handful of issues. Rather than revert, we've opted to patch forward. This is the patch.
[Scuba Before](https://scuba.corp.google.com/#/report/5aac4b0b-c8c3-4751-8aca-c1c0ab57891e?groupBy=Golden+Location&pageSize=25&pageIndex=0&selected_node=5aac4b0b-c8c3-4751-8aca-c1c0ab57891e&status=2
)
[Scuba After](https://scuba.corp.google.com/#/report/11258c25-5a3e-47fb-939b-979fceded566?groupBy=Golden+Location&pageSize=25&pageIndex=0&selected_node=11258c25-5a3e-47fb-939b-979fceded566&status=2)
Here are the issues we noticed:
1) The scalar card top padding was wrong.
2) Tables without many runs shrank when expanded.
3) Charts on full size cards did not expand if step selection was disabled.
4) Toggling a card to full size persisted settings incorrectly.
The top …
> Bug Fix: Fix regressions created by #6200

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
When none of the runs shown in a scalar card are selected, the scalar card is still shown. This is inconsistent with the image and histogram cards and is a generally poor experience.
For Googlers [b/241511328](https://github.com/tensorflow/tensorboard/pull/b/241511328)
This first PR just adds the action, reducer, and selector for the new setting. The setting will default to true.
See #6218 for usage
No changes
The tests should pass
> Feature: Add redux setting to control the visibility of empty scalar cards

- tensorboard/plugins/graph/graphs_demo.py
To avoid retracing every time one of the `tf.function`s are called, we should pass tensors instead of python literals as described [here](https://tensorflow.google.cn/guide/function#pass_tensors_instead_of_python_literals)
Fixes #6219
> Pass tensors instead of python literals for graphs demo

- tensorboard/plugins/graph/keras_util.py
- tensorboard/plugins/graph/keras_util_test.py
Currently, `keras_model_to_graph_def` throws `IndexError`s when there are multiple `inbound_nodes` for a layer that reference the same upstream layer (since each `inbound_node` specifies the index to look up in that layer). This is a quick fix to work around these `IndexError`s being raised, and isn't guaranteed to work perfectly for all potential cases. This ultimately seems to stem from the graph plugin not accurately tracking `inbound_nodes` when layers are added, but a complete refactor to handle this perfectly seems nontrivial.
Contributes to #6216
> Handle multiple `inbound_nodes` referencing a single upstream layer

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
On internal project of preserving settings, we rehydrate step index data from shareable link, however, the step index contains unloaded cards too. That is to say, that setting will be set to null here. This PR is to remove that condition.
Also manually inspect cardStepIndex state, the map slightly increase on card visibility change (increase on viewing more cards). This makes sense to me. No obvious issues noticed.
The downside is, we might store some unnecessary data in cardStepIndex, but now we don't have a way to tell whether that is necessary (in sharing) or not
> Shareability: Do not set cardStepIndex to null on no series data

- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts
- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
- tensorboard/plugins/hparams/tf_hparams_utils/tf-hparams-utils.ts
Googlers, see b/268530875.
An internal hparams user recently discovered that session groups with NaN values are not returned to the plugin in the results. (Note on terminology: A "session group" is effectively a row in the table of results). Therefore some rows were surprisingly missing from the hparams table results.
The root cause: The request from the client to the server was aggressively adding filters even for fields that were not being set. The server, as a side-effect, was filtering out NaN values for these fields.
This change modifies the request from the client to the server so that we only add a filter for fields that actually specify some sort of constraint in the left-hand panel. For example, we only send a filter for a discrete field if at least one of the discrete values is …
> Hparams: Add better support for session groups with NaN values.

- tensorboard/compat/tensorflow_stub/io/gfile_fsspec_test.py
Reverts tensorflow/tensorboard#6231
The upstream update to fsspec has been submitted, so we can re-enable this test.
> Revert "Temporarily disable fsspec glob test for sync"

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
There are a variety of issues caused by cards storing their step selection state without passing it to redux.
1) Pinned versions of cards lose their step selection
2) Adding another card using the comparison view resets all step selections
3) Shareable links cannot contain step selection information
The time selection is actually derived from a handful of other settings
* Linked Time Enabled + Linked Time Selection
* Step Selection Enabled
* Range Selection
* Min/Max step contained within a card
* Min/Max step that a user has set (by zooming, modifying the axis, etc)
* The actual step selection value stored in the card
Previously in #6172 I modified the redux state to ensure all these values can be stored in redux
In #6234 I started storing the step selection in redux
Now I am adding the …
> Linked Time: Start writing scalar card min max changes to redux

- tensorboard/webapp/metrics/internal_types.ts
Adjust xAxisType to string enum as it will be utilized for internal link sharing.
Number enum will cause mismatch on proto conversion.
Googlers, please see cl/515062969.
> Shareability: update xAxisType enum to string enum

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
On developing internal project (settings preservation), the series data loaded after we rehydrate preserved settings and that overwrites the state minMax. Therefore, we want to take the card state userMinMax into consideration. If it exists, we don't dispatch cardMinMax change.
Googlers please see cl/515750547.
Need to clean up tests once we remove minMaxStep$ from scalar card container.
Manually test and no significant errors found.
> Shareability: do not overwrite card state userMinMax if it exists

- tensorboard/webapp/experiments/types.ts
This attribute is used internally to determine if the experiment is active or hidden.
> Add state attribute to Experiment interface

- tensorboard/components/polymer/BUILD
- tensorboard/components/tensor_widget/BUILD
- tensorboard/defs/defs.bzl
- tensorboard/defs/internal/resource.bzl
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
This is part of an internal Large Scale Change(googlers see b/265933639).
In pr #4031 we switch from using the tools(host mode) to using exec_tools(exec mode). This was done as part of a Large Scale change(Googlers see b/163558320). This was always supposed to be a temporary measure until the host mode was switched to use python3 by default. That has now happened so we are switching back to using genrule.tools.
For reference, the difference between host and exec mode:
genrule.tools uses host mode, which ignores the py_binary.python_version attribute and always use Python 3
genrule.exec_tools uses exec mode, which respects the py_binary.python_version attribute (unless an upstream host
dependency forces all downstream …
> Chore: use genrule.tools again instead of genrule.exec_tools

- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
When scroll bars are fixed(which is optional on mac and default on linux) the "?" info icon shrinks. This fixes that icon to the correct size.
googlers see b/266229349
With fixed scroll bar
Before this change:
After this change:
Without scrollbar before and after:
> Add min-width to  info mat-icon

- tensorboard/webapp/BUILD
- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_container.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_container_test.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_module.ts
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.ng.html
- tensorboard/webapp/feature_flag/views/feature_flag_page_component.ts
- tensorboard/webapp/feature_flag/views/feature_flag_page_container.ts
- tensorboard/webapp/feature_flag/views/feature_flag_page_test.ts
As we add more feature flags it's starting to get hard to find them. This is particularly true when trying to help someone else find a feature flag in the modal.
The `enableShowFlags` feature was a weird edge case that wasn't being fully utilized. Now it supports string values. When a string value is supplied it filters the feature flags shown.
I changed the name and value of `enableShowFlags: boolean` to `showFlags: string`.
I then updated the `feature_flag_page_container` to filter the feature flags rendered based on the value of the `showFlags` feature.
Modal With a Filter
Modal without a filter
2) Navigate to localhost:6006
3) Assert the feature flags modal does not appear
4) Navigate to localhost:6006?showFlags
5) Assert the feature flags modal appears
6) Assert …
> Feature: Update the showFlags feature to allow filtering

- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts
When the differences between the max and min points on an axis are very small we use some special logic to make the axis tick marks more readable. However, this logic assumes the numbers to be decimal and gives NaN values when the numbers take on scientific notation. Fortunately more times scientific notation is used the number become small enough to use regular tick marks. This change simply reverts back to standard tick marks whenever javascript starts using scientific notation.
Before: 
After:
> Bug fix: Use Standard ticks when dealing with scientific notation

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/card_view_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
To be able to remember the fullsize mode settings, we need to have it in state and also take the value from
state as the source of truth for fullsize mode.
> Shareability: use table expansion from state for fullsize mode

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
See #6240 for why we are moving the step selector to redux.
When the linked time is enabled, card specific range selection overrides should be ignored.
None
1) Patch #6240
2) Start TensorBoard
3) Navigate to localhost:6006
4) Enable step selection on a scalar card
5) Enable step selection on a second card
6) Enable linked time
7) Add an end step to the second card
8) An end step should appear on the first card
> Linked Time: Use global range selection value when linked time is enabled

- tensorboard/data/server/cli/dynamic_logdir.rs
- tensorboard/data/server/gcs/logdir.rs
* Motivation for features / changes #6248 
As discussed in the original issue, running `rustboard` on a large number of tf event files can result in a OOM because of a larged, fixed size read buffer for each file.
Allow to configure the buffer size via the `TB_GCS_BUFFER_SIZE_KB` environment variable (buffer size in Kb).
```sh
> cargo build
> RUST_LOG=debug TB_GCS_BUFFER_SIZE_KB=1024 cargo run -- --logdir=gs://PATH/TO/MANY/FILE --reload-once
```
Could have been a CLI flag, see https://github.com/tensorflow/tensorboard/issues/6248#issuecomment-1476593312
> DEV: allow to set `rustboard` file read buffer size via ENV var

- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts
Currently in data table, large integers are shown in an abbreviated format e.g. 3.14e+6, which is not meaningful for numeric metrics such as `weight`.
Googlers, see b/274255386 and POC cl/518330666 for more information.
#oncall
> Increase precision for values in data table

- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/persistent_settings/_data_source/BUILD
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
We now have a way for users to customize which columns they would like to appear in their data table and in what order. However, we currently revert back to default on every page load. This change stores their selection in localStorage so that it persists a crossed sessions.
This just follows the same structure as all persisted settings in OSS.
> Column Customization: Persist Column Settings

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
See #6240 for context around why the step selector is being moved to redux.
Part of this has involved decoupling card specific step and range selection from the global values.
For Googlers see [internal test failures]( https://fusion2.corp.google.com/invocations/88e32921-2cbc-4924-9dcc-986ffaa5f6a2/targets/%2F%2Flearning%2Fbrain%2Ftensorboard%2Fservice%2Ftbcorp%2Fwebtests:linked_time_complex_test_chrome-linux/tests)
Whenever the global range selection value is changed, I remove all step selection overrides at the reducer level.
1) Patch #6240 
2) Start tensorboard
3) Navigate to localhost:6006
4) Enable global step selection
5) Remove the start fob from a scalar card
6) Enable global range selection
7) Ensure start and end fobs appear on all cards
> Linked Time: Remove step selection overrides when global range selection is toggled

- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/utils.ts
- tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
Now that the step selection is being read from redux I found a bug where the histogram card will show a linked time end step even if range selection is disabled. Note this could only happen if an end step was set a card.
I added another parameter to the observable that gets the value of the linked time selection in the histogram container card then conditionally removed the end value based on status of the global range selection setting.
Before
After
2) Navigate to localhost:6006
3) Add a start step to two different scalar cards
4) Add an end step to one of the scalar cards
5) Enable link by step
6) Ensure range selection is not enabled and that end steps are not shown on either card
7) Ensure only the start step is shown on histogram cards
8) Enable range selection …
> Linked Time: Update histogram card to show linked time end step based on global range selection

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
Linked time is supposed to make all cards mirror the state of the card most recently interacted with. Because cards can have range selection enabled locally we need to ensure the global value gets updated when linked time is enabled.
I updated the linked time toggled reducer to enable range selection globally if the linked time selection has an end value.
For Googlers: [internal tests all pass](https://fusion2.corp.google.com/presubmit/tap/518701168/OCL:518701168:BASE:518705279:1679528159833:1e20cf2f/targets)
See gif
2) Navigate to localhost:6006
3) Ensure global step selection is disabled
4) Add two fobs to a scalar card
5) Enable linked time
6) Ensure range selection is enabled globally
> Linked Time: Enable range selection when linked time is enabled while linked time selection has an end value

- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
This is simply a change to our code organization. In #6229 we decided to handle formatting the time selection in container layer, but that has become a bit messy so I'm moving it back to the selector layer
Rather than getting the cards time selection in the selector layer, then formatting it in the container layer, I'm opting to handle all the logic in the container layer.
None
I added lots of tests, all the tests should pass
For Googlers [internal tests passed](https://fusion2.corp.google.com/presubmit/tap/518714309/OCL:518714309:BASE:518717432:1679531577959:4d567b9a/targets)
> Linked Time: Move time selection formatting to the selector layer

- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Internal checks throw JSC_UNDEFINED_VARIABLE errors when using localStorage directly. However, window is defined so window.localStorage does not throw an error. This change helps us pass those checks internally.
> Chore: Prefer window.localStorage over localStorage

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
The current logic of calculating minMaxStep$ assumes data has existed. However, for Google-internal project, we might have other card state (userMinMax, timeSelection..) first then fetch time series data later. Then minMaxStep$ will not emit new values with "withLatestFrom". Therefore, this PR simply move that part above to assume we update minMaxStep$ on data loaded.
Googlers, please see cl/520194063 for demo.
Manually examine zoom and step selection, no serious issue found, it should not affect anything.
> Shareability: updates minMaxStep on data loaded 

- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
It's unclear when we'll be able to adopt TS 5. It is somewhat likely we'll run into some issues. These comments suppress some warnings from our internal code tooling about some incompatibilities with TS 5, in the meantime.
Googlers, see b/275900646 and cl/520430860.
> Adds @ts-ignore annotations for TS 5.0 errors.

- .github/workflows/ci.yml
Cargo ignores a crates `Cargo.lock` file unless the `--locked` flag is passes (http://github.com/rust-lang/cargo/issues/7169). We don't want transitive dependencies being updated in our CI, so explicitly specify `--locked`.
> Add locked flag to cargo install command

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/main_view/main_view_component.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_container.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_module.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
This PR adds a new affordance for opening the column editor directly from the card menu. It also adds a close button inside the editor.
* Screenshots of UI
I changes
> Column Customization: New affordances

- tensorboard/backend/event_processing/plugin_event_multiplexer.py
Executing event_exporter with `--root_dir=~/tensorboard-logdirs/my_test_dir` fails because gfile does not automatically expand the homedir tilde.
Explicitly expands the user directory before scanning subdirs.
Ran tests and attempted uploads using both alias and unaliased dir.
Played around with unit tests and gave up.  All our other tests put files in a tempdir, which is different from the homedir by definition.  Decided it wasn't worth playing with the tester's homedir or mocking it out.
> Expand tilde at the beginning of paths

- tensorboard/plugins/projector/vz_projector/scatterPlot.ts
When Shift key is used to select points and is released before mouseUp, UI does not exist selection mode after mouse is released, leaving a permanent rectangular selection box with no way of panning.
Reset orbit mode properly after mouse is released
> Embedding Projector: exit select mode onMouseUp

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
I found a couple of problems with scalar line chart rendering in Safari while investigating https://github.com/tensorflow/tensorboard/issues/6280.
* Safari 16.4 introduced limited OffscreenCanvas support. Notably it does not include 'webgl2' support. We have to be a bit more strict with our OffscreenCanvas feature detection to check for 'webgl2' support.
* Scalar line charts still would not render in either canvas or svg mode until the charts were resized manually. We have to adjust our CSS in order to convince WebKit to render the line chart with the space available to it. We use 'flex' for this.
* Testing
I tested in both Safari and Chrome that Canvas/Three.js and SVG rendering work (using forceSVG=false and forceSVG=true, respectively). 
I imported …
> Fix safari chart rendering issues.

- tensorboard/backend/client_feature_flags.py
- tensorboard/backend/client_feature_flags_test.py
- tensorboard/webapp/feature_flag/http/const.ts
Some plugins (e.g. [image](https://github.com/tensorflow/tensorboard/blob/963afb7be883c15373c121c96c9039828e3fb728/tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.ts#L356) and [audio](https://github.com/tensorflow/tensorboard/blob/963afb7be883c15373c121c96c9039828e3fb728/tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.ts#L111)) specify URLs as src attributes on some HTML elements, which precludes them from attaching the necessary client feature flags via the `requestManager`. This PR adds support to the client feature flags middleware to also accept feature flags via query parameters, so that we can support this use case.
> Add support for client feature flags to be passed as query parameters

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/types.ts
We are about to start working on a new feature to show hparams in the runs table and the scalar card data table and would like to control its roll out.
I added a new feature flag.
2) Navigate to localhost:6006?showFlags=hparams
3) Ensure the new feature flag is shown in the modal
> HParams: Add feature flag to control the rollout of the hparams in time series

- tensorboard/components/tf_backend/router.ts
Remove the ability to create and inject Polymer Router instances with customizations.
The customizations are no longer necessary.
* The`dataDir` argument may be a remnant of internal extensions of the Router that no longer exist.
* The `urlSearchParams` argument may be a remnant from when the polymer code had tests.
Additionally, the setRouter() function is no longer necessary as its Google-internal usage was recently removed.
Tested:
* There are no tests for the polymer code so this was tested by hand. I ensured the Scalars, Images, and Hparams dashboards all continued to work with these changes.
* Additionally I imported the changes internally and ran presubmit tests.
> Simplify Polymer Router implementation

- .github/workflows/ci.yml
Nightly Build broken after the pip 23.0->23.1 release
Found a newer version of the docs repo that doesn't exhibit the error and pinned to that version of the repo.
none
Creating the PR and seeing if it triggers the new workflow, in flight.
none
> Pin to a more recent docs repo to stop the pip 23.1 error message as part of the nightly build

- tensorboard/webapp/BUILD
- tensorboard/webapp/experiments/store/BUILD
- tensorboard/webapp/experiments/store/experiments_selectors.ts
- tensorboard/webapp/experiments/store/experiments_selectors_test.ts
As part of the effort to bring hparams to the time series dashboard a handful of new selectors need to be created. In particular I will be creating a new one to handle runs filtering by moving the logic out of the runs_table_container into the selector layer.
This will ensure filtered runs are consistent across the dashboard.
Getting a mapping of experiment id to name is a prerequisite for this.
Also the experiments tests weren't being run?
I created a new selector factory which takes in a list of experiment ids and creates a `Record<ExperimentId, ExperimentName>`
None
The tests should pass (note that the webapp experiments tests should be run)
> HParams: Add new experiments selector

- tensorboard/webapp/runs/data_source/runs_data_source.ts
The dashboard will not load when `inColab` is true because the runs data cannot be fetched.
Googlers see b/278706604 for why this is important
When `inColab` is true `POST` requests are automatically converted to `GET` requests see [tensorboard/webapp/webapp_data_source/tb_http_client.ts](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/webapp/webapp_data_source/tb_http_client.ts). This conversion assumes the provided body is of type `FormData`, however, when I open sourced `runs_data_source` in #6318 I was unaware of this conversion taking place and didn't modify the format of the post request body.
Before:
After:
2) Navigate to http://localhost:6006?tensorboardColab#timeseries
3) Assert that the dashboard loads
I could have updated the conversion …
> Bug Fix: Update runs_data_source to request hparams data using FormData

- tensorboard/webapp/hparams/_redux/BUILD
- tensorboard/webapp/hparams/_redux/hparams_selectors.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors_test.ts
As part of the effort to bring hparams to the time series dashboard a handful of new selectors need to be created. Rather than further the practice of creating selectors with props ([which is deprecated](https://ngrx.io/guide/migration/v12)) I am choosing to create them using the recommended solution of a selector factory. Unfortunately selector factories don't play nicely with selectors dependent selectors WITH props. There are a handful of hacky solutions to this problem but I am opting to create new dependent selectors using the factory pattern.
I extracted the result functions from the existing selectors, then created new factories which call them with an additional closured parameter.
None
Tests should pass
I could have just wrapped the existing selectors and then called them passing …
> HParams: Add new hparams selector factories

- tensorboard/plugins/projector/vz_projector/vz-projector.html.ts
Help button cannot be seen in dark mode
force white background so the button is visible
Before:
After:
turn on dark mode and verify the dialog button is visible
> Embedding Projector: fix dark mode button contrast

- tensorboard/plugins/projector/vz_projector/vz-projector-input.ts
The regex end slash and the regex button did not fit in the same line.
There should be a single suffix slot element that flex in the correct direction
Open the regex option in input
> Embedding Projector: fix regex suffix css

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
- tensorboard/plugins/projector/vz_projector/vz-projector.ts
When a bookmark state of loaded, it will contain data on a certain set of projections for some of points (B).
The app also has a different (current) state (A) in terms of which points are projected.
We should completely replace the App state (A) with the bookmark state B.
store/replace shuffledDataIndices for bookmarks
wipe out existing projections in app state
N/A
1. Export a bookmark that has a UMAP state
2. Refresh app, open UMAP panel and load in the previous state.
3. Verify only one set of 5k points are shown (as opposed to 10k points)
4. Refresh app, load previous UMAP state and adjust parameters to a new UMAP calc is performed
5. Verify only one set of 5k points are shown (as opposed to 10k points)
> Embedding Projector: fix bookmark projection state

- tensorboard/plugins/projector/vz_projector/bh_tsne.ts
- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
#6289
new tsne learning rate will take effect during next tsne iteration
N/A
1. Open t-SNE projection
1. Adjust learning rate
1. Verify a small learning rate will stall changes and a large learning rate will accelerate changes between iterations
> Embedding Projector: update tsne learning rate during iteration

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-legend.ts
Fix errors for gradient color map
When colorby gradient metadata is selected the UI currently not working as expected due to multiple errors that causes exceptions/bugs in UI.  
This fixes:
- gradient not getting rendered at all when there are no items
-  a race condition where the gradient color map would not get rendered
- linearGraident children does not get attached
- rendering issue with the end label when switching away to a categorical coloring
Before:
After:
Use the default Word2Vec 10k dataset
change `color by` from "No Color Map" to `count`
> Embedding Projector: fix gradient color map

- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
unlike t-SNE sampling message, the UMAP sampling message isn't hidden properly
Show UMAP sampling message only when number of points exceeds 5000
1. Change to Iris data set
1. Navigate to UMAP
1. verify the 5000 sampling mage doesn't show
> Embedding Projector: fix UMAP sampling message

- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.html.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.ts
Update UI inconsistencies in the inspector panel
Update minor styles
Reset button text when selection changed
Reset searchbox text when metadata or dataset changed
Before:
After:
1. Select some points
1. click out from selection
1. verify that the buttons reset
> Embedding Projector: fix inspector panel inconsistencies

- tensorboard/webapp/webapp_data_source/tb_http_client.ts
- tensorboard/webapp/webapp_data_source/tb_http_client_test.ts
In #6318 I ported over the runs_data_source from internal tensorboard in order to begin fetching hparams data in the timeseries dashboard. However, I later learned that it didn't play well with internal Colab which does not allow POST requests and thus had to revert the change in #6336.
The current implementation of this "hackaround" converts post bodies to query params and assumes that all post bodies are of type `FormData`. This does not work in this situation for two reasons:
1) HParams Plugin backend does not accept `FormData`
2) The [the hparams plugin](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/hparams/hparams_plugin.py#L191) only expects GET requests to have a query parameter titled "request" which is a serialized JSON object.
N/A
I considered …
> HParams: Update `tb_http_client` to support the hparams plugin backend

- tensorboard/webapp/metrics/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_container.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
When the Column Editor is opened from the scalar card it opens to whatever the default or last selected tab is. However, it would be expected to open to the mode that the card used to open it is in(Single vs Range). This makes that happen
This PR creates a new value in the metricsState(tableEditorSelectedTab) which reflects the selected tab in the table editor. It then pulls that value into the editor and uses it to select the tab. It is kept up to date with calls to tableEditorTabChanged (a new action created for this purpose) when the tab is changed inside the controller. 
Lastly it adds a new prop to the metricsSlideoutMenuOpened action which contains the current mode of the chart which dispatched the action. This mode is used to update the new tableEditorSelectedTab value.
> Column Customization: Open Editor to the expected tab

- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
This PR fixes a bug where the scroll bar would appear when it was not needed. It appeared because one of the divs inside the mat-tab-group did not grow properly which causes a slight bit of overflow.
Since the div which is not growing is built inside the mat-tab-group the only way to access it is to apply ng-deep
before
after
> Column Customization: Fix scroll bar appearing when not needed

- tensorboard/webapp/runs/data_source/BUILD
- tensorboard/webapp/runs/data_source/runs_data_source.ts
- tensorboard/webapp/runs/data_source/runs_data_source_test.ts
- tensorboard/webapp/runs/data_source/testing.ts
As part of the effort to surface hparams data in the time series dashboard we need to start actually fetching it. The logic existed internally but for some reason was not previously available in OSS.
I originally attempted this in #6318 but due to incompatibilities with internal Colab had to revert it in #6336.
The issue was that Colab does not allow `POST` requests and our method of mapping POST requests to GET requests didn't meet the expectations of the hparams_plugin backend.
I've improved the tb_http_client in #6337 to now work with the hparams_plugin backend so this should now be fine
I mostly copied the internal code to the oss implementation and made a few small adjustments to imports.
The biggest change is that I now utilize the `serializeUnder` parameter of our custom POST …
> HParams: Update tb_http_client to support the hparams plugin backend take 2

- tensorboard/plugins/projector/vz_projector/data.ts
Fix a bug with knn computation in projector
If we have 1000 points, and we sample 100 points, we cannot reuse the old knn computation because it could contain points that are not part of the sample.
N/A
1. Build and launch [projector](https://github.com/tensorflow/tensorboard/blob/bbc9e4f29a55d48478c3f23a7d80221b5b1b1e3c/tensorboard/plugins/projector/README.md)
2. Use default demo tensor (Word2Vec 10K)
3. Change projection type from PCA to T-SNE.  This should compute 10k sample points with 90 neighbors for knn.
4. Change projection type from T-SNE to UMAP.  You'll see a "Initializing UMAP..." screen loading indefinitely.   UMAP uses 5k sample points and 15 neighbors for knn by default
Verify the above step results in successful UMAP rendering after the changes are applied
> Embedding Projector: fix projector knn computation

- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
Internal TS compiler threw error "Property 'class' comes from an index signature, so it must be accessed with ['class']." This change fixes those errors.
tested internally. (googlers see cl/526813276)
> Access class property in acceptable way for internal TS compiler

- tensorboard/webapp/metrics/actions/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
For internal project, we want to preserve zoom, which is a two-dimension range. However, in current card state we only have x direction. This PR prepares the preservation by replacing "userMinMax"(type MinMaxStep) with "userViewBox"(type: Extent)
Googlers, please see cl/526116905 for full PoC and demo.
- update CardState type
- rename action `cardMinMaxChanged` to `cardViewPortChanged`
- additional handling on `getMinMaxStepFromCardState` selector
following pr: https://github.com/japie1235813/tensorboard/pull/30
Manually checked step selection on zoom interactions, they behave the same as expected.
> Shareability: preserve two-dimensional zoom range in state

- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
The code after `||` will not be touched since we have changed our "userViewBox" logic in this selector. Removed it.
Googlers, please see sync cl cl/488391097
> Sync: remove untouched condition

- .github/workflows/ci.yml
- RELEASE.md
- docs/what_if_tool.md
- tensorboard/BUILD
- tensorboard/components/BUILD
- tensorboard/components/polymer3_lib.ts
- tensorboard/default.py
- tensorboard/pip_package/requirements.txt
- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/wit_redirect/BUILD
- tensorboard/plugins/wit_redirect/__init__.py
- tensorboard/plugins/wit_redirect/tf_wit_redirect_dashboard/BUILD
- tensorboard/plugins/wit_redirect/tf_wit_redirect_dashboard/tf-wit-redirect-dashboard.ts
- tensorboard/plugins/wit_redirect/wit_redirect_plugin.py
- tensorboard/plugins/wit_redirect/wit_redirect_plugin_test.py
- tensorboard/tools/diagnose_tensorboard.py
- tensorboard/version.py
The [What-If Tool](https://pair-code.github.io/what-if-tool/) is no longer actively maintained and contains generated protobufs that are incompatible with the 4.x protobuf runtime. This patch release adds a dynamic plugin that redirects users to the actively supported [Learning Interpretability Tool (LIT)](https://pair-code.github.io/lit/) instead.
Cherry picks the dynamic plugin loader modification introduced in #6343 (and the necessary fixes in #6332 in for order for CI to run).
This PR contains four commits that will be rebased and merged into the 2.12 branch. The result will be released as TensorBoard 2.12.3 on PyPI.
> TensorBoard 2.12.3

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
- tensorboard/webapp/widgets/data_table/data_table_header_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
The goals is to allow for dynamic HParam columns in the data table. This means that we cannot have an enum like ColumnHeaderType be the unique identifier for the column headers because we cannot encapsulate all possible hparams into an enum.
This change adds a name and displayName field to the ColumnHeader interface. The goal here is to make name be the unique identifier for columns. However, this PR does not use these fields at all. It simply adds them. THERE IS NO FUNCTIONAL CHANGE in this PR.
Upcoming changes will switch the code over to start using the name as the unique identifier and display the displayName. 
(For POC to see how this change fits in googlers see cl/526767686)
N/A
POC works
There were many alternatives considered. In fact I do not believe this is going to be the final …
> HParam UI: update ColumnHeader type

- tensorboard/plugins/image/summary_test.py
- tensorboard/plugins/image/summary_v2.py
The vectorization unblocks running tf.summary.image under DTensor.
Vectorization of EncodePNG is added in https://github.com/tensorflow/tensorflow/commit/7c422273dc560005c82cd0a91875ddfbb41b9791
Applied a forward compatibility wrapper for 14 days since the EncodePNG change landed.
Verified by both branches work without DTensor, and the new (vectorized) branch works under DTensor.
Note that I manually applied the internal patch to the OSS format. 
N/A
cl/488391097
> Start using the vectorized EncodePng Op

- tensorboard/webapp/runs/store/runs_selectors.ts
- tensorboard/webapp/runs/store/runs_selectors_test.ts
As part of the effort to bring hparams to the time series dashboard a handful of new selectors need to be created. In particular I will be creating a new one to handle runs filtering by moving the logic out of the runs_table_container into the selector layer.
This will ensure filtered runs are consistent across the dashboard.
This new selector is not meaningfully different from the existing one but the factory allows it to be called with an encapsulated experiment id.
> HParams: Add new selector factory to get runs from experiment ids

- tensorboard/webapp/widgets/data_table/data_table_header_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_header_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
In #6346 we added a displayName attribute to the ColumnHeader. This PR uses that name to be displayed in the headers.
I removed lots of headers from a test since now we do not need to test that each type has the proper text displayed.
> HParam UI: display the displayName

- tensorboard/webapp/feature_flag/directives/feature_flag_directive.ts
Internal end-to-end tests are failing due to the async nature of the directive leading to attributes not being set before validation occurs. This forces change detection to occur after the href/src are updated.
> Update feature flag directive to fix internal tests

- .github/workflows/ci.yml
- RELEASE.md
- tensorboard/compat/proto/BUILD
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/coordination_config.proto
- tensorboard/compat/proto/graph.proto
- tensorboard/compat/proto/graph_debug_info.proto
- tensorboard/compat/proto/proto_test.py
- tensorboard/compat/proto/struct.proto
- tensorboard/version.py
The TensorBoard release that tracks the TF 2.13 release.
* Update TensorFlow protos as part of the 2.13 release.
* Pin the TF version for CI (to `tf-nightly=2.13.0.dev20230501`)
The proto updates were made by manually copying and editing the new file then updating the remaining files according to  [these intructions](https://github.com/tensorflow/tensorboard/blob/b6afe57af75636eaa61081f8f0e9636036aad4c8/tensorboard/compat/proto/proto_test.py)
> TensorBoard 2.13.0

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
These new properties break internal sync as the components which use ColumnHeader do not have these properties.
I will make them required again once internal uses are changed.
Googlers see cl/508442178 for sync test.
> Temporarily make new ColumnHeader properties optional for sync

- tensorboard/data/server/BUILD
- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Take userViewBox in state and apply on scalar line chart.
- Select `userViewBox` from state and pass all the way down to `line_chart_component`
- Update `userViewBox` in state on line chart zoom (includes reset view box)
- Set `userViewBox` to null when view box is rest. This saves the effort of checking viewBox and userViewBox equivalence to determine correct `isViewBoxOverridden` value
- In `line_chart_component`,
- `userViewBox` might be updated before data series change coming in, thus we need `userViewBoxUpdated` variable to mark until next `updateLineChart()` being called. (otherwise `isViewBoxOverridden` will not be updated correctly and have unwanted disabled behavior of reset icon)
- On the case of user view box is the same as data extent, explicitly sets `userViewBox` to null …
> Shareability: introduce userViewBox in scalar and lineChart

- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
In #6346 we updated the ColumnHeader interface. However, objects using this interface are stored in localStorage. This checks localStorage to ensure it has the new interface. If it does not then it ignores those values.
I am simply checking if the first value has the name property to ensure the values are valid. I could do a more thorough check but it seems unnecessary. 
It worked for me when running locally.
> HParam UI: reset ColumnHeaders if using obsolete interface

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
We are changing single step selection to default to the maximum step. We think this is more useful than making the default the minimum step.
This also means that when step selection changes from single selection to range selection, the minimum value of the chart is added as the start of the range and the previous single step now becomes the end of the range. Similarly, when step selection changes from range selection to single selection, the new single selection is the previous maximum value of the range.
Where default value is set to "min" step, instead set it to the "max" step. Where range selection is enabled, ensure the new start of the range is the "min" step.
I have three internal CLs that accompagny this change.
* cl/528745120 adjusts or comments out code to allow the import to …
> Use maximum step as default for single step selection.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
These attributes were added in #6346. There were then made optional in #6369 to fix sync issues. The internal issues have now been resolved and this changes them back to required fields.
> Require new ColumnHeader attributes

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/main_view/BUILD
- tensorboard/webapp/metrics/views/main_view/common_selectors.ts
- tensorboard/webapp/util/BUILD
- tensorboard/webapp/util/memoize.ts
- tensorboard/webapp/util/memoize_test.ts
Using non memoized selector factories can lead to awkwardness in tests and slightly lower performance in general.
None
We could have used a library instead (for example lodash) but the typing wasn't as good.
> Add new memoize utility and use it to memoize selector factories

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/backend_context_test.py
The backend_context_test.py has, for historical reasons, mocked its data dependencies at the "multiplexer" level. When backend_context.py was migrated to use DataProvider interface in 2020 (See #3425), its tests weren't fully converted to mock data dependencies at the "DataProvider" level.
We will soon be adding more logic to hparams/backend_context.py and it would be convenient to mock data dependencies at the "DataProvider" level instead of the "multiplexer" level. This PR updates existing backend_context_test tests so that they mock at the "DataProvider" level.
The refactor can be done fairly cleanly - only one of the tests need to be updated directly. Otherwise it is just the helper functions that need to change.
> Refactor backend_context_test to use DataProvider mock.

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
The timeSelectionCleared() action is unused except by the reducers.
> Remove unused timeSelectionCleared() action.

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/get_experiment.py
- tensorboard/plugins/hparams/list_session_groups.py
Use the result from a DataProvider.list_hyperparameters() call to generate HparamInfos for operations in the Hparams plugin. Generate the HparamInfo name, display_name, data_type, and domain from each Hyperparameter.
We use the same two-step strategy for generating these as is done with tensor-based hparams. The tensor-based hparams has one operation, `hparams_metadata()` for retrieving the tensor data, and then passes the result to `experiment_metadata()` to generate the HparamInfos and MetricInfos. Similarly, we add an `hparams_from_data_provider()` operation for retrieving the hyperparameter data and we pass the result to `experiment_metadata()`.
Note: We don't yet generate `MetricInfos`. We don't yet have enough information from the data provider.
Note: We don't yet merge the new …
> Hparams: Use DataProvider.list_hyperparameters() to generate HparamInfos

- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
- tensorboard/webapp/persistent_settings/_redux/persistent_settings_actions.ts
- tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts
- tensorboard/webapp/persistent_settings/index.ts
- tensorboard/webapp/settings/_redux/settings_reducers.ts
The current action name "globalSettingsLoaded" is actually about persistent settings, rename to make it clear.
Still preserves an extra export of "globalSettings" to not break sync and fix everything all at once.
> Cleanup: rename globalSettings to persistentSettings

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
This has been a bug for a while that we only noticed now that hparams are being used to filter runs in the time series dashboard.
Googlers see https://chat.google.com/room/AAAA03izhrk/VyyPgojcNvY for context on how this was discovered
Boolean HParams were not having a domain set. This lead to the ui treating them as intervals, however, this lead to incorrect filter conditions. We currently treat all non number values being filtered this way as not matching (the alternative would be to treat them all as being true which also seems wrong). This leads to all runs with a value for a boolean hparam being filtered out.
Googlers see cl/532932348
This could have been done on the client but ideally the bug would be fixed in other places where the api is being used.
> Bug Fix: update hparams plugin to generate domains for boolean hparams

- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_test.ts
This probably should have been done when the data table was created. html table is generally considered old technology. Building tables with divs is preferred as it allows for more flexibility. 
Pretty straight forward swap to using display table, table-row, table-column instead of table, tr, td. For the header we use a \<header\> to wrap it and still use the .col. Because of this header specific logic for .col was moved inside the header object.
I also had to mess around with the row-circle class to get the color circle to align properly because the display is now table-cell instead of flex.
New table looks like this.
The only change is that the circle icon moves ever so slightly(to see the difference more clearly googlers can check the screenshot diffs here cl/529831620).
A couple CSS …
> Data Table: refactor data table to use divs instead of html table

- tensorboard/webapp/core/store/core_reducers_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/notification_center/_redux/notification_center_reducers_test.ts
- tensorboard/webapp/persistent_settings/_redux/persistent_settings_actions.ts
- tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects_test.ts
- tensorboard/webapp/persistent_settings/index.ts
- tensorboard/webapp/settings/_redux/settings_reducers_test.ts
Remove globalSettingsLoaded action export once all internal actions have been renamed.
Googlers, see cl/532908969
> Cleanup: remove globalSettingsLoaded action

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
We have been discovering issues with the way the hparam domains are defined. This has lead to issues due to #6377 causing scalar cards to appear empty when one of these issues occurs. I attempted to fix this in #6393 but missed the situation where a string type hparam with more than 10 values returns an empty domain (Googlers see tb/3183400180427144287 for an example).
I am moving the new filtering logic added in by #6377 behind a flag while we fix this issue on the backend.
Screenshots for Googlers only
Before: https://screenshot.googleplex.com/AELb2oHqhxa8UNF
After:
Feature Flag Enabled: https://screenshot.googleplex.com/AcPxsbNNXSSFGx9
Feature Flag Disabled: https://screenshot.googleplex.com/3aEXpfHrGZdzYgZ
> HParams: Only filter scalar card runs by hparams when `enableHparamsInTimeSeries` is `true`

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/data_table/types.ts
For the HParam work that is being done we are now using the name field as the unique identifier for columns. Therefore the SortingInfo interface needs to use name and not header. However, making the hard swap to using name would break sync so it is happening in stages. The name switch to using names happened in #6362. However, we had to make name optional for sync reasons. Googlers see cl/534097086 to see where name was added. Now this PR makes header optional. I will then make an internal change to remove it. Then I can finally submit a final PR which removes the property entirely.
> Continue moving to use name in SortingInfo

- tensorboard/webapp/metrics/store/BUILD
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
As part of the effort to add hparams into time series we would like to be able to determine the columns to be shown at the selector layer. To that end I have added a new selector which, given a card id, returns the appropriate columns to be shown.
Single Selection (its the same)
Range Selection (it's also the same)
> HParams: Update scalar card to show columns based on selector

- tensorboard/webapp/widgets/data_table/data_table_component.scss
The sort icons should turn white in dark mode. This seems to be a bug with material icons having set the fill attribute of the svg path to black for the down arrow icon.
The up arrow (which works)
The down arrow (which does not)
Before
After:
We are using the icon from version 3.0.1 but when I checked version 4.0.0 (the newest) the problem had not been fixed.
> Bug Fix: Fix data table icons in dark mode

- tensorboard/webapp/theme/_variable.scss
Googlers, see cl/537831311, which requires a placeholder be added to the code to _variable.scss in order for a new import transform to be applied.
> Chore: Add placeholder for internal import of deprecated styles.

- tensorboard/plugins/graph/tf_graph_common/graph.ts
A zero dimension tensor results in a proto with an empty `size` field, as seen below:
```
node {
name: "input/b"
op: "IO Node"
attr {
key: "attr"
value {
s: ""
}
}
attr {
key: "_output_shapes"
value {
list {
shape {
dim {
size: 1
}
dim { <<<
}
}
}
}
}
}
```
This results in `dim.size` returning null for these particular cases, breaking graph rendering. We update to default the null case to 0.
Fixes #6418
> Fix graph rendering issue for tensors with zero dimension size

- tensorboard/webapp/BUILD
- tensorboard/webapp/widgets/custom_modal/BUILD
- tensorboard/webapp/widgets/custom_modal/custom_modal_component.ts
- tensorboard/webapp/widgets/custom_modal/custom_modal_module.ts
- tensorboard/webapp/widgets/custom_modal/custom_modal_test.ts
This is intended to be used with #6412 and the custom context menu we intend to build in the future.
See #6412 for screenshots of a component being projected inside this.
* `MatDialog` does not have all the built in logic to handle closing when clicking outside if the background is not enabled.
* `MatDialog` seems to have issues with form components? (I consistently get errors related to property changes when I open it)
* Content projection provides a nice declarative way of showcasing the what should appear in the modal.
* This is additional code we have to maintain
* Clicking someplace else where event propagation is disabled will not result in the modal being closed.
> HParams: Add custom modal widget

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.ts
- tensorboard/webapp/widgets/data_table/header_cell_component_test.ts
This refactoring allows more customization of the data table which will be used by both the runs table and scalar card. This allows the parents(like the runs table) to add functionality to the header component such as the color pallet and select all checkbox. 
This change pulls out the header cells from the DataTable and allows the parent component to project them back down. We add a HeaderCellComponent which is used keep consistency and allow the DataTable to still keep the logic which should be on all tables such as dragging and sorting. This is done by using event emitters in the HeaderCellComponent which the DataTable subscribes to.
The Scalar table has no changes.
This does break the runs data table which is still behind a flag. This will be fixed in a follow up.
Ran it and clicked a …
> HParams: project header cell components

- tensorboard/webapp/widgets/custom_modal/BUILD
- tensorboard/webapp/widgets/custom_modal/custom_modal_component.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/column_selector_module.ts
It seems like the linter is no longer catching unused variables so that part was easy.
There was also an issue with the a missing build rule remapping
~Sync should pass after cl/538963303 is submitted. See example sync cl/538963353~
It really did pass cl/539096814
> Clean Up: Fix sync breakage due to import inconsistencies

- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/data_table/header_cell_component_test.ts
The errors from using the regular MatIconModule in the test file does not effect the test. However, they do produce a lot of error logs. This eliminates those error logs which helps a lot when debugging.
Just a simple swap for our internal MatIconTestingModule which is used elsewhere and should have been used here from teh start.
> Clean Up: Use MatIconTestingModule in data table test

- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
Not recommended to put a click event on an icon because it has accessibility problems, so this change aims to address that.
Wrap the delete icon in a <button> and have the on click component from the button and not the icon. 
N/A
> Data table delete button accessibility

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/content_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/content_cell_component.scss
- tensorboard/webapp/widgets/data_table/content_cell_component.ts
- tensorboard/webapp/widgets/data_table/content_cell_component_test.ts
- tensorboard/webapp/widgets/data_table/content_row_component.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/data_table/header_cell_component_test.ts
This is part of the effort to use the data table widget in the Runs table which will allow for lots of code reuse as we add HParam functionality to both tables. To allow more customization in each table this PR pulls all the table content out of the data_table_component and allows users to project it using the new content_row_component and content_cell_component.
Created new content_row_component and content_cell_component. The row is extremely basic and basically just wraps the content inside a table-row. The content_cell_component take all the logic for formatting each cell. To customize the content users of this component can simply pass in no datum or a ColumnHeaderType that does not have a specified way to format in the getFormattedDataForColumn function and then put the custom …
> HParams: project table content components

- tensorboard/webapp/BUILD
- tensorboard/webapp/testing/mat_icon_module.ts
- third_party/js.bzl
We need these new icons to expand and collapse the runs table for the hparams in time series feature.
See #6408 for how icons are added
> Add left and right arrow icons

- tensorboard/webapp/core/actions/core_actions.ts
- tensorboard/webapp/core/store/core_reducers.ts
- tensorboard/webapp/core/store/core_reducers_test.ts
- tensorboard/webapp/core/store/core_selectors.ts
- tensorboard/webapp/core/store/core_types.ts
- tensorboard/webapp/core/testing/index.ts
Once we have added a bunch of more columns to the runs table we foresee users wanting to make the table full screen.
* I am not adding a test for the selector given it has no logic. This is as per a previous offline discussion
* It will not be possible to drag the runs table to full screen with this implementation, but if we decide to add support for that, it should be fairly simple.
> HParams: Add redux logic for making the runs table full screen

- tensorboard/webapp/runs/views/runs_table/BUILD
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
We preparation for adding HParam functionality to both the Scalar Table and the Runs Table we have refactored the Data Table to be more flexible. This refactoring was done in #6422 and #6427 and was only implemented in the Scalar Table because the Runs Table only uses the Data Table behind a flag. This PR implements the new Data Table Structure in the Runs Table.
Basically just followed the same structure as the Scalar Table.
Runs Table specific styling still needs to be done. It currently looks like this.
We still need to add a column for check boxes and add styling.
> HParam: Implement new Data Table projection architecture in Runs Table

- tensorboard/webapp/app_routing/internal_utils.ts
- tensorboard/webapp/app_routing/types.ts
Adds a new route which will be used later for internal embedded card project.
Googlers, please see cl/540654482 for the internal route CL.
This change adds a new route type CARD.
> Embedded Single Card View: add card route type

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/types.ts
In #6438 we rewrote the Runs Data Table to use the new projection Data Table structure(Created in #6427 and #6422). This allows us to project custom controls such as the run selection check boxes. This PR implements those checkboxes.
Pretty straight forward use of projection. The weird part was that the projected checkbox in the header did not fire the "change" event while the header itself had a subscription to a "click" event for sorting. The solution was to subscribe to the "click" event and that seems to work just fine.
All selected:
Some selected:
None selected:
> HParams: Add selected checkbox column to Runs table

- tensorboard/plugins/projector/vz_projector/data-provider-demo.ts
- tensorboard/plugins/projector/vz_projector/data-provider.ts
- tensorboard/plugins/projector/vz_projector/util.ts
When an error occurs user gets stuck with a modal that can't be dismissed.
show a proper error modal that can be dismissed.
1. Open Word2Vec 10K
2. open t-SNE
3. open UMAP
4. see this error
> Embedding Projector: show error on task failure

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html.ts
fix broken/inconsistent tooltips
Some places tooltips aren't showing up (Spherize), some place we have two tooltips show up
Before:
After:
Hover over tabs and Spherize option, verify things show up as expected
> Embedding Projector: fix tooltips

- tensorboard/webapp/metrics/internal_types.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
With the addition of hparam columns header type is no longer guaranteed to be unique, thus we are changing everything to use header name instead.
While making the change I also made some small refactors to remove usage of header type from the column editor as well.
I can still remove columns
I can still add columns
> HParams: Update remove header to use header name

- .github/workflows/ci.yml
We're seeing issues in CI with pip's hash-checking logic failing on `tf-nightly`, and that same error mentions that pip is stale (see example error at end). There are a few mentions of hash-checking in the release notes so it seems plausible that the old pip version is somehow incompatible with how pip downloads are resolving in our CI environment.
This PR resolves that by upgrading pip before installing TF, the same as we do before installing our own requirements.txt file (we still keep that upgrade to handle the no-TF case; I could conditionally omit it but it'd be more complex and I expect the second pip upgrade will be a fairly quick no-op).
```
Collecting tf-nightly==2.13.0.dev20230426
Downloading tf_nightly-2.13.0.dev20230426-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl …
```
> ci: update pip to latest before installing TF

- tensorboard/webapp/runs/views/runs_table/BUILD
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
We are trying to reach feature parity with the new RunsDataTable. This is a new table structure which will allow us to add many new custom columns and make the table more useful. This PR links up the color objects with the controls that were already there for the old runs table.
Pretty straight forward copy of the old functionality in the RunsTableComponent.
> HParams: Add runs data table color controls

- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/widgets/data_table/content_cell_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
We are replacing the RunsTableComponent with a RunsDataTable which uses the DataTable Widget. We have been making it functional but this trying to style the table to look similar the original table.
> hparams: Style Runs Data Table

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
We will soon replace the RunsTableComponent with the RunsDataTable which will allow for more customization in the columns. However, we first need to reach feature parity with the current component. We are missing the regex filter. This adds that filter.  There is still more work needed to filter out the runs which are deselected from this filter. That will come in a later PR.
I just copied the component from the RunsTableComponent and used the same inputs and outputs.
I think the current testing for the component is sufficient. The only thing we could test is that the filter renders in the RunsDataTable. It does not seem like a valuable test to me.
> hparams: Add regex filter control to RunsDataTable

- tensorboard/webapp/core/views/layout_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
Somehow some tests got broken on master and caused nightly to fail
https://github.com/tensorflow/tensorboard/actions/runs/5377348327/jobs/9755711856#step:11:2529
> Chore: Fix broken tests

- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
We are building some new hparams-related functionality internally. It is early stages and the data we return to the UI does not contain metrics. The hparams dashboard, however, requires `metricInfos` to be non-empty in order to show the main view of the dashboard. We want to show the main view despite not having metric data.
More generally, though, it doesn't seem like metric data should be a requirement to show hparam dashboard information. The hparams fields can still be valuable on their own.
Remove a UI-level check for non-empty metricInfos.
> Remove requirement that metricInfos are present to show Hparams main view.

- tensorboard/data/provider.py
provider.Hyperparameter's 'name' and 'display_name' properties should be required rather than defaulting to empty string "".
> Require some provider.Hyperparameter properties.

- tensorboard/data/provider.py
In https://github.com/tensorflow/tensorboard/pull/6383 we introduced the notion of Hyperparameter to the DataProvider interface and a function that allows to provider for hyperparameter metadata - list_hyperparameters().
This PR extends that work to include a read_hyperparameters() function. This function can most easily be thought of as the function that provides the data for the main pane of the hparams dashboard.
> Declare DataProvider.read_hyperparameters()

- tensorboard/webapp/runs/actions/runs_actions.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
The dragging functionality was all in place except it never fired an action to actually change the order. This PR creates the reordering action/reducer and hooks up the orderColumns event with that action.
As in the Scalar Table be re-ordering we actually just replace the entire list of headers with a new one. I am not a huge fan of this. I would like to change how this works sometime but that is beyond the scope of this PR.
I considered refactoring the orderColumns events to just return source and destination indexes. However, I decided that was too big a change ATM. I think it should be done sometime in the future.
> HParams: Order RunsDataTable Columns on drag

- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/widgets/data_table/content_cell_component.ts
- tensorboard/webapp/widgets/data_table/types.ts
When comparing two experiments another column should be added showing the experiments name. This is a feature that we had not implemented in our replacement for the runs table.
I added an additional reducer which is called upon navigation which checks if the current route is a comparison route and then potentially adds an experiment name column.
Screenshot from internal
> HParams: Add experiment name column

- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
As part of adding hparams columns into the data table we have added a context menu with a lot of additional options. Because we were worried about users finding the context menu we decided to add it a button to trigger it to the header as well. 
We've got a lot of icons in the header now...
> HParams: Add button to header cells which triggers the context menu

- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component_test.ts
The styling on the remove button was broken by one of the recent changes to the column header. I am fixing and improving it.
Dark Mode
Light Mode
> HParams: Restyle remove column button

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
This boolean was removed in #6463. However, I forgot to remove it from being passed in the ScalarCardDataTable. This was caught in an internal build.
> HParams: Stop passing controlsEnabled boolean to DataTable

- tensorboard/plugins/hparams/list_session_groups_test.py
Note that this is similar to #6386.
The list_session_groups_test.py has, for historical reasons, mocked its data dependencies at the "multiplexer" level. When list_sessions_groups.py was migrated to use DataProvider interface in 2020 (See https://github.com/tensorflow/tensorboard/issues/3425), its tests weren't fully converted to mock data dependencies at the "DataProvider" level.
We will soon be adding more logic to hparams/list_sessions_groups.py and it would be convenient to mock data dependencies at the "DataProvider" level instead of the "multiplexer" level. This PR updates existing list_session_groups_test tests so that they mock at the "DataProvider" level.
The refactor can be done fairly cleanly - just the helper functions need to change.
> Refactor list_session_groups_test to use DataProvider mock.

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html.ts
The delimiter got lost compared to projector.tensorflow.org
In the upload dialog example, show tab delimiters correctly
Click on Upload to see this
> Embedding Projector: Upload dialog example delimiter fix

- tensorboard/webapp/widgets/custom_modal/custom_modal_component.ts
We have been creating context menus using our custom modal component. The custom modal component had the height of the header hard coded as a vertical offset, however, the header is not the same height in internal tensorboard so the offset needs to be set programatically.
In OSS
In Internal
> HParams: Change strategy for positioning context menus

- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
This is a bug fix. When removing a column via the context menu the context menu should immediately close.
It closes now
> HParams: Close the context menu after a column is removed

- tensorboard/webapp/runs/store/runs_reducers.ts
The experiment name column should always have been movable and sortable but it was created before those properties existed and didn't get updated until now.
> HParams: Make experiment name column sortable and movable

- tensorboard/webapp/widgets/custom_modal/custom_modal_component.ts
- tensorboard/webapp/widgets/custom_modal/custom_modal_test.ts
It was possible to open a context menu which would overflow the page. This actually lead to a strange CLS issue which looked pretty bad. Now the custom_modal component will check the size of the content once it has rendered and adjust its position to ensure it fits in the page.
The context menu never overflows the window
This also works at the bottom of the page but it doesn't come across as well in a screenshot
> HParams: Bug Fix - Ensure context menu always opens within the window

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.ts
- tensorboard/webapp/widgets/data_table/header_cell_component_test.ts
While testing the new hparams in time series feature we got a lot of feedback about the styling and placement of the header buttons.
The main takeaways are:
- Remove the "Delete Column" button
- Ensure the icons are the same height and color
- The 3dot button ripple was weird
We also noticed that the sort button was missing from the context menu and discovered that right clicking a header cell logged an error to the console
Header Buttons (Dark Mode)
Header Buttons (Light Mode)
Context Menu (Dark Mode)
Context Menu (Light Mode)
No context menu in scalar card
> HParams: Header Button Styling and Context Menu updates

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
The select all checkbox very often got into a bad state where it showed checked when it should show unchecked and vice versa.  This fixes that bug.  I could not get the tests to reproduce the issue so I could not write a test to ensure it does not happen again.
I could not completely nail down why this was happening. This does fix it though.
Before:
After:
> HParams: Prevent select allheckbox from its default behavior

- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
We will soon be flipping the flag to enable the RunsDataTable. However, this new table does not work on the hosted experiments list page. This allows that page(which is internal only) to force the runs table to use the old table so we do not break that feature.
I ran this code internally first and used it to fix the problem. Then copied it out to OSS.
> HParams: Allow an input to force use of legacy table

- docs/tensorboard_projector_plugin.ipynb
There is a broken image link.
Removing the reference.
N/A.
The original image:
https://github.com/tensorflow/docs/blob/f957ee6185e5b2135da5c3d3f8ba0c429794ebe1/site/en/tutorials/text/images/embedding.jpg
Was removed as part of: 
https://github.com/tensorflow/docs/commit/d16e549c837c7a268c9e8d866e886164aac86d2d#diff-31e6e93b3e0ec43331ea20072ef374ae4fe5c86f6600c794fd3ae333dd789f20
Considered copying over the old image, but I see the new docs use a different image format, and that the examples in the current notebook are very similar to the initial image.
> Removing missing image reference

- tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.ts
There is a broken link on the projector dashboard page.
Updating it with the newest version.
N/A.
Accessing an empty projector dashboard page.
Instead of using the `compat` link, figure out what the new way should be and link in there.
> Fixing broken link in projector dashboard

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
We will soon be replacing the RunsTableComponent with the RunsDataTable. In an effort to reach feature parity with the current runs table this PR implements the dblClick functionality of the selected check boxes. When the checkboxes are double clicked it has the effect of selecting this and only this run.
I implemented the dblclick logic differently than the RunsTableComponent. I utilized the MouseEvent details property to decide if a click was a click or a dblclick. This stops the click from firing both the onSelectionToggle and the onSelectionDblClick events for a single click.
> HParams: Implement selection checkbox double click

- tensorboard/webapp/widgets/data_table/column_selector_component.ts
- tensorboard/webapp/widgets/data_table/column_selector_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ts
This fixes a bug. These key presses are subscribed to at all times. Therefore clicking enter anytime would add an HParam to the runs table. 
I simply added a boolean isActive to track the state of the ColumnSelector. If it is not active I ignore the key presses.
> HParams: Ignore key presses in ColumnSelector when not active

- tensorboard/data/provider.py
The DataProvider abstract base class is changed to have simple implementations of both list_hyperparameters() and read_hyperparameters(). This is to accomodate TensorBoards' DataProvider implementations that do not currently implement these operations. We return empty lists in both operations.
> Hparams: Return empty lists for DataProvider hyperparameter operations.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
- tensorboard/webapp/widgets/data_table/content_cell_component.ts
- tensorboard/webapp/widgets/data_table/types.ts
The Experiment column in the current runs table uses the tb-experiment-alias widget to nicely display the experiment alias and alias number. Our RunsDataTable simply displayed the experiment name. This changes the RunsDataTable to use the same tb-experiment-alias widget in its Experiment column.
Since the ExperimentAlias interface does not conform to the TableData value which is defined as string|number|boolean. I had to add object as an option. Values that use an object require specific logic for sorting. I added that logic into for the experimentAlias. I also added a place for that logic if an object is ever used in the Scalar Table with a comment explaining its purpose.
I imported this and ran internally to ensure this worked.
I also considered having the experimentAlias DataTable …
> HParams: Use experiment alias in experiment column

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
Use the result from DataProvider.read_hyperparameters() to generate SessionGroups.
Note: Like in https://github.com/tensorflow/tensorboard/pull/6391 we don't yet support retrieval of Metric values for these SessionGroups and we don't yet merge the new SessionGroups with the tensor-based SessionGroups.
> Hparams: Add ListSessionGroups support for DataProvider results.

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_module.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
The scalar card line chart will be a separate module that we want independent of the scalar card. This aims to resolve build errors in the previous scalar card line chart changes.
Googlers, see cl/547304448 to see that these changes build. 
Move ScalarCardFobController from Scalar Card to Scalar Card Line Chart. 
Demo that current scalar card with fob still works
[demo.webm](https://github.com/tensorflow/tensorboard/assets/70195566/7a0828df-5c65-4989-8746-70da632b4411)
> Embedded Single Card: fix modules for scalar card line chart 

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
The previous runs table showed a spinner when the data was still loading. I am just reusing the existing logic to show a spinner in the new one as well.
A wild spinner appears
Dark Mode
> HParams: Add loading spinner

- tensorboard/plugins/hparams/api.proto
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
This addresses several issues and cleanup related to how we generate and handle hparams with discrete domains:
1. From the backend, always return the list of discrete domain values for a string hparam. Previously we were returning no discrete domain values when the number of values exceeded 10 but this was breaking assumptions in the Angular hparam logic. 
2. In the polymer UI, generate a "regexp" filter for discrete string hparams with greater than 10 values. 
3. Fix regexp filter display logic in the polymer UI. We were never successfully showing the regexp filter. The check `[[hparam.filter.regexp]]` was incorrect since it would evaluate to `false` when `regexp` is the empty string. Instead we must check that `hparam.filter.regex !== undefined`.
4. Simplify the logic for generating …
> Hparams: Change some handling/generation of hparams with discrete domains.

- tensorboard/data/provider.py
- tensorboard/plugins/hparams/api.proto
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
Add a `differs` field at both the DataProvider level (in Hyperparameter) and at the hparams API level (in HParamInfo).
Also write logic to consume it in the hparams dashboard by sorting the hparams that differ to the top.
There are, unfortunately, no tests in the repo for UI changes so I had to test the changes manually. I tested that an experiment with < 5 hparams renders all hparams and selects all hparams. I tested that an internal experiment (from an internal data provider implementation) that has > 5 hparams sorts hparams with `differs===true` to the top and that the first five are selected. I checked that attempts to set the order and to set filters succeed.
> Hparams: Add differs field.

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/json_format_compat.py
- tensorboard/plugins/hparams/json_format_compat_test.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
There are cases where users might log hparam numeric values that are NaN or Infinity. Recall, we use proto's Value message for logging and storing hparam values. While processing these values in the python layer of the Hparams plugin, we may run these Value message through json_format.MessageToJson, at which point the json_format library raises an error.
The limitation is documented at https://protobuf.dev/reference/protobuf/google.protobuf/#value. "[A]ttempting to serialize NaN or Infinity results in error."
We now will try to avoid calling MessageToJson on these problematic hparam values. We instead chose to treat these as "unset" values -- equivalent to having not set an hparam value at all. It will mean the values will not contribute to the calculation of discrete domains. And it …
> Hparams: Treat Nan/Infinity numeric hparam values as unset values.

- tensorboard/plugins/hparams/BUILD
#6496 broke the internal import due to missing BUILD dependency for json_format_compat_test.py.
> Add missing build dependency for internal import.

- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
There was a bug where opening another modal (such as the column adder using the + button) the context menu would not close. This happened because of event propagation is disabled to allow nested context menus.
Before
After
> HParams: Fix bug where context menu stays open when another modal is opened

- tensorboard/webapp/header/plugin_selector_component.scss
We're in the process of changing the Angular Material components to use CSS variables for theming. This involves moving some declarations from the theme to the component base styles which changes its specificity. One such change that breaks the Tensorboard screenshot tests is https://github.com/angular/components/pull/27479.
The problem boils down to the fact that because the styles that override the form field color are in the base styles now _and_ the Tensorboard dark theme targets `body.dark-mode`, only in dark mode some of the select declarations aren't being overwritten anymore. This won't be a problem once Tensorboard moves away from the legacy Angular Material components, but for now this patch is necessary to ensure that it doesn't blend into the toolbar.
**Note:** these changes …
> Change to facilitate Angular Material theming API update

- tensorboard/webapp/metrics/store/metrics_selectors.ts
Reverts tensorflow/tensorboard#6499. Creating new card state to fetch card Id instead.
Googlers, please see cl/549111524 to see how the card Id will be linked in the card state.
> Revert "Embedded Single Card: export card Id list"

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_container.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view_test.ts
The internal embedded single card will not render the tooltip, so the line chart needs to handle that behavior. 
Add in a flag to disable the tooltip.
Demo - disabled tooltip on single card
[single card.webm](https://github.com/tensorflow/tensorboard/assets/70195566/1da09258-951e-4e23-96ea-9fbad6244817)
Demo - scalar card tooltip working normally (renders tooltip)
[scalar card.webm](https://github.com/tensorflow/tensorboard/assets/70195566/c89cc3cd-0327-456b-87a1-838f22f7b556)
> Embedded Single Card: disable tooltip on line chart

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_test.ts
Simplify testing for readability of scalar card line chart testing. 
After making stepOrLinkedTimeSelection an input for the Scalar Card line chart, we can set the value directly on the fixture. This change goes with https://github.com/tensorflow/tensorboard/pull/6498. Previously, we needed to set the variable on the line chart component instance.
> scalar card line chart: simplify testing

- .github/workflows/ci.yml
This reverts commit e75d5b9adaae36d06e142964610d769f59c1963e.
The pinned version of tf-nightly has been deleted and ci is now failing. We once again allow ci to use latest 'tf-nightly'.
> Revert "Chore: Pin `tf-nightly` (#6350)"

- tensorboard/plugins/hparams/tf_hparams_utils/tf-hparams-utils.ts
Hparams from data provider can return null for some hparam values. The Hparams dashboard code does not yet expect this and would call toString() on null values, resulting in error and stopping the table from rendering properly.
The fix is simple, render empty string '' for null values just as we already do for undefined values.
> Handle null hparam values in table view.

- tensorboard/data/provider.py
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
Adds support for specifying sort in
DataProvider.read_hyperparameters(), represented as keyword argument
`filters: Sequence[HyperparameterSort]`.
Updates list_session_groups.py to translate ColParams from the HTTP
request into HyperparameterSort objects and include it in the request
to the DataProvider implementation.
> Hparams: Adds sort argument to DataProvider.read_hyperparameters().

- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
The card route should be set up to parse experiment ids and return alias for run display names on the internal single card. 
Googlers, please see cl/547910211 for use of experiment alias when setting the chart metadata map.
> Embedded Single Card: parse card route exp alias

- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
Create a separate selector so that the single card fetch the time series data with a given card Id. 
Separate the existing time series selector to have card metadata as input so that the single card can pass in parsed metadata. 
Googlers, please see cl/547536441 for the usage of the decomposed selector.
> Embedded Single Card: get loadable time series selector

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
For the internal new single card, we want to keep step selection toggled on at all times. 
Prevent removal of the single fob when step selection is single selection. On range selection, allow removal of either fob. By default, the fob should allow removal, otherwise it will not allow removal when receiving specific input.
> Embedded Single Card: single fob removal

- package.json
- yarn.lock
This upgrades our npm typescript dependency to "4.9.5", the latest 4-series release on npm.
No code changes required. I audited our usage of ts-ignore but none of our usage would be impacted by this upgrade.
Note: I attempted to upgrade to TypeScript 5.1 but it was non-trivial. This is my consolation prize.
> Chore: Upgrade to use TypeScript 4.9.5.

- tensorboard/webapp/widgets/custom_modal/custom_modal_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
In #6504 I introduced a bug to the column selector modal when it was opened via the + button. The effect was that the modal was being closed in the same event that opened it. Rather than changing the way that specific event was being dispatched I instead am preventing the modal from being closed until at least a single frame has been rendered.
It didn't work before 
It works now
> Bug Fix: Prevent custom modal from being closed until after it is opened

- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/runs/store/runs_reducers_test.ts
- tensorboard/webapp/runs/store/runs_selectors_test.ts
- tensorboard/webapp/runs/store/testing.ts
- tensorboard/webapp/widgets/data_table/types.ts
This is the final change in a long line of changes to move to using name. The original and functional change is #6362. This had to add name as an optional parameter only in order to avoid internal breakages. Now that we had name we could add the use of name internally(Googlers see cl/534191646) . Then we could switch to make the header optional and the name required which was done here: #6400. After header was optional we removed the use of headers internally(googlers see cl/552643471). Finally in this PR we removed the header attribute.
> Chore: Remove header attribute of sortingInfo interface

- tensorboard/webapp/metrics/effects/index.ts
For years we have been making two requests to fetch tags then canceling the first one. This occurs because the request is dispatched when either the dashboard is shown without data or a new plugin is loaded. When the dashboard is initially loaded both of these conditions are true.
Before:
After:
> Throttle tags request

- tensorboard/plugins/wit_redirect/BUILD
This is a follow up PR for [#6495](https://github.com/tensorflow/tensorboard/pull/6495) to add load() statements for Blaze-builtin Python rules/providers. 
More information: [go/py-add-loads-lsc](https://goto.google.com/py-add-loads-lsc)
> Add load() statements for Blaze-builtin Python rules/providers

- tensorboard/examples/plugins/example_raw_scalars/BUILD
- tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/BUILD
- tensorboard/examples/plugins/example_raw_scalars/test.py
I expect the behavior for relative imports changed after the python rule changed in #6495, and made this test fail, so it now needs to be an absolute import. (Unsure of why this was not making CI fail... maybe this particular target is not run as part of CI, since it's just an example.)
Adds a BUILD target for the submodule that was previously imported with a relative import. With the BUILD target and the dependency, the module can now be referenced as an absolute import.
N/A
Tests that were previously failing now pass.
N/A
> Updates import and BUILD dependency in test from example

- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
This was causing "Maximum call stack size" errors when we received too many data points.
I am simply looping over the data points and getting the min and max instead of passing them all to Math.min and Math.max
I ran internally hardcoding the backend to return 300,000 data points. This caused the "Maximum call stack size" error. Then I made this change and the data loaded. I increased the number of data points to over 1 million(timeseries call was 7mb) and the data still loaded. When I went to 10 million data points the call failed after waiting 5 minutes.
> Bug fix: Do not pass all data points as parameters

- tensorboard/pip_package/requirements.txt
We currently don't have an upper bound on the protobuf dependency, but the new release broke our CI.
> Restricts protobuf dependency to < 4.24 due to protocolbuffers/protobuf#13485

- .github/workflows/ci.yml
- RELEASE.md
- tensorboard/pip_package/setup.py
- tensorboard/version.py
- Cherry-pick the drop for support for Python 3.8
- Cherry-pick the relnotes
- Update version for our nightly builds to the next number: 2.15.0a0
> Post-release 2.14.0

- tensorboard/data/provider.py
Resultant session groups would be sorted if `sort` is specified.
#hparams
> Hparams: Change `read_hyperparameters()` return type

- tensorboard/webapp/hparams/_redux/BUILD
Googlers, see cl/557139147 for failure.
The CL's presubmit passes because the tests are not run but fixing the Builder failures seems like good hygiene.
> Hparams: Fix internal Builder failure for test.

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
Motivation: Sometimes a user is viewing a single experiment and the DataProvider determines that experiment contains exactly one session. In this case the DataProvider will return a session with both empty experiment_id and empty run.
We want this "empty-name session" to represent all runs in the experiment. But we have a bug where the /experiment and /session_group responses do not contain any metrics for the session. We want to instead designate all (run,tag) combinations as separate metrics to include in the /experiment and /session_groups responses.
The first change to get this to work:
* When generating session names, a session with experiment_id="" and run="" should generate an empty session_name "" (instead of using the somewhat-meaningless input experiment id as the session_name). …
> Hparams: Allow sessions without name to pull all run,tag combinations as metrics.

- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
Handle metric-based filters for DataProvider-based hparam requests.
There are three parts:
* Stop sending the metric-based filters to the DataProvider. The DataProvider does not have the metric data to apply the filtering.
* Generate local filters. The generated local filters are based on metrics only. Local filters are not generated for hparams so as not to repeat the work of the DataProvider.
* Apply the local filters after session group metrics have been retrieved and aggregated.
> Filter metric values in /list_session_groups.

- tensorboard/webapp/hparams/_redux/BUILD
- tensorboard/webapp/hparams/_redux/hparams_actions.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers_test.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors_test.ts
- tensorboard/webapp/hparams/_redux/testing.ts
- tensorboard/webapp/hparams/_redux/types.ts
- tensorboard/webapp/hparams/_redux/utils.ts
- tensorboard/webapp/hparams/_redux/utils_test.ts
Now that the filter dialog is merged #6493 we need to add support for filtering by hparams. However, #6544 changed the way hparam values are read. This change adds a new property to state in which to store dashboard related hparam and metric filters.
See #6488 for the WIP integration with the runs_table_container + tb_data_table -> common_selectors + hparam_selectors.
> HParams: Add new state property to store hparam and metric filters

- tensorboard/plugins/hparams/api.proto
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/get_experiment.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
There are some clients of the Hparams HTTP API that do not require the metric information. This includes the metric_infos usually returned in the /experiments request and the metric_values usually returned in the /session_groups request. Since these can be expensive to calculate, we want the option to not calculate and return them in the response.
Add option `include_metrics` to both GetExperimentRequest and ListSessionGroupsRequest. If unspecified we treat `include_metrics` as True, for backward compatibility. Honor the `include_metrics` property in all three major cases: When experiment metadata is defined by Experiment tags, by Session tags, or by the DataProvider.
> Hparams: Support excluding metric information in HTTP requests.

- tensorboard/webapp/theme/_tb_theme.template.scss
We are starting to use the new MDC components. This applies our theme to those components so they are the correct colors.
> MDC Migration: Apply tb theme to new mat components

- tensorboard/program.py
#6552
The port scanning logic originally added in #1851 does not seem to work anymore. WerkzeugServer no longer raises an Error when attempting to bind to a port which is in used and instead handles the issue silently.
The current Werkzeug version is 2.3.7 but I had 2.3.4 installed when I first verified this. I tried installing 2.2.0 and the issues was not present so I assume it was introduced in 2.3.0.
https://pypi.org/project/Werkzeug
1) Start TensorBoard, note the port it is bound to (it should be 6006)
2) In a separate terminal start TensorBoard again.
3) TensorBoard should successfully bind to a different port (this time 6007)
> Bug Fix: Update the port scanning logic to properly skip ports in use

- tensorboard/webapp/app_routing/types.ts
- tensorboard/webapp/runs/effects/runs_effects.ts
- tensorboard/webapp/runs/effects/runs_effects_test.ts
Now that we are fetching the hparams data using the newly created hparams_effects (#6540) we no longer need to fetch them using the old method.
Note that the experiment list SHOULD still use the old method.
> HParams: Stop fetching hparams data using run effects

- tensorboard/webapp/metrics/store/metrics_reducers.ts
This feature has been out for awhile and we have had good feedback. However, based on the number we believe many user who would find this useful have not discovered it. This change turns the table on by default.
It is worth noting that if users have enabled/disabled this in the past their choices are stored and then will not see any changes unless they delete their local storage or move to a new computer.
I deleted localStorage, reloaded the page, and observed that is was enabled. Then disabled, reloaded the page, and observed that it was still disabled. All is working as expected.
> Data Table: enable data table by default

- tensorboard/webapp/runs/effects/runs_effects.ts
The internal TS compiler does not seem to understand this typing and is failing to build the project due to this.
Googlers see [this build error](https://fusion2.corp.google.com/invocations/93bb13a8-2f19-4353-ae39-1fbebcb484a3/targets/%2F%2Fthird_party%2Ftensorboard%2Fwebapp%2Fruns%2Feffects:effects;config=5586cf857573577a6cafd5ec36717fe7433482d93abeca5f0b792636a7fd48dd/log)
Also see [this successful build](https://fusion2.corp.google.com/invocations/36e64c96-1280-4f5d-89da-bfbd36172401/targets/%2F%2Fthird_party%2Ftensorboard%2Fwebapp%2Fruns%2Feffects:effects)
[go/typescript-g3patterns#tuple-types](http://goto.google.com/typescript-g3patterns#tuple-types)
> Chore: Fix internal sync

- tensorboard/webapp/runs/effects/runs_effects.ts
`zip` and `forkJoin` work somewhat differently internally so these observables simply aren't emitting and thus break our sync.
Googlers see cl/562877415 for the breakage and cl/cl/563214152 as proof that this works.
#6566 #6488
> Bug Fix change run effects to use combine latest instead of forkjoin

- tensorboard/webapp/app_routing/types.ts
- tensorboard/webapp/runs/effects/runs_effects.ts
- tensorboard/webapp/runs/effects/runs_effects_test.ts
#6561 created issues when syncing internally. When we discovered the problem we tried to patch forward twice
* #6566 
* #6568
There was a couple of issues.
* Improper support for tuples internally.
* Internally `forkJoin` and `zip` work differently, it's not document how though.
* The unapproved screenshot changes in [cl/563231334](http://cl/563231334)
Googlers see [cl/563516101](http://cl/563516101) for confidence this ACTUALLY fixes the sync.
> Revert HParams: Stop fetching hparams data using run effects (#6561)

- tensorboard/data/provider.py
- tensorboard/plugins/hparams/api.proto
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
This PR extracts the filtering logic for hparams only (metrics filtering will be done later) from bmd3k's [commit](https://github.com/bmd3k/tensorboard/commit/ab75cd1812097f5ca54085e68a34a8cfa346a60b). 
Googlers, see comments in cl/559852837 for more context.
Test internally at cl/563163418.
#hparams
> Hparams: Add `include_in_result` field and implement support for `hparams_to_include`

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
Currently TF summary written hparams with `DATA_TYPE_FLOAT64` value type have no domain types.
#hparams
> Hparams: Set interval domain fields for float summary hparams.

- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
This allows `list_scalars` of some of the data provider implementations to return the last scalar value, which will improve the performance when loading experiments with Hparams data.
Googlers, see b/292102513 for context.
Tested internally: cl/563163418
#hparams
> Add `last_value` to `ScalarTimeSeries` interface.

- tensorboard/webapp/metrics/data_source/BUILD
- tensorboard/webapp/metrics/data_source/card_interactions_data_source.ts
- tensorboard/webapp/metrics/data_source/card_interactions_data_source_module.ts
- tensorboard/webapp/metrics/data_source/card_interactions_data_source_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
We are working on a feature to suggest cards to users at the top of the timeseries dashboard. Suggestions are generated based on previous interactions with TensorBoard. In order to determine what those previous interactions were we are storing them to localStorage.
See #6437 for more information.
Googlers see [go/tb-suggested-cards](go/tb-suggested-cards)
> Suggested Cards: Create data source for persisting card interactions to localStorage

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/get_experiment.py
Limit for summary hparams fetched from `data_provider.list_tensors` will be applied later (see `TODO` for details).
#hparams
> Hparams: Apply limit to hparams retrieved from protos with `_hparams_/experiment` tag.

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
Currently `differs` fields are not populated for hparams written by TF summary API. 
Also changed the boolean hparam domain discrete values to be the actual values used in the sessions rather than both True and False.
#hparams
> Hparams: Populate `differs` field for TF summary hparams.

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
Bug fixed by this PR: Currently when there is no limit, `_sort_and_reduce_to_hparams_limit()` truncates the last value. Corresponding unit test is wrong as well. 🤦 
Googlers, see internal test at: cl/563163418
#hparams
> Hparams: fix the bug where the last hparam was discarded when there is no limit

- tensorboard/webapp/runs/store/runs_reducers.ts
The new runs data table was sorting the runs in a different order than the older runs table. We want to keep the sorting the same when we make the switch to the new table for users.
> HParams: Default Runs table sorting to ascending

- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.ts
Internally we have migrated our GA logging implementation to use the "gtag.js"-based method instead of the "analytics.js" method.  We want to update this bit of hparams GA logging to do the same.
Tested:
* Compiled and ran the program and noticed that no logging is performed (because GA is not configured by default)
* Imported the code internally and ran and noticed that logging is performed.
> Migrate hparams to use gtag.js-based logging for Google Analytics.

- tensorboard/webapp/widgets/data_table/data_table_component.ts
There are a lot of funky interactions revolving around interactions in nested context menus. This is one of them. Essentially we don't always want to close context menus when you click in them, but there are a couple of edge cases where we actually do want it closed, such as removing the subject of the context menu.
2) Nagivate to localhost:6006?enableHparamsInTimeSeries=true
3) Add an hparam column to the runs table
4) Using the context menu open the filter dialog
5) Without closing anything click the remove button in the context menu
6) Assert the filter dialog disappears
> HParams: Bug fix - removing a column closes the filter modal

- tensorboard/webapp/widgets/data_table/data_table_component.ts
The context menus were being aligned to the bottom of the button which opened them. This was wrong.
2) Navigate to localhost:6006?enableHparamsInTimeseries
3) Right click on the runs table
4) Add a column
5) Note that the column selector opens aligned to the top of the "Add Left / Right" button
6) Try the same thing with the filter menu
> HParams: Align sub context menus to the top of the button which opened them

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/runs/effects/runs_effects_test.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
This PR will launch the hparams in timeseries feature.
> HParams: Enable `hparamsInTimeSeries` by default

- tensorboard/webapp/runs/effects/runs_effects_test.ts
I let #6565 sit for a long time, then merged without rebasing. The result broke CI. This should fix it.
When the PR was created the `enableHparamsInTimeSeries` was already imported, but between the PR creation and merge it was removed.
https://github.com/rileyajones/tensorboard/blob/3cd4ce2e00a4e5fb0bb92e82a44d2fcdc8a7f13b/tensorboard/webapp/runs/effects/runs_effects_test.ts
> Chore: Fix CI breakage

- tensorboard/webapp/widgets/range_input/range_input_component.ng.html
- tensorboard/webapp/widgets/range_input/range_input_test.ts
When teamfooding the hparams in timeseries feature we discovered that the interval filter widget doesn't look good when there is only a single value. This is actually due to the `tb-range-input` widget looking bad when the min and the max are equal. I'm opting to simply not show the slider when `min === max`
For Googlers:
https://screenshot.googleplex.com/5rZbjsd6ijp8dkY
> Bug Fix: update the range input widget to only show the slider when min and max are different

- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/filter_dialog_component.ng.html
- tensorboard/webapp/widgets/data_table/filter_dialog_component.scss
These modals felt pretty cramped sow were' adding more space. Additionally more items should fit in the scroll container prior to the scroll bar appearing.
Before
After
Before
After
Before
After
> Improve styling of context menus

- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
There was a bug when readding columns because the column was getting set to readonly when written to redux. Making a copy of the column as it is added resolves this issue.
2) Navigate to localhost:6006?enableHparamsInTimeseries
3) Add a column to the runs table
4) Remove that column
5) Add the column again
> HParams: Bug fix when adding table columns copy them rather than mutate them

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
Apply `hparams_limit` to hyperparameters from tensors, and sort them by `differs` field (differed first).
#hparams
> Hparams: Sort and apply limit to hparams from runs.

- tensorboard/webapp/widgets/data_table/header_cell_component.ng.html
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
To allow for tabbing to buttons and for general best practice clickable elements should be buttons. So the 3 dot menu button was changed into a button instead of a div. For sorting the entire header is clickable. We did not want to make the entire header a button so I turned the sorting icon into a button.
I also made some styling changes to spread out the icons and make them easier to click.
When I made the sorting icon a button I had to add the click event to make it sort. I also had to stop propagation so the header's click event was not fired.
> HParams: Make icons buttons in data table header

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
After sorting with the explicitly specified sorting key (`differs`), `sorted()` returns the order within each `differs` group differently when running externally v.s. internally, which broke internal tests. Changing to sort by name within each `differs` group as a workaround.
Googlers, see the test failure details in cl/568227790.
#hparams
> Hparams: Sort by `differs` then by `name`.

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
I originally started to fix a bug where the bottom border in the regex did not stretch to the end of the table once scrolled. However, I decided there is no reason to scroll the regex at all and it can actually be kind of annoying. So I change the x scroll to just be the table
(or N/A)
> HParams: Do not scroll regex filter in the horizontal direction

- tensorboard/pip_package/requirements.txt
This package is no longer needed in newer versions of python. It comes as a seed package where needed. It is even causing some users problems(#6567)
> Chore: Remove wheel from requirements.txt

- tensorboard/webapp/header/plugin_selector_component.ng.html
- tensorboard/webapp/header/plugin_selector_component.scss
- tensorboard/webapp/header/plugin_selector_container.ts
Background: We are trying to migrate to all the non legacy angular components. To accomplish this we changed them all over at once and began hunting for differences.
One of the biggest differences is that the header is totally foobar. This seems to be primarily due to the following issues:
1) The header had a lot of custom hacky css in it
2) The `mat-tab` component had a significant number of structural changes
Light Mode https://screenshot.googleplex.com/AJdQE3T35aQSxpT
Dark Mode https://screenshot.googleplex.com/4Tn3XYqd6FSKCzS
> MDCMigration: Restyle the header tabs

- tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Updating the style of this menu after update to new MDC components. T
The new MDC mat-menu no longer uses `<label>` and can also handle mat-icons on its own.
> MDC Migration: Fix styling for runs_group_menu

- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
After migrating to the new Material Components many of the styles were broken. This cleans up the buttons in the runs table context menu.
> MDC Migration: Fix styling for runs table context menu

- tensorboard/webapp/widgets/dropdown/dropdown_component.scss
- tensorboard/webapp/widgets/dropdown/dropdown_component.ts
This restyles the right-hand pane dropdowns. The end result is:
1. selection trigger looks mostly like current.
2. selection panel is styled similar to current but selection rendering is different and the panel is offset lower and slightly to the right.
Here are some sample screenshots but please patch it in locally and give it a try:
> MDCMigration: Style right pane dropdowns for MDC migration.

- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
Restyle the checkboxes in both the runs table and right pane.
For runs table this is mostly just about removing and adjusting padding.
For right pane this:
* adds negative margin to account for checkbox padding - aligning the checkboxes with other elements in the pane.
* adjusting the text of checkbox labels to look more like the current style.
Here are some sample screenshots but please patch it in locally to play with it:
> MDCMigration: Style run table and right pane checkboxes.

- tensorboard/webapp/header/plugin_selector_component.ng.html
- tensorboard/webapp/header/plugin_selector_component.scss
- tensorboard/webapp/header/plugin_selector_container.ts
This is another attempt at restyling the plugins selector component for MDC Migration.
We start by reverting the previous attempt so that we have a good base for the conversion.
(See b846aae50da844a62f44c1fb0d08a89fa5f3d538)
We then take the approach of attempting to adjust the current styling to mdc components as much as possible, in order to preserve current styling and current behavior.
(See 4012cae19d433eeb254a61a9f9658a606868f1bf for the clean diff compared to original)
The end result is:
* The header plugin tabs appear and behave almost identically to current.
* The inactive plugin selector is styled slightly differently but still, in spirit, is similar to current.
Some sample screenshots but please patch it locally to play with it:
> MDCMigration: Restyle all plugins selector component for MDC migration.

- tensorboard/webapp/metrics/views/_common.scss
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/theme/_tb_theme.template.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
One of the biggest changes we have noticed during the mdc migration appears in the `mat-icon-button`. I am opting to attempt to fix them all at once by modifying the global files present in the theme file, then tweaking specific buttons.
[Light Mode](https://screenshot.googleplex.com/85bjNe5T2H6nBhy)
[Dark Mode](https://screenshot.googleplex.com/5grTGURG8kddzfX)
> MDC Migration: Globally restyle `mat-icon-button`

- tensorboard/plugins/image/summary_v2.py
See https://github.com/tensorflow/tensorboard/pull/6344 for context.
Googlers, see b/276803093 for more details.
Tested internally: cl/570508513
#oncall #summary #image
> Image Summary: Officially start using vectorized EncodePng Op

- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
Restyle the runs data table column selector.
The contents end up being larger than current master version.
The search icon, and search text input are bigger.
The height of each item in the list is taller to match the larger button touch target.
Some sample screenshots:
> MDCMigration: Style runs data table column selector for MDC migration.

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/widgets/data_table/content_cell_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
Restyle the height of header and rows in the runs data table. 
The height of these rows does need to increase compared to current master in order to account for the increase in height of the checkbox touch target. But they don't need to be as tall as they are now compared to current MDCMigration.
The end result is:
* Header and rows height are now 48px. (compared to 56px and 49px in MDCMigration and compared to 48px and 44px in master).  So the non-header rows grow in height by 4px compared to master. Header rows remain the same compared to master.
Implementation Detail:
* I move the common `padding: 4px` out of content_cell_component and header_cell_component and now make this padding the responsibility of runs_data_data and scalar_card_data_table to specify.
* scalar_card_data_table …
> MDCMigration: Style runs data table row heights for MDC migration.

- tensorboard/webapp/theme/_tb_theme.template.scss
Style the readme button for MDC Migration.
In global theme we change the rules that ensure a read `<a>` link remains white.
Screenshots:
> MDCMigration: Style readme button for MDC migration.

- tensorboard/webapp/theme/_tb_theme.template.scss
Style the "settings" button and the "scalars | images | histograms" plugin chooser button.
We can do this by adjusting the global styles we recently introduced, meaning that other buttons we add in the future will also adhere to these styles:
1. Set letter-spacing to normal for all button text.
2. Reuse the .mat-icon styling we introduced even for non icon-button buttons.
Sample screenshot:
> MDCMigration: Style Settings button and Plugin picker for MDC migration.

- tensorboard/webapp/alert/views/alert_display_snackbar_container.scss
Style the alert snackbar buttons for MDC migration.
They were appearing a dark color at all times. Now we ask it to inherit its color.
Sample screenshots:
> MDCMigration: Style alert snackbar for MDC migration.

- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
After an update to the new MDC Components the style of this feature was messed up. This fixes that style.
> MDCMigration: fix Column Editor Style

- tensorboard/webapp/settings/_views/settings_dialog_component.css
- tensorboard/webapp/settings/_views/settings_dialog_component.ng.html
After migrating to the new MDC components many new components needed style fixes. This is that fix for the SettingsDialogComponent.
before:
after:
> MDCMigration: fix settings modal style

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
Fixing regex since it looked pretty bad after MDC Migration. While doing this I also standardized the padding across the entire page to 16px.
Before:
After:
> MDCMigration: set padding in regex modal

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
- tensorboard/webapp/settings/_views/settings_dialog_component.css
Some last minute fix ups before the MDC Migration feature branch merge.
Before(note save button color): 
After:
Before:
After:
> MDCMigration: 2 dialog style changes

- tensorboard/plugin_util_test.py
Googlers, see b/303850407
Update to google-internal package markdown_freewisdom no longer has this behavior.
Removes test that was testing a behavior that has been removed in the new version
> Remove markdown test for deprecated behavior.

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
The checkbox (aka 'selected') and color icon columns in the new runs data table would have variable width in the table's flex layout. This led to some awkward looking spacing for these columns.
We want to fix the width of these columns.
Similar to strategies for other tables (mat-table and the old runs table, for example), add a column-specific class to each cell and customize the width of the 'selected' and 'color' columns using these classes.
> Give fixed width to runs table's checkbox and color columns.

- tensorboard/plugin_util.py
Followup to https://github.com/tensorflow/tensorboard/pull/6634, which references b/303850407 (Googlers only).
The PR was incomplete and also required removal of a reference to markdown_freewisdom.
> Chore: Remove markdown freewisdom reference.

- .github/workflows/ci.yml
- tensorboard/data/server/pip_package/build.py
This should ensure that the generated wheels are compatible with the `manylinux_2_31` platform tag, since that's the version of `glibc` shipped with ubuntu 20.04. This aligns us with https://peps.python.org/pep-0600/ instead of reconfiguring our CI workflow to build on a system with `glibc<=2.17` to keep supporting the `manylinux2014` tag (https://peps.python.org/pep-0599/).
> Update data server build step to run with ubuntu 20.04 and change platform tag

- tensorboard/webapp/hparams/_redux/hparams_effects.ts
- tensorboard/webapp/hparams/_redux/hparams_effects_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/util/ui_selectors.ts
Previously any changes to the metrics state would result in the runs table being redrawn. This was happening for two reasons both related to selectors with dependencies on `state`. Whenever any value on state changed these selectors would reflow.
While testing this I discovered that entering a value into the tag filter triggered a `navigated` event which would in turn re-fetch the session_groups data. I have chosen to fix this by deduplicating events at the effect layer.
Before
After
> Hparams: Fix repainting bug

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
Issue number 5 in #6651.  It is also just a better experience to keep previously loaded data intact while fetching new data.
In order to put the spinner below the headers I added the spinner to the data-table. It seems like a general feature that should be in that widget anyway.
> HParams: Load spinner in data table and do not reload table

- RELEASE.md
- tensorboard/version.py
- Cherry-pick the relnotes
- Update version for our nightly builds to the next number: 2.16.0a0
> Post-release 2.15.0

- tensorboard/pip_package/requirements.txt
protocolbuffers/protobuf#13485 was fixed with protocolbuffers/upb#1514, so this shouldn't be an issue anymore. 
If CI passes successfully with this change, then it should be fine to merge.
> Relaxes restriction on protobuf dep since issue was fixed.

- tensorboard/webapp/widgets/data_table/BUILD
This spinner was added to the Data Table in #6658. However, I forgot to add the placeholder dependency which is required for internal syncs. This adds that dependency to fix the sync.
> Add a placeholder dependency for angular material progress spinner

- tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
The new mat-button uses different colors in it's styling. This caused a readability problem with our Next and Prev buttons when enabled. This fixes the buttons to be readable and look nice. We decided the transparent background looked nice in dark mode but not in light mode. 
This was brought to our attention in #6651.
Before:
After:
Also considered having a transparent background in light mode.
> MDCMigration: Fix prev and next buttons for dark mode

- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
The runs table previously always showed the scroll bar. Now it only shows when there are enough runs.
Before (no scroll):
Before (with scroll):
After (no scroll):
After (with scroll):
> Bug Fix: Make the runs data table only show a scrollbar when needed

- tensorboard/webapp/runs/views/runs_table/BUILD
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/sorting_utils.ts
- tensorboard/webapp/runs/views/runs_table/sorting_utils_test.ts
We have been treating all run names as strings even though some run names are (serialized) numbers and some begin with numbers. This means that sorting worked pretty unintuitively.
Note: I've also changed the behavior around sorting `undefined` values. When sorting descending they should now appear at the top of the list. This was a recent change but it wasn't clear it was intentional and I found it made the code more complex.
https://github.com/tensorflow/tensorboard/issues/6651
Internal users see [b/278671226](http://b/278671226)
Before:
After:
> Sort run names with leading numbers differently

- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
The additional right margin on the image slider from #6666 adds an unnecessary horizontal scrollbar to the image card. I don't think the margin is necessary so I've just removed it.
Screenshot of changes:
> MDC Migration: Adjust image slider styling to get rid of card horizontal scroll bar.

- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/data_provider.py
- tensorboard/backend/event_processing/data_provider_test.py
- tensorboard/data/grpc_provider.py
- tensorboard/data/grpc_provider_test.py
- tensorboard/data/provider.py
- tensorboard/plugins/debugger_v2/debug_data_provider.py
This will be used for `hparams.backend_context.read_last_scalars`.
Googlers, see b/292102513 for more context.
Tested internally at cl/577906864.
#hparams
> data: define interface for `read_last_scalars`

- tensorboard/uploader/BUILD
- tensorboard/uploader/util.py
- tensorboard/uploader/util_test.py
We deleted the tensorboard.uploader.util.RateLImiter in #6638. However it is used internally and needs to be returned. This is therefore a partial rollback of #6638.
> Chore: Bring back RateLimiter.

- tensorboard/data/provider.py
Googlers, see cl/578850759 and cl/579209461 for more context.
> fix docstring for read_last_scalars

- tensorboard/webapp/hparams/_redux/hparams_data_source.ts
- tensorboard/webapp/hparams/_types.ts
- tensorboard/webapp/runs/data_source/runs_backend_types.ts
The runs table does not display any of the metric fields/data returned by the hparams plugin. We want to avoid unnecessarily calculating this data on the backend.
The hparams plugin allows requests to specify an include_metrics parameter (added in https://github.com/tensorflow/tensorboard/pull/6556). We set this flag to false for all hparams-related requests coming from the "hparams_data_source".
Testing:
* Observed in both OSS and internal TensorBoard that setting this flag to False results in responses that do not include the metric data.
* Observed that hparams in timeseries runs table still works.
* Observed that hparams in experiment list runs table still works.
> Hparams: Avoid retrieving metrics when populating timeseries runs table with hparams.

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
- tensorboard/webapp/alert/views/alert_snackbar_module.ts
- tensorboard/webapp/app_routing/route_registry_module.ts
- tensorboard/webapp/app_routing/views/router_outlet_test.ts
- tensorboard/webapp/customization/customizable_component.ts
- tensorboard/webapp/customization/customization_test.ts
- tensorboard/webapp/feature_flag/views/feature_flag_dialog_module.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_module.ts
- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/views/card_renderer/data_download_module.ts
- tensorboard/webapp/plugins/plugin_registry_module.ts
- tensorboard/webapp/plugins/testing/index.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
- tensorboard/webapp/settings/_views/settings_module.ts
- tensorboard/webapp/settings/_views/settings_test.ts
- tensorboard/webapp/tb_wrapper/tb_wrapper_module.ts
As of Angular 12 the entryComponents aren't required anymore.
Removes entryComponents properties fields from all ngModules calls.
> Removes obsolete entryComponents from ngModules

- tensorboard/webapp/widgets/range_input/range_input_component.ng.html
- tensorboard/webapp/widgets/range_input/range_input_component.ts
- tensorboard/webapp/widgets/range_input/range_input_test.ts
The rangeInputComponent was not triggering the rangeValueChanged event when dragging the slider thumb. This fixes that bug.
The slider changes the value of lowerValue and upperValue while the thumb is being dragged. When dragging is stopped the component used to ensure the value sent in the event was different from the previous values by comparing it to the lowerValue and upperValue. This check always failed as the component now keeps these values up to date. It should be noted that if these values are not kept up to date the input fields do not update while dragging.
To solve I simply call the event every time without doing the check. If the value has not changed we update the state to the same value. This does cause an unnecessary repaint but that seems reasonable for when I user clicks …
> Bug Fix: Always fire rangeValueChanged event when thumb is dragged

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
There was a regression associated with the new runs table which meant that changing the color of a run immediately closed the color picker.
Previously the runs table did not have a dependency on the metrics state. Now that it does, changing the color of a run leads to a state change which then in turn rerenders the row and thus closed the color picker.
The state dependency is important so that cannot be undone, however, we don't actually need to re render the rows when the color changes so I've update the render logic to ignore the `color` attribute (I know it's a little hacky). 
Before:
After - With Paint Flashing
After - Without Paint Flashing
2) Open the color picker
3) Change the color
4) Observe the color picker does not close
5) Check a row and observe that it …
> Bug Fix: Fix color picker regression

- README.md
Continuing #6639 
tensorboard.dev is being shut down, removing the remaining reference in README.md following Commit 7cb91184 / PR #6639
Tensorboard.dev is being shut down, PR #6639 updated the relevant documentations but didn't update README.md.
Removed tensorboard.dev from README.md
N/A
N/A
N/A
> tbdev turndown: Remove references to TensorBoard.dev in README.md

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
Internal TS is slightly different then external TS and leads to some "fun" issues when running syncs.
Googlers see cl/582334596 for failures, see cl/582808018 for proof this passes
> Fix presubmit issue due to internal ts differences

- tensorboard/webapp/experiments/types.ts
Add the type and its corresponding fields of metrics data source to the Experiment type
TB.corp backend already includes metrics data source in the HTTP response of Experiment related GET request. This PR adds the corresponding type and fields to the FE Experiment type to make metrics data source available in the Ngrx store.
This PR is the prerequisite of the Data Source Selector UI in TB.corp 
Googlers see cl/575344506 for implementation of this feature.
> Add types for metrics data source

- tensorboard/webapp/theme/_tb_theme.template.scss
We missed some style issues in the MDC migration. This fixes those style issues. It is done inside the theme file to help facilitate the internal migration as well.
The new mdc dialog does not have this 24px padding. The old one did. Therefore, all of our dialogs are built to assume it is there. Adding this padding keeps the dialogs from changes their design during the upgrade.
(Googlers see cl/580652255 for internal migration)
Before:
After:
I considered adding the padding to individual dialogs.
> MDC Migration: Add padding to all new mdc dialog

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
- tensorboard/webapp/settings/_views/settings_dialog_component.css
- tensorboard/webapp/theme/_tb_theme.template.scss
For consistency it would be better to have a global padding setting. The old mat-dialog had a default padding. During migration we added padding to a few components but we missed one. Internally we also have many more dialogs which look broken after migration. The global setting is less code to maintain and gives our dialogs consistency.
I added the global setting in #6689 but realized the stacking of the previously added padding during migration made some of the dialogs look bad.
> MDC Migration: remove padding to individual dialogs in favor of global padding setting

- tensorboard/webapp/theme/_tb_theme.template.scss
- Angular Material is splitting the mat-button tokens into separate tokens for each button variant. This change is needed to land cl/586440723
> fix mat-button letter spacing style override

- tensorboard/tools/convert_tbdev_export.py
This adds a standalone script `convert_tbdev_export.py` that can convert the JSON-based export format for TensorBoard.dev (produced by `tensorboard dev export`) into tfevents files that can be used to display the exported data in open source TensorBoard. See documentation in the script itself for more details about how it's intended to be used.
Note that I've structured this as a standalone script in the style of diagnose_tensorboard.py (i.e. no BUILD target, no dependencies, no unit tests). Arguably, had we done this earlier, it would be better to have integrated this into the `tensorboard dev export` command itself as an output format option. But we're planning to remove the `tensorboard dev` command entirely once the turndown happens at EOY, so keeping it separate ensures that we can …
> tbdev turndown: add export converter script

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
Issue #6276 
The plus button and help icon were not visible in dark theme. Changed the color to the same color as name text.
Changed design for black
Working for all colors.
Light theme:
Help icon
Go to the graphs tab and select dark theme.
N/A
> Added compatibility for dark theme

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
The experiment name tooltip broke when we migrated to the new RunsDataTable. This fixes that tooltip
Screenshot not available in OSS.
> Pipe full experiment name to experiment alias component for tooltip

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts
- tensorboard/webapp/metrics/views/main_view/pinned_view_container.ts
We noticed that the behavior for showing the "New Card Pinned" notice is flaky. It sometimes does not trigger for the first pinned card after page load.
We just simplify the logic by tracking the "lastPinnedCardTime" in ngrx state and deriving the "New Pinned Card" notice from that state.
> Fix flaky "New Card Pinned" behavior.

- tensorboard/webapp/notification_center/_views/notification_center_component.scss
The styling of the notifications menu, which is only used internally, was broken after MDC migration. This fixes it up.
Screenshots below are only available to Googlers.
Before migration:
https://screenshot.googleplex.com/3GKSmvthNeMbSUq
After migration, broken:
https://screenshot.googleplex.com/3YUdd2PLRPcneQv
After migration, fixed:
https://screenshot.googleplex.com/3uvLB54yWzhVSoL
(Note that, in the screenshots, the position of the "fixed" notifications menu is higher than before migration because the new MDC menu shifts up to accomodate content that is taller than the current viewport.)
> MDC migration: Fix notifications menu rendering after MDC migration.

- tensorboard/BUILD
> tbdev turndown: remove no-longer-needed expect_x_installed placeholder BUILD targets

- tensorboard/plugins/hparams/get_experiment.py
- tensorboard/plugins/hparams/hparams_plugin.py
Fixing 6088 : Download CSV data
Setting good parameters to constructor and adding a default value for an optional parameter 
Download with no error
Googlers, see b/307370637. @yatbear tested internally at cl/598969320.
> Fixing 6088 : Download CSV data

- tensorboard/program.py
Since this functionality is no longer used, I wanted to add some context for why it exists and the fact that it is actually not used anymore (or at least at the moment).
> Adds small documentation about unused subcommands feature.

- tensorboard/webapp/widgets/data_table/types.ts
As-is, tslint will complain that "Type ColumnHeader should have the `declare` modifier because type BackendSettings has it."
> Adds declare statement to ColumnHeader interface to squelch 1p error

- tensorboard/webapp/theme/_tb_theme.template.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
During the mdc-migration I restyled all the buttons via #6608 and only recently noticed that the `mat-calendar` component (which is only used internally) looked pretty off...
To resolve this I am allowing button widths and heights to be set separately then overriding them in the internal date picker component (Googlers see cl/601592566).
Before - https://screenshot.googleplex.com/AKuAQqzf9g6K2GF
After - https://screenshot.googleplex.com/7s6vm8SsajKg9v7
> Bug Fix: Allow icons to be sized by both width and height

- WORKSPACE
The current WORKSPACE file in the repo doesn't correspond to the `buildifier` result.
- Simply applied the result of `buildifier WORKSPACE`. Confirmed that the output is the same for both internal and external (`npx buildifier` v5.1.0) buildifier
> Fixes WORKSPACE format

- WORKSPACE
- tensorboard/webapp/hparams/_redux/hparams_reducers.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_container.ts
- tensorboard/webapp/runs/store/runs_selectors.ts
- tensorboard/webapp/widgets/data_table/utils.ts
- tensorboard/webapp/widgets/data_table/utils_test.ts
Recently merged hparam column PRs (#6732, #6733, #6736) will cause build and lint errors during 1p sync.
- import map from rxjs/operators instead of rxjs
- `DataTableUtils` -> `dataTableUtils`
- use proper string signature on CardStateMap in tests
> Fixes sync errors

- RELEASE.md
(cherry picked from commit 663efeba9e9f1ea1db2de648da1ba38be50c23a4)
> Add 2.15.1 relnotes to RELEASE.md.

- tensorboard/pip_package/requirements.txt
I should have added this condition in #6660. At the time I thought it wouldn't matter much, as I assumed users would most likely get a newer version installed, but on second thought, it would be better to have this check, just in case.
> Avoids bad protobuf version 4.24.0

- .github/workflows/ci.yml
- RELEASE.md
- tensorboard/pip_package/requirements.txt
- tensorboard/version.py
Patch release to relax the protobuf dependency restriction that we introduced when their release broke our CI workflow.
> TensorBoard 2.15.2

- RELEASE.md
- tensorboard/version.py
Bump version at HEAD and cherry-pick release notes into master.
Will rebase and merge the commites.
> TensorBoard 2.16.0 Post-Release chores.

- RELEASE.md
- tensorboard/version.py
The TensorBoard 2.16.0 release depends on tf-keras-nightly, which is bad.
I will perform a TensorBoard 2.16.1 release that depends on tf-keras instead.
These commits prepare for the release. I will rebase and merge them.
> TensorBoard 2.16.1 release

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Currently [scalar_card_data_table.ts:273](https://github.com/tensorflow/tensorboard/blob/5033fef6cf89f5f539b6ec56e193689d98daa6cf/tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts#L273) will throw an error if the scalar card table does not contain the corresponding hparam column data - this will happen often for multi-experiment dashboards.
- Extends the optional chaining to the get() call (this was the original intent)
- Adds test to prevent regression
> Fixes hparam columns from breaking multi-experiment scalar cards

- .github/workflows/ci.yml
- tensorboard/pip_package/requirements.txt
- tensorboard/plugins/hparams/_keras.py
- tensorboard/plugins/hparams/_keras_test.py
We must still install keras 2 as part of CI in order to successfully run graph plugin tests.
> Migrate hparams plugin to Keras 3 and remove Keras 2 from requirements.txt

- tensorboard/plugins/graph/graphs_demo.py
- tensorboard/plugins/hparams/hparams_demo.py
This adjusts *_demo.py files to work with Keras 3.
The hparams_demo is fully backward compatible with Keras 2 and forward compatible with Keras 3.
Unfortunately the graphs_demo is not backward compatible with Keras 2. Users attempting to run it with Keras 2 will get the following error:
```
File "/usr/local/google/home/bdubois/.cache/bazel/_bazel_bdubois/079646a57be11faea0b2bfefccb2a81a/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/graph/graphs_demo.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/graph/graphs_demo.py", line 128, in profile
tf.summary.trace_on(profiler=True, profiler_outdir=logdir)
TypeError: trace_on() got an unexpected keyword argument 'profiler_outdir'
```
Amazingly, though, the graph that the demo generates with Keras 3 can …
> Adjust demo scripts to be Keras 3 compatible

- DEVELOPMENT.md
Some graphs-related tests still require keras 2 to be installed to work.
DEVELOPMENT.md instructions are updated to include `pip install tf-keras-nightly`.
> Add `pip install tf-keras-nightly` to DEVELOPMENT.md

- tensorboard/plugins/hparams/_keras_test.py
This test behaves differently internally and externally. The changes made in #6761 succeed in getting the test to pass externally, but it will then fail when imported Googlers see (cl/608667862).
> Comment out inconsistent test in `_keras_test.py`

- tensorboard/data/server/Cargo.toml
Potential improvement to the build: reduce the binary size by ~5Mb
Run `strip` on release build so that [whatever strip does to the binary] is not shipped in the production build.
Run `cargo build --release`, with and without the change, to observe the binary size (as tested on M1 Mac) reducing from 14Mb to 9.5Mb
> BUILD: strip for release build

- tensorboard/plugins/hparams/_keras_test.py
#6759 modified _keras_test.py to work with Keras 3 but it did not import correctly into the internal repository. It was therefore reverted in #6767.
This changes the test to work both in the oss and internal repos.
Googlers, see cl/612511563 for sample import results.
> Change Hparams keras test to be compatible internally

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
The regex dialog "Save" button is rendered poorly internaly, dark text on dark background.
The color of the button text was changed to 'inherit' in go/tbpr/6631. It doesn't seem to have been necessary so I revert that particular change here.
It means in OSS TensorBoard the button text color will be slightly darker than previously. I didn't personally notice the difference but internal screenshot tests show a slight difference. Googlers, see cr/612557079.
> Fix regex dialog 'Save' text color

- WORKSPACE
- third_party/chromium/BUILD
- third_party/workspace.bzl
We haven't updated this dependency on the bazel webtesting rules for a while, and it looks like we need to do it to be able to also update our reference to the rules_closure target, to unblock #6721.
To be clear, this PR is a prerequisite to pin the rules_closure version in a separate PR, which in turn will unblock #6721. (Or at least that's the expectation. It is yet to be confirmed that the rules_closure version we want to pin is compatible with this one).
An attempt to use the versioned browsers provided by the rules_webtesting dependency was created in #6772, but some tests were failing. It seems that some components or tests were written in a way that depends on the specific browser (?), so to be able to update this dependency, this continues to use the same browser version, only …
> Bump webtesting rules version.

- tensorboard/webapp/hparams/_redux/hparams_actions.ts
- tensorboard/webapp/hparams/_redux/hparams_data_source.ts
- tensorboard/webapp/hparams/_redux/hparams_data_source_test.ts
- tensorboard/webapp/hparams/_redux/hparams_effects.ts
- tensorboard/webapp/hparams/_redux/hparams_effects_test.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers_test.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors_test.ts
- tensorboard/webapp/hparams/_redux/testing.ts
- tensorboard/webapp/hparams/_redux/types.ts
- tensorboard/webapp/hparams/_types.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/views/main_view/common_selectors.ts
- tensorboard/webapp/metrics/views/main_view/common_selectors_test.ts
- tensorboard/webapp/runs/data_source/runs_data_source_types.ts
- tensorboard/webapp/runs/store/runs_selectors_test.ts
- tensorboard/webapp/runs/views/runs_table/types.ts
We no longer surface Hparam-related Metric Values from the server in Angular TensorBoard UI. We therefore remove the MetricSpec and HparamAndMetricSpec types. The latter is replaced with just HparamSpec[] where necessary.
> Remove MetricSpec and HparamAndMetricSpec types.

- tensorboard/webapp/hparams/_redux/BUILD
- tensorboard/webapp/hparams/_redux/hparams_data_source.ts
- tensorboard/webapp/hparams/_redux/hparams_data_source_test.ts
- tensorboard/webapp/hparams/_redux/hparams_effects.ts
- tensorboard/webapp/hparams/_redux/hparams_effects_test.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers_test.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors_test.ts
- tensorboard/webapp/hparams/_redux/testing.ts
- tensorboard/webapp/hparams/_redux/types.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/runs/data_source/runs_backend_types.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_component.ts
- tensorboard/webapp/widgets/data_table/column_selector_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
Limit the number of hparams retrieved by default to 1000 for display in Time Series. Print retrieval information: # of columns loaded and whether there could be more.
This is to address performance issues with loading 1000s of hparams from the backend and trying to render them all.
In a future PR we will add abitlity to "Load All" if user wants to nonetheless load them all.
Screenshot (with default set to 2 instead of 1000):
> Hparams: Limit number of Hparams retrieved by default.

- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_module.ts
- tensorboard/webapp/widgets/data_table/data_table_header_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_header_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
Add tooltips for hparam column names when the name does not match the display name (using case-insentive comparison).
> Add tooltips for columns with names that don't match display names.

- tensorboard/webapp/hparams/_redux/hparams_actions.ts
- tensorboard/webapp/hparams/_redux/hparams_effects.ts
- tensorboard/webapp/hparams/_redux/hparams_effects_test.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers.ts
- tensorboard/webapp/hparams/_redux/hparams_reducers_test.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_component.ts
- tensorboard/webapp/widgets/data_table/column_selector_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
In #6777 we limited the number of hparams we load by default.
Now we add the option for the user to load all hparams in spite of the performance implications.
OSS Light Mode:
OSS Dark Mode:
Internal Light Mode:
Internal Dark Mode:
> Hparams: Allow users to load more Hparams if they are not all included in default.

- tensorboard/webapp/hparams/_redux/hparams_data_source_test.ts
- tensorboard/webapp/hparams/_redux/testing.ts
- tensorboard/webapp/metrics/views/main_view/common_selectors.ts
- tensorboard/webapp/metrics/views/main_view/common_selectors_test.ts
- tensorboard/webapp/runs/data_source/runs_backend_types.ts
- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_test.ts
- tensorboard/webapp/widgets/data_table/types.ts
Shows a 'differs' tag in the data table column selector if an hparam has multiple values.
We start by adding generic support to the data table column selector for "tags". Tags can be arbitrary strings.
Then, for each Hparam column, we calculate whether to include a 'differs' tag.
Light mode:
Dark mode:
Internal Light mode:
Internal Dark mode:
> Hparams: Show 'differs' tag in selector if hparam has differing value

- tensorboard/defs/internal/html.bzl
- tensorboard/defs/web.bzl
The "to_proto" method on Starlark structs is deprecated and shouldn't be used. Instead, the proto module's "encode_text" function should be used. (https://bazel.build/rules/lib/toplevel/proto)
It, along with "to_json", can be disabled in Bazel using the flag --incompatible_struct_has_no_methods
The underlying implementation is the same, so there should be no observable changes in final outputs.
> Migrate uses of struct.to_proto

- tensorboard/plugins/hparams/backend_context.py
Some responses from data_provider.read_last_scalars() may contain run names of the following form: 'SOME_EXPERIMENT_OR_SOMETHING/.', with a trailing '/.' at the end. 
'.' always behaves sort of weird with Hparams and this is no exception. The problem in this case is that sessions of this sort could not be matched with metric values. No metric values would appear for them in the hparams dashboard.
This is because the logic to generate metric names drops the '/.' and so we could not match. That code relies on some os-level path operations and we know that '.' has special meaning for filesystems:
https://github.com/tensorflow/tensorboard/blob/23073c55c03f2f1a9da8c7e0bb9db3349dc15c90/tensorboard/plugins/hparams/metrics.py#L39
We fix the problem by transforming the result of …
> Hparams: Workaround problem with '/.' in run names.

- tensorboard/defs/internal/html.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
To fix an internal breakage since `extract_providers` hasn't been imported from OSS to internal rules_closure repo yet. Also fixing a few internal build warnings.
#oncall
> Define extract_providers method directly instead of importing from closure

- tensorboard/webapp/widgets/data_table/context_menu_test.ts
Importing MatIconTestingModule from `@angular/material/icon/testing` will break 1p sync. Changing this to import from `webapp/testing/mat_icon_module.ts` instead, in accordance with previous usage.
> Fixes MatIconTestingModule import

- .github/workflows/ci.yml
Reverts tensorflow/tensorboard#6804.
keras-team/keras#19353 resolves this on Keras' end.
> Revert "Force tests to use keras 2" after keras-team/keras#19353

- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
We limit the number of hparams retrieved and rendered in the Hparams plugin. Otherwise the plugin can become very slow and even crash.
Unlike #6780, we do not provide an option for loading more in the Hparams plugin. We may provide this option later if there is demand. But generally we think 1000 should be enough, especially if the underlying hparams provider is sorting the results with "differs" fields first.
> Hparams plugin: Retrieve and render only first 1000 hparams.

- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
Ensure the following properties are passed to the column selector from the data table:
```
[numColumnsLoaded]="numColumnsLoaded"
[hasMoreColumnsToLoad]="hasMoreColumnsToLoad"
(loadAllColumns)="loadAllColumns.emit()"
```
These were accidentally removed in #6799. Caught by internal tests.
> Hparams: Fix regression in column selector.

- tensorboard/webapp/widgets/custom_modal/custom_modal_test.ts
Similar to #6810 but for a test file. This is not strictly necessary for the internal import (these tests are not run internally) but I figured it would be good to do for completeness.
> Build: Import 'first' from 'rxjs/operators' (again).

- tensorboard/plugins/projector/README.md
The output file for the standalone version was changed from generating an `index.html` file to generating a `standalone.html` file in #3933, but the README file was not updated with the new url.
Reported in #6795.
> Fixes documentation from projector plugin when running in standalone mode.

- tensorboard/pip_package/requirements.txt
The protobuf release 5.26.x is the first one in the major version 5, which introduces a breaking change.
This change adds a restriction on that dependency. See #6808 for details.
> Restricts the protobuf dependency to be < 5.0.0, due to a recent breaking change.

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
Context menus in Time series scalar tables are ready for use
Removes the enableScalarColumnContextMenus feature flag and associated code
Manually tested context menus in runs table, filterbar, scalar tables
> Sets defaultvalue of enableScalarColumnContextMenus to true

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
- tensorboard/plugins/hparams/metrics.py
- tensorboard/plugins/hparams/tf_hparams_utils/tf-hparams-utils.ts
In the Hparams plugin, when fetching metrics (scalar data) for multiple experiments in the comparison view, we can't replace group name `.` with an empty string. 
Googlers, see b/332308243 for more details.
Tested internally: cl/582334596
#hparams #oncall
> Hparams: fix metrics loading when group name is "."

- .github/workflows/ci.yml
- DEVELOPMENT.md
- tensorboard/plugins/graph/graphs_plugin_v2_test.py
- tensorboard/plugins/graph/keras_util.py
- tensorboard/plugins/graph/keras_util_test.py
This should fix the issue described in https://github.com/tensorflow/tensorboard/issues/6686. Compared the graph content with the one parsed from Keras 3, there are some changes in the structure and naming, this PR modifies the graph parsing accordingly.
Googlers, see b/325451531 and b/312739672.
Tested with `tensorboard/plugins/graph:graphs_demo`:
#keras3 #oncall
> Migrate graph plugin to Keras 3 and remove dependencies on Keras 2 and tf-keras-nightly

- tensorboard/plugins/graph/keras_util.py
Currently inbound node parsing is not backward compatible with Keras 2. Instead of failing directly, changed the code to return empty inbound node results.
Googlers, see the description in cl/622948159 for context.
Tested internally: cl/582334596
#keras3 #oncall
> Avoid failing directly when parsng Keras 2 layers

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/data_source/saved_pins_data_source.ts
- tensorboard/webapp/metrics/data_source/saved_pins_data_source_test.ts
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/effects/metrics_effects_test.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
- tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts
- tensorboard/webapp/metrics/views/main_view/pinned_view_container.ts
Following #6821 As pin data is accumulated, unwanted pins can easily crowd the dashboard. Therefore, this PR adds a button that allows users to conveniently clear all pins at once.
* 57c6a47 Introduced new action called `metricsClearAllPinnedCards`
* When `metricsClearAllPinnedCards` is dispatched, the reducer removed all pinned cards in the state.
* a04c2d7 Added `clear all pins` button in the pinned view container.
* The button will be shown if there's at least one pinned card.
* f0c3a54 Implemented `removeAllScalarPins` method in the saved pins data source.
* This method removes stored pins from local storage.
* e97b110 Added `removeAllPins` effect in the `metrics/effects/index.ts`
* When `metricsClearAllPinnedCards` action is called, this effect will call `removeAllScalarPins` method …
> [Global pins] Add clear all pins button

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/metrics_module.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors_test.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
- tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
Following #6828,
Since global pins are applied automatically, this PR allows users disable the global pin feature.
2cf2b11 Added `savingPinsEnabled` in the `MetricsSettings`
* Also added a selector getting `settings.savingPinsEnabled` value from the store.
dec6a63 Introduced new action `metricsEnableSavingPinsToggled`
* If `metricsEnableSavingPinsToggled` is dispatched, it toggles the `savingPinsEnabled` store value.
6ea22fd Added a checkbox UI to the settings view component.
* Also added a feature flag guard to the component. If check box is clicked, it dispatched  `metricsEnableSavingPinsToggled` action.
568febf Added a new effect `disableSavingPins`
* When `metricsEnableSavingPinsToggled` action is called, this effect will call `removeAllScalarPins` method if `savingPinsEnabled` value …
> [Global Pins] Added a disabling global pins feature

- tensorboard/components/tf_markdown_view/tf-markdown-view.ts
Some users require the spaces to be preserved in the text shown in the text dashboard.
At the moment I can't think of a reason why not to enable this unconditionally. I imagine anybody interested in seeing text logged would be interested in the value *verbatim*, including spaces.
Googlers, see b/335770352
> Preserve white space in text plugin.

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
In 3p, enabling standard (non-hparam column) hide is currently dangerous as there is currently no way to re-show them. Enabling for 3p will have to wait until we add an affordance other than the 1p-only column customizer.
Affected users can clear localStorage for the page, or add the `enableScalarColumnCustomization=true` flag to enable the column customizer in the settings menu and re-add hidden columns.
Sets `enableScalarColumnContextMenus` default to `false`. (Reverts #6817)
> Re-disables enableScalarColumnContextMenus flag

- tensorboard/webapp/metrics/views/card_renderer/BUILD
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/runs/views/runs_table/BUILD
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.ts
- tensorboard/webapp/runs/views/runs_table/runs_data_table_test.ts
Using functions in Angular templates leads to unnecessary recomputation, e.g. getHeaders() is called 60 times from data tables on init and add). More seriously, they also interfere with other component usage like CDK Overlay: namely, when an Overlay is set to appear next to a header, the header element is destroyed and recreated (because of the function in the template) before the Overlay can position itself, and ends up always resetting its position to (0,0). Simply memoizing the function will prevent the recomputation ([Angular ref](https://angular.io/guide/change-detection-slow-computations#optimizing-slow-computations)).
Profiling the memoized change (using Chrome devtools profiler, which is admittedly a bit inconsistent) seems to show a several 100ms improvement in scripting …
> Memoizes the functions for getting header both runs and scalar data tables

- tensorboard/webapp/metrics/BUILD
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/effects/metrics_effects_test.ts
This PR fixes the renaming in #6831 and adds test cases to make the test robust. 
* Tried to rename `disableSavingPins` to `removeSavedPinsOnDisable`, but #6831  accidentally changed `removeAllPins` to `removeSavedPinsOnDisable`.
* Added test cases + cl TAP presubmit passes
> [Global pins] Correct the incorrect name change and add test cases

- tensorboard/webapp/metrics/views/right_pane/saving_pins_checkbox_component.ts
Theme color was not applied to the checkbox. 
Apply `color="primary"` to the `saving_pins_checkbox_component`
AS-IS
TO-BE
tested with ` tb_theme=corp`  & TAP presubmit passes
> [Global Pins] [Quick Fix] Apply theme color to the check box

- tensorboard/webapp/metrics/data_source/saved_pins_data_source.ts
- tensorboard/webapp/metrics/data_source/saved_pins_data_source_test.ts
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/effects/metrics_effects_test.ts
- tensorboard/webapp/metrics/testing.ts
Feature request during the teamfood: `Clicking disable pins -> pinning a card -> clicking enable pins` doesn't save the currently pinned card. It seems reasonable to save all currently pinned cards when the setting is activated.
This PR saves all currently pinned cards when user clicks enable global pins.
* 97c6324389e1a9a5f51b89e5e33b0665ead533a4 Added `saveScalarPins` to the data source
* c6be93b Modified `addOrRemovePinsOnToggle` logic to include adding pins logic
*  Previously, if a user disabled the global pin feature, all pins would be removed. 
*  This PR added logic that will cause all currently pinned cards to be saved to local storage when the user activates the feature.
N/A
Unit test passes
N/A
> [Global Pins] Saves all currently pinned cards if the user has enabled global pins.

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
launch global pins feature by enabling the feature by default 
https://screenshot.googleplex.com/7WaVHXBFfAfHYUk
* Needs to update scuba test images after this PR is merged
> [Global pins] enable globalpins by default

- tensorboard/webapp/runs/views/runs_table/BUILD
This was missing when #6847 was merged, but it's causing some build errors in internal repo due to more strict dependency checks (this target is currently used via transitive dependencies).
> Adds import that was used via a transitive dependency.

- .github/workflows/ci.yml
- tensorboard/plugins/graph/keras_util.py
Keras' output format was slightly changed in https://github.com/keras-team/keras/pull/19711; for non-input layers dtypes will now be exported as a config map instead of just a string.
This fixes test breakages when using ToT keras.
Alternative to #6855
> Fix keras dtype importing and unpin for CI

- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/graph/keras_util.py
- tensorboard/plugins/graph/keras_util_test.py
Following-up on PR #6857, which seems to have introduced a regression for issue #5548.
This change just gracefully degrades the functionality to avoid crashing on an error (as it was before the recent change in #6857), but it might not be a proper fix for the scenario described in that issue.
> Fixes regression for issue #5548: Avoid attempting to convert dtypes from "mixed precision" policy types.

- tensorboard/webapp/routes/dashboard_deeplink_provider.ts
- tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
- tensorboard/webapp/runs/store/utils.ts
- tensorboard/webapp/runs/store/utils_test.ts
There was a problem when user tried to 1) enable coloring by experiment name, 2) trying to add more experiments. It stemmed from not implementing the serialization and deserialization of REGEX_BY_EXP in the query pararms of the route. To followup the #6846 and #6847 I have added the 'regex_exp:' as a query parameter for coloring by experiment name.
To fix the issue with the new feature. 
Added `regex_exp:` query param for serialization and deserialization of `REGEX_BY_EXP` GroupBy. It ensures that whenever user share the URL the filter will remain in place. 
1) Enable the coloring by experiment name.
2) Try to add more experiments via pressing `Add more experiments` in the top panel.
> Fix the issue with coloring when trying to add more experiments.

- tensorboard/plugins/graph/keras_util_test.py
A recent change in Keras broke these tests. I believe it's related to keras-team/keras#19805, which caused a name change in the names of the nodes in the graph, but not too sure.
Updates the affected test, but leaves it commented out, because when this code is imported into the internal repository on our side, before the keras update does, our project would break, as the keras change would not be synced internally yet.
Once this is sycned to our internal repo, and keras is able to sync theirs (without breaking us), we can enable the test and it should work fine.
N/A
Ran tests with keras-nightly before and after the change, and they pass. Then commented out the test for the reason noted above.
N/A
> Update tests to be compatible with recent keras update.

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 2.17.0 release process:
- Bump tb-nightly version to 2.18.0a0
- Cherrypick of 2.17.0 relnotes added to RELEASE.md
> Post release 2.17.0

- tensorboard/compat/tensorflow_stub/dtypes.py
- tensorboard/util/tensor_util.py
Nightlies are failing due to new numpy release(one example: https://github.com/tensorflow/tensorboard/actions/runs/9546526095/job/26309613783)
The new numpy replaced np.string_ with np.bytes_ and np.unicode_ with np.str_
I ran tests that were failing and they passed.
Locking numpy version < 2 was considered. However, this will eventually get us very out of date and should be avoided.
> Update usage of numpy to reflect numpy 2.0 changes

- tensorboard/webapp/notification_center/_views/notification_center_component.scss
An upcoming change in Angular Material (https://github.com/angular/components/pull/29291) changes the `z-index` of icons which ended up putting it behind the notification dot.
This change adds an explicit `z-index` to the dot to ensure that it's on top of the icon.
> Fix stacking of notification dot

- tensorboard/webapp/settings/_views/settings_dialog_component.css
When we migrated all the MDC components a year or so ago we missed the size of the fields in the settings dialog changing. This should restore the original intention there.
Before:
After:
> :bug: :gear:  Fix settings dialog styling regression

- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_container_test.ts
- tensorboard/webapp/plugins/testing/index.ts
- tensorboard/webapp/testing/integration_test_module.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_testing.ts
- tensorboard/webapp/webapp_data_source/tb_http_client_testing.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_testing_module.ts
- tensorboard/webapp/widgets/resize_detector_testing_module.ts
This PR is for the LSC that will add `jit: true` to all `@Directive`, `@Component` and `@NgModule` classes that are not AOT compatible.
Commonly in Google3, TypeScript test files are part of a `ts_library` or a `ng_module w/ testonly=True`. These targets simply run the TypeScript compiler from Microsoft, without any specific Angular processing. This allows code to exist that isn't necessarily compatible with Angular's compiler that strictly checks e.g. components 
This LSC adds `jit: true` to those components to clearly indicate that those components are not processed by the Angular compiler. This is a no-op because the Angular compiler doesn't even run on these files (as said above). In the future, we would like to change this, and need clear indication of what is incompatible or not. …
> LSC — Explicitly mark AOT incompatible targets via 'jit:true'

- tensorboard/pip_package/requirements.txt
- tensorboard/plugin_util.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/hparams/hparams_plugin.py
Instead of restricting `protobuf<5.0.0` due to the removal to `including_default_value_fields` kwarg in `json_format.MessageToJson` (replaced by `always_print_fields_with_nopresence`), we can instead detect the currently installed protobuf version and use the appropriate kwarg.
Contributes to #6808 and should resolve #6887.
> Relax `protobuf<5.0.0` restriction

- tensorboard/webapp/widgets/custom_modal/custom_modal.ts
On some browsers, the [custom modal close](https://github.com/tensorflow/tensorboard/blob/0627ad5480b309a5f3f69f39e52670496c2e5863/tensorboard/webapp/widgets/custom_modal/custom_modal.ts#L116) logic will be triggered immediately after releasing the right click button, which causes the modal to be closed as soon as it is opened.
The modal close event handler will ignore the `auxclick` (right click) mouseup event. Modals can still be closed with left clicks and the `contextmenu` event.
Status quo: ![image](https://github.com/user-attachments/assets/5b4c0c8f-4878-4cbe-a46a-cd425c188061)
> Custom modal aux click

- RELEASE.md
- tensorboard/BUILD
- tensorboard/compat/tensorflow_stub/dtypes.py
- tensorboard/pip_package/requirements.txt
- tensorboard/plugin_util.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/util/tensor_util.py
- tensorboard/version.py
- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_container_test.ts
- tensorboard/webapp/notification_center/_views/notification_center_component.scss
- tensorboard/webapp/plugins/testing/index.ts
- tensorboard/webapp/settings/_views/settings_dialog_component.css
- tensorboard/webapp/testing/integration_test_module.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_testing.ts
- tensorboard/webapp/webapp_data_source/tb_http_client_testing.ts
- tensorboard/webapp/widgets/custom_modal/custom_modal.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_testing_module.ts
- tensorboard/webapp/widgets/resize_detector_testing_module.ts
- yarn.lock
This patch release resolves some underlying dependency issues, most notably:
* Relaxing protobuf dependency restrictions
* Numpy 2.0 compatibility updates
These commits prepare for the release. I will rebase and merge them.
> TensorBoard 2.17.1 Release

- tensorboard/pip_package/requirements_dev.txt
We're seeing issues when trying to build our wheels which resolve when upgrading to a newer virtualenv version.
> Relax development `virtualenv` dependency versioning

- tensorboard/webapp/metrics/views/main_view/card_groups_container.ts
- tensorboard/webapp/metrics/views/main_view/empty_tag_match_message_container.ts
- tensorboard/webapp/metrics/views/main_view/main_view_component.ts
- tensorboard/webapp/metrics/views/main_view/main_view_container.ts
There is an ongoing LSC cl/652971829 which changes how instance methods are set. The change is blocked because of our split codebase. This PR is intended as a replacement for go/tbpr/6882
> Unblock LSC - Patch 1 - Fix initializer of instance members that reference identifiers declared in the constructor

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container.ts
- tensorboard/webapp/core/views/hash_storage_container.ts
- tensorboard/webapp/core/views/page_title_container.ts
- tensorboard/webapp/feature_flag/views/feature_flag_modal_trigger_container.ts
- tensorboard/webapp/header/dark_mode_toggle_container.ts
- tensorboard/webapp/header/plugin_selector_container.ts
- tensorboard/webapp/header/reload_container.ts
- tensorboard/webapp/metrics/effects/index.ts
- tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/reloader/reloader_component.ts
- tensorboard/webapp/runs/views/runs_selector/runs_selector_container.ts
- tensorboard/webapp/runs/views/runs_table/filterbar_container.ts
- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
- tensorboard/webapp/settings/_views/polymer_interop_container.ts
- tensorboard/webapp/settings/_views/settings_button_container.ts
- tensorboard/webapp/settings/_views/settings_dialog_container.ts
There is an ongoing LSC cl/652971829 which changes how instance methods are set. The change is blocked because of our split codebase. This PR is intended as a replacement for go/tbpr/6883
> Unblock LSC - Patch 2 - Fix initializer of instance members that reference identifiers declared in the constructor

- tensorboard/pip_package/requirements_dev.txt
This avoids issues during test due to incompatibility between the installed pandas and numpy versions:
`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`
> Relax pandas dev dependency

- tensorboard/compat/proto/proto_test.py
I've ran into linter / formatting issues the last couple of times I've ran the proto sync script, so this is expanding the instructions to run the `buildifier` tool after the proto sync is made.
> Update instructions to sync TF compat protos

- tensorboard/BUILD
This is updating our OSS code with a change made in cl/678434606, to prevent that change being reverted next time we sync our code to the internal code base.
This target is intended to expose part of the public API of TensorBoard, but it does not include all the underlying dependencies, so it could lead to issues if other dependencies are not included otherwise.
I expect the explicit naming of `lib_init_only` should be enough to note this, so the visibility was changed to allow a new client to include it as a dependency.
> Update visibility of `lib_init_only` target

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 2.18.0 release process:
- Bump tb-nightly version to 2.19.0a0
- Cherrypick of 2.18.0 relnotes added to RELEASE.md
> Post release 2.18.0

- tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
- tensorboard/webapp/app_routing/route_config_test.ts
- tensorboard/webapp/app_routing/views/router_link_directive_container.ts
- tensorboard/webapp/feature_flag/directives/feature_flag_directive.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
- tensorboard/webapp/widgets/intersection_observer/intersection_observer_testing_module.ts
- tensorboard/webapp/widgets/resize_detector_directive.ts
- tensorboard/webapp/widgets/resize_detector_testing_module.ts
Angular v19 is going to change the default value for `standalone` from `false` to `true`. Even though tensorboard is on an older version of Angular on GitHub, the version inside Google runs at HEAD. We're in the process of changing existing code in google to explicitly set `standalone: false` for existing code, so I'm sending this change to the source of truth here.
This is a follow-up to #6912, which missed a handful of places.
> Explicitly set `standalone` for all Angular directives

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container.ts
- tensorboard/webapp/core/effects/core_effects.ts
- tensorboard/webapp/feature_flag/views/feature_flag_dialog_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_container.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
- tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
- tensorboard/webapp/metrics/views/metrics_container.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
- tensorboard/webapp/plugins/plugins_container.ts
- tensorboard/webapp/runs/effects/runs_effects.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
Move the initializer into the constructor for instance members that reference identifiers declared in the constructor.
Googlers, see cl/683332949 for more details.
> LSC cl/683332949 - Move initializers into constructors.

- docs/get_started.ipynb
As title. Current code no longer runs in the newer TF version (2.17.0 on Colab) with the following error / warning:
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-19-f1056f2ad84b>](https://localhost:8080/#) in <cell line: 5>()
24 
25   # Reset metrics every epoch
---> 26   train_loss.reset_states()
27   test_loss.reset_states()
28   train_accuracy.reset_states()
AttributeError: 'Mean' object has no attribute 'reset_states'
```
```
/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
super().__init__(**kwargs)
```
N/A
N/A
Run on …
> Update legacy API usage in get_started.ipynb

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
As communicated in [this announcement](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/), v3 of these actions is deprecated.
I followed [this example](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact) matching our use of these actions.
> Updates GH actions upload- and download-artifact to v4

- .mailmap
Hello! I used to work on TensorBoard full time. Then I changed my name. (👋!) I still consult this repo sometimes, so I'd like for my name to be updated and correct.
This patch adds a [Git mailmap], which is a plain text file that teaches Git to correct errors or duplication in user information. It transparently fixes the output of commands like `git shortlog` and `git show`, without needing to rewrite old hashes or destroy any information. I've initialized the mailmap with my name and also unified the email addresses to the one that I used most commonly (99.2% of the time).
Test Plan:
`git shortlog -nse | head` and see that my name is [spelled right now][wc].
[Git mailmap]: https://git-scm.com/docs/gitmailmap
[wc]: https://wchargin.com
> mailmap: update info for wchargin

- tensorboard/webapp/experiments/types.ts
> Adds a more generic 'url' field to a MetricsDataSource

- .github/workflows/ci.yml
macos 12 is deprecated so nightly PIP release is failing
> Use macos-13 in ci

- .github/workflows/ci.yml
Follow-up to #6936, where I missed one occurrence of this deprecated action.
As noted in the [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact), the upload action can no longer be called with the same name more than once within the same workflow, so the matrix values needs to be included in the name.
> Updates missed GH upload-artifact action to v4

- tensorboard/plugins/hparams/list_session_groups_test.py
> Updates deprecated alias 'assertEquals' with non-deprecated method name

- .github/workflows/ci.yml
Our nightly workflows started failing because the versions before 4.0.0 have been turned down. The new version is fully backwards compatible, according to the [documentation here](https://github.com/actions/toolkit/tree/main/packages/cache#%EF%B8%8F-important-changes), so it should just be a matter of updating the version.
> Updates GH actions/cache version to v4

- tensorboard/pip_package/setup.cfg
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
- tensorboard/webapp/theme/_tb_theme.template.scss
Add `--mat-` prefixed variables alongside `--mdc-` variables because Angular Material will be renaming these tokens internally. This rename will occur in v20, which is used internally. The `--mdc-` tokens will continue to be defined since this still depends on an older version of Angular Material externally.
Includes necessary update to `tensorboard/pip_package/setup.cfg`, using underscore instead of dash-case for `description_file`
```
python3.11/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options      
********************************************************************************
Usage of dash-separated 'description-file' will not be supported in future
versions. Please use the underscore name 'description_file' instead.
This deprecation …
```
> use Angular Material overrides API

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
- tensorboard/webapp/theme/_tb_theme.template.scss
Angular v15, which is the one currently used in the OSS repo, uses styles with format `--mdc-` to style material components.
Later versions of angular migrated to a `--mat-` prefix, and Angular v20 will update some of the names again.
Our internal codebase uses the styles defined internally, so we need to use the new format.
We recently set up translations internally from these "old" `--mdc-` stylings to the newer `--mat-` names, so we don't need them duplicate here, which could potentially be a source for confusion.
Googlers, see cl/744892387 and cl/744895577 for some details.
Remove some scss lines that are unused in the public repo.
> Removes duplicate style specs.

- .github/workflows/ci.yml
This old version of Ubuntu is no longer available: https://github.com/actions/runner-images/issues/11101
> Update Ubuntu version used to run data-server-related workflows

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/_lib.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.scss
- tensorboard/webapp/feature_flag/views/feature_flag_dialog_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/vis_linked_time_selection_warning_component.scss
- tensorboard/webapp/metrics/views/main_view/filter_input_component.scss
- tensorboard/webapp/metrics/views/main_view/main_view_component.scss
- tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
- tensorboard/webapp/metrics/views/metrics_container.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/notification_center/_views/notification_center_component.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss
- tensorboard/webapp/theme/_tb_palette.scss
- tensorboard/webapp/theme/_tb_theme.template.scss
- tensorboard/webapp/theme/_variable.scss
- tensorboard/webapp/widgets/card_fob/card_fob_component.scss
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/context_menu_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/filter_dialog_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/dropdown/dropdown_component.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
Required for internal cl/753816882
> Add a prefix comment for M2 Sass APIs to allow transformations to occur internally

- tensorboard/webapp/alert/effects/index.ts
- tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
- tensorboard/webapp/notification_center/_redux/notification_center_effects.ts
- tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts
- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
When tsc's `--target` is updated `es2022` or newer, the initialization order of parameter properties changes. Inline field initializers that directly or indirectly reference parameter properties can break with this change as the parameter properties may be initialized if the reference occurs too soon.
This can be difficult to accurately statically detect because it's not always clear if callbacks are executed immediately or later.
Migrating to Angular's `inject()` function solves the problems as parameter properties are no longer used.
Updates classes where some inline field initializer has an indirect reference to a parameter property to use Angular `inject()`.
N/A
Should be a no-op refactor. Simply verify test flows the involve all modified classes.
We could also avoid this upcoming …
> Migrate Angular code to call inject()

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/_lib.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.scss
- tensorboard/webapp/feature_flag/views/feature_flag_dialog_component.scss
- tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/metrics/views/card_renderer/vis_linked_time_selection_warning_component.scss
- tensorboard/webapp/metrics/views/main_view/filter_input_component.scss
- tensorboard/webapp/metrics/views/main_view/main_view_component.scss
- tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
- tensorboard/webapp/metrics/views/metrics_container.scss
- tensorboard/webapp/metrics/views/right_pane/saving_pins_checkbox_component.scss
- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.scss
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
- tensorboard/webapp/notification_center/_views/notification_center_component.scss
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss
- tensorboard/webapp/theme/_tb_palette.scss
- tensorboard/webapp/theme/_tb_theme.template.scss
- tensorboard/webapp/theme/_variable.scss
- tensorboard/webapp/widgets/card_fob/card_fob_component.scss
- tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/context_menu_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/filter_dialog_component.scss
- tensorboard/webapp/widgets/data_table/header_cell_component.scss
- tensorboard/webapp/widgets/dropdown/dropdown_component.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
- tensorboard/webapp/widgets/range_input/range_input_component.scss
This is a simple squash and cleanup of the following PRs which are intended to unblock an internal lsc
#6995
#6996
#6997
> Unblock mat lsc

- tensorboard/plugins/projector/projector_plugin_test.py
This method has been deprecated since version 1.14, and it started raising an error in 2.3, according to the [release notes](https://github.com/numpy/numpy/releases/tag/v2.3.0rc1)
A replacement with more appropriate semantics exists, so this change updates that use case to use the appropriate, non-deprecated method `frombuffer`.
Googlers, see b/422161123.
> Replaces deprecated use of numpy#fromstring method with #frombuffer

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- third_party/workspace.bzl
This was a deprecated call to a no-op function. The function has now been removed in a newer version of the library. We need to support this newer library version to unblock an internal lsc Googlers see cl/771125806
I also needed to add a new source for the jsoup dependency. Previously this was being provided by the operating system (CI currently uses ubuntu 22.04 lts), but that version is now 3 years out of date.
> Remove deprecated call to flatDoc.normalize

- .github/workflows/ci.yml
- third_party/python.bzl
`urllib3` is a transitive dependency that "vendors" the `six` library in it, but the version of `six` vendored within the version of urllib3 that our code was using is not compatible with python >= 3.12.
This newer version is still within the major version number, but [after 1.26.5, which updated the vendored version of `six`](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#1265-2021-05-26) to one that runs with python >= 3.12.
> Updates version of urllib3 used by bazel

- docs/tensorboard_projector_plugin.ipynb
> fix spelling error
