- tensorboard/__main__.py
- tensorboard/pip_package/BUILD
- tensorboard/pip_package/MANIFEST.in
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/setup.py
It's called tensorflow-tensorboard for now.
I didn't add TensorFlow as a requirement, yet. This is because none of the currently released pip packages will support the APIs we need; to get this to work, you need to manually install a TF nightly.
Once tf1.2 is released, I'll add a dependency on tf >= 1.2
> Add ability to build a pip package.

- .gitignore
One line change. Let me know if you want anything else in the .gitignore while I'm at it.
> Ignore IntelliJ configuration directory

- tensorboard/components/vz_line_chart/dragZoomInteraction.ts
- tensorboard/components/vz_line_chart/vz-line-chart.ts
Replaces https://github.com/tensorflow/tensorflow/pull/10310
Fixes https://github.com/tensorflow/tensorboard/issues/36
> Don't unnecessarily reset y domain on line charts

- README.md
Also, out of vague respect for line lengths, I moved long links onto their own lines.
> Fix link in the README

- tensorboard/components/tf_categorization_utils/BUILD
- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/tf-categorization-utils.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
Until now, we've had a `tf-categorizer` component that renders a regex
input field and outputs a set of categories as a Polymer property.
The set of categories then needed to be post-processed; this was done by
`tf-panes-helper`. This commit exposes a function that performs the
categorization and post-processing all at once. It exposes data in
either of two forms: grouped by tag (used by the scalars dashboard), or
grouped by run-tag combination (to be used by the histogram dashboard).
The emitted data is of suitable form to be used as the `items` of a
`<dom-repeat>`, as we demonstrate in the scalars dashboard.
Test Plan:
The function `categorizeRunTagCombinations` is not used as of this
commit. To test it, apply the patch
```diff
diff --git …
```
> Create categorization helpers for Polymer bindings

- third_party/js.bzl
> Update trace viewer dependency

- tensorboard/components/tf_dashboard_common/tf-no-data-warning.html
Fixes https://github.com/tensorflow/tensorboard/issues/126
> Fix wrog links to TensorBoard README

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/backend/event_processing/reservoir.py
- EventMultiplexer now lets us access the EventAccumulator objects.
- EventAccumulator now lets us access the Reservoir objects.
- Reservoir now has fields visible showing us how it was configured.
> Open up some event_processing APIs

- tensorboard/plugins/projector/projector_config.proto
This fixes issues with multiple protos having the same package.
> Update package in projector/projector_config.proto

- tensorboard/backend/application.py
- tensorboard/main.py
This is so we can fix the MPM internally.
> Add assets_zip_provider delegates

- tensorboard/BUILD
- tensorboard/test_util.py
These classes are useful for testing many types of production code, without introducing nondeterminism or slowness.
> Introduce FakeClock and FakeSleeper

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
The Polymer team made a few modifications that have no effect now, but are important for future compatibility.
> Rexport changes made inside Google.

- tensorboard/BUILD
- tensorboard/loader.py
- tensorboard/loader_test.py
- tensorboard/test_util.py
- tensorboard/util.py
This change fixes the build flakiness that was caused by fea144d. I added some
documentation and logging utilities, took a really close look at what was
happening, and ironed out a few more edge cases.
> Further refine BufferedRecordReader

- tensorboard/plugins/projector/vz_projector/vz-projector-input.html
Change was made by Googlers, I'm just exporting it.
> More upstream Polymer futureproofing.

- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
The run name is currently a timestamp like "YYYY-MM-DD_HH:MM:SS".
Sort runs by timestamp in reversed order so that the latest run comes first.
> [profile] Sort runs properly.

- tensorboard/plugins/projector/vz_projector/data-provider.ts
Previously, the projector would hang on "Parsing metadata" when the metadata cannot be found because the projector frontend code tries to parse an error message retrieved from the server. This happened because the frontend relied on the request.onerror handler to handle errant cases. That handler only ran when network errors (404s) occurred. When the server responded with a 400 status, the onload handler was called. This behavior caused issue #247.
This change fixes that problem by instead using the onreadystatechange handler. The embedding projector now prints an error message:
> Show message when metadata cannot be found

- ADDING_A_PLUGIN.md
This draft was collectively written by @dandelion, @wchargin, @chizeng, and @jart
> Initial draft of the ADDING_A_PLUGIN.md document.

- tensorboard/BUILD
> Add exports_files(["LICENSE"]) to main BUILD

- tensorboard/defs/protos.bzl
- tensorboard/plugins/pr_curve/BUILD
- tensorboard/plugins/profile/BUILD
- tensorboard/plugins/projector/BUILD
Proto rules also made public in case anyone ever wants to parse their own event log data.
> Make proto build config more sync friendly

- tensorboard/plugins/histogram/metadata.py
- tensorboard/plugins/histogram/summary.py
wchargin-branch: histogram-docs
> Update histogram plugin documentation

- tensorboard/pip_package/pip_smoke_test.sh
to perform smoke test of the build, install and basic usage of the
tensorboard pip package.
> Add pip_smoke_test.sh

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
Other plugin names are plural.
> Rename pr_curve plugin to pr_curves

- tensorboard/BUILD
- tensorboard/db.py
- tensorboard/db_test.py
- tensorboard/test_util.py
- Added Experiments.name index
- Never allow an ID to be 0 just in case
- Make VARCHARs larger than 255 just in case
- Made DbTestCase lazy and put it in test_util.TestCase
> Refactor the db module a bit

- .travis.yml
But it won't build random branches.
> Have Travis build release branches

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager_test.py
- tensorboard/plugins/distribution/compressor.py
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/pr_curve/summary_test.py
- tensorboard/plugins/projector/projector_plugin_test.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/plugins/text/text_plugin_test.py
This is blocking sync. Many teams depend on those APIs internally.
> Restore event_processing APIs

- tensorboard/BUILD
> Remove superfluous build rule

- tensorboard/plugins/pr_curve/pr_curve_demo.py
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
Fixed lint issues related to indentation, trailing whitespaces. Removed an un-used import and an un-used variable.
> Fix lint issues related to the pr_curves plugin

- tensorboard/defs/vulcanize.bzl
- tensorboard/plugins/pr_curve/pr_curves_plugin.py
These changes came up in the sync process.
> Fix depset and license header

- tensorboard/components/tf_color_scale/palettes.ts
Reorder colors in the random order suggested by Paul Toh. #449
> Reorder colors in the random order suggested by Paul Tol.

- tensorboard/pip_package/pip_smoke_test.sh
1) Refactor the test HTTP request into a bash funciton for modularity.
2) Previously, the script tested only the "/data/logdir" path, which
means the test wouldn't have caught the breakage due to, e.g.,
'webfile.zips' being omitted from package_data in setup.py, which
has happened before. This change adds a check of the "/" path in
order to cover that.
3) Do tensorboard process shutdown and temp file cleanup even if the
test fails.
> Improve pip_smoke_test.sh

- CONTRIBUTING.md
For now, this CONTRIBUTING.md file merely tells contributors to sign a
CLA. Fixes #398.
> Add a brief CONTRIBUTING.md

- tensorboard/BUILD
- tensorboard/pip_package/BUILD
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/profile/profile_demo_data.py
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_op_profile/BUILD
- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/profile/tf_op_profile/utils.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
- tensorboard/plugins/projector/vz_projector/data-provider.ts
- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
- tensorboard/summary.py
- tensorboard/summary_test.py
- tensorboard/version.py
- third_party/polymer.bzl
This patch release proposal grants a semver policy exception to @ioeric by cherry-picking feature code for the TPU Profiling plugin. This seems reasonable to me, since the plugin itself was only introduced quite recently. The rest of the picks are my curation of bug fixes.
Cursory local testing building, installing, and running the pip package look good. Feel free to test on your own. Feel free to request additional picks.
PyPi upload will most likely happen on Monday or Tuesday.
> Cherry picks for TensorBoard 0.1.7

- tensorboard/pip_package/setup.py
> Update required version of html5lib to 1.0b10

- WORKSPACE
- third_party/workspace.bzl
I figured out why we didn't need that if statement :)
> Revert accidental WORKSPACE change

- tensorboard/plugins/graph/tf_graph_common/render.ts
The `buildSubhierarchy` and `cloneFunctionLibraryMetanode` methods have been growing a lot. To make them more legible, this change moves some logic within them to new helper methods:
* cloneLibraryMetanodeEdges
* patchEdgesIntoFunctionInputs
* patchEdgesFromFunctionOutputs
* buildSubhierarchiesForNeededFunctions
Fixes #573.
Test plan: Load the pbtxt attached to the PR into the graph dashboard. Expand one of the (hatched) function nodes. The explorer should WAI.
[mnist_with_functions.pbtxt.txt](https://github.com/tensorflow/tensorboard/files/1339728/mnist_with_functions.pbtxt.txt)
> Make helper methods related to visualizing functions

- tensorboard/components/vz_line_chart/vz-line-chart.ts
Update vz-line-chart to have default values for the three required fields: xComponentsCreationMethod, yValueAccessor, tooltipColumns. This makes vz-line-chart backwards compatible with old functionality, and also serves to document the API.
> Add old default values to vz-line-chart

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
This commit is a simple solution for issue #265. However, using single letter group (e.g. f:/bar) will break. Shall I add a safety check?
> fix for issue #265

- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/__init__.py
- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/client_side/BUILD
- tensorboard/plugins/beholder/demos/demo/BUILD
- tensorboard/plugins/beholder/demos/demo/__init__.py
- tensorboard/plugins/beholder/demos/demo/demo.py
- tensorboard/plugins/beholder/file_system_tools.py
- tensorboard/plugins/beholder/im_util.py
- tensorboard/plugins/beholder/server_side/BUILD
- tensorboard/plugins/beholder/server_side/beholder_plugin.py
- tensorboard/plugins/beholder/shared_config.py
- tensorboard/plugins/beholder/video_writing.py
- tensorboard/plugins/beholder/visualizer.py
- Add license headers and build declarations
- Run buildifier on BUILD files
- Fix Python imports in certain places
No other style changes have been made. We can make the deeper fixes
once we get it working in this repo.
> Minor cleanup of Beholder code

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
> Change default value of tag filters to empty

- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/client_side/beholder-dashboard.html
- tensorboard/plugins/beholder/demos/demo/demo.py
> Fix issue #654 Simple BeholderHook to work with tf.train.MonitoredSession

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
This was requested by the Closure Compiler team.
> Use ECMASCRIPT_2017

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
This is a manual sync of cl/172687149. CC: @rictic
> Update deprecated Polymer code

- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
The custom scalars plugin had been responsible for catching a KeyError
within its `is_active` and `layout_impl` methods. Now, the plugin calls
`PluginRunToTagToContent` to retrieve the runs that have layouts.
Note that `PluginRunToTagToContent` still catches a KeyError within its
implementation. However, the plugin is no longer responsible for
catching the error.
Test Plan: Note that the custom scalars dashboard works when some run
has a layout. The plugin becomes inactive when I remove the events file
containing the layout from the log directory.
> Avoid catching KeyError within custom-scalars

- tensorboard/__main__.py
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/main.py
- tensorboard/pip_package/setup.py
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/version.py
This is a quick release to make sure the absl flags initialization thing (#716) doesn't impact tf-nightly users, since we don't have tb-nightly yet. It also includes some other fixes.
> TensorBoard 0.4.0-rc3

- tensorboard/plugins/profile/README.md
- tensorboard/plugins/profile/input_pipeline_analyzer/BUILD
- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/plugins/profile/input_pipeline_analyzer/utils.html
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
tools only activate when there are specific files in plugin-specific
directory, therefore should be safe right now.
> polymerize internal input pipeline analyzer tools for tpu profiler.

- tensorboard/plugins/custom_scalar/README.md
- tensorboard/summary.py
- tensorboard/summary_test.py
Also renamed the `custom_scalars_pb` method to `custom_scalar_pb`.
This is in line with how the `scalar` op is named.
> Rename the custom_scalars op to custom_scalar

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
to use the latest TensorBoradDebugWrapperSession and
TensorBoardDebugHook that were added to TensorFlow recently:
https://github.com/tensorflow/tensorflow/commit/72b4acc3ba121af7680a49b9519d4d4470c6a1f2
This leads to simpler usage.
> [Debugger Plugin]: Update Python code snippet

- tensorboard/components/tf_color_scale/colorScale.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-line-chart.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
Also slightly improve the error message from `colorScale.ts`.
> [Debugger Plugin]: Fix incorrect colorScale in line plots

- tensorboard/plugins/graph/tf_graph_common/render.ts
This PR fixes some issues that enable users to examine the intricacies
of nodes that represent functions:
* We only patch outputs of functions at the very end of cloning a
metanode that encapsulates its internal content. Previously, the graph
explorer patched edges from output nodes that did not exist.
* We render subhierarchies of metanodes only after extracting nodes from
the graph. Otherwise, the graph logic errs because it later tries to
construct edges to nodes that would later be extracted from the graph.
* We take into account how the last few inputs into a function might map
to the same node. Otherwise, edge-patching logic might reference a
non-existent node.
> Correctly render function nodes

- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
1. handle the case where host table is empty.
2. fix a typo which missing %.
3. handle the error where tpu step are not strictly monotonically
increasing.
4. fix the activeTools and selectedTool race condition.
5. fix the case where selectedTool is not changed between runs, however
the tools is actually changed.
> fix several bugs in profile plugins.

- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
make x-axis formatting as integer for vz-line charts
add axis caption for both x-y.
> [Plugin Profile] Format x-axis as integers and add captions.

- tensorboard/plugins/graph/tf_graph_common/op.ts
This snuck in because Travis doesn't seem to be launching our test jobs at all
today. See also: 50097ae30b5ca15a740c4902cd1ba8d1ca896ea1
TBR @chihuahua
CC @tayo
> Fix minor build breakage

- tensorboard/plugins/custom_scalar/custom_scalar_demo.py
> Fix custom scalar plugin demo to run in google internal.

- .travis.yml
- RELEASE.md
- tensorboard/backend/event_processing/event_file_inspector.py
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/pip_smoke_test.sh
- tensorboard/pip_package/setup.py
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/debugger_server_lib.py
- tensorboard/plugins/debugger/numerics_alert.py
- tensorboard/plugins/debugger/session_debug_test.py
- tensorboard/program.py
- tensorboard/scripts/generate_testdata.py
- tensorboard/version.py
- third_party/workspace.bzl
Cherry-picks for a few bug fixes but otherwise no changes.
See the newly added RELEASE.md for release notes that I prepared, please let me know if there's anything further I should add or remove from them.
> TensorBoard 0.4.0

- RELEASE.md
> Add 0.4.0 relnotes in RELEASE.md file

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html
> Fixed offset of checkbox label

- tensorboard/plugins/profile/README.md
- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
Add recommendations to users for how to reduce the overhead in different components of their input pipeline.  See the attached screenshot.
> Show performance recommendations to users (for improving the TPU input pipeline)

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-continue-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
* The caption and behavior of the 'Continue...' button is now set
dynamically, depending on whether we are in the middle of a
'continue-to' action. This helps with situations in which the
user wants to interrupt a continuation action halfway through, e.g.,
when it is realized that a certain tensor-value condition will not
be met by any of the watched tensors.
* Slightly adust the graph section of the top-right quadrant to make
it occupy a fuller section of the quadrant.
> [Debugger Plugin]: 'Continue...' button becomes 'Stop' during action

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Please see attached screeshot. Some links will only be accessible when they are available to the public.
> Added error message when no profile data was found.

- RELEASE.md
Cherrypick to add 1.5.1 relnotes back to master.
> Add 1.5.1 relnotes to RELEASE.md

- RELEASE.md
CHERRY-PICK of 1.6.0 relnotes from 1.6 branch onto master.
> [PICK] Add 1.6.0 relnotes to RELEASE.md

- tensorboard/plugins/pr_curve/README.md
> Fix F1 score formula in pr-curves README.md

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
Fixes #1003.  Also simplifies the code a bit overall; there's no need to pre-cache the first event times in a dict because the key function passed to sort will only be called once per element anyway (i.e. it will cache it internally).  At that point I think it's cleaner to just inline the key function to where it's used.
I also extended the testing of the run ordering to cover the no-started-timestamp cases.
> Fix attempt in _serve_runs() to .sort a py3 dict_keys

- tensorboard/components/vz_bar_chart/BUILD
- tensorboard/components/vz_bar_chart/vz-bar-chart.html
- tensorboard/components/vz_bar_chart/vz-bar-chart.ts
- tensorboard/components/vz_chart_helpers/vz-chart-helpers.ts
- tensorboard/components/vz_line_chart/vz-line-chart.ts
This new component will be used by the internal mutant inference plugin.
Thank you to @000drax for coding the component internally.
> Create vz_bar_chart component

- tensorboard/backend/application.py
- tensorboard/plugins/base_plugin.py
- tensorboard/program.py
Adding flags object to plugin context after discussion with Justine about enabling plugins to have access to all runtime flags.
> Add flags to plugin context

- .travis.yml
- RELEASE.md
- tensorboard/backend/application.py
- tensorboard/components/tf_tensorboard/registry.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/beholder/README.md
- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/beholder/file_system_tools.py
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
- tensorboard/version.py
This PR contains relnotes and a couple small bug fixes for our 1.7.0 release.
Please confirm the wording of the proposed release notes. I'd like to avoid making any further edits to them when merging them back into master's RELEASE.md.
cc @caisq
> Release 1.7.0

- RELEASE.md
Cherrypicking relnotes from #1073 onto master.
> CHERRYPICK: Add 1.7.0 relnotes to RELEASE.md

- tensorboard/plugins/pr_curve/BUILD
- tensorboard/plugins/pr_curve/pr_curves_plugin.py
- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
> Make PR curves plugin work in SQL mode

- third_party/polymer.bzl
Here's the diff of how this changed the TensorBoard HTML page:
https://gist.github.com/jart/8884ce9d4d5f60f5698640b35034f7eb
Editing this file is easy with Emacs: jart/justinemacs@b3fe4fa
> Roll forward some Polymer dependencies

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
Fixes: https://github.com/tensorflow/tensorboard/issues/1097
> [Debugger Plugin] Fix wrapper name for keras snippet

- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
These are the changes needed to make to the input_pipeline_analyzer to work with TensorFlow 1.8.
> Fix the input_pipeline_analyzer plugin for TensorFlow 1.8

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/api.proto
- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/error.py
- tensorboard/plugins/hparams/hparams_demo.py
- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/http_api.md
- tensorboard/plugins/hparams/list_session_groups.py
- tensorboard/plugins/hparams/list_session_groups_test.py
- tensorboard/plugins/hparams/metadata.py
- tensorboard/plugins/hparams/metrics.py
- tensorboard/plugins/hparams/plugin_data.proto
- tensorboard/plugins/hparams/summary.py
Hi @nfelt , @sagipe,
Please take a look! Thanks.
@sagipe: This is mostly the tensorboard-side implementation so feel free to pass on this.
> Initial backend implementation for the HParams plugin.

- .travis.yml
- RELEASE.md
- tensorboard/plugins/pr_curve/pr_curve_demo.py
- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/version.py
This PR contains relnotes and a couple small bug fixes for our 1.8.0 release.
> Release 1.8.0

- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
This has been causing surprising problems and it might not be needed anymore.
> Remove web_aspect

- tensorboard/plugins/debugger/debugger_plugin_testlib.py
This caused an issue with the sync process...
> Remove space from import line

- tensorboard/plugins/hparams/hparams_plugin.py
- tensorboard/plugins/hparams/list_session_groups.py
@jart Please take a look.
Thanks.
> Disable endpoints when hparams is not active

- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
> Remove cfg="data" from Skylark rules

- .travis.yml
- RELEASE.md
- tensorboard/version.py
This PR contains relnotes for our 1.9.0 release.
cc @qiuminxu, @caisq
> Release 1.9.0

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
tf-multi-checkbox component is a generic component. Untangle
business logic of tf-run-selector so it can be used more robustly.
> Moved runSelection persistence to an run selector

- tensorboard/components/tf_backend/BUILD
- tensorboard/components/tf_backend/baseStore.ts
- tensorboard/components/tf_backend/experimentsStore.ts
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/tf-backend.html
- tensorboard/components/tf_color_scale/colorScale.ts
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- Refactored runsStore to a BaseStore to reduce redundancy
- Refresh list of experiments (not plugged into UI) every x-seconds
> Added frontend side integration for experiments

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
_setIsolatorIcon was observing wrong property.
> Fixed typo: selectedName -> selectionState

- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/image/summary.py
- tensorboard/plugins/image/summary_test.py
HxWxC tensor is what's commonly used to represent images.
Also this function calls `util.encode_png` which expects HxWxC tensor.
> Fix reverse order of w & h

- tensorboard/components/tf_backend/experimentsStore.ts
- tensorboard/components/tf_color_scale/colorScale.ts
- tensorboard/components/tf_color_scale/test/colorScaleTests.ts
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
ColorScale and MultiCheckbox embedded runs business logic. Extract them out and make them more generic.
> Refactored colorScale and multi-checkbox

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
@nfelt @jart  -- I need this to be able to use the tf-scalar-card component with the hparams end-point.
Please take a look. Thanks,
Erez.
> Added dataUrl property to tf-scalar-card

- .travis.yml
- RELEASE.md
- tensorboard/version.py
> Release 1.10.0

- RELEASE.md
Copy 1.10.0 relnotes from 1.10 branch to master.
> CHERRYPICK: Add 1.10.0 relnotes to RELEASE.md

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/registry.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
When a plugin specify "useDataSelector", a selector will appear
on the top of the UI and selection will be injected to the plugin
via dataSelection property.
> Expose registry API for using data-selector.

- tensorboard/components/tf_markdown_view/tf-markdown-view.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
- Make custom scrollable region perform better when large DOM is inside
- scope CSS after an animation frame after the markdown DOM has been
mounted and is laid out.
> PERF: Make text plugin perform better

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Now, user can see how fresh/stale data is by hoving over the refresh
button.
> UX: show last updated time in refresh button

- tensorboard/components/tf_backend/BUILD
- tensorboard/components/tf_backend/environmentStore.ts
- tensorboard/components/tf_backend/tf-backend.html
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
We would like to be able to use information about environment in many
place and now we have a common place where we sync with the backend and
each component access data through the store.
When refreshing global storage, the refresh button spins for fun :)
> REFACTOR: common storage for environment

- tensorboard/components/tf_data_selector/tf-data-select-row.ts
After fetching runs for an experiment, we decide whether to default
select all runs for convenience or not.
> Default select runs based on number of runs

- tensorboard/components/tf_data_selector/tf-collapsible-data-selector.html
- tensorboard/components/tf_data_selector/tf-collapsible-data-selector.ts
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
A run can contain tags from various plugins. Filter out tags that
belongs to inactive plugins and runs without a tags.
> Filter out selection based on active plugins

- tensorboard/components/tf_backend/environmentStore.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Based on the backend mode, we now conditionally render and make use of
the data selector in the scalar plugin.
> Conditionally render tag/run selector in scalar

- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/components/tf_data_selector/type.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
This will allow us to color the runs in the single data selection mode
as opposed to data-selection comparison.
> Differentiate single from comparison mode

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.html
- tensorboard/plugins/profile/memory_viewer/memory_viewer_dashboard/memory-viewer-dashboard.html
- tensorboard/plugins/profile/memory_viewer/memory_viewer_dashboard/memory-viewer-dashboard.ts
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
- Sidebar line no longer intrudes the main content
- The sidebar tooltip properly renders
This addresses #1393
> Fixed the Profile plugin UI issues

- tensorboard/backend/event_processing/io_wrapper.py
- tensorboard/backend/event_processing/reservoir.py
TYPO: nonegative -> nonnegative
DOC: refactored a comment in io_wrapper
> Fixed typo and rewrote a part of comment for clarity

- tensorboard/components/tf_data_selector/tf-data-selector.ts
`_selection` can be added in non-deterministic way. Use the persisted
enable experiment ids, which is in order of insertion, to order the
selection.
> Order selection as persisted

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- When you drag zoom, it shows crosshair
- When pressing down alt for pan, it shows hand
- When panning, it shows closed hand
> UX: show cursor on chart for affordance

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 1.11.0 release process:
- Bump tb-nightly version to 1.12.0a0
- Cherrypick of 1.11.0 relnotes added to RELEASE.md
> Post-release 1.11.0

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-source-code-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.ts
- tensorboard/plugins/profile/overview_page/overview-page.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Category of changes
- Mistypes in property (i.e., string -> number, Object -> Function)
- Misspell
- Missing function type info with seldom missing arguments
- Missing Polymer property
Remaining issues that won't be addressed are:
- inheritance from Polymer behaviors
- setting `null` on a Polymer property (which cannot be declared as nullable at least at the moment)
- Closure wants `addEventListener`'s third option argument
> CLEANUP: addressed Closure compiler warns

- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- Coloring: when experiment name includes "/", scalar dashboard failed
to color the plots properly
- Exp name: experiment name in the data selector better draws
- Row margin: removed awkward margin between each data selection rows
> Fixed UX issues found with db_import

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
- tensorboard/plugins/graph/tf_graph_controls/BUILD
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- More space for the controls
- Now run dropdown appears without serious clipping (#47)
> Adjust graph plugin sidebar for usability

- tensorboard/plugins/profile/overview_page/overview-page.html
Put error message and main contents in divs under the same template.
> Fix a bug that overview page sometimes doesn't render.

- tensorboard/components/tf_card_heading/BUILD
- tensorboard/components/tf_color_scale/BUILD
- tensorboard/components/tf_line_chart_data_loader/BUILD
- tensorboard/components/tf_markdown_view/BUILD
- tensorboard/components/vz_chart_helpers/BUILD
- tensorboard/components/vz_line_chart/BUILD
- tensorboard/components/vz_line_chart2/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
@nfelt @jart @stephanwlee  please take a look. 
Thanks.
> Making a tensorflow_webcomponent_library target for tf-scalar-card.

- tensorboard/components/tf_card_heading/BUILD
- tensorboard/components/tf_line_chart_data_loader/BUILD
- tensorboard/components/vz_line_chart/BUILD
- tensorboard/components/vz_line_chart2/BUILD
for tf-scalar-card and its dependencies.
@stephanwlee @nfelt @jart please take a look.
Thanks.
> Fixing a few errors with the new tensorboard_webcomponent_library rules

- .travis.yml
- RELEASE.md
- tensorboard/version.py
cc @jameswex @qiuminxu for the release notes
> Release 1.12.0

- tensorboard/components/tf_line_chart_data_loader/BUILD
@stephanwlee @nfelt @jart 
Please take a look. Thanks.
> Added tf_dashboard_common missing dependency

- tensorboard/components/BUILD
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
Unintended removal was committed as part of #1507
> Add What-If tool back to list of plugins

- tensorboard/BUILD
- tensorboard/compat/proto/BUILD
- tensorboard/summary/summary_test.py
- Expose summary target back to public (became private at #1533)
- Don't run proto_test on CI
- summary test refactor
> Minor build changes

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
> Made image accessible with right click

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Fixes https://github.com/tensorflow/tensorboard/pull/1446#issuecomment-436915402
> Fixed the malformed SVG in Firefox

- third_party/workspace.bzl
> Update the Chromium to 70 for functionaltest

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
@stephanwlee please take a look. Thanks!
> Adding color-scale to tf-scalar-card

- .travis.yml
- RELEASE.md
- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-source-code-view.html
- tensorboard/plugins/graph/tf_graph_common/minimap.ts
- tensorboard/version.py
This is a patch release that fixes bug that critically impacts the debugger plugin.
> 1.12.1 Release

- RELEASE.md
Because it is a patch update, there is no change in version.py.
> Post 1.12.1 release

- tensorboard/BUILD
This facilitates doing a find-replace on them using the full label name.
> Make :expect_absl_logging_installed deps absolute

- PULL_REQUEST_TEMPLATE.md
Reviewers of large PRs often do not have context to properly review or understand the motivation and supplied code changes. This template ensures that a bare minimum context is provided for the reviewer and commit reader.
None, text only
None
None
This is the simplest process we could conceive of.
Co-authored-by: William Chargin <wchargin@gmail.com>
> Add template for PRs

- tensorboard/pip_package/build_pip_package.sh
Addresses https://github.com/tensorflow/tensorboard/pull/1707#issuecomment-449539014
> fix build_pip_package.sh arg parsing to be POSIX sh compatible

- RELEASE.md
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/version.py
Patch release that fixes the path_prefix bug.
> TensorBoard 1.12.2 Release

- tensorboard/plugins/profile/trace_events_json.py
- tensorboard/plugins/profile/trace_events_json_test.py
dict will throw an exception when retrieving an none value via "dict['key']". Fix this bug and add a test to it
> fix a bug in trace_events_json

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Fixes https://github.com/tensorflow/tensorboard/issues/982#issuecomment-461919990
> Fix incorrect data binding to src prop.

- README.md
> Expose samples_per_plugin cli arg in README

- tensorboard/compat/proto/BUILD
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/event.proto
- tensorboard/compat/proto/function.proto
- tensorboard/compat/proto/op_def.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/step_stats.proto
- tensorboard/compat/proto/verifier_config.proto
Updating TensorBoard replica of TF protos to be in sync.
Ref TF commit: https://github.com/tensorflow/tensorflow/commit/6120bedc3d14ca953ab9e937d86d72c1f3ec25c9
This change will pick up new fields to RunMetadata we require.
> Sync with TF protos

- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/graph/graph_util.py
- tensorboard/plugins/graph/graph_util_test.py
Graph plugin soon will support FunctionGraphs in the RunMetadata.
Because it is a tree of GraphDefs, for our frontend, we need to be
able to compose one GraphDef.
> Utility method for combining protos naively

- docs/r2/scalars_and_keras.ipynb
Linkify some text to Keras docs and clean up text in some minor ways to be more descriptive.
> Update Scalars tutorial text to be more descriptive.

- docs/r2/get_started.ipynb
The get started tutorial says the FashionMNIST dataset will be used, but the tutorial actually uses the MNIST dataset.
> Fix get started tutorial incorrect dataset mentioned 

- docs/r2/scalars_and_keras.ipynb
> Fix bad url

- tensorboard/plugins/histogram/histograms_demo.py
In the histograms_demo.py, we need an argument to let user define the number of iterations for which summary are to be seen.
I have passed the number of iterations with default value of 400 as used earlier, as an argument to the main function of histograms_demo.py file/
> add argument to histograms_demo.py

- tensorboard/components/tf_backend/requestManager.ts
- tensorboard/components/tf_backend/test/requestManagerTests.ts
- tensorboard/plugins/hparams/tf_hparams_backend/tf-hparams-backend.html
- tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.html
- tensorboard/plugins/hparams/tf_hparams_query_pane/test/tf-hparams-query-pane-test.html
> Use HTTP GET in HParams in colab, POST otherwise.

- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
Broken tfgraph standalone app.
Change to latest internal api call for loader.
> Fix standalone tf-graph-app after internal refactor

- tensorboard/plugins/hparams/tf_hparams_backend/BUILD
- tensorboard/plugins/hparams/tf_hparams_main/tf-hparams-main.html
- tensorboard/plugins/hparams/tf_hparams_parallel_coords_view/tf-hparams-parallel-coords-view.html
- tensorboard/plugins/hparams/tf_hparams_scale_and_color_controls/tf-hparams-scale-and-color-controls.html
- tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_view/tf-hparams-scatter-plot-matrix-view.html
- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.html
- tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.html
* Added legacy target to tf-hparams-backend
* Fixed <style> tags to be inside <template> tags in hparams elements.
@stephanwlee , @wchargin  PTAL.
Thanks!
> Minor hparams fixes.

- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Allow sending capture profile request via TB
> add capture-profile into profile plugin

- tensorboard/functionaltests/wct_test_driver.py
> Use console logs to determine web test results

- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.html
- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.html
@wchargin please take a look.
Thanks!
> Adding attributes to facilitate integration testing of HParams

- README.md
- docs/r1/overview.md
RE: https://github.com/tensorflow/docs/pull/406
> Stack Overflow spelling

- tensorboard/plugins/pr_curve/README.md
I was following the README file and tested some sample code snippets when I noticed some of them don't actually work.
- Updated sample code snippets so it no longer raises exceptions like:
```
File "/Users/derekhh/.virtualenvs/tmp_py36/lib/python3.6/site-packages/tensorboard/plugins/pr_curve/summary.py", line 211, in pb
float_labels = labels.astype(np.float)
AttributeError: 'list' object has no attribute 'astype'
```
- Copied the sample snippets to a new Python script again, verified that executing these snippets no longer raises any exception.
* Alternate designs / implementations …
> [PR Curve Plugin] Fix some bugs in sample code snippets

- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.html
- tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.html
This aids integration tests to synchronize on completion of redraw.
@wchargin please take a look.
Thanks!
> Adding redraw-counter to tf-hparams-parallel-coordinates-plot

- tensorboard/components/vz_example_viewer/vz-example-viewer.html
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Update datapoint editor visuals to match updated mocks. No functionality changes.
Ran demos and visually inspected
> Update What-If Tool datapoint editor visuals

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
> Fix custom-scalars dashboard reloading

- tensorboard/plugins/hparams/BUILD
> add missing :expect_tensorflow_installed dep to hparams:summary

- tensorboard/plugins/profile/profile_plugin.py
Set the workers list value when profiling a TPU. This allows profiling all tpu workers in the pod, rather than only the master.
> Add workers list to tpu profiler

- tensorboard/BUILD
- tensorboard/default.py
This change enables the new Mesh plugin for visualizing point cloud data. 
+cc @podlipensky
> Enable mesh plugin as one of default plugin

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/build_pip_package.sh
`from tensorboard.plugins.mesh import summary` was failing in
tb-nightly.
cc @podlipensky
> Add mesh summary in the pip package

- third_party/js.bzl
Related issue: https://github.com/tensorflow/graphics/issues/8
> Update link to mesh-viewer.js

- tensorboard/plugins/interactive_inference/README.md
Fit witwidget-gpu spelling in readme.
> Fix readme spelling error

- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
Release new WitWidget with latest changes.
Updated version number
Fixed issue with custom predict functions found during testing - check explicitly for dict so as to capture edge cases in prediction lists.
N/A
Ran all our different colabs with a locally-uploaded version of this new pip package. Verified correctness.
> Update WitWidget pip version

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
> typo: indicies -> indices

- tensorboard/plugins/profile/input_pipeline_analyzer/BUILD
- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.html
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.ts
- tensorboard/plugins/profile/memory_viewer/mv_line_chart/mv-line-chart.ts
- tensorboard/plugins/profile/overview_page/BUILD
- tensorboard/plugins/profile/overview_page/overview-page.html
- tensorboard/plugins/profile/pod_viewer/pod_viewer_dashboard/BUILD
- tensorboard/plugins/profile/pod_viewer/pod_viewer_dashboard/pod-viewer-dashboard.html
- tensorboard/plugins/profile/pod_viewer/pod_viewer_dashboard/pod-viewer-dashboard.ts
- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
This change fixes all aspects of profile plugin in Polymer 2.
Please refer to each commit messages on nature of the changes.
> Polymer 2: fix the profile plugin

- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- tensorboard/components/tf_dashboard_common/dashboard-style.html
- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/components/tf_dashboard_common/tf-dropdown-trigger.html
- tensorboard/components/tf_data_selector/tf-collapsible-data-selector.html
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-card-style.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-resizer.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/graph/tf_graph/tf-graph-minimap.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
This pull request contains three changes that are more platform-y than future pull requests.
Please see individual commit messages for better descriptions of the changes.
> Polymer 2: core fixes

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
Fixing up WIT usage in cloud AI platform models.
- Add custom user agent when using with cloud, for usage tracking purposes
- Add cloud project env var setting for ease of use in notebooks
- Bump up version number for new pip release
Ran colabs with cloud models to show functionality. Verified that user agent worked and was logged.
> WIT updates for cloud AI platform

- tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
Commit 5cc7176b9 added a bad console.log
> cleanup: removed extreanous logs on tooltip

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
Summary:
This commit broke Jupyter notebook integration: a content security
policy that whitelists Colab also blocks access by any Jupyter
notebooks.
I don’t see a simple fix for this other than permitting all frame
ancestors: Jupyter origins are arbitrary, and we can’t use `'self'`
because Jupyter and TensorBoard are not in fact served from the same
origin.
This reverts commit ff05d1af8d118d0add237766980d31163a94c40b.
Test Plan:
Build the Pip package, then install it into a virtualenv with Jupyter.
From a Jupyter notebook, run `%tensorboard --logdir logs`. Before this
commit, that rendered an empty cell and printed a console error,
> Refused to display 'http://localhost:6006/' in a frame because an
> ancestor violates the following Content Security Policy directive:
> "frame-ancestors …
> Revert "core: add CSP header for Colab output frames (#2390)"

- docs/r2/tensorboard_profiling_keras.ipynb
> The GPU device check is too specific. Making it more general

- third_party/polymer.bzl
Sync with the master was bad and what was meant to be "mirror.tensorflow" to "mirror.bazel.build".
> core: fix the mirror url

- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
Mnemonic help with `bazel aquery` and improves general debuggability.
> build: add mnemonics to actions

- README.md
> Add FAQ entry describing TB behavior without TF

- tensorboard/compat/tensorflow_stub/dtypes.py
The same issue ( https://github.com/tensorflow/tensorflow/issues/30427 ) and the same solution ( https://github.com/tensorflow/tensorflow/pull/30559 ) as in tensorflow/tensorflow.
> Fix warning with numpy 17.x+

- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.html
Open help and bug link in a new tab.
> hparams: open link in new tab

- docs/r2/tensorboard_profiling_keras.ipynb
Fixed typo
Fixed typo
None
None
None
> Fixed Typo: 'RestNet' -> 'ResNet'

- tensorboard/data/BUILD
Summary:
Fixes internal sync.
Test Plan:
<http://cl/263422038>
wchargin-branch: data-build-license
> data: add license to `BUILD` file

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
Update package to fix dependency version issue.
Need to rely on >= rules for dependencies, so this package works with latest JupyterLab notebooks.
Verified new version of npm package works in JupyterLab 1.0+, which old version did not.
> Update wit-widget npm package

- tensorboard/components/tf_ng_tensorboard/BUILD
- tensorboard/components/tf_ng_tensorboard/app.component.html
- tensorboard/components/tf_ng_tensorboard/app.component.ts
- tensorboard/components/tf_ng_tensorboard/app.module.ts
- tensorboard/components/tf_ng_tensorboard/plugins/BUILD
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.css
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.html
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.test.ts
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
- tensorboard/components/tf_ng_tensorboard/plugins/plugins.module.ts
This change renders plugin body where it should appear.
Note that there still are tons of work to do with w.r.t. data loading.
> ng: draw contents of the active plugin

- tensorboard/data/provider.py
- tensorboard/data/provider_test.py
Test Plan:
Unit tests included.
wchargin-branch: data-value-types
> data: make `ScalarTimeSeries` and `ScalarDatum` value types

- tensorboard/plugins/interactive_inference/DEVELOPMENT.md
- tensorboard/plugins/interactive_inference/README.md
Add development documentation for WIT
> Add What-If Tool developers guide doc

- third_party/js.bzl
This updates version of threejs from r104 to r108.
> infra: upgrade threejs to r108

- .travis.yml
- RELEASE.md
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/variable.proto
- tensorboard/compat/proto/verifier_config.proto
- tensorboard/version.py
Small delta from 1.15.0 - mostly just our planned breaking changes.
Still need to do some local sanity check testing, but sending this out to start Travis.
> Release 2.0.0

- .travis.yml
- RELEASE.md
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/variable.proto
- tensorboard/compat/proto/verifier_config.proto
- tensorboard/version.py
Like #2672 but merged into the actual 2.0 branch this time :man_facepalming:
> Release 2.0.0 (round 2)

- docs/r2/get_started.ipynb
- docs/r2/migrate_tf2.ipynb
Updating links in cl/272280503
> Update links for TF2

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Need to release witwidget 1.4.1 due to a significant regression in 1.4.
Update version number and release notes.
> WitWidget 1.4.1 patch

- tensorboard/backend/application.py
Summary:
Currently, we apply the `_handle_errors` middleware as a decorator
directly on `__call__`. We plan to add middleware that is parameterized
on instance variables, so this pattern will no longer suffice. This
commit simply refactors the existing code to apply middleware at
initialization time.
Test Plan:
It suffices to run `bazel test //tensorboard/backend:application_test`.
wchargin-branch: app-middleware
> application: factor out middleware installation

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
**vulc: graceful handling of absolute URL**
Recently with #2719, we introduced script tag hashing with the
Vulcanization. This did not correctly address the case when a script tag
refers to a remote resource or a case when webpath could not be resolved
to a webfiles passed to Vulcanization.
tested on more complex set up where we use `vulcanize-noinline` and an absolute URL.
**vulc: break scripts when there are src in between**
Order of script declarations cannot be changed for correctness sake.
Previously, we were combining all script tags into one while leaving the
ones with `src` in the same place. This caused the correctness issue so
we now combine scripts up to occurrences of src-full script tag.
WANT_LGTM=any
merge plan=rebase
> vulcanization: improvements

- docs/r1/summaries.md
Fix link to graphs.md
Fixes tensorflow/tensorflow#33185
> Fix link to graphs.md

- .travis.yml
- tensorboard/plugins/mesh/BUILD
This reverts commit 69848209eaccbdcf2985aab754d1eb3ec2eafc81.
Fixes #2624.
> Revert "build: disable mesh summary v2 test (#2625)"

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Release patch version with minor fixes, including cloud model fix.
> Release WIT patch 1.4.2

- docs/graphs.ipynb
> Fix typo s/sumary/summary

- README.md
Fixes #2748 (unless there are additional instances of `tb-nightly` somewhere that I didn't find?)
WANT_LGTM=any
> Remove mentions of tb-nightly from README

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
TFMA visualizations will link up with WIT to drive what examples to load. Created a callback generator for use in the TFMA API for a WIT instance.
Added method on WitWidget to return a callback function that can be provided directly to the TFMA visualization creation API.
Used created callback to drive examples loaded into WIT dynamically.
> Add WIT callback creator for TFMA slicing usage

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Push new patch version
Test changes in new package in notebooks.
> WitWidget 1.4.3

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- max-len: 80
- 'of of' -> 'of'
- consistent quoting
> cleanup: application(|_test).py formatting

- tensorboard/plugins/interactive_inference/DEVELOPMENT.md
Fix typo.
N/A
See screenshot.
N/A
> Fix typo in development instructions

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
What-If tool uses blob for sprite drawing.
> csp: allow blob for img

- tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Try to decode the "bytes" type to "str". It was comparing the 'bytes' with 'str', which will not get the expected results.
Decode the 'bytes' type to 'str' type.
No UI change.
Tested it under colab.
No.
> Decode the bytes

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Motivation for features / changes
Push new patch version
Detailed steps to verify changes work correctly (as executed by you)
Only modifies TFMA callback that got tested in #2816.
> WitWidget 1.4.4

- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Release new pip version of witwidget
Ran colab and jupyter notebooks to verify correct functionality as a delta vs last version.
> Update witwidget to 1.4.5

- docs/_book.yaml
> Update _book.yaml with Fairness Indicators

- docs/tbdev_getting_started.ipynb
This adds the TensorBoard.dev getting started notebook.
> Add TensorBoard.dev getting started notebook

- docs/fairness-indicators.md
> Updating fairness-indicators.md

- RELEASE.md
One commit to round out the 2.0.1 release process: cherry-pick of
2.0.1 relnotes added to RELEASE.md.
> Post-release 2.0.1

- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
If attributions are provided, do not use them for distance between datapoints.
Test in regression with attribution demo.
> Fix WIT datapoint distance with attributions

- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
- tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
- tensorboard/plugins/interactive_inference/witwidget/version.py
Updates for WitWidget 1.5.0
Version updates for pip and npm.
Documentation updates about attribution mode.
> WitWidget 1.5.0 documentation and version number updates

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
The sentence "We only need to specify the layout once" is duplicated.
> Remove duplicate comment

- docs/fairness-indicators.md
> Updating link to Fairness Indicators TB plugin colab

- tensorboard/plugins/mesh/mesh_plugin.py
Summary:
This is a small refactoring to encapsulate direct access to a few
private caches into methods.
Test Plan:
The mesh dashboard still appears to work fine with the standard demo
dataset.
wchargin-branch: mesh-cache-encapsulate
> mesh: encapsulate access to caches

- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
Fix string broken by previous commit.
String cleanup change https://github.com/tensorflow/tensorboard/commit/ff5d2b42c4184505b4417aadba25c499b05c1e8c#diff-14e865ec253ff0abe583324f8028144b accidentally replaced a '>' character with an 'r' character.
> Fix broken What-If Tool path string

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/BUILD
- This fixes a BUILD error encountered during attempt to pull.
> [DebuggerV2] Add missing BUILD dependency for "data_source"

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
This unbreaks the Google sync process.
> [DebuggerV2] Remove extraneous Jasmine dep

- tensorboard/plugins/debugger_v2/BUILD
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- Fix some test failures in debugger_v2_plugin_test.py due to py2/3 differences.
> [DebuggerV2] Minor test fixes for Py2/3 compatibility

- tensorboard/plugins/debugger_v2/BUILD
- tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
- In debugger_v2_plugin.py: add helper method _error_response()
to shorten code.
- As suggested by wchargin@, avoid catching ValueError.
> [DebuggerV2] Some minor refactoring and cleanup in backend

- README.md
Update README with legacy `logdir_spec` as discussed with @stephanwlee in this #3153 issue.
WANT_LGTM=all
> Update README with legacy logdir_spec

- docs/tbdev_getting_started.ipynb
Fix a typo in "Getting Started with TensorBoard.dev" colab.
Add an "e" between "p" and "r".
pip install jupyter
jupyter notebook
open http://localhost:8888/notebooks/git/tensorboard/docs/tbdev_getting_started.ipynb in browser
> Fix typo in "Getting Started with TensorBoard.dev".

- DEVELOPMENT.md
- package.json
- yarn.lock
Also documented how to uue ibazel with yarn.
> Upgrade npm bazel dependency for ibazel

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
* Remove unnecessary import line
* Unblock sync'ing
* Remove an unused import line in debugger_effects_test.ts
> [DebuggerV2] Remove extraneous import line

- tensorboard/plugins/core/core_plugin.py
* Minor code clean up.
* Remove a redundant function checked in due to oversight.
> [Core Plugin] Remove redundant call in _serve_environment()

- docs/get_started.ipynb
Misspelling
Changed tf.keras.callback to tf.keras.callbacks in the description
N/A
N/A
> Updated misspelling

- docs/get_started.ipynb
Code Style
Adding spaces around a variable assignment to be a better example to people following the tutorial.
---
Question: All of the example code in this file uses 2 spaces for indents instead of 4. Should that be changed?
> Docs - Get Started - PEP8 Code Style Fix

- README.md
> Fixed broken Embedding Projector link

- RELEASE.md
Post-release for the 2.1.1 patch release.
> Add 2.1.1 relnotes to RELEASE.md

- tensorboard/webapp/settings/dialog_component.css
- tensorboard/webapp/settings/dialog_component.ts
- more margins between setting (reload controls are more visual grouped)
- font size adjustment
- overall margin adjustment
Before:
After:
> style: fix settings panel

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
* Clean up an unneeded BUILD dependency
> [DebuggerV2] Remove unneeded dependecy from the timeline BUILD target

- docs/r1/graphs.md
- docs/r1/histograms.md
> Fix links to summaries page

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
* Continue developing DebuggerV2 plugin.
* Add some supporting types for source code and stack frames
* Add data source method for fetching list of all source files known to the debugger
* Add selectors for the source-file-list-related state fields
* Add actions for requesting and loading the source file list
* Add effects for loading the source-file list on debugger view load
* N/A since this is a pure type + ngrx change
* Unit tests added
> [DebuggerV2] Add types, selectors, reducers & effects for source code

- package.json
🧼We now have scss files in the repo. Lint and pretty format them!
> cleanup: lint scss formats using prettier

- tensorboard/webapp/header/header_module.ts
Export reload button to be reused in other context.
> ng: allow reload button to be reused

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
* Continue developing DebuggerV2
* Add `fileContents` field to debugger state to hold the content of individual files and their loading state.
* Add actions `sourceFileRequested` and `sourceFileLoaded`
* Add reducers for the said actions
* Add `fetchSourceFile` to data source
* Add an effect to trigger `fetchSourceFile` on the `sourceFileRequested` action.
* N/A
* Unit tests added
> [DebuggerV2] Create ngrx state and effects for fetching individual source-file contents

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
Inadvertent change made in #3359
> Reverts a small inadvertent change to a license file.

- tensorboard/webapp/core/testing/index.ts
- tensorboard/webapp/header/header_test.ts
- tensorboard/webapp/header/reload_container.ts
- tensorboard/webapp/plugins/plugins_component.ts
- tensorboard/webapp/plugins/plugins_container_test.ts
Our plugin API allows plugin authors to disable reload. In that case, we
gray out the reload button.
WANT_LGTM=any
> ng: disable reload button for disable_reload=True

- tensorboard/tools/mirror_urls_test.sh
Summary:
The `mirror_urls_test.sh` occasionally has flaky 404s. This happens
rarely for any given URL, but the test currently checks 233 URLs, so we
see false positives once in a while. This patch changes the test to
retry up to 3 total attempts on each URL individually, not just on the
failure status of the whole test.
Test Plan:
Emulate flakiness by changing `check_cmd` to nondeterministically fail:
```diff
diff --git a/tensorboard/tools/mirror_urls_test.sh b/tensorboard/tools/mirror_urls_test.sh
index 8c50a742..a926b2f5 100755
--- a/tensorboard/tools/mirror_urls_test.sh
+++ b/tensorboard/tools/mirror_urls_test.sh
@@ -40 +40 @@ check_urls_resolve() {
-    check_cmd='curl -sfL "$1" >/dev/null || printf "%s\n" "$1"'
+    check_cmd='(( RANDOM % 16 )) && curl -sfL "$1" >/dev/null || printf …
```
> ci: retry mirror URLs test

- docs/_index.yaml
> Update description and landing page video

- README.md
TensorBoard.dev now supports graphs dashboards. Update documentation to reflect this.
Explain that TensorBoard.dev now supports graphs dashboards.
Provide a link to an experiment with both scalars and graphs.
> Update README with TensorBoard.dev graph info

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/source_code_component.ts
* This addresses a code-analysis warning raised by tooling. 
* In component classes that contain `ngOnChanges()` methods, properly implement the `OnChanges` interface of Angular.
> [DebuggerV2] Cleanup: properly implement angular OnChanges interface

- tensorboard/plugins/graph/tf_graph_debugger_data_card/tf-graph-debugger-data-card.html
Use innerText in lieu of innerHTML in the debugger data card in the graphs plugin.
> [Debugger] Replace some usage of innerHTML with innerText

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Internally, current code triggered "Java Clarity" errors.
Reference: cl/310389378
> cleanup: add @Override on interface impl

- docs/fairness-indicators.md
Updating Fairness Indicators TensorBoard Plugin colab path
> Updating documentation

- docs/graphs.ipynb
- docs/image_summaries.ipynb
- docs/scalars_and_keras.ipynb
- Update TensorFlow versions to 2.2
- Remove GPU from graphs.ipynb (runs in <10s on CPU)
- Refresh output on graphs.ipynb
- Remove nightly installs from profiling.ipynb
> Freshen notebooks.

- package.json
- tensorboard/defs/defs.bzl
- yarn.lock
> ng: allow i18n in Angular

- tensorboard/uploader/uploader.py
> uploader: refactor nested context managers

- tensorboard/webapp/core/views/hash_storage_component.ts
#3725 committed unwanted console statement by mistake. This reverts the line.
> ng: removed unwanted console statement

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Clarity fixes recommended by tooling.
Test plan:
*  Checked bazel build of the Vulcanize target
*  Built and ran tensorboard using scalar_demo logdir and verified I could see & interact with the web app
> (cleanup) Code clarity fixes

- tensorboard/plugins/text/http_api.md
**Motivation for features / changes**
Add documentation to clarify how the text plugin's http request/response api works, similar to documentation for other plugins (e.g. the scalars plugin)
**Technical description of changes**
Added file `tensorboard/plugins/text/http_api.md`
**Screenshots of UI changes**
N/A
**Detailed steps to verify changes work correctly (as executed by you)**
N/A
**Alternate designs / implementations considered**
N/A
> Documentation for Text Plugin's HTTP API

- tensorboard/webapp/header/BUILD
- tensorboard/webapp/header/header_component.ts
- tensorboard/webapp/header/header_module.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
- tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
Reverts tensorflow/tensorboard#3773
> Revert "Add "Upload" button to header for local users"

- tensorboard/webapp/tbdev_upload/BUILD
- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ng.html
- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.scss
- tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
- tensorboard/webapp/theme/_tb_palette.scss
- tensorboard/webapp/theme/_variable.scss
* Motivation for changes
Style new "Upload" button to match UX designs
* Technical details
Override default angular styles with those from the UX designs
* Screenshot
> Style "Upload" button to match UX designs

- tensorboard/webapp/core/effects/BUILD
- tensorboard/webapp/core/effects/core_effects.ts
- tensorboard/webapp/core/effects/core_effects_test.ts
- tensorboard/webapp/types/api.ts
- tensorboard/webapp/webapp_data_source/BUILD
- tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
Fetch and store the runs in the Angular app similar to that of environment.
> ng: fetch and populate the runs in the store

- .travis.yml
- RELEASE.md
- tensorboard/version.py
Prepared for the 2.3.0 pip package release.
Created from HEAD @ 0c88c1f8c98e68898bd5eabfed47e90ae1267a44
Cherrypicks: none
fyi @jameswex @qiuminxu @jindalshivam09
> TensorBoard 2.3.0

- tensorboard/plugins/npmi/BUILD
Unblock sync by removing explicit dependency on the py ruleset.
> sync: remove explicit dependency on py_library

- tensorboard/webapp/plugins/npmi/BUILD
> sync: add core:types dep for strictDeps

- tensorboard/components_polymer3/tf_storage/storage.ts
Co-authored-by: William Chargin <wchargin@gmail.com>
> bug: fixed wrong ref to urlDict

- tensorboard/plugins/text/polymer3/tf_text_dashboard/tf-text-dashboard.ts
1. ready without super call
2. wrong imports
> bug: fixed the text dashboard

- tensorboard/plugins/projector/polymer3/vz_projector/bh_tsne.ts
> license: edit license of polymer3 version of bh_tsne

- tensorboard/webapp/plugins/text_v2/BUILD
This change unblocks the sync.
> strict deps: missing ngrx/store dependency

- tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.ts
Property on readOnly `@property` is disallowed.
> polymer3: fix profile redirect command

- tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
- tensorboard/webapp/plugins/npmi/store/npmi_types.ts
- tensorboard/webapp/plugins/npmi/testing/index.ts
Adding the part of the state that does not come from the backend.
Added reducers, actions, and types for the part of the state that is user controlled/does not come from the backend.
`bazel test //tensorboard/webapp:karma_test_chromium-local`
> [nPMI] Non-Backend Related State

- tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
Added the selectors corresponding to the app state.
Added selectors and tests.
`bazel test //tensorboard/webapp:karma_test_chromium-local`
> [nPMI] Added Selectors

- tensorboard/webapp/BUILD
- tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/metric_search/metric_search_test.ts
- tensorboard/webapp/plugins/npmi/views/main/main_component.ng.html
- tensorboard/webapp/plugins/npmi/views/main/main_component.scss
- tensorboard/webapp/plugins/npmi/views/main/main_component.ts
- tensorboard/webapp/plugins/npmi/views/main/main_container.ts
- tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts
- tensorboard/webapp/plugins/npmi/views/violin_filters/BUILD
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_component.ng.html
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_component.scss
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_component.ts
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_container.ts
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_module.ts
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_test.ts
- tensorboard/webapp/testing/mat_icon.module.ts
- third_party/js.bzl
Adding more UI Components. This contains the first part of the sidebar component.
Added sidebar component to the app. This will later contain violin plots for the data selection.
bazel run tesnsorboard -- --logdir [your logdir]
open localhost:6006/?experimentalPlugin=npmi
> [nPMI] Added Sidebar Display

- tensorboard/webapp/BUILD
- tensorboard/webapp/plugins/npmi/views/annotations_list/BUILD
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_module.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/BUILD
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_component.ng.html
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_component.scss
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/BUILD
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/legend_element_component.ng.html
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/legend_element_component.scss
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/legend_element_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/legend_element_module.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/legend_element_test.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_module.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_test.ts
Added the legend of the annotations list.
`bazel run tesnsorboard -- --logdir [your logdir]`
open localhost:6006/?experimentalPlugin=npmi
> [nPMI] Annotations legend

- docs/get_started.ipynb
Add instructions for how to use hosted tensorboard service from notebook.
Edited new markdown cell in colab, saved locally to laptop and ran nbfmt.
Open ipynb file in colab and execute.
> Add TB.dev instructions to TB getting started notebook.

- tensorboard/backend/application.py
'path_prefix' comment was retrieved from f2b959c2
> docstring:  Argument here is `path_prefix`, not `flags`

- tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
- tensorboard/webapp/plugins/npmi/store/npmi_types.ts
- tensorboard/webapp/plugins/npmi/testing/index.ts
- tensorboard/webapp/plugins/npmi/util/metric_type.ts
- tensorboard/webapp/plugins/npmi/util/sort_annotations.ts
- tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ng.html
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.scss
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_container.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_test.ts
Change all occurences of "sorting" to "sort".
> [nPMI] Change "Sorting" to "Sort" throughout the Plugin

- tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
Fixed incorrect soorting and patched annotations to correct height.
> [nPMI] Fixed Run Sorting for Annotation and Height of Rows

- tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_component.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
- Motivation for features / changes
Fixed incorrect behaviour of the filter chips in the nPMI plugin.
- Detailed steps to verify changes work correctly (as executed by you)
bazel run tensorboard -- --logdir [your logdir]
> [nPMI] Fixed Filter Chips

- tensorboard/webapp/BUILD
- tensorboard/webapp/plugins/npmi/util/BUILD
- tensorboard/webapp/plugins/npmi/util/coordinate_data_test.ts
- tensorboard/webapp/plugins/npmi/util/csv_result.ts
- tensorboard/webapp/plugins/npmi/util/csv_result_test.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ng.html
- tensorboard/webapp/plugins/npmi/views/data_selection/BUILD
- tensorboard/webapp/plugins/npmi/views/data_selection/data_selection_component.ng.html
- tensorboard/webapp/plugins/npmi/views/data_selection/data_selection_module.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/BUILD
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_component.ng.html
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_component.scss
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_component.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_container.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_module.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_test.ts
- tensorboard/webapp/testing/mat_icon_module.ts
- third_party/js.bzl
Added the download button for report generation.
> [nPMI] Implemented Download

- tensorboard/plugins/npmi/README.md
Updated the README to explain more about the plugin.
> [nPMI] Updated Plugin README

- tensorboard/components/BUILD
- tensorboard/components/polymer3_lib.ts
- tensorboard/components/tf_color_scale/BUILD
- tensorboard/components/tf_color_scale/tf-color-scale-polymer.ts
- tensorboard/webapp/plugins/npmi/store/npmi_types.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
- tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_component.ts
- tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_test.ts
- tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ts
Added a workaround for making the run color selection in the plugin possible.
> [nPMI] Run Color Selection

- tensorboard/plugins/scalar/scalars_demo.py
Fix the Tf/tf2 issue in the scalars demo.
> Fix scalar demo

- tensorboard/uploader/flags_parser.py
Work around argparse bug for internal users
> uploader: accept internal alternate experiment name flag

- tensorboard/uploader/BUILD
- tensorboard/uploader/proto/BUILD
- tensorboard/util/BUILD
Internal cleanup (see cl/334213124) 
NA
NA
NA
NA
> remove LICENSE from exports_files where there is no LICENSE file to be exported

- tensorboard/backend/BUILD
- tensorboard/backend/event_processing/BUILD
- tensorboard/compat/BUILD
- tensorboard/compat/proto/BUILD
- tensorboard/data/BUILD
- tensorboard/logo/BUILD
- tensorboard/plugins/BUILD
- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/core/BUILD
- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/mesh/BUILD
- tensorboard/plugins/metrics/BUILD
- tensorboard/plugins/profile_redirect/BUILD
- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/text/BUILD
- tensorboard/scripts/BUILD
- tensorboard/summary/writer/BUILD
Cleanup. See go/bad-license-exports-lsc (this is pt 2) 
Deleting LICENSE from exports_files where no LICENSE exists (and deleting exports_files if the list is then empty).
NA
NA
NA
> remove LICENSE exports files where no LICENSE exists (pt 2)

- tensorboard/compat/proto/BUILD
> Defining a new build target for tensor.proto and its deps.

- tensorboard/defs/defs.bzl
- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/README.md
- tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/coordinator_test.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/threejs_coordinator.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
Coordinator is a module that converts coordinate system. It is a
stateful wrapper around scale and abstract out some quirks about
different coordinate systems of different renderers.
One feature it has is, it provides some ability to check whether
converted coordinate has to be updated with the updateIdentifier: it
currently is just the time (in number) of an update. This is used later
when determining the coordinate converted data has to be updated.
> line chart: add coordinator

- README.md
Corrected the link for summary_iterator
* Motivation for features / changes  The hyperlink of the documentation should be working
* Technical description of changes  Corrected the Hyperlink
* Detailed steps to verify changes work correctly (as executed by you)  Opened the New Link and ensured that it is working
> Corrected the link for summary_iterator in README.md

- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
line_chart_v2/lib is a general library for charting that is currently
written for line chart. The Chart is an enty point the non-Angular,
JavaScript based charting library.
> line chart: Chart, the library entry point

- .travis.yml
- RELEASE.md
- tensorboard/version.py
Cherrypicks: none
Merge plan: rebase and merge, do not squash
This PR should be similar to those from the past:
https://github.com/tensorflow/tensorboard/pull/2347
> TensorBoard 2.4.0

- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/testing.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils_test.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view_test.ts
- tensorboard/webapp/widgets/line_chart_v2/sub_view/sub_view_module.ts
This change introduces interactivity to the line chart. The interactive subview
or layer handles mouse and user actions onto the chart and converts it to
mutations.
Understandably, the change is sizable due to all the interactions we are supporting.
If requested, I can break it down so testing refactor and utils are introduced separately.
> line chart: interactive subview

- tensorboard/data/server/run.rs
Summary:
This avoids ambiguity with `commit::TimeSeries`, even though they’re in
separate namespaces. It also improves consistency with sibling types:
now, a `StageTimeSeries` wraps a `StageReservoir<StageValue>`.
Per suggestion of @nfelt on #4352.
Test Plan:
Type-checking suffices.
wchargin-branch: rust-rename-run-timeseries
> rust: rename `run::TimeSeries` to `StageTimeSeries`

- tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts
This change adds paint brushes for drawing circles and triangles.
> line chart: add paint brush methods for circle/triangle

- tensorboard/webapp/widgets/source_code/source_code_diff_component.ts
- tensorboard/webapp/widgets/source_code/source_code_diff_container.ts
- tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts
Misc cleanup to SourceDiffComponent
- Remove unused import
- Add NO_ERROR_SCHEMA to silence spurious test console messages
- Adds `implements OnInit`
> misc: fix lint and test output in Source Diff component

- tensorboard/plugins/graph/tf_graph_common/graph.ts
TensorBoard graph has a method of extracting out output tensor key from
the input names. This method currently relies on regex matches which
usually is fast but given that inputName length gets longer (deep
name_scopes) with many nodes make it a hotspot and using the regex only
when we absolutely need it (i.e., when the name contains ':') reduced
the normalization time from 80s to 450ms*.
*: Tested with a graph.pbtxt that is 250MB with 3136733 LOC (43958 nodes).
Do note that this magnitude of improvement is not generalizable: you need
many nodes with input names that are lengthy. In the example, `input`s are:
- count: 1714220
- average length ~134 characters
- max length: 168 characters
> graph: speed up "Normalizing names" step

- docs/fairness-indicators.md
> Update the link of FI colab.

- tensorboard/data/server/cli.rs
Summary:
If `--port-file` is given, we should assume that the server is being
invoked programmatically. It thus makes less sense to print the
listening address: in particular, we don’t want to surface that to
normal TensorBoard users. We still log equivalent information at
info-level.
Test Plan:
Note that `tensorboard --load_fast --logdir ~/tensorboard_data/mnist`
still works and no longer prints “listening on [::1]:NNNNN”.
wchargin-branch: rust-quiet-listening
> rust: quiet “listening on…” if `--port-file` given

- tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
- tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/store/feature_flag_types.ts
- tensorboard/webapp/feature_flag/store/testing.ts
- tensorboard/webapp/routes/core_deeplink_provider.ts
- tensorboard/webapp/routes/core_deeplink_provider_test.ts
This reverts commit e072e23826e6f61d736f5220ebef21bfe90b492e.
Changes in the types badly break the internal application.
> Revert "feature flag: persist only overridden flags (#4593)"

- tensorboard/program.py
This removes an ugly global state mutation that we never really needed; we can just subclass the request handler passed into `WerkzeugServer` to set `protocol_version` only for our own usage.
Test plan: Used `curl -s -I http://localhost:6006/ | head -n 2` to confirm that without the old global setting we respond with `HTTP/1.0` but after adding the replacement code in this PR we respond with `HTTP/1.1` again.  Confirmed that the new code works as far back as Werkzeug 0.11.15 (our oldest supported version) as well as 1.0.1 (most recent version).
> program: set WerkzeugServer to use HTTP/1.1 in a proper non-global way

- tensorboard/webapp/widgets/markdown_renderer/BUILD
Follow-up pr for #4666
Adding test deps for markdown renderer
> markdown: add testing deps

- tensorboard/data/server/run.rs
Summary:
We currently wrap tagged metadata events in `GraphDefValue`s rather than
`TaggedRunMetadataValue`s. This doesn’t actually cause any user-facing
errors, because we still generate the correct metadata and the two kinds
of values are enriched into blob sequences in the same way (and we have
tests for the public API, so such an error would have been caught).
Perhaps this raises the question of whether the distinction between the
two types is useful at all. I think that it is: the *values* are treated
the same, but the associated functions `initial_metadata` are different.
Also, these *are* two different kinds of event values, so it seems more
faithful to represent them this way rather than some `BytesLikeValue`.
Along the way, we trim a bit of fat from this logic to make its essence …
> rust: use `TaggedRunMetadataValue` consistently

- tensorboard/data/server/disk_logdir.rs
Summary:
Path manipulation bug: we were joining the root logdir onto a path that
already had the logdir in it. When the logdir is absolute, this does
nothing, but when the logdir is relative, it tries to open files at
incorrect paths, like `logs/mnist/logs/mnist/train/tfevents`.
Test Plan:
Added unit tests to cover this: `test_absolute` passes before and after
this change, whereas `test_relative` fails before and passes after.
wchargin-branch: rust-disklogdir-relpath
> rust: fix disk logdir reading for relative paths

- tensorboard/summary/writer/BUILD
Follow-up to #4582 to address an issue with the internal sync.  See comments inline in the code.
Googlers, see cl/346718222.
WANT_LGTM=any
> ensure tensorboard.summary.writer has no TF build dependency

- tensorboard/webapp/BUILD
- third_party/js.bzl
Add notificaiton icon for the usage of notification center component.
The icon exists both internally and externally
icon link from angualr material github:
https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/social/notifications_none/materialicons/24px.svg
> icon: add notification icon

- tensorboard/webapp/notification_center/BUILD
- tensorboard/webapp/notification_center/_notification_center_module.ts
- tensorboard/webapp/notification_center/_redux/BUILD
- tensorboard/webapp/notification_center/_redux/notification_center_actions.ts
- tensorboard/webapp/notification_center/_redux/notification_center_effects.ts
- tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
- tensorboard/webapp/notification_center/_redux/notification_center_reducers_test.ts
- tensorboard/webapp/notification_center/_redux/notification_center_selectors.ts
- tensorboard/webapp/notification_center/_redux/notification_center_selectors_test.ts
- tensorboard/webapp/notification_center/_redux/notification_center_types.ts
- tensorboard/webapp/notification_center/_views/BUILD
- tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
- tensorboard/webapp/notification_center/_views/notification_center_component.scss
- tensorboard/webapp/notification_center/_views/notification_center_component.ts
- tensorboard/webapp/notification_center/_views/notification_center_container.ts
- tensorboard/webapp/notification_center/_views/view_types.ts
- tensorboard/webapp/notification_center/_views/views_module.ts
- tensorboard/webapp/notification_center/types.ts
Boilerplate new notification center component for what's new content
It's structured under the new structure(see diagram below). The functionality for now only listen to the icon click event.
Texts are all placeholder.
```
tensorboard/webapp/notification_center
├── BUILD
├── _notification_center_module.ts
├── types.ts
├── _redux
│   ├── BUILD
│   ├── notification_center_actions.ts
│   ├── notification_center_effects.ts
│   ├── notification_center_reducers_test.ts
│   ├── notification_center_reducers.ts
│   ├── notification_center_selectors_test.ts
│   ├── notification_center_selectors.ts
│   └── notification_center_types.ts
└── _views
├── BUILD
├── view_modules.ts
├── notification_center_component.ng.html
├── …
```
> whats-new: notification component initial structure

- tensorboard/webapp/notification_center/BUILD
- tensorboard/webapp/notification_center/index.ts
Create an index.js for components to use notification_center_module, which should be private.
> what's new: export notification module through index.js

- tensorboard/defs/defs.bzl
- tensorboard/defs/internal/js.bzl
- tensorboard/webapp/BUILD
- tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
- tensorboard/webapp/plugins/npmi/data_source/BUILD
- tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
- tensorboard/webapp/plugins/npmi/data_source/npmi_data_source_test.ts
- tensorboard/webapp/plugins/npmi/effects/npmi_effects_test.ts
- tensorboard/webapp/plugins/npmi/store/BUILD
- tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
- tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
- tensorboard/webapp/plugins/npmi/store/npmi_types.ts
- tensorboard/webapp/plugins/npmi/testing/BUILD
- tensorboard/webapp/plugins/npmi/testing/index.ts
- tensorboard/webapp/plugins/npmi/util/BUILD
- tensorboard/webapp/plugins/npmi/util/sort_annotations.ts
- tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
- tensorboard/webapp/plugins/npmi/util/umap.ts
- tensorboard/webapp/plugins/npmi/util/umap_test.ts
- tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_container.ts
- tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
- tensorboard/webapp/testing/require_js_karma_config.js
Add data structure and implementation of umap functionality.
Added a util and modified the data structures to support umap.
> [npmi] umap

- tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
- tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
As we add more features, the module is getting out of hand. This change
refactors and extracts template and style part of the module into
separate files.
> line chart: extract HTML and style from axis

- tensorboard/webapp/notification_center/_views/BUILD
- tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
- tensorboard/webapp/notification_center/_views/views_module.ts
Add mat-icon and mat-menu for notification center
The notification content is a placeholder
> what's new: notification center icon and menu basic view

- tensorboard/webapp/notification_center/_redux/notification_center_types.ts
- tensorboard/webapp/notification_center/_views/BUILD
- tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
- tensorboard/webapp/notification_center/_views/notification_center_component.scss
- tensorboard/webapp/notification_center/_views/notification_center_component.ts
- tensorboard/webapp/notification_center/_views/notification_center_container.ts
- tensorboard/webapp/notification_center/_views/notification_notes.ts
- tensorboard/webapp/notification_center/_views/view_types.ts
- tensorboard/webapp/notification_center/_views/views_module.ts
Reads notification contents  from `notificaiton_notes.ts` and parsing date format
Styling drop down menu to match mockup
More styling coming (e.g. bell icon background color)
No markdown import yet. The content is pure html for now.
mockup
> what's new: read notes and styling drop down menu

- tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
- tensorboard/webapp/plugins/npmi/testing/index.ts
- tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
- tensorboard/webapp/plugins/npmi/util/umap.ts
- tensorboard/webapp/plugins/npmi/util/umap_test.ts
As we only use umap and only in 2D for now, I simplified the data structure.
Changed how projections are stored in our embedding datasets.
> [npmi] Simplified UMAP Data Structure

- tensorboard/plugins/histogram/histograms_plugin.py
Summary:
As the comment says, the histograms plugin used to manually downsample
because the multiplexer data provider didn’t. As of #3272, it does, so
this code is vestigial.
Test Plan:
Note that changing the default histogram sampling constants (in the same
file) to very small numbers causes the frontend to show less data. Unit
tests for the histograms plugin also cover this: removing downsampling
from the multiplexer data provider causes the histogram tests to fail.
wchargin-branch: histogram-rm-downsample
> histogram: remove unnecessary downsampling

- tensorboard/plugins/text/summary_v2.py
Update documentation for `tf.summary.text`.
Adds some examples and examples of what features are supported.
#API_FIXIT_3_18_21
> docs: update `tf.summary.text()`

- tensorboard/data/server/disk_logdir.rs
Summary:
Running classical `tensorboard --logdir /no/such/logdir` prints no
indication that the logdir does not exist. RustBoard now behaves the
same way. We still print IO errors other than `ENOENT` at warning level.
Test Plan:
Run TensorBoard with `--logdir /no/such/logdir` and note that the logs
are quiet. Then, `mkdir /tmp/eacces && chmod 000 /tmp/eacces`, and note
that `--logdir /tmp/eacces` does print a warning still.
wchargin-branch: rust-logdir-io-errors
> rust: downgrade logdir traversal errors

- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/event.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saved_object_graph.proto
- tensorboard/compat/proto/struct.proto
- tensorboard/data/server/tensorboard.pb.rs
This change syncs proto from TensorFlow for our release and correctness
purposes.
WANT_LGTM=any
> infra: update protos to TF at 2.5.0-rc0 

- tensorboard/webapp/notification_center/_redux/BUILD
`notification_center_effects_test.ts` depends on `@ngrx/store`.
WANT_LGTM=any
> sync: fix the strictdep on @ngrx/store

- tensorboard/context.py
- tensorboard/context_test.py
Motivation for features / changes
Fixes #4820
Technical description of changes
Added a new filed to RequestContext for http attributes like ip address and x_forwarded_for header value.
Screenshots of UI changes
NA
Detailed steps to verify changes work correctly (as executed by you)
Added unit tests.
bazel test tensorboard:context_test
Alternate designs / implementations considered
NA
Old PR: https://github.com/tensorflow/tensorboard/pull/4835 (messed up the commit history beyond I can repair so created this one fresh, this time correctly i think)
> Adding remote_ip and x_forwarded_for to request context.

- tensorboard/context.py
- tensorboard/context_test.py
Fixing a minor bug introduced in #4820 .
Added a new test for context.replace()
NA
bazel test tensorboard:context_test
> Fix a bug in context.replace().

- tensorboard/webapp/settings/BUILD
- tensorboard/webapp/settings/polymer_interop_container.ts
- tensorboard/webapp/tb_polymer_interop_types.ts
- tensorboard/webapp/widgets/histogram/BUILD
- tensorboard/webapp/widgets/histogram/histogram_component.ts
- tensorboard/webapp/widgets/histogram/histogram_test.ts
- tensorboard/webapp/widgets/histogram/histogram_types.ts
This change adds better typing pattern for tf-paginated-view and
vz-histograms.
> types: further improve Polymer interop types.

- tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
> projector: remove Multiply blend mode

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/store/testing.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
add enabledColorGroup flag for color grouping function switch
> color grouping: add feature flag

- tensorboard/webapp/notification_center/BUILD
- tensorboard/webapp/notification_center/index.ts
export actions for internal analytics
> what's new: export notification actions

- docs/scalars_and_keras.ipynb
Docs cleanup:  Adds a note about how the smoothing parameter may affect the appearance of the learning rate graph.
> (docs) Add a sentence about smoothing to the scalars tutorial.

- tensorboard/plugins/custom_scalar/custom_scalar_demo.py
Updates the custom scalars demo so it uses the idiomatic TF 2.0 APIs.  Note that the plugin's summary APIs themselves are not really in TF 2.0 style, so they require use of `tf.summary.experimental.write_raw_pb()`.  We haven't added TF 2.0 APIs for this plugin due to low usage, but at least this way the demo shows how to integrate the existing summary API into TF 2.0 style summary writing code.
The layout proto is entirely unchanged (only indentation change) except for the margin chart definition, which used to refer to the tags as `loss/baz_*/scalar_summary` and is now just `loss/baz_*` because the TF 2.0 scalar summary doesn't emit the `/scalar_summary` suffix (in contrast to the TB 1.x summary API, which this demo previously used).
What the resulting dashboard looks like after fully …
> custom scalars: update demo to TF 2.0 style

- docs/graphs.ipynb
Adds instructions to push to tb.dev to graph.ipynb.  Mirrors getting_started.ipynb.
* Tested
Ran in colab
> docs: Graph tutorial link to tb.dev

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container.ts
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/_lib.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.scss
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.scss
Do note that due to a bug in production, I could not run the plugin
successfully end-to-end. This change mostly contains the style changes
for the components that I was able to run.
> dark mode: improve debugger under dark mode

- docs/debugger_v2.md
fixes #5057 
tf.clip_by_value should be applied on probs rather than tf.math.log(probs)
> Fix_value_clipping_code

- tensorboard/plugins/histogram/summary_v2.py
This updates the histogram summary TPU outside compilation workaround logic (needed until #2885 is fixed) so that we only invoke it when summaries will actually be written, to avoid the overhead of transferring data to the CPU only to be discarded.
cc @kenfranko 
For googlers, internal tests: cl/379618042
> histogram: avoid data transfer overhead for TPU outside compilation

- tensorboard/webapp/customization/customizable_component.ts
Type improvement. 
For Googlers, see comments in [cl/381412276](cl/381412276).
> doc: update type in tb-customization cookbook example

- tensorboard/webapp/experiments/types.ts
Extends the Experiment interface with an optional repository_id field.
> Add optional repository_id to Experiment

- tensorboard/plugins/histogram/summary_v2.py
Reverts tensorflow/tensorboard#5093
This broke things internally, again. Googlers, see b/194203115.
WANT_LGTM=any
> Revert "histogram: avoid data transfer overhead for TPU outside compilation"

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
> sync: fix import tslint and html analyze

- tensorboard/webapp/widgets/histogram/BUILD
- tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html
- tensorboard/webapp/widgets/histogram/histogram_v2_component.scss
- tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
- tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
This change introduces interactivity to the histogram visualization
where we show tooltips on mouse move in the chart.
This is a final implementation of the new histogram in Angular that is
functionally equivalent to that of Polymer.
> histogram: tooltips on histogram

- tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
> sync: fix tslint 

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We are now working on a new feature that we call "Linked time
visualization". This work is to be done under a feature flag until it is
ready.
> feature flag: add "enableLinkTime"

- tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
See cl/388310456 for better screenshot test structure
> color grouping: add data attribute to color grouping dropdown menu

- package.json
- tensorboard/components/experimental/plugin_util/message.ts
- tensorboard/plugins/graph/tf_graph_common/minimap.ts
- tensorboard/webapp/runs/store/runs_reducers.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
- yarn.lock
Internally, they are meaning to upgrade TypeScript and this is the
pre-work for the upgrade.
When we upgraded TypeScript, some type checks changed and this change
adapts to the change.
> infra: upgrade TypeScript to 4.4.2.

- tensorboard/webapp/metrics/views/BUILD
- tensorboard/webapp/metrics/views/metrics_container.scss
- tensorboard/webapp/metrics/views/metrics_container.ts
- tensorboard/webapp/metrics/views/metrics_container_test.ts
- tensorboard/webapp/metrics/views/metrics_promo_notice_component.ng.html
- tensorboard/webapp/metrics/views/metrics_promo_notice_component.ts
- tensorboard/webapp/metrics/views/metrics_promo_notice_container.ts
- tensorboard/webapp/metrics/views/metrics_views_module.ts
This change adds scaffolding for the TimeSeries promotion. The content
is not complete on purpose.
> timeseries: draft of promo banner

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/directory_watcher.py
- tensorboard/backend/event_processing/io_wrapper.py
- tensorboard/backend/event_processing/io_wrapper_test.py
- tensorboard/util/BUILD
- tensorboard/util/io_util.py
- tensorboard/util/io_util_test.py
To be replaced with an internal implementation.
Googlers, see [issue](https://buganizer.corp.google.com/issues/198329196) for more details.
#onduty
> util: separate out IsCloudPath from io_wrapper

- tensorboard/webapp/types/ui.ts
This change adds an enum for searching by experiment id.
> feat: adds experiment id as one of the searchable

- tensorboard/plugins/histogram/summary_v2.py
Add skeleton for `histogram_v3()`, further implementation and tests will be added in subsequent PRs.
> histogram: add histogram_v3 skeleton

- tensorboard/plugins/histogram/summary_v2.py
See https://github.com/tensorflow/tensorboard/pull/2899 for more details regarding `LazyTensorCreater`.
Currently `_buckets_v3()` is  just a copy of `_buckets()`, modification for single value case handling and corresponding tests will be added in subsequent PRs.
> histogram: apply lazy tensor and set up _buckets_v3 skeleton

- tensorboard/plugins/histogram/histograms_demo.py
Add demo examples for empty data and data consisting of a single value.
Visualization:
> histogram: add demo examples for edge cases

- tensorboard/webapp/app_routing/BUILD
- tensorboard/webapp/app_routing/store/BUILD
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/app_routing/store_only_utils.ts
- tensorboard/webapp/experiments/types.ts
This PR is to help with the introduction of experiment numbers.
> Add Alias selector which includes numbers

- tensorboard/plugins/histogram/tf_histogram_dashboard/histogram_core_test.ts
Fix ban-iterable-foreach and g3-no-void-expression violations.
> fix tslint errors for copybara

- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
- tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
- tensorboard/webapp/feature_flag/testing.ts
- tensorboard/webapp/feature_flag/types.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
- tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
We are working on a new setting on the TS right panel to enable users to adjust the card with. We want to hide the UI and functionality behind a feature flag.
> Feature Flag: add feature flag for card width setting

- tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.scss
> Time Series: inherit font

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
- tensorboard/webapp/metrics/views/main_view/main_view_test.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
Last piece of our card width adjustment. Take the updated value from setting panel and apply on the card css to change the width.
> Time Series: Card width adjustment, connect settings and ui together

- tensorboard/plugins/histogram/summary.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/histogram/summary_v2.py
Remove V2 code.
Ran internally: cl/413690112
> histogram: clean up v2 code

- docs/tensorboard_projector_plugin.ipynb
Closes https://github.com/tensorflow/tensorboard/pull/4799 (no response regarding CLA for 6 months).
#onduty
> docs: fix typo

- .github/workflows/ci.yml
Reverts https://github.com/tensorflow/tensorboard/pull/5499 with the import fix in cl/422561603.
> ci: unpin 2022-01-11 tf-nightly

- WORKSPACE
Googlers, see [b/188559854#comment22](https://b.corp.google.com/issues/188559854#comment22) for more details.
> docs: Bazel versions on Tomservo and Github CI need to in sync

- tensorboard/webapp/widgets/linked_time_fob/BUILD
googlers, please see cl/363052284 for sync result.
> sync: add core testing dependency

- tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
Add data attributes to buttons in toolbar for better webtest structure.
Googlers, please see wip cl/434861398.
> linked time: add data attribute to toolbar buttons for test structure

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
This is the first step to move setting stepIndex in image card from view (image container) to ngrx state (reducer). Full context please see #5615
> linked time: dummy method to prepare stepIndex moving

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
Creates a function to get step values from a image card. This prepares for stepIndex moving. Motivation and full context please see #5615.
> linked time: stepIndex moving: add function to collect all step values within a image card

- tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
- tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
- tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
Creates a function to get selected step(s) within selected time. This prepares for stepIndex moving. Motivation and full context please see https://github.com/tensorflow/tensorboard/pull/5615.
> linked time: stepIndex moving: add function to get selected step(s)

- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ng.html
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.scss
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_component.ts
- tensorboard/webapp/widgets/linked_time_fob/linked_time_fob_controller_test.ts
Implements logic for horizontal dragging in anticipation of implementing the dragging fob feature on Scalar cards.
> Implement horizontal dragging logic in LinkedTimeFobControllerComponent

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_linked_time_fob_test.ts
This is the first step in implementing the functions needed to add fob dragging to the Scalar card. 
There is no guarantee that the minMax object is in order to we simply check which member is greater than the other and return the appropriate one.
> linked time: Implement getHighestStep and getLowestStep

- RELEASE.md
- tensorboard/version.py
Post 2.9.0 release : updates release notes and HEAD version.
> Post 2.9.0 release

- DEVELOPMENT.md
Adding instruction on running and debugging TB for development purpose
> doc: running and debugging instruction on TB development

- tensorboard/data/dispatching_provider.py
Need this argument for post-processing.
Googlers, see cl/457725357.
#refactor
> data: set `_default_prefix`

- tensorboard/data/dispatching_provider.py
- tensorboard/data/dispatching_provider_test.py
Googlers, see b/237101984 for more details.
Tested internally: cl/458001580
#refactor
> data: remove `unprefixed_provider` arg

- tensorboard/pip_package/setup.cfg
* Motivation for features / changes Fixed: #5812 
> Fixed #5812:  Rename license_file

- DEVELOPMENT.md
Add some basic documentation about how to add, update, or remove frontend dependencies, using yarn and bazel.
> Add documentation for adding or updating frontend dependencies.

- ADDING_A_PLUGIN.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- docs/design/colab_integration.md
- docs/r1/histograms.md
- docs/r1/overview.md
- docs/r1/summaries.md
Add or remove extra line in README.md, RELEASE.md and CONTRIBUTING.md.
> Add or remove extra line

- tensorboard/plugins/graph/tf_graph_common/contextmenu.ts
- tensorboard/plugins/metrics/metrics_plugin_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text_v2/text_v2_plugin.py
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.ts
> Update 2.10 RC with fixes.

- RELEASE.md
Preview: https://github.com/yatbear/tensorboard/blob/fb9324f7ad4d5c59d970cfff51492b96b17ced1a/RELEASE.md
> Add release notes for TensorBoard 2.10.0

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_module.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
This is the first change which adds a column in the data table for range selection. We plan to have many columns which deal with a range for the launch of linked time. 
This change sets the structure for changing the column headers based on the linked time selection and the structure for having different styles in certain columns of the data table. I used ngSwitch for the style in anticipation for more styles in other columns.
> linked time: Add value change to data table in range selection

- RELEASE.md
- tensorboard/version.py
Cherry-picks 2.10.0 release notes and bumps version at master.
> Post-release 2.10.0

- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
In [this PR]( https://github.com/tensorflow/tensorboard/pull/5858) I added some checks that are only necessary for IE. We do not need to support IE and these checks are not used elsewhere in the code. Therefore I am removing those checks.
> Remove IE fail safes

- tensorboard/plugins/histogram/README.md
See issue https://github.com/tensorflow/tensorboard/issues/1803 for details.
#onduty
> docs: add a note about histogram rebinning and "smoothing"

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_reducers_test.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/metrics/store/metrics_types.ts
- tensorboard/webapp/metrics/testing.ts
- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
This is part of the effort to enable range selection in an upcoming launch. 
This simply follows the same pattern used for other settings such as the step selector.
> Step Selector: Add Range enabled boolean to state and update based checkbox

- tensorboard/plugins/hparams/hparams_plugin.py
Currently, feeding badly formatted request data to `tb.corp/experiment/<id>/data/plugin/hparams/experiment` endpoint can result in 500s (see  [b/250791957](https://b.corp.google.com/issues/250791957)):
```
...
raise ParseError('Failed to load JSON: {0}.'.format(str(e)))
google3.net.proto2.python.public.json_format.ParseError: Failed to load JSON: Expecting value: line 1 column 1 (char 0).
```
The 500s are confusing to the end users because they will see an `Internal Server Error` page without any useful debugging information. It also adds unnecessary noise to the logging/monitoring system which makes it hard to found the real alerts.
This CL catches the JSON ParseError, logs the request data for debugging, and throws 400s.
Open the browser and enter the hparams plugin endpoint of an …
> Handle the JSON parse error in HParams plugin

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
Introduce feature flag in the card fob and used to render a fob component.
Getting prospectiveFob feature and passing all the way down to card-fob.
Note: this part might need refactor once we have nested container or some kind of structure refactoring.
None
> linked time: set up feature flag and fob rendering

- RELEASE.md
- tensorboard/version.py
Cherry-picking the release and relnotes commits from @JamesHollyer 's #6034 since his branch got borked by a rebase.
Will rebase and merge.
> TensorBoard 2.11.0

- tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts
Internal code health LSC.
Adding comments to suppress ts 4.8 strictNullCheck. We still need to clean up the type mismatch (`Settings` to `PersistableSettings`)
Test: run webapp and manually test settings preservation.
sync presubmit "pass" (Googlers please see cl/487331149, broken by #5991)
> chore: TypeScript 4.8 suppress comment

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ng.html
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.scss
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
1) The text in the prospective fob was off center
2) The prospective fob "did not feel clickable"
3) Clicking near the prospective fob would enable it which lead to some weird bugs
I changed the padding on the fob when the `allowRemoval` flag is set to fix the text centering issuel
The prospective fob is shown based on the value of the `prospectiveStep` variable which is set when hovering the `prospective-fob-area` and set to `null` when the cursor leaves that area. I moved the prospectiveFob inside the `prospective-fob-area` so the cursor would not count as leaving it when the fob appears and takes focus. I also moved the click handler to the fob object (rather than the `prospective-fob-area`) to ensure click events are more accurate.
The changes to the HTML nesting made css changes much …
> Linked Time: Update prospective fob styling

- package.json
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
- tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts
- tensorboard/webapp/testing/lang.ts
- yarn.lock
This reverts commit abb4dfc389fcca1c71ede85ea23f18fd806b91d7.
It breaks the sync to the internal repo.
> Revert "Upgrade to TypeScript 4.8.4. (#6082)"

- tensorboard/webapp/metrics/actions/index.ts
- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_data_table.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ts
- tensorboard/webapp/widgets/data_table/data_table_test.ts
This adds the main logic for dragging columns directly in the data table. 
This both adds the action/reducer which makes the actual change of column order and the UI logic while dragging.
> Column Customization: Add Data Table Column Dragging

- package.json
- tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
- tensorboard/webapp/persistent_settings/_data_source/types.ts
- tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts
- tensorboard/webapp/testing/lang.ts
- yarn.lock
This is a revert of a revert of https://github.com/tensorflow/tensorboard/pull/6082 with problems with the original PR addressed in commit https://github.com/tensorflow/tensorboard/commit/a003b1ab390cf6688b06406e6b05fdf627c155ad
Original PR description:
Upgrade to TypeScript 4.8.4 following instructions in https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md#adding-updating-or-removing-frontend-dependencies.
This upgrade is also a good opportunity to remove some @ts-ignore annotations that were added to the codebase to satisfy the internal upgrade to TS 4.8.4. See https://github.com/tensorflow/tensorboard/pull/6075 and https://github.com/tensorflow/tensorboard/pull/6037. Removing the annotations did indeed lead to build errors that I then fixed with some type adjustments. …
> Upgrade to TypeScript 4.8.4 (again). 

- tensorboard/pip_package/requirements.txt
https://github.com/googleapis/google-cloud-python/issues/10566 has been closed. This PR removes out-dated comments
> Remove out-dated comment about google-auth

- tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Googlers, refer to b/261080964 and  b/264288347.
This PR is accompanied with an internal change to TensorFlow's tf.function codebase. The tensorboard debugger v2 test changes are made to work with the tf.function changes.
> fix: update debugger v2 test

- docs/image_summaries.ipynb
I have updated broken link from(https://research.zalando.com/welcome/mission/research-projects/fashion-mnist/) to new link(https://github.com/zalandoresearch/fashion-mnist) because everywhere in our website we are using new link for Fashion-MNIST dataset.
Please do needful changes to approve and merge this PR if you feel it's valid PR 
Thank you!
> Updated Broken link for Fashion-MNIST dataset

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_fob_controller.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_component.ts
- tensorboard/webapp/widgets/card_fob/card_fob_controller_test.ts
It was named onPrespectiveStepChanged but we normally call it a "prospective" fob.
> Cleanup: Fix name of onProspectiveStepChanged.

- tensorboard/compat/proto/proto_test.py
- tensorboard/compat/proto/update.sh
This fixes a few issues with our compat proto update process:
1) https://github.com/tensorflow/tensorboard/pull/5997 added logic to update.sh to copy protos in a new directory `tensorflow/tsl/protobuf/`, but we didn't update the corresponding replacement logic in proto_test.py, leading to spurious test failures. This fixes the test, and adds comments instructing future editors to keep the two sets of replacements in sync.
2) https://github.com/tensorflow/tensorboard/pull/6020 manually added an `exports` declaration (needed by our google internal build) to the BUILD target for summary.proto, but the entire BUILD file there is autogenerated by update.sh, so rerunning it clobbers that change. This adds logic to update.sh to automatically regenerate that declaration based on the presence of …
> compat: fix proto update script+test to handle recent changes

- tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
- tensorboard/webapp/alert/store/alert_selectors.ts
- tensorboard/webapp/app_routing/store/app_routing_selectors.ts
- tensorboard/webapp/core/store/core_selectors.ts
- tensorboard/webapp/experiments/store/experiments_selectors.ts
- tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
- tensorboard/webapp/hparams/_redux/hparams_selectors.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
- tensorboard/webapp/notification_center/_redux/notification_center_selectors.ts
- tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
- tensorboard/webapp/plugins/text_v2/store/text_v2_selectors.ts
- tensorboard/webapp/runs/store/runs_selectors.ts
- tensorboard/webapp/settings/_redux/settings_selectors.ts
https://github.com/ngrx/platform/issues/3179
This should be a simple replace in all instances
None
Tests should pass
Import works cl/509549062
> Chore: remove deprecated usage of `createFeatureSelector`

- tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.ts
A spelling fix and function rename following up on #6208.
> Follow up fixed to HParam plugin telemetry

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
None
2) Navigate to localhost:6006
3) Add a fob to a card
4) View the console and find the most recent time selection changed event
5) Assert the action contains a `cardId`
6) Assert the state a `timeSelection` value exists in the states `metrics.cardStateMap[cardId]` bucket
> Linked Time: Add step selector to redux state Part 2

- docs/what_if_tool.md
Fixed the broken link for official documentation in line 58
> Fixed the broken link in what_if_tool.md

- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
number of neighbors isn't stored properly in bookmark
fix bookmark value
> Embedding Projector: fix umapNeighbors in bookmark

- tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
Bookmark panel is currently broken.  You can not switch between bookmarks, name bookmarks or delete bookmarks
This fixes aforementioned bookmark issues.
> Embedding Projector: fix bookmark panel

- RELEASE.md
- tensorboard/version.py
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
- tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
- tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
- tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
- tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
This PR contains three commits that will be rebased and merged into the 2.12 branch. The result will be released as the TensorBoard 2.12.2 pip.
> TensorBoard 2.12.2

- RELEASE.md
Will rebase and merge to get clean cherry-pick.
> Cherry-pick 2.12.2 relnotes into master RELEASE.md

- tensorboard/webapp/metrics/views/BUILD
#6317 broke the internal sync Googlers see (cl/524838273)
This should fix it Googlers see cl/524852584
> Bug Fix: Add additional BUILD dependency to fix sync

- tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
- tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
Fixes up the button in settings which opens the editor. This change makes it an actual button with an edit icon. It also adds some functionality to highlight the button when the editor is open.
> Column Customization: Fix up settings button

- tensorboard/webapp/runs/data_source/runs_data_source.ts
Reverts tensorflow/tensorboard#6334
> Revert "Bug Fix: Update runs_data_source to request hparams data using FormData"

- tensorboard/plugins/projector/vz_projector/data.ts
for t-SNE max number of knn neighbors is 3 * max_perplexity (3 * 100 = 300).  For umap max number of neighbors is 100.
let's just compute 300 knn neighbors so we can slice the result each time when we tweak perplexity for tSNE.
When computing KNN, use an upper threshold of 300 so any future computation with same number of points will be cached.
N/A
1. Launch local app
2. Open t-SNE
3. adjust to Perplexity > 25
4. verify knn isn't computed a second time
> Embedding Projector: reduce knn computation

- tensorboard/plugins/projector/vz_projector/vz-projector.ts
fix status bar display
Status bar is always hidden, change it so it shows appropriately
Before:
After:
hover over a point and verify status bar changes
> Embedding Projector: fix status bar display

- tensorboard/webapp/metrics/views/right_pane/scalar_column_editor/scalar_column_editor_component.ts
> cleanup: remove unused import

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
Re-introduces #2912 by @cannoneyed 
Tested with the lastest master to ensure the new param works as expected
> Embedding Projector: Adds UMAP minDist hyperparameter

- RELEASE.md
Will rebase and merge to get clean cherry-pick.
> Cherry-pick: Add 2.12.3 relnotes to RELEASE.md

- tensorboard/webapp/feature_flag/directives/BUILD
> Update directive BUILD rules to fix internal build on sync

- RELEASE.md
- tensorboard/compat/proto/BUILD
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/coordination_config.proto
- tensorboard/compat/proto/graph.proto
- tensorboard/compat/proto/graph_debug_info.proto
- tensorboard/compat/proto/proto_test.py
- tensorboard/compat/proto/struct.proto
- tensorboard/version.py
Merging the RELEASE notes and version bump into master
> TensorBoard 2.13.0

- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
Fix PCA sampling message visibility bug
dim[0] is number of points, dim[1] is number of dimensions
message should be hidden if using MNIST dataset
> Embedding Projector: Fix PCA sampling message

- tensorboard/data/provider.py
Add notion of "Hyperparameter" to DataProvider interface and add a basic list_hyperparameters() operation.
> Hparams: Add notion of "Hyperparameter" to DataProvider interface.

- tensorboard/webapp/widgets/data_table/BUILD
- tensorboard/webapp/widgets/data_table/column_selector_component.ng.html
- tensorboard/webapp/widgets/data_table/column_selector_component.scss
- tensorboard/webapp/widgets/data_table/column_selector_component.ts
- tensorboard/webapp/widgets/data_table/column_selector_module.ts
- tensorboard/webapp/widgets/data_table/column_selector_test.ts
As part of the hparams in time series project we are creating a new tool for adding columns to tables.
Light Mode:
Dark Mode:
Here's what it's like to use
> HParams: Create column selector component

- tensorboard/webapp/feature_flag/store/feature_flag_metadata.ts
- tensorboard/webapp/feature_flag/types.ts
We are working on a new feature to suggest cards to a user based on their previous interactions with TensorBoard.
This feature flag will help control it's rollout.
> Suggested Cards: Add new feature flag to control the suggested cards feature

- tensorboard/plugins/projector/vz_projector/bh_tsne.ts
- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
#6289 
Restart tsne with current solution when dimension or perplexity is changed
N/A
1. open t-SNE projection.
2. toggle 2D/3D will result in a new t-SNE run with the existing projection
> Embedding Projector: fix tSNE tweaking hyperparams

- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
The filter was added in #6450. The screenshots in that PR include these styles. Somehow I forgot to add these when I pushed those changes.
> HParams: Add Style to RunsDataTable Regex Filter

- tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
- tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
The RunsDataTable has an affordance for sorting and the plumbing is there to set the sorting info. However, the data was never sorted. This PR sorts the data based on that sorting info which we have stored in ngrx.
I simply added another Obvservable which watches allRunsTableData$ and sortingInfo$ and sorts. Then I passed that sorted observable to the RunsDataTable.
I really only tested this with the run column. Then I wrote test for the rest.
> HParams: Sort Runs Table Data

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
- tensorboard/webapp/runs/views/runs_table/runs_data_table.scss
- tensorboard/webapp/widgets/data_table/data_table_component.ng.html
- tensorboard/webapp/widgets/data_table/data_table_component.scss
This is simply an aesthetics change. I centered the color palette button at the top of the color column. I also made forced the "add column" to be much smaller and added a right border to the last column before that add column.
Before:
After:
> HParams: Style fixes for color and add column

- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_component.ts
- tensorboard/webapp/metrics/views/card_renderer/scalar_card_line_chart_container.ts
Make slight modifications on the scalar card line chart for eventual single card usage. 
cardId is only needed on the container level and stepOrLinkedTimeSelection needs to be an input as it will be defined on the card level to be used in both the scalar card line chart as well as the data table.
> Embedded Single Card: line chart modifications

- tensorboard/plugins/hparams/list_session_groups.py
This is a cleanup PR to list_session_groups.py, reducing its reliance on data attributes.
We now keep the set of data attributes small - to correspond exactly to the arguments of the `__init__` method (`self._request_context`, `self._backend_context`, `self._experiment_id`, and `self._request`).
Two motivating factors:
* Recently we have split list_session_groups.py into two major branches of logic: The branch that generates "classic" hparams from tensor metadata; and the branch that generates hparams from the data provider. Many of the existing data attributes applied only to the first branch and, in some cases, were not strictly guaranteed to be set since they are no longer set in `__init__`.
* We can now move `self._extractors` and `self._filters` out of the`__init__` method now that …
> Clean up usage of data attributes in list_session_groups.

- tensorboard/webapp/metrics/store/metrics_reducers.ts
- tensorboard/webapp/metrics/store/metrics_selectors.ts
Make card list exportable for single card to fetch card Id. 
Googlers, please see cl/548878204 how the single card will fetch the card Id from card list.
> Embedded Single Card: export card Id list

- DEVELOPMENT.md
- patches/README.md
Make some minor fixes/additions to documentation related to upgrading npm dependencies and generating patch files.
> Tweak some patch and upgrade documentation.

- tensorboard/plugins/hparams/backend_context.py
- tensorboard/plugins/hparams/backend_context_test.py
In calls to the /experiment endpoint for hparams, we now generate metric_infos based on the session_groups returned by the DataProvider. We are able to reuse most of the logic that generates metric_infos for the classic tensor-based hparams.
The end result is that metrics are listed in the left pane of the hparams dashboard.
We have not yet integrated generating metric values into the /session_groups operation so the values do not yet appear in the table view.
> Hparams: Generate metric_infos from data provider session groups.

- tensorboard/pip_package/requirements.txt
See issue #6580 for more details.
> Adds explicit dependency on `six` package.

- tensorboard/webapp/runs/views/runs_table/runs_data_table.ng.html
Adding attribute for internal testing.
> Add data-id attribute to RunsDataTable rows for internal tests

- RELEASE.md
This PR is to update the master branch with the patch notes from the 2.14.1 patch release.
> Post Release 2.14.1

- tensorboard/data/provider.py
- tensorboard/plugins/hparams/backend_context.py
Googlers, see b/292102513 for context.
#hparams
> Hparams: Update docstrings 

- tensorboard/webapp/widgets/range_input/BUILD
Fixes an angular import to unbreak the copybara sync.
> Fix angular dependency for range_input.

- tensorboard/webapp/BUILD
- tensorboard/webapp/testing/mat_icon_module.ts
- third_party/js.bzl
I followed my own instructions documented in #6692
I did encounter an issue with the tf mirror cli but I managed to work around it.
> Add the filter list icon

- tensorboard/webapp/BUILD
- tensorboard/webapp/testing/mat_icon_module.ts
- third_party/js.bzl
I followed the instructions documented in https://github.com/tensorflow/tensorboard/pull/6408 to add [this icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aopen_in_new%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) .
> Add open_in_new icon

- tensorboard/compat/proto/config.proto
Just updating some proto definitions for compatibility with no-TF mode.
> Updates compat protos with latest snapshot from TF

- RELEASE.md
(cherry picked from commit f59e9b3a035c6bb92a3843a27c134577783fcd25)
> Add 2.15.2 relnotes to RELEASE.md

- .github/workflows/ci.yml
- RELEASE.md
- tensorboard/pip_package/requirements.txt
- tensorboard/plugins/hparams/_keras.py
- tensorboard/plugins/hparams/_keras_test.py
- tensorboard/version.py
This release will remove the dependency on the tf-keras pip package.
I will rebase and merge the commits.
> TensorBoard 2.16.2 release

- RELEASE.md
I will rebase and merge this change.
> Cherry-pick 2.16.2 release notes

- tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
Fix a typo `darkModeEanbled` -> `darkModeEnabled `
Fixing a typo made in code. Although it doesn't change functionality, it keeps the code health.
N/A
N/A
N/A
> Fix typo in regex_edit_dialog_container.ts.

- tensorboard/defs/internal/html.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
Add the missing arg for `extract_providers` and fix struct provider syntax.
Googlers, see cl/617097191.
#oncall
> Fix internal build error

- .github/workflows/ci.yml
This should resolve build breakages.
> Force tests to use keras 2

- DEVELOPMENT.md
Fix a typo `ibazle` to `ibazel`
Fix a typo `ibazle` to `ibazel`
N/A
N/A
N/A
> fix typo in the DEVELOPMENT.md

- .github/workflows/ci.yml
Temporary fix since master is failing due to upstream changes in Keras. 
[Link](https://github.com/tensorflow/tensorboard/actions/runs/9111112046) to first failure.
> Pin nightly since keras_util test has failed.

- tensorboard/BUILD
Required to get internal build passing
> Ensure protobuf is installed internally

- tensorboard/BUILD
Update build rules to properly match expected sync format.
> Internal sync fix

- RELEASE.md
> Post-release 2.17.1

- tensorboard/webapp/metrics/store/metrics_reducers.ts
This throws errors when using TypeScript 5.6.
See cl/671116520
> Remove redundant usage of nullish coalescing operator

- tensorboard/plugins/graph/tf_graph_common/render.ts
This is being done to support an internal migration cl/675299509
> Add a declare to class fields which override a base class

- tensorboard/webapp/experiments/types.ts
Follow up to #6955 with an update to the doc comment from feedback in cl/702173713.
> Deletes deprecated field and updates comment for data source url.

- tensorboard/webapp/theme/_tb_theme.template.scss
> LSC with style fix for material icon.
