- third_party/js.bzl
This is necessary so web library example can depend on this repo.
> Fix Clutz workspace definition

- third_party/werkzeug.BUILD
Fixes the following error:
ImportError: No module named debug.tbtools
> Fix werkzeug by recursively finding python sources

- tensorboard/components/tf_runs_selector/tf-runs-selector.html
Summary:
Now that we've removed the `tf-sidebar-helper`, the new runs selector is
the only runs selector in use. Thus, we can remove the "new" label, as
we no longer need to tell it apart from anything else.
Test Plan:
Run TensorBoard, and look at the scalars and images dashboards. They
should each have a functioning runs selector that uses the Polymer
component tf-runs-selector (not tf-run-selector), and this component
should not have a bright red "new" label.
> Remove the "new" label from the runs selector

- tensorboard/components/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/components/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/components/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/components/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/components/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/components/tf_profile_dashboard/tf-profile-dashboard.html
- tensorboard/components/tf_text_dashboard/tf-text-dashboard.html
Summary:
The `factoryImpl` method is called when the constructor of a Polymer
component is invoked. The constructor is the object returned by the call
to `Polymer({...})`. But we always immediately discard this constructor,
so the constructor is never called and these functions are unused.
I remember that these were a significant red herring when I was first
looking at the code base. We should remove them to prevent further
confusion.
Test Plan:
I loaded TensorBoard with enough logdirs to provide data from all
dashboards, then tested that the basic functionality of each dashboard
still worked.
> Remove all `factoryImpl`s

- .travis.yml
Since we're compiling things like protobuf from scratch, it makes a lot of sense to cache the blaze-bin directories. This really plays to Bazel's strengths, which is that it solves the cache invalidation problem.
Results: Rather than taking 8 minutes, Travis now takes somewhere between two minutes and eight minutes. The [proof is in the pudding](https://travis-ci.org/tensorflow/tensorboard/builds/243572006).
> Make Travis go faster

- .travis.yml
Summary:
Looks like TF's nightly build URLs aren't stable with respect to the
TensorFlow version number: 1.2.0rc2 is dead, long live 1.2.0. Perhaps we
can write something clever to automagically update this; for now,
manually updating is probably fine.
Test Plan:
Consider the following command:
```sh
grep -F NIGHTLY_URL= .travis.yml | \
cut -d \' -f 2 | \
xargs curl -sI | \
grep -F 'HTTP/1.1'
```
Before this commit, it outputs:
```
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
```
After this commit, it outputs:
```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```
> Fix TensorFlow nightly URL in Travis build file

- tensorboard/components/tf_card_heading/BUILD
- tensorboard/components/tf_card_heading/tf-card-heading.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
This commit rewrites the scalars dashboard so that it does not have any
essential dependencies on TensorBoard framework components like
`tf-panes-helper`. There are two purposes to this commit: first, this
commit enables us to inspect where the essential complexities of the
dashboard are and better evaluate what parts might merit being pulled
into framework code; second, it will be far easier to implement new
framework code if we do not have to tear the old stuff down at the same
time.
I have marked some sections with `// DESTINATION` comments when I think
that they should be pulled into framework components. Other than those,
the resulting code is complete and functional.
Test Plan:
Run TensorBoard on a directory with ample scalar summaries. Most data
bindings have been rewired, …
> Remove TensorBoard framework from scalar dashboard

- tensorboard/backend/application.py
Previously, the hacky_loader had loaded assets such as the TAG file relative to the tensorflow directory when tf.resource_loader.load_resource was to be used. This resulted in the file not being found and thus TensorBoard failing to start up when running in certain self-contained environments.
> Correct path for assets to be relative to the tensorboard directory

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
This commit removes references to scalars from `backend.ts` and related
tests, and also removes temporary comments from the scalars dashboard.
Test Plan:
`bazel test //tensorboard/...` and interact with the TensorBoard
dashboard.
wchargin-branch: clean-up-scalars-dashboard
> Clean up the scalars dashboard

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/images/tf_image_dashboard/BUILD
- tensorboard/plugins/images/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/images/tf_image_dashboard/tf-image-loader.html
Summary:
This commit removes the image dashboard's dependencies on such old-style
framework components as `tf-panes-helper`, `tf-chart-scaffold`, and
`tf-categorizer`.
Test Plan:
Tested tag groups, run selection (shared with scalars and other
dashboards), expanding and collapsing panes, expanding and collapsing
cards (the individual images), showing actual size, and adjusting the
step slider. Also tested the view when there is no image data.
wchargin-branch: refactor-image-dashboard
> Bring the image dashboard into the new world

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/histograms/tf_histogram_dashboard/BUILD
- tensorboard/plugins/histograms/tf_histogram_dashboard/histogramCore.ts
- tensorboard/plugins/histograms/tf_histogram_dashboard/test/BUILD
- tensorboard/plugins/histograms/tf_histogram_dashboard/test/histogramTests.ts
- tensorboard/plugins/histograms/tf_histogram_dashboard/test/tests.html
- tensorboard/plugins/histograms/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/histograms/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/histograms/vz_histogram_timeseries/vz-histogram-timeseries.html
Summary:
This commit removes the histogram dashboard's dependencies on old-style
framework code, and removes mentions of histograms from core code like
`backend.ts`.
As usual (e.g., #108), I had to delete some minimal tests in
`backendTests.ts` to do this. Unfortunately, this time there were also
some substantive tests of the `convertBins` function, which I regret
leaving behind. I've included a TODO in the code to add them back in
once our frontend tests work again, which will of course be Soon™.
Note that both the old and new versions of the histogram dashboard have
an unfortunate behavior regarding graphical updates after changing run
selection state. Specifically, suppose that Histogram A and Histogram B
appear side-by-side, and the run for Histogram A is toggled off. Then we
would …
> Bring histograms back to the future

- tensorboard/backend/application.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/plugins/graphs/graphs_plugin_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
This is an import of @chihuahua's code from inside Google. Here's his original change description:
> Use the new SummaryMetadata field of the Value proto to pass per-plugin information.
> This will let TensorBoard figure out which plugins should handle which types of summaries.
> Have TensorBoard read metadata from SummaryMetadata

- tensorboard/components/tf_backend/backend.ts
- tensorboard/plugins/distributions/tf_distribution_dashboard/BUILD
- tensorboard/plugins/distributions/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/distributions/tf_distribution_dashboard/tf-distribution-loader.html
Summary:
Like #107 and #108 and #110, but now for distributions.
This change was pretty straightforward; not too much to mention. There
weren't any distribution-related tests in `backendTests.ts`, so I didn't
need to remove anything there.
wchargin-branch: refactor-distributions-dashboard
> Renovate the distributions dashboard

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/main.py
- tensorboard/plugins/base_plugin.py
We're going to allow plugins to persist data. The flag accepts a DB URI. The only thing supported currently is sqlite. It has to be a file, rather than :memory:, because memory mode only allows a single thread.
> Add --db flag for persistent storage

- tensorboard/components/tf_dashboard_common/tf-collapsable-pane.html
It looks sooo much better now. Here are the [before](https://kek.gg/i/j3J-.png) and [after](https://kek.gg/i/3_tQCK.png) screenshots.
> Make tf-collapsable-pane look good in Firefox

- tensorboard/plugins/graphs/graphs_plugin_test.py
Chi's code originally included these lines, but they broke the test when I merged yesterday. I now realize that this is because the modified code is needed once the tf.summary.text switches over from the TensorSummaryV1 implementation to the TensorSummaryV2, which generate different graphs. Apparently the switch happened in last night's nightly.
> Fix the broken graph plugin test

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/components/tf_dashboard_common/tf-no-data-warning.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/graphs/tf_graph_dashboard/tf-graph-dashboard.html
Summary:
This commit mostly consists of inlining functions from `backend.ts` and
`router.ts` into `tf-graph-dashboard.html`. The graph dashboard was
already reasonably self-contained: it didn't use `tf-panes-helper` or
other similar components, and it didn't use the Polymer behaviors. (It
had them enabled, but overrode the provide functions in such a way that
simply removing the behaviors had no observable effect.)
Test Plan:
I can load and manipulate graphs. I can load and view run metadata, like
compute time and memory usage. I can change the session run under
display, and I can change the graph under display. When I add
`debugger_data=enabled` to the URL, the graph dashboard fails in the
same way before and after this commit: it 404s on the health pills route
and the numerics route. …
> Decouple the graph dashboard from TensorBoard core

- tensorboard/components/tf_dashboard_common/tf-no-data-warning.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.html
Summary:
The most straightforward dashboard of them all! My only nit is the
existence of the `_routePrefix` Polymer property; ideally, all
subcomponents should use `getRouter().pluginRoute('projector', '/foo')`,
because setting the route prefix to an empty plugin route is somewhat
hacky. But that can be a low-priority change for another day.
Test Plan:
PCA and t-SNE work fine. The no-data warning appears correctly.
wchargin-branch: refactor-embeddings-projector
> Decouple the embeddings projector from TB core

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/router.ts
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
- tensorboard/plugins/text/tf_text_dashboard/BUILD
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
Summary:
This removes references to text-related stuff from the backend and
router, and removes references to old-style TensorBoard components like
`tf-panes-helper` and `tf-chart-scaffold`. The text dashboard, like
other dashboards, now uses only the API components that we'll want to
keep supporting (with the exception of `tf-regex-group`).
I also took the liberty of improving the implementation of the CSS for
the text loader. The appearance should be the same (with the exception
of a bugfix relating to paragraph margins), but the code is now cleaner.
Test Plan:
Tested on runs with just one tag, runs with multiple tags, and tags that
contain long values (http://lipsum.lipsum.com/). You can select and copy
text, scroll through summaries, etc.
wchargin-branch: refactor-text-plugin
> Decouple the text plugin from TensorBoard core

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/distributions/tf_distribution_dashboard/BUILD
- tensorboard/plugins/distributions/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histograms/tf_histogram_dashboard/BUILD
- tensorboard/plugins/histograms/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/histograms/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/images/tf_image_dashboard/BUILD
- tensorboard/plugins/images/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/images/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
Some files were not importing all the things that they depended on.
Instead, these dependencies were being set by unrelated files.
Amusingly, the audio dashboard is the only one that had _extra_ imports!
I'll go ahead and give it a real dashboard soon...
Test Plan:
My procedure to create this was to comment out all but one plugin at a
time in `tf-tensorboard.html`, including the import tags. Then, I ran
TensorBoard, saw that everything looked awful, and added back inputs
until it looked correct again. To test post hoc, I just checked that
everything builds and still looks correct.
wchargin-branch: strengthen-imports
> Strengthen imports

- tensorboard/plugins/images/tf_image_dashboard/tf-image-loader.html
Summary:
This got lost when I migrated the image dashboard away from using the
chart scaffold: the chart scaffold used to include the run, and I forgot
to reinstate it after removing the scaffold. Easy fix, though.
Test Plan:
Load the image dashboard with any dataset that has image summaries. Look
for a run name in the card heading. Note that the run name changes
appropriately as you adjust which runs are selected.
wchargin-branch: display-run-on-images
> Display the run on each image summary

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/audio/tf_audio_dashboard/BUILD
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
Redesign the audio dashboard
Summary:
The audio dashboard used to be laid out in a grid, with tags by row and
runs by column. This made it inconsistent with all other dashboards, and
also gave it some bizarre behaviors (e.g., if you have ten runs without
any audio summaries and then five runs with the summaries, you'd have
to scroll horizontally past all ten runs without summaries before
getting to anything interesting). The implementation also had some
needlessly complicated behavior, like generating `<source>` elements and
manually listening for onload events instead of letting the browser do
what it does best.
This commit replaces it with a clone of the image dashboard adapted to
serve audio instead. The implementation is just like the image
dashboard, but considerably simpler because …
> Redesign the audio dashboard

- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
Summary:
I removed these in PR #131 because they didn't appear to target
anything, as there aren't any table subcomponents---but in fact they
target Markdown tables that might be rendered from the text from the
backend.
wchargin-branch: markdown-tables
> Add back table styles for text dashboard

- tensorboard/components/tf_backend/backend.ts
- tensorboard/components/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
Similar to the graph plugin, only simpler.
Note that the `BackendBehavior` was not actually used at all (it
provides `runs`, `tags`, `runToTag`, and `dataNotFound`, none of which
was used). The `ReloadBehavior` was also useless, as it provided a
`frontendReload` method that (a) did nothing and (b) wasn't called. And
`DashboardBehavior` has always done nothing! So this was really just a
matter of inlining the methods from `backend.ts`, one of which was not
actually used.
Test Plan:
**None: I am not able to test this change.** I'm not able to run this
dashboard: even if I were to hook it up, I don't have the backend plugin
or the appropriate data.
I mean, it builds, I guess.
wchargin-branch: migrate-profile-dashboard
> Migrate the profile/trace viewer dashboard

- tensorboard/plugins/images/tf_image_dashboard/tf-image-loader.html
Summary:
In some cases, Polymer's reconciler opts to update components' data
bindings when the behavior actually intended is to shuffle components
around. The image dashboard should listen for those changes and update
appropriately.
(Also, a typo in the reload handler made the attached-guard a no-op.)
wchargin-branch: image-dashboard-data-bindings
> Update images in response to data binding changes

- tensorboard/main.py
Summary:
We attempt to quiet the Werkzeug logger, because it's quite verbose. But
our patch to do so wasn't robust: Werkzeug only initializes its log
handlers if we don't touch the logger at all [1]. The result of this was
that any calls to Werkzeug's log function would yield an error, 'no
handlers could be found for logger "werkzeug"'. This is particularly
problematic because the Werkzeug log function is used whenever there's
an internal server error, so the effective result was that any 500s
wouldn't print tracebacks, but instead just yield the above message.
[1]: https://github.com/pallets/werkzeug/blob/423a356d4a49a50179a2be7ba131570dbc607a34/werkzeug/_internal.py#L80-L86
This patch fixes that by emulating [1] and reinstating the default
logging handler.
Test Plan:
Apply the following …
> Fix logging and error handling

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/test/BUILD
- tensorboard/components/tf_categorization_utils/test/categorizationUtilsTests.ts
- tensorboard/components/tf_categorization_utils/test/tests.html
Summary:
This change moves the core categorization logic from `tf-categorizer`
into `categorizationUtils`. In doing so, we can strip away much of the
complexity: no one's using nonstandard categorizers, nor do we ever want
to do that, so we can remove a lot of indirection. Not coincidentally,
this change fixes #41.
After this change, nothing will be using `tf-categorizer`, so we will be
able to remove it.
Test Plan:
I included tests! Here is how to run them...
Make the following changes to `categorizationUtilsTests.ts`:
1. Replace the import statement with the literal contents of
`categorizationUtils.ts`.
2. This will add another import statement for `getTags`. Inline that
function, too. Change `.sort(compareTagNames)` to `.sort()` (it
doesn't affect any functions under test, and we don't …
> Pull categorization logic into categorizationUtils

- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/graphs/tf_graph/tf-graph-minimap.html
- tensorboard/plugins/graphs/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graphs/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graphs/tf_graph_info/tf-graph-info.html
- tensorboard/plugins/graphs/tf_graph_loader/tf-graph-loader.html
- tensorboard/plugins/images/tf_image_dashboard/tf-image-loader.html
Summary:
This eliminates all warnings except for the following:
- warnings from library code, like `paper-input-container`
(10 occurrences);
- warnings of the form "Bad type annotation. Unknown type $foo", where
$foo is a qualified type expression like `tf.scene.Minimap` or
`d3.scale.ordinal` (7 occurrences).
The former we should not fix, and should instead instruct the compiler
to ignore. The latter I'm not sure how to fix.
Most fixes in this patch simply required specifying nullability
constraints on Polymer properties and functions from TypeScript code.
(Ideally, the existence of a default value for a TypeScript parameter
would inform the Closure Compiler, but this is not the case.) Others
involved specifying default values of arguments (e.g., explicitly
setting `false` instead of …
> Fix 18 Closure Compiler warnings

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
This commit makes it so that `tf-tensorboard` creates dashboards
programmatically, instead of including HTML code for each dashboard
(namely, a `dom-if` containing the dashboard element). In doing so, we
move one step closer to being able to define dashboards at build- or
run-time.
Note that each dashboard's Polymer component still needs to be imported.
Note also: part of the functionality of this commit essentially
reimplements the Polymer component `dom-if`. I tried using `dom-if`
directly, and was thoroughly unsuccessful. (The problem is that you need
to dynamically create a data binding context, which is much more
complicated than simply dynamically creating elements. Theoretically,
this should be possible with a `dom-bind`, but I couldn't get it to
work---and, frankly, I'm …
> Create dashboard components programmatically

- tensorboard/components/tf_paginated_view/BUILD
- tensorboard/components/tf_paginated_view/tf-paginated-view.html
- tensorboard/plugins/scalars/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
The purpose of this component is to reduce lag when expanding a category
that has hundreds of summaries, especially if they're histograms or
something else that takes up a lot of space and CPU time.
As a test drive, we implement it in the scalars dashboard.
[img]: https://user-images.githubusercontent.com/4317806/27566218-9a4b639e-5a98-11e7-866a-2e283f0adc7a.png
Test Plan:
Tested page navigation with buttons and the text field (including arrow
keys in the text field). Tested persistence of per-card state, like
"toggle log scale" and "card expanded", across page navigation. Tested
both Chrome and Firefox.
This uncovers and even sheds light on a few existing bugs in the scalar
charts. For instance, if you quickly (like, 500ms delay or less) click
through a few pages, then click …
> Create a tf-paginated-view

- tensorboard/pip_package/setup.py
- third_party/python.bzl
Strangely, we load a recent version of markdown in our workspace files, but we have an outdated pip dependency.
> Upgrade pip dependency on Markdown

- tensorboard/plugins/scalars/tf_scalar_dashboard/tf-scalar-chart.html
Summary:
Remember which runs we've fetched since the last explicit reload. If we
need to load more data, don't fetch those runs again.
More details on docstring on new property.
Test Plan:
Open the network panel. Open a category with a dozen or so tags. Then,
in the list of runs, go down the list and check each run one at a time
(starting from all disabled).
Before this change:
You can see that the number of network requests is linear in the number
of selected runs, so the total number of requests is quadratic in the
number of selections you make.
After this change:
You can see that the number of network requests is constant in the number
of selected runs, so the total number of requests is linear in the
number of selections you make.
Also, deselecting runs now causes zero requests …
> Reduce unnecessary fetches in scalar chart

- tensorboard/components/tf_paginated_view/test/BUILD
- tensorboard/components/tf_paginated_view/test/paginatedViewTests.html
- tensorboard/components/tf_paginated_view/test/paginatedViewTests.ts
- tensorboard/components/tf_paginated_view/test/tests.html
- tensorboard/components/tf_paginated_view/tf-paginated-view.html
Summary:
Because the observer didn't explicitly note that `pages` depends on the
value of `_pageCount`, Polymer could sometimes update `pages` before
updating `_pageCount`. In the case that the true value of `_pageCount`
changed from `0` to `1`, this resulted in an empty array of pages being
returned.
Test Plan:
Create a category that has zero tags. Expand it. Then, update the
category to have a tag (and reload the plugin data). Before this patch,
nothing would appear in the paginated view. After this patch, the data
appears correctly.
wchargin-branch: fix-pagination-data-dependency
> Add missing data dependency in pagination view

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
This removes the `_activeDashboardIndex` property from `tf-tensorboard`,
instead directly binding `_selectedDashboard` (the name) from the tab
selector component.
This simplification is nice-to-have now, but once we start using the
`is_active` method of plugins on the backend, the set of tabs shown on
the frontend will not be constant; this change will then be significant.
While I'm at it, I changed `active` to `selected` everywhere, because
"active" means "can be selected" in our parlance.
Test Plan:
Note that there are no console errors when TensorBoard is launched, and
that you can still switch among tabs.
wchargin-branch: select-dashboards-by-name
> Track selected dashboard by name, not index

- .travis.yml
Summary:
Re-application of #100.
Test Plan:
Consider the following command:
```sh
grep -F NIGHTLY_URL= .travis.yml | \
cut -d \' -f 2 | \
xargs curl -sI | \
grep -F 'HTTP/1.1'
```
Before this commit, it outputs:
```
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
```
After this commit, it outputs:
```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```
wchargin-branch: bump-tf-nightly-to-1.2.1
> Bump Travis TensorFlow nightly URL: 1.2.0 → 1.2.1

- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
Summary:
The text plugin was checking whether any runs existed, not whether any
runs with text summaries existed.
Test Plan:
Load `/data/plugins_listing` on a data set with text summaries and one
without. Before this change, both results included `"text": true`. After
this change, the data set without text summaries has `"text": false`.
Also, the new unit test fails before this change and passes after it.
wchargin-branch: fix-text-is-active
> Fix the text plugin's `is_active` route

- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalar/vz_line_chart/vz-line-chart.ts
Summary:
This fixes a number of issues with the scalar charts, some of which are
interdependent, and all of which are existing issues made more visible
by the presence of a search pane.
In particular:
1. If a chart's `run` and `tag` properties are changed simultaneously,
two updates will be triggered, and the first update will see the
data in an inconsistent state (e.g., Tag B but still Run A). We fix
the resulting issues by making observer updates asynchronous, so
that they only actually take effect once all changes have flushed.
(This fixes #169.)
2. To reduce latency due to the above solution, we further debounce
these update handlers.
3. Because the handlers are asynchronous and debounced, we need to
maintain stronger invariants on the caching keys. (In particular, if
a chart changes …
> Improve the scalar chart user experience

- tensorboard/plugins/scalar/vz_line_chart/vz-line-chart.html
- tensorboard/plugins/scalar/vz_line_chart/vz-line-chart.ts
Summary:
Fixes #183. We now render the actual value in the "Smoothed" column
when smoothing is disabled. (This makes sense: in the limit as the
smoothing factor goes to zero, the smoothed value approaches the scalar
value, so this just makes the column continuous. It also makes the UI
less dynamic and more predictable, which is nice.)
The existing code tries to remove the "Smoothed" column altogether when
smoothing is disabled. Although the data bindings are wired correctly,
the column continues to render in the tooltip even when the `dom-if`
flips to `false`. It's completely unclear to me and @dandelionmane why
this is the case: the code certainly looks correct, and copying the
table structure verbatim into a fresh document demonstrates the right
behavior.
We're pretty sure that this is …
> Fix scalar chart tooltips when smoothing disabled

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
Don't show search results when there's no data
Summary:
The current behavior is to show a no-data warning and also an (empty)
search results pane:
This behavior was a holdover from when we had tag groups: if you had a
tag group called `.*`, it would show up under the no-data warning. But
this really isn't something that we want to do, so we should gate all
the categories behind `!_dataNotFound`.
I recommend viewing this diff with `git diff -w` (ignore whitespace-only
changes), which shows only a 12-line delta.
Test Plan:
Launch TensorBoard with no data, some data, and all data. Check that all
dashboards appear correctly in each case.
wchargin-branch: no-data-no-categories
> Don't show search results when there's no data

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/main.py
- tensorboard/util.py
- tensorboard/util_test.py
Open source logs now:
- Use the same format as Google logs
- Use ANSI color for non-INFO records
- Get emitted *above* the line with the TensorBoard URL
The functionality that makes the TensorBoard URL stick to the last line in the
terminal is ironically called "ephemeral logging" because it was designed to
meet the requirements of FileLoader's progress bar.
Please note that ephemeral logging and ANSI colors do not happen on Windows or
anything that isn't a TTY. For example, piping stderr to a file will cause
everything to look normal.
In the future, flags will be added so open source users can configure the
verbosity of the logger.
> Add open source logging infrastructure

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/functionaltests/BUILD
- tensorboard/functionaltests/core_test.py
Summary:
This commit incorporates the backend's `is_active` plugin functions and
the related `plugins_listing` handler, and uses them on the client: we
will only display dashboards that correspond to backend plugins that are
active.
Test Plan:
- Launch TensorBoard with a normal data set and note that the correct
set of dashboards is displayed.
- Launch TensorBoard with a nonexistent or empty logdir and observe
the global "no data" message.
- Launch TensorBoard and cause the `plugins_listing` network request
to fail. (In Chrome: Network devtools tab, right-click the request,
select "Block Request URL", refresh.) Note the resulting message.
Then, unblock the request, and click TensorBoard's reload button:
everything should work as usual.
- Launch TensorBoard with a large data set, and open …
> Only display active dashboards

- tensorboard/util.py
- tensorboard/util_test.py
1. This way the progress bar class doesn't need to worry about calling isatty()
and os.name.
2. We can configure the logger to go to both stderr and a file, and not end up
with ANSI codes in the log file.
> Strip ANSI codes from non-terminal log records

- tensorboard/components/tf_globals/globals.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
This resolves a `TODO` of mine to standardize the frontend and backend
names. Per an email from @dsmilkov, "Projector" is the preferred name.
Test Plan:
Verified that the dashboard is still active when it should be, inactive
when it should be, and has the "reload" button disabled.
Also, I checked the results of `git grep embeddings` and they all seem
reasonable (they're variable references, not user-facing strings).
wchargin-branch: rename-embeddings-to-projector
> Rename "embeddings" to "projector" on the frontend

- tensorboard/components/tf_dashboard_common/dashboard-style.html
Summary:
This width is wide enough that the runs selector has enough space, and
also that the "offset time axis" on the histogram dashboard shows all
dashboards on one line. No existing dashboard has controls that
naturally exceed this width.
Test Plan:
Check the conditions noted above.
wchargin-branch: sidebar-min-width
> Enforce a minimum width on the sidebar

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
There is a general issue across TensorBoard: with the tf-paginated-view, if you
switch pages quickly, it's likely that some charts will be rendered when they
are `display: none`. Data visualizations often depend on measurement code to
layout properly, and the measurements break when the item is not being
displayed. As a consequence, the chart renders wih strange and broken
proportions.
When @wchargin and I were pair-programming this, we initially tried to work
around the measurement issue so that the chart would layout properly even if it
were `display:none`, but that proved infeasible. So instead we decided to write
code to detect when the chart gets in a bad state, and fix it.
This code marks scalar charts as being in a bad state if their data finishes
loading when the chart is no …
> Fix issue where scalar charts can become tiny.

- tensorboard/__init__.py
- tensorboard/backend/__init__.py
- tensorboard/backend/event_processing/__init__.py
- tensorboard/pip_package/__init__.py
- tensorboard/plugins/__init__.py
- tensorboard/plugins/audio/__init__.py
- tensorboard/plugins/core/__init__.py
- tensorboard/plugins/distribution/__init__.py
- tensorboard/plugins/graph/__init__.py
- tensorboard/plugins/graph/tf_graph/demo/BUILD
- tensorboard/plugins/graph/tf_graph_app/demo/BUILD
- tensorboard/plugins/graph/tf_graph_board/demo/BUILD
- tensorboard/plugins/graph/tf_graph_controls/demo/BUILD
- tensorboard/plugins/graph/tf_graph_dashboard/demo/BUILD
- tensorboard/plugins/graph/tf_graph_debugger_data_card/demo/BUILD
- tensorboard/plugins/graph/tf_graph_info/demo/BUILD
- tensorboard/plugins/graph/tf_graph_loader/demo/BUILD
- tensorboard/plugins/histogram/__init__.py
- tensorboard/plugins/image/__init__.py
- tensorboard/plugins/projector/__init__.py
- tensorboard/plugins/scalar/__init__.py
- tensorboard/plugins/text/__init__.py
- tensorboard/scripts/__init__.py
- Add license headers to __init__.py files.
- Remove outdated references to //third_party/tensorflow
> Cleanup TensorBoard to satisfy Google-internal checks

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
If an inactive dashboard becomes active, it should be removed from the
list of inactive dashboards. We use a `dom-if` to control the
`paper-item`s corresponding to each inactive dashboard, so these
elements were being `display: none`d as desired. However, they still
existed in the DOM, so when the selected dashboard was set to such an
was-inactive-now-active dashboard, the inactive dashboards dropdown menu
would still display this dashboard as its currently selected item.
By restamping, we force these elements to be torn down.
Test Plan:
1. Create an empty directory `/tmp/slow`.
2. Launch TensorBoard with logdir `/tmp/slow`.
3. Load TensorBoard in the browser, and see that there are no active
dashboards.
4. Generate, copy, or symlink a run into `/tmp/slow`.
5. Click the "Reload" …
> Keep inactive dashboards list up-to-date over time

- tensorboard/functionaltests/core_test.py
Summary:
The `core_test` is very flaky on Travis. (I can't reproduce locally.)
Maybe it's due to the two test classes trying to bind to the same port,
so the latter fails?
Test Plan:
See what Travis thinks.
wchargin-branch: separate-core-test-ports
> Attempt to make Travis tests less flaky

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Summary:
This removes warnings from files like iron-a11y-announcer.html,
neon-animation-runner-behavior.html, and paper-input-container.html,
leaving us just with warnings that actually come from our own code!
The Vulcanizer is already TensorBoard-aware with respect to error
suppression (e.g., the "/tf-graph" check), so it seems fine to me to
hard-code these libraries.
Test Plan:
Run `bazel build tensorboard` and inspect the warning count. This brings
us down from 17 warnings to 7 warnings, and—just as importantly—has the
effect that the warnings all fit on a single screen! (As long as your
terminal has at least 27 rows.)
wchargin-branch: suppress-closure-warnings-from-libraries
> Ignore Closure Compiler warnings from library code

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Previously, the timestamp shown for each image had been Sun Jan 18 1970 00:38:34 GMT-0800 (PST) because a time in seconds (instead of milliseconds) had been passed to the Date constructor.
This fixes issue #225. This screenshot is from a demo with some data generated last year:
> Fix timestamps in the image dashboard

- tensorboard/components/BUILD
- tensorboard/components/tensorboard.html
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/components/tf_tensorboard/demo.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.html
This is going to allow our friend in chrisranderson/beholder#4 to build a
custom TensorBoard, without needing to copy the whole of tf-tensorboard.html
into his repository.
> Make tf-tensorboard less hard coded

- tensorboard/BUILD
- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/pip_package/BUILD
- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/core/BUILD
- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/profile/BUILD
- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/text/BUILD
- tensorboard/scripts/BUILD
- third_party/html5lib.BUILD
- third_party/python.bzl
- third_party/six.BUILD
- third_party/werkzeug.BUILD
- third_party/workspace.bzl
This is slight breaking change. BUILD files must be updated as follows:
- @six_archive//:six             -> @org_pythonhosted_six
- @org_pocoo_werkzeug//:werkzeug -> @org_pocoo_werkzeug
We want repository names to be consistently canonicalized with DNS. We also
want the primary build rule in a repository to have the same name as the
repository itself. This allows us to take advantage of Bazel's elegant label
shortening.
> Change Werkzeug and Six build labels

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
Summary:
The categorization utils require that any run in selectedRuns have a
corresponding entry in runToTag. By relaxing this requirement (and
defaulting to []) we make it easier for alternate backends to
implement the /tags routes.
Test Plan:
Verified that when the output of /data/plugin/histograms/tags is
changed to not include runs without histogram tags, the categorization
functions still work without raising "cannot read property forEach of
undefined."
> Allow `runToTag` to omit irrelevant runs

- .travis.yml
Summary:
Re-application of #182.
Test Plan:
Consider the following command:
```sh
grep -F NIGHTLY_URL= .travis.yml | \
cut -d \' -f 2 | \
xargs curl -sI | \
grep -F 'HTTP/1.1'
```
Before this commit, it outputs:
```
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
```
After this commit, it outputs:
```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```
wchargin-branch: bump-tf-nightly-to-1.3.0rc0
> Bump Travis TensorFlow nightly URL: 1.2.1 → 1.3.0rc0

- DEVELOPMENT.md
Not found `plugins/scalars` dir.
> Fix typo in DEVELOPMENT.md

- tensorboard/functionaltests/BUILD
Summary:
Per the [Bazel docs], this should let the test run up to three times
until it's marked as failed. A stopgap to reduce build failures and
overall build times (we won't have to wait for a full 10-minute build,
just a 100-second re-test…(“just”…)).
[Bazel docs]: https://docs.bazel.build/versions/master/be/common-definitions.html#test.flaky
Test Plan:
None.
wchargin-branch: mark-webdriver-flaky
> Mark webdriver tests as flaky

- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
The current tf-graph-app element defaults to 100% width, 650px height, and includes a toolbar with a number of features. This PR add the ability for someone to specify width & height values in pixels, as well as toggle the toolbar visibility. The reason for this is that some instances of the graph need to be a particular size and often need to avoid using the toolbar.
To test:
```html
<tf-graph-app width="400" height="450" toolbar="false"></tf-graph-app>
```
And you should have a graph 400px x 450px sans toolbar! :+1:
> Adds width, height, and toolbar / sidebar visibility support

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
Summary:
Now that there is data stored in the `SummaryMetadata` that is not part
of the `plugin_data[*].content`, we need to expose this data to plugins.
This commit adds a `SummaryMetadata` function to return the entire
metadata proto, from which interested parties can pick out the display
name and summary description.
Test Plan:
`bazel test //tensorboard/...`
wchargin-branch: expose-summary-metadata-from-multiplexer
> Expose `SummaryMetadata` from event multiplexer

- tensorboard/plugins/graph/tf_graph_common/node.ts
Originally, when expanding a node, all annotation nodes representing that node
would take on the expanded color. Now, the annotation nodes will retain the
color of the non-expanded node.
> Fixed annotation coloring when node is expanded.

- tensorboard/plugins/graph/tf_graph_common/render.ts
Originally, annotation nodes were not being stylized during the initial graph
display due to the RenderNodeInfo not being passed into the Annotation
constructor functions.
> Annotation nodes will now be stylized on initial graph display.

- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/histograms_demo.py
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/histogram/metadata.py
- tensorboard/plugins/histogram/summary.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/histogram/tf_histogram_dashboard/histogramCore.ts
- tensorboard/plugins/histogram/tf_histogram_dashboard/test/histogramTests.ts
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
Summary:
This commit introduces a new-style summary for histograms, which new
code should prefer over `tf.summary.histogram`. The new summary is not
privileged and is built on top of `tensor_summary`.
I've updated the histogram dashboard to support both the old and new
forms.
Once `display_name` and `description` are implemented, we can start
using those in the API, backend, and frontend. Doing so will give us the
opportunity to strip out the ugly `.../histogram_summary` from the tag
on the frontend. (I could have done this in this commit, but wanted to
keep it reasonably sized.)
Note: we don't have a way to run the `histogramTests` on the frontend,
and per #174 they don't pass anyway. I tried to make them valid but did
not run them and provide no guarantees!
Test Plan:
Generate test data …
> Create a tensor histogram summary

- tensorboard/plugins/graph/tf_graph_common/render.ts
Annotation nodes were not being properly highlighted if there parent's
name was a substring of their hierarchical path name. Say we had a node
'A/B/C' who is an annotation node for node 'A/B'. Originally, when we
hovered over the node 'A/B/C', the node 'A/B' would be highlighted. We
fix this bug by first finding the first non-expanded node, and then
checking to see if the next node is an annotation of the first
non-expanded node, which means that it is also visible.
> Fixed annotation node hover/highlighting bug

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
The inactive menu dropdown now just says "Inactive" so the text doesn't render
with ellipsis. The brightness of the "Loading active dashboards" text has also
been reduced. This is so we draw less attention to the fact that TensorBoard is
loading.
> Make inactive dashboard UI subtler

- .travis.yml
These warnings are nice because they tell us when we should do things like have
size="small" on our test rules. That allows our internal CI system to schedule
tests more effectively.
> Have Travis show test size warnings

- .travis.yml
Summary:
Re-application of #252.
Test Plan:
Consider the following command:
```sh
grep -F NIGHTLY_URL= .travis.yml | \
cut -d \' -f 2 | \
xargs curl -sI | \
grep -F 'HTTP/1.1'
```
Before this commit, it outputs:
```
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
```
After this commit, it outputs:
```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```
wchargin-branch: bump-tf-nightly-to-1.3.0rc1
> Bump Travis TensorFlow nightly URL: 1.2.1rc0 → 1.3.0rc1

- tensorboard/plugins/pr_curve/summary.py
Per issue tensorflow/tensorflow#11856, a variable cannot be read from
directly after it is merely initialized in a TensorFlow graph. We must
instead use read_value to retrieve its value. This means that using
tf.scatter_add is problematic because it only accepts a single mutable
tensor (tf.Variable) that is both written to and read from.
Hence, we avoid using tf.scatter_add and re-implement its logic using
tf.gather and tf.scatter_update. We also use read_value() to retrieve
the values of variables throughout the summary logic.
This fixes #302.
> Fix :summary_test by avoiding scatter_add

- tensorboard/BUILD
- tensorboard/plugin_util.py
- tensorboard/plugin_util_test.py
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
- tensorboard/plugins/text/BUILD
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
Summary:
Now that every summary has a `summary_description` field, plugins will
need to serve rendered Markdown to the frontend (assuming that we don't
want to do Markdown rendering in JavaScript, which we don't). This
has security implications (sanitization), so TensorBoard should expose a
function that does the right thing.
An alternative would be to provide a route that provides rendered
Markdown for the `summary_description` only. This has disadvantages:
(1) it would require at least one extra network roundtrip (plugins must
first request the list of tags, then request the rendered description),
(2) it would induce a FoUC-like state where the tags have been fetched
but their metadata has not; and (3) it would not generalize to plugins
that want to safely render other kinds of …
> Centralize a `markdown_to_safe_html` function

- tensorboard/components/tf_card_heading/BUILD
- tensorboard/components/tf_card_heading/tf-card-heading.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/histogram/histograms_demo.py
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
Summary:
This commit retrofits `tf-card-heading` to display the new metadata
associated with summaries.
Test Plan:
Re-run the histogram demo to generate test data with summaries. Then,
check that all dashboards behave properly, and that the histogram
dashboard has an option to show descriptions.
wchargin-branch: show-display-name-and-description
> Display summaries' `displayName` and `description`

- .travis.yml
The previous links, based on specific versions (1.3.0rc1), are not
stable and will change with each and every release. The links here,
with fixed name "head" is stable and will never change (until TF 2 comes
out).
> Use head pip artifacts in build+test environment

- tensorboard/BUILD
- tensorboard/data_compat.py
- tensorboard/data_compat_test.py
Summary:
As we move from using old-style summaries to using only tensor
summaries, we need to continue supporting the old formats. The only
plugin that has been converted so far is the histogram plugin, and that
plugin manages the compatibility itself. But it would be nicer to have a
unified Event Translation Layer where we convert all the old-style
events to new-style events. Once we do this, plugin code will only have
to deal with new-style events---which is especially attractive because
it makes the plugins more copy-pastable.
This commit introduces `data_compat`, a module that will perform such
conversions. This module will intercept events before the event
accumulator processes them. This is forward-compatible with SQL mode:
we can simply call out to this module from the SQL loader …
> Introduce `data_compat`, legacy summary converter

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/db.py
- tensorboard/db_test.py
This code only supports SQLite, but the schema itself takes Spanner, MySQL, and
other DBs into consideration, which we intend to support soon.
The following tables are defined:
- Experiments: Has one-to-many relationship with Runs.
- Runs: Has one-to-many relationshi with Tags, with experiment locality.
- Tags: Has one-to-many relationship with Tensors, with experiment locality.
- Tensors: Gzipped tf.Tensor protos stored in-page with tag locality.
- BigTensors: A one-to-one Tensor storage with no particular locality.
- EventLogs: Used to track loader progress for Runs.
While serving anything related to a given experiment, TensorBoard will fetch
all Runs, Tags, and TagsPlugins rows associated with that experiment at once,
and cache them for a short period of time.
When TensorBoard serves …
> Define SQL schema for tensor storage

- tensorboard/backend/application.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/distribution/compressor.py
- tensorboard/plugins/distribution/compressor_test.py
- tensorboard/plugins/distribution/distributions_plugin.py
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
Summary:
This commit moves histogram compression from the event accumulator to
the distributions plugin. That is, instead of compressing histograms at
event processing time, we compress them at serving time (when the
`/distributions` route is requested). This should have no performance
impact, as the number of buckets in the histograms being compressed is
at most 30 (unless the user overrides the default), and the compression
algorithm is already very efficient.
Here is one subtle effect of this change: because the histograms and
compressed histograms had different reservoir sizes, naively applying
the change as described above would result in the time granularity of
the rendered distributions becoming significantly more coarse. (See
screenshots below.) To resolve this effect, we raise …
> Remove histogram compression from TensorBoard core

- tensorboard/functionaltests/BUILD
Summary:
This test takes over 100 seconds to run and often fails multiple times.
It has never discovered any regressions, and causes far more trouble
than it is worth. @caisq reports that it sometimes hits hard timeout
limits. We should run it manually only.
Test Plan:
To verify that this commit does in fact prevent the test from running
automatically, invoke `bazel test //tensorboard/...` and note that it
completes within a reasonable amount of time, and in particular that
this test is not included in the list of passing tests.
wchargin-branch: disable-webdriver-test
> Make webdriver test manual-only

- tensorboard/plugins/pr_curve/summary.py
Set the default parameter value for `weight` as well as `num_thresholds` to be `None`. That had slipped through a previous PR.
> Set defaults for weight and num_thresholds to None

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
We now hide the "Show health pills" toggle within the graph dashboard
when the debugger plugin is inactive.
When the debugger is active:
vs inactive:
Previously, the problem had been that a dom-if block had been used as a
direct child of a `<table>` element. Apparently, polymer ignores the
dom-if condition in that case. I also formatted the toggles using divs
instead of tables and positioned labels to the right of their respective
toggle widgets for alignment.
Fixes #318.
> Hide "Show health pills" when debugger is inactive

- tensorboard/backend/application.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/http_api.md
- tensorboard/plugins/distribution/distributions_plugin_test.py
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/histograms_plugin_test.py
Summary:
This commit simply hooks up the existing `data_compat` module to the
event accumulator. This is possible now that the distributions dashboard
does not rely on the existence of old-style histogram events.
In doing so, we remove the logic for old-style histograms from the event
accumulator and multiplexer. (Ideally, I'd prefer to do this in a
separate commit, but the tests depend heavily on this behavior, so it's
far easier to just knock 'em all out in one go. This is why this commit
is not only a few lines. But the delta is all red!)
Test Plan:
Take TensorBoard for a test drive (paying closest attention to the
histograms and distributions dashboards), and run all tests.
wchargin-branch: use-data-compat
> Perform legacy event conversion with `data_compat`

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
Summary:
In the current model, we determine reservoir size solely by which
`oneof value` is relevant to a given summary (e.g., `image` summaries
and `simple_value` scalar summaries have different values). But once
everything becomes a tensor, we lose this ability to differentiate.
This patch introduces a short-term solution, wherein we dispatch on the
`plugin_name` from the plugin metadata. It is short-term because it
preserves the current privileging of first-party plugins instead of
reducing it. However, it is a necessary step for porting our first-party
plugins to use tensor summaries.
Test Plan:
Note that before this change text summaries would have 500 samples due
to #291, while after this change they are back down to 10 while
distributions remain at 500 and histograms at 50 (by …
> Allow tensor reservoir size to depend on plugin

- tensorboard/BUILD
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/metadata.py
- tensorboard/plugins/image/plugin_data.proto
- tensorboard/plugins/image/summary.py
- tensorboard/plugins/image/summary_test.py
Summary:
This commit introduces a new-style summary for images, which new code
should prefer over `tf.summary.image`. The new summary is not privileged
and is built on top of `tensor_summary`.
The backend has not yet been updated, so there is no user-visible
effect. The next PR will contain a demo (including screenshots), and the
one after that will contain the backend and frontend changes.
The `pb` function is not yet supported because we don't have a
PNG-encoding library that is not TensorFlow, and we try to implement the
`pb` functions without using TensorFlow kernels (i.e., stuff like
`tf.make_tensor_proto` is of course fine, but `tf.Session.run()` is
not).
Test Plan:
Run `bazel test //tensorboard/plugins/image:summary_test`.
wchargin-branch: tensor-image-summary
> Create a tensor image summary

- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/images_demo.py
Summary:
This demo exhibits two of my favorite kinds of convolutions…and also
provides valuable test data for the image plugin.
It uses one CC-BY-SA image, which is properly attributed in both the
code and the resulting summaries.
Here's a screenshot of the resulting dashboard:
wchargin-branch: images-demo
> Add an images demo using the new summary

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/data_compat.py
- tensorboard/data_compat_test.py
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/images_plugin.py
- tensorboard/plugins/image/images_plugin_test.py
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Summary:
This commit adds support for new-style image summaries to the plugin
frontend and backend.
From the previous PR (#314), here's a screenshot of the resulting
dashboard:
Old-style and new-style image summaries handle larger-than-unit batch
sizes in different ways. Old-style summaries create multiple tags, and
may emit multiple summaries per step. New-style summaries can't do this
(they have to emit a single tensor at every step), so they emit a tensor
containing all the images at once. The new-style format gives us more
flexibility as to how we display the result (see #296 for some ideas),
but for now we preserve the form of the UI used for the old-style
summaries.
This change is fully compatible with the old data format.
Test Plan:
Run `bazel run …
> Support new-style image summaries

- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_common/BUILD
- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/node.ts
- tensorboard/plugins/graph/tf_graph_common/op.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_common/tf-graph-common.html
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_info/BUILD
- tensorboard/plugins/graph/tf_graph_info/tf-graph-info.html
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
- tensorboard/plugins/graph/tf_graph_op_compat_card/BUILD
- tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
- tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.html
This feature allows the user to view the graph with the new
compatibility coloring option. This option will color the nodes on the
graph by whether they are compatible for their assigned Device. This
feature is only viewable based on the debuggerData flag.
Currently, if an op is not specified a device, the device is defaulted
to the TPU. Furthermore, all ops are considered compatible for CPU and
GPU devices, while a whitelist of compatible ops are specifed for the
TPU.
> Add op compatibility graph coloring option

- tensorboard/BUILD
- tensorboard/encode_png_benchmark.py
- tensorboard/util.py
- tensorboard/util_test.py
Summary:
This commit introduces a function `tensorboard.util.encode_png`, which
efficiently encodes PNGs using a TensorFlow backend. The function uses a
persistent TensorFlow session and graph, and is highly parallelizable.
(See the module docstring of `encode_png_benchmark.py` for timing data.)
A subsequent commit will make use of this function from the image
plugin.
Test Plan:
The core has comprehensive tests: `bazel test //tensorboard:util_test`.
The benchmark does not have tests. I verified that it works correctly
under both Python 2 and Python 3.
wchargin-branch: encode-images-in-python
> Encode images in Python with a TensorFlow kernel

- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/summary.py
- tensorboard/plugins/image/summary_test.py
Summary:
This commit completes the implementation of the image summary's `pb`
function by using `tensorboard.util.encode_png` for PNG encoding.
In doing so, we can remove the stubs for the PNG encoding from the test.
Interestingly, this change makes the Python 3 tests take significantly
longer, without a corresponding increase in the Python 2 test timing.
Tests take 2.2s on Python 2 and 10.3s on Python 3. These results are
consistent within 0.2s across multiple runs. The previous times were
1.6s for Python 2 and 1.9s for Python 3, consistent within 0.1s.
I haven't investigated the discrepancy.
Test Plan:
Unit tests suffice. Run `bazel test //tensorboard/plugins/image:all`.
wchargin-branch: use-encode-png-in-image-plugin
> Use `encode_png` in the image plugin

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/db.py
- tensorboard/db_test.py
- tensorboard/test_util.py
- tensorboard/util.py
- tensorboard/util_test.py
These helpers allow us to do optimistic write-deferred transactions retried
with exponential back-off. This is necessary because we're planning to compute
primary keys randomly, in order to get good sharding behavior, and collisions
might occur. Writes are deferred to minimize the amount of time that SQLite
needs a RESERVED lock, which blocks both transactional reads and writes.
This was implemented by composing the PEP 249 API, which was burdensome,
but will pay dividends as we support more databases.
> Implement DB transaction logic

- tensorboard/BUILD
- tensorboard/loader.py
- tensorboard/loader_test.py
This class delegates to RecordReader and decodes the individual protos. It
supports marking which is going to be needed when transactions have transient
failures. Instances are sortable, which assists with reading them in order.
> Introduce loader.EventLog helper class

- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/projector_plugin_test.py
This change makes the projector plugin start a separate thread to compute whether it is active. This allows the `is_active` method to return immediately. Otherwise, it may take a long time to return, which could cause issues. See #301.
We can actually compute the `_is_active` property in less time by halting the other thread when we know we have 1 entry in the config object (instead of computing all the values of the object), but computing the config object should usually not take severely long anyway so the added complexity and duplicated logic does not seem worth it.
> Make is_active for projector return quickly

- .travis.yml
Summary:
We were recently encountering the following error on Travis on any
attempt to import `tensorflow` in the Python 3 environment:
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
```
This exception ultimately manifests with the following message:
```
SystemError: initialization of _pywrap_tensorflow_internal raised unreported exception
```
The Travis logs include the following line during the TensorFlow
installation:
```
Requirement already satisfied: numpy>=1.11.0 in /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages (from tensorflow==1.head)
```
This indicates that the Travis system already has a conflicting numpy
version installed. Because we’re not using a virtualenv, this conflict
prevents TensorFlow from being imported. …
> Force reinstallation of TensorFlow deps on Travis

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/data_compat_test.py
- tensorboard/plugins/histogram/metadata.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/image/metadata.py
- tensorboard/plugins/image/summary_test.py
- tensorboard/plugins/pr_curve/summary.py
We had just modified the plugin_data field of SummaryMetadata to be
optional instead of repeated. TensorBoard code must now jive with that
because that change is now in TensorFlow nightly.
This change makes tests pass again.
> Make TensorBoard logic assume 1 plugin_data

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
Summary:
Same as #226, but for audio summaries.
Test Plan:
Before:
After:
wchargin-branch: fix-audio-timestamps
> Fix timestamps in the audio dashboard

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
Previously, the call to tensor_summary within the PR Curve summary op accepted the tag as the name parameter. This should be the name of the plugin instead. The pattern followed by existing ops is to create a name-scope of tag specified by the user and then create a summary with the name of the plugin.
> Make tensor_summary accept 'pr_curves' as a name

- tensorboard/util.py
- tensorboard/util_test.py
Summary:
I built some useful infrastructure in #320, and right now we only use it
to encode PNGs. We’ll soon want to encode WAV files, too, and it’s quite
plausible that future use cases will arise. Therefore, this commit makes
a class `_PersistentOpEvaluator` to manage the infrastructure. Users can
extend this class to create a particular kind of op evaluator, just like
our existing `_TensorFlowPngEncoder`.
Test Plan:
The only API changes are private within the `tensorboard.util` module.
Unit tests suffice: `bazel test ...`.
wchargin-branch: persistent-op-evaluator
> Extract a PersistentOpEvaluator abstraction

- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/audio/metadata.py
- tensorboard/plugins/audio/plugin_data.proto
- tensorboard/plugins/audio/summary.py
- tensorboard/plugins/audio/summary_test.py
- tensorboard/util.py
- tensorboard/util_test.py
Summary:
This commit introduces a new-style summary for audio, which new code
should prefer over `tf.summary.audio`. The new summary is not privileged
and is built on top of `tensor_summary`.
The backend and `data_compat` layers have not yet been updated, so there
is no user-visible effect. The next PR will incorporate the remaining
changes.
NOTE: This change requires a TensorFlow build from 2017-08-11 nightly or
later. (Specifically, we need 22730fd4c633a74e59c03ff76dc92e6ae2d5d020.)
Test Plan:
The new code is completely self-contained (nothing references it), so
the additional unit tests suffice: `bazel test ...`.
wchargin-branch: tensor-audio-summary
> Create a tensor audio summary

- tensorboard/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/data_compat.py
- tensorboard/data_compat_test.py
- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/audio/audio_demo.py
- tensorboard/plugins/audio/audio_plugin.py
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/audio/tf_audio_dashboard/BUILD
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
Summary:
This commit adds support for new-style audio summaries to the plugin
frontend and backend.
Here is a screenshot of the resulting dashboard:
This change is fully compatible with the old data format.
Test Plan:
Run `bazel run //tensorboard/plugins/audio:audio_demo` to get data
using new-style audio summaries. Also grab some old-style audio
summaries, perhaps by running the version of that target that appeared
before this commit (and changing the logdir to avoid writing into the
same directory). Launch a TensorBoard with a logdir enclosing all of
this data, and verify that it all renders correctly.
When running `bazel test //tensorboard/...`, be aware that this diff
contains a particularly large number of uses of `tf.compat.as_bytes` and
friends. Thus, it is wise to run this test …
> Support new-style audio summaries

- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/scalar/metadata.py
- tensorboard/plugins/scalar/plugin_data.proto
- tensorboard/plugins/scalar/summary.py
- tensorboard/plugins/scalar/summary_test.py
Summary:
It's the last one! This commit introduces a new-style summary for
scalars, which new code should prefer over `tf.summary.scalar`. The new
summary is not privileged and is built on top of `tensor_summary`.
The backend and data_compat layers have not yet been updated, so there
is no user-visible effect. The next PR will incorporate the remaining
changes.
Test Plan:
The new code is completely self-contained (nothing references it), so
the additional unit tests suffice: `bazel test ...`.
wchargin-branch: tensor-scalar-summary
> Create a tensor scalar summary

- tensorboard/BUILD
- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/data_compat.py
- tensorboard/data_compat_test.py
- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/scalar/scalars_demo.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
This commit adds support for new-style scalar summaries to the plugin
frontend and backend.
Here is a screenshot of the resulting dashboard:
This change is fully compatible with the old data format.
Removing the scalars from the event accumulator required more changes
than usual to test code, because test code often used scalars as a
"dummy event type" (understandably, when it was privileged). I switched
all of those occurrences to use tensors.
With respect to summary display names and titles, the scalar dashboard
is different from others: as it aggregates across runs, it needs to be
prepared for variation in these values. The screenshot above shows how
this is handled; see comments in `tf-scalar-dashboard.html` for a more
precise description. This was made by applying the …
> Support new-style scalar summaries

- tensorboard/plugins/pr_curve/summary.py
This change renames the weight parameter of the op method (for PR curve
summaries) to weights to more accurately reflect how the user should
pass in a tensor with multiple weights. Updated the docs for the
parameter correspondingly. Passing in a non-zero scalar value (as opposed to a
tensor) would do nothing because it is canceled out in division.
> Rename the weight parameter to weights

- tensorboard/util.py
- tensorboard/util_test.py
Summary:
We’ve used this class three times now (encoding PNGs, encoding WAVs, and
[performing nearest-neighbor resizing][1]). The API has proven to be
sufficiently permissive to be widely useful, so we should expose this
publicly.
[1]: https://github.com/chrisranderson/beholder/issues/48#issuecomment-322533474
Test Plan:
There are no changes in functionality. All unit tests pass.
wchargin-branch: expose-persistentopevaluator
> Expose the `PersistentOpEvaluator` class

- tensorboard/plugins/histogram/summary.py
- tensorboard/plugins/scalar/summary.py
Summary:
I’d been using the implicit definition that “dtype *x* is **compatible
with** dtype *y* if `tf.cast(op, y)` is valid when `op` has dtype *x*”.
However, it appears that [TensorFlow uses the term “compatible” to mean
something different][1]. To avoid confusion, I’m switching to “castable
to,” which is a bit less of a real word but just as clear.
[1]: https://www.tensorflow.org/api_docs/python/tf/DType#is_compatible_with
wchargin-branch: reword-compatible-with
> Reword “compatible with” → “castable to” in docs

- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
Summary:
We used to have a blanket `pointer-events: none` provided by
`tf-chart-scaffold`. We no longer have such a construction, so these
exemptions are no longer required.
Test Plan:
Note that you can still click on all the buttons.
wchargin-branch: remove-unneeded-styles
> Remove some unneeded styles

- tensorboard/plugins/text/BUILD
- tensorboard/plugins/text/text_demo.py
Summary:
After this commit is merged, all our first-party summaries will include
demos.
Screenshot:
Test Plan:
Run the demo with `bazel run //tensorboard/plugins/text:text_demo` and
then point TensorBoard at `/tmp/text_demo`. Verify that the data renders
correctly.
wchargin-branch: text-demo
> Add a demo for the text plugin

- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/histogram/metadata.py
Summary:
For consistency with the rest of plugins, we should pick one of
`parse_{plugin,summary}_metadata` and stick to it. I opine that the
former is better, because the latter could be confused as parsing an
entire `SummaryMetadata` proto, while really all that we're doing is
parsing the plugin-specific data.
Test Plan:
The `metadata` module is private, so there are no external API changes.
Lint and tests suffice.
wchargin-branch: rename-histogram-metadata-parser
> Rename internal histogram metadata parser function

- tensorboard/plugins/audio/summary.py
- tensorboard/plugins/histogram/summary.py
- tensorboard/plugins/image/summary.py
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/scalar/summary.py
Summary:
We’d like to push a new pip package, but we also recognize that the new
summary modules are still somewhat in development, and we want to retain
the flexibility to change either the Python APIs or the format of the
data stored on disk. As these APIs are additions to existing
functionality, it should be sufficient to clearly indicate their status
in the module docstrings.
A follow-up commit will explicitly version the metadata protos for each
summary.
wchargin-branch: summary-modules-in-beta
> Add "in beta" warnings to new summary modules

- tensorboard/plugins/audio/metadata.py
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/metadata.py
- tensorboard/plugins/histogram/plugin_data.proto
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/image/metadata.py
- tensorboard/plugins/image/plugin_data.proto
- tensorboard/plugins/pr_curve/BUILD
- tensorboard/plugins/pr_curve/plugin_data.proto
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
- tensorboard/plugins/scalar/metadata.py
Summary:
This commit ensures that the plugin data proto defined by each plugin
has an `int32 version = 1` field, where the only value currently
supported is `version = 0`. Plugins that have a `metadata` module have
had such modules updated to populate the field appropriately when
generating protos, and check it when deserializing, emitting a warning
if the version is not recognized (and, presumably, performing some
transformations if the data is from an older version).
While we’re at it, we rename `pr_curve.proto` to `plugin_data.proto` so
that it can fit in with all the rest of the plugins.
Test Plan:
Run all unit tests. Then, launch TensorBoard with data from all plugins
that have frontends, and verify that everything is still displayed
properly. …
> Explicitly version plugin data protos

- tensorboard/BUILD
- tensorboard/loader.py
- tensorboard/loader_test.py
- tensorboard/test_util.py
- tensorboard/util.py
The `RunReader` weaves `EventLogReader` handles together into one continuous stream of events.
It's able to store the file offset in the database so we don't import the same data twice. This allows the loader to be re-run on the same experiment directory, over and over again, as new contents are added, without suffering the penalty of doing everything from scratch. This is helpful since SQL will introduce some overhead.
It also has functionality for our cool progress bar.
The mark and reset functionality is being moved into this class. It's not needed in the other one. The purpose of this functionality is so we can retry aborted transactions.
> Add RunReader class to loader module

- tensorboard/plugins/graph/tf_graph_common/minimap.ts
Summary:
In the graph dashboard, we attempt to set the size of the download
canvas according to the scene size. However, the syntax that we use to
do this is no longer supported by d3v4 ([source]), and so this ends up
doing nothing. Simply changing the syntax fixes the bug.
Fixes #88.
[source]: https://github.com/d3/d3/issues/2793
Test Plan:
Launch the graph explorer, and click "Download PNG" at left. Before this
patch, this always resulted in a 300×150 px image. Now, it results in an
image whose size is properly determined by the contents of the graph.
wchargin-branch: fix-graph-png-size
> Fix downloaded graph PNGs to make them not tiny

- tensorboard/version.py
This will correspond with the TensorFlow 1.4.x release.
Cherry-picks for TensorBoard 0.1.x (TF 1.3.x) will go in our `0.1` branch.
> Make version at HEAD 0.4.0

- tensorboard/pip_package/setup.py
Summary:
We need this for changes to `SummaryMetadata`. Trying to run TensorBoard
on TensorFlow 1.2.0 yields the error
```
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/google/home/wchargin/tensorboard-0.1.4-on-tensorflow-1.2/local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 327, in _reload_forever
reload_multiplexer(multiplexer, path_to_run)
File "/usr/local/google/home/wchargin/tensorboard-0.1.4-on-tensorflow-1.2/local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 301, in reload_multiplexer
multiplexer.Reload()
File …
```
> Declare dependency on TensorFlow >= 1.3.0

- tensorboard/plugins/projector/projector_plugin.py
Currently, Projector has a tensor cache (of size 1) indexed by tensor name. When a tensor of the same name is requested successively for different runs, the same cached value is served every time, resulting in the wrong embedding being displayed.
This change fixes the issue by using `(run, tensor_name)` tuples as keys to the tensor cache.
> Fix Projector bug causing the wrong embeddings to be displayed

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_info/tf-graph-icon.html
- tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.html
- tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.html
Previously, Closure type annotations with non-native types (such as those within the tf.* or d3 namespace) triggered compile-time warnings noting that the types were not known.
If the types were not known, then the Closure compiler had not been using the annotations to enforce type safety anyway. Therefore, this change removes those annotations in favor of explicitly mentioning the type in a comment.
I am not sure how to make those types available to HTML files at the Closure level. Maybe we could dynamically generate an extern? Anyways, that seems like it might not be worth it because the HTML files are mostly un-annotated with types.
This fixes #355.
> Remove Closure annotations for non-native types in HTML files

- tensorboard/plugins/graph/tf_graph_common/graph.ts
Previously, if a function lacks input_args or lacks output_args, the
graph explorer would be unable to load a graph because
`input_arg['name']` triggers an error (due to input_arg being undefined).
And indeed, functions without inputs (such as one with this signature from #375)
are possible:
```
signature {
name: "_make_dataset_14a55393"
output_arg {
name: "BatchDataset"
type: DT_RESOURCE
}
}
```
Likewise, nothing stops the `function.Defun` API from making a function
without outputs (and only side effects).
This change guards those cases. Fixes #375. I can view the graph from the TensorFlow workshop (07_structured_data.ipynb) after this change:
> Guard no input or output args for functions

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/node.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
Rendered `input_arg`s of TensorFlow functions as brown triangles. Rendered `output_args` of TensorFlow functions as teal triangles.
Triangles nicely convey a sense of direction and seem starky different from other nodes.
Screenshot:
> Visualize function inputs and outputs as triangles.

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/layout.ts
- tensorboard/plugins/graph/tf_graph_common/node.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
This change adds a "Functions" scene group if the graph being visualized has a function library, which contains definitions for functions (templates for subgraphs) used in the TensorFlow graph.
As part of that effort, this change also strips the arbitrary hexadecimal suffix from names of functions in the graph. That suffix is not user-generated - it merely serves to distinguish between functions with the same name but different signatures.
This refactors the implementation to prefix metanodes representing functions with `FUNCTION_LIBRARY_NODE_PREFIX` instead of lumping them under a metanode named `FUNCTION_LIBRARY_NODE`. We now also remove the function metanodes from the core graph later when building the sub-hierarchy instead of excluding them in the first place from the `__root__` …
> Add a "Functions" scene group

- tensorboard/pip_package/setup.py
This removes a dependency cycle - previously, tensorboard depended on tensorboard, which depended on tensorboard. This led to issues such as #410.
> Remove tensorflow from tensorboard's list of required packages

- tensorboard/defs/web.bzl
skipLibCheck means that the TypeScript compiler will not check `.d.ts` files for
internal correctness. It will only check their use in `.ts` files.
This works around two issues:
- With certain inputs, Clutz will produce inconsistent `.d.ts` files. The
problems are cosmetic insofar as using the APIs generated works and checks
correctly, just the `.d.ts` doesn't check out internally. As no user wrote
that code, it doesn't make sense to check it.
- TypeScript initially reads large declaration files such as `lib.d.ts`. That
takes a lot of time, so this change will speed up compilation.
This change unblocks an upgrade of Clutz in google3.
> Pass skipLibCheck to tsc in ts_web_library

- tensorboard/util_test.py
It uses a binary comparison that is flaky internally.
> Remove OpEvaluator graph preservation test

- tensorboard/plugins/debugger/debugger_plugin_testlib.py
`tf.test.mock.patch` makes me sad because it's bad for static analysis and bad for syncing.
CC: @caisq
> Use tf.test.mock.patch.object

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalar/vz_line_chart/vz-chart-helpers.ts
- tensorboard/plugins/scalar/vz_line_chart/vz-line-chart.html
- tensorboard/plugins/scalar/vz_line_chart/vz-line-chart.ts
Specifically, rewired the vz_line_chart component to take
- an object that configures the X axis (the specific field and scale)
- an Plottable accessor that computes the value on the Y axis
- a list of TooltipColumns that specify the columns within the table in the tooltip
Modified tf-scalar-chart.html to use the generalized logic. This change sets the stage for the precision—recall curve plugin to also use vz_line_chart, discouraging duplicate code.
Unfortunately, by generalizing vz_line_chart instead of tf-scalar-chart.html, we do miss out on some benefits. tf-scalar-chart.html contains some logic to correct bugs in Plottable (#163, #189, #204). We should think about how to bring those benefits to other dashboards that use vz_line_chart.
This PR is a part of dividing …
> Generalize vz_line_chart

- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
Previously, the profile plugin had been outputting build warnings. This change removes them. Interestingly, the warnings (outputted by Closure) indicate that we should not use optional function parameters in our code. TypeScript allows for parameters with default values, but Closure will issue a warning.
> chizeng-macbookpro:tensorboard chizeng$ bazel run tensorboard:tensorboard -- --logdir=~/Desktop/mnist-logs
> INFO: Found 1 target...
> INFO: From Vulcanizing /tensorboard.html:
> 2017-08-25 00:36:26.559 WARNING /tf-op-profile/tf-op-details.html-2.js:16: WARNING - Function module$tf_op_profile$utils.flameColor: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
>     var color = flameColor(utilization(node), 0.7);
> …
> Remove build warnings from the profile plugin

- tensorboard/plugins/audio/BUILD
- tensorboard/util_test.py
This is a known issue documented in the release notes. A contrib.ffmpeg
change didn't make it into TF 1.3. This new API for audio summaries
will work if the user installs the nightly pip package for TensorFlow.
> Remove tests relating to ffmpeg change

- tensorboard/components/tensorboard.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
This way we don't have a global HTML tooltip that says "TensorBoard".
> Rename tf-tensorboard title attribute to brand

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
#261 recently removed the expand button from the image dashboard, which freed up whitespace. However the checkbox in the top left isn't conspicuous enough. With this change, clicking on an individual image, will toggle its actual size state, for only that image. This seems intuitive to me.
> Have click toggle actualSize of image

- tensorboard/components/tf_card_heading/BUILD
- tensorboard/components/tf_card_heading/tf-card-heading-style.html
- tensorboard/components/tf_card_heading/tf-card-heading.html
- tensorboard/components/tf_card_heading/util.html
- tensorboard/components/tf_card_heading/util.js
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
This change improves the aesthetics of figure captions. It makes the information seem less crowded, while also freeing up vertical space. The improvement looks the best on the image dashboard.
Before:
After:
> Improve card header UI

- tensorboard/plugins/graph/tf_graph_common/parser.ts
TypeScript 2.4 has more strict type checking around Promises;
the current code fails with:
.../tf-graph-common/parser.ts(192,3): error TS2322: Type 'Promise<Object>' is not assignable to type 'Promise<NodeDef[]>'.
Type 'Object' is not assignable to type 'NodeDef[]'.
The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
Property 'length' is missing in type 'Object'.
This function is declaring that it returns an arbitrary object, which in TypeScript
is written "any".
> fix type annotation for typescript 2.4

- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/parser.ts
- tensorboard/plugins/graph/tf_graph_common/proto.ts
This allows the graph explorer to successfully parse repeated fields.
Without this change, the parser cannot differentiate between a
non-repeated field vs. a repeated field with a single value.
That results in some subtle bugs. For instance, logic might iterate over
the characters of a string instead of across strings.
> Mark certain fields as repeated

- tensorboard/plugins/graph/tf_graph_common/edge.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
In SVG 2, getPathSegAtLength (which the graph explorer depends on as part of
rendering edges), is deprecated. This means that the graph explorer
would render with no edges in Chrome 62 (current in the dev channel) and
would thus be very much broken in Chrome 62.
This commit pre-empts that change by implementing the functionality of
getPathSegAtLength in the graph explorer so that the explorer still
works in Chrome 62.
I do not see alternative ways of implementing this functionality using
the native pathLength property + getTotalLength() and getPointAtLength()
methods still provided by the SVG API.
After this change goes in, we should quickly release a new pypi package
and internal version of TensorBoard so that the graph explorer is not
broken for users of Chrome 62.
Fixes #425. The graph …
> Implement getPathSegAtLength in JavaScript

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/BUILD
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-steps-selector.html
This frontend for the PR curves plugin makes use of the `vz-line-chart` component that had been generalized in #388. Each `tf-pr-curve-card` contains 1 PR curve. The `tf-pr-curve-steps-selector` creates 1 slider per run and lets the user select steps.
This PR is a part of dividing #334 (which contains resourceful input from @wchargin) into smaller PRs.
> Add the frontend for the PR curves plugin

- tensorboard/main.py
This needs to be fine tuned a bit more, in order to ensure it always appears
when being logged to TTYs that aren't proper TTYs.
> Don't ephemeral log server URL for now

- tensorboard/plugins/pr_curve/BUILD
Made the BUILD target for the PR curve summary op visible to other packages. Otherwise, no code outside of TensorBoard can use it.
> Make PR curve summary visible to public

- tensorboard/components/tf_utils/BUILD
- tensorboard/components/tf_utils/tf-utils.html
- tensorboard/components/tf_utils/utils.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
Plugins that render one visualization per tag may need to aggregate
information across multiple runs. This commit generalizes that logic
from the scalar plugin to a `tf-utils` module, so that it can be used in
other similar plugins. This is particularly worthwhile because it
contains some security-sensitive code (HTML sanitization).
Test Plan:
Verified that the current behavior of the scalar dashboard is maintained
in the following cases:
- A tag with a display name.
- A tag with no display name.
- A tag with no selected runs, and so no descriptions.
- A tag with one or multiple selected runs that all have identical
descriptions.
- A tag with differing descriptions.
wchargin-branch: expose-tag-info-aggregation
> Expose the tag-info aggregation logic

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/components/tf_tensorboard/default-plugins.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Previously, logic related to dashboards would reference
TENSORBOARD_PLUGINS, a mapping between plugin name to dashboard element
name. Logic would also use the name of the plugin (the key of that
mapping) as the tab name displayed in TensorBoard.
This is suboptimal for several reasons - the plugin name is not
necessarily optimized for display purposes. For instance, take the
plugin name pr_curves. We would ideally remove the underscore from it.
We thus introduce the concept of `DashboardData`, which encapsulates data on a dashboard - the name of the element for the dashboard component (`elementName`), the name of the associated plugin (`plugin`), and the name to show within the navigation menu (`tabName`).
Renamed the _dashboards array within the tf-tensorboard component to …
> Modify dashboard mapping to take object values

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/BUILD
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
Summary:
Fixes #446.
The UI is the same as the existing UI as seen in the scalar dashboard
(including the existing display bug discussed in #430), but here’s a
screenshot, anyway:
Test Plan:
Load the PR curve dashboard, and ensure that you’re able to replicate
the screenshot above.
wchargin-branch: pr-curve-display-name-description
> Use `displayName` and `description` for PR curves

- tensorboard/plugins/graph/tf_graph_common/render.ts
When calculating the color scale for the compute time, consider all nodes in the graph instead of just the nodes in the top-level graph. 
I have a graph with one single sub-graph, which consumes all the compute time (say X ms), in the top-level graph, so the color scale becomes "X ms -> X ms". 
Not sure about the original intention of the top-level graph; let me know if this is the right fix.
(I don't really know typescript. Please let me know if there is more efficient way to get  the extent of a map :)
> graph] Use 0 as the minimum memory/time in the color scale.

- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
When the threshold is high enough so that the predictor makes no
positive predictions, precision is undefined because its denominator is
fp + tp. Hence, we remove the max operation from the numerator of the
precision calculation, so that precision is 0 (and not 1) when the thresold is 1.
1 might be misleading because that implies there is area under the curve.
Screenshot with this change:
Notice that the curve does not drop from 1 to some tiny value and then
go back up again as recall increases (as before).
A subsequent effort will make the frontend just not show data points for
which fp + tp = 0. For now, we get rid of that max op so that the user
does not see precision as equal to 1e-07, which can be confusing.
Also computed recall simply as
```python
recall = tp / …
```
> Remove max op from numerator of precision

- tensorboard/components/tf_card_heading/tf-card-heading-style.html
- tensorboard/components/tf_card_heading/tf-card-heading.html
In comments within #430, @wchargin proposed that we use flex positioning
to position elements within the header. That seems like a robust idea.
This PR thus uses @wchargin's proposed method to implement @jart's
original, space-efficient design that makes use of both the left and
right sides of headings (if space is available).
Having that idea lingering at the end of a closed PR seemed a bit precipitous, so I just went ahead and implemented.
This PR fixes the layout issues brought up in #430. This change also fixes #421.
> Use flex positioning for card headings

- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
Broken in 68fe0422ad5c344f3cdcab67c3fc38cda64ec4de - I guess a template literal was intended here.
> Fix tf-op-bar in profile plugin.

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
This change encodes the names of runs and tags included within the GET
parameters of URIs for the audio, image, and pr_curve plugins. We pass
those run and tag names into `encodeURIComponent`.
For the audio and image plugins, we simply needed to use
`pluginRunTagRoute` while constructing URLs. `pluginRunTagRoute` calls
`queryEncoder` from `urlPathHelpers`, which in turn calls
`encodeURIComponent`. The pr_curves plugin lacks that luxury because
its URLs contain multiple run GET property-value pairs, and
`pluginRunTagRoute` only supports 1 run argument. The scalars plugin
might seem analogous, but the scalars plugin actually requests data for
each run--tag combination separately.
Fixes #477. I verified that the audio, image, and PR curve plugins WAI.
> Encode run and tag names

- DEVELOPMENT.md
Within DEVELOPMENT.md, we note how TensorBoard at HEAD relies on TF nightly - that seems important to developers and has been the root of various issues such as #431.
> Note how we develop on TF nightly

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
Without this change, the tall legend runs into the content on top of it. The legend is expanded by default.
Screenshots (expanded and closed):
This fixes #396.
> Let the user expand/collapse the graph legend

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
Make it so that when users highlight or select a node that is a call to
a function, the corresponding node within the function library is also
styled. This linking further clarifies that the nodes are related.
> Link function nodes with library

- tensorboard/plugins/projector/vz_projector/data.ts
Previously, the embedding projector would take the norm of vectors of all 0s, resulting in vectors of all NaN values being used as part of PCA calculations. This change adds a guard to prevent that.
Fixes #450.
> Prevent computing unit norm of vectors of 0s

- tensorboard/plugins/projector/vz_projector/data-provider.ts
Previously, when an error occurred while the projector was processing data (creating data sets and vectors, normalizing data points, computing PCA, etc), it would be logged to the console.
This change uses a try ... catch block to make those exceptions appear as errors in the modal.
This change unfortunately hurts performance a bit because Chrome's V8 engine bypasses an optimized path for JS within a try ... catch block. However, so many people have taken issue with the lack of clarity surrounding projector bugs that I deem this change worth it.
> Log exceptions during processing in the modal

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/node.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
We use a striped background to differentiate metanodes that represent functions. This is accomplished via an SVG pattern, which requires no special background image.
We use 3 rects all overlaid atop each other to render the metanode. The first one renders the color (for structure, device, etc). The second one renders the striped pattern (and is semi-transparent). The last one (on top of the other 2) handles mouse events.
> Add stripes to the background of function metanodes

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_common/node.ts
Added a property nodeContextMenuItems to the tf-graph and tf-graph-scene components. This optional property is an array of `contextmenu.ContextMenuItem`s. This property offers an API for developers to extend the context menu by adding custom items, each with a title and a callback.
See `getContextMenu` for an example array:
```ts
let menu = [{
title: (d): string => {
return getIncludeNodeButtonString(node.include);
},
action: (elm, d, i) => {
sceneElement.fire('node-toggle-extract', {name: node.name});
}
}];
```
Screenshot (Here, we add a "Foo" context menu item):
FYI, @caisq
> Add property nodeContextMenuItems to tf-graph

- tensorboard/plugins/graph/tf_graph_common/template.ts
This change makes it so that when the user colors nodes by structure, metanodes are differentiated in color based on function. Previously, functions were assigned an 'unknown' color because there is only 1 instance of a function within the library for each function.
> Color metanodes by function

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-steps-selector.html
This change modifies the tf-pr-curves-steps-selector component so that
sliders update after the list of runs changes. Fixes #496.
> Make sliders update when runs are added

- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/data_compat_test.py
- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/debugger_server_test.py
- tensorboard/plugins/debugger/numerics_alert.py
A proto change will soon make the type of the content field of
PluginData 'bytes' instead of 'string'. This PR pre-empts that
change by using the compat module to convert to bytes or text as
necessary within the debugger plugin.
Without this change, the script could fail because strings must
consist of UTF-8 characters, but bytes fields are not restricted by
that rule.
FYI @caisq 
Ideally, we would also use protos instead of JSON
serialization/deserialization, but can make that change in a
separate PR.
> Use compat to pre-empt how content is now bytes

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
- tensorboard/components/tf_dashboard_common/tf-regex-group.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Summary:
This commit improves the API of the `tf-storage` module, and also
simplifies its internal implementation (hence the negative delta).
There are two API changes:
- It is now possible to have a `polymerProperty` different from the
`key` used in the storage layer.
- Arguments other than the `key` are now accepted in an `options`
object, so that they are effectively named arguments instead of
positional arguments. This is especially useful for the boolean
observer and initializer functions, which used to take two
consecutive boolean parameters: one was the default value, and one
indicated whether to use local storage. (Which was which?)
Internally, each object type’s bindings are now generated and exported
from a single function call. This removes a bunch of boilerplate code
(120 …
> Redesign the `tf-storage` module

- tensorboard/plugins/graph/tf_graph_dashboard/BUILD
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
Introduced a selected_dataset GET parameter for the graph dashboard. The
value of this parameter is the name of the dataset (run) to load. This
parameter lets users send links to other users of the graph dashboard
that load specific datasets. Fixes #306.
When the user changes the dataset in the graph dashboard UI, the URL
parameter correspondingly changes. I tested this behavior out using the
various runs of the scalars demo. The correct dataset loads given the
selected_dataset parameter, and the URL changes when the dataset is
changed in the UI.
For instance, http://localhost:6006/#graphs&selected_dataset=temperature%3At0%3D270%2CtA%3D270%2CkH%3D0.001 makes the dashboard load the correct dataset.
If no dataset with the specified name can be found, we show a dialog
that notifies the user. …
> Introduce the selected_dataset GET parameter

- tensorboard/components/tf_dashboard_common/tf-downloader.html
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
Summary:
This commit replaces uses like `base + "?things"` (when `base` is not
known to not already contain a query component), or that fail to call
`encodeURIComponent` on the `things`, with uses of `addParams`.
I generated this commit by running `git grep '[&?].*='` and
investigating each occurrence. I ignored all occurrences in the graph
and projector plugins, as they have their own mini-ecosystems. I also
ignored the unique occurrence in the profile plugin, because (a) I can’t
test it, and (b) its inputs are hard-coded such that this change
provably would not fix any bugs.
Test Plan:
I verified the behavior of all existing plugins.
wchargin-branch: use-add-params
> Use `addParams` where it would improve code

- tensorboard/components/tf_backend/router.ts
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
Summary:
A long, long time ago, we had one module `backend.ts` that had lots of
functions like `scalarTags()` and `scalar(run, tag)`. While
decentralizing these, I introduced `pluginRunTagRoute` as an immediate
compatibility layer for these functions.
But `pluginRunTagRoute` is not a good long-term solution. There’s no
reason that our backend core should assume the format of plugins’
routes. Plugins that need to extend this—say, with run, tag, and sample
parameters—use
pluginRunTagRoute('foo', '/bar')(tag, run) + '&sample=sample',
which is bizarre because it requires the arguments in heterogeneous
form. Every route can easily just use `pluginRoute` and the `addParams`
function to specify exactly what it needs.
Test Plan:
I verified that all plugins work as intended. …
> Remove `pluginRunTagRoute`

- tensorboard/components/tf_dashboard_common/tf-downloader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
Summary and Test Plan:
Steps to reproduce bug fixed by this commit:
1. Load the scalar sample dataset and enable one run.
2. Check “Show data download links”.
3. Select the run in the dropdown for the first tag, `delta`.
4. _Paste_ into the search box: `temperature/current`. The first view
now represents `temperature/current` instead of `delta`.
5. Right-click the CSV download link, and copy the link location.
Before this commit: The link in the clipboard corresponds to `delta`.
After this commit: It corresponds to `temperature/current`.
Note: `tf-downloader` is never actually used. We can delete it if we
want. (I don’t think it carries its own weight: the implementation in
the scalar chart is cleaner than it would be using `tf-downloader`.) …
> Properly express data dependency in tf-downloader

- tensorboard/plugins/pr_curve/BUILD
- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
This change introduces a `raw_metrics_op` for collecting data for generating PR curves. Fixes #515. See #515 for the motivation behind `raw_metrics_op`.
> Create raw_metrics_op for creating PR curves

- tensorboard/plugins/profile/BUILD
- tensorboard/plugins/profile/profile_demo.op_profile.json
- tensorboard/plugins/profile/profile_demo.py
The data is about the minimal set that exercises all current features (and #484)
For brevity, it omits some "required" stuff we don't currently use, like the byProgramStructure tree, and the raw{Time,Flops} metrics.
@ioeric
> Add demo data for op_profile view

- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
Move TPU profile tf-op-details into the tool controls area on the left.
This is pretty weird, but we're currently extremely wasteful of horizontal space, and adding any more data to the table will break layout on 1200px monitors. This column is exactly the width we need, and basically empty.
It looks like this:
> Move TPU profile tf-op-details into the tool controls area on the left

- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
Show TPU utilization% in a new column.
That column also shows the utilization color, and the time bar is now uniformly blue. This should reduce confusion about the two metrics that bar used to display.
Switched the rows to flexbox in order to get the layout right. (Unfortunately it can't be an actual table or display:table, due to the HTML nesting structure induced by polymer)
> Show TPU utilization% in a new column

- tensorboard/plugins/pr_curve/metadata.py
- tensorboard/plugins/pr_curve/pr_curves_plugin.py
- tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
We make the PR curves plugin backend serve more information so that PR curves can later display them in tooltips. Specifically, the backend's /pr_curves route now additionally serves the counts of true positives, false positives, true negatives, and false negatives. The backend also serves the thresholds for a PR curve.
This additional information helps users gain visibility into the precision and recall values. For instance, they might wonder about #444.
The thresholds are actually the same for each run--tag combination (and do not change per step), so we could actually serve them through another endpoint that is requested once per TensorBoard refresh. However, serving the thresholds via the /pr_curves route does make the frontend design more straightforward because we do not have …
> Make PR curves backend serve more information

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
This change makes use of the additional data (added in #462) served by the PR curve plugin by displaying the added fields within the tooltip for PR curves.
Screenshot:
This fixes #463 and should only be submitted after #462 is merged.
> Modify the card for PR curve summaries to show more info

- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Before this change, tf-scalar-chart.html contains much logic specific to
the scalars plugin. We extract that scalars-specific logic into a new
component called tf-scalar-card. Some of the logic extracted includes
properties that allow for setting X and Y axes, the buttons under the
chart, and the callback that is run when data is received from the
server.
This change is a step towards allowing any plugin to make use of the
tf-scalar-chart component (albeit a subsequent change will move and
rename this component to clarify that it is generally applicable). That
goal is desirable because tf-scalar-chart contains a lot of fixes that
correct for bugs in the vz-line-chart component and Plottable. Those fixes
include #163, #189, and #204. 
Screenshot (The scalars dashboard WAI):
> Generalize tf-scalar-chart.html

- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
This is designed to show how well your data fits the TPU. It looks like this:
The new data is described in a change to `tensorflow/contrib/tpu/profiler/op_profile.proto` that hasn't made it to github yet. This is what's added to XLA instruction info:
// Describes the physical memory layout of the instruction's primary input.
// e.g. for a convolution, this analyzes the image and ignores the kernel.
LayoutAnalysis layout = 5;
message LayoutAnalysis {
// The physical data layout, from most-minor to most-major dimensions.
repeated Dimension dimensions = 1;
message Dimension {
int32 size = 1;       // Size of the data in this dimension.
int32 alignment = 2;  // Data must be padded to a multiple of alignment.
string semantics = 3;  // What the dimension represents, e.g. "spatial".
}
}
> Show layout analysis for convolution ops

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
The scalars dashboard had been broken by #470 because the buttons had not been moved out of the tf-scalar-chart container:
Furthermore, the tf-card-heading now must be block-positioned for the margin to take effect. The scalars dashboard now WAI. The buttons work, and download links work.
> Fix buttons for the scalars dashboard.

- tensorboard/components/tf_card_heading/tf-card-heading.html
Summary:
In the case where a run label appears on the same line as the tag name
(i.e., is not wrapped to the next line), the label is too tall. This is
because the label was a direct flex item and so was being blockified.
It should have been a `<span>`, and it also needs to be wrapped in a
second `<span>` to avoid blockification.
Before:
After:
Test Plan:
Load a dataset with both short tag names and long tag names, so that
some of the run labels are wrapped while others are not. (The standard
histogram demo suffices.) Ensure that the height of each run label is
the same.
wchargin-branch: fix-run-label-height
> Fix dimensions of card heading’s colored run label

- tensorboard/plugins/pr_curve/pr_curves_plugin.py
Summary:
The PR curve data route was returning numpy arrays, which are not
JSON-serializable. This caused `/data/plugin/pr_curves/pr_curves`
requests to fail with status 500, which in turn caused the PR curve
dashboard to not display any data.
Test Plan:
Load the PR curve dashboard with some demo data. Before this patch,
you’ll see only perpetual loading spinners, plus some console failures
indicating the status-500 request. After this patch, the PR curves will
load and there won’t be any console failures.
wchargin-branch: fix-pr-curve-serialization
> Fix the PR curve plugin backend JSON serialization

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
Previously, when the user performs some functionality to expand the
graph and then select a node (such as navigating to a node after
observing TPU compatibility or clicking an op in the debugger plugin),
the graph would select a node before expanding its parent nodes.
This can cause an error because the selected node is not yet present in
the graph hierarchy:
```
(index):7546 Uncaught (in promise) TypeError: Cannot read property
'node' of undefined
at HTMLElement._updateNodeState ((index):7546)
at HTMLElement._selectedNodeChanged ((index):7547)
```
This change makes the scene only stylize the selected node
after expansion of necessary nodes finishes. I don't think I can repro
the issue after this change.
FYI, @caisq
> Stylize the newly selected node after expansion

- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
Previously, when the data provider changed, a new projector config might not load because the name of the new run (string) could stay the same - indeed the name of the run is always 'proto'.
This change makes it so that we load a new projector config and correspondingly update the UI when the data provider changes (even if the run name changes).
Fixes #478. This commit is coauthored by @svsgoogle and @chihuahua.
> Load new projector config when dataset changes

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-steps-selector.html
The PR curves dashboard used to show a slider for each selected run.
A dysfunctional slider is still shown even if a run lacks PR curve data.
That dysfunctional slider also causes a console error.
This change makes it so that only sliders for selected runs with PR
curve data are rendered.
The alternative of using a `dom-if` within the `dom-repeat` that guards
whether there is data for a run does not work - the sliders in those cases
render after `updateSliders` is called.
Test plan:
Create a logdir containing some runs with PR curve data and some without. For instance, first run the PR curves demo, then run the scalars demo ... then move subdirectories generated by the scalars demo into the PR curves demo directory. Load the PR curves dashboard. Toggle some runs. Try 10 times
to check for …
> Only show sliders for runs with steps

- tensorboard/plugins/text/BUILD
- tensorboard/plugins/text/metadata.py
- tensorboard/plugins/text/plugin_data.proto
- tensorboard/plugins/text/summary.py
- tensorboard/plugins/text/summary_test.py
- tensorboard/plugins/text/text_plugin.py
Fixes #481. As part of this effort, introduced a metadata.py file for
text plugin which currently provides the name of the plugin as well as
some functionality for creating and parsing (currently unused)
TextPluginData protos.
Looping in @dandelionmane as the plugin author. :)
> Write op and pb methods for text summaries

- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
This change adds an icon beneath each PR curve that lets the user reset
the ranges of the chart axes. The icon mirrors that under scalar charts.
Test plan: Run the PR curves demo. Start TensorBoard. Zoom in to a
PR curve, and click the icon.
This change should merge only after https://github.com/tensorflow/tensorboard/pull/541 is merged.
> Add icon for resetting PR curves

- tensorboard/plugins/pr_curve/summary_test.py
A FileWriter within the summary_test for the PR curves plugin had
previously been unclosed before the multiplexer read from it, which
potentially could have been causing flaky behavior.
> Close the FileWriter in summary_test

- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
Beforehand, the `vz-line-chart` component would set reasonable X and Y
ranges for all plots. This was problematic because as the user slides
across steps in the PR curves dashboard, the Y axis would change,
leading to difficulty in comparing across steps.
This change adds `defaultXRange` and `defaultYRange` properties to
`vz-line-chart` so that dashboards can manually set default ranges for
the X and Y axes if the need arises. It also makes PR curves start out
with those default ranges.
Test plan:
Run the PR curves demo, and start TensorBoard. Note that all PR curves
exhibit the new X and Y ranges. Also, run the scalars demo, and start
TensorBoard. Note that it loads and behaves as expected.
Before:
After:
> Fix X and Y ranges of PR curves to [-0.05, 1.05]

- tensorboard/components/tf_paginated_view/BUILD
- tensorboard/components/tf_paginated_view/paginatedViewStore.ts
- tensorboard/components/tf_paginated_view/tf-paginated-view-store.html
- tensorboard/components/tf_paginated_view/tf-paginated-view.html
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
In accordance with #483, this patch adds a configuration option to allow
changing the number of visualizations per page to a value other than 12.
Closes #483.
Test Plan:
Load the histogram dashboard with the histogram demo, which has seven
visualizations. Open the settings menu, and note that the default
pagination limit value is 12. Change the value to 1, close the dialog,
and move to page 6. Then, reopen the dialog and change the pagination
limit to 2; note that you are now on page 3 of 4. (This tests that the
existing-but-never-before-used behavior of `tf-pagination-view` that
attempts to retain approximately the same view across pagination limit
changes still works.)
Try to change the value to 0 or a negative value; note that this fails
without any console errors. …
> Allow configuring pagination limit in settings

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Previously, the text atop image loaders (displaying step and wall time)
would only depend on the step index. This was problematic because during
reloads, the array of steps changes, but the number of sampled steps
remains the same, so the text above individual images would not update.
Fixes #550.
Test plan: Run mnist_with_summaries.py:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
Start TensorBoard pointed at
/tmp/tensorflow/mnist/logs/mnist_with_summaries, and navigate to the
image dashboard. Notice that the step updates now when TensorBoard
reloads, both during the periodic reload and during manually triggered
reloads.
> Make step text depend on steps array

- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
This change makes it so that the info card lists where a function is
called when the highlighted node represents a library function. Clicking
on one of the function calls makes the graph select the node that
represents the call.
This change involves introducing a new data container
`LibraryFunctionData` that encapsulates the name of a function as well
as instances in which the function is called.
Test plan:
1. Create a log directory containing the attached events file. The only reason that the binary file ends in txt is because GitHub forbids users from uploading binary files.
2. Start TensorBoard pointed at it.
3. Click on a node representing a library function.
4. Click on one of the node list items representing the function call. The graph should select it. …
> Make info card list usages of a function

- tensorboard/plugins/audio/BUILD
This broke the internal CI by taking longer than sixty seconds.
A test that spawns subprocesses also probably can't be called
small, according to the go/testsizes definitions.
> Define audio/summary_test as medium size

- tensorboard/components/analytics.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- third_party/typings.bzl
Added a tf-logging component that contains a logEvent function. This function takes an Analytics event and logs it if Analytics is enabled (as detected by whether the global 'ga' object is defined). Used that method to log dashboard selection.
The vz-projector-app is for now unaffected because that app is a standalone app not used within TensorBoard.
Fixes #524.
Test Plan:
1. Start TensorBoard externally. Note the requests in the Network tab - none are triggered by the `logEvent` method. Also `console.log`ging shows that the `logEvent` method is not called.
2. Start TensorBoard within Google. Note that requests are issued, and `console.log`ing reveals that `logEvent` is called. I think we'll have to wait a few days for the events to show up in the Analytics UI. We can iterate then if we …
> Log dashboard selection if Analytics is enabled

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
Per internal feedback, 'metric op' has a specific meaning:
https://www.tensorflow.org/versions/r0.12/api_docs/python/contrib.metrics/metric_ops
and the op is not a metric op. This renaming avoids confusion.
> Rename raw_metrics_op to raw_data_op

- tensorboard/components/tf_line_chart_data_loader/BUILD
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Also moved that component into the components directory. Modified the scalars dashboard to use `tf-line-chart-data-loader`.
At a higher level, the scalars dashboard had been reloading the `tf-scalar-chart` component, which was unexpected - this change sets it to reload `tf-scalar-card` components.
The scalars dashboard WAI.
A subsequent change will make the PR curves component use `tf-line-chart-data-loader`.
> Rename tf-scalar-chart to tf-line-chart-data-loader

- tensorboard/BUILD
- tensorboard/pip_package/BUILD
- tensorboard/summary.py
- tensorboard/summary_test.py
Summary:
Resolves #561.
Test Plan:
Ran the `build_pip_package.sh` script to build the Python 2 package,
then created a new Python 2 virtualenv in which I installed only the
latest nightly TensorFlow release (2017-09-22) and the generated wheel.
Then wrote
```py
import tensorflow as tf
from tensorboard import summary
result = tf.Session().run(summary.scalar('shelby', tf.constant(3)))
s = tf.Summary()
s.ParseFromString(result)
print(s)
```
and verified that the result was a proper scalar summary.
I then repeated the process using `pip install tensorflow==1.3.0`
instead of the nightly version to ensure that the module works for
normal TensorFlow users. (Note: the audio summary will not work because
TensorFlow 1.3 lacks 22730fd4c633a74e59c03ff76dc92e6ae2d5d020. This is
fine; users can …
> Add the `tensorboard.summary` public entry point

- tensorboard/plugins/graph/tf_graph_common/render.ts
Previously, if the output for a function was the input into an op within a metanode, the graph explorer would fail to visualize the graph and produce an error upon rendering the hierarchy for the metanode:
Uncaught TypeError: Cannot read property 'inputs' of undefined
This PR takes 2 actions to fix that.
1. We scan the base edges of the destination op, which have to have OpNodes as destinations (instead of scanning the inputs of the destination op, which could be MetaNodes).
2. If a node at the current hierarchy has an input that is within a function call, we render the hierarchy of the function call's parent so that edges are generated correctly (because the source nodes are now available).
Test plan:
Load the attached pbtxt file into the graph explorer. Beforehand, the error would …
> Make graph explorer work for functions that output to metanodes

- .travis.yml
- WORKSPACE
- tensorboard/plugins/text/summary_test.py
- third_party/workspace.bzl
> Make TensorBoard work with latest Bazel

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/LICENSE
- tensorboard/pip_package/MANIFEST.in
- tensorboard/pip_package/README.rst
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/setup.cfg
- tensorboard/pip_package/setup.py
- Include LICENSE in metadata (Fixes #556)
- Add mini README file in Restructured Text
- Stop copying deps (e.g. six) into our whl file
The LICENSE file was copied into this directory in the interest of avoiding
adding a BUILD file to the top level directory.
> Make pip package more prim and proper

- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
This change adds a `handleNodeSelected` property to the `tf-graph` and
`tf-graph-board` components. This property is a function that is called
every time the selected node changes (a new node is selected or the
current node is unselected).
This change is part of an effort to make the graph explorer
generalizable to various use cases.
Test plan: Modify the graph dashboard to pass a `handleNodeSelected`
callback to the `tf-graph-board` that console.logs selected nodes. After
starting TensorBoard, note that both node selection and deselection are
logged correctly.
> Add handleNodeSelected property to tf-graph

- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
Library functions are not part of the TensorFlow graph - they serve as templates for creating other ops. The graph explorer should thus not allow library functions to be extracted.
This change hides the 'Add/remove to/from the main graph' button from the info card when a library function is selected.
This relates to fixing #574.
Test plan: Start TensorBoard pointed at the attached events file. Note that the button for adding/removing a node is hidden if the node is a library function. Also not that the button still appears for other ops in the graph.
[events.out.tfevents.functions.txt](https://github.com/tensorflow/tensorboard/files/1339011/events.out.tfevents.functions.txt)
> Remove add/remove button for library function nodes

- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
Previously, when a user selected a node that represents a function, the list of function usages in the info card might not update. In response, this change
1. makes the info card asynchronously update that iron-list when the list of function usages changes. The logic for asynchronously updating node list items is now moved into a helper method also used by the logic for rendering lists of inputs and outputs.
2. makes `_functionUsages` depend on `_node` instead of `nodeName` like the other lists of nodes do. This prevents duplicating a little code and also ensure that `_resetState` is called when `_functionUsages` updates.
3. Renamed the 3 methods that obtain lists of nodes (`_getSuccessors`, `_getPredecessors`, and `_getFunctionUsages`) to be consistent. Moved them closer together so that …
> Ensure that the list of function usages updates

- tensorboard/plugins/graph/tf_graph_common/render.ts
Previously, the graph explorer would iterate through all nodes and deem nodes that lack any inputs or outputs to be in or out extracts. Library functions are isolated nodes within a special scene group, so they got lumped into the in and out extracts. This change adds a guard to prevent that.
Test Plan: Start TensorBoard with the attached events file. Add the init op to the main graph. Note that the library functions are no longer replicated, which had been a bug.
Fixes #574. The library functions are no longer extracted into auxiliary when a node such as init is added or removed:
[events.out.tfevents.functions.txt](https://github.com/tensorflow/tensorboard/files/1338982/events.out.tfevents.functions.txt)
> Prevent library functions from being in/out extracted

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/node.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
Previously, the graph explorer had made functions stand out via giving
them a hatched background. However, functions are intended to seamlessly
integrate into the graph, so we remove the hatch. @wchargin brought up some
compelling points:
* The nodes are extremely hard to read. To quote from pgfmanual (3.0.1a,
95): Do not use background patterns, like a crosshatch or diagonal
lines, instead of colors. They distract. Background patterns in
information graphics are _evil_.
* We already have a "Usages of the Function" section within the info
card that shows up when either a function template or one of its calls
is selected. This suffices to identify the node as being associated with
a function.
* We already have triangles within function nodes that uniquely identify
function input and output …
> Remove the hatched background from functions

- tensorboard/main.py
These errors aren't very helpful and they tend to fill up logs. They could be
caused by something as innocent as `curl -N http://localhost:6006/ | head`. It
could also be caused by firewalls, or perhaps the browser abruptly navigating
somewhere else. So we wouldn't want users to mistake these as meaningful when
troubleshooting.
> Make EPIPE tracebacks go away

- tensorboard/main.py
- tensorboard/pip_package/BUILD
- tensorboard/pip_package/LICENSE
- tensorboard/pip_package/MANIFEST.in
- tensorboard/pip_package/README.rst
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/setup.cfg
- tensorboard/pip_package/setup.py
- tensorboard/version.py
This is a patch release to polish the pip package. It's now smaller and has better metadata.
cc: @jakirkham from #556
cc: @alanpurple from #588
> Cherry picks for TensorBoard 0.1.8

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
- tensorboard/summary.py
This op produces the same result (a Tensor Summary containing the PR
curve data) as the existing op() function, but it does so by
aggregating the result over multiple batches of data.  The function
also returns an update_op that should be used to update the summary
for each batch of data.
With these changes, the function provides a tf.metrics-like function
for generating PR curve data.
> Add a streaming_op() to the pr_curves plugin.

- tensorboard/BUILD
- tensorboard/main.py
The import also becomes conditional, which should get rid of
ImportErrors related to futures and grpcio when the user
hasn't explicitly specified the --debugger_data_server_grpc_port
flag.
> Make addition of Debugger Plugin conditional on FLAG

- tensorboard/plugins/debugger/debugger_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager_test.py
We skip `debugger_plugin_test` and `events_writer_manager_test` if importing debugger_plugin fails.
#606 had fixed `application_test`. This PR fixes tests specific to the debugger plugin.
> Skip debugger-related tests if import fails

- tensorboard/pip_package/setup.py
This reverts commit 46c153f993b126f0ba9e599229ecfee440c8393c and unfixes #588. A regression was caused where the following happens:
```
(tf)html5lib-rollback jart@compy:~/code/tensorboard$ tensorboard --logdir=~/tb/fast
File "/usr/local/google/home/jart/tf/bin/tensorboard", line 7, in <module>
from tensorboard.main import main
File "/usr/local/google/home/jart/tf/local/lib/python2.7/site-packages/tensorboard/main.py", line 36, in <module>
from tensorboard.plugins.audio import audio_plugin
File "/usr/local/google/home/jart/tf/local/lib/python2.7/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in <module>
from tensorboard import plugin_util
File "/usr/local/google/home/jart/tf/local/lib/python2.7/site-packages/tensorboard/plugin_util.py", …
```
> Revert "Update required version of html5lib to 1.0b10 (#589)"

- tensorboard/plugins/debugger/debugger_plugin_test.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager_test.py
Overriding the setUp() method without calling super caused the test to fail
when it isn't being skipped.
> Simplify debugger_plugin_testlib test skipping

- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_common/edge.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
This change adds a `edgeWidthFunction` property to tf-graph and
tf-graph-board. This is a method that a user can specify to compute the
thickenss (in pixels) of individual edges in the graph. If specified,
edge thickness is no longer based on tensor size but rather on
`edgeWidthFunction`.
Renamed `EDGE_WIDTH_SCALE` to
`EDGE_WIDTH_SIZE_BASED_SCALE` in order to clarify that the
scale is relevant to default behavior.
This change is part of making the graph generalizable to other
applications.
Test plan: Make `tf-graph-dashboard` pass some arbitrary
`edgeWidthFunction` to `tf-graph-board` such as this one.
```ts
_edgeWidthFunction: {
type: Object,
value: () => {
return (edgeData, edgeClass) => {
if (edgeClass.indexOf('edgeline') == -1) {
// Other edges such as annotation edges continue to …
```
> Add property edgeWidthFunction to tf-graph

- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_common/edge.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
This new property lets users override the default graph behavior of
labelling edges based on tensor size.
Test plan: Make `tf-graph-dashboard` use a custom edge label function
such as this one.
```ts
_edgeLabelFunction: {
type: Object,
value: () => ((metaedge, renderInfo) => {
if (metaedge.baseEdgeList.length > 1) {
return 'multiedge';
}
const baseEdge = metaedge.baseEdgeList[0];
console.log(baseEdge, renderInfo);
return 'edge from ' + baseEdge.w + ' to ' + baseEdge.v;
}),
readOnly: true,
},
```
Note that it is reflected within the graph.
> Add property edgeLabelFunction to tf-graph

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph/tf-graph.html
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_common/edge.ts
- tensorboard/plugins/graph/tf_graph_common/scene.ts
Added a new property to `tf-graph` and `tf-graph-board` called
`handleEdgeSelected`. If this property is set, the user can select edges
by clicking on them. That same property is a callback run when an edge
is selected, allowing developers to handle edge selection.
Stylized selected edges so that they are red.
This change is part of an effort to generalize the graph explorer. The info
card does not respond yet, but that is fine because I believe developers
who use this new API functionality can handle edge selection.
Test Plan: Pass a handleSelectedEdge property from `tf-graph-dashboard`
to `tf-graph-board`. Load a graph such as via the attached events file.
Note that edges are now selectable and turn red upon selection. Clicking
on the graph deselects edges.
Also, try removing the …
> Let user select edges if handleEdgeSelected set

- tensorboard/main.py
- tensorboard/pip_package/setup.py
- third_party/workspace.bzl
grpcio is now an optional dependency, thanks to 939fcb3e6c998e0444fee162048b79232dc999a0.
NumPy and Protobuf were updated to be the same as what's in TensorFlow's setup.py file at HEAD.
Once this change is merged, I'll cut a 0.4 branch off HEAD and publish TensorBoard 0.4.0-rc1 in preparation for TensorFlow 1.4-rc1 which is expected in the next few days.
> Update pip dependencies in preparation for 0.4

- tensorboard/main.py
- Order of magnitude reduction in TCP sockets and Python threads
- Small improvement on overall page loading time
> Use HTTP/1.1

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Tweak to make the images plugin step counts more readable when they exceed 1000.
Before:
After:
> Format image-loader step counts with commas

- tensorboard/plugins/scalar/scalars_plugin.py
This change makes the `is_active` method of the scalars plugin
short-circuit if it discovers that any run has at least 1 relevant tag.
This change preserves existing behavior, so there are no changes to
tests (which check for the preservation of behavior).
Test plan: Start TensorBoard pointed at the scalars demo data. Note that
the scalars plugin loads. Start TensorBoard pointed at the PR curves
demo data. The scalars plugin is inactive.
Use `time.time()` to log the time it takes for some internal events file
(with over 30K tags in one specific run) with and without this change.
With this change, the is_active method takes 0.0s to complete. Without this
change, it takes 12.0s. Sometimes, the frontend won't load because
`is_active` takes too long to respond.
Granted, one might reason that …
> Make scalars is_active short circuit if apt

- tensorboard/BUILD
- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/default.py
- tensorboard/main.py
- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/core/index.html
- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/pr_curve/BUILD
- tensorboard/program.py
This change will make it easier to write plugins with custom builds of
TensorBoard. The plugin author will no longer be required to explicitly list
all the first-party plugins, as they can now be inherited via the
`tensorboard.default` module.
The `tensorboard.program` module has also been introduced. This module gives a
permanent home to all the APIs that crept into `tensorboard.main` over the
years. After this change, the `tensorboard.main` module is nothing more than
glue between the `program` and `default` modules.
The special-case code in main.py that the debugger plugin was using, has now
been relocated into the debugger plugin's directory.
This change is backwards-compatible. Delegates have been added for relocated
functions that will log a deprecation warning if used.
This change, …
> Tidy up the tensorboard.main API

- DEVELOPMENT.md
This clarifies some things that I encountered - in particular, it specifies that you'll probably want TensorFlow installed in a virtualenv, and it updates the advice about getting the nightly build now that tf-nightly is on pypi (https://pypi.python.org/pypi/tf-nightly).  It also links to Bazel installation instructions just for the sake of being explicit.
> Clarify DEVELOPMENT.md from a new dev perspective

- tensorboard/plugins/graph/tf_graph_common/render.ts
Previously, the graph explorer attempted to extract a label from a
string to use as the display name for a node representing a function.
Apparently, that regex does not always match a function. Certain graphs
found within Google directly use the entire string as the name of the
function. That caused the graph explorer to be blank due to an error.
This change makes it so that we just use the entire string as the
display name if no display name can be extracted from the string.
Test Plan: Start TensorBoard pointed at the attached events file. The
graph loads correctly as before. Also load the newly discovered internal
pbtxt. It also loads successfully.
[events.out.tfevents.1506397086.functions.txt](https://github.com/tensorflow/tensorboard/files/1357970/events.out.tfevents.1506397086.functio …
> Use entire string as node label if no match

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
PR #626 had added default properties to `vz-line-chart`, and so we no
longer have to specify them in `tf-scalar-card`.
Specifically, we remove `yValueAccessor` and `tooltipColumns` but keep
the binding for `xComponentsCreationMethod`. We keep the latter to let
the user change the value on the horizontal axis.
Test Plan: Note that TensorBoard WAI on scalars demo data. Changing
horizontal axis (to wall time or relative) still works.
> Remove properties from tf-scalar-card

- tensorboard/version.py
This PR starts the TensorBoard 0.4 minor series, which maps to TensorFlow 1.4.
The `0.4` branch has been cut from `HEAD` today for this series. The true name of this release will be `0.4.0-rc1`, to conform to semver. However, in `tensorboard.version` and on PyPi it will be known as `0.4.0rc1` to conform to PEP 440. @gunan has informed me there are benefits to semver conformance, as we introduce more languages into the repository.
As soon as this change is merged, this release candidate will be published to PyPi. I've confirmed that `pip install tensorflow-tensorboard` will *not* choose by default to install an RC.
Then, I will send a PR to TensorFlow updating their setup.py to say `tensorflow-tensorboard >= 0.4.0rc1, < 0.5.0`, so they can create their release candidate. I'm confident this …
> Create TensorBoard 0.4.0-rc1

- tensorboard/plugins/graph/tf_graph_common/node.ts
Previously, triangles within function nodes that represented inputs and outputs ops had relied on the wrong width and height, resulting in stretched triangles.
Now, the triangles use the dimensions of their core box, as was already the case with ellipses representing normal ops.
Test Plan: Load the attached events file and view the graph dashboard. Confirm the behavior above after expanding the `MnistForward` function.
[events.out.tfevents.functions.txt](https://github.com/tensorflow/tensorboard/files/1358841/events.out.tfevents.functions.txt)
> Use corebox dimensions to render triangles

- tensorboard/plugins/pr_curve/summary.py
Set the default number of thresholds used by PR curve summary calculations to 201 instead of 200. 200 yielded strange, unfriendly bin edges. The number of bins is 1 less than the number of thresholds. Hence, it usually makes more sense for the number of thresholds to be odd.
This is a request from Waymo folks.
> Set _DEFAULT_NUM_THRESHOLDS to 201

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
PR curve summaries had used 1.0 as the minimum division value while computing precision and recall.
That actually does not work because certain weights can cause TP, FP, TN, and FN values to be below 1.0.
This change sets that minimum to 1e-7 and adds a test.
> Lower _MINIMUM_COUNT to 1e-7

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
- tensorboard/summary.py
This method lets users generate PR curve summaries from raw TP, FP, TN, FN, precision, recall values without the use of TensorFlow.
Added `pr_curve_raw_data_pb` to TensorBoard's main summary module. Renamed `pr_curve_raw_data` to `pr_curve_raw_data_op` to be parallel.
> Introduce a raw_data_pb method for PR curve summaries

- tensorboard/program.py
Changes "todisable" -> "to disable".
```
--host HOST           What host to listen to. Defaults to serving on all
interfaces, set to 127.0.0.1 (localhost) todisable
remote access (also quiets security warnings).
```
My OCD needs this to be fixed, sorry :)
> Adds space to `--host` argument description.

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/base_plugin.py
Specifically, we add a `plugin_name_to_instance` dictionary property to
the context magic container passed to all plugins during construction.
Fixes #658.
> Add a mapping from plugin name to instance

- tensorboard/backend/application.py
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
This is a preliminary step in addressing tensorflow/tensorboard#625 that just adds logging (at INFO) for the amount of time taken by the is_active() call for each plugin loaded by TensorBoard when the plugins listing endpoint is invoked.  This way as we make fixes we can monitor for regressions, and it also can help isolate the problematic plugin if we get reports from users that TensorBoard is taking a long time to respond with the list of active plugins (which is a prerequisite for basically any other usage of TensorBoard).
I also bundled in a couple small tweaks to other logging lines that can help diagnose slow plugin behavior.
> Log time taken by is_active() calls for plugin listing

- WORKSPACE
- third_party/js.bzl
- third_party/polymer.bzl
- third_party/python.bzl
- third_party/typings.bzl
- third_party/workspace.bzl
Update "mirror.bazel.build" urls to use https. (All traffic to `*.bazel.*` is now routed through https, so those http requests currently cause a redirect. This removes the redirect.)
> Use https for mirror.bazel.build

- tensorboard/components/tensorboard.html
Please note we currently only use Google Analytics internally. We changed the
code to use async loading, so it makes more sense to have it happen earlier on
the page.
> Move up analytics tag

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
This PR fixes some duplication issues in pageview counting for Google Analytics.  Note that currently analytics is only enabled for internal Google users.
Specifically, sending pageview hits from _updateSelectedDashboard() was not really correct because that Polymer observer is invoked on any change to either observed property - the selected dashboard or the list of active dashboards.  That means that as the active dashboards are loaded, every change to _activeDashboards will result in a duplicate page hit being logged for the currently selected dashboard.
As a special case of this, observers are also invoked a single time once their default values are all initialized to handle the default values (as a new change from "undefined").  So this also meant that on every page load we would send …
> Fix pageview hit counting to avoid dupes

- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
Addresses tensorflow/tensorboard#625 by changing TextPlugin to avoid blocking its `is_active()` method on reading from the filesystem.  Note that "reading from the filesystem" is not only reading once, but reading in all plugin assets from all runs, which could be dozens of reads per run, potentially over the network if using a remote filesystem.  In my testing this could easily cause `is_active()` to take 30+ seconds that kind of scenario, which in turn blocks the `/plugins_listing` response for the whole of TensorBoard.
Since the TextPlugin's `is_active()` is based on its `index_impl()` (which backs its `/tags` route) and the expensive filesystem-checking logic is shared, this change puts the entirety of `index_impl()` on a background thread.  This way the `/tags` route can also benefit …
> Change TextPlugin to compute index_impl() asynchronously

- tensorboard/pip_package/setup.py
The `futures` package is a backport of python3's `concurrent.futures` package. The former does not exist for python3.
This would fix #650.
> Do not install futures for python3

- tensorboard/pip_package/setup.py
Previously, we had used `sys.version_info.major` to determine the
python version within setup.py and the conditionally installed
certain modules.
We now directly state those conditions while declaring required
packages. This solution is more robust. See discussion in #667.
We also now only install the `futures` package if the python
version is less than 3.2 (not just 3).
> Declare required packages that vary by python version

- tensorboard/plugin_util.py
- tensorboard/plugin_util_test.py
- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
This fixes tensorflow/tensorboard#647 in which TextPlugin incorrectly decodes scalar string values as their raw numpy byte representation before passing them to `markdown_to_safe_html()`.  When running python 2 this happens to work because numpy and Python use the same raw byte representation for string data, but in python 3 this is not the case, and the result is a string with spurious null bytes, leading the markdown processor to interpret certain patterns incorrectly.  See the issue for details.
This both fixes the TextPlugin decoding logic itself, and also fixes `markdown_to_safe_html()` so that it will discard null bytes and log a warning about them before doing markdown interpretation.
Tested under python 2 and 3 via `bazel test --python_path=...`.
> Fix TextPlugin scalar string decoding errors in py3

- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
When there are more than 2 runs, the FLOPS utilization column doesn't update. 
The column for the second run stays the same with the first run. Similarly, the horizontal distribution bar is also not updated. 
This diff resolves the data binding issue and fixes the bug.
> Fix the bug that Op Profile tool doesn't update to multiple runs.

- .travis.yml
- tensorboard/pip_package/setup.py
- third_party/workspace.bzl
The previous version was very old (3.0.0), which may caused the
following error to occur when the --debugger_data_server_grpc_port
flag is used when launching the tensorboard binary from bazel run.
The version was also inconsistent with the protobuf dependency
version specified in pip_package/setup.py.
This change fixes those inconsistencies.
It also makes the protobuf version consistent with tensorboard.
Also in this change:
* Update grpcio version used by Travis CI.
> Upgrade protobuf version in workspace.bzl and setup.py

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
This change adds an optional `fillArea` property to
`vz-line-chart` and `tf-line-chart-data-loader`. This property takes on
a `FillArea` object. If provided, line charts visualize fill areas for
each data series. See screenshot.
A developer is making a plugin to address #545 and would like this
feature within line charts.
Test Plan: Add a `_fillArea` property to `tf-scalar-dashboard` that
contains some stock accessors, like these ones that generate random
bounds:
```ts
// Specify a fill area by setting accessors for its bounds.
fillArea: {
type: Object,
readOnly: true,
value: {
lowerAccessor: d => d.scalar + Math.random() * 0.05 + 0.03,
higherAccessor: d => d.scalar - Math.random() * 0.05 - 0.03,
},
},
```
Pass the property into `tf-line-chart-data-loader`. Line charts should
visualize …
> Add optional fillArea prop to vz-line-chart

- tensorboard/components/vz_line_chart/vz-line-chart.ts
This takes the existing smoothing algorithm, and updates it to avoid getting biased on the initial value. Addresses #610. At low smoothing values, the difference is small, but as smoothing approaches 1, the difference becomes clearer. At smoothing=1, the old code draws a straight line at data[0] - this code draws a straight line at 0 instead, just because of how the initialization changes. 
Below are several pictures of the same curves with different smoothing values. The first image (teal curve) is before the change, and the second image (orange curve) is after the change.
Smoothing=0.0
Smoothing=0.1
Smoothing=0.6
Smoothing=0.9
Smoothing=0.999
Smoothing=1
> Debiasing for Tensorboard smoothing

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
Some plugins (such as the `custom-scalar` and `debugger` plugins) make use of the `vz_line_chart` component but plot data series that are not runs (such as custom run-tag combos or tensor values).
This change makes the `tf-line-chart-data-loader` component accept a data series property that defaults to the list of runs.
Test plan: Note that the custom scalars plugin works (allows for custom run-tag combos within `vz_line_chart`) after this change: #664 
I plan to rebase #664 after this change goes in. Furthermore, it seems like the scalars dashboard still WAI.
FYI, @caisq
> Allow for data series that are not runs

- tensorboard/plugin_util.py
- tensorboard/plugin_util_test.py
Instead of logging, it will now insert an HTML comment warning about the null bytes being stripped, per suggestion from @000drax.
> Change markdown_to_safe_html() to avoid tf.logging dep

- WORKSPACE
- third_party/js.bzl
Three's now string enums and better support for generic types.
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-25
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-24
See also cl/174189632
> Upgrade TypeScript v2.3.1 -> v2.5.3

- tensorboard/components/tf_card_heading/tf-card-heading.html
- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- tensorboard/components/tf_dashboard_common/tf-option-selector.html
- tensorboard/components/tf_option_selector/tf-option-selector.html
- tensorboard/components/tf_paginated_view/tf-paginated-view.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
*Imported from cl/174107529 and cl/174588409*
The `<content>` element is deprecated, part of the Shadow DOM v0 API which has
been supplanted by Shadow DOM v1's `<slot>` element. For very simple uses – like
those in this CL – this change should be safe and will not require changes to
the usage sites of your element. Therefor, these changes are
backwards-compatible with Polymer 1.0 applications.
As `<content>` is the more powerful API, Polymer 1.0 supports both `<content>` and
`<slot>` by converting `<slot>` back into `<content>` at runtime. Polymer 2.0 only
supports `<slot>`. There will likely never be cross-browser native support for
`<content>`, while Safari and Chrome already support `<slot>` natively.
> Convert the simplest cases of <content> to <slot>

- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
Sorting table entries in Polymer consumes a lot of time for large profile. Offloading this logic to trace generation eliminates this latency.
> Improve the op_profile response time by offloading table sorting to trace generation

- tensorboard/__main__.py
- tensorboard/main.py
- tensorboard/pip_package/setup.py
The open source entry-point might not have been invoking tf.app.run() which
a user reports might have caused errors like this to happen:
```
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag
--debugger_data_server_grpc_port before flags were parsed.
```
I wasn't actually able to reproduce this error, but this change might fix things.
> Ensure flags get initialized

- tensorboard/components/tf_categorization_utils/tf-category-pane.html
Based on user feedback, we updated the dashboards to not display search results by default. Therefore it now makes sense to have panes expanded by default, especially since we implemented pagination a few months ago.
cc: @wchargin
> Make category panes open by default

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
This change makes it possible to render the UI on desktops when there's a large
number of active plugins, which might have long names. While it may not be the
optimal solution, it represents a significant improvement.
> Add chevron scrolling to toolbar tabs

- tensorboard/plugins/debugger/debugger_plugin_loader.py
This way we can specify a default value in our production configs.
> Make grpc debugger port flag -1 by default

- tensorboard/plugins/projector/vz_projector/bh_tsne.ts
- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
A user-defined perturb factor determines the extent of random position shifts upon pressing of Perturb button, which is useful to move out of a local optimum or to alter the solution for a fresh perspective. Perturb T-SNE by independently scaling point positions when Perturb button is clicked, which is useful to move out of a local optima.
Demo here: http://tensorserve.com:6014
```bash
git clone -b projector-tsne-perturb https://github.com/francoisluus/tensorboard-supervise.git
git checkout 5b6a71b30f8f5b68896bef4354c90fd4d8bd73e1
bazel run tensorboard -- --logdir /home/emnist-2000 --host 0.0.0.0 --port 6014
```
1. Behavior remains exactly the same when the perturb button is never clicked.
2. Only one change is made in the t-SNE step() function, with a random …
> Projector: Perturb t-SNE solution

- tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
The Projector can now enlarge/shrink the actual sprite images/placeholders during zooming, which is useful for closer inspection of samples when zooming, or for reducing sprite occlusion when zooming far out.
Demo here: http://tensorserve.com:6011
```bash
git clone -b projector-2d-spritezoom https://github.com/francoisluus/tensorboard-supervise.git
git checkout 9a71c652944672826671a6ff32c6d022e0d9cd01
bazel run tensorboard -- --logdir /home/emnist-2000 --host 0.0.0.0 --port 6011
```
Supersedes [#672](https://github.com/tensorflow/tensorboard/pull/672): Projector improvements: Pause/resume T-SNE, and 2D sprite element zoom
Smallest sprite size, and reset zoom size:
Medium enlarge size, and maximum sprite size:
The 2D zoom is set according to the …
> Projector: 2D sprite element zoom

- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.ts
Make the neighbors slider editable in the inspector panel of the projector. This allows for finer-grained control on neighborhood size when selecting groups, which becomes important during interactive supervision.
Demo here: http://tensorserve.com:6021
```bash
git checkout  de640f6fb3a4dd1822dafca928055e8f0476ddac
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6021
```
1. Lowered maximum from 1000 to 999 to fit into slider edit box.
2. Requires [Enter] to set the new neighborhood size.
3. Edit box arrows auto-hide when unfocused.
> Projector: Inspector-panel neighbors slider editable

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
Make the default value for the dataSeries property an empty list.
Previously, PR #679 had set no default value for the property, which
meant that polymer would not trigger observers that depend on the
property, which meant that changing runs via the run selector did
nothing for dashboards that had not set the dataSeries property to a
non-falsy value (such as the scalars and PR curves dashboards).
> Set dataSeries to default to empty list

- tensorboard/BUILD
- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/components/vz_line_chart/vz-chart-helpers.ts
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/default.py
- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/custom_scalar/__init__.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/custom_scalar/layout.proto
- tensorboard/plugins/custom_scalar/metadata.py
- tensorboard/plugins/custom_scalar/summary.py
- tensorboard/plugins/custom_scalar/summary_test.py
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/BUILD
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-helpers.ts
- tensorboard/summary.py
- tensorboard/summary_test.py
This plugin makes custom line charts based on regex filtering of tags. Input appreciated! I want to port a prototype into google ASAP so we can test it out.
At a glance, here's how it works. The user sets the dashboard layout via a proto. For instance,
```python
from tensorboard import summary
from tensorboard.plugins.custom_scalar import layout_pb2
...
layout = layout_pb2.Layout(
category=[
layout_pb2.Category(
title='mean biases',
chart=[
layout_pb2.Chart(
title='mean layer biases',
tag=[r'mean/layer\d+/biases'])
]),
layout_pb2.Category(
title='std weights',
chart=[
layout_pb2.Chart(
title='stddev layer weights',
tag=[r'stddev/layer\d+/weights'])
]),
layout_pb2.Category(
title='cross entropy ... and maybe some other values',
chart=[
layout_pb2.Chart(
title='cross entropy',
tag=[r'cross …
```
> Prototype the custom-scalars plugin.

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
Projector: Replaced t-SNE Stop button (which terminates t-SNE) with a Pause/Resume button and functionality, while retaining t-SNE auto-termination upon projection-type switch (from t-SNE to PCA or Custom).
Demo here: http://tensorserve.com:6010
```bash
git checkout a6a61e902234b48ee9429f4657dea5dc0dddc300
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6010
```
Supersedes [#672](https://github.com/tensorflow/tensorboard/pull/672): Projector improvements: Pause/resume T-SNE, and 2D sprite element zoom
> Projector: Add t-SNE pause/resume button (replaced Stop button)

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector.html
- tensorboard/plugins/projector/vz_projector/vz-projector.ts
In the Projector any point selections can be modified by toggling selection/deselection, which can be done for single points or a collection.
Demo here: http://tensorserve.com:6012
```bash
git clone -b projector-selection-editor https://github.com/francoisluus/tensorboard-supervise.git
git checkout 9d9a9658fa8ffbe29e55ed375f2abd97019f4591
bazel run tensorboard -- --logdir /home/emnist-2000 --host 0.0.0.0 --port 6012
```
1. Uses toggle button for edit mode, like "Bounding box selection".
2. When edit mode is off Projector works exactly as before.
3. When edit mode is on, any existing point selection will toggle selection/deselection for any chosen points, even for multiple points now selected with bounding box.
4. Inspector panel neighbors list gets updated with …
> Projector: Add selection editor

- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
t-SNE now first terminates upon press of Stop/Re-run button, then a second button click re-runs t-SNE. Otherwise existing requestAnimationFrame(step) process does not terminate.
Demo here: http://tensorserve.com:6010
```bash
git checkout a7f1672f29875dde29f2a0080a61f105606a85dc
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6010
```
Referencing https://github.com/tensorflow/tensorboard/pull/691 Projector: Add t-SNE pause/resume button (replaced Stop button).
@dsmilkov please consider merging this important fix.
1. Re-run button now becomes a Stop or Re-Run button, depending on _dataSet.hasTSNERun_.
2. Stop/Re-run button press checks _dataSet.hasTSNERun_ to …
>  [Fix] Projector: Terminate t-SNE properly on re-run

- tensorboard/backend/http_util.py
- tensorboard/backend/http_util_test.py
- tensorboard/plugins/core/core_plugin.py
This changes CorePlugin to load its static assets into memory at startup and precompress them with gzip.  The two static assets in this case are "index.html" (the main vulcanized TensorBoard HTML blob) and "trace_viewer_index.html".  Since "index.html" at a minimum is always served when using TensorBoard, this spends roughly 1 MB of extra RAM to move the cost of preparing it to startup-time so that it can be served directly from memory.
Prior to this change, a typical request for those assets would involve 1) a disk read to open the assets_zip_provider webfiles.zip file, 2) unzipping that zip file, 3) extracting the index.html file from the zip archive, and 4) recompressing the file using gzip (about 40ms to compress 2.6MB down to 0.7ish) to send it back to the client.
Now it's just …
> Preload and precompress static assets in CorePlugin

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
Prevent sidebar from getting to big for new plugins that use tf-dashboard-layout.
> Set max-width for TensorBoard sidebar

- tensorboard/BUILD
- tensorboard/__init__.py
- tensorboard/lazy.py
- tensorboard/summary_test.py
This change introduces a lazy loader that will allow us to provide some of the
conviences TensorFlow has. For example:
import tensorboard as tb
tb.summary.scalar('foo', tensor)
Only the hourglass summary module has been made available in this namespace,
since that's probably the only thing where we're 100% positive we want this
functionality.
> Make import tensorboard as tb possible

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
Previously, TensorBoard had only stored 10 samples of PR curves at once
for each tag, which has proven a bit coarse.
A common threshold for PR curves is 201. Each PR curve summary consists
of 6 rows of num_threshold float32 values. Therefore, storing 100
samples in memory for each tag means that we store
100 * 201 * 6 * 4 B = 482.4 KB for each tag
That seems fine.
> Make TensorBoard store 100 samples of PR curves

- tensorboard/plugins/graph/tf_graph_common/template.ts
comparing of visit pattern should be done symmetrically. we should NOT check g2's node inside g1's visit map.
> FindSimilarSubGraph bug fix.

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/comm_channel.py
- tensorboard/plugins/debugger/comm_channel_test.py
- tensorboard/plugins/debugger/debug_graphs_helper.py
- tensorboard/plugins/debugger/debug_graphs_helper_test.py
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/debugger/debugger_server_lib.py
- tensorboard/plugins/debugger/interactive_debugger_plugin.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/interactive_debugger_server_lib.py
- tensorboard/plugins/debugger/session_debug_test.py
- tensorboard/plugins/debugger/tensor_helper.py
- tensorboard/plugins/debugger/tensor_helper_test.py
- tensorboard/plugins/debugger/tensor_store.py
- tensorboard/plugins/debugger/tensor_store_test.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/selection-tree-node.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tensor-shape-helper.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-line-chart.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
This large change list fleshes out the overall architecture of the
TensorBoard Debugger Plugin (TDP), including the backend and frontend.
The basic functionalities of the TDP are working, despite many rough
edges and TODO items. The basic functionalities include:
* Control Session.run() state with the Step and Continu... buttons:
breakpoints at the level of intra-graph nodes, possibly inside
tensorflow control-flow structures such as `tf.while_loop`s.
* Inspection of device-partitioned, runtime graphs, in conjuction with
the node list.
* Ability to filter nodes by node-name and op-type regular expressions,
which facilitates the searching and activation of node breakpints.
* Viewing a summary of runtime tensor shape, dtype and values for the
node breakpoints that have been activated.
* …
> [Debugger Plugin]: Initial commit

- tensorboard/components/tf_categorization_utils/BUILD
- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- tensorboard/components/tf_categorization_utils/tf-tag-filterer.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
@jart spearheaded this effort by introducing the tf-tag-filterer component. For each dashboard, we guard the rendering of categories until the DOM is ready.
Test Plan: Run the mnist_with_summaries model as well as the PR curves demo and the text demo. For each of the scalars, images, distributions, histograms, text, and PR curves dashboards, try loading the dashboard with and without a tagFilter GET parameter. Also, clear the tag filter and modify it.
Fixes #782
> Let users specify and store tagFilter in the URL

- tensorboard/plugins/debugger/debugger_plugin.py
- tensorboard/plugins/debugger/interactive_debugger_plugin.py
Partly addresses #454 by changing the debugger plugin startup lines to write directly to stderr rather than using `tf.logging.info()` which is not displayed by default since we set `tf.logging.level` to `WARN`.  Writing directly to stderr is what we do for the main `TensorBoard <version> at <url>` startup message.
> Send debugger plugin startup message directly to stderr

- tensorboard/plugins/projector/vz_projector/vz-projector-metadata-card.html
- tensorboard/plugins/projector/vz_projector/vz-projector-metadata-card.ts
Paper-icon-button in metadata-card eventually becomes null, which throws an error when trying to set style. Rewrote metadata-card toggling to use Polymer property to dynamically change icon based on collapse state. Also reduced the width of the metadata-card slightly as it often occludes part of the projection slightly.
Demo here: http://tensorserve.com:6023
```bash
git checkout 8e266291011e3dc693d69cc1130ac5d014cee4a9
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6023
```
```javascript
Uncaught TypeError: Cannot read property 'style' of null
at HTMLElement.MetadataCard._expandLess ((index):142485)
at handler ((index):8238)
at HTMLElement.decorated ((index):12199) …
```
> [Fix] Projector: MetadataCard toggle icon

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
Make the debugger plugin only start long-polling after opening the
dialog that notes we're waiting for the first session run.
Otherwise, if the user starts the TF run time before starting
TensorBoard, the dialog might be closed before it is opened, so the
dialog perpetually appears.
> Make debugger plugin wait on dialog open

- tensorboard/pip_package/build_pip_package.sh
This change ensures that `build_pip_package.sh` uses just one python binary - whatever is available as `python` - rather than building the py2 wheel file with `python` and the py3 one with `python3`.  Building a wheel file for pyX doesn't actually require running `setup.py` with the matching pythonX binary; you can just specify the version the wheel file should be built for explicitly.
It's better to use just `python` because that means that within a virtualenv that only provides `bin/python` (e.g. a python2 virtualenv), you still pick up the hermetization of the virtualenv.  Otherwise, under a python2 virtualenv, the invocation of `python3` will break out of the virtualenv to the system's python3 and whatever old crufty package versions it shipped with, instead of using the virtualenv's …
> Make build_pip_package.sh use only one python binary

- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
The spinners are activated during rendering of the node list and the
graph, as well as the TF runtime execution time following the
stepping/continuing actions.
> [Debugger Plugin]: Add spinners for the debugger page

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
Clicking a node or tensor in the table focuses on the corresponding node
in the graph visualizer, if it exists.
> [Debugger Plugin]: Add clickable links to Session.runs table

- tensorboard/pip_package/pip_smoke_test.sh
This makes `pip_smoke_test.sh` robust against two types of false positives that I realized it might produce:
1.  Testing for the post-pip-package-installation presence of a tensorboard binary with `which tensorboard` could falsely return true if tensorboard was anywhere on the path (e.g. installed to the system outside the virtualenv), meaning it didn't actually guarantee that the tensorboard command used later in the script would be the one from the pip package.
2. Testing for whether URLs are accessible at `localhost:6006` (by default) could falsely succeed if there was another pre-existing tensorboard instance running locally on port 6006 (which is common for a developer machine since that's the default tensorboard port), since the accesses don't really have a way to check that they're …
> Make pip_smoke_test.sh more robust against false positives

- tensorboard/backend/application.py
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/program.py
> Add --window_title flag.

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
We make the debugger plugin use a custom backdrop that does not occlude
the main TensorBoard navigation bar. This lets the user navigate to a
different dashboard after arriving at the debugger dashboard and
encountering the dialog that notes how the plugin is waiting for the
first session run.
Screenshot:
Fixes #793.
> Make debugger plugin backdrop not block navbar

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
We:
* Make the node list vary in height based on the height of the window
and scroll if necessary during overflow
* Solve an issue in which the UI becomes unclickable after the dialog
disappears.
* Add some top-bottom padding to various elements on the page.
Here is how the dashboard now looks like.
And here is how the dialog screen looks like.
Some of the issues fixed I had introduced in #806.
> Fix lay out of the debugger plugin

- tensorboard/plugins/graph/tf_graph_debugger_data_card/BUILD
- tensorboard/plugins/graph/tf_graph_info/BUILD
Add direct dependency on paper-material-html target, since the latest version of paper-button does not depend on it.
This change is a no-op with the current code, and is required for the update of paper-button to hybrid.
> Add direct dependency on paper-material-html target

- tensorboard/plugins/profile/tf_op_profile/BUILD
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
Add a slider to show top K time consuming ops per category. Also add a toggle button to select whether to show only top 90th percentile ops. The costly op section is removed.
> Add slider and toggle button to show top K nodes within top 90th percentile.

- tensorboard/plugins/debugger/tf_debugger_dashboard/selection-tree-node.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
* Add context menu in the Runtime Graph View to expand to a given node.
* Highlight nodes in Node List during stepping.
* Make the Node List automatically expand non-leaf levels with only one
child.
* Make clicking the "(Click to view)" links in Tensor Value Overview
reliably open the Tensor Values tab in the top-right quadrant.
> [Debugger Plugin]: Some improvements to Node List and Tensor Value View

- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
This enables the purging of out-of-order steps, which was behavior in EventAccumulator that evidently never quite made it to PluginEventAccumulator.  Also cleans up the testing a little bit.
Fixes #803 (and consequently also #652).
> Enable out-of-order step purging in PluginEventAccumulator

- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/scene.ts
When a user selects a node that is out of view, the graph explorer pans
to it and centers it. Unfortunately, this feature had some issues.
0. Panning happened before graph expansion completed. This led to pan
target calculations that relied on incorrect, outdated measurements. We
fix by waiting 250ms (the default duration for animations in the graph
explorer) before panning in order to give enough time for node expansion
to complete.
1. The graph explorer did not take into account the position of the
graph's root SVG element with respect to the viewport. This led to
panning calculations that were off by a constant amount along the X and Y
dimensions. We fix by taking those 2 values into account.
2. Nodes could sometimes be occluded by the minimap - those nodes are
strictly speaking still …
> Fix issues related to panning to a node

- tensorboard/BUILD
- tensorboard/pip_package/BUILD
- tensorboard/pip_package/pip_smoke_test.sh
This fixes our pip package's bundled library (what you get from `import tensorboard`) so that it actually includes the full `:lib` target rather than just `:summary`.  Right now, they're essentially the same, except that `:lib` also includes the lazy-loading functionality that makes `import tensorboard as tb` work as intended.  This is also more future-proof since at some point we may want our consumer python API to include more easily accessible functionality than just `tb.summary`.
I added some clarifying comments and a test in `pip_smoke_test.sh` to avoid regressions.
Note that while `import tensorboard` right now only directly exposes the summary API (via the lazy `tf.*`-style loading), pip package users can of course still access whatever python files we bundled into the pip package …
> Include entire :lib target in pip package

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph/tf-graph.html
Previously, the debugger dashboard would not pan to a node if it had
already been selected. Now, we pan to the node regardless.
There are unfortunately still cases in which the graph does not pan to
a node if it is slightly out of view. Those cases are still being
investigated. Furthermore, the graph does not pan to `const` annotation
nodes, which may appear more than once in the graph ... like this:
> Make debugger dashboard pan to focused node

- tensorboard/plugins/graph/tf_graph_common/scene.ts
Previously, logic for determining whether a node was out of bounds in
the graph did not take into account how the top-left of the graph might
not match the top-left of the viewport.
Now, we correct that and furthermore pan to a node if it is even
partially out of view.
> Correct logic for finding if a node is in bounds

- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/custom_scalar/README.md
- tensorboard/plugins/custom_scalar/custom_scalar_demo.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
- tensorboard/plugins/custom_scalar/layout.proto
- tensorboard/plugins/custom_scalar/summary_test.py
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/BUILD
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-card-style.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
We let the user plot both margin charts as well as (the pre-existing)
multi-line charts within the custom scalars dashboard. Margin charts are
configured with a list of series. Each series takes 3 tag strings
(value, lower, and upper) that correspond to scalar summaries (logged as
usual via `tf.summary.scalar` or via TensorBoard's summary module).
Those 3 tag strings are used to populate the value, lower bounds, and
upper bounds of margins. See changes to the Layout proto for details.
This screenshot shows a working margin chart.
If data for a tag cannot be found, the custom scalars dashboard issues
a warning message, as this screenshot shows.
Also introduced a custom_scalar_demo.py script for generating demo data.
> Let custom scalars dashboard plot margin charts

- tensorboard/plugins/projector/vz_projector/bh_tsne.ts
- tensorboard/plugins/projector/vz_projector/data.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
- tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
- tensorboard/plugins/projector/vz_projector/vz-projector.ts
Integrates/supersedes:
1) #756 Projector: Supervision and metadata editor (semi-supervised t-SNE)
2) #762 Projector: t-SNE perturb v2
https://medium.com/@fpsluus/interactive-supervision-with-tensorboard-9a101c91d3f7
Demo here: http://tensorserve.com:6016
```bash
git checkout 84e9c55c56fc358a1f9a7746d896ccdc62db6128
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6016
```
Notice the repeating contraction in the below image, relating to repetitively turning supervision on and off, which incorporates the prior probabilities based on pairwise label similarity/dissimilarity when supervision is turned on.
Add supervise metadata column selection and unlabeled class input …
> Projector: Semi-supervised t-SNE

- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-vertical-resizer.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
We introduce a `tf-debugger-vertical-resizer` component that lets the user resize the left hand panel by dragging the component. The component lets the user specify a min and max width (so that for instance (1) both the left and right sides remain usable and (2) the dragger component does not disappear). Logic also responds to resizing of the window.
Screenshots:
> Make the LHS of debugger dashboard resizable

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
We rename the left menu within the debugger plugin to the left pane.
This seems semantically more accurate. The left hand side is not really
a menu.
We store the window width as a property of the debugger dashboard so
that other methods may respond to it.
This change does not alter functionality at the user level.
> Rename left menu to left pane

- .travis.yml
The security certificate of ci.tensorflow.org expired, causing TensorBoard's tests on travis to fail. See https://github.com/tensorflow/tensorflow/issues/15827.
This change enables our travis environment to successfully install tf-nightly.
Unfortunately, the travis tests still fail after this PR goes in, but that is because of https://github.com/tensorflow/tensorflow/issues/15777. We are still deciding what to do there - we might have to dockerize tests.
Anyways, fixing the issue caused by the expired certificate will let us focus on that different issue. Thanks to @nfelt for suggesting that we try using `pip install tf-nightly`.
> Use `pip install tf-nightly` within .travis.yml

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
We store the left pane width of the debugger dashboard within local
storage as well as within the _leftPaneWidth GET param. That way, when
the user revisits the debugger dashboard, the width will be restored.
We store the default width of the left pane within a
`_DEFAULT_LEFT_PANE_WIDTH` variable.
We also add 8px of padding to the main content area:
This change makes it easier to review #848.
> Store left pane width in local storage and URL

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-vertical-resizer.html
The debugger dashboard now uses the `clientX` property to obtain the X position of the mouse instead of using the `screenX` property. Fixes #858.
> Obtain position using CSS pixels

- tensorboard/plugins/debugger/interactive_debugger_plugin.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/interactive_debugger_server_lib.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/selection-tree-node.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-op-selector.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-source-code-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
Main feature:
* Viewing the Python source code files involved in the creation of nodes
of the graph. (Only files outside the TensorFlow library are
included.)
* Lines of the code files are annotated with collapsible views of the
nodes whose creation stacks involve the lines.
* Clicking the node names in the Source Code View will focus on the
corresponding node in the Node List, the Graph View and the Tensor
Value Overview.
* Clicking the "forward" icon button next to the node name in the
Source Code View will cause the debugger to continue to the node and
display any tensor values in the Tensor Value Overview.
* Clicking the "stack" icon button right next to the node name will
open a sticky dialog that shows the full stack trace of the node's
creation. The stack trace contains clickable …
> [Debugger Plugin]: Add Source Code View

- tensorboard/defs/web.bzl
The `+` operator on dicts is deprecated and will be removed from Bazel.
> Remove usages of + on dicts

- tensorboard/components/vz_line_chart/vz-line-chart.ts
This lets the user specify a custom formatter for values along the X
axes of line charts which allows, for instance, plugin authors to round
those values to a certain number of decimal places.
Test plan: Introduce a custom formatter to charts within the scalars
dashboard:
```ts
_xAxisFormatter: {
type: Object,
value: () => d3.format('d'),
},
```
Notice that, for instance, this custom formatter rounds values to
integers.
Without that formatter, the rounding does not happen:
FYI @trisolaran
> Add xAxisFormatter property to vz-line-chart

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
This will prevent TensorBoard from using too many resources for anyone with a
large number of tags. In the near future we might want to solve this in a
smarter way, possibly by not rendering things outside the viewport.
See also #728
> Only open first two panes by default

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Allow xComponentsCreationMethod to be defined via xType.
Tested on PR curve plugin, scalar plugin, custom scalar plugin.
> Simplify vz-line-chart creation by allowing xType

- tensorboard/plugins/graph/tf_graph/tf-graph.html
We make the `tf-graph` component rebuild the graph hierarchy if any of the handlers related to edges or nodes are set on the component. This is necessary because the graph would render incorrectly if the graph hierarchy is built without taking into account the handlers. This fixes a race condition in the internal mapper tool in which the edge width function is occasionally not taken into consideration on certain page loads.
> Rebuild graph hierarchy if callbacks changed

- tensorboard/plugins/scalar/scalars_demo.py
This makes the scalars demo generate 100% deterministic deterministic summary output, by correcting for a race condition that probably afflicts a significant amount of TensorFlow summary-writing code.
The general race condition occurs when summary ops are fetched (in a `sess.run()` call) alongside ops that mutate a variable on which the actual summary values depend.  The scalars demo is a particularly simple example of this (there's a temperature variable that is incremented in each step, and also written out as a scalar summary), but many kinds of other TF graphs have a fundamentally similar structure. [1]
The problem lies in the fact that a `sess.run()` call with multiple fetches doesn't guarantee to execute the fetches in any particular order beyond what are expressed in explicit …
> Fix scalars demo summary writing race condition

- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/health_pill_calc.py
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/interactive_debugger_server_lib.py
- tensorboard/plugins/debugger/tensor_helper.py
- tensorboard/plugins/debugger/tensor_store.py
- tensorboard/plugins/debugger/tensor_store_test.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-source-code-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
- tensorboard/plugins/graph/tf_graph_common/scene.ts
* Add health pills to Tensor Value Overview. Health pills are succinct
graphical summaries of the values of tensors with numerical and
boolean types. They present a color-coded breakdown of the composition
of the tensor's elements, such as NaN, Infinity, positve, negative and
zero elements, as well as simple statistics including min, max, mean
and standard deviation. They are updated in real time as debugging
progresses. This is based on the prior work by @chihuahua 
* A legend is provided for health pills' color codes in Tensor Value
Overview.
* Add logic for handling uninitialized tensors.
* Add logic for handling string-type tensors.
* To this end, make the addHealthPill() method in the graph plugin
public.
> [Debugger Plugin]: Add health pills and handle special tensor values

- tensorboard/plugins/profile/README.md
- tensorboard/plugins/profile/overview_page/BUILD
- tensorboard/plugins/profile/overview_page/overview-page.html
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Add a new TPU profiling tool called Overview Page, which gives an overview of the performance of the workload run on the TPU. 
A screenshot of the tool output is attached.
Note that the step-time graph won't be shown in the current version of TensorBoard because of a bug in vz-line-chart. The screenshot was generated using an older version of TensorBoard.
> Add a new TPU profiling tool called Overview Page as a plugin

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
Before this change, the graph explorer minimap had been broken, as
discovered by @nfelt during manual testing. Specifically, the graph
would not render within the minimap.
Surprisingly, this CSS specification within the
`tf-debugger-initial-dialog` component had been hiding the SVG element
for the rendered graph within the minimap:
```css
:host:not([_open]) {
display: none;
}
```
That seems odd. The `:host` selector refers to the root of the shadow
DOM for the current component, in this case
`tf-debugger-initial-dialog`. That dialog is only rendered by the
debugger plugin - the debugger dashboard is not even constructed when
the graph dashboard (containing the minimap) is rendered.
I perused the vulcanized HTML and JS, and no issues seem to stand out
there.
This change solves the …
> Fix graph minimap by removing CSS property

- tensorboard/plugins/debugger/tensor_store.py
- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/health-pills.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-continue-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
Main new feature:
* Ability to continue to a given condition for any of the watched
tensors. This is presented as a new section in the pop-up dialog
of the "Continue..." button, while the existing continue n times
of Session.run is put into the first section of the dialog.
* The new continue-to momde supports the following modes:
* Contains inf or nan
* Contains inf
* Contains nan
* Max > or < ref value
* Min > or < ref value
* Range (Max - Min) > or < ref value
* Mean > or < ref value
* Stddev > or < ref value
* The pop-up dialog for Continue... is refactored into its own
Polymer component: tf-debugger-continue-to-dialog.html
Misc. improvements:
* Fix a bug wherein continue across multiple Session.run keys does
not render graph for new run key.
* Move the toast from the bottom left to …
> [Debugger Plugin]: Continue to condition & misc. improvements

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
Fixes two polymer bugs/misuses:
dom-repeat items can't be intialized from a function call that takes a property
dom-repeat can't be used with table rows.
Additionally, the device checkboxes under 'Devices included in stats':
now display the trimmed item suffix
is aligned with item suffix
Before image:
After the fixes:
[Note: I added a GPU to my machine during development.  That is why there is just ONE device in the 'before' picture and TWO devices in the 'after picture]
> The list of devices is now displaying correctly when coloring by "Device", "Compute", or "Memory".

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Previously, containers of unselected dashboards would not be displayed
(They are set to `display:none;`). We now "display" unselected
dashboards within a container of max-height 0, effectively hiding it,
but also allowing Plottable logic to obtain correct container
measurements. Fixes #554.
Test Plan (for Chrome and Firefox):
Run mnist_with_summaries.py and start TensorBoard. Switch from the
scalars to the images dashboard. Toggle the train run. Navigate back to
the scalars dashboards. Note that no line charts are degenerate.
> Display unselected dashboards in height 0 divs

- tensorboard/components/vz_line_chart/vz-line-chart.ts
We remove the outer function wrapper from the default value for xComponentsCreationMethod because `vz_line_chart.stepX` is already a valid value for the property. Creating a function that returns `vz_line_chart.stepX` results in a bug.
This fixes an internal issue.
> Remove outer function wrapper

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
Previously, smoothing would affect the main line within margin charts,
but not the lower and upper bounds. That confused the user.
Hence, we avoid making smoothing affect margin charts. The alternative
of smoothing the bounds in addition to the main line raises statistical
concerns about how valid the smoothing is when applied to bounds. The
first team that might find this feature valuable also noted that just
making margin charts unsmoothed would likely work nicely.
The main line now lies within the bounds.
> Make smoothing not affect margin charts

- tensorboard/components/tf_dashboard_common/BUILD
- tensorboard/components/tf_dashboard_common/dashboard-style.html
- third_party/polymer.bzl
The classes/iron-flex-layout.html file is deprecated.
Previously, this caused line charts within TensorBoard run in Google to
stack atop each other - the file contained CSS necessary for flex
positioning.
We now instead include the recommended file
iron-flex-layout/iron-flex-layout-classes.html in order to import those
necessary flex styles. This causes the line charts to lie next to each
other (flex-positioned) as expected.
We still can't drop classes/iron-flex-layout.html from BUILD
dependencies, however, because TensorBoard's version of the paper-styles
component still imports that file. We may want to consider upgrading the
version of paper-styles.
> Include iron-flex styles within dashboard styles

- RELEASE.md
- tensorboard/version.py
The 1.5.0 release series and beyond will use the new PyPI package name of just plain `tensorboard`.
> TensorBoard 1.5.0

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
Previously, the user was unable to interact with the debugger dashboard
because the tf-debugger-initial-dialog occluded the dashboard even if
the dialog was closed (and thus visible).
This change fixes the problem by directly altering the display of the
component itself.
> Hide debugger dialog by using _hidden property

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
PR #902 fell short of fixing #554 because some elements such as dialogs
may be fix-positioned, in which case they anchor to the browser viewport
instead of the container. This means that may still be visible even when
the dashboard containing them is not selected.
For instance, here, we navigated to the debugger dashboard before
switching to the graph dashboard.
This fixes that problem by also making containers invisible in addition
to having a max height of 0. Note that invisible elements still have
height (unlike elements that are not displayed) - thus, Plottable can
still obtain accurate measurements of DOM elements and prevent charts
from becoming degenerate.
Test Plan (First run mnist_with_summaries.py):
Start TensorBoard with the debugger_port flag set (to enable the debugger …
> Make containers of inactive dashboards invisible

- tensorboard/plugins/graph/tf_graph_common/annotation.ts
- tensorboard/plugins/graph/tf_graph_common/contextmenu.ts
- tensorboard/plugins/graph/tf_graph_common/node.ts
Previously, the context menu was often incorrecrtly positioned due to
unexpected behavior of the layerX and layerY properties. They returned
distances in non-device spaces and thus varied based on local CSS.
Furthermore, the layerX and layerY properties will [soon be deprecated](https://bugs.webkit.org/show_bug.cgi?id=21868).
We therefore redo the logic for positioning the context menu by making
use of the clientX and clientY properties. We subtract the offset of the
scene element from those properties. This correctly positions the
context menu.
> Correct position of context menu

- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/pip_smoke_test.sh
- tensorboard/pip_package/setup.py
This fixes the installation issues from #916, specifically items 1 and 2, by:
1. fixing `build_pip_package.sh` to use setuptools > 36.2.0 so that environment markers are preserved upon wheel generation (and hence PyPI upload)
2. adjusting our `futures` dependency to be python 2 only rather than allowing up to python 3.2 (when the `concurrent.futures` python3 module was introduced, which `futures` backports).  The `futures` package is not actually compatible with python 3.0+ and they recently started enforcing this in futures 3.2.0+ which resulted in broken tensorboard and tensorflow installs for some users.
Thanks to @fortran-favors-the-old for the suggested fixes.
> Enforce py2-only constraint on pip package `futures` dependency

- tensorboard/plugins/custom_scalar/custom_scalar_demo.py
Previously, the margins generated by the custom scalars demo were so
thin that it was hard to see that the plots were margin plots. We make
them significantly wider:
> Widen margins for custom scalars demo

- RELEASE.md
- tensorboard/version.py
Adds the 1.5.0 release notes back to master's RELEASE.md, reformats the 0.4.0 notes slightly, and bumps the version number at HEAD to ~1.5.1a0~ 1.6.0a0 since ~1.5.1~ 1.6.0 will be the next release _that gets branched from HEAD_.
> Update master based on 1.5.0 release

- tensorboard/pip_package/build_pip_package.sh
- tensorboard/pip_package/pip_smoke_test.sh
- tensorboard/pip_package/setup.py
This fixes the installation issues from #916, specifically items 1 and 2, by:
1. fixing `build_pip_package.sh` to use setuptools > 36.2.0 so that environment markers are preserved upon wheel generation (and hence PyPI upload)
2. adjusting our `futures` dependency to be python 2 only rather than allowing up to python 3.2 (when the `concurrent.futures` python3 module was introduced, which `futures` backports).  The `futures` package is not actually compatible with python 3.0+ and they recently started enforcing this in futures 3.2.0+ which resulted in broken tensorboard and tensorflow installs for some users.
Thanks to @fortran-favors-the-old for the suggested fixes.
> Enforce py2-only constraint on pip package `futures` dependency (#920)

- WORKSPACE
- tensorboard/defs/protos.bzl
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
- third_party/workspace.bzl
This unfortunately adds about 30 seconds of build time. This same change was recently made in https://github.com/tensorflow/tensorflow/pull/16157 and is part of the https://github.com/bazelbuild/bazel/issues/4425 effort.
> Upgrade Protobuf and Closure Rules deps

- .travis.yml
The updated `rules_webtesting` that works with Bazel 0.10.0 in fact *requires* Bazel 0.9.0 or greater, so Travis won't build #931 with its current config.  So I'm going to update Travis to use 0.9.0 in this separate PR, which is easier to notice and revert later if necessary.
> Set Travis to build with Bazel 0.9.0

- WORKSPACE
Fix #929 by following up on #883 to also update the `rules_webtesting` dependency, which was also suffering from a broken version comparison that started failing with Bazel 0.10.0.
cc @jart I have TODOs against you to add the requisite mirror.bazel.build mirror URLs.  I don't seem to have any access to update that mirror myself.
>  Update bazel rules_webtesting dep to work with Bazel 0.10.0

- tensorboard/db.py
Some SQL queries within db.py had been referring to columns named
`name`. Such columns don't exist and are actually named a little more
specifically. This is a quick fix for that.
> Fix a few column names in db.py

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/pip_smoke_test.sh
Fix #926 by explicitly including the projector module API, i.e. `import tensorboard.plugins.projector`, which provides access to `visualize_embeddings`, when building the pip package.
>  Add projector module API to pip package

- tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-resizer.html
We add a dragger that lets the user resize the explore container (the section containing the graph or visualizations of tensor values) vs the tensor value overview section.
We achieve this by generalizing the `tf-debugger-vertical-resizer` component, allowing it to support both vertical and horizontal resizing.
As part of this effort, we make the height of the graph scale based on the size of its container, which solves another problem: There will no longer be a giant gap between the graph and the tensor value overview section. Previously, that gap was possible in tall viewports because the height of the graph was fixed.
Screenshots:
> Let user resize tensor data and graph section

- tensorboard/program.py
This is a really simple change but I had to look at the code to understand why it wasn't working.
Another possibility would be to accept `sqlite3` as a valid scheme as well.
> Fix --db docstring to a working example

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
This makes it easier to read and enter.
> [Debugger Plugin] Set font-family of space/time slicing to monospace

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-data-summary.html
That height caused blank space to be under the tensor data table.
Before:
> Remove height 29% from tensor data table

- README.md
The custom scalars plugin lets the user overlap custom run-tag pairs
within the same plot as well as visualize margins. This change modifies
the main TensorBoard README to note those new features.
> Update README to consider custom scalars plugin

- tensorboard/version.py
I propose that going forward we should maintain our version at HEAD as +1 minor release ahead of our most recent release, i.e. as soon as we release the first release or release candidate for 1.N then we should move head up to 1.(N+1).0a0.  Or concretely, in this case since we've release 1.6.0-rc0 we should be at 1.7.0a0 at HEAD.
This is because logically, at HEAD we may already have new features that aren't going to be in 1.6.x and will be instead only incorporated into 1.7.0.  So HEAD is really an "alpha prerelease" for 1.7.0, not for 1.6.0.
Once we've bumped the version and have at least one 1.(N+1).0a<date> nightly release on PyPI, but no earlier than the TensorFlow release 1.N.0-rc0 release, we would send a PR to TensorFlow updating their tb-nightly dep to >= 1.(N+1).0a0 < …
> Bump version at HEAD to 1.7.0a0

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
Some early users of margin plots noticed a bug. If data associated with
a tag for any run was missing, an error message appeared noting that
data was missing for that tag. The error message gave no indication of
which runs were missing information. 
Sometimes, the behavior (missing information) is intended. For instance,
some run might not log a certain scalar value.
This change now offers users a more nuanced message when margin plot
logic is missing information for certain tags within a run. The message
notes specific runs and then lists the specific tags without data for
those runs. The message is placed under a collapsible so that the user
can chose to not see the message if the behavior is intended.
> Let user know which tags are missing per run

- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Currently, if you come in via link to a tensorboard page on /, a plugin hash will immediately get appended (/#scalars). No amount of back button clicking will get you back to the linking page because the history item for / will get you immediately js-redirected back to /#scalars (or whatever).
This pull request allows us to specify that the storage state set call should be history-replacing (i.e. use 'window.location.replace(...)' instead of 'window.location.hash ='. Now when you link into a tensorboard server, you will be able to navigate back!
> Makes the back button work across tensorboard index (/) landing page

- tensorboard/plugins/debugger/debugger_plugin_loader.py
Without this fix, under python3, we get a second exception because `err.message` does not exist (it was renamed to `msg`).  This fixes that issue, and also changes the logic to reraise any non-grpc ImportErrors without the grcp-related tip.
> Make debugger plugin's grpc ImportError handling work on py3

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/base_plugin.py
- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/text/text_plugin_test.py
This new `/data/environment` route (of the core plugin) responds with
base properties relevant to the frontend upon startup of TensorBoard.
These properties include:
* the window title
* the location of data - either a path to a log directory or a database
URI. This new route will enable the frontend to display the data
location on the bottom left when TensorBoard runs in database mode
(once the frontend makes use of this backend change in a different PR):
I was also hoping to use this relatively innocuous change to jumpstart
discussions. For example, as we progress towards getting TensorBoard to
run in database mode, tests for plugins will have to test behavior for
both logdir and database mode. What are the norms we expect tests to
follow?
One proposal is to have tests start a …
> Add /data/environment route

- tensorboard/plugins/scalar/scalars_plugin.py
We remove a comma and a quote from the SQL query for fetching scalar
values. This fixes a SQL syntax error that had been causing the route to
respond with an error 502.
> Fix SQL syntax errors in scalars plugin

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Previously, the frontend displayed the logdir under the run selector.
This change makes that area display either the logdir or the SQL URI
depending on which is used.
> Make frontend use /data/environment route

- tensorboard/backend/application.py
Removed logic for creating tables and a schema from the TensorBoard
application. The schema created by TensorBoard is out of date,
leading to errors that make TensorBoard fail to start up such as
```
return f(*args[:-2] + (request,))(*args[-2:])
File "/usr/home/chihuahua/Desktop/tensorboard/tensorboard/backend/application.py", line 243, in _serve_plugins_listing
response[plugin.plugin_name] = plugin.is_active()
File "/usr/home/chihuahua/Desktop/tensorboard/tensorboard/plugins/scalar/scalars_plugin.py", line 77, in is_active
''', (metadata.PLUGIN_NAME,))
File "/usr/home/chihuahua/Desktop/tensorboard/tensorboard/db.py", line 505, in execute
cursor.execute(sql, parameters)
File "/usr/home/chihuahua/Desktop/tensorboard/tensorboard/db.py", line 572, in execute
self._delegate.execute(sql, …
```
> Remove logic for creating tables

- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
We make the core plugin serve a list of runs retrieved from the database.
> Serve list of runs in database mode

- tensorboard/plugins/scalar/scalars_plugin.py
This change makes the scalars plugin exclude tags without runs ... as
well as tensors without either a tag or a run.
The scalars dashboard still WAI:
> Convert LEFT JOINs to JOINs within scalars plugin

- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/histogram/histograms_plugin.py
Note that logic for serving histogram values performs string templating
to accommodate downsampling.
> Make histogram plugin work in SQL mode

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
This PR makes the frontend obtain the window title from the
/data/environment route instead of via the /data/window_properties route
(which we will deprecate).
Test Plan:
Start TensorBoard with the `window_title` flag specified. Note that the
window title is changed appropriately:
```
bazel run //tensorboard -- --logdir /tmp/custom_scalar_demo --window_title foo
```
Start TensorBoard without that flag. Note that the window title defaults
to "TensorBoard".
> Obtain window title from /data/environment route

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
Previously, the font sizes of chart titles and various other pieces of
content within the custom scalars dashboard did not match the font sizes
of corresponding content within the scalars dashboard (and other
dashboards). Thank you to @jart for noticing.
This PR makes those font sizes match.
> Fix font mismatch in custom scalars dashboard

- tensorboard/plugins/histogram/histograms_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
Applying `bool()` to a `sqlite3.Cursor` always returns `True` - while the Cursor can be used like an iterable, it doesn't define `__len__()` (since the result set size isn't necessarily known until you start iterating over it) or `__nonzero__()` and hence is Truthy always, even when the result set is empty.
The fix for this is just to convert it to a list first.
> Fix DB-based is_active() methods to not always return True

- tensorboard/backend/application.py
- tensorboard/program.py
This disables event file loading when --db is passed.  It does this by making a negative value for --reload_interval have the effect of disabling all the Multiplexer run-adding and reloading logic (even the initial load that you get by passing 0), and then conditionally setting reload_interval to -1 if we got a DB.
Currently, even when you pass --db and do not pass --logdir, we still try to load event files, which could lead to inconsistent state across the DB-enabled and not-yet-DB-enabled plugins.  It's especially bad if you don't pass --logdir at all, since that gets interpreted as the empty directory i.e. the current directory, and so we can easily waste a lot of cycles on the Reloader thread searching through the entire current directory tree looking for tfevents files.
> Disable event file loading when --db is passed

- tensorboard/components/tf_dashboard_common/dashboard-style.html
- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
Within small viewports, main content had been overlapping with the
sidebar.
This change fixes that by removing a `min-width` specification on the
wrong container and placing it on the right one. Changed that min width
to 270px (from 350px). Any lower, and buttons overflow to the next line. 
New behavior:
> Prevent content from intruding into sidebar

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-continue-dialog.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
1. In some cases, a node with other nodes whose name scopes are the
nodes name will not have a normalized (i.e., base-expanded) node
name in the graph visualizer. E.g., consider a graph with two
nodes, "Reshape" and "Reshape/shape". The "Reshape" node will
be named as simply "Reshape", instead of "Reshape/(Reshape)" in
the graph visualizer. As such, assuming base expansion always
happens will lead to problems focusing on graph nodes through
clicking nodes in the Node List or the Source Code View. This
CL relaxes this assumption, which ensures the correct behavior.
2. When continuing to a given tensor, notify the user when a
new Session Run has started. Also give user the option to stop
continuation during the continue-to-tensor actions.
> Two fixes to debugger plugin

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
* Instead, bind the refresh() method to on-change events of the
Slicing and Time Indices input boxes.
> [Debugger Plugin] Remove "Refresh" Button from Value Cards

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
* Make the tensor name title clickable. When clicked, it'll highlight
the node in the Graph View, the Node List, as well as the Source
Code View (if open).
* Hide the default "DebugIdentity" op name to reduce visual cluttering.
> [Debugger Plugin] Tensor Value Card UI Improvements

- tensorboard/plugins/graph/tf_graph_common/scene.ts
* The label, which previously shows only min ~ max even for
tensor values with NaNs and Infs, now will explicitly say
how many NaNs and Infs there are if any of those exist.
> Let health pill label indicate NaN/Infs more saliently

- tensorboard/plugins/distribution/distributions_plugin.py
- tensorboard/plugins/histogram/histograms_plugin.py
This replaces the randomized downsampling used in the histograms plugin SQL query with a systematic linear sampling strategy, based on dividing the range into k - 1 equal-sized intervals and then returning the lowest steps at or above the k interval boundaries.  This produces cleaner and more readily understandable/predictable charts, where we now get the nice property that (at least when steps are contiguous) any two adjacent histogram curves will be separated by the same step delta +/- 1 so the actual rate of change is easier to discern.  As a bonus, the new results also always include the lowest and highest steps in the series.
Old sampling:
New sampling:
We can now turn off sampling inline with the same query rather than using string templating.  I factored out finding the tag ID into …
> Change histogram SQL query to use linspaced sampling

- tensorboard/pip_package/setup.py
- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/tf_beholder_dashboard/BUILD
This fixes a few build issues with the Beholder plugin:
1. removes `@org_tensorflow_tensorboard` repository identifiers from dep paths
2. removes redundant `//tensorboard/plugins/beholder` within beholder package
3. changes `shared_config.py` to actually be a shared lib vs a src in three libraries
4. whitelists `beholder/resources/*` as pip package data - fixes #1032 
It turns out that (1) was actually breaking our pip package, because somehow having @org_tensorflow_tensorboard was bringing in a whole separate copy of TensorBoard sources into the `build_pip_package` rule's data attribute, and due to Bazel's poor legacy handling of __init__.py files (https://github.com/bazelbuild/rules_python/issues/55), this causes it to clobber our actual tensorboard/__init__.py file with an empty …
> Fix build issues caused by adding Beholder plugin

- tensorboard/plugins/image/images_plugin.py
This adds SQL queries to the images plugin so that it works in database mode.  For now, we don't do any sampling by step count, so each image series will return the full series of available steps in the DB.
There are some inefficiencies in the queries due to mismatches between the way we store image summaries in the DB and the structure of the the image plugin requests.  The worst offender is that in order to satisfy the original index_impl() request - which blocks loading the rest of the dashboard - we end up needing to scan over every single image summary entry in Tensors.  This is because index_impl() needs to know the sample count for each image tag (since each sample gets its own image loader card), but within a tag the sample count of each summary can vary independently.  The …
> Add SQLite support to images plugin

- tensorboard/pip_package/README.rst
- tensorboard/pip_package/pip_smoke_test.sh
- tensorboard/pip_package/setup.py
This is a cherry-pick of 71a816bd38785adf0b478fd75d733858c4698bed from 1.6 to master, since I realized we never actually merged this change back into master.  We'll want it for the 1.7 release onwards.
> [CHERRYPICK] Change PyPI package name to just 'tensorboard'

- tensorboard/components/vz_chart_helpers/BUILD
- tensorboard/components/vz_chart_helpers/vz-chart-helpers.html
- tensorboard/components/vz_chart_helpers/vz-chart-helpers.ts
- tensorboard/components/vz_line_chart/BUILD
- tensorboard/components/vz_line_chart/vz-line-chart.html
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-helpers.ts
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
- tensorboard/plugins/distribution/vz_distribution_chart/BUILD
- tensorboard/plugins/distribution/vz_distribution_chart/vz-distribution-chart.html
- tensorboard/plugins/distribution/vz_distribution_chart/vz-distribution-chart.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
We move logic within the ChartHelpers module to a new vz_chart_helpers
component. This enables other components to depend on logic within that
file.
In the near future, we will add a vz_bar_chart component that will make
use of this new component.
Test plan: Verify that TensorBoard WAI with logs from
[mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/b1c32226cc0cd44da9985a60e6a0ac6dec120fa5/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py).
> Create vz_chart_helpers component

- tensorboard/components/vz_bar_chart/vz-bar-chart.html
- tensorboard/components/vz_bar_chart/vz-bar-chart.ts
This fixes the build breakage due to a few TypeScript compilation errors in the newly introduced vz-bar-chart.ts from PR #1037.  One was a typo and the other was a typing issue with the createTooltipHeaders() function not having type information its tooltipColumns parameter necessary to know it has a .title property.
There were a few other fixes necessary to get the tooltips fully working:
- moved it inside BarChart (where it probably belongs more anyway) so the selection can use `this.tooltip` since it wasn't finding `#tooltip-table-header-row` from the old location
- added the insertion of an initial empty header (for the column that contains the swatches of color to identify different data series).
- as a bonus, I added in the "closest" highlighting behavior from the scalars tooltip …
> Fix and enhance tooltip logic in vz-bar-chart.ts

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-session-runs-view.html
* Let the table occupy 100% of the parent's width
* Let the table not expand to unreasonably large sizes if there are
many session.run() types and/or a session.run() with many fetches
or feeds
* When the table is scrolled, auto-scroll to the row that corresponds
to the active session.run().
> [Debugger Plugin] Fix session run list UI

- tensorboard/plugins/text/text_plugin.py
- tensorboard/plugins/text/text_plugin_test.py
We make the text plugin's is_active method return true if it detects
relevant data present within the multiplexer. Subsequently, there would
be no more need to check for data stored within plugin assets.
This solves an issue: The text plugin used to be inactive when the user
initially loads into it because the thread for computing whether the plugin
is active would not have completed executing yet.
Part of #625.
Test plan:
Run the [text demo](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/text/text_demo.py). Verify behavior. The text plugin should be active on
the first load.
> Make text plugin's is_active method check for data in multiplexer first before checking plugin assets.

- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/interactive_debugger_server_lib.py
* keys() returns a `dict_keys` object in python-3, which can cause
errors durinng json serialization sometimes.
> [Debugger Plugin] Fix a python-3 bug

- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/video_writing.py
This change reimplements video writing in Beholder.  The new API consists of a VideoWriter class that takes a list of VideoOutput types.  When sending a frame to VideoWriter, it handles cascading through the list of outputs until it finds one that works, as well as re-initializing an output if the frame size changes, which lets us simplify logic in Beholder itself.
Right now there are only two VideoOutputs implemented.  The primary one is FFmpegVideoOutput which uses a subprocess call to FFmpeg and currently is hardcoded to generate lossless-VP9-encoded video wrapped in a .webm container at 15 FPS.  As a fallback that should work in just about any scenario, PNGVideoOutput writes individual frames as PNG files to disk using TensorFlow's own `encode_png()` op.
A note on codecs: previous …
> Reimplement video writing support in Beholder

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/pip_smoke_test.sh
- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/__init__.py
- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/beholder_demo.py
This imports Beholder and BeholderHook into the top-level `tensorboard.plugins.beholder` module so we can use that distinction to emphasize what parts of that package are public vs "internal".  I also changed the pip package BUILD rule and smoke test to include the beholder build target, so that `tensorboard.plugins.beholder` will actually be included with our pip package.
Updated the demo to use this import style.  Doc updates to come in a future PR.
> Make "from tensorboard.plugins.beholder import Beholder" work

- tensorboard/plugins/pr_curve/summary.py
- tensorboard/plugins/pr_curve/summary_test.py
Previously, the streaming op for computing PR curves had relied on the
`tensor_summary` method to both produce a single update op to return as
well as add the update ops to various collections. That turned out
problematic since it wrote a duplicate summary, yielding an extra PR
curve plot in TensorBoard.
We now use a `tf.group` op and manually add individual update ops to
each collection.
Fixes #965.
> Make streaming_op for PR curves use tf.group.

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
PR #1033 had forgotten to migrate `tf-pr-curve-card.html` and `tf-custom-scalar-margin-chart-card.html` to use the `vz_chart_helpers` component.
> Fix frontend logic to use vz_chart_helpers module

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
Easier when there are multiple audio samples on a summary page that is user is listening to.
More discussion at:
https://github.com/tensorflow/tensorboard/issues/296
cc @rryan
> Remove loop by default from audio summary.

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
This fixes a breakage in the debugger plugin disabled dialog rendering, which was caused by a renamed element ID value.
Surprisingly, the logic failed in such a way that when triggering the dialog (e.g. navigating to "Debugger" from the "INACTIVE" plugin drop-down list), it would actually wipe the entire DOM, resulting in a totally blank and unusable page.  This is because `Polymer.dom(null)` apparently returns a DomApi instance for the entire document, so a pattern like `Polymer.dom(this.$$('#session-run-code-example')).textContent = ex;` will actually nuke the DOM if the selected element isn't found.
To avoid any future issues, I rewrote the logic so that now a custom message gets inserted using more regular `dom-if` templating and data binding.  I also adjusted the CSS to minimize the …
> Fix Debugger disabled dialog rendering logic

- .travis.yml
- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/tensor_helper_test.py
Re-enable Travis for Python 3.x, and use Python 3.6 since that's the most recent version TF supports.
> Re-enable travis testing for Python 3.6

- tensorboard/backend/application.py
I'm not sure why the py3 Travis tests didn't catch this on the original PR, but evidently this snuck through somehow.  I believe this is a false positive where the import order logic is apparently silly enough to decide that just because we're calling the import `urlparse` that makes it a standard library import, even though the actual package we're importing from is `six`.
Note that this only happens for py3 pylint, which is even weirder, since in python 3 `urlparse` is no longer even a package in the standard library, which is the whole point of that `six` import anyway...
> Suppress py3 pylint import order false positive

- tensorboard/version.py
We've cut the 1.7 branch, so head is now an alpha of 1.8.0a0.
> Bump version at HEAD to 1.8.0a0

- tensorboard/plugins/beholder/README.md
- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/beholder/file_system_tools.py
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
This change makes Beholder fail gracefully if it can't write a config file.  Previously the plugin attempted to write a default config file to the log directory as early as `__init__()`, so any error on writing the file (e.g. a permissions error on a read-only directory) would kill TensorBoard.
With this change, Beholder only attempts to write a config file if it's already determined that it should be active (i.e. if the `Beholder` class in the model code is writing data).  This ensures that users who aren't intending to use Beholder won't have their log directories written to at all, which avoids leaving "junk" in those directories and ensures that they won't be impacted by missing write permissions.
As a further convenience, we also rewire the Beholder frontend controls to accept a …
>  Make Beholder fail gracefully on non-writable config file

- WORKSPACE
It shouldn't be necessary to comment out unmirrored URLs since the downloader is able to workaround failures.
> Fix mirror URLs

- tensorboard/components/tf_tensorboard/registry.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
This will allow the Polymer 'detached' event to fire when navigating away from
certain plugin tabs, e.g. Beholder, thereby allowing timers and such to be
cleaned up.
> Add option to have dashboard DOM be removable

- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
- Navigating away from Beholder tab will now abort XHRs and clear timers.
- The "FPS" timeout is now throttled by how quickly the web server responds.
- Missing semicolons were added.
> Make Beholder be gentler on HTTP server

- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
This restores the 0 value minimum setting of the FPS slider, which is a documented Beholder feature that allows "pausing" the video generation.  See more in https://github.com/tensorflow/tensorboard/pull/1075/files#r177321183.
It adds logic to the tf-beholder-video and tf-beholder-info elements so that they don't send any XHRs when the FPS value is set to 0.
> Revert Beholder FPS slider to allow setting to 0

- tensorboard/plugins/text/text_plugin_test.py
Previously, text_plugin_test sometimes failed because #1021 made the test check for complete dictionary equality, and tags may appear in different orders for each test run. This fix makes the test check for equality of content within lists, regardless of order. This makes the test parallel previous test logic for tags.
Fixes #1072.
> Check for content of lists within text_plugin_test

- tensorboard/plugins/graph/tf_graph_common/render.ts
The logic for patching inputs to function nodes performs a scan across
metaedges (edges that encapsulate potentially numerous base edges) in
order to determine the correct metaedge to patch. Previously, this logic
had not taken into consideration how a metaedge could represent several
regular edges. This was problematic since the index pertained to the
collective number of regular edges (not metaedges).
This had caused an internal user's graph to fail to render. The graph
contained an edge into a series node within a function. The series node
caused several regular edges to be collapsed into one metaedge.
This change has been tested with that graph as well as other graphs that
make use of TensorFlow functions. The graph WAI.
This logic will be tested within internal integration tests for …
> Count regular edges while picking metaedge.

- tensorboard/components/tf_imports/BUILD
- tensorboard/components/tf_imports/closure.html
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
According to https://caniuse.com/#search=object.value this does not work in IE
or Chrome <=49 which is 0.82% of the global population. The Closure Library can
solve this problem.
See also: https://stackoverflow.com/q/49355552/1653720
> Remove Object.values()

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/io_wrapper_test.py
The io_wrapper module contains functionality related to file
system traversal that is important for TensorBoard. It should
have tests.
> Write tests for io_wrapper

- .travis.yml
Without this flag, Bazel basically builds the entire codebase twice. Once for
AMD k8 CPUs from 2003, and a second time for -march=native (host).
> Reduce build latency on Travis

- tensorboard/plugins/graph/tf_graph_common/externs.ts
- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
We add a `rankDirection` property to the `tf-graph-loader` component.
This property is passed to the dagre layout engine as the 'rankdir'
graph option. We hence let the user change which way the graph flows.
For instance, we can let the graph flow from top to bottom.
This PR is a small part of generalizing the graph explorer. This change
will be tested within internal integration tests.
> Let developer set rank direction for graph

- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/loader.py
Tensorflow's C API now will now raise this error using SWIG without having to raise it in explicitly in Python.
> Don't pass a status to _reader.GetNext()

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/directory_watcher_test.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_file_inspector.py
- tensorboard/backend/event_processing/event_multiplexer.py
- tensorboard/backend/event_processing/io_wrapper.py
- tensorboard/backend/event_processing/io_wrapper_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_multiplexer.py
Previously, TensorBoard found runs within the log directory by
performing a `tf.gfile.Walk` across directories. That turned out to be
very slow for users with expansive log directories (with many
subdirectories and files) because `tf.gfile.Walk` makes many calls at
the python level to C++ logic for reading data from disk (as opposed to
performing much of that logic directly at the C++ level). Disk reads can
be very costly for certain (such as remote and distributed) file systems.
We find runs (subdirectories) much more quickly by iteratively glob-ing
deeper and deeper directory levels. For a certain internal user, this
reduced the time it took to find all runs from 20 minutes to 20 seconds.
We already have tests that check whether the multiplexer correctly finds
subdirectories that are …
> Find runs by glob-ing levels of subdirectories

- tensorboard/backend/application.py
- tensorboard/plugins/audio/audio_plugin_test.py
- tensorboard/plugins/image/images_plugin_test.py
Previously, when the reload_interval flag was set to 0, TensorBoard
would reload the multiplexer once at the beginning of TensorBoard
startup on the main thread. Now, TensorBoard performs that reload on a
separate daemon thread. As comments note, this behavior prevents joining
threads that start while TensorBoard is reloading from blocking
TensorBoard from quitting after the user hits Ctrl + C.
This PR introduces a change in behavior. When the user starts a
TensorBoard with reload_interval set to 0 (no continuous reloading),
TensorBoard server starts up before all data is read from disk.
Previously, TensorBoard would read all events files (reload
multiplexers) before starting its server. A few tests were modified
accordingly.
Test Plan:
Start TensorBoard pointed at logs from …
> Always reload multiplexer on thread.

- tensorboard/plugins/profile/input_pipeline_analyzer/BUILD
- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/plugins/profile/overview_page/overview-page.html
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/profile_plugin_test.py
- tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
* Profile plugin is extended to take per host traces
* Added a host dropdown menu in profile dashboard
* Moved the _request_manager from each tool to tf_profile_dashboard, so that individual tool can be directly used by internal tools
* Add per host test in profile_plugin_test
> Extend the profile plugin to take per host profile traces

- WORKSPACE
- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
- tensorboard/defs/zipper.bzl
- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- third_party/polymer.bzl
This change fixes a regression that might have been introduced by a TypeScript
upgrade a few months ago, where Facets wasn't able to compile, possibly due to
tsc.js no longer adding .js to ES6 imports. The solution was to set module
resolution to NODE in the Closure Compiler. The Polymer dep was upstreamed for
more completeness for Facets.
This change also ensures that the development web server, when we `bazel run` a
`tf_web_library` or `tensorboard_html_binary` rule, will display sources in the
correct order we had originally, before Bazel changed from set() to depset().
r/cc: @jameswex
> Fix ES6 module resolution and polish build tooling

- tensorboard/components/tf_trace_viewer/BUILD
- tensorboard/components/tf_trace_viewer/tf-trace-viewer-helper.ts
- tensorboard/components/tf_trace_viewer/tf-trace-viewer.html
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/profile_plugin_test.py
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
trace viewer normally involve huge amount of data which browser can not
handle. streaming trace viewer use grpc to connect to a tpu profiler
analysis service to get small part of whole trace and display to user.
the amount of data depends on current view port (defined by a start and
end timestamp) and resolution (defined by zoom level).
currently the server reside on google owned virtual machine. there are
plans to open source those part.
to avoid confusing user, the patch is done in a backward compatible
fashion. user are expected to use old trace viewer (which limit the
event to 1 million), if the user specify the MASTER_TPU environment to
the IP address of the green VM, we will try to estabilish a grpc stub to
that IP:8466 port. only if stub is successfully connected we will use
new …
> support streaming trace viewer.

- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
- tensorboard/plugins/graph/tf_graph_controls/BUILD
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_node_search/BUILD
- tensorboard/plugins/graph/tf_graph_node_search/tf-graph-node-search.html
This change introduces a search box to the graph explorer that lets the user input a regex and then performs a partial regex match on all nodes (both metanodes and ops) within the graph.
When the user clicks on a match, the graph selects the node and pans to it if it is out of view.
Fixes #76.
> Let user search nodes by regex

- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
Previously, graph explorer logic made series nodes based on the last few digits of node names. This change generalizes that behavior to make series nodes based on any consecutive indices found within the names of nodes. This change enables an internal team seeking to generalize the graph explorer to move forward. Thank you to Chen Li for the generalization method.
The new logic for series collapsing may entail changes to existing behavior as well as performance. Therefore, we guard this behavior with a boolean hierarchy param called `useGeneralizedSeriesPatterns`. The graph loader component is now able to specify that boolean within its `overridingHierarchyParams` property.
> Generalize logic for computing series nodes

- tensorboard/plugins/pr_curve/pr_curve_demo.py
TensorFlow commits https://github.com/tensorflow/tensorflow/commit/083cf6b91a380641933457a4301f9b1efa13af92 and https://github.com/tensorflow/tensorflow/commit/daf0b206b5afde875a19270136ad22d9d2bb138c have made their way into `tf-nightly` build 254. The commits modified the behavior of the `tf.clip_by_value` op in an attempt to resolve https://github.com/tensorflow/tensorflow/issues/7225 in a way that minimizes memory usage by taking different pathways of logic based on characteristics of the system running TensorFlow. Unfortunately, our python 2 and python 3 setups on travis differ along those characteristics, causing the `tf-nightly` build to break `:pr_curves_test` (which relies on the demo to generate test data) for python 2 only.
This PR fixes the test by removing usages of …
> Make pr_curves_demo manually implement clip

- tensorboard/backend/application.py
- tensorboard/program.py
Add TensorBoard flag `samples_per_plugin` that allows for custom specification of samples to keep per summary type. 
Previously, TensorBoard always downsampled summaries for OOM reasons but some users wanted the ability to keep all their summaries of some types.
With this flag, --samples_per_plugin='histogram=2,images=0'
keeps TensorBoard defaults for other summaries, restricts the number of histograms to 2, and keeps all image summaries.
> Add --samples_per_plugin to specify explicit sampling counts

- tensorboard/plugins/debugger/tensor_helper.py
- tensorboard/plugins/debugger/tensor_helper_test.py
Related to: https://github.com/tensorflow/tensorboard/issues/1115
After this change, visualization of string-type tensors is
still not fully working, but at least the user can slice a
string tensor to a single element (i.e., a string scalar) and
see its value.
> [Debugger Plugin] Fix a bug in handling string scalar

- tensorboard/plugins/pr_curve/pr_curve_demo.py
Previously, #1132 had circumvented the use of `tf.clip_by_value` within the PR curves demo because it was buggy. However, that behavior seems to have been fixed. See https://github.com/tensorflow/tensorflow/issues/18527.
Hence, we make the demo use `tf.clip_by_value` once again.
> Use tf.clip_by_value again in PR curves demo

- tensorboard/plugins/beholder/beholder.py
- tensorboard/plugins/beholder/shared_config.py
This PR suggests to use a different summary key instead of using a default one for Beholder plugin.
Using Beholder plugin with `tf.estimator.Estimator` results in the following InvalidArgumentError.
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype uint8 and shape [?,?,?]
[[Node: Placeholder = Placeholder[dtype=DT_UINT8, shape=[?,?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
This is because `tf.estimator.Estimator` registers a loss scalar summary with a default collection key and merge it with the other summaries with the default key including Beholder's summary. As a result, we are required to feed `frame_placeholder` when running  a training op.
Since beholder writes summaries …
> [Beholder plugin] use different summary key to avoid merging with the other summaries

- tensorboard/plugins/pr_curve/pr_curve_demo.py
This addresses the root cause of the issue detected and originally addressed in #1132, per my description in https://github.com/tensorflow/tensorboard/pull/1150#pullrequestreview-115395956.
Pinning the random seeds makes the test robust to changes in the sequence of ops added to the graph prior to the `sample()` calls.  E.g. I tested this by confirming that with the previous code, adding `tf.constant(1)` after the `tf.reset_default_graph()` call but before the `sample()` calls - even if that constant op value was never used anywhere - caused a test failure.  With the pinned random seeds, adding/removing ops that should be functional no-ops doesn't affect the demo output and hence doesn't break the test.
The long-term fix, as the TODO describes, would be changing the PR curve test so that …
> Pin random seeds in PR curve demo for robustness

- tensorboard/plugins/graph/tf_graph_controls/BUILD
- tensorboard/plugins/graph/tf_graph_node_search/BUILD
We remove the statement that loads the
`tensorboard_webcomponent_library` symbol into the BUILD
file for the `tf_graph_node_search` component.
`tensorboard_webcomponent_library` is not used.
We remove an empty line from the BUILD file for the
`tf_graph_node_search` component.
We remove an un-needed dep from the tf_graph_controls BUILD
target.
The graph explorer's node search feature still WAI after this PR:
> Remove a couple un-needed lines

- README.md
Changes some FAQ wording to emphasize that GitHub issues should be primarily for actual TensorBoard bugs; not being able to load data is often a user-specific error or misconfiguration, and for those issues, self-driven debugging using `--inspect` with Stack Overflow as a fallback is a better option.
Fixes #815 by removing stale reference to a `--debug` flag that no longer exists (and where trying to pass it generates a confusing error).
> Update FAQ for TensorBoard not showing data

- tensorboard/defs/defs.bzl
- tensorboard/defs/vulcanize.bzl
- tensorboard/defs/web.bzl
It's an artifact of a rules_closure migration a while back. It's since been
renamed `closure_js_aspect`.
> Remove `legacy_js` Skylark stub

- tensorboard/program.py
I can never remember what the actual argument for logdir is.
Is it `tensorboard ./logs/`  ? 
Is it `tensorboard --logdir ./logs/` ?
Is it `tensorboard --log-dir ./logs/` ?
I feel like putting in an example just makes it really obvious.
Also with the version I am using (1.7),
`tensorboard --help` gives no useful information on this argument, so when it needed for details and examples is `tensorboard --helpfull`.
> Improve error message when logdir/db  not given.

- tensorboard/plugins/graph/tf_graph_controls/BUILD
- tensorboard/plugins/graph/tf_graph_node_search/BUILD
It should be possible to remove this rule bifurcation in a future change.
> Fix legacy definition of tf-graph-node-search

- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/beholder_plugin.py
- tensorboard/plugins/beholder/im_util.py
- tensorboard/util.py
This change does some code cleanup on Beholder to fix #1107, where invoking
TensorFlow routines caused a nontrivial amount of GPU to be reserved.
> Remove expensive plugin initialization code

- tensorboard/plugins/pr_curve/BUILD
This is a TF integration test that takes at minimum 30 seconds.
> Mark pr_curve test size as medium

- tensorboard/loader_test.py
When I run `bazel test tensorboard/...` it is complaining about `unsupported locale setting`.
Somehow on my machine `en_US.UTF-8` was installed but `en_US.utf8`.
I looked into the `loader_test.py` history and seems like we are skipping German locale test if it's not found, so I created this PR.
Env:
Tensorflow 1.8
Tensorboard 1.8
> Ignore en locale test if locale is not installed

- tensorboard/functionaltests/core_test.py
`bazel test //tensorboard/functionaltests:core_test`
- The `#logdir` element was renamed since `1.7.0`, it should be `#data_location`.
- If there is some data in log dir, TensorBoard doesn't have element `#data_location`, so waiting for this element causes timeout.
- If there is some data in log dir, seems like it takes few seconds (3 - 4 seconds) for the local server to get ready (see the screenshot below), so I ask it to wait up to 10 seconds before throwing timeout exception. If it finds the element will return it in 0 - 10 seconds. 
(Actually 6 seconds works just fine for me, but I am not sure it it's the same on other machines, so I put 10).
Result:
Any suggestion is appreciated!
> Update selenium tests

- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
- tensorboard/plugins/debugger/interactive_debugger_server_lib.py
- tensorboard/plugins/debugger/tensor_helper.py
- tensorboard/plugins/debugger/tensor_helper_test.py
- tensorboard/plugins/debugger/tensor_store.py
* Binary strings (strings that cannot be encoded in JSON, as is the case
with output tensors of Summary ops) are now converted to a printable
format using Python's `binascii.b2a_qp()`.
* To prevent overloading the frontend and frontend-backend
communication, long string elements are truncated at 40 bytes.
* Display dtype 'object' as 'string' for clarity.
> [Debugger Plugin] Fix bugs related to binary string tensors

- .travis.yml
- tensorboard/plugins/pr_curve/BUILD
Yesterday we helped fix TensorFlow's C++ ABI regression fixed in `tf-nightly`. I'm curious if it impacts 1.8 final.
> Pin 1.8 branch to TensorFlow 1.8.0 final

- tensorboard/plugins/profile/profile_plugin.py
if not specified, all hosts' data will be aggregated.
> populate host in data request, so the server can filter based on host.

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
The graph visualizer omits nodes of certain types (e.g., the ones
associated with TensorBoard summaries), e.g.,
'layer2/biases/summaries/mean/tags'. When the debugger plugin
steps to such nodes and attempts to focus the graph visualizer on
the nodes, errors will occur.
This PR fixes this issue by more thoroughly checking whether the
node is omitted by the graph visualizer before setting its
'selectedNode' property.
> [Debugger Plugin] Guard against nodes omitted by Graph visualizer

- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/main.py
Sets an environment variable before the first import of tensorflow that disables the TF GCS filesystem cache, which interacts pathologically with the pattern of reads used by TensorBoard for logdirs.
See #1225 for the full context.
> Opt TensorBoard out of tf.gfile's GCS filesystem caching

- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
- tensorboard/plugins/profile/tf_op_profile/utils.ts
Add a bar indicates how much memory is utilized for each Hlo Ops.
> Add memory utilization bar in op profile.

- tensorboard/backend/event_processing/plugin_event_accumulator.py
...by returning a copy of the underlying tag-to-content dict for that plugin, and using a set of per-plugin locks to protect against simultaneous addition of keys to that dict.
Fixes #1201.
> Fix race condition in PluginEventAccumulator.PluginTagToContent()

- tensorboard/plugins/profile/memory_viewer/buffer_details/BUILD
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.html
- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.ts
- tensorboard/plugins/profile/memory_viewer/memory_usage/memory-usage.ts
- tensorboard/plugins/profile/memory_viewer/memory_viewer_dashboard/BUILD
- tensorboard/plugins/profile/memory_viewer/memory_viewer_dashboard/memory-viewer-dashboard.html
- tensorboard/plugins/profile/memory_viewer/mv_line_chart/BUILD
- tensorboard/plugins/profile/memory_viewer/mv_line_chart/mv-line-chart.html
- tensorboard/plugins/profile/memory_viewer/mv_line_chart/mv-line-chart.ts
- tensorboard/plugins/profile/overview_page/overview-page.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
* Added charts and interactions of memory viewer.
* Shows up a buffer details card when mouse hovering over a buffer allocation.
* Fixed a bug that overview page doesn't align correctly horizontally.
> Add line charts for memory viewer tool

- tensorboard/plugins/profile/memory_viewer/mv_line_chart/mv-line-chart.ts
* Clears the previous chart components when rendering again.
* Redraw the chart when the tool is attached. Sometimes, the data change happens before the tool is attached, so that the renderTo function couldn't be applied.
> Fix a bug that the line chart doesn't redraw correctly.

- tensorboard/version.py
We've cut the 1.9 branch, so head is now an alpha of 1.10.0a0.
> Bump version at HEAD to 1.10.0a0

- tensorboard/pip_package/build_pip_package.sh
@martinwicke mind taking a look since Justine is OOO?
This fixes a line I added yesterday that doesn't work on our `tb-nightly` build machine, where apparently `/bin/sh` isn't just an alias to `bash`.
> Remove use of non-portable [[ in build_pip_package.sh

- tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
- tensorboard/plugins/profile/overview_page/overview-page.html
Input Pipeline Analyzer:
The pie chart in input_pipeline_analyzer is occasionally missing due to two reasons:
(1) When -0.00 is present in the input JSON.
(2) Try to render the pie chart when DOM is not ready.
Fix these two issues and also refactored the code for better performance.
Overview Page:
Fix the 'node' not found error. Need to use dom-if so that isn't a hidden line chart from another RUN.
> Fix a bug that pie chart in input_pipeline_analyzer is missing

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
A couple fixes to get raw sources mode working for the full frontend component, so that `bazel run tensorboard/components:tensorboard` produces a working raw-source frontend.
In raw sources mode, `goog.require('goog.object')` fails on a missing `goog` symbol and it wasn't clear how to fix it, so since that was only present for `values()` which is also provided by lodash, an existing depedency, I just changed it to `_.values()`.  I also fixed an issue where when the dashboard stamping logic got confused by a comment node, which in raw sources mode doesn't get stripped.
The raw-source frontend at `bazel run tensorboard/components:tensorboard` doesn't include any demo data by default, but it can be paired with data endpoints from a running TensorBoard backend on another port (e.g. 7006) by …
> Fix raw sources mode for full frontend component

- tensorboard/plugins/profile/memory_viewer/buffer_details/buffer-details.html
- tensorboard/plugins/profile/memory_viewer/utils/utils.ts
- tensorboard/plugins/profile/memory_viewer/xla/shape.ts
Fix a bug that memory_viewer is broken because XLA newly added a 'TOKEN' primitive.
> Fix memory viewer due to minor compiler changes.

- tensorboard/plugins/profile/tf_profile_common/BUILD
- tensorboard/plugins/profile/tf_profile_common/tf-profile-common.html
- tensorboard/plugins/profile/tf_profile_common/util.ts
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Add a progress bar to TPU profile plugin. It is needed when the input tool data is large, and takes a long time to fetch from GCS.
> Add a progress bar to TPU profile plugin.

- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
When using multiple runs with the same custom scalar layout, tensorboard will duplicate the charts for every run.
This PR fixes the problem by deduplicating the charts before adding them to the category.
> Fix custom_scalar displaying duplicated charts

- tensorboard/components/tf_dashboard_common/dashboard-style.html
- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/components/tf_dashboard_common/tf-option-selector.html
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-smoothing-input.html
- Width is now fixed (and is variable to vw)
- All slider are styled the same
- Margin and padding of content in the sidebar the same
- Made few elements respond better to variable width
> Make sidebar consistent across all plugins

- tensorboard/http_api.md
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
/data/experiments now return all runs and tags in it.
> Experiments endpoint now returns nested data

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
As a follow-up to #1296, this removes a style rule for the `.center` div for the custom scalars dashboard that was inconsistent relative to the to other dashboards (in particular, the scalars dashboard).  The rule added extra padding within that div, causing the custom scalars category panes to be shifted rightward relative to their position in other dashboards.  With the rule removed, the alignment is now consistent.
> Remove inconsistent custom scalars center-div styling

- tensorboard/version.py
We've cut the 1.10 branch, so head is now an alpha of 1.11.0a0.
> Bump version at HEAD to 1.11.0a0

- tensorboard/components/tf_backend/experimentsStore.ts
- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.ts
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/experiment-selector.html
- tensorboard/components/tf_data_selector/experiment-selector.ts
- tensorboard/components/tf_data_selector/storage-utils.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
While working on it, it alos adds,
- Refactored filterable-checbox-list to allow title and subtitle
- Factored out experiemnt selection from tf-data-selector
What is missing in this commit:
- piping data selection to a plugin
- data-selector-row removal
> Persisted experiment, run, and tag selection

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
The change should have zero visual change but general scroll performance improvement.
As depicted in picture below, we want larger DOM elements to be in separate GPU context and simply GPU rasterize when there is a repaint required in it. Without the orange boxes around each graph, a change in DOM structure will cause a reflow in entire page causing poor rendering performance in general.
> Put large elements under separate GPU context

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
Below are addressing concerns on #1302:
- Added comments on why prune is required when item changes
- Specified persistence-number to the tf-data-select-row
- Added TODO for compute method
> Improved readability of tf-data-selector

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
This fixes the issue where, when content is smaller that the parent height, it showed double scrollbar when tooltip renders.
> Bug fix: content now takes up whole height

- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
> Prevent 404 on src on Firefox

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Now, the data flows properly from the data-selector to the plugins
that uses the data selector.
> Connect data-selector to tf-tensorboard

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/experiment-selector.html
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
This feature allows user to easily toggle a data selection group
or remove the group entirely from the comparison.
> Adds checkbox and remove button on data-select-row

- tensorboard/components/tf_paginated_view/paginatedViewStore.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_storage/test/storageTests.ts
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- Polymerized API handles empty value and default values well. We now
expanded the API to allow for that.
- Refactored the API to have named option argument
Specifically, the setter now removes the key from the hash when a value matches the defaultValue.
> Refactored storage for get/set to be more powerful

- tensorboard/components/tf_backend/type.ts
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
When a run comes from the logdir data source, it does not have an id.
Fixed the type and data selection when the id is missing.
> Fixed the noExperiment data selection

- tensorboard/components/tf_dashboard_common/BUILD
tf_dashboard_common is using more verbose version,
@org_polymer_iron_icon//:org_polymer_iron_icon, and it can be shorter
with @org_polymer_iron_icon.
> Refactor: Use shorter notation for @org_polymer_iron_icon

- tensorboard/components/tf_line_chart_data_loader/BUILD
- tensorboard/components/tf_line_chart_data_loader/data-loader-behavior.ts
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
- tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
The loader, previously, was very geared towards runs and tag
combination which can be generalized a little bit. 
Also, while working on this, I factored out the loading logic out of 
the line-chart-data-loader as a reusable behavior and, now, the
line-chart-data-loader is responsible for redrawing the chart.
> Refactor: Pass arbitrary data to line-chart-data-loader

- WORKSPACE
Bazel 0.16 comes with java 1.9, which doesn't have javax/annotation/Generated,
which dagger 2.9 needed.
rules_closure 0.8.0 updates its dagger deps to 2.14.1, which resolves
the issue.
> Fix the build for bazel 0.16.

- tensorboard/components/tf_backend/type.ts
- tensorboard/components/tf_categorization_utils/BUILD
- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/test/categorizationUtilsTests.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/http_api.md
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
The utility divides the data, based on selection, into
tag prefix and tags. After those division, it does not make
assumption about how the data is used and returns list of
experiment/run pair that matches the criteria.
> Added categorization for data_selector.Selection

- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/components/tf_data_selector/type.ts
- tensorboard/components/tf_line_chart_data_loader/data-loader-behavior.ts
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
When using data selector experiment, scalar plugin now uses
the selectionCategory to populate the items.
The change that is not backwards compatible is the name of the
every row in the tooltipe has prefix of "default/" in all cases.
> Integrate selectionCategory to scalar plugin

- tensorboard/BUILD
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/vz_chart_helpers/vz-chart-helpers.ts
- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/plugins/graph/tf_graph/tf-graph-scene.html
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/layout.ts
- tensorboard/plugins/graph/tf_graph_common/render.ts
- tensorboard/plugins/graph/tf_graph_common/template.ts
- tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
- tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
- third_party/js.bzl
- third_party/typings.bzl
- Lodash renamed `pairs` to `toPairs`.
- `sortedIndex` renamed to `sortedIndexBy`
Unfortunately, type information lacks reference to the new ones
so we wrote the POJO version of these utilities at least for now.
> Cleanup: Upgrade lodash and plottable

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
As part of multi-experiment effort, tf_scalar_card recently added
experiment name in the data series with slash. It wrongly pruned the run
name with slash and caused look up to fail.
> BUG: Fixes run name coloring lookup failure

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
Fix the issue where `categorize` returned more runs than what `createTagToRuns` contain.
> BUG: JSE when toggle on/off runs

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
Previously, every keydown in regex input caused the plugin to redraw and it was very CPU intensive (not forgetting to mention network request initially). 
Try to cause least amount of redraws.
> Debounce data-selection change for performance

- tensorboard/components/tf_globals/globals.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
URL storage uses two mediums when bootstrapping -- before the TB
application is up, it uses fake hash, then it uses the real URL hash.
This is done for test predictability.
Since whether to use data selection or not is related to the
experiment control and not storage of some user data, we decided to use
the query parameter instaed.
> Use QueryParam for data selector config

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/test/categorizationUtilsTests.ts
Previously, the series was populated based from `tagToSeries`
which contains all tags in the experiment/run combination regardless
of the tagRegex.
This resulted in very confusing UI as search pane showed a series,
experiment/run/tag tuple, that is supposed to be omited based on
tagRegex criteria.
> BUG: omit tag from selection based on tagRegex

- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- Tooltip header related code was deleted at cb5a8ca
- When finding closest points in dataset, it did not account for zero
length array
> Bug fix: tooltip header and JSE

- tensorboard/components/tf_backend/type.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Data-selection can be easily toggled on/off without having to remove or
insert a new data grouping for comparison by simply clicking on the
checkbox on each row.
Now, the `selection` from `tf-data-selector` will honor the toggle
state of each selection row.
> Toggle data-selection-row with toggle button

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/test/categorizationUtilsTests.ts
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
- tensorboard/plugins/scalar/scalars_plugin_test.py
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Now that selection is populated and categorized by the scalar plugin, it now needs to
filter out scalar values based on the experiment id. 
About test: although not calling implementation method is the preferred way in general,
I decided to honor established pattern at least for this change.
> Filter scalar values based on optional param `experiment`

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- Tooltip sorting method change did not take effect in tooltip drawing.
d3 requires `order` call to make DOM order the same way as the data is
orderd.
- Chart domain update: data-loader-behavior has changed its properpty
name but the change was not reflected in the tf-line-chart-data-loader.
> BUG: fixed tooltip sorting and chart domain update

- tensorboard/components/tf_line_chart_data_loader/data-loader-behavior.ts
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/tf_tensorboard/tf-tensorboard.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- Experiments did not have the right unique ID for fetching because,
even in the multi experiment mode, `this` was pointing at the wrong
instance.
- Fixed the issue where chart did not create when toggling visibility
with the tag header
- Fixed the issue where data-loader fetched incomplete selection in the
beginning due to the timing issue. Data-selection was bootstrapping
from the storage and it changes the output rapidly. Without debounce,
data-loader starts to fetch and it causes timing issue.
- Set dataSelection only when a dashboard requires it.
> BUG: Fixed chart rendering issues

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/components/tf_categorization_utils/test/categorizationUtilsTests.ts
- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- When no selection has a regex search, keep the name as an enpty string
- Report malformed regex
Also fixed the broken tests that were not caught by Travis.
- Show that compositeSearch has invalid regex
> Improved categorizeSelection for search

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Polymer observer fails silently when not all properties are initialized.
The PR also addresses the bug where "runs to download" dropdown was not properly populated.
> BUG: fix the scalar plugin for experimentless src

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
When not comparing experiments and only selected one experiment, color
the run checkbox lists like the runs-selector.
> Colors run checkboxes in data-selector

- tensorboard/components/tf_backend/baseStore.ts
- tensorboard/components/tf_backend/environmentStore.ts
- tensorboard/components/tf_backend/experimentsStore.ts
- tensorboard/components/tf_backend/runsStore.ts
- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
When removing an experiment, because of debounce and asyncness,
selection that has been removed gets reinserted to the list of
selection. This is fixed by removing the debounce and making the higher
order component, data-selector, emit-less change when data does not
change. Also, it added some safeguard where we ignore events from a
removed experiments.
Also, we now populate the internal state of `_dataReady` correctly.
> Fixed the zombie selection bug

- tensorboard/components/tf_data_selector/experiment-selector.html
- tensorboard/components/tf_data_selector/experiment-selector.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
When backend is in DB mode, it will require user to make a selection
based on experiments even if one does not want to compare experiments.
Previously, when no experiment was chosen, we had a fallback to original
runs selector (not ID-based) with tag input.
Now that we require user to make selection based on experiments, there
is an awkward UI state in case of cold start (nothing is chosen and "add
comparison" button shows up without a clear affordance). To alleviate
this problem, we now expand the experiment selector when nothing has
been chosen without an ability to minimize the experiment selector.
> Make data-selector aware of backend mode

- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/components/tf_storage/BUILD
- tensorboard/components/tf_storage/listeners.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_storage/tf-storage.html
Say there were two selection: A and B. When removing A, Polymer does not
remove DOM for A but, rather, one for B. As a result, A will be updated
with parameter of B and it will need to be reinitialized including
binding to the storage.
When updated, not only should it refetch the list of runs, but also needs
to detach event listeners with the previous storage keys. If not done,
any change in hash will trigger the callback and set the value
incorrectly.
> BUG: make select-row update when shifted

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Series title needs to update based on whether user is comparing multiple
experiment or not. However, changing the name, which was previously used
as an id to LineChart class, caused various issues. Instead of changing
the name depending on setting, we now set the TitleGetter.
> REFACTOR: make series name separate from title

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/core/core_plugin.py
This ensures that `tensorboard --logdir ~/logs/dir1,~/logs/dir2` works.  The call to expanduser() only does anything if the tilde is the first character in the path, so previously this only would have expanded correctly for the first component of the multipart logdir spec.
> BUGFIX: Call expanduser() for multi-part logdir components

- tensorboard/components/vz_chart_helpers/vz-chart-helpers.ts
A step is a discrete entity, not a contiguous one. Plottable, without a
custom tick generator, tries to generate predefiend number of ticks
which can result in decimal ticks when domain is small enough.
Instead, we now show only ticks on integer values.
> Show only integer ticks in stepAxis

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/backend/event_processing/event_file_loader_test.py
- tensorboard/db.py
- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/scalar/scalars_plugin.py
This PR adds a DbImportMultiplexer class which is essentially a version of EventMultiplexer that only implements the data loading API (i.e. `AddRunsFromDirectory()` and `Reload()` methods).  Rather than exposing data through the read API methods, it loads the logdir data into a SQLite DB using the `tf.contrib.summary.create_db_writer()` and `tf.contrib.summary.import_event()`, such that the DB can then be read by the plugins which have been adapted to support DB query mode.
This multiplexer is used for on-the-fly logdir loading when the `--db_import` flag is passed.  By default, it uses a temporary DB file under `/tmp/` that is cleaned up on exit, but if the `--db` flag is passed then it will import the data into a DB file at that path or create a persistent file if no DB exists.  The …
> Add experimental --db_import for on-the-fly import of logdir to DB

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
As part of refactor, the categorization now returns series instead of tag and runs. This broke `_tagMetadata` not to be invoked by Polymer.
Also, the change trims scalar card title if it matches prefix.
> Fixed scalar card header description bug

- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.ts
- tensorboard/components/tf_data_selector/tf-data-selector.ts
- tensorboard/components/vz_line_chart2/line-chart.ts
When list of runs changes, runsScale remaps runName to color. The
change has to be reflected by UI but tooltip or run selector dropdown
reflected the color change.
The change addresses the bug described above but the change is not
final -- a runsColorScale change is picked up by components that also
listens to change of the runsStore, but this is by luck and not design.
RunsColorScale which currently is a function of runs in the runsStore
should emit change separately and componennts should not be aware of
this dependency when consuming the color. The fix does not address this
issue and tf-data-select-row currently has an issue because it does not
listen to the runsStore.
> FIX: Recolor when color scale changes for run

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
When using paginated to scroll through charts quickly, you will trigger
the chart creation (which is debounced for 350ms). The chart creation,
even if it is no longer in foreground ("display:none"d), it will draw and result
in a shrunken line-chart. There is a bad draw detection logic to remedy the
problem, but it did not account for the debounce logic in the line-chart.
To mitigate the problem, we now listen to on Plottable.Component#onAnchor
event to known when a chart is mounted on DOM and know when a drawn
happened while it was in the background.
Alternatively, we can cancel the chart creation debounce by either creating
a new state in chart, `active`, or a method `cancelMakeChart`.
> FIX: line-chart is rendered properly (no-shrink)

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Recently (#1402), we made how `_categories` is updated to leverage better dom-repeat and it broke the data-selector.
> Fix categorization for data selection

- tensorboard/components/tf_dashboard_common/array-update-helper.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.html
- tensorboard/components/tf_data_selector/tf-data-selector.ts
We recently introduced a helper mixin for dom-repeat that updates an
Array property in a way compatible with Polymer v1. The change
incorporates the mixin to the data selector which nicely removes
crufts.
> CLEANUP: use array-updater in tf-data-selector

- tensorboard/main.py
cc @jameswex 
This fixes an issue with my #1409 PR where on absl-py < 0.4.0, app.run() would fail with an unrecognized keyword argument instead of correctly falling back to the non-app.run() execution mode.
> Guard use of absl.app.run(flags_parser=??) with import check

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Since PR #1404 changed the main tensorboard_html_binary() to pass compile=True to Vulcanize.java, opening the Chrome devtools causes the TensorBoard command to emit two unexpected 404 warnings for missing sourcemap files as follows:
```
W0911 15:58:29.992902 Thread-3 application.py:300] path /web-animations-next-lite.min.js.map not found, sending 404                              
W0911 15:58:30.172698 Thread-3 application.py:300] path /weblas.map.json not found, sending 404                                                                                                                                                                      
```
This is because the compile=False path of Vulcanize.js strips out the sourceMappingURL comments but the compile=True path did not.  Now they both …
> Make Vulcanize strip sourcemap URLs even when compile=True

- tensorboard/BUILD
- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/storage-utils.html
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-selector.html
This fixes a breakage in the data selector when compile=True is used for tensorboard_html_binary, as was done for PR #1404.  For some reason, the vulcanization logic stopped inlining storage-utils.js properly.  This resulted in a later build error from building //tensorboard:assets (which was just suppressed to a warning by #1404):
```
INFO: From Checking webfiles //tensorboard:assets:
WARNING: bazel-out/k8-fastbuild/bin/tensorboard/components/index.html: Referenced storage-utils.js (/storage-utils.js) without depending on a web_library() rule providing it
```
But by ignoring this, at runtime, storage-utils.js can't be loaded, resulting in 404s and a broken data selector.
The way I fixed this was by adding a storage-utils.html "shell" file and then referencing that via HTML imports rather …
> Fix broken storage-utils.js reference for data selector

- tensorboard/program.py
__name__ is an undefined name in this context.  __flag.name__ is used in the __if__ statement on the line above.
[flake8](http://flake8.pycqa.org) testing of https://github.com/tensorflow/tensorboard on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorboard/program.py:159:60: F821 undefined name 'name'
raise ValueError('Conflicting Abseil flag: %s' % name)
^
1     F821 undefined name 'name'
1
```
> Undefined name: 'name' --> 'flag.name'

- .travis.yml
- tensorboard/__init__.py
Automatically detect issues like #1417
Use [flake8](http://flake8.pycqa.org) to look for Python syntax errors or undefined names on both Python 2 and Python 3.
__E901,E999,F821,F822,F823__ are the "showstopper" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc.  Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.  This PR therefore recommends a flake8 run of these tests on the entire codebase.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable `name` referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
@nfelt
> Travis CI: Python syntax errors or undefined names 

- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector.ts
1. Fix the issue where run name contains comma
Run names, when using non-DB mode, can contain random characters and we
need to use the delimiter that is unique. Instead of "," which can be
part of the run name, we now serialize the list of run names using JSON.
stringify.
2. Fix the issue where runs are incorrectly colored
Fix the bug where data selector incorrectly colors the runs in the
filtered run selector list. The bug happened because of incorrect
complex observer: we now update the `experiments` array instance
instead of setting a new array instance onto the property.
> FIX: two bugs with the data selector

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
In scalars plugin, the category panes were expanded/collapsed if index
is less than 2. This made, if categories list changed, panes to reopen
even if it was explicitly disabled.
Now, we expand top 2 panes only when user has no pane  expanded or
collapsed panes explicitly.
> Expand pane when no panes are user controlled

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
We now place the injected overview above the data-selector and allow the
content to adjust height correctly when injected-overview takes non-zero
height.
> Fix scroll issue when overview is injected

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_chart_helpers/BUILD
- tensorboard/components/vz_chart_helpers/vz-chart-tooltip.html
- tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Chart tooltip (or all popovers) should render at the body level in order
to prevent clipping from a scrollable area. To be more specific, even
position:fixed can get contained inside a region if it is within a
scrollable region. As a remedy, most tools render popover in children of
body.
To achieve this in a component structure, there are two competing goals:
1. intuitive component structure (tooltip is a subcomponent chart)
2. DOM-wise, tooltip should not be nested in chart but should be at body
level.
Libraries like React allows such pattern via "tunneling". By manually creating 
an element in the body, we emulated the behavior.
In this commit, we:
- introduced vz-chart-tooltip that knows how to position
- applied the new tooltip to scalar-card
- introduced new positioning, "auto"
> REFACTOR: mv tooltip container out of scroll area

- tensorboard/program.py
This rewrites the WerkzeugServer wrapper introduced in #1409 to eliminate some issues with the old approach to IPv4/v6 handling and in particular fix #1320.  Gory details are in https://github.com/tensorflow/tensorboard/issues/1320#issuecomment-423364207
This change also streamlines the class so that it now directly inherits from Werkzeug's ThreadedWSGIServer class, which gives us a `serve_forever()` implementation for free and cleans up the `handle_error()` behavior so it's an overridden method instead of monkey-patched.
Fixes #1320
> Rewrite WerkzeugServer for better IPv4/v6 handling

- tensorboard/components/tf_categorization_utils/categorizationUtils.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
This reverts the new behavior introduced as part of #1324.
It used to remove pane that has no matching tag/run.
> Revert category pane behavior to 1.10

- tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
alt collides with some linux window manager's default behavior.
> Remapped alt key for line-chart pan to shift

- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
With tf-line-chart-data-loader refactor which now takes `dataToLoad`
separately from `dataSeries` (latter defines series that are to be drawn
onto the chart whereas the former defines data requirement), the custom
scalar plugin broke because it failed to take run selection when setting
the `dataSeries` property.
The change also addresses the issue where smoothed series do not show in
fade.
> FIX: custom scalar now reacts to run selection

- tensorboard/plugins/image/images_plugin.py
If known image detection fails, and if the beginning of the data is either XML or SVG header, then set mimetype to image/svg+xml.
> Make image plugin to attempt to detect SVG types

- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/plugins/core/core_plugin.py
This adds an experimental `--reload_task=auto|thread|process` flag to allow running the reloading logic in a child process rather than a background thread, to work around the `--db_import` issues on macOS described in #1467.  Now by default, a process will be used when `--db_import` mode is active, and a thread otherwise (the process version isn't useful with regular logdir importing, since the data would be imported into the child process's EventMultiplexer instance only).
cc wicke@
> Add ability to run reload logic in a child process

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
ES6 modules are incorrectly considered moochers right now. Once this is fixed in the compiler the vz-example-viewer file will be moved after its use. Nothing imports it directly, so the compiler thinks its can move it later (it will put moochers before explicit entry points).
A moocher is something that is not importable, e.g. has no `goog.provide` or `goog.module` statements and is not an ES6 module and thus can never be `goog.require`d or `import`d. Moochers with `setMoocherDropping(false)` are considered entry points (why else would they be input?).
> Turn off dependency pruning

- tensorboard/components/tf_categorization_utils/tf-category-pane.html
It looks like #1465 removed this inadvertently?  I'm assuming the intent was to leave it customizable on a per-plugin basis, and just set restamp=false for the histogram dashboard.  Without restamping, we hit the chart shrinking bug (#1473) every time we reopen a pane where the charts were redrawn while closed (e.g. due to changing run selections, for example).
> Restore tf-category-pane restamp functionality

- tensorboard/components/tf_storage/listeners.ts
- tensorboard/components/tf_storage/storage.ts
- tensorboard/components/tf_storage/test/storageTests.ts
localStorage change event does not get triggered when a change is made
within the tab. This lead to very subtle bug where a change in value did
not propagate to another already mounted plugins.
> Propagate storage change to intra-tab listeners

- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/tf-collapsible-data-selector.html
- tensorboard/components/tf_data_selector/tf-collapsible-data-selector.ts
- tensorboard/components/tf_data_selector/tf-data-selector-advanced.html
- tensorboard/components/tf_data_selector/tf-data-selector-advanced.ts
- tensorboard/components/tf_data_selector/tf-data-selector-simple.html
- tensorboard/components/tf_data_selector/tf-data-selector-simple.ts
- tensorboard/components/tf_data_selector/type.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
For most of the user, data-selector-alt is the appropriate UI while
data-selector is more appropriate for more advanced user who wants to
fine tune what to compare.
Instead of TB deciding what to display, we now make use of both of them
with a simple toggle button to toggle between two modes.
> Created modes to data selector

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/BUILD
- tensorboard/components/vz_line_chart2/line-chart-exporter.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Motivation: TB should give ability to save line chart as high quality
SVG.
Right solution: Modify Plottable to draw in one SVG with grouping
instead of multiple SVG fragments.
Problem: SVG creation is scattered and it may require a lot more effort
to understand design choice around these fragments (may require dynamic
creation of clipPath for masking a part of a figure)
Current solution: Parse the Plottable drawn DOM and generate one SVG out
of the DOM snapshot
Shortcomings:
- X-axis label may take up larger than required space
- There are no labels to each line (should give an option when
exporting)
This may require few iteration to constitute as done.
> Export current line chart as SVG

- tensorboard/plugins/projector/vz_projector/data.ts
When closure compilation is turned on, it uses prototype definitions to
mangle and optimize the calls. This made some method not defined
statically problematic and it seems to have turned `numeric.div` into
something else.
According to numericjs, unlike other methods we use like dot and
transpose, is genearted dynamically from numeric.ops2 and Closure seems
to not handle it well.
https://github.com/sloisel/numeric/blob/master/src/numeric.js
Concretely, it turns numeric.div(a, b) into mangledName(numeric, a) and
this led division operation to infinitely loop.
```
c = d.slice(0, a.PCA_SAMPLE_SIZE);
c = Oa(numeric, numeric.dot(numeric.transpose(c), c));
var e = numeric.svd(c)
```
In above code snippet, `Oa` is the `div` method.
Fixes #1480
> Fixed the Projector infinite loop issue

- tensorboard/backend/BUILD
- tensorboard/backend/application.py
- tensorboard/backend/application_test.py
- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/backend/event_processing/sqlite_writer.py
- tensorboard/plugins/core/core_plugin.py
This adds new python sqlite ingestion logic as an option for DbImportMultiplexer, as contrasted with the preexisting logic which uses TensorFlow's C++ SummaryDbWriter and the ImportEvent op (via their python bindings).  The new logic is now the default, but the old logic can be activated with `--db_import_use_op`.
There are several components to the PR:
- Reimplementation of DbImportMultiplexer.Reload(), which now supports multithreading.  RunImporter is replaced with RunLoader that emits events in batches (hardcoded for now to use the lesser of 5000 events or 1 MB), and these batches are channeled from worker threads through a Queue to an EventSink running on the main thread.
- EventSink has two implementations, ImportOpEventSink with the old logic, and SqliteWriterEventSink with the new …
> Implement DbImportMultiplexer python sqlite ingestion logic

- tensorboard/components/tf_categorization_utils/tf-tag-filterer.html
- tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Polymer's complex observer require values it listens to be instantiated.
`tagFilter` was previously removed because tf-tag-filterer took the
value from its parent instead of bootstrapping from the storage.
This change ensures that complex observers are properly set up with all
listed properties instantiated and to take all consumed properties in
callback to be listed in the observer definition.
> Fix observers when using data selector

- tensorboard/components/vz_example_viewer/vz-example-viewer.html
When connecting to Tensorboard with a Firefox browser, the following errors are
seen in the console window:
path /[[getImageSrc(feat.name)]] not found, sending 404
path /[[getCompareImageSrc(feat.name)]] not found, sending 404
path /[[getSeqImageSrc(seqfeat.name, seqNumber)]] not found, sending 404
path /[[getCompareSeqImageSrc(seqfeat.name, seqNumber)]] not found, sending 404
Similar errors were resolved in:
https://github.com/tensorflow/tensorboard/pull/1315/files
Repeating that process for these errors resolves this issue.
> Fix 404 errors when using Tensorboard with Firefox

- tensorboard/backend/event_processing/sqlite_writer.py
- tensorboard/plugins/image/images_plugin.py
Fixes a bug in #1486 with stringifying non-scalar tensor shapes, and also fixes a latent issue in the images plugin SQL tag-finding query causing it to skip tags with no description (and the python DB import logic doesn't currently populate any descriptions).
The images plugin still doesn't work even with this fix, because it looks for image summary data in TensorStrings, which the python DB import logic doesn't currently populate either.  But at least it shows the detected tags.
> Fix issues with python DB import logic and non-scalars

- tensorboard/main.py
I tested this by profiling loading a file of 100,000 scalar summaries.  With python protobuf, the protobuf library calls dominate the profiling stats.  With the C++ implementation, these calls drop much lower in the ranking, and the file loads twice as fast.
> Enable fast C++ implementation of python protobuf

- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
Cause: `ignoreYOutlier` instead of `_ignoreYOutlier`
It has always had wrong property value since #664.
> Connect ignoreYOutlier in custom scalars

- tensorboard/components/tf_line_chart_data_loader/data-loader-behavior.ts
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
Please refer to #1499 for details.
The observer to the `loadKey` change was not triggered even when it
changed. Weirdly, the complex observer for `dataToLoad` was triggering
fine.
Due to the issue, the line-chart appeared stale even when its tag/run
pair has changed.
> FIX: data-loader now responds to loadKey changes

- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
Repro step:
1. Open TB in scalar dashboard
2. Type something into tag filter
3. Navigate to audio dashboard
4. See nothing <- bug
The regression was caused by #1475 which has broken the Polymer
complex observer.
> Fix broken audio dashboard with tag filter

- tensorboard/components/tf_categorization_utils/tf-category-pane.html
- tensorboard/components/tf_line_chart_data_loader/data-loader-behavior.ts
Also fixed the issue where, when showing the spinner, the iron-collapse
does not always open. Note that this collapse bug did exist in version
1,10 too,
> Fixed to show spinner on data load

- tensorboard/components/tf_data_selector/storage-utils.ts
- tensorboard/components/tf_data_selector/tf-data-select-row.ts
- tensorboard/components/tf_data_selector/tf-data-selector-advanced.ts
- tensorboard/components/tf_data_selector/tf-data-selector-simple.html
- tensorboard/components/tf_data_selector/tf-data-selector-simple.ts
Simple data selection was not connected to the storage for brevity of
the code review. Now, all field are appropriately connected to the
storage.
> Persist simple data selection to storage

- tensorboard/defs/web.bzl
- third_party/clutz.bzl
Corresponds to internal change cl/216429546.
> Update clutz.bzl to use deprecated symbol naming expected internally

- tensorboard/components/tf_categorization_utils/tf-tag-filterer.html
tf-tag-filterer, correctly, defined its property `tag-filter` as
readOnly and this broke the data connection between `paper-input`.
Between the paper-input and the filterer, there should be a
two-way binding of its value whereas all the consumers of the
tf-tag-filterer should only read from the component.
Now, using the private property, `_tagFilter`, we establish the two-way
binding while the public property is only used to publish the change.
Note: bug was introduced over #1483, #1475, and #1493.
> Fixed tagFilterer to correctly bootstrap and work

- tensorboard/components/tf_tensorboard/autoReloadBehavior.ts
This is useful when user wants to, say, do a screenshot test. It makes
the UI more predictable.
> Allow user to disable auto reload programmatically

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
When using db_import where we don't import some of the Tensor types,
images plugin can be activated but without actual images. This can cause
the plugin to throw bunch of JSE for accessing property of undefined.
> Fixed JSE when steps is an empty array

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
PR #1375 conflated the ideas and caused explicitly resetted the domain
on any data fetch (even if it is already loaded). This will cause some
other "regression" (typing on tag filter then deleting it quickly causes
chart to not draw any axis) but it should be addressed in other PRs.
> Fixed domain reset bug on charts refresh

- tensorboard/components/tf_paginated_view/test/paginatedViewTests.ts
- tensorboard/components/tf_paginated_view/test/tests.html
- tensorboard/components/tf_paginated_view/tf-paginated-view2.html
As part of `Templatizer` contract, we need to correctly forward bound
value changes to instances.
These subtlety we keep miss are costly and we should re-evaluate our
strategy should this happen more often in the future.
> Paginated-view: forward parent props to child

- tensorboard/components/tf_dashboard_common/BUILD
- tensorboard/components/tf_dashboard_common/data-loader-behavior.html
- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/components/tf_line_chart_data_loader/BUILD
- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/BUILD
- tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-loader.html
- tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-loader.html
data-loader-behaior is a mixin that abstracts out data fetching logic
for all tf-*-loader.html. This change moves it out of the scalars plugin
and now applies to histogram and distribution plugins
> REFACTOR: data-loader to histogram & distrib

- tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Plottable caches DOM measurements for performance and it can be poisoned
when used with display: none that dom-if applies. Detect the bad layout
and bust the cache.
> Determine if cache should be busted for line-chart

- RELEASE.md
- tensorboard/version.py
Two commits to round out the 1.12.0 release process:
- Bump tb-nightly version to 1.13.0a0
- Cherrypick of 1.12.0 relnotes added to RELEASE.md
> Post-release 1.12.0

- tensorboard/plugins/histogram/histograms_plugin.py
In one of more realistic event file, we had
N=len(tensor_events)=500, M=max(len(event.tensor_proto))=110,000.
When making burst of requests from the histogram plugin, this large
`c*N*M` the /histograms endpoint to perform really poorly (c=number
of histogram charts on the screen). tf.make_ndarray ideally should
perform better wrt to the input but it can be done/studied separately.
Another way to mitigate the issue is to use ForkingWSGIServer instead
of ThreadedWSGIServer as, in this case, compute power is the bottleneck.
However, we do not have too many compute intensive data endpoints and it
is rather an overkill.
> Downsample histogram tensor before conversion

- tensorboard/components/BUILD
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/components/vz_line_chart2/BUILD
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/components/vz_line_chart2/linear-scale.ts
- tensorboard/components/vz_line_chart2/log-scale.ts
- tensorboard/components/vz_line_chart2/tf-scale.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
Line chart was using Plottable.Scale.ModifiedLogScale which treated
values near (0, 1] very differently than what log does. This handles
negative value (wrong but data is presented) and sometimes present line
chart very nicely but it works against researchers' expectation.
Fixes #57
> Add true log scale to line chart

- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/template.ts
- tensorboard/plugins/graph/tf_graph_common/test/graph-test.ts
- tensorboard/plugins/graph/tf_graph_common/test/hierarchy-test.ts
- tensorboard/plugins/graph/tf_graph_common/test/util-test.ts
- tensorboard/plugins/graph/tf_graph_common/util.ts
When we upgraded the Lodash from 3 to 4, it broke one of the private
method used to comput the size. According to
https://lodash.com/docs/4.17.10#lodash, `sum` is no longer chainable
breaking the method.
Though we tried to add tests to detect such breakage but graph code
is massive nad is largely untested. Since we cannot add all the tests at
once, we added one simple test, as a start.
> Fixed graph edge size computation

- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/core/index.html
This simplifies CorePluginTest so that it uses a fake `assets_zip_provider` that's backed by a transient in-memory zipfile, rather than actually building a real zipfile from a source-controlled index.html and passing it in as a data dependency to the test.
This way the test can't fail unintentionally due to changes in the index.html file such as those in #1546.
> Change CorePluginTest to use memory-only zipfile

- tensorboard/BUILD
- tensorboard/program.py
- tensorboard/program_test.py
Due to the inverted predicate on if, a legal flag was reported as
unknown to TensorBoard.
Added small test that does a sanity check against the bug.
> Fixed flag parsing in TB.configure

- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-source-code-view.html
Hi all,
The source code view in the debugger plugin isn't working. The code tries to call `_.contains`, which is a method in Underscore, but not Lodash, which is the actual library used. Changing the call to `_.includes` fixes things.
> Fix debugger plugin source code viewer "_.contains not found" error

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
When it contains leading slash, it creates url like "//data/..." which
is interpretted as an absolute url.
> Fix bug when data dir contains leading slash

- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Repro steps:
1. Display two series
2. Toggle off one series (using run selector)
3. Create a new chart instance by say toggle log scale
4. Toggle on the series that got turned off
5. ?? where is the second series?
This bug happened at least since TB==1.7 and is not a recent regression.
> FIX: chart correctly shows series when toggled

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- setDependencySorting(false), setDependencyPruning(false) and setMoocherDropping(false) are the initial value of DependencyOptions.
- setManageClosureDependencies(true) is equivalent to setDependencySorting(true), setDependencyPruning(true) and setMoocherDropping(false).
- setEntryPoints() is a no-op unless setDependencyPruning(true).
> Remove redundant logic when setting up the Closure Compiler dependency options.

- tensorboard/components/vz_line_chart2/log-scale.ts
- tensorboard/components/vz_line_chart2/test/BUILD
- tensorboard/components/vz_line_chart2/test/log-scale-test.ts
- tensorboard/components/vz_line_chart2/test/tests.html
When min and max values are multiple of 10, it had no padding causing
some visual discomfort.
Also, when value do not vary like [1, 1, 1], now we put some padding.
Added few basic tests around it.
> Improved log scale padding logic

- tensorboard/plugins/graph/tf_graph_common/minimap.ts
Bug: https://github.com/tensorflow/tensorboard/issues/1574
Cause: the graph contains no main graph node and all nodes are
auxilliary nodes. As a result, the drawn nodes are shifted right by
predefined amount for visuals. When measuring the bounding box of the
scene to draw the minimap, we were measuring using
SVGGraphicsElement.getBBox which returned BBox without any whitespace.
As a result, although we wanted the width from the origin to right edge
of the right most node, we were omitting the origin to left most edge
of the content resulting in clipped content in the minimap.
Fixes #1598.
> Fix the issue where minimap content gets clipped

- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
Guide user to upload pbtxt to the graph plugin. Without it
users were confused and tried to upload event file.
User can override the "accepts" and select any file with any extensions.
> Specify recommended file type on graph upload btn

- tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
Adds proposed changes from https://github.com/tensorflow/tensorboard/issues/1549.
> Make run name wrap better for the run-selector

- tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
This is needed in the HParams plugin since the API method that gets the metric values uses a POST not a GET.
@stephanwlee , @nfelt , @jart  Please take a look.
> Adding a callback to data-loader-behavior to allow customizing the HTTP request.

- tensorboard/plugins/graph/tf_graph_common/minimap.ts
Summary:
When viewing large graphs in Chrome, clicking the “Download PNG” button
could the error message, “Failed - Network error”. This is because
Chrome does not support downloading large data-URLs. Chrome does,
however, support downloading large object URLs, so this patch makes the
appropriate change to use that API instead.
Test Plan:
Generate the `audio_demo` data and open the `wave:01;sine_wave` graph in
TensorBoard in Chrome. Transitively expand all node groups. Then, click
“Download PNG”. Before this patch, this consistently failed to download.
After this patch, it downloads and image with the correct contents.
Also tested in Firefox.
wchargin-branch: graph-download-png-blob
> graph: fix “Download PNG” for large images

- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Summary:
Fixes #1621. These docs were far too closely specified. There was a day
where they also happened to be correct, but it is not this day.
Test Plan:
Look at the implementation of `resmoothDataset` in both versions of the
code (v1: `vz-line-chart.ts`, v2: `line-chart.ts`; the implementations
are the same). Observe that the implementation is not a moving average
whose window size is set by the `smoothingWeight`; instead, it is the
attenuation parameter of a low-pass filter.
wchargin-branch: docs-smoothing
> docs: fix vz_line_chart smoothing documentation

- tensorboard/components/vz_sorting/test/BUILD
- tensorboard/components/vz_sorting/test/test.py
- tensorboard/functionaltests/BUILD
- tensorboard/functionaltests/wct_test_driver.py
Summary:
Currently, we have some TypeScript unit tests, but we don’t run them
because they can only be run in a browser. This commit adds
infrastructure for running these tests headlessly and automatically.
Test failures will unfortunately simply be printed as
AssertionError: 1 failing test
because it is not obvious how to easily get additional information about
which tests have failed and why.
After running `bazel build`, running `bazel test` takes 17–18 seconds on
a 6-core W-2135 workstation, which is obviously obscene and untenable.
Running with `bazel run` takes “only” about 5s, which is still obscene
and untenable, but raises the question of why there is such a large
difference. We will need to investigate this performance if we want to
actually use this pattern to run our tests. …
> test: add infra for running WCT tests

- tensorboard/components/tf_color_scale/test/colorScaleTests.ts
Summary:
This test was broken in #810 when the code was changed but the test was
not updated appropriately. The failure was not caught because we do not
run our tests.
Test Plan:
Run `bazel run //tensorboard/components/tf_color_scale/test`, then
navigate to <http://localhost:6006/tf-color-scale/test/tests.html> and
verify that the page title reads, “3 passing tests”. A future change
will make this test run automatically.
wchargin-branch: tf_color_scale-fix-test
> tf_color_scale: fix test case

- tensorboard/components/tf_data_selector/BUILD
- tensorboard/components/tf_data_selector/storage-utils.html
- tensorboard/components/tf_data_selector/test/BUILD
- tensorboard/components/tf_data_selector/test/storage-utils-test.ts
- tensorboard/components/tf_data_selector/test/tests.html
Summary:
Both the `tf_data_selector` module and its `test` module failed to
declare and import their dependencies, so these test cases could not be
initialized or run. Independently, half of the test cases were incorrect
because they asserted reference equality instead of value equality. One
test case continues to have a genuine failure, so we skip it in this
commit. Another group of tests passes under Chrome but fails under
Chromium (see #1625), so we skip it, too.
Test Plan:
Run `bazel run //tensorboard/components/tf_data_selector/test`, then
navigate to <http://localhost:6006/tf-data-selector/test/tests.html> and
observe that the page title reads “2 passing tests” as opposed to the
previous “6 failing tests”. A future change will make this test run
automatically. …
> tf_data_selector: fix build deps and some tests

- tensorboard/components/tf_backend/test/BUILD
- tensorboard/components/tf_backend/test/test.py
- tensorboard/components/tf_categorization_utils/test/BUILD
- tensorboard/components/tf_categorization_utils/test/test.py
- tensorboard/components/tf_color_scale/test/BUILD
- tensorboard/components/tf_color_scale/test/test.py
- tensorboard/components/tf_data_selector/test/BUILD
- tensorboard/components/tf_data_selector/test/test.py
- tensorboard/components/tf_paginated_view/test/BUILD
- tensorboard/components/tf_paginated_view/test/test.py
- tensorboard/components/tf_storage/test/BUILD
- tensorboard/components/tf_storage/test/test.py
- tensorboard/components/vz_line_chart2/test/BUILD
- tensorboard/components/vz_line_chart2/test/test.py
- tensorboard/plugins/audio/tf_audio_dashboard/test/BUILD
- tensorboard/plugins/audio/tf_audio_dashboard/test/test.py
- tensorboard/plugins/graph/tf_graph_common/test/BUILD
- tensorboard/plugins/graph/tf_graph_common/test/test.py
- tensorboard/plugins/histogram/tf_histogram_dashboard/test/BUILD
- tensorboard/plugins/histogram/tf_histogram_dashboard/test/test.py
- tensorboard/plugins/projector/vz_projector/test/BUILD
- tensorboard/plugins/projector/vz_projector/test/test.py
Summary:
As of #1615, we have the infrastructure necessary to run most of our
frontend tests. This commit processes those test targets listed by
$ git ls-tree -zr --name-only HEAD | grep -z 'test.*\.ts' | tr '\0' '\n'
with three exceptions:
- the false positive `web-component-tester.d.ts` is not actually
itself a test;
- tests under `//tensorboard/components/tf_tensorboard/test` do not
have a BUILD file, and the main HTML file appears to use a different
pattern for loading and running the tests, so we can figure these
out in a separate commit; and
- tests under `//tensorboard/plugins/graph/tf_graph_loader/test` do
not have a BUILD file, and do not actually have any tests, anyway.
Some test cases are not run automatically because they are currently
failing.
Test Plan:
Run `bazel test …
> test: enable most existing frontend tests

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/backend/event_processing/db_import_multiplexer_test.py
- tensorboard/backend/event_processing/io_wrapper.py
- tensorboard/backend/event_processing/io_wrapper_test.py
Previously, user had to supply name of the experiment when passing
logdir. While this guaranteed correctness, it caused some friction in
adopting the db_import so, when a name is not passed, we infer the name
from the first top level in subdirectories of logdir.
> Infer name of exp when using db_import

- tensorboard/components/tf_backend/test/BUILD
- tensorboard/components/tf_categorization_utils/test/BUILD
- tensorboard/components/tf_color_scale/test/BUILD
- tensorboard/components/tf_data_selector/test/BUILD
- tensorboard/components/tf_paginated_view/test/BUILD
- tensorboard/components/tf_storage/test/BUILD
- tensorboard/components/vz_line_chart2/test/BUILD
- tensorboard/components/vz_sorting/test/BUILD
- tensorboard/plugins/audio/tf_audio_dashboard/test/BUILD
- tensorboard/plugins/graph/tf_graph_common/test/BUILD
- tensorboard/plugins/histogram/tf_histogram_dashboard/test/BUILD
- tensorboard/plugins/projector/vz_projector/test/BUILD
Summary:
These tests have a default timeout of 900s, which is way too long: they
should never take more than 20 seconds to legitimately complete, so
that’s just time spent waiting. The WebDriver connection also appears to
be somewhat flaky (@stephanwlee estimates that each test fails
independently with probability about 1/50), so we mark these tests
accordingly.
Generated with
awk -i inplace '
/browsers =/ {
print;
print "    timeout = \"short\",";
print "    flaky = True,";
next
}
1
' $(git grep -F --name-only 'name = "test_web_library"')
Test Plan:
Running `bazel test //tensorboard/...` still passes. We’ll see
anecdotally whether this reduces the number of spurious Travis failures.
wchargin-branch: test-webdriver-short-flaky
> test: mark web driver tests as short and flaky

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
We would like to able to hide datetime in the view that can sometimes
cause unnecessary flakiness. Currently, it is hard to select a datetime
without relying on specific dom structure.
> Add class on image card date for webdriver test

- tensorboard/components/tf_data_selector/storage-utils.ts
- tensorboard/components/tf_data_selector/test/storage-utils-test.ts
To save space on URL, data_selector persisted IDs by base 36 serializing
the ids. However, this lead to inconsistent behavior across browsers
while achieving very weak compression.
We disable the compression for now in favor of more holistic compression
at the tf_storage level using libraries like lz_string for URL safe
compression.
Related: #1625
> Disable base 36 encoding of IDs

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
PR #1512 introduced a bug where it formed a complete path without using
existing pathname. Previously without forming the complete path, it was
treated as a relative path from current window.location.pathname.
> Fixes path_prefix flag

- tensorboard/components/tf_backend/router.ts
- tensorboard/components/tf_backend/test/backendTests.ts
- tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
Resolves #1640.
Test Plan:
Within TypeScript files, the fact that the code typechecks is sufficient
to verify that callers are correct. To account for JS-in-HTML files,
first note that `git grep isDemoMode` returns no results. Then note that
each call site of `git grep pluginRoute` has been updated to use either
the 2-argument or 3-argument form (i.e., not passing a `demoCustomExt`).
I also manually checked the basic behavior of each plugin on the
frontend.
wchargin-branch: router-remove-demo-mode
> router: remove demo mode

- tensorboard/components/vz_chart_helpers/vz-chart-tooltip.html
- tensorboard/components/vz_line_chart/vz-line-chart.html
- tensorboard/components/vz_line_chart2/vz-line-chart2.html
- tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.html
- tensorboard/plugins/profile/google_chart/google-chart.html
Summary:
Some modules have `@demo` annotations that point to nonexistent demos,
so we fix or remove those references as appropriate.
The `google-chart` demo is not working and does not appear to have ever
worked: when running it on its initial commit after cherry-picking #1334
we see only a blank page. However, deleting this demo isn’t trivial,
because the main profile dashboard depends on it for some reason. As
this plugin is still being actively developed, we’ll leave the demo
alone for now: it’s not actually causing any problems.
Context: <https://github.com/tensorflow/tensorboard/pull/1645#issuecomment-443000383>
Test Plan:
Note that `git grep @demo` only lists correct paths to working demos.
wchargin-branch: remove-broken-demos
> Remove some broken demos and demo annotations

- third_party/workspace.bzl
Generally, it is a good idea to update the ChromeDriver along with
Chromium we use since they can sometimes be incompatible. Upgrade
to the latest ChromeDriver that supports 70.
Ran the test 200 times and it does not seem to solve the flakiness issue we were witnessing.
```sh
//tensorboard/components/tf_backend/test:test_chromium                   PASSED in 10.4s
Stats over 200 runs: max = 10.4s, min = 5.9s, avg = 8.1s, dev = 0.7s
//tensorboard/components/tf_categorization_utils/test:test_chromium      PASSED in 10.2s
Stats over 200 runs: max = 10.2s, min = 6.7s, avg = 8.3s, dev = 0.7s
//tensorboard/components/tf_color_scale/test:test_chromium               PASSED in 10.0s
Stats over 200 runs: max = 10.0s, min = 6.7s, avg = 8.1s, dev = 0.7s …
```
> Upgrade the ChromeDriver for Chromium 70

- tensorboard/components/vz_sorting/test/BUILD
- tensorboard/defs/BUILD
- tensorboard/defs/web.bzl
- tensorboard/defs/web_test_python_stub.template.py
Summary:
This macro removes the need to create a `test.py` target for each web
test, and centralizes some common options like browser selection,
default test timeout, and flakiness.
A benefit of this change is that it removes the direct dependency on the
webtesting rules in each BUILD file, instead centralizing the dependency
in `web.bzl`. This makes it easier to change this dependency when we
import into Google (where the infrastructure is different).
Test Plan:
Run `bazel test //tensorboard/components/vz_sorting/test` and note that
it passes. Then, change `sortingTests.ts` to make a test fail. Re-run
the bazel command and note that it fails. Run with `bazel run` instead
and note that it opens a browser.
wchargin-branch: tf-web-test
> test: add `tf_web_test` Starlark macro

- tensorboard/defs/web.bzl
- tensorboard/defs/web_testing.bzl
Summary:
This is needed for the Google import process. At the Bazel level, it’s
an API-compatible change: clients can (and do) continue to import
`tf_web_test` from `web.bzl`.
Test Plan:
All existing tests pass, and correctly fail if so modified.
wchargin-branch: encapsulate-webtesting
> web.bzl: encapsulate rules_webtesting dependency

- .travis.yml
- WORKSPACE
- tensorboard/defs/web_testing.bzl
- tensorboard/functionaltests/browsers/BUILD
- tensorboard/functionaltests/browsers/chromium.json
- third_party/chromium/BUILD
- third_party/js.bzl
- third_party/python.bzl
- third_party/urllib3.BUILD
- third_party/workspace.bzl
Summary:
Bazel 0.20.0 introduced some incompatible changes that broke both our
code and our dependencies. Our dependencies also introduced some
incompatible changes of their own. This commit upgrades our dependencies
and fixes up our code to accommodate them.
An upgrade to transitive dependency `rules_go` introduces a dependency
on the `@bazel_tools//tools/build_defs/cc:action_names.bzl` builtin
target. This target was only introduced in Bazel 0.16.0, so as a
consequence our workspace is no longer compatible with earlier versions
of Bazel. In practice, we must use at least version 0.16.1 to fix a
regression in 0.16.0: <https://github.com/bazelbuild/bazel/issues/5726>.
Unfortunately, Bazel 0.16.0 also introduced a regression that prevents
us from using the …
> build: fix Bazel 0.20.0 compatibility issues

- .travis.yml
Summary:
As suggested by @nfelt in:
<https://github.com/tensorflow/tensorboard/pull/1661#pullrequestreview-181946869>
Test Plan:
Verify that the new chunk of shell script has the following properties:
- When executed with the environment variables at the top of the
Travis config, successfully downloads Bazel 0.16.1 and returns 0.
- When executed with `BAZEL=0.19.2` (which does not exist in the
mirror) and shasum updated per the instructions in the comment,
successfully downloads Bazel 0.19.2 and returns 0.
- When executed with `BAZEL=0.wat.0` (which does not exist), fails
and returns 1.
- When a bit is flipped in the shasum, fails and returns 1, having
removed the invalid downloads.
Note that Shellcheck reports no errors or warnings with `#!/bin/sh`. …
> travis: add GitHub fallback for Bazel download

- tensorboard/backend/event_processing/BUILD
- tensorboard/plugins/core/BUILD
Summary:
This is breaking some Google-internal tests.
Test Plan:
Note that those files that `import sqlite3` are in correspondence with
those targets that depend on `expect_sqlite3_installed`:
```
$ bazel query 'attr("deps", "expect_sqlite3_installed", //...)' | sort
//tensorboard/backend:application
//tensorboard/backend/event_processing:db_import_multiplexer_test
//tensorboard:db
//tensorboard/plugins/core:core_plugin_test
//tensorboard/util:test_util
$ git grep --name-only 'import sqlite3' | sort
tensorboard/backend/application.py
tensorboard/backend/event_processing/db_import_multiplexer_test.py
tensorboard/db.py
tensorboard/plugins/core/core_plugin_test.py
tensorboard/util/test_util.py
```
wchargin-branch: declare-sqlite3-dep
> build: declare sqlite3 dep where appropriate

- tensorboard/defs/web.bzl
Summary:
Per the [“Skylint: Re-exporting `load()`ed names” docs on the Bazel
website][1].
[1]: https://docs.bazel.build/versions/master/skylark/skylint.html#re-exporting-loaded-names
Test Plan:
That existing tests build and pass is sufficient.
wchargin-branch: re-export-syntax-fixup
> web.bzl: use Skylint-recommended re-export syntax

- tensorboard/defs/web_testing.bzl
Summary:
- Change “Arguments” to “Args”
- Document the `name` parameter
- Reformat with `buildifier`
Recommend reviewing with `-w`.
Test Plan:
None.
wchargin-branch: buildify-webtesting
> web_testing.bzl: fix miscellaneous lint errors

- third_party/python.bzl
Summary:
This makes the Google-internal linter happy.
Recommend reviewing with `-w`.
Test Plan:
None.
wchargin-branch: python-bzl-format
> python.bzl: add minimal docs and reformat

- tensorboard/BUILD
- tensorboard/util/BUILD
- tensorboard/util/__init__.py
- tensorboard/util_test.py
Summary:
This reintroduces the `tensorboard.util` module removed in #1629; some
targets within Google still depend on its Bazel target, so this will
enable us to migrate them cleanly.
Test Plan:
All tests pass in both Python 2 and Python 3. Removing an export from
`__init__.py` causes `util_test` to fail with a helpful message.
wchargin-branch: util-wrapper
> util: add `tensorboard.util` compatibility wrapper

- tensorboard/backend/event_processing/event_file_loader.py
This commit fixes a performance bottleneck in `event_file_loader.RawEventFileLoader` by caching the result of a TensorFlow compatibility check.
The `event_file_loader_test` test succeeds under both `tensorflow==1.7` (the latest TensorFlow release that needs the compatibility check) and `tf-nightly==1.13.0.dev20181211`, but there are several other tests failing under `tensorflow==1.7`. These tests also fail at the head of master 0d4b71ba when using `tensorflow==1.7`.
Fixes #1676
> Remove compatibility check from hot path

- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/loader.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager.py
- tensorboard/plugins/projector/projector_plugin.py
The symbol `pywrap_tensorflow` is deprecated and will only be available through compat.v1.
> Change usages of tf.pywrap_tensorflow to tf.compat.v1.pywrap_tensorflow.

- DEVELOPMENT.md
Summary:
When bisecting or exploring the history, it can be useful to build old
commits. Unfortunately, due to backward-incompatible changes in Bazel,
this is not possible natively. This commit describes a workaround.
It’s unfortunately not too discoverable in `DEVELOPMENT.md`, but at
least it’s somewhere.
Test Plan:
$ git checkout -q "$(git rev-list origin/master --before=2018-08-01 -n 1)"
$ bazel build //tensorboard 2>&1 | tail -n 1
FAILED: Build did NOT complete successfully
$ git cherry-pick bc4e7a6e5517daf918433a8f5983fc6bd239358f >/dev/null
$ bazel build //tensorboard 2>&1 | tail -n 1
INFO: Build completed successfully, 117 total actions
wchargin-branch: docs-build-old
> docs: add instructions for building old revisions

- tensorboard/components/tf_data_selector/experiment-selector.html
- tensorboard/components/tf_data_selector/tf-data-select-row.html
- tensorboard/components/tf_data_selector/tf-data-selector-advanced.html
We need to import scrollbar only when we <style include> it.
Remove unused scrollbar imports.
- Found the instance of wrong scrollbar-style usage by grepping
- I have been searching for ways to find unbalanced tags without too much noise but have not found a good tool for it
- tidy is too noisy
- polymer linter does not catch unbalanced tag
- parse5 that Polymer tools use fixes unbalanced tag when constructing AST without an ability to complain: https://github.com/inikulin/parse5/issues/180
- etc
> Removed unused import and fixed unbalanced tags

- tensorboard/plugins/profile/overview_page/overview-page.html
> Add a breakdown of step time to overview page.

- tensorboard/plugins/profile/overview_page/overview-page.html
The batch size is based on heuristics. However, it appears to be wrong very often now.
The right way is to get the batch size from TensorFlow.
Before we fix it, rather than presenting a wrong batch size to the user, let's remove it.
> Remove reporting of the batch size from the overview page.

- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/components/vz_line_chart2/line-chart.ts
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-continue-dialog.html
Summary:
Lodash removed `isFinite` and `isNaN` in January 2017; this commit
removes them from our codebase. They are equivalent to `Number.isFinite`
and `Number.isNaN`, respectively, which were introduced in ES6. We
already use `Number.isFinite` elsewhere in our codebase, so I figure
that it’s okay to add more such dependencies.
Test Plan:
Note that `git grep -F -e _.isFinite -e _.isNaN` returns no results.
wchargin-branch: lodash-remove-isfinite
> lodash: remove uses of deprecated `_.isFinite`

- tensorboard/components/vz_line_chart/vz-line-chart.ts
- tensorboard/components/vz_line_chart2/line-chart.ts
Due to IEEE 754 floating-point precision, multiplying floating smoothing
factor into a value can cause discrepency in otherwise mathematically
constant value.
Please see #786 for examples of weird spikes/messed up y-scale.
Partially addresses #786.
> Check whether values are constant before smooth

- tensorboard/pip_package/build_pip_package.sh
This is useful when trying to quickly iterate on the output of build_pip_package, since running the smoke tests can take 30+ seconds whereas just building the package is often faster.
> Allow passing --no-smoke to build_pip_package to skip smoke testing

- .travis.yml
- tensorboard/tools/do_not_submit_test.sh
Summary:
Google-internal tools perform this check, which is useful for preventing
premature merging of in-progress code. This commit adds equivalent
functionality to the Travis build only and not as a Bazel test,
analagous to our existing license test.
Test Plan:
Invoke the script and note that it passes with no output. Run
printf >hmmm 'DO NOT SUBMIT'
and note that the script fails with a helpful error message. Then run
printf >hmmm 'DO NOT SUBMIT\0'
and note that the script passes because this is a binary file.
Then, run `(cd tensorboard && ./tools/do_not_submit_test.sh)`, and note
that the script fails because it is not being run from TensorBoard root.
wchargin-branch: test-dns
> test: add Travis test for “DO NOT SUBMIT” in files

- tensorboard/backend/event_processing/BUILD
- tensorboard/backend/event_processing/db_import_multiplexer.py
- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_file_inspector.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
Now that TensorBoard hosts all proto definitions required to run it, we
use the TensorBoard version of protos. #1678 has missed few usages of
SessionLog.[CONSTANT] and this change fixes that.
Related: #1718.
> [CLEANUP] Change tf.SessionLog.* to TB.SessionLog.*

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/plugins/debugger/BUILD
- tensorboard/plugins/debugger/debug_graphs_helper_test.py
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/image/images_demo.py
We are deprecating usage of tf.proto but have missed few usage of
RunMetadata in #1678.
Confirmed that this is not causing regression by:
1. running TB with variety of event files
2. reading the code: change in graphs_plugin is innocuous as we are
serializing proto into string.
Do note that this changes output of event_accumulators#RunMetadata but
we do not seem to be using it at least in our repo.
Relates to #1718.
> [CLEANUP] tf.RunMetadata to tb.RunMetadata

- tensorboard/backend/event_processing/event_accumulator.py
- tensorboard/backend/event_processing/event_accumulator_test.py
- tensorboard/backend/event_processing/plugin_event_accumulator.py
- tensorboard/backend/event_processing/plugin_event_accumulator_test.py
- tensorboard/plugins/core/BUILD
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/util/test_util.py
TF 2.0 is removing symbols for GraphDef and MetaGraphDef protos.
We are converting it to TB proto definitions instead.
Relates to #1718.
> Change TF graph proto to TB graph proto

- tensorboard/backend/event_processing/event_multiplexer_test.py
- tensorboard/backend/event_processing/plugin_asset_util.py
- tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
- tensorboard/plugins/beholder/file_system_tools.py
- tensorboard/plugins/beholder/im_util.py
- tensorboard/plugins/debugger/debugger_server_lib.py
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/projector/__init__.py
- tensorboard/plugins/projector/projector_api_test.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/projector/projector_plugin_test.py
GFile was omitted from V2 API by mistake and the migration script
misbehaved. Now that TF has fixed it, we now want to use the V2 API.
Relates to #1718.
> Use v2 API for GFile

- tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
- tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
While refactoring the dashboard layout, we inadvertently broke the
horizontal resizing capability. The resizer was clipped and was bound
by the TB global max/min-width limit on the sidebar width.
- Note that `Show code` is clipped due to the max-width on the container.
> Fix horizontal resizer in debugger

- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/custom_scalar/custom_scalar_demo.py
Summary:
This is functionally a no-op; we just moved a package.
Test Plan:
Run `bazel run //tensorboard/plugins/custom_scalar:custom_scalar_demo`
and note that the demo still works.
wchargin-branch: migrate-summary-v1
> custom_scalar_demo: migrate to summary_v1 module

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
When specifying path to resources in, for instance, image tag, we use a
relative path. This path is supposed to be relative to the webpath (at
least when using WebfilesValidator) but vulcanized resources do not
convert this relative path into an appropriate path.
For instance, say we are trying to build index.html that refers to
another HTML file, foo/bar.html. In bar.html, we use a relative path
"./faz.png" to a resource in the same "foo" namespace. Previously, the
relative path was not expanded and was relative to the index.html. After
this change, we now expand faz.png based on foo/bar.html and make it
relative to output file index.html.
Confirmed the fix by running TensorBoard with path_prefix and checking the What-If
tool, the only place where we use relative paths to image resources …
> Fix the relative path issue when Vulcanizing

- .travis.yml
- tensorboard/pip_package/build_pip_package.sh
Summary:
This unbreaks our build until tensorflow/tensorflow#24867 is merged:
<https://github.com/tensorflow/tensorflow/pull/24867>
Test Plan:
Running `bazel run //tensorboard/pip_package:build_pip_package` includes
a smoke test that fails before this change and passes after it.
wchargin-branch: pin-tf-nightly
> build: temporarily pin working tf-nightly version, and fix build

- .travis.yml
Summary:
Testing on fresh Trusty VMs on GCP suggests that this may suffice to
stop the strange errors wherein Bazel invokes GCC with invalid flags,
though it should be noted that we do not actually understand the root
cause or the mechanism of failure.
Test Plan:
That this build should pass on Travis does not actually indicate that
this commit fixes the underlying problem, because the build will use
a new Bazel cache due to the version change. So: merge now, and hope
that this fixes the problem.
wchargin-branch: travis-bazel-0.21.0
> ci: update Travis to Bazel 0.21.0

- .travis.yml
- tensorboard/pip_package/build_pip_package.sh
Summary:
This reverts part of d285c7de73a09e9ece5a13368a58c00e1dcabda9 because
the upstream package has been fixed.
Test Plan:
Running `from tensorflow.compat import v1` fails in the 20190114
virtualenv but works in the 20190115 virtualenv. Building the Pip
package with `bazel run //tensorboard/pip_package:build_pip_package`
also works.
wchargin-branch: unpin-tf-nightly
> build: unpin tf-nightly version

- tensorboard/BUILD
- tensorboard/summary/BUILD
Summary:
We’ve migrated all users inside Google to use the explicitly versioned
endpoints (either `summary:summary_v1` or `summary:summary_v2`), so we
can now enforce that going forward.
Any existing users should migrate to `//tensorboard/summary:summary_v1`,
which is API-compatible and stable.
Test Plan:
That `bazel build //tensorboard` and `bazel query 'deps(//...)'` still
work suffices.
wchargin-branch: restrict-summary-visibility
> build: lock down visibility of unversioned summary targets

- tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
- tensorboard/pip_package/setup.py
- tensorboard/scripts/execrooter.py
- third_party/python.bzl
This PR makes it possible to build a working TensorBoard on Windows again, which has evidently been broken for quite some time.  This in turn makes it possible for us to debug Windows-specific TensorBoard issues.
There are three separate fixes in this PR:
- Fixes to execrooter.py to work on Windows, e.g. by using copying instead of symlinks
- Removal of a bug-triggering `jvm_flags` argument to the vulcanize java_binary() rule - this is a bug in bazel's parsing of jvm_flags on windows, see https://github.com/bazelbuild/bazel/issues/7072, which for us manifested itself as #1466 
- Bumping our werkzeug dep to 0.11.15 to pick up fixes from https://github.com/pallets/werkzeug/pull/999 so it's compatible with Windows + python 3.6
With these fixes, I can build and run tensorboard at HEAD on …
> Unbreak the tensorboard windows build

- tensorboard/plugins/pr_curve/BUILD
Having py_binary in deps is deprecated and will break in 19Q1.
Removed py_binary target in deps of any other target.
> Split py_binary into py_binary for pr_curve_demo

- docs/_book.yaml
- docs/_index.yaml
- docs/_project.yaml
- docs/api_docs/README.md
- docs/api_docs/python/_toc.yaml
- docs/api_docs/python/index.md
- docs/graphs.md
- docs/histograms.md
- docs/overview.md
- docs/summaries.md
- docs/tutorials/tutorial.md
Creates basic structure for a tensorflow.org subsite, see cl/229872850
This moves in the current TensorBoard guides from the main tensorflow/docs repo.
Adding to master branch, let me know if you want it on another branch (and please make it for me).
> Create TensorBoard docs subsite structure

- tensorboard/__init__.py
- tensorboard/compat/BUILD
- tensorboard/compat/__init__.py
- tensorboard/compat/tensorflow_stub/__init__.py
- tensorboard/lazy.py
- tensorboard/plugins/audio/summary_test.py
- tensorboard/plugins/audio/summary_v2.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/histogram/summary_v2.py
- tensorboard/plugins/image/summary_test.py
- tensorboard/plugins/image/summary_v2.py
- tensorboard/plugins/projector/projector_plugin.py
- tensorboard/plugins/scalar/summary_test.py
- tensorboard/plugins/scalar/summary_v2.py
- tensorboard/plugins/text/summary_test.py
- tensorboard/plugins/text/summary_v2.py
- tensorboard/summary/BUILD
- tensorboard/summary/summary_dep_test.py
This PR makes `tensorboard.compat.tf` into a lazy-loading module for accessing the TF API (either real or stub), and introduces a similar `tensorboard.compat.tf2` lazy-loading module for accessing the TF 2.0 API (either as `tf` or `tf.compat.v2`). 
The first change (lazifying `tensorboard.compat.tf`) is necessary so that that the `tensorboard.summary.v2` summary API can be imported without immediately importing TensorFlow, since we want TF to be able to import that without triggering a circular dependency.  Previously, the V2 summary API transitively imports various pieces from under `tensorboard.compat`, and that module's `__init__.py` file was opportunistically importing `tensorflow` at module load time to provide `tensorboard.compat.tf`).  Now that import is deferred until `tf` is …
> Make tensorboard.compat.{tf,tf2} lazily loaded

- tensorboard/plugins/profile/overview_page/overview-page.html
The infeed_ms_average was mistakenly set as compute_ms_average  value.
> Fix a bug in overview page

- tensorboard/summary/summary_dep_test.py
Using the local-only name of the module in the later tests makes the internal code sync simpler.
> Fix module references in new summary_dep_test.py

- tensorboard/BUILD
- tensorboard/compat/tensorflow_stub/BUILD
Internal build requires the dependency declaration for the translation.
> Created empty target to denote absl.flags dep

- tensorboard/pip_package/setup.py
Tensorflow requires `protobuf>=3.6.0` which has hidden this issue, but TensorBoard itself now requires 3.6.0+ on its own, because we compile our _pb2.py files using the 3.6.0 protoc, and the outputs are not backwards-compatible with older protobuf runtimes - they fail with an error like the following:
```
File "/usr/local/google/home/nickfelt/scratch/tb-notf/bin/tensorboard", line 6, in <module>
from tensorboard.main import run_main
File "/usr/local/google/home/nickfelt/scratch/tb-notf/local/lib/python2.7/site-packages/tensorboard/main.py", line 45, in <module>
from tensorboard import default
File "/usr/local/google/home/nickfelt/scratch/tb-notf/local/lib/python2.7/site-packages/tensorboard/default.py", line 37, in <module>
from tensorboard.plugins.audio …
```
> Update protobuf dep to >=3.6.0 which is what is actually required

- tensorboard/BUILD
- tensorboard/lazy.py
- tensorboard/lazy_test.py
Follow-up to #1781. See individual commit messages for details. To be
merged with rebase.
> Make and test some small improvements to `lazy`

- tensorboard/program.py
Summary:
Currently, TensorBoard does not change the default signal dispositions
for any signal handlers, so if killed by SIGTERM or SIGQUIT it will exit
without running its `atexit` handlers, such as the one registered by the
DB import mode. As of this commit, we handle SIGTERM by exiting
gracefully. We leave SIGQUIT at the default disposition (temporary files
will not be cleaned up), in accordance with the GNU libc guidelines:
<https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGQUIT>
The implementation is not perfect. Ideally, we would perform our
graceful cleanup and then kill ourselves with the same signal to
properly inform our parent of the source of the exit: for details, see
<https://www.cons.org/cracauer/sigint.html>. But `atexit` doesn’t
provide …
> main: handle SIGTERM, running `atexit` handlers

- tensorboard/BUILD
- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
This type describes information about a running TensorBoard instance. In
a future commit, TensorBoard’s main function will be outfitted to write
an “info file” containing this structure to a well-known location, which
other processes can inspect to find all running TensorBoard instances,
the ports on which they’re listening, their arguments and context, etc.
The wire format is JSON as opposed to pbtxt for two reasons: it’s more
open-source friendly (tools like `jq` have no publicly available
protobuf equivalents), and the Python protobuf APIs are so frustrating
that it doesn’t feel right to force callers to use them, even if this
means that we have to implement our own validation and serialization.
Supersedes part of #1795.
Test Plan:
Unit tests included; run `bazel test …
> manager: add `TensorboardInfo` type definition

- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
This function computes the (opaque) value of the `cache_key` field of
`TensorboardInfo` objects, which is used to determine whether it is safe
to reuse a TensorBoard instance. See docs for more details.
Test Plan:
Unit tests included; run `bazel test //tensorboard:manager_test`.
For a sanity check at the REPL:
```
>>> from tensorboard import manager
>>> import base64, json, os, pprint
>>> ck = manager.cache_key(
...     working_directory=os.getcwd(),
...     arguments=["--logdir", "foo"],
...     configure_kwargs={},
... )
>>> ck
'eyJhcmd1bWVudHMiOlsiLS1sb2dkaXIiLCJmb28iXSwiY29uZmlndXJlX2t3YXJncyI6e30sIndvcmtpbmdfZGlyZWN0b3J5IjoiL3Vzci9sb2NhbC9nb29nbGUv
aG9tZS93Y2hhcmdpbi9naXQvdGVuc29yYm9hcmQifQ=='
>>> pprint.pprint(json.loads(base64.b64decode(ck)))
{u'arguments': [u'--logdir', …
```
> manager: add a `cache_key` function

- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
The previous implementation always returned `six.binary_type`; it now
returns `str` in both Python 2 and Python 3.
Test Plan:
Regression test added; `bazel test //tensorboard:manager_test` passes in
Python 2 and 3, and fails on Python 3 if the code under test is
reverted.
wchargin-branch: cache-key-str
> manager: always return `str` from `cache_key`

- tensorboard/util/__init__.py
Summary:
Having an (empty) `__init__.py` file enables us to import modules under
`tensorboard.util` at a Python 2 REPL. (It works either way in Python 3,
because `tensorboard.util` is interpreted as a namespace package.)
Test Plan:
Running `python -c 'from tensorboard.util import tb_logging'` after this
change works in both Python 2 and Python 3, but before this change works
in Python 3 but fails in Python 2 (after removing any cached `.pyc`
bytecode file).
wchargin-branch: util-init-py
> util: add __init__.py for REPL convenience

- tensorboard/pip_package/build_pip_package.sh
This bug will be triggered if the predefined dest folder exists.
Because mktemp has different argument definition in mac.
> fix pip build script under mac

- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Summary:
The Google import process complains about common typos; this makes it
happy. :-)
Test Plan:
None.
wchargin-branch: wit-example-typos
> wit: fix typos in visualization.py

- docs/summaries.md
Summary:
Resolves root cause of Google-internal bug <http://b/117792912>, which
pointed out that `argmax(y_, 1)` should just be `y_`.
Test Plan:
```shell
$ url='https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py' &&
> diff -u \
>   <(curl -L --silent "${url}" |
>       sed -n -e 's/^  //' -e '/def variable_summaries/,/global_variables_initializer/p') \
>   <(sed -n -e '/def variable_summaries/,/global_variables_initializer/p' \
>       ./docs/summaries.md) &&
> echo $?
0
```
wchargin-branch: update-summary-docs-code
> docs: update summary example code from TF source

- tensorboard/BUILD
- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
This commit implements functions `write_info_file`, `remove_info_file`,
and `get_all` on the `tensorboard.manager` module. See docs for details.
Supersedes part of #1795.
Test Plan:
Integration tests included; run `bazel test //tensorboard:manager_test`.
wchargin-branch: tensorboardinfo-io
> manager: add I/O for TensorboardInfo files

- tensorboard/BUILD
- tensorboard/program.py
Summary:
This commit wires up `TensorBoard.main` to the `TensorboardInfo` I/O
introduced in #1806.
Test Plan:
Run `bazel run //tensorboard -- --logdir ./whatever/`, then verify that
an info file has been created…
$ ls /tmp/.tensorboard-info/
pid-85532.info
…and that the file is visible to the Python APIs:
$ python
>>> from tensorboard import manager
>>> infos = manager.get_all()
>>> len(infos)
1
>>> infos[0].pid
85532
>>> infos[0].port
6006
Then, SIGTERM the server and verify that this is reflected from Python…
>>> import os
>>> os.kill(infos[0].pid, 15)
>>> manager.get_all()
[]
…and that the underlying file is gone:
$ ls /tmp/.tensorboard-info/ | wc -l
0
wchargin-branch: write-tensorboardinfo
> program: write TensorboardInfo on server startup

- tensorboard/manager.py
- tensorboard/manager_test.py
- tensorboard/notebook.py
- tensorboard/program.py
Summary:
Per @manivaradarajan’s request, for consistency with other uses of
`TensorBoard` as an identifier.
Generated with:
$ git grep --name-only -z TensorboardInfo |
> xargs -0 sed -i -e 's/TensorboardInfo/TensorBoardInfo/g'
$ git add -u
Test Plan:
$ git grep TensorboardInfo | wc -l
0
wchargin-branch: tensorboardinfo-capitalization
> manager: rename TensorboardInfo to TensorBoardInfo

- tensorboard/manager_e2e_test.py
Summary:
Within Google, the `//tensorboard:tensorboard` target is at a different
path in the build workspace, so tests with a data dependency on it
cannot find it at `./tensorboard/tensorboard`. However, the binary
should always be in the same place relative to the test binary, so we
now use that instead.
Test Plan:
Running `bazel test //tensorboard:manager_e2e_test` still works in
Python 2 and 3.
wchargin-branch: relative-data-path
> test: resolve TensorBoard binary relative to test

- tensorboard/BUILD
Summary:
This can take longer on Google-internal infrastructure in some cases.
(Note that this commit will introduce a test size warning when the test
takes less than a minute, which is common in the open-source version.)
Test Plan:
The BUILD file is still valid, and the test still passes.
wchargin-branch: manager-e2e-moderate
> manager_e2e_test: mark as moderate

- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
PR #1750 added a new required prop for tf-graph-loader which broke all
use cases of tf-graph-loader: e.g., debugger plugin, tf-graph-app, and
all the custom tf-graph implementations.
Instead of explicitly defining the provider, it looks appropriate to
have the sane default to keep the same behavior we have had for many
minor versions.
> Default compatibilityProvider to tf-graph-loader

- tensorboard/notebook.py
Summary:
This hooks up the `notebook` module to Colab. The Colab runtime
sandboxes the contents of the output frame, but provides a service
worker tunnel so that the frame may communicate with underlying VM. We
take advantage of this by loading TensorBoard through a JavaScript shell
that changes the document `baseURI` to proxy requests through this
worker.
Test Plan:
Add `//tensorboard:notebook` to the deps of `build_pip_package`, then
build the Pip package and manually upload it onto a public Colab
instance. Then run:
!pip uninstall -q -y tensorflow tf-nightly-2.0-preview
!pip install -q tf-nightly-2.0-preview
!pip uninstall -q -y tensorboard
!pip install -q ./tensorboard-1.13.0a0-py3-none-any.whl
%load_ext tensorboard.notebook
%tensorboard --logdir ./tensorboard_data/mnist
and watch …
> notebook: add Colab integration shell

- tensorboard/compat/proto/allocation_description.proto
- tensorboard/compat/proto/api_def.proto
- tensorboard/compat/proto/attr_value.proto
- tensorboard/compat/proto/config.proto
- tensorboard/compat/proto/cost_graph.proto
- tensorboard/compat/proto/cpp_shape_inference.proto
- tensorboard/compat/proto/debug.proto
- tensorboard/compat/proto/event.proto
- tensorboard/compat/proto/function.proto
- tensorboard/compat/proto/graph.proto
- tensorboard/compat/proto/meta_graph.proto
- tensorboard/compat/proto/node_def.proto
- tensorboard/compat/proto/op_def.proto
- tensorboard/compat/proto/resource_handle.proto
- tensorboard/compat/proto/rewriter_config.proto
- tensorboard/compat/proto/saver.proto
- tensorboard/compat/proto/step_stats.proto
- tensorboard/compat/proto/summary.proto
- tensorboard/compat/proto/tensor.proto
- tensorboard/compat/proto/tensor_description.proto
- tensorboard/compat/proto/tensor_shape.proto
- tensorboard/compat/proto/tfprof_log.proto
- tensorboard/compat/proto/types.proto
- tensorboard/compat/proto/update.sh
- tensorboard/compat/proto/versions.proto
- tensorboard/tools/license_test.sh
In preparation for our own 1.13 release.
Licenses are removed because they aren't present on the original protos; I've updated license_test.sh to not require licenses on *.proto files.  I also tweaked the update.sh script so that it runs on linux (`sed -i ''` is macOS-only) and doesn't require the git clean.
> Update compat/*.proto to tensorflow v1.13.0-rc1 versions

- tensorboard/BUILD
- tensorboard/__init__.py
- tensorboard/pip_package/BUILD
- tensorboard/pip_package/build_pip_package.sh
Summary:
Users of the Pip package now have the files necessary to use Jupyter
extensions, by incanting `%load_ext tensorboard.notebook` at the top of
their notebook.
The `notebook` module is also directly exposed on the `tensorboard`
module, so `import tensorboard as tb` followed by `tb.notebook.start`
works (like `program` and `summary`, and unlike `backend` or `plugins`).
Test Plan:
Run `bazel run //tensorboard/pip_package:build_pip_package`, and suppose
that `${WHEEL}` is the path to the emitted Python 3 wheel. Then run
$ cd "$(mktemp -d)"
$ virtualenv -q -p python3 ./ve/
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview
(ve) $ pip uninstall -q -y tb-nightly
(ve) $ pip install -q "${WHEEL}"
(ve) $ pip install -q jupyter
(ve) $ jupyter notebook
Then, create a notebook …
> pip: add `tensorboard.notebook` to Pip package

- tensorboard/manager.py
Summary:
When running on Google-internal Colab, launching a fresh TensorBoard
instance usually takes around 12 seconds. (It’s faster on public Colab.)
Setting the timeout to 60s should do the trick.
This commit updates the default timeout so that users don’t have to run
the `%tensorboard` magic twice (once for it to start and time out, and
once for it to pick up the now-existing instance).
Test Plan:
I made the analogous change inside google3, and `%tensorboard` worked on
the first try; it’s never worked without timing out before.
wchargin-branch: manager-20s
> manager: change default timeout from 10s to 60s

- tensorboard/components/tf_tensorboard/tf-tensorboard.html
Summary:
In a normal standalone TensorBoard, users probably want the help button
to open in a new tab rather than replacing their current state.
In a Jupyter or Colab notebook context, this is more important, because
the GitHub response’s CSP includes `frameancestors 'none'`.
Consequently, clicking the “help” button causes the frame contents to be
erased entirely, replaced with a white page. The user can right-click
and select “Back” to go back to TensorBoard, but this is far from
obvious, and also bad.
Test Plan:
Build TensorBoard, put it on your path, and run `jupyter notebook`. Then
use a `%tensorboard` command to launch TensorBoard, and verify that the
help link properly opens the documentation in a new tab.
wchargin-branch: ui-help-blank
> ui: open help in new window/tab

- tensorboard/BUILD
- tensorboard/lazy.py
- tensorboard/lazy_test.py
Summary:
If a module fails to load once, we propagate its raised error. If the
module fails to load again, we mistakenly think that we’re still
executing the first load, so we raise the _wrong_ error the second time.
This patch fixes that.
Test Plan:
Unit test added. Running `bazel test //tensorboard:lazy_test` passes,
but fails if you revert the change to `lazy.py`.
wchargin-branch: lazy-errors
> lazy: properly handle errors during load

- tensorboard/components/tf_runs_selector/tf-runs-selector.html
Steps to repro:
1. load dashboard 1
2. load dashboard 2
3. change run selection in 2
4. check whether dashboard 1 reflects the change
We want to prevent regression with a test (b/124343760).
Regression caused by https://github.com/tensorflow/tensorboard/pull/1279
> Fix the run selector state sync bug

- tensorboard/compat/__init__.py
Summary:
This lets the Google sync process detect these as normal imports and
rewrite them internally.
Test Plan:
All non-`manual`, non-`noci` Python tests pass. Making the analogous
change within Google fixes http://b/124321202.
wchargin-branch: compat-normal-imports
> compat: use import statements, not importlib

- tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.html
Summary:
This fixes a lint warning raised by the Google import bot.
Test Plan:
None.
wchargin-branch: hparams-fix-typo
> hparams: fix typo in comment

- tensorboard/summary/BUILD
- tensorboard/summary/_tf/__init__.py
- tensorboard/summary/_tf/summary/__init__.py
This change provides a package suitable for injection into TensorFlow's API generation as an API "component package" providing the `tf.summary` API.  It re-exports symbols from the original `tf.summary` module so that when used with `component_api_helper` from TensorFlow and inserted into the TF namespace, the effect is to overlay symbols from TensorBoard over the existing module.
The component package approach mitigates circular dependency issues (a risk because the TensorBoard ops in turn depend on TF) because the TF API __init__.py imports the core TF API symbols before it imports components, so if they in turn `import tensorflow` the module has been mostly initialized. It also means that TensorBoard needn't be importable at API generation time, only when TF is actually imported, which …
> Add summary/_tf/ package for providing tf.summary API component

- tensorboard/manager.py
- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/interactive_inference/utils/inference_utils.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
- tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
- tensorboard/plugins/interactive_inference/witwidget/version.py
Add custom prediction function support in colab and jupyter mode so it is easier to load non-TensorFlow models into WIT.
WITConfigBuilder now has a "set_custom_predict_fn" method to pass a python function for prediction purposes. Parts of notebook backend and inference_utils are updated to use the custom function when provided.
No UI changes.
Ran WIT Toxicity Text Model Comparison and WIT Model Comparison colabs with custom_predict_fn to verify the tool is getting inferences correctly. 
> Add support for custom prediction function in colab and jupyter notebook modes.

- tensorboard/components/tf_dashboard_common/tf-downloader.html
- tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Summary:
We have a `<tf-downloader>` element that provides CSV and JSON download
links alongside a run selector, but this element is actually unused.
This commit replaces the scalar plugin’s reimplementation, updating the
styling of `<tf-downloader>` to stay mostly consistent with the existing
UI. This will enable us to fix #1845 in a way that can work for other
download links, too.
Test Plan:
Observe that the UI is virtually identical (the only visible change is
that the vertical position of the dropdown menu has shifted slightly):
Check that the download links download identical files before and after
the change, with the same filenames except that the `run_` prefix has
been changed to `run-` for internal consistency.
wchargin-branch: scalars-tf-downloader
> scalars: use `tf-downloader` for download links

- tensorboard/pip_package/BUILD
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/summary/_tf/summary/__init__.py
These are two fixes so that the tf.summary API component package introduced in #1847 works properly for users when pip-installing the code.  (It already works internally in the non-pip-package variation.)
1) add the code to the TensorBoard pip package - this was just an oversight
2) fix the import logic used by the API component module to re-export symbols from the original tf.summary module, which was broken because the generated API structure of opensource TF is such that the original logic breaks
The fix for issue 2 isn't as clean as I would like, so I'm going to see if I can find a better way.  This is just to unbreak things.
> Make tf.summary API component package work in pip package land

- README.md
Summary:
Per <https://docs.travis-ci.com/user/status-images/>, via:
<https://docs.travis-ci.com/user/migrate/open-source-repository-migration#do-i-need-to-make-any-other-changes>
Test Plan:
The link resolves to a valid image, though it currently lists “unknown”
status; this is expected, as the status on https://travis-ci.com is the
same.
wchargin-branch: readme-ci-badge
> readme: update Travis badge to travis-ci.com

- tensorboard/plugins/core/core_plugin.py
- tensorboard/program.py
Summary:
This patch teaches TensorBoard about `--port=default` (which is the new
default value for `--port`). If `--port=default` is specified,
TensorBoard will attempt to bind to port 6006, just as prior to this
patch. If this fails, TensorBoard will try to bind incrementally to
ports 6007, 6008, …, giving up after 10 attempts.
If an explicit port is specified, TensorBoard will not try to search for
other ports; it will fail (as before) if it cannot bind. This is the
only way in which `--port=default` and `--port=6006` differ.
This patch also changes the behavior of one edge case, at least on
Linux. Prior to this patch, explicit port numbers were interpreted
modulo 65536 (TCP ports are u16s), so `--port=71542` and `--port=6006`
had the same behavior. It is now an error on all platforms …
> server: when no port is specified, try to find one

- tensorboard/program.py
Summary:
In response to [a helpful post-commit review from @nfelt][1].
Test Plan:
Most of the changes are non-functional. The wildcard address resolution
logic did change, but we don’t expect the behavior to. The test plan
from #1851 suffices, plus explicitly binding `--host` to each of
`localhost`, `"$(hostname)"`, `"$(hostname -s)"`, `127.0.0.1`, and `::`
to verify that each works.
[1]: https://github.com/tensorflow/tensorboard/pull/1851#pullrequestreview-204418466
wchargin-branch: port-search-revisions
> server: amend #1851’s port-crawling implementation

- tensorboard/summary/_tf/summary/__init__.py
This fixes issues with the import logic I already attempted to fix in #1852, which indeed worked in pip package land (mostly) but not internally.
Fixed:
- the "test import" of `tensorflow.compat.v2` has now been fixed so that it works internally as well as in pip package land
- in pip package land for TF 2.0, we now fall back to `tensorflow._api.v2` after `.v1`
- typo in the final `import *`, not that anything was getting that far anyway
I've tested the same changes against `tf-nightly`, `tf-nightly-2.0-preview`, and internal HEAD.
> Fix bugs in _tf/summary/__init__.py import logic for tf.summary

- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/graph/http_api.md
- tensorboard/plugins/graph/tf_graph_common/common.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_loader/BUILD
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
With TensorFlow v2, graph will be part of RunMetadata and will be
tagged. In order to keep the backwards compatibility, we established new
contract between graph plugin backend and frontend.
Reviewers: Due to changes in backend APIs, both BE and FE have to be updated at the same time. However, I have broken the changes down into two commits, one for BE and one for FE, for "easier review".
> Change graph plugin backend for v2 compatibility

- .travis.yml
- tensorboard/pip_package/build_pip_package.sh
This PR adds `bazel run //tensorboard/pip_package:build_pip_package` to our Travis CI testing script.
This will allow us to ensure the pip package builds and passes basic smoke tests as a presubmit check, which in turn unblocks adding minimal TF + TB integration testing for the tf.summary module (in a future PR).  The smoke tests run quickly - less than 30 seconds on my machine - and seem pretty stable, though they do launch the TB webserver very briefly so that's a potential source of flakiness.  If it proves too flaky we can look into maybe running just the non-webserver parts of the smoke testing.
In order to get the smoke test embedded in build_pip_package.sh to run appropriately in our Travis environment, using the Travis env's TF version and python version, I added some arguments …
> Test build_pip_package.sh on Travis

- tensorboard/BUILD
- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/default-plugins.html
- tensorboard/default.py
* Motivation for features / changes: Enable the HParams plugin in Tensorboard. HParams allows visualizations of experiments ran for hyperparameter tuning.
```
bazel test //tensorboard/plugins/hparams/...:all
bazel run //tensorboard/plugins/hparams:hparams_demo 
bazel run //tensorboard -- --logdir /tmp/hparams_demo 
```
and (briefly) verified manually that the plugins works as expected.
> Enable the hparams plugin

- tensorboard/main.py
This should fix #1566 by reverting #1489, which was unfortunately a misguided change on my part.  I thought that the env var was necessary in order to opt in to the C++ implementation because not all protobuf python distributions have the C++ implementation activated by default even if they include the appropriate extension.  Apparently this either was never true, or certainly hasn't been true since protobuf 3.5.1 (and we're already on 3.6.0).  And setting the env var is actively harmful when protobuf doesn't include the C++ extension because then it fails with the error in #1566.  (Protobuf should really provide a safe way to opt into the C++ implementation only if it is present, but they currently don't.)
I think I thought this was necessary because apparently when you `bazel build …
> Stop setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION env var

- RELEASE.md
- tensorboard/version.py
- Bump tb-nightly version to 1.14.x
- Cherrypick of 1.13.0 release notes back onto master
(Will be rebase-and-merged to keep the two logically separate commits.)
> Post release 1.13.0

- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/graphs_plugin_test.py
- tensorboard/plugins/graph/graphs_plugin_v2_test.py
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
This change pipes more data into the graph plugin that is persisted
on the TensorFlow's side with the new summary ops.
Also refactored the test a bit but it is hard to test anything
because the nightlies do not contain the required changes yet.
In a follow up changes, we will add test using more public APIs.
The PR as is contains #1873. Please review the last commit starting from 
face82a9.
> Graph plugin populates graph and RunMeta v2.

- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_info/tf-graph-icon.html
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
Few changes are:
- graph plugin assumed all GraphDefs are graph of ops.
Removed some checks on node.op but in the long run, we should have
a non-op mode and use something like MetaNode.
- Make sure correct GraphDef is loaded before loading a profile
information. RunMetadata or profile information is strongly associated
with a GraphDef. Though via the selection from the graph-control, we
always GraphDef before the profile, we want better protection in case
we make changes to the control without knowing this dependency.
> Support conceptual graph in graph plugin

- tensorboard/manager.py
Summary:
Fixes #1895 by replacing the (apparently unportable) `%s` format
specifier with an explicit subtraction from epoch.
Test Plan:
I don’t have easy access to a Windows machine with a Bazel/TensorBoard
setup, but I verified that this expression can be evaluated by itself:
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import datetime
>>> dt = datetime.datetime.now()
>>> dt.strftime("%s")
File "<pyshell#2>", line 1, in <module>
dt.strftime("%s")
ValueError: Invalid format string
>>> int((dt - datetime.datetime.fromtimestamp(0)).total_seconds())
1551203889
```
Running `git grep strftime.*%s` returns no matches as of this …
> manager: use portable epoch time computation

- .travis.yml
- WORKSPACE
- third_party/clutz.bzl
Summary:
Fixes #1903. Googlers are now locked to Bazel 0.23, which breaks
`rules_closure` unless we pull in HEAD (they’ve not yet had a release).
Conversely, `rules_closure` HEAD is broken on Bazel 0.21, so our CI
needs to be upgraded to match; Bazel 0.22 is the minimum working
version. Also, `rules_closure` had a breaking change in a package
called `private` whose default visibility is `public`, so our
`clutz.bzl` needs to be updated to work around that.
Test Plan:
Running `bazel build //tensorboard/... && bazel test //tensorboard/...`
passes on Bazel versions 0.22.0 and 0.23.0, failing on version 0.21.0.
Verified that the shasum matches the properly signed Bazel 0.22 binary:
```
$ gpg --verify ./bazel-0.22.0-linux-x86_64{.sig,}
gpg: Signature made Mon 28 Jan 2019 05:30:32 AM PST
gpg: …
```
> build: upgrade to Bazel 0.22, rules_closure HEAD

- docs/_index.yaml
Update the TensorBoard docs index page:
- Description includes brief itemization of some of TensorBoard's capabilities
- GIF shows some of TensorBoard's capabilities
- Adding a link to a Google AI blog on TensorBoard's WIT plugin
> Update the index page description and add a GIF

- tensorboard/plugins/audio/summary_test.py
- tensorboard/plugins/histogram/summary_test.py
- tensorboard/plugins/image/summary_test.py
- tensorboard/plugins/scalar/summary_test.py
- tensorboard/plugins/text/summary_test.py
This PR avoids flaky behavior in the way that eventfiles get read in the test cases for V2 summary ops, which in turn unblocks https://github.com/tensorflow/tensorboard/pull/1891 which otherwise needs to hack around the flakiness.
The implemented change is to fully encapsulate the creation of an eventfile as an implementation detail of the test helpers that construct V2 summary API `Summary` protos, and ensure that at most 1 eventfile is on disk at any given time by deleting it after we read it in.
---
Motivation: the summary API tests all use helpers that attempt to encapsulate the process of converting the API call into a resulting `Summary` protobuf.  For the V1 ops, this is easy because they're designed to produce this output directly.  For the V2 ops, there is no intermediate way to …
> Fix flaky eventfile usage in summary V2 tests

- docs/r2/what-if-tool.md
- tensorboard/compat/tensorflow_stub/io/gfile_s3_test.py
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
- tensorboard/plugins/interactive_inference/README.md
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/program.py
- overriden -> overridden
- programatically -> programmatically
- `@returns` -> `@return`
- the the -> the
- indicies -> indices
> Fixed various typos

- tensorboard/notebook.py
Summary:
The previous default height of 600px is okay for some dashboards but
particularly cramped for hparams. Through rigorous testing, we have
determined that 800px is a larger number.
Before and after screenshots of the hparams dashboard:
Test Plan:
Build a Pip package, upload it to Colab, run the hparams demo, take
screenshots above.
wchargin-branch: notebook-enlarge-default-height
> notebook: change default height to 800px

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
The profile dashboard now shows a “disabled” message on the frontend
when we detect that we’re running in a Colab notebook. See #1913.
This commit does _not_ cause the profile dashboard to be marked inactive
by the main TensorBoard UI. We might want to do that, but it’s less
straightforward: currently, the backend is responsible for telling the
frontend which plugins are active, and the backend can’t know whether
we’re running in Colab. As a quick hack, we could add special-case logic
in `tf-tensorboard.html` to check for the profile plugin specifically.
As a longer-term solution, we could let the `tf_tensorboard.Dashboard`
interface specify an `isActive` callback, defaulting to `() => true`.
[s]: https://user-images.githubusercontent.com/4317806/53541886-b83b1880-3ad0-11e9-9501-2 …
> profile: disable dashboard inside Colab

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
Not only is opening in new tabs a better user experience, it’s necessary
in notebook contexts so that we don’t try to load the GitHub docs in an
iframe, which would fail because GitHub sets `frame-ancestors 'none'`.
(When I tested #1914 in Colab, I instinctively Ctrl-clicked the link,
thus not hitting this issue.)
Test Plan:
Tested that in both Jupyter and Colab, clicking on a help link before
this change yields a white frame with a “Refused to display…” console
error, while after this change it opens the appropriate link in a new
tab.
Checked statically that each link has `rel="noopener" target="_blank"`:
```shell
$ <./tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html tee \
> >(grep 'href=' | grep -Fcv '<link') \
> >(grep -Fc 'rel="noopener"') \
> >(grep …
```
> profile: make help links open in new tabs

- docs/_project.yaml
This adds an announcement banner to the site: go/tfo-stage/tensorboard
The included `_project_included.yaml` lives in the main tf.org directory (which this directory gets imported into). (see: cl/236066165)
> Add project include file for banner

- tensorboard/pip_package/build_pip_package.sh
- tensorboard/summary/_tf/summary/__init__.py
This rewrite fixes the issue where `import tensorflow.compat.v2.summary as tf_summary` produced a module that included only the tensorboard-defined symbols and none of the TF-defined ones.  See the comments in the rewritten code for the detailed explanation of the new approach.
This PR also adds tests for importing `tf.summary` to our pip package smoke test (which runs on Travis as of #1883), so that there's at least some test coverage for this cross-package import quagmire.
> Rewrite the tf.summary import logic, this time with tests

- tensorboard/backend/event_processing/plugin_asset_util.py
- tensorboard/plugins/profile/BUILD
- tensorboard/plugins/profile/profile_demo.py
- tensorboard/plugins/profile/profile_plugin.py
- tensorboard/plugins/profile/profile_plugin_test.py
This fixes #500 by making the profile plugin use EventMultiplexer's plugin assets handling logic to find profile plugin data in arbitrarily deep logdir subdirectories, *as long as those subdirectories contain at least one tfevents file*.  It's an alternative to PR #1360.
The plugin assets system is deprecated, but the profile plugin data already matches the format expected by that system, and we don't have a better way yet to manage large blobs of plugin-specific data that are too big or unwieldy to want to shove into event files.
One complication here is that the profile plugin has a particular complex plugin assets usage pattern in its `plugins/profile` subdirectories.  Each such directory can itself contain multiple "runs" in the profile plugin terminology - not to be confused with …
> Make profile plugin use EventMultiplexer to find data in subdirectories

- tensorboard/plugins/graph/graphs_plugin.py
- tensorboard/plugins/graph/tf_graph_board/tf-graph-board.html
- tensorboard/plugins/graph/tf_graph_common/parser.ts
- tensorboard/plugins/graph/tf_graph_common/util.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
Few issues:
1. fetchPbTxt or XMLHTTPRequest invokes `onload` even in case of error.
2. Promise handling was weird
3. Graph plugin try/catched and returned None instead of letting the
route handle the error by responding with 400.
Test changes to catch these issues will come in follow up changes.
> Graph plugin: show graph fetch error properly

- tensorboard/plugins/histogram/summary_v2.py
We will change v2 name_scope to only have a name argument, no more values (since that makes no sense without a Graph and all). Hence this usage would break.
> Remove deprecated usage of name_scope

- tensorboard/plugins/profile/profile_demo.py
- tensorboard/plugins/profile/profile_demo_data.py
Summary:
We make this change because we have a bug in profile plugin that will be
triggered if logdir only contains trace data.
Test Plan:
Remove any old profile demo data, then regenerate the data and launch
TensorBoard:
```
$ rm -rf /tmp/profile_demo/
$ bazel run //tensorboard/plugins/profile:profile_demo
$ bazel run //tensorboard -- --logdir /tmp/profile_demo
```
Prior to this commit, this would have _appeared_ to work; now, it hangs
on the “Processing datasets” screen. Fix to come shortly.
> profile: update demo data to include trace-only run

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Summary:
The profile dashboard had an existing bug that was revealed by #1914:
the loading progress bar never actually finishes. Prior to #1914, you
could actually see the loading bar if you made your window narrow
enough:
This was because the prior version of the dashboard rendered the main
tool irrespective of whether the data had actually finished loading. As
of #1914, the “loading” and “active” states are mutually exclusive, so
instead of just having a zombie progress bar we actually block the view.
The cause of the bug is a promise that never resolves. (The executor
provided to the `Promise` constructor’s return value is ignored; only
the `resolve` and `reject` callbacks can fulfill a promise.)
This was not caught while testing #1914 because it cannot be reproduced
with the demo data …
> profile: fix loading progress behavior

- tensorboard/plugins/graph/tf_graph_common/parser.ts
- tensorboard/plugins/graph/tf_graph_common/test/parser-test.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
When GraphDef is empty, due to the bug in streamParse, we failed to
resolve or reject the promise.
Added a test and improved test a bit to add malformed pbtxt case, which
in turn required some additional code changes.
Will work on further UI improvements in follow up changes.
> Fix parser when GraphDef is empty

- docs/r2/graphs.ipynb
The link currently doesn't render correctly; it renders as
```
You may encounter a situation where you need to use the tf.function annotation
to ["autograph"]((https://www.tensorflow.org/r2/guide/autograph), 
```
> Fix link-breaking typo in docs/r2/graphs.ipynb

- RELEASE.md
- tensorboard/manager.py
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
- tensorboard/version.py
**Merge this pull request ONLY via rebase, NOT via squash or merge-commit.**
This PR cherry-picks #1898, #1900, #1914, #1922, and #1945 on top of the
1.13 tracking branch to form 1.13.1, per our plan in #1906.
Tested in Python 3 on Windows and in Python 2 on Linux: TensorBoard
starts, and the profile dashboard works (all tools) and is disabled if
you set `window.TENSORBOARD_ENV = {IN_COLAB: true}`, in which case the
help link opens in a new tab.
> Release 1.13.1

- RELEASE.md
One commit to round out the 1.13.1 release process: cherry-pick of
1.13.1 relnotes added to RELEASE.md.
> Post-release 1.13.1

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Summary:
This commit amends the comment added in #1601 per my subsequent
investigations. The generated SVG includes hash characters in the
`clip-path` attribute; Firefox interprets these as fragment specifiers,
truncating the SVG. The prior version of the comment speculated that the
issue was related to the length of the SVG, but there’s no evidence that
this is the case.
With this understanding, it’s easy to construct a [simple repro][1] to
confirm this behavior. In Firefox 61, a data-URI describing an SVG image
with a hash character is invalid in both an `img src` and an `a href`;
in Chrome pre-72, it’s fine in both, while Chrome 72 behaves the same as
Firefox. Firefox and Chrome also differ in their handling of newlines in
the non-encoded data-URI; Chrome includes the newlines (except …
> scalars: document why SVGs are base64-encoded

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Data uri in the link for download has given us some trouble with
encoding and length limitations. We want to use the ObjectURL like
PR #1610 that is more durable to aforementioned limitations.
Tested this on Chrome 72 & 74, Firefox 65, and Safari.
> scalar: use ObjectURL for SVG link for durability

- tensorboard/lazy.py
- tensorboard/lazy_test.py
Summary:
This is not likely to be a problem in practice, but we might as well do
the safe thing when comparing to a sentinel.
Test Plan:
Unit test added, for good measure.
wchargin-branch: lazy-sentinel-is
> lazy: check sentinel identity with `is`, not `==`

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Summary:
This reverts commit e46bab98da5b2369d96721758c50c01b23a2ec83.
A Google-internal check objects to that PR on the grounds that object
URLs can induce XSS vulnerabilities. Googlers, see <http://b/128425516>.
Test Plan:
Downloading the chart still works, in both Chrome 72 and Firefox
60.5.1esr.
wchargin-branch: revert-1979
> Revert "scalar: use ObjectURL for SVG link for durability (#1979)"

- tensorboard/plugins/beholder/beholder.py
Summary:
This reverts part of #1911. Tests seem to pass either way (on both
mainline nightly and the 2.0 preview), but the `tf.estimator` form
works better inside Google.
Test Plan:
Running `bazel test //tensorboard/...` passes on both Python 2 and
Python 3, with both tf-nightly-2.0-preview==2.0.0.dev20190312 and the
same version of tf-nightly.
Importing this tree into Google yields a working TensorBoard.
wchargin-branch: beholder-estimator-via-tf
> beholder: use estimator from `tf.estimator`

- tensorboard/BUILD
- tensorboard/__init__.py
- tensorboard/lib_test.py
Summary:
Fixes #1989 (also described in a new comment in `__init__.py`).
This will require a Google-internal sync change: <http://cl/238144308>.
Test Plan:
Regression test added. It fails before this change in Python 2 and 3,
and passes after this change in both as well. The <http://cl/238144308>
test plan also passes.
wchargin-branch: reload-tensorboard
> init: fix top-level module reloading

- tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
1 as a smoothing factor always leads to a constant value of 0 being plotted.
0.999 is the actual highest value you can select for meaningful smoothing.
> Change maximum smoothing factor from 1 to 0.999.

- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/projector/__init__.py
Not sure how I missed this, but we need to use `tensorboard.compat` for the TensorFlow dependency in the projector plugin. Saw this failure when attempting to use internally.
cc @nfelt @wchargin
> Use tensorboard.compat for tf in projector plugin

- tensorboard/plugins/projector/vz_projector/vz-projector-metadata-card.html
Bug with long strings presentation in metadata card. 
Only two css classes were changed. 
Before fix:
After fix:
Just put long strings in metadata
> Fix with long words in projector metadata card

- tensorboard/plugins/graph/BUILD
Summary:
Supersedes internal <http://cl/238681208>.
Test Plan:
Running `bazel test //tensorboard/plugins/graph/...` still passes.
wchargin-branch: 238681208-deps
> build: split `py_test` to avoid deps on binary

- tensorboard/__init__.py
- tensorboard/pip_package/build_pip_package.sh
Summary:
Resolves #2020. The `__version__` attribute meets the specifications set
forth in [PEP 396].
[PEP 396]: https://www.python.org/dev/peps/pep-0396/
Test Plan:
The newly modified smoke test still passes; manually verified that the
new `__version__` attribute has the right value.
wchargin-branch: export-version
> lib: export `version` and define `__version__`

- .travis.yml
- tensorboard/plugins/audio/BUILD
- tensorboard/plugins/custom_scalar/BUILD
- tensorboard/plugins/distribution/BUILD
- tensorboard/plugins/graph/BUILD
- tensorboard/plugins/histogram/BUILD
- tensorboard/plugins/image/BUILD
- tensorboard/plugins/pr_curve/BUILD
- tensorboard/plugins/projector/BUILD
- tensorboard/plugins/projector/projector_plugin_test.py
- tensorboard/plugins/scalar/BUILD
- tensorboard/plugins/text/BUILD
Continuation of https://github.com/tensorflow/tensorboard/pull/1663
This adds plug and TensorFlow compat tests both locally running and in Travis CI.
cc @nfelt, @lanpa 
All the tests can be run with
```
bazel test //tensorboard/compat/proto:proto_test --test_output=errors
bazel test //tensorboard/compat/tensorflow_stub:gfile_test --test_output=errors
bazel test //tensorboard/compat/tensorflow_stub:gfile_s3_test --test_output=errors
bazel test //tensorboard/plugins/audio:audio_plugin_notf_test --test_output=errors
bazel test //tensorboard/plugins/custom_scalar:custom_scalars_plugin_notf_test --test_output=errors
bazel test //tensorboard/plugins/distribution:distributions_plugin_notf_test --test_output=errors
bazel test //tensorboard/plugins/graph:graphs_plugin_notf_test …
```
> Add plugin and compat tests for tensorboard-notf

- tensorboard/components/tf_runs_selector/tf-runs-selector.html
- tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.html
I also fixed a bug in tf-runs-selector that caused flakiness in the integration tests:
The 'dataLocation' property wasn't being updated, which caused the scalars PageObject to fail to find
the 'data-location' div.
@stephanwlee, @wchargin please take a look.
Thanks.
> Minor changes to make integration tests work.

- tensorboard/plugins/interactive_inference/utils/platform_utils.py
Summary:
tensorflow/tensorflow#26676 removed `tf.io.TFRecordCompressionType`,
which our tests used; `tf-nightly-2.0-preview==2.0.0.dev20190319` was
the first version without this symbol.
Fixes #2035.
Test Plan:
All tests pass on `tf-nightly-2.0-preview==2.0.0.dev20190321` and also
on `tf-nightly==1.14.1.dev20190321`.
wchargin-branch: fix-tf26676-failures
> Fix `TFRecordCompressionType` test failures

- tensorboard/plugins/hparams/BUILD
Needed to allow "packaging" these public binaries from other BUILD packages.  
@wchargin please take a look.
Thanks!
> Added public visibility to binary HParams targets

- tensorboard/plugins/graph/keras_util.py
Summary:
Fixes #2051. This cherry-picks part of Google-internal cl/239834276 to
fix a change made in TensorFlow 90f1ed7cd3ae167b60c1b0acc6f45af454c8d592
that first appeared in the 20190323 nightly.
Test Plan:
Running `bazel test //tensorboard/plugins/graph:keras_util_test` fails
before this patch but passes after it, on tf-nightly-20190325-py2.7.
wchargin-branch: fix-2051
> graph: bring keras_util.py up to date with TF

- tensorboard/manager.py
- tensorboard/manager_test.py
- tensorboard/notebook.py
- tensorboard/program.py
Summary:
Fixes #2017. I’ve spent multiple hours on multiple weekends trying to
figure out how to get Python `datetime`s to properly (a) count seconds
since the epoch and (b) serialize and deserialize properly on all
platforms and all Python versions. I have failed. If nothing else, I can
trust in `int`s.
This is a backward-compatible change: the data format on disk is
unchanged, and the only APIs with incompatible changes were always
explicitly marked as private.
Test Plan:
In addition to running `//tensorboard:manager_e2e_test`, I built a Pip
package and exercised the full notebook workflow in Jupyter (magic
invocation plus `tensorboard.notebook` API) in Python 2 and 3.
wchargin-branch: bare-int-times
> manager: switch from `datetime` to bare timestamps

- .travis.yml
- docs/r2/graphs.ipynb
- docs/r2/hyperparameter_tuning_with_hparams.ipynb
- tensorboard/tools/docs_list_format_test.sh
Summary:
The Google-internal Markdown processor, which renders our docs site,
requires that lists be preceded by a blank line. This is [nonstandard],
so the previews shown in GitHub and even Colab itself look fine, but the
docs site does not:
This patch fixes up our notebooks to accommodate to the stricter style.
Test Plan:
Regression test added. Before this change, running the new test outputs
```
docs/r2/graphs.ipynb:413:        "*   Define and annotate a function with `tf.function`\n",
docs/r2/graphs.ipynb:416:        "*   With a Summary file writer, call `tf.summary.trace_export()` to save the log data\n",
docs/r2/hyperparameter_tuning_with_hparams.ipynb:85:        "1. Experiment setup and HParams summary\n",
docs/r2/hyperparameter_tuning_with_hparams.ipynb:510:        "- Filter which …
```
> docs: fix list rendering

- tensorboard/plugins/hparams/hparams_demo.py
Summary:
Fixes #1564. Supersedes #1565 by using Unicode strings in both Python
versions, rather than using bare literals and only sometimes explicitly
encoding them.
Test Plan:
Running `bazel run //tensorboard/plugins/hparams:hparams_demo` now
passes in both Python 2 and Python 3, whereas prior to this commit it
passed in Python 2 but failed with “TypeError: Unicode-objects must be
encoded before hashing” in Python 3.
wchargin-branch: hparams-demo-unicode
> hparams: fix demo Unicode handling in Python 3

- third_party/clutz.bzl
It is deprecated from 0.24.0 on March 26, 2019.
Fixes #2059
> Remove deprecated usage of Bazel FileType

- third_party/clutz.bzl
Per [1]: we follow new depset(transitive=[])
https://github.com/bazelbuild/bazel/blob/master/site/docs/skylark/skylint.md#using-the-operator--on-depset-deprecated-plus-depset
Addresses #2071
> Address deprecated depset+depset

- tensorboard/program.py
Summary:
This resolves a piece of technical debt that was convenient but not
robust to implementation changes in Werkzeug and the Python standard
library. When searching for ports, instead of calling superclass
initializers multiple times until they succeed, we create new server
objects (each with a single port) multiple times until one is
successfully initialized. Each object’s initializer chain is invoked
only once.
The mechanism provides a `with_port_scanning` factory that is agnostic
to the actual server implementation.
This commit is easier to review when ignoring whitespace changes.
Test Plan:
Spawn 11 TensorBoard processes without specifying a port; e.g.:
```
$ bazel build //tensorboard
$ for in in {1..11}; do
> ./bazel-bin/tensorboard/tensorboard --logdir /tmp/whatever &
> done; …
```
> program: initialize server objects exactly once

- third_party/js.bzl
Since we're pulling [`umap-js`](https://github.com/PAIR-code/umap-js) into Google3, I rebuilt the minified bundle to be better compatible with reimport. This PR simply upgrades the bazel dependency to the newest (1.0.4) version of that built bundle (functionally equivalent)
> Update to latest build of umap.js

- tensorboard/plugins/beholder/BUILD
- tensorboard/plugins/beholder/beholder_test.py
- tensorboard/plugins/beholder/im_util.py
Summary:
This reverts part of #1734 to fix #2073. A change to the TensorFlow APIs
added a static shape requirement, but Beholder’s image resizer operates
on images whose size is not statically known.
Test code adapted from @comzyh’s MWE in #2073—thanks!
Test Plan:
Added a unit test, which has the correct pass/fail behavior on current
`tf-nightly` and TensorFlow 1.13.1. The test does not run in TF 2.0,
because Beholder depends on sessions.
wchargin-branch: fix-2073
> beholder: fix image resizing

- .travis.yml
- tensorboard/BUILD
- tensorboard/compat/tensorflow_stub/BUILD
- tensorboard/pip_package/build_pip_package.sh
- tensorboard/summary/BUILD
Continuation of work for https://github.com/tensorflow/tensorboard/issues/2027 and ultimately removing the `TENSORBOARD_NO_TF=1` environment variable.
Plugins tests aren't run yet, but this confirms that build and limited tests run without TensorFlow installed.
> Add separate non-TensorFlow test run in Travis CI

- tensorboard/plugins/graph/tf_graph_common/parser.ts
- tensorboard/plugins/graph/tf_graph_common/test/parser-test.ts
A repeated field in Graph proto definition requires an entry in the
parser.ts to parse the text proto correctly. It was not only missing
entries for FunctionDefLibrary but also missed ones for few properties.
Do note that we did not encounter issues because we do not make use of
most of the properties.
Fixes #2062
> graph: sync parser config to proto counterpart

- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/compat/__init__.py
- tensorboard/compat/tensorflow_stub/__init__.py
- tensorboard/plugins/debugger/debugger_plugin_testlib.py
- tensorboard/plugins/debugger/events_writer_manager.py
- tensorboard/plugins/projector/projector_plugin.py
Update TensorBoard to import pywrap_tensorflow from tensorflow.python instead of tensorflow.compat.v1. We are removing pywrap_tensorflow from TF API including tf.compat.v1. Importing from tensorflow.python is a temporary solution until a better API for reading records is available for TensorBoard to use.
tensorboard/compat/__init__.py now includes a function _pywrap_tensorflow to access either actual or stub pywrap_tensorflow implementation.
bazel test //...
I verified that the only tests that fail also fail on master without my change.
> Update TensorBoard to import pywrap_tensorflow from tensorflow.python

- tensorboard/plugins/hparams/tf_hparams_session_group_details/tf-hparams-session-group-details.html
This is needed to solve b/111691396 as well as make the UI more deterministic which aids integration tests (without this, occaisonally and non-predictably the charts do not reset).
> Making session group detail reset after data change

- tensorboard/BUILD
- tensorboard/backend/BUILD
- tensorboard/backend/application_test.py
- tensorboard/backend/http_util_test.py
- tensorboard/backend/json_util_test.py
- tensorboard/manager_test.py
- tensorboard/plugin_util_test.py
- tensorboard/program_test.py
- tensorboard/test.py
- tensorboard/util/BUILD
- tensorboard/util/platform_util_test.py
- tensorboard/util/test_case.py
Continuation of work for #2027 and ultimately removing the TENSORBOARD_NO_TF=1 environment variable.
Pulled out of https://github.com/tensorflow/tensorboard/pull/2075 and still need to fix some Python 3 vs 2 issues.
Tested with
```
bazel test //tensorboard:manager_test --test_output=errors
bazel test //tensorboard/backend:application_test --test_output=errors
```
> Enable more tests in notf case for Travis CI

- tensorboard/plugins/audio/summary_v2.py
- tensorboard/plugins/histogram/summary_v2.py
- tensorboard/plugins/hparams/hparams_util.py
- tensorboard/plugins/image/summary_v2.py
- tensorboard/plugins/scalar/summary_v2.py
- tensorboard/plugins/text/summary_v2.py
This updates TensorBoard's usage of `tf.summary.summary_scope()` and `tf.summary.import_event()` in TF 2.0 in anticipation of a change to those APIs, which moves the functionality under `tf.summary.experimental` and in the case of `import_event()`, also changes it to import `tf.compat.v1.Summary` proto bytes instead of `Event` protos.
Fallback logic is included so we stay compatible with TF versions that don't have this change, including current tf-nightly as of sending this PR.  I've filed https://github.com/tensorflow/tensorboard/issues/2109 to track cleaning up those fallbacks before TF 2.0 final.
Tested by confirming tests pass both before the TF change (as this PR is sent) and after (with the change made locally).  I also manually tested the `hparams_util` helper binary since the …
> Update TF 2.0 summary_scope()/import_event() usage

- tensorboard/backend/event_processing/event_file_loader.py
- tensorboard/compat/tensorflow_stub/__init__.py
Summary:
Fixes #2115 in response to:
<https://github.com/tensorflow/tensorflow/commit/ea3f474c5ff94152f72b5417eff2046111bb77e3>
The other two symbols deprecated in that commit are not used by
TensorBoard.
We alias `compat.v1.errors = errors` from the TensorFlow stub so that
notf tests can continue to work.
Test Plan:
All Bazel tests pass in `tf-nightly-2.0-preview==2.0.0.dev20190416`, and
the Pip package smoke test also passes.
wchargin-branch: fix-tf-status-handling
> Use `raise_exception_on_not_ok_status` from V1

- docs/r2/get_started.ipynb
"module `tensorboard.notebook `  not found"
It uses the whole line to determine the module name, including the space.
Fix this to work in Jupyter.
Remove bad whitespace.
None.
Run this notebook in OSS jupyter notebook.
None
> Fix whitespace: this breaks running in jupyter.

- docs/r2/get_started.ipynb
- docs/r2/graphs.ipynb
- docs/r2/hyperparameter_tuning_with_hparams.ipynb
- docs/r2/image_summaries.ipynb
- docs/r2/scalars_and_keras.ipynb
- docs/r2/tensorboard_in_notebooks.ipynb
- tensorboard/__init__.py
- tensorboard/notebook.py
Summary:
“Drop the `.notebook`. It’s cleaner.” (Fixes #1857.)
Using `%load_ext tensorboard.notebook` now gives users a helpful error.
This is a breaking change, which we think is okay because (a) notebook
support was always explicitly marked as “alpha” in release notes and
“experimental” in the code, and (b) notebooks are meant to be run
interactively, so the fix will be easy and immediate.
Test Plan:
Built the Pip package and installed it into a new virtualenv, then
verified that `%load_ext tensorboard.notebook` properly emits an error
message, which directs users to the working `%load_ext tensorboard`:
Tested the above with `tf-nightly` and `tf-nightly-2.0-preview`. Also
verified that the `getting_started.ipynb` notebook still works, from
start to finish, within the new virtualenv. …
> notebook: relocate to `%load_ext tensorboard`

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/plugins/hparams/api.proto
- tensorboard/program.py
* Issue was related to this change
* Added version flag in main
Issue #2087
> print version with `tensorboard --version`

- .travis.yml
Summary:
Due to <https://github.com/tensorflow/tensorflow/issues/27955>.
This unblocks our CI until tomorrow’s nightlies are pushed.
Test Plan:
Fingers crossed.
wchargin-branch: pin-20190417-nightly
> ci: pin to non-broken nightlies

- .travis.yml
Summary:
This reverts commit 54eb0bc882e03afa56d0a07024f87720a19ec7c8.
Test Plan:
CI suffices.
wchargin-branch: unpin-20190417-nightly
> ci: unpin 2019-04-17 nightlies

- tensorboard/manager.py
- tensorboard/manager_test.py
Summary:
Fixes #2010.
This patch is primarily directed at Unices. On Windows, the underlying
problem should not be an issue, because the default temporary directory
seems to be user-scoped (e.g., `C:\Users\wchargin\AppData\Local\Temp`).
Test Plan:
Unit tests added. Before this change, the first test has an assertion
error (`'0o755' != '0o777'`) and the second test has an I/O error trying
to write to a non-writable directory. After this change, all tests pass.
Tested only on Linux.
wchargin-branch: info-dir-mode
> manager: make TensorBoardInfo directory universally accessible and useful

- .travis.yml
- tensorboard/BUILD
- tensorboard/backend/BUILD
- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/interactive_inference/BUILD
- tensorboard/plugins/interactive_inference/utils/BUILD
- third_party/mock.BUILD
- third_party/python.bzl
Summary:
We’ve heretofore used the `mock` library without telling Bazel about it.
This isn’t generally a problem when `tensorflow` is installed in the
same virtualenv, because `tensorflow` pulls in `mock`. But tests that
don’t depend on TensorFlow have no build edge to `mock` when imported
into google3’s build system, causing build failures after syncing. This
commit makes the `mock` dependency explict.
We use `mock==1.0.0` rather than the current version (2.0.0) because the
current version depends on `pbr` at runtime in a way that does not play
well with Bazel: <https://github.com/testing-cabal/mock/issues/383>
(It appears to be trying to find some globally registered `setup.cfg`
file from which to read a version identifier.) Rather than vendoring and
patching `mock`, declaring a fake …
> build: register `mock` dependency with Bazel

- docs/r2/tensorboard_in_notebooks.ipynb
Summary:
Closes tensorflow/tensorflow#27304, wherein a user noted difficulty
using the TensorBoard notebook extensions with Jupyter installed as a
user-level site package rather than in the virtualenv.
Test Plan:
Uploaded this notebook to Colab; the Markdown renders properly:
wchargin-branch: docs-jupyter-path
> docs: describe PATH requirements for Jupyter

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/api.py
- tensorboard/plugins/hparams/api_test.py
- tensorboard/plugins/hparams/hparams_demo.py
Summary:
This change introduces `HParam`, `Metric`, and `Experiment` classes,
which represent their proto counterparts in a more Python-friendly way.
It similarly includes a `Domain` class hierarchy, which does not
correspond to a specific proto message, but rather unifies the domain
variants defined on the `HParamInfo` proto.
The design is roughly as in the original sketch of #1998.
The primary benefit of this change is that having first-class domains
enables clients to reuse the domain information for both the experiment
summary and the underlying tuning algorithm. We don’t provide a method
to do this out of the box, because we don’t actually provide any tuners
at this time, but it’s easy to write (e.g.) a `sample_uniform` function
like the one included in this commit. Then, sampling is …
> hparams: add Python layer for hparams and metrics

- tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
External customer requested to add full TensorFlow name in the details card.
The node.xla.provenance has the full name, it is just we didn't show it.
```sh
bazel run tensorboard/plugins/profile:profile_demo
bazel run tensorboard:tensorboard -- --logdir=/tmp/profile_demo
```
N/A
> Add TensorFlow full name in op profile details card.

- tensorboard/components/tf_backend/requestManager.ts
- tensorboard/components/tf_backend/test/requestManagerTests.ts
RequestManager is a thin wrapper around XMLHttpRequest and fetch.
Unfortunately, for some convenience of plugin authors, XMLHttpRequest
version hide away certain control over the request or response. For
fetch API, we would like to keep it as true to the real browser API
while giving it feature of automatic retries and request queuing.
Motivation: it enables clients to interpret responses as array buffers,
plain text, etc., rather than only JSON. This is helpful for performance
reasons: you can send binary blobs without having to JSON-over-base64
encode them on the server.
> Support browser fetch with retry/queue 

- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
Commit 95d729f caused regression by not clearing the `items` before
pushing onto it.
Fixes #2123.
> Beholder: fixed infinite growing items issue.

- tensorboard/components/tf_tensorboard/BUILD
- tensorboard/components/tf_tensorboard/plugin-dialog.html
- tensorboard/main.py
- tensorboard/plugins/beholder/tf_beholder_dashboard/BUILD
- tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
- tensorboard/plugins/debugger/debugger_plugin_loader.py
- tensorboard/plugins/hparams/tf_hparams_dashboard/BUILD
- tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.html
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/BUILD
- tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
- tensorboard/plugins/profile/tf_profile_dashboard/BUILD
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Adding a popup dialog for when plugins are not created. Note that this is different from being "inactive", which can be due to data, etc.
Fixes #2027 
Everything should be good to go and I've tested on my Mac with the following:
```
conda create --name tfpy36 python=3.6
conda activate tfpy36
pip install --upgrade pip
pip install tf-nightly-2.0-preview
conda install protobuf
conda install absl-py
conda install numpy
bazel build tensorboard
./bazel-bin/tensorboard/tensorboard --logdir ~/local/sample_runs/runs
conda create --name notf python=2.7
conda activate notf
pip install --upgrade pip
pip install scipy
conda install protobuf
conda install absl-py
conda install numpy
bazel build tensorboard
./bazel-bin/tensorboard/tensorboard --logdir ~/local/sample_runs/runs
```
cc @lanpa, @nfelt
> Add popup dialog for plugins that require TensorFlow

- tensorboard/plugins/profile/pod_viewer/stack_bar_chart/stack-bar-chart.ts
The 'rect' and 'text' elements should be appended to individual labels rather than the top group of all legends.
> Fix a bug that legend of the stack bar chart was missing.

- third_party/python.bzl
Security Vulnerability
Urllib3 version 1.24.1 and earlier have an issue with certificate handling. Details in:
https://nvd.nist.gov/vuln/detail/CVE-2019-11324
This Pull Request updates urllib3 to the latest version (1.25). No other changes.
Update the effected package (urllib3) to the latest version, which contains the fix
no UI changes
Updated .bzl file, rebuilt, started TensorBoard
N/A
> Update urllib3 for CVE-2019-11324

- tensorboard/plugins/core/core_plugin.py
- tensorboard/plugins/core/core_plugin_test.py
- tensorboard/program.py
The `--version` flag introduced in #2097 unfortunately conflicts with a non-optional Google-internal `--version` flag.  By renaming it `--version_tb` we avoid the conflict, while still allowing the flag to be used like `tensorboard --version` because argparse auto-expands unambiguous flag prefixes.
> rename --version flag to --version_tb to avoid conflict

- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
https://github.com/tensorflow/tensorboard/issues/2090
Show the capture profile button when no data is found. Modify the FAQs to both TPU and CPU/GPU.
Before:
After:
bazel run tensorboard:tensorboard -- logdir=.
http://localhost:6006/#profile
> Show "capture profile" button in the profile plugin even if there is no profile data.

- tensorboard/plugins/projector/projector_plugin.py
Further progress on #1718 - TF now issues deprecation warnings for compat v1 usage, and this is the last one that is triggered just from running the `tensorboard` binary (using TB V1 summary APIs also triggers them, but that's less of an issue).
> replace deprecated tf.compat.v1.train.checkpoint_exists()

- third_party/js.bzl
This adds a download target for node.js ppc64le. Support for ppc64le was added in rules_closure with this commit: https://github.com/bazelbuild/rules_closure/commit/87d24b1df8b62405de8dd059cb604fd9d4b1e395
This becomes a simple and safe add to allow building on ppc64 without any patches.
sha256_urls_extract_ppc64le target added to the js.bzl file
No UI Changes
rebuilt Tensorboard; install; start Tensorboard
N/A
> Add node.js target for ppc64le architecture

- tensorboard/summary/_tf/summary/__init__.py
This adds a friendlier docstring to the `_tf/summary` module that TF 2.0 re-exports as `tf.summary`, which is also the source for the [tf.summary generated API documentation](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/summary).  I've included minimal API usage examples for all three expected execution contexts, and verified that all three can be executed properly with the latest tf-nightly-2.0-preview [1].
The comments about the component module implementation details I've moved into an actual comment so they don't appear in the API docs.
[1] ok, this is not quite true yet for the third example, but it should hopefully be true tomorrow, and I'll hold off on merging until then.
> add user-friendly docstring for TB-provided tf.summary module

- tensorboard/plugins/graph/tf_graph_app/tf-graph-app.html
- tensorboard/plugins/graph/tf_graph_common/BUILD
- tensorboard/plugins/graph/tf_graph_common/graph.ts
- tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
- tensorboard/plugins/graph/tf_graph_common/loader.ts
- tensorboard/plugins/graph/tf_graph_common/tf-graph-common.html
- tensorboard/plugins/graph/tf_graph_common/util.ts
- tensorboard/plugins/graph/tf_graph_dashboard/BUILD
- tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
- tensorboard/plugins/graph/tf_graph_loader/BUILD
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.html
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
- tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts
tf-graph-control, being inside graph plugin, changed recently to work
better with other graph components like tf-graph-controls. More
specifically, the problem happen because the tf-graph-loader was
refactored to take `selection` as the primary input to the loader and
it used run & type of graph selected by user to fetch appropriate data.
This contrasts with previous input `datasets` which took a `path` as an
input which loader used to fetch the data from. tf-graph-app and
tf-debugger-dashboard plugin were using the datasets prop to pass in
the special endpoint where the data lives.
Before describing refactor, we should define what the tf-graph-loader
should be. The loader is a UI-less functional component (renders no DOM;
uses lifecycle method and props to provide some functionality) …
> Fix graph-loading for tf-graph-app and tf-debugger

- tensorboard/plugins/audio/summary_test.py
- tensorboard/plugins/audio/summary_v2.py
TF's upcoming 1.14 release (and current nightlies) expose a `tf.audio` module with `encode_wav()` and `decode_wav()`, so when these are available we can use the symbols from there instead of `gen_audio_ops` which is not part of the public API, and which was used only as an interim fix for TF 2.0 compatibility since the old solution (`tf.contrib.ffmpeg.encode_audio`) is not present in TF 2.0 at all.
See https://github.com/tensorflow/tensorboard/issues/1705 for migrating other parts of the APIs/tests off of `tf.contrib.ffmpeg.encode_audio` which remains to be done.
Tested by running `summary_test` against both `tf-nightly` and TF 1.13, which lacks `tf.audio`.
> use tf.audio for encode/decode_wav if available

- tensorboard/summary/BUILD
- tensorboard/summary/tf_summary_test.py
This adds a new python-based integration test that for TF 2.0, the Tensorboard-provided symbols are successfully exported under `tf.summary`.  We already have tests for this in build_pip_package.sh, but that only runs regularly in our Travis CI, whereas this python test easily can run wherever our python tests run, including our internal CI (which I verified with a test sync).
This should help avoid issues like https://github.com/tensorflow/tensorflow/issues/28027.
> add new test for exporting TB symbols under tf.summary

- tensorboard/components/tf_tensorboard/plugin-dialog.html
- tensorboard/plugins/profile/profile_plugin_loader.py
- tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
In testing TensorBoard for PyTorch in Colab I saw an error when running
```
!pip install -q torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
!pip install -q tb-nightly
%load_ext tensorboard 
%tensorboard --logdir pytorch_logs
```
The error was
```
ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
File "/usr/local/bin/tensorboard", line 10, in <module>
sys.exit(run_main())
File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 77, in run_main
sys.exit(tensorboard.main())
File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 228, in main
server = self._make_server()
File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 309, in _make_server …
```
> Add extra import check for profile plugin

- tensorboard/plugins/hparams/api_test.py
Summary:
This test case already contains actual TensorFlow code. Within Google,
such tests must be run via `tf.test.main()` or `absltest.main()`, and
the TensorFlow-specific code should be in a `tf.test.TestCase` as well
(though this is not strictly required).
Test Plan:
Verified that this patch fixes a test that’s broken when syncing into
Google3.
wchargin-branch: tf-test-api-test
> build: use `tf.test.main` for `hparams:api_test`

- tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
In my case the image is too big I suppose it's 1920x640.
After clicking:
I let it scroll.
But it's not that visually pleasing totally.
I'm not sure how to make it more beautiful, but the current fix works perfectly for me. Hope it helps.
> feat: enable scrolling when added large image

- tensorboard/components/vz_example_viewer/vz-example-viewer.html
- tensorboard/components/vz_example_viewer/vz-example-viewer.ts
WIT's example viewer textarea's had incorrect border styling.
Added css rules to not use the -appearance rules for textareas and instead allow our custom styling
Reorganized existing rules around these elements to be a little simpler
Ran demos, saw correct visuals
> Fix WIT textarea border issue

- tensorboard/plugins/hparams/BUILD
- tensorboard/plugins/hparams/summary_v2.py
- tensorboard/plugins/hparams/summary_v2_test.py
Summary:
We reimplement `hparams_config` in terms of a new `hparams_config_pb`,
which has no direct dependencies on TensorFlow. The `metadata` module
unfortunately still emits TensorFlow protos, so there is still a
transitive dependency.
Note that this duplicates a small bit of logic from `summary`. We don’t
reimplement `summary` in terms of `summary_v2`, because we intentionally
provide a smaller API in `summary_v2` (e.g., we omit experiment name and
owner, which are unused). It is thus not possible to implement the full
functionality of `summary` in terms of `summary_v2`.
Test Plan:
Existing unit tests suffice for coverage, and also updated to test the
new endpoint explicitly.
wchargin-branch: hparams-config-pb
> hparams: add (mostly-)notf `hparams_config_pb`

- tensorboard/plugins/hparams/api.py
Summary:
This should have been in #2174.
Test Plan:
That unit tests pass is sufficient. We don’t have demos that exercise
this endpoint. (The implementation is tested in `summary_v2_test`.)
wchargin-branch: hparams-config-pb-export
> hparams: expose `hparams_config_pb` from `api`

- docs/r2/hyperparameter_tuning_with_hparams.ipynb
- docs/r2/tensorboard_in_notebooks.ipynb
Summary:
Follow-up to #2118, surfaced in a thread on tensorflow-testing:
<https://groups.google.com/a/tensorflow.org/d/msg/testing/Dh_kAR8omg8/Y5rLELCSAgAJ>
These notebooks work fine in Colab, but apparently break in Jupyter.
Test Plan
Running `git grep 'load_ext.* "'` yielded two matches before this commit
and zero matches after.
wchargin-branch: load-ext-whitespaces
> docs: fix more trailing whitespace in `%load_ext`s

- tensorboard/plugins/hparams/BUILD
When a Python module imports tensorflow, it needs to explicitly define
dependency to TensorFlow in the BUILD file. This unblocks internally
sync.
> hparams: Add explicit TF dependency

- third_party/js.bzl
bzl macros require docstring and missing it would violate the linter.
> Add docstring to tensorboard_js_workspace

- tensorboard/plugins/mesh_visualizer/tf_mesh_dashboard/mesh-loader.js
This PR depends on fixes to mesh-viewer.js.
NOTE: I'll update the PR once I have up to date SHA's for updated js files in tf-graphics repo.
> Pass runColor to mesh viewer

- tensorboard/pip_package/BUILD
- tensorboard/plugins/hparams/BUILD
Summary:
Previously, `hparams.summary` was available via a “fake” dependency of
`:hparams_plugin`. We replace that fake dependency with a “public API”
target, as used by Beholder and the projector.
Test Plan:
Cherry-pick #2188, then:
```
$ bazel run //tensorboard/pip_package:build_pip_package -- --no-smoke
$ PATH_TO_PY3_WHEEL=...  # last line of command output
$ cd "$(mktemp -d)"
$ virtualenv -q -p python3.5 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview
(ve) $ pip uninstall -q -y tb-nightly
(ve) $ pip install "${PATH_TO_PY3_WHEEL}"
(ve) $ python
>>> from tensorboard.plugins.hparams import api
>>> from tensorboard.plugins.hparams import plugin_data_pb2
>>> pb = api.hparams_pb({"optimizer": "adam", "magic": True})
>>> content = …
```
> hparams: add `api` and `summary_v2` to Pip package
